### ISSUE TITLE
About nil sid in "connect" event callback

### ISSUE THREAD

**Issue by hankbao** [socketio/socket.io-client-swift#100]
in "connect" event callback, `sid` of `SocketIOClient` may be nil in some circumstance. I'm not sure if that's a bug caused by some race conditions or it's designed to work that way. Any information would be appreciated. Thanks.

**Comment by nuclearace** [comment]
That's weird, I'm not exactly sure what could cause that. I'll try making a small change to master.

**Comment by hankbao** [comment]
I encountered this issue on one of my iOS projects recently. I close the socket.io client with fast set to true when the app enters background and recreate another one when the app enters foreground and then connect to the server immediately. In the connect event callback, I need to send the client sid to the server. Normally the sid is there. However in some rare condition, it could be nil.

**Comment by nuclearace** [comment]
@hankbao Have you tried the latest master?

**Comment by hankbao** [comment]
@nuclearace Could you merge the change onto carthage branch so that I can test it with my project? Thanks.

**Comment by nuclearace** [comment]
Done

**Comment by nuclearace** [comment]
Any luck?

**Comment by hankbao** [comment]
I've seen several related crash reports in previous version of my app. However current version contains the change has just been shipped. I shall feedback a few days later.

**Comment by nuclearace** [comment]
The sid can still be nil if there is no engine attacked, which should really only happen during a reconnect.

**Comment by NachoSoto** [comment]
I just encountered this issue. I'm connecting to the server with `"forceWebsockets": true`, and the server is receiving a `nil` `sid` on connection.

This is what I'm doing:
```swift
let options: [String: AnyObject!] = [
	"forceWebsockets": true
]

socket = SocketIOClient(socketURL: socketURL, options: options)
socket.connect()
```

I'm using version` 2.3.8`.

**Comment by nuclearace** [comment]
What do you mean the server is receiving a nil sid? I thought the issue was the client's sid was still nil after connect.

**Comment by NachoSoto** [comment]
I'm using [this socket.io library](https://github.com/mrniko/netty-socketio) on the server side, and on connect, [this line](https://github.com/mrniko/netty-socketio/blob/master/src/main/java/com/corundumstudio/socketio/transport/WebSocketTransport.java#L111) throws an Exception because the `sid` is an empty string.

Note that if I don't pass `"forceWebsockets": true` in `options`, this is not an issue. So it seems like this may be a problem with the `SocketEngine`?

Please let me know if I can provide more information!

**Comment by nuclearace** [comment]
Oh, there was an old issue about netty-socketio I guess this is why. Looking into it.

**Comment by nuclearace** [comment]
I'm able to recreate this with the JavaScript client doing:

```javascript
var socket = require('socket.io-client')("http://localhost:8080", {transports: ["websocket"]})
```

**Comment by NachoSoto** [comment]
@nuclearace awesome!

**Comment by NachoSoto** [comment]
@nuclearace wait, you mean that you can reproduce the same problem in `netty-socketio` using a JS client? I guess that means the problem is on the server implementation?

**Comment by nuclearace** [comment]
Well, I reproduced it using the node.js version of socket.io.

<img width="446" alt="screen shot 2015-07-12 at 8 15 38 pm" src="https://cloud.githubusercontent.com/assets/1211049/8640789/ed3af01e-28d2-11e5-9f89-3498f65b3243.png">

**Comment by nuclearace** [comment]
Actually, I was doing something wrong.

**Comment by NachoSoto** [comment]
What exactly did you reproduce? Sorry, it's not entirely clear from the screenshot.
Are you saying the node.js also produces an error?

**Comment by nuclearace** [comment]
Okay, it looks like the node.js version correctly creates a sid when you force websockets. I've never tried setting up a netty-socketio server, is there an easy guide or something?

**Comment by nuclearace** [comment]
@NachoSoto Can you checkout master and see if it's still broken?

**Comment by NachoSoto** [comment]
Will do! Thanks for the quick response and fix.

**Comment by nuclearace** [comment]
@NachoSoto Have you checked if it's fixed?

**Comment by NachoSoto** [comment]
@nuclearace I just did. Same error :(

**Comment by nuclearace** [comment]
Do you have JavaScript clients that force WebSockets connecting to this server?

**Comment by NachoSoto** [comment]
Yeah and that's working fine:
```
var socket = io("http://localhost:3001", { transports: [ 'websocket' ] });
```

**Comment by NachoSoto** [comment]
> I've never tried setting up a netty-socketio server, is there an easy guide or something?

If you're familiar with setting up java servers, the actual code is really simple: https://github.com/mrniko/netty-socketio#server

**Comment by nuclearace** [comment]
I'll try to look into it when I get home.

>If you're familiar with setting up java servers, the actual code is really simple

I've done a bit of Spring stuff, but that's about it.

**Comment by NachoSoto** [comment]
I created a [really simple test server](https://github.com/NachoSoto/Netty-Test-Server) so that you can debug this.

It's really simple to run, simply clone it and execute `mvn compile exec:java`. It'll start listening on port `3001`, and you can reproduce the issue connecting to it using `socket.io-client-swift`.

You'll see this exception being thrown during handshake:
```
java.lang.IllegalArgumentException: Invalid UUID string:
	at java.util.UUID.fromString(UUID.java:194)
	at com.corundumstudio.socketio.transport.WebSocketTransport.channelRead(WebSocketTransport.java:111)
```

Let me know if I can do anything else!

**Comment by NachoSoto** [comment]
My bad, I did something wrong when getting your fix from `master` so I wasn't actually testing that! Good news is, looks like 5057226a6cfa3e732ac5ac3aa29ecd29e580ddc1 did actually fix this!

If you'd like, you can verify this yourself with that test server (hopefully it's useful for you in the future), but this looks solved on my end :)

**Comment by nuclearace** [comment]
Looks like it's fixed.
