### ISSUE TITLE
Listener not firing for some messages with Xcode 9.3 and iOS 11.3

### ISSUE THREAD

**Issue by nipunru** [socketio/socket.io-client-swift#1001]
After I update Xcode 9.2 to 9.3 I faced this problem. I have 3 scenarios.

**Scenario A**
Client emit to server and server broadcast to a different function
Eg: Client emit "FuncA" and server broadcast same data to "FuncB"

**Scenario B**
Server directly broadcast his own data set

**Scenario C**
Client emit to server and server broadcast to the same function
Eg: Client emit "FuncA" and server broadcast same data to "FuncA"

In my case **Scenario A** and **Scenario B** working fine. **But after update to Xcode 9.3 Scenario C is not working**. In my socket io log file, it shows that the **message is received** but
`socket.on(emit) { (dataArr, ack) in
            print("data = ",dataArr)
}` 
is **not firing**.

I am using **Socket.IO-Client-Swift 11.1.3c** on **Swift 3.3**
Socket Endpoint use **HTTPS**

I connect like this.
` var socket: SocketIOClient = SocketIOClient(socketURL: url!,
                                                config: [.log(true),
                                                         .selfSigned(true),
                                                         .forceWebsockets(true),
                                                         .forceNew(true)
        ])`

**Comment by nuclearace** [comment]
Did you get anywhere with this? Sorry I couldn't get back sooner.
