### ISSUE TITLE
xcode9.2 compile error

### ISSUE THREAD

**Issue by chunxige** [socketio/socket.io-client-swift#1003]
<img width="810" alt="2018-04-16 1 57 03" src="https://user-images.githubusercontent.com/8032681/38792153-35a1e7f6-417e-11e8-8eb4-2be7cfd4d252.png">
<img width="807" alt="2018-04-16 1 57 14" src="https://user-images.githubusercontent.com/8032681/38792156-38fd75a0-417e-11e8-99d2-ac986edd4ef3.png">

**Comment by nuclearace** [comment]
If you're adding through CocoaPods make sure all targets have a SWIFT_VERSION > 4. The most recent version of the lib is for the current version of Swift.
