### ISSUE TITLE
Upload image data (NSdata or data) from ios project to server using socket script 

### ISSUE THREAD

**Issue by payalu** [socketio/socket.io-client-swift#1005]
Hi i want to upload image/video from ios project to server using socket script. I can do it using base64 but i do not want to use base64. Any one who know how to upload data on server via socket ? 

ios code

    

     let msgDictionary = [
    "file":UIImagePNGRepresentation(imageData)!];                  
    APP_DELEGATE.socketIOHandler?.socket?.emit("Upload_Image",msgDictionary)

below is my script (data.file is a data sent from ios)
but it is not working

     socket.on('Upload_Image', function(data)
	{
		var multer  = require('multer')
    	var storage = multer.diskStorage({
			  destination: function (req, file, cb) {
				cb(null, 'uploads/')
			  },
			  filename: function (req, file, cb) {
				cb(null, file.fieldname + '-' + Date.now())
			  }
    	})

	var upload = multer({ storage: storage }).single(data.file);
		console.log(data.file);

		app.post('/',  function (req, res) 
		{
			upload(req,res,function(req,res)
			{
				if(err)
				{
					console.log("error uploading file");
				}
				else
				{
					console.log("uploaded");
				}
			});
		});
	});

if without any other working way available than please share example.

**Comment by payalu** [comment]
Can you give example for supporting  binary data upload through this library ?

**Comment by nuclearace** [comment]
@payalu The simplest case is just

```swift
socket.emit("myDataEvent", Data())
```

But you can also have `Data` inside dictionaries and arrays.

Turning your image data into a `Data` object is something I can't help with though, you'll need to ask that sort of question on StackOverflow.

**Comment by payalu** [comment]
Yes i understood this emit event 
socket.emit("myDataEvent", Data())

but what should i write in "myDataEvent" --> in script ?

I can send data inside dictionaries and arrays.But how can i get that data values in socket script (.js file) and save it as a file in server.
