### ISSUE TITLE
SSLSecurity option <objecitve c>

### ISSUE THREAD

**Issue by hwangey** [socketio/socket.io-client-swift#1006]
hi im using soceket lib with objective c 
we will be used ssl sever.

 SSLSecurity *Security = [[SSLSecurity alloc]initWithUsePublicKeys:YES];
<img width="736" alt="2018-05-03 10 44 31" src="https://user-images.githubusercontent.com/38929998/39556930-03d42c22-4ebf-11e8-8429-ca562489f3b4.png">

 [[SocketManager alloc] initWithSocketURL:url config:@{@"log": @TRUE, @"forceWebsockets" :@true ,@"reconnects" :@true,@"reconnectWait" : @3, @"reconnectAttempts" :@-1,  @"security" :  Security, @"forcePolling": @true, @"secure" : @true,@"sessionDelegate":self}]

- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * _Nullable credential))completionHandler{

if([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]){
   NSURLSessionAuthChallengePerformDefaultHandling 
//@"have to not connect"

}else{

// @"ClientCertificate" 
out certificate and key match
if(is correct){
NSURLSessionAuthChallengeUseCredential 
// @"have to connect"
}else{

NSURLSessionAuthChallengeCancelAuthenticationChallenge   
//@"have to not connect"

}
}

if (completionHandler) {
        completionHandler(disposition, credential);
    }
}

but when i use  this option, soceket  awlays connect fail.
how to i use option?

also i used @"selfsigned" : @ true 
but that option is  alwsay connected  ;;

please help.

**Comment by hwangey** [comment]
@"forceWebsockets" :@true  -> remove

**Comment by EmotionV** [comment]
how do you solve that
