### ISSUE TITLE
Client, Manager and Engine getting released on second connection attempt

### ISSUE THREAD

**Issue by sootra** [socketio/socket.io-client-swift#1012]
@property (nonatomic, strong) SocketManager* manager;
@property (nonatomic, strong) SocketIOClient* socket;

Inside init:

if (self.socket == nil) {
          self.manager = [[SocketManager alloc] initWithSocketURL:url config:config];
          self.socket = self.manager.defaultSocket;
      }

And on my function to dismiss view:
if (self.socket != nil) {
        [self.socket disconnect];
        [self.socket removeAllHandlers];
        [self.manager disconnect];
        [self.manager removeSocket:self.socket];
        self.manager = nil;
        self.socket = nil;
    }

Works fine the first time. But when the view is loaded again and attempts connection, got log that the client, manager and engine is released and the app crashes.

Log:
**1st exit**
LOG SocketManager: Manager closing
LOG SocketEngine: Writing ws: 1/, has data: false
LOG SocketEngineWebSocket: Sending ws: 1/, as type: 4
LOG SocketEngine: Engine is being closed.
LOG SocketEngineWebSocket: Sending ws:  as type: 1
LOG SocketIOClient{/}: Closing socket
LOG SocketManager: Manager closing
**View disappears and then load the view again**
LOG SocketIOClient{/}: Client is being released
LOG SocketManager: Manager is being released
LOG SocketEngine: Engine is being released
**Crashes here**

Is that i am not closing the objects properly on first exit? Please help me. I am in trouble.

**Comment by nuclearace** [comment]
What is the crash reason?

**Comment by sootra** [comment]
Created a sample app and tested connect and disconnect alone. Works fine. I am using another class where i connect socket.io which is actually crashing the app. The object of that class was not strong. dealloc of that class is getting called when i started using socket.io. Previously that was working fine. So i guess the strong reference of socket.io objects is causing some reference issue to the whole project.

**Comment by sootra** [comment]
There was a weak reference in that class. When changed to strong, the crash disappeared.
