### ISSUE TITLE
Socket server is busy

### ISSUE THREAD

**Issue by EdwinXiang** [socketio/socket.io-client-swift#1020]
When I connect to the server and successfully connect to the server, the event operation is performed. Many times, the server is busy. Is there a good solution? thank you

**Comment by EdwinXiang** [comment]
oh, it so bad! let me think how to Explain to you.

it means that i connect my server,it works! We made a heartbeat connection with the server。However, sometimes the server returns a busy error result。we don't know how to solve it? Do you understand? Is there any good proposal? thank you very much!

**Comment by nuclearace** [comment]
This sounds more like a programming issue rather than an issue with the library. I'm not sure of the best way to communicate to a client that a server is busy.
