### ISSUE TITLE
swift 4 and socket io 1.0

### ISSUE THREAD

**Issue by ArtemShvydky** [socketio/socket.io-client-swift#1021]
Hello, I'm doing a migration to Swift 4. And find that on server side was implemented socket io 1.0 version and I use version for socket io 1.0 (v9.0.1).
Can I use the last version of this library (v13.2.0) and which troubles can be in this case? 
I use swift 4 in my project

**Comment by nuclearace** [comment]
No, you'll need to use the swift4 branch that still supports socket.io 1.0. The latest versions only support socket.io 2.0. I strongly recommend upgrading the server, as 1.0 is no longer supported.

**Comment by ArtemShvydky** [comment]
Thank you so much!
