### ISSUE TITLE
init SocketIOClient 13.2

### ISSUE THREAD

**Issue by alekzernov** [socketio/socket.io-client-swift#1022]
Hello, there was a problem using the library.
In the previous version, my code was such
extension SocketIOClient {
    convenience init(for myObj:MyObj) {
        guard let url = URL(string: "http://\(myObj.host):\(myObj.port)") else {
            fatalError("Unable to construct valid url for myObj \(myObj)")
        }
        self.init(socketURL: url, config: [.reconnectWait(5)])
    }
}
After updating this initializer does not work, I fixed it like this:
extension SocketIOClient {
    
    convenience init(for myObj:MyObj) {
        guard let url = URL(string: "http://\(myObj.host):\(myObj.port)") else {
            fatalError("Unable to construct valid url for myObj \(myObj)")
        }
       self.init(manager: SocketManager(socketURL:url, config: [.reconnectWait(5)]), nsp: "/")
    }   
}

Can not connect to server.
Help me please!

**Comment by nuclearace** [comment]
Check out the [migration guide](https://nuclearace.github.io/Socket.IO-Client-Swift/12to13.html) from going from pre-v13 versions.

**Comment by alekzernov** [comment]
I do not understand this guide

**Comment by alekzernov** [comment]
help please understand

**Comment by nuclearace** [comment]
It explains that actual socket clients are created through a manager. Which also is where configs go now.

**Comment by nuclearace** [comment]
V13 is a major API change, so I would check the readme example and the docs for how the new API is laid out.

**Comment by alekzernov** [comment]
What nps?

**Comment by alekzernov** [comment]
extension SocketIOClient {
    
    convenience init(for myObject: MyObject) {
        guard let url = URL(string: "http://\(myObject.host):\(myObject.port)") else {
            fatalError("Unable to construct valid url for myObject \(myObject)")
        }
        let manager = SocketManager(socketURL: url, config: [.log(true), .reconnectWait(5)])
        let socket = manager.defaultSocket
        self.init(manager: socket.manager!, nsp: "")
    }
    
}

Did as in the documentation all exactly does not work (((

**Comment by nuclearace** [comment]
@alekzernov The manager must be a property or a global, otherwise it will be released and the connection will go.

**Comment by nuclearace** [comment]
Also, you must use the, `socket(forNamespace)` on the manager.

**Comment by alekzernov** [comment]
can tell how to use the manager in my case? in version 12 there was an initializer at the client's socket where it was possible to transfer the link and parameters now it is not present could not prompt analogue of this action

**Comment by nuclearace** [comment]
@alekzernov It's basically the same, except you pass the URL and the configs to the manager. And then use `socket(forNamespace:)` or `defaultSocket` to get a socket.

**Comment by alekzernov** [comment]
I understand that it should be like this then
extension SocketIOClient {
    
    convenience init(for myObject: MyObject) {
        guard let url = URL(string: "http://\(myObject.host):\(myObject.port)") else {
            fatalError("Unable to construct valid url for myObject \(myObject)")
        }
        let manager = SocketManager(socketURL: url)
        self.init(manager:manager, nsp: "/")
    }
    
}

But it does not work for me ((
the server does not even understand that I'm connecting to it

**Comment by nuclearace** [comment]
No, the manager *must* be a property or a global. If and when it goes out of scope it will bring down the connection with it. And furthermore, you shouldn't be making SocketIOClients yourself unless you're familiar with how the manager is structured. See the README and the docs for examples on how to make clients.
