### ISSUE TITLE
init SocketIOClient

### ISSUE THREAD

**Issue by alekzernov** [socketio/socket.io-client-swift#1023]
Hello, there was a problem using the library.
In the previous version, my code was such
extension SocketIOClient {
convenience init(for myObj:MyObj) {
guard let url = URL(string: "http://(myObj.host):(myObj.port)") else {
fatalError("Unable to construct valid url for myObj (myObj)")
}
self.init(socketURL: url, config: [.reconnectWait(5)])
}
}
After updating this initializer does not work, I fixed it like this:
extension SocketIOClient {

convenience init(for myObj:MyObj) {
    guard let url = URL(string: "http://\(myObj.host):\(myObj.port)") else {
        fatalError("Unable to construct valid url for myObj \(myObj)")
    }
   self.init(manager: SocketManager(socketURL:url, config: [.reconnectWait(5)]), nsp: "/")
}   
}

Can not connect to server.
Help me please!
Migratory guide not absolutely understand help please understand

**Comment by nuclearace** [comment]
Please do no open multiple issues.
