### ISSUE TITLE
Init SocketIOClient different with .forceWebsockets(true)

### ISSUE THREAD

**Issue by gorbat-o** [socketio/socket.io-client-swift#1024]
Hello guys,

I am using socket.io, and I had to pass from swift 2 to 4 on one of my project 😅
So I read this [migration help](https://nuclearace.github.io/Socket.IO-Client-Swift/12to13.html)
But I didn't find how to pass from this (below) to the new version with the .forceWebsockets(true).
I probably missed a point.
```
SocketIOClient(socketURL: URL(string:"https://somefancyurl.fr:3000")!, config: [.forceWebsockets(true)])
```

I saw that I have to use the manager like this, that is fine, but where this .forceWebsocket gone ? 😂
```
let manager = SocketManager(socketURL: URL(string:"https://somefancyurl.fr:3000")!)
func someFancyFunc() {
    let socket = SocketIOClient(manager: manager, nsp: "")
}
```

Thanks in advance for the future help :)

**Comment by nuclearace** [comment]
@gorbat-o All configs are the same for the most part, but are on the manager. Generally you only explicitly make `SocketManger`s, since they are the ones responsible for clients. Clients are obtained from the `socket(forNamespace:` method.

**Comment by gorbat-o** [comment]
Thank you for the fast answer.

I still don't understand where I have to put the .forceWebsockets(true) condition. It didn't find it in the documentation.

**Comment by nuclearace** [comment]
It gets passed into the manager.

**Comment by gorbat-o** [comment]
Ok I finally found it with ```setConfigs([.forceWebsockets(true)])```
But the socket is not receiving anything
that worked before
```
socket!.on("joinThreadResponse") { data, ack in
}
```

**Comment by Maks273** [comment]
@gorbat-o how did you fix it? I have the same problem
