### ISSUE TITLE
Socket.on is not working. I did everything. Please help

### ISSUE THREAD

**Issue by mlabgamestudio** [socketio/socket.io-client-swift#1030]
This is code. Socket is connected. And Emit is working.
But socket.on("forumyeni") is not working. Server is ok. Android socket is working without an issue. But like I said. socket.on is not working. What is wrong with this?

`import Foundation
import SocketIO

class SocketIOManager: NSObject {
    
    static let sharedInstance = SocketIOManager()
    let manager = SocketManager(socketURL: URL(string: "http://localhost:8080")!, config: [.log(true), .compress])
    var socket:SocketIOClient? = nil
    
    override init() {
        super.init()
         socket = manager.defaultSocket
        socket?.on(clientEvent: .connect) {data, ack in
            print("socket connected \(data)")
            let myJSON = [
                "kimden": "DENEME",
                "yaziyormu" : "true",
                "id" : "16827891",
                "yenitip" : "1",
                "kimlik" : "yorumyaziyor"
                ] as [String : Any]
            socket.emit("forumyeni", myJSON)
           
            
        }
        
        socket?.on("forumyeni") { dataArray, ack in
            print("verigeldi \(dataArray)")
        }
        
    }
    
    func establishConnection() {
        socket?.connect()
    }
    
    func closeConnection() {
        socket?.disconnect()
    }
}
'

**Comment by nuclearace** [comment]
Can you post some logs? I don't see anything wrong with the code.

**Comment by mlabgamestudio** [comment]
By the way I had to make some change when I installed Socket.io library via pod. Because there were 17 errors at first. Do you think this can be the issue?

**Comment by mlabgamestudio** [comment]
Any help would be great.Please

**Comment by Rupasekhar** [comment]
I still think something is setting a SWIFT_VERSION to something lower than 4.0. that "Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?" was for an old version of Swift where the string init returned an optional; it shouldn't in Swift 4.0.
<img width="676" alt="30652002-32dce8a4-9df5-11e7-9600-ec3351714db9" src="https://user-images.githubusercontent.com/2901360/43248901-dc0e0e10-90d6-11e8-9d06-fb2e94aa4179.png">

It resolved 17 runtime errors only, but still "on" is not invoking. @nuclearace Pls help us out.

**Comment by vikashkumar0795** [comment]
At my end, there is another library which was using starscream and socket.io is also using same. So there were version difference between this library. so make sure both library have same version
