### ISSUE TITLE
[objective c] Cannot send header using extraHeaders

### ISSUE THREAD

**Issue by webtamizhan** [socketio/socket.io-client-swift#1031]
Hello there!

I trying to connect with my web socket using the following 

`NSString* token = [NSString stringWithFormat:@"Authorization: Bearer %@", self.accessToken];`
`NSURL* url = [[NSURL alloc] initWithString:@"http://example.com:6001"];`
`self.manager = [[SocketManager alloc] initWithSocketURL:url config:@{@"log" : @YES, @"nsp" : @"/",  @"extraHeaders": token}];`

I would like to connect web socket using `Authorization: Bearer some_token`., But in server side the request cannot have this header.

When i am trying to connect socket using basic web(html) with header, connection succeeded and receiving broadcast without any problem.

Logs:
While connection succeeded from html socket connection request

`
[2018-06-03 16:56:00] development.INFO: app.requests {"request":"[object] (Illuminate\\Http\\Request: POST /broadcasting/auth HTTP/1.1
Authorization:    Bearer my_token
Connection:       close
Content-Length:   33
Content-Type:     application/x-www-form-urlencoded
Cookie:           
XSRF-TOKEN=token; 
io=BELZpg6pTgVemz6ZAABd
Host:             example.com
X-Requested-With: XMLHttpRequest
Cookie: XSRF-TOKEN=token=; 
laravel_session=token; 
io=BELZpg6pTgVemz6ZAABd
channel_name=channel_name-59)"} 
`

While using Swift client request would be
`
[2018-06-03 17:32:17] development.INFO: app.requests {"request":"[object] (Illuminate\\Http\\Request: POST /broadcasting/auth HTTP/1.1
Connection:       close
Content-Length:   33
Content-Type:     application/x-www-form-urlencoded
Host:             example.com
X-Requested-With: XMLHttpRequest
channel_name=channel_name-55)"} 
`

Socket server was created by node broadcasting with Socket.io

using socket.io 2.1.1 for server.
Server : Laravel echo server

Any solution?

**Comment by nuclearace** [comment]
@webtamizhan If you look at the docs for [extraHeaders](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:8SocketIO0A14IOClientOptionO12extraHeadersACs10DictionaryVyS2SGcACmF), it takes a dictionary of `[String: String]`. Which in obj-c is just an NSDictionary.

**Comment by webtamizhan** [comment]
Still i cannot receive Authorization Header even using extraHeaders.

Can i have some sample code please?

**Comment by nuclearace** [comment]
I added a test for it [here](https://github.com/socketio/socket.io-client-swift/blob/development/Tests/TestSocketIOObjc/ManagerObjectiveCTest.m#L16). I would try debugging the server and see what is coming over in the request.
