### ISSUE TITLE
iOS 12: Use the Network.framework for socket connections

### ISSUE THREAD

**Issue by hansemannn** [socketio/socket.io-client-swift#1036]
Hey there!

I want to start a general discussion on implementing the Network.framework for iOS 12+ targets. As presented during the WWDC 2018, the new framework offers great benefits over the current native socket handling by having clean states and handling the `waiting` state more performant.

While exposing the Network.framework, Apple is also planning to deprecate the `SFSocket` and all related API's. They did not so far (but mentioned they may do over the next view betas) during the session. 

Read more about the new API in the [official API docs](https://developer.apple.com/documentation/network).

**Comment by nuclearace** [comment]
You probably should open this against the Starscream project. This library doesn’t use any direct networking.
