### ISSUE TITLE
Getting EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by shravansukumar** [socketio/socket.io-client-swift#1038]
I'm in version 12.1.2 and I'm getting a corrupted heap issue.
Please refer below for the logs:

`#25. Crashed: <>.<>Queue`
`0  libobjc.A.dylib                0x1802a01a0 objc_retain + 16`
`1  SocketIO                       0x102057ff8 @objc SocketEngine.connect() -> () + 4330356728`
`2  SocketIO                       0x102074824 specialized SocketIOClient.connect(timeoutAfter : Double, withHandler : () -> ()?) -> () + 4330473508`

Followed by trace to our files. This gets triggered when `socket?.on("reconnect", callback: onReconnect)` is called.

**Comment by nuclearace** [comment]
Make sure all interaction with the client is on the `handleQueue`. The client is not thread safe.

**Comment by shravansukumar** [comment]
Just to make things clear, you are asking me to add another parameter in `config` array, `.handleQueue(someQueue)` while I create my SocketClient, and while I'm using the socket, I'll be dispatching it in that queue right?
