### ISSUE TITLE
emitWithAck not working

### ISSUE THREAD

**Issue by Elhoej** [socketio/socket.io-client-swift#1039]
I'm trying to make an emit with a callback, but it seems like the server doesn't recognize the call back function as a function. I have looked up the documentation, and to my knowledge the code should work.

This is the error I'm getting: `TypeError: callBack is not a function`

Here is the client code:
```

socket?.emitWithAck("connectUsername", username).timingOut(after: 2, callback: { (data) in
            
        print(data)
    })
```

And server code:    

```
socket.on("connectUsername", function(username, callBack)
    {
        //Do stuff with username here...

        var id = socket.id
        callBack(id);
     });
```

Any help is appreciated.

**Comment by nuclearace** [comment]
What server version?

**Comment by Elhoej** [comment]
version: socket.io@2.1.1
