### ISSUE TITLE
socket.connecting never set to 'YES'

### ISSUE THREAD

**Issue by cmorss** [socketio/socket.io-client-swift#104]
I would expect socket.connecting to be true after calling [socket connect], however this is not the case. 
A search in the code for _connecting turns up no places that it is set to true, just set to false.
 (I'm using Objective-C)
Thanks - C

**Comment by nuclearace** [comment]
Probably lost in a refactoring

**Comment by cmorss** [comment]
Thanks for the update but does closing this issue mean that it'll be fixed soon?

**Comment by nuclearace** [comment]
It's fixed in the latest master, I'll push a new minor version later

**Comment by cmorss** [comment]
Thanks so much. Very much appreciated.

On Tue, Jun 23, 2015 at 5:36 PM, Erik Little <notifications@github.com>
wrote:

> It's fixed in the latest master, I'll push a new minor version later
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io-client-swift/issues/104#issuecomment-114682945>
> .
>



-- 

charlie.morss@gmail.com
