### ISSUE TITLE
Cannot setConfigs after init in objective-c

### ISSUE THREAD

**Issue by MarcoBrescianini** [socketio/socket.io-client-swift#1040]
Hi @nuclearace, i'm developing a project in objective-c using this swift library and i notice that it's impossible from objective-c to change the SocketManager configs after a socket manager has been initialized. I tried to call the setConfigs: method on a SocketManager instance passing a dictionary as argument, like you do when you init a new SocketManager instance, but the compiler complains about 'SocketManager not declaring the selector setConfigs:'. 
I also noticed, it's not possible to get the current configs from a SocketManager instance either, the compiler complains that 'property 'config' not found on object of type 'SocketManager *''.
What i'd like to do is change the connection query parameters before the socket manager tries a reconnection attempt.

I'm using version 13.1.3

**Comment by nuclearace** [comment]
Yeah, this currently isn't supported, because the actual type of the configs aren't representable in Objective-C. There would need to be a method that takes an NSDictionary and does the conversion like the init does.

**Comment by zhonglaoban** [comment]
I create a class inherit SocketManager to do setConfigs like this
`Swift
@objc public func setConfigs(_ config: [String:Any]) {
        let options = config.toSocketConfiguration()
        setConfigs(options)
    }
`
