### ISSUE TITLE
SSL Pinning not working

### ISSUE THREAD

**Issue by satishVekariya** [socketio/socket.io-client-swift#1043]
Here is my code:

```swift
SocketManager(socketURL: url, config: 
[.connectParams(["token": "abc123"]), .forceNew(true), .reconnects(true), .compress, .secure(true), security(SSLSecurity(usePublicKeys: true))]
)
```

When i enable ssl proxy on charles it's show as plan text not in encrypted,
i also added root certificate file(.cer) in my main bundle

lib version: **13.2.1**

**Comment by nuclearace** [comment]
Make sure your URL is actually https. Besides that, you'll probably need to use the URLSessionDelegate option if you want real SSL pinning.

**Comment by satishVekariya** [comment]
Thanks for replay!!

Ya, I'm sure, my URL is https and its working well on Android platform.
What do you mean real SSL pinning??. Above code is not for real pinning!!

**Comment by hschouman** [comment]
Hello,

I have the same issue :-/

@satishVekariya did you found a solution ?
If not : are you sure your certificate is in binary ? if not you should try to convert it with the following command :
openssl x509 -in cert.cer -outform der -out cert.der

In my case, the key or certification seems to be correctly set but I can see everything as plain text in Charles Proxy...
My config with a certificate :

```
if let url = Bundle.main.url(forResource: "cert", withExtension: "der") {
    let data = try Data(contentsOf:url)
    let sslSecurity = SocketIO.SSLSecurity(certs: [SSLCert(data: data)], usePublicKeys: false)
    return [.log(true), .reconnectWait(5), .compress, .secure(true), .security(sslSecurity), .forceNew(true), .cookies([])]
```

I also tried with the public key as following :
(I used https://github.com/btnguyen2k/swiftutils to store the public key to the keychain)
```
let key = try RSAUtils.addRSAPublicKey(keyString, tagName: Constant.publicTagKey)
if let key = key {
    let sslSecurity = SocketIO.SSLSecurity(certs: [SSLCert(key: key)], usePublicKeys: true)
    return [.log(true), .reconnectWait(5), .compress, .secure(true), .security(sslSecurity), .forceNew(true), .cookies([])]
}
```

**Comment by hschouman** [comment]
I finally succeed doing it.
you should add an URLSessionDelegate in the config and compare the server certificate with the client one.

You can follow the explanations of this article :
https://medium.com/@andersongusmao/certificate-pinning-technique-on-ios-af0f0813e88
