### ISSUE TITLE
Missing required modules: 'SSCZLib', 'SSCommonCrypto'

### ISSUE THREAD

**Issue by weifans** [socketio/socket.io-client-swift#1044]
**Project directory structure**
<img width="615" alt="1" src="https://user-images.githubusercontent.com/5456137/41697274-9b0765b2-754a-11e8-8fe9-bb266cfe2997.png">

**Package.swift**
<img width="1121" alt="2" src="https://user-images.githubusercontent.com/5456137/41697302-bdb6fdf2-754a-11e8-8f01-3bf906519da8.png">

**Swift package manage**
swift package init
swift package update
swift package generate-xcodeproj

**Problem**
Do not import SocketIO to run successfully.
Import SocketIO to run error.

**ERROR**

<img width="1166" alt="3" src="https://user-images.githubusercontent.com/5456137/41697445-613ebd0c-754b-11e8-8cd7-2d544042ba58.png">

**Thank you**

**Comment by weiFans** [comment]
@nuclearace Can you see my question?

**Comment by techvj** [comment]
@weiFans did you find solution for this

**Comment by weiFans** [comment]
@techvj I gave up SMP and chose Carthage to solve this problem.
