### ISSUE TITLE
SocketIOClient: Handling event: error with data: [“Invalid SSL certificate”]

### ISSUE THREAD

**Issue by Nag91777** [socketio/socket.io-client-swift#1045]
Question is regarding Invalid SSL Certificate. I have been trying to connect to Websocket using SocketIOClient. But getting "Invalid SSL certificate" issue. The code used to connect Socket is

import UIKit
import SocketIO
class SocketIOManager: NSObject, URLSessionDelegate {
    
    static let shared = SocketIOManager()
    var socket: SocketIOClient!
    
    func socketConnect() {
        
        let token = "ggggggg" //some token
        let url  = URL(string: "https://sample.com") // some https url
        let specs: SocketIOClientConfiguration = [
            .connectParams(["access_token": token]),
            .log(true),
            .forceNew(true),
            .selfSigned(true),
            .forcePolling(true),
            .secure(true),
            .reconnects(true),
            .forceWebsockets(true),
            .reconnectAttempts(3),
            .reconnectWait(3),
            .security(SSLSecurity(usePublicKeys: true)),
            .sessionDelegate(self),
            ]
        socket = SocketIOClient(socketURL: url!, config: specs)
        
        socket.on(clientEvent: .connect) {data, ack in
            print("socket connected")
            self.socket.emitWithAck("emit", with: []).timingOut(after: 2, callback: { (data) in
                print(data)
            })
        }
        
        socket.on("fetch") { (dataArray, ack) in
            print(dataArray)
        }
        
        socket.on(clientEvent: .error) {data, ack in
            print(data)
        }
        
        socket.on(clientEvent: .disconnect) {data, ack in
            print(data)
        }
        
        socket.onAny { (data) in
            // print(data)
        }
        
        socket.connect()
        
    }
    
    func urlSession(_ session: URLSession, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
        
        completionHandler(.useCredential, URLCredential(trust: challenge.protectionSpace.serverTrust!))
    }
    
    func urlSession(_ session: URLSession, didBecomeInvalidWithError error: Error?) {
        // We've got an error
        if let err = error {
            print("Error: \(err.localizedDescription)")
        } else {
            print("Error. Giving up")
        }
    }
    
}

**Comment by nuclearace** [comment]
Make sure you're properly handling your session delegate methods to handle your cert.

**Comment by Nag91777** [comment]
I don't have an SSL Certificate. But other Socket IO clients are accessing without SSL Certificate, like Android and Javascript with default SSL Configuration.

**Comment by nuclearace** [comment]
You should look into Apple's security requirements, they're pretty strict for production apps.

Some reading:
[handling challenges](https://developer.apple.com/documentation/foundation/url_loading_system/handling_an_authentication_challenge?changes=_6)
[General security for networking on page 36](https://www.apple.com/business/docs/iOS_Security_Guide.pdf) specifically the App Transport Security section.

**Comment by Nag91777** [comment]
Hi Nuclearace, I followed all the session delegate methods as per Apple documentation, still we are facing the same issue.
My question is do we need to insert any SSL Certificate that is provided by client or do we need to generate a Certificate and insert it.

**Comment by czbalazs** [comment]
@Nag91777 Have you managed to solve the issue? If so, could you please give me some insights?
