### ISSUE TITLE
User interface not working when and run CFRunLoopRun after method connect

### ISSUE THREAD

**Issue by ngocdtph03070** [socketio/socket.io-client-swift#1046]
When I run CFRunLoopRun after medthod connect. User interface not update only show white screen

**Comment by nuclearace** [comment]
You shouldn't need to call CFRunLoopRun in a regular App. You only need to call that for command line apps.

**Comment by UzumakiAlfredo** [comment]
I have the same problem! but if I don't  call CFRunLoopRun, then my socket will not connect.

**Comment by ngocdtph03070** [comment]
> I have the same problem! but if I don't call CFRunLoopRun, then my socket will not connect.

You should create a singleton manager socket  and call it where need use
