### ISSUE TITLE
Unable to add 'Socket.IO-Client-Swift', '~> 13.2.1' as a dependency.

### ISSUE THREAD

**Issue by Nitish34** [socketio/socket.io-client-swift#1047]
Hello ,

I want to create a framework that has dependency of socketIO client. I have created podspec of the project but when I add dependency in that pod spec "s.dependency 'Socket.IO-Client-Swift', '~> 13.2.1' ". So it gives various error
 
<img width="1691" alt="screen shot 2018-06-26 at 4 03 54 pm" src="https://user-images.githubusercontent.com/9015460/41906113-a1fb127e-795a-11e8-8658-b31beeddcb6c.png">

**Comment by nuclearace** [comment]
@Nitish34 Be sure you're specifying somewhere in your project files what Swift version your code is. The library requires the latest version of Swift.

**Comment by Nitish34** [comment]
@nuclearace. I have tried mentioning swift version but it was giving a error. But by default it takes swift version 3.2 as mentioned .

**Comment by Nitish34** [comment]
@nuclearace I just want to include socket client in my iOS "bundle" which I can use somewhere else also.

**Comment by nuclearace** [comment]
@Nitish34 This library only supports Swift 4, so you'll need to make sure your project is using Swift 4.

**Comment by Nitish34** [comment]
It is swift 4.

**Comment by nuclearace** [comment]
@Nitish34 what errors are you getting when your project is in Swift 4 mode?

**Comment by Hemrajjhariya** [comment]
@nuclearace trying to do the same thing and getting errors. Is there any solution for it.

**Comment by Nitish34** [comment]
@hemrajjhariya. Try clean and delete derived data. That trick works and make sure there is no other socket project running or ongoing. Thats how I resolved it

**Comment by Hemrajjhariya** [comment]
@Nitish34 I have my own custom cocoaPod with Name 'ABC' and in ABC pod spec file I have added   s.dependency 'Socket.IO-Client-Swift', '~> 12.0.0'. Now, when I run command pod spec lint. I'm getting the same errors which you had mentioned above.

**Comment by Nitish34** [comment]
@hemrajjhariya.What I havr done in my project was. I created a dynamic lib, then pod init in that, added socket library. Pod install. Open workspace import socketio. Clean and build using generic device as a target that's it. Use your library.

**Comment by Hemrajjhariya** [comment]
@Nitish34 I'm not trying to install Socket lib from pod file in the project. What I am trying is, that adding Socket as s.dependency 'Socket.IO-Client-Swift', '~> 12.0.0' in my framework Podspec file and  when I run command pod spec lint then it is giving error.

**Comment by Nitish34** [comment]
@hemrajjhariya in my project there was a socket dependency so I have done that via pod install.

**Comment by DeveloperDongHao** [comment]
same too  What's the solution？ THX

**Comment by DeveloperDongHao** [comment]
![image](https://user-images.githubusercontent.com/10461205/45531129-c77b2200-b820-11e8-8fd4-2454ee36e855.png)
this
