### ISSUE TITLE
Socket IO client doesn't work on Xcode 9.2

### ISSUE THREAD

**Issue by Nitish34** [socketio/socket.io-client-swift#1048]
I am creating a cocoaTouch framework that has dependency of SocketIO client, So I was doing that via cocoa pods. I have added "pod 'Socket.IO-Client-Swift', '~> 13.2.0'",  pod install, but it shows no module found error. My swift version is 4.1.

**Comment by nuclearace** [comment]
Are you using the workspace that CocoaPods creates? You have to use that one.

**Comment by Nitish34** [comment]
Yes I m using workspace only.

**Comment by Nitish34** [comment]
Is that a question

**Comment by nuclearace** [comment]
I was able to make a new project, `pod init`, add `pod 'Socket.IO-Client-Swift', '~> 13.2.0'` to the Podfile, `pod install`, and then use the new workspace that CocoaPods created and use the module with no issues in Xcode 9.3.
