### ISSUE TITLE
won't compile with existing project

### ISSUE THREAD

**Issue by rw86347** [socketio/socket.io-client-swift#105]
/Users/rwilson/Dropbox/dev/carepix/Pods/Socket.IO-Client-Swift/SwiftIO/WebSocket.swift:239:26: Cannot invoke 'setProperty' with an argument list of type '(Dictionary<NSObject, NSObject>, forKey: CFString!)'

            inputStream!.setProperty(settings, forKey: kCFStreamPropertySSLSettings)
            outputStream!.setProperty(settings, forKey: kCFStreamPropertySSLSettings)

Many of these issues.  Is there some Switch version I need to set?

Why wasn't this written in Objective-C?

**Comment by nuclearace** [comment]
>why wasn't this written in Objective-C
Because Swift is much nicer than Objective-C, and is the future of Apple development. 

As for your problem, are you trying this from Xcode 7? Because if so, you'll need to checkout the Swift 2 branch.

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/tree/swift-2

**Comment by rw86347** [comment]
I am using xcode 6.3.2

**Comment by nuclearace** [comment]
What version of the client are you using?

**Comment by rw86347** [comment]
6.3.2

**Comment by rw86347** [comment]
My college believe it is 1.1 or 1.2

**Comment by nuclearace** [comment]
That sounds like the Swift version, in which case it's Swift 1.2 with xcode 6.3. What version of socket.io-client did cocoa-pods install?  If you just copied the example from the README you'll need to update the version it installs to 2.3.6.

I should probably just update the README each time.
