### ISSUE TITLE
Looks like memory leak within Socket.io

### ISSUE THREAD

**Issue by allenlinli** [socketio/socket.io-client-swift#1050]
Please refer to the images below.

![screen_shot_2018-06-28_at_5_46_16_pm](https://user-images.githubusercontent.com/849911/42027320-02205360-7afc-11e8-9e32-e4e9abe8c849.png)
![screen shot 2018-06-28 at 5 46 48 pm](https://user-images.githubusercontent.com/849911/42027325-03f4db16-7afc-11e8-8660-c97f2fc04431.png)

It looks like memory leaks when `SocketEngine.createURLs`
Just leaks two bytes, but just let you know.

**Comment by nuclearace** [comment]
Memory analysis for Swift is notoriously error prone, especially between module boundaries.  I don't see how this code would leak anything.
