### ISSUE TITLE
To receive message in Chinese will be show unrecognizable characters, like ä½ å¥½å

### ISSUE THREAD

**Issue by MrShiY** [socketio/socket.io-client-swift#1052]
How to configure to solute the problem

**Comment by nuclearace** [comment]
@MrShiY What version is the server using?

**Comment by MrShiY** [comment]
@nuclearace 13.1.3

**Comment by MrShiY** [comment]
I also  detect the older version 9.0, it is fine, why is the new version bad ?

**Comment by zixinxiaohei** [comment]
I also have the same problem in Version 13.2.1 ,but no see doubleEncodeUTF8 ,
doubleEncodeUTF8 Has been removed （接收的中文的内容乱码），how can I do？

**Comment by zixinxiaohei** [comment]
I use swift language ,This phenomenon does not occur with the simulator, this problem occurs with the real machine.（模拟器不会出问题，真机就会出现内容乱码）

**Comment by MrShiY** [comment]
@zixinxiaohei  我自己处理了,把消息都给base64一下再发,可能新版本库有问题,我有个工程用的9.0的就没有这个问题.

**Comment by nuclearace** [comment]
@MrShiY I meant what server version. This library only supports socket.io 2.0. 2.0 introduced a breaking unicode change, which is what you're probably seeing.

**Comment by nuclearace** [comment]
If you need socket.io 1.0 support, you'll need to use the (unmaintained) [1.0 branch](https://github.com/socketio/socket.io-client-swift/tree/1.0-swift4).

**Comment by WatermelonPrince** [comment]
> @zixinxiaohei 我自己处理了,把消息都给base64一下再发,可能新版本库有问题,我有个工程用的9.0的就没有这个问题.



> @zixinxiaohei 我自己处理了,把消息都给base64一下再发,可能新版本库有问题,我有个工程用的9.0的就没有这个问题.

你好，你们这个问题怎么解决的啊，我是客户端开发的，现在安卓没有这个问题，只有iOS有这个问题，你说的发之前base64是服务端需要base64之后再发吗？
