### ISSUE TITLE
Not getting Disconnect event when network dosconnects

### ISSUE THREAD

**Issue by ilandbt** [socketio/socket.io-client-swift#1053]
Hey,

I'm not getting a `disconnect` event when i turn off my wifi connection (working on a simulator).
On the `onAny` handler i'm just getting a few `ping` events

This used to work for me, using your framework for the last 2+ years.

Thanks

**Comment by nuclearace** [comment]
This library is completely platform agnostic. It relies on the underlying networking libraries to tell it if the connection has gone away. Your best bet is to add some availability checks yourself. Is this happening when the client is doing long-polling or WebSockets, or both?

**Comment by wongzigii** [comment]
@ilandbt Did you finally solve this issue? My socket is not receiving `disconnect` event from server, too

**Comment by wongzigii** [comment]
FYI this may relate to #1016

**Comment by 954788** [comment]
@ilandbt My solution is to listen to error envent, determine if the hint in data is no network, and then proceed.

**Comment by ljcp** [comment]
any news on this issue?  i had to use the same workaround @ 954788

**Comment by 954788** [comment]
I am sorry to see it so late. At that time, I wanted to reconnect through disconnect. Finally, I replaced it with reconnectAttempt. @ljcp
