### ISSUE TITLE
  "Foundation.CharacterSet.init(charactersIn: Swift.String) -> Foundation.CharacterSet", referenced from:

### ISSUE THREAD

**Issue by praveen4D2** [socketio/socket.io-client-swift#1054]
Hi,

If i install podfile in objective c project it shows errors. can u help me to solve this issue. I am Using Xcode Version 9.4 (9F1027a) and  pod version  1.5.2

**Comment by nuclearace** [comment]
Be sure that you're setting a SWIFT_VERSION for your project.

**Comment by fotiDim** [comment]
Add an empty Swift file and answer yes when Xcode asks you to add the bridging header.
