### ISSUE TITLE
How to use Swift Package Manager？

### ISSUE THREAD

**Issue by weifans** [socketio/socket.io-client-swift#1056]
**Project directory**
<img width="203" alt="444" src="https://user-images.githubusercontent.com/5456137/42861208-ab233d48-8a8c-11e8-9cf8-7f0e2ff8f4f7.png">

swL.xcodeproj is Library 
swP.xcodeproj is project

**Package.swift file**
<img width="1125" alt="1232" src="https://user-images.githubusercontent.com/5456137/42861598-3b24e8dc-8a8e-11e8-91e6-a9cec69195c3.png">

**Dependency**

<img width="1001" alt="123" src="https://user-images.githubusercontent.com/5456137/42861630-618d35d8-8a8e-11e8-9c5c-6d3f200c6793.png">

**ERROE**
<img width="520" alt="22" src="https://user-images.githubusercontent.com/5456137/42861788-2aa32b12-8a8f-11e8-9213-877ff595cc37.png">

This is my second question. I am really anxious and hope to be resolved. Thank you.

**Comment by nuclearace** [comment]
I've not seen that second issue, but others have apparently. The CI system also doesn't seem to run into the issue when testing the library using SPM. I will try and look into this a bit more.

**Comment by nuclearace** [comment]
Yes, you can check out https://github.com/nuclearace/socket.io-client-testing. Which is just a scratch project I use to test some stuff for this lib.

**Comment by weiFans** [comment]
@nuclearace This link didn't help me.
I hope you can take the time to test SPM.
It won't take you too much time, there really is a problem, I tested it in a new project.
There is a problem with the dependency package.

<img width="520" alt="22" src="https://user-images.githubusercontent.com/5456137/43177508-377fc892-8ffb-11e8-9627-6563f7fe63c0.png">
Thank you very much, I hope to get your support.
