### ISSUE TITLE
make a slight change to the README

### ISSUE THREAD

**Issue by rw86347** [socketio/socket.io-client-swift#106]
I am using cocoapods to include the socket.io library.  However I cannot figure out how to add the correct Swift.h file in my Objective-c files.  I think just a few lines would really help.

**Comment by nuclearace** [comment]
I'm not actually sure, I would think it would be something along the lines of `Socket_IO_Client_Swift.h"

**Comment by banjun** [comment]
When you use CocoaPods, socket.io will be compiled to a module (framework). This import seems to work, although I have not used from Objective-C.

```
#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>
```

**Comment by nuclearace** [comment]
If what @banjun says is correct, I'll update the readme to include that.

**Comment by hfossli** [comment]
I can confirm that this works
```
#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>
```
