### ISSUE TITLE
 pod 'Socket.IO-Client-Swift', '~> 13.2.0' installed, but runtime errors.

### ISSUE THREAD

**Issue by Rupasekhar** [socketio/socket.io-client-swift#1064]
Hi,
Thanks for the amazing socket.io-client-swift for developers, previously i was using 11.1.3 pod version & SocketIOClient to initialize, now I upgraded to **13.2.0 pod version** which comes with SocketManager. Now am getting 17 runtime errors in **SocketAckEmitter.swift, SocketIOClient.swift and SocketEngine.swift** classes. My Project developed in **OBJ-C**. Can you please tell me how to fix them or any minor settings for that? As I have **urgent delivery
![screen shot 2018-07-26 at 10 16 05 am](https://user-images.githubusercontent.com/2901360/43242172-066a1cea-90bd-11e8-89ce-f2a1cf1a3474.png)
** to client today, all these issues are eating all my time, Kindly help me out.

**Comment by nuclearace** [comment]
@Rupasekhar Usually when this happens. Something is not properly setting the SWIFT_VERSION. This shouldn't be a problem with the library itself, it [already declares](https://github.com/socketio/socket.io-client-swift/blob/master/Socket.IO-Client-Swift.podspec#L25) what SWIFT_VERSION to use.

**Comment by Rupasekhar** [comment]
Ya, I will Ckeck it now. Thanks for ur quick reply. I'm facing another scenario problem. 
I had initialised socketmanager and socket client in appdelegate of didfinishWithLaunchOptions, and invoked connect method in after sucessfully login. then only my ON method which is in appdelegate is getting called without any issue.
Now i need to send loggedin userid and devicetoken in config for connectParams key. So in appdelegate of didfinishWithLaunchOptions we never get loggedin userid and devicetoken. So after login, when invoking connect method am initialising again with new connectParams and  my ON method which is in appdelegate is not getting called.

I hope you understand my scenario. Pls do help me out.

**Comment by nuclearace** [comment]
@Rupasekhar Your best bet is just to create a whole new SocketManager, client, and handlers if you need to change connectParams.

**Comment by Rupasekhar** [comment]
Ok, whole new SocketManager, client objects have to initialise in AppDelegate only right?
am I right?

**Comment by nuclearace** [comment]
@Rupasekhar That's up to you how you want to structure your app.

**Comment by nuclearace** [comment]
The thing you want to be wary of is that the Manager should be retained for as long as the connection should be around.

**Comment by MD04-TanTan** [comment]
Hi @Rupasekhar  !! Could u tell me how to import this lib to a Objective C project?. I installed it from cocoapods but my xcode (9.4) can not complie with ~201 error

**Comment by huforrest** [comment]
@Rupasekhar I have similar problem. When I build my project, I also got 17 runtime errors. Have you solved this problem? And how did you solve it?

**Comment by huforrest** [comment]
@Rupasekhar I finally solved this problem. Here is my solution:
1 I go to Build Settings > Swift Language Version, and I set the swift version to 4.1
2 In Podfile I changed Socket.IO-Client-Swift version to 13.3.0 like this pod 'Socket.IO-Client-Swift', '~> 13.3.0'
3 pod update
