### ISSUE TITLE
SocketEngine crash

### ISSUE THREAD

**Issue by leehonn** [socketio/socket.io-client-swift#1066]
I find same users can carsh when SocketIOClient connect.
error message as follow:
createURLs (SocketEngine.swift:0)
 init (SocketEngine.swift:189)
0x0000000100744000 + 8457484
 0x0000000100744000 + 8458116
connect (SocketIOClient.swift:0)
connect (SocketIOClient.swift:0)
[SocketIOManager connect] (SocketIOManager.m:126)

When I connect,I use asynchronous ways.Is that reason？

**Comment by nuclearace** [comment]
All interaction with the client should be done on the `handleQueue` which by default is the main queue. If you try and access the client outside of that queue, you're prone to race conditions and crashes.

That being said, that stack trace really isn't enough to go on.

**Comment by leehonn** [comment]
SocketIOManager connect in the asynchronous thread,I can't recurrent this crash.In the logs,I can find a lot crash messages. Error is:  BLYCPPExceptionTerminate() + 2004
Because I can't recurrent this crash,I don't sure that crash disappear when SocketIOClient connect in the main queue.
Hope you can give me some advice,thank you!

**Comment by leehonn** [comment]
Stack information details are as follows：
libsystem_kernel.dylib | __pthread_kill + 8
-- | --
1 libsystem_pthread.dylib | _pthread_kill$VARIANT$armv81 + 360
2 libsystem_c.dylib | abort + 140
3 libc++abi.dylib | __cxa_bad_cast + 0
4 libc++abi.dylib | default_unexpected_handler()
5 libobjc.A.dylib | _objc_terminate() + 124
6 O2O | BLYCPPExceptionTerminate() + 2004
7 libc++abi.dylib | std::__terminate(void (*)()) + 16
8 libc++abi.dylib | __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
9 libobjc.A.dylib | _objc_exception_destructor(void*)
10 CoreFoundation | -[NSException initWithCoder:]
11 Foundation | -[__NSConcreteURLComponents setPercentEncodedQuery:] + 132
12 libswiftFoundation.dylib | __swift_deallocate_boxed_opaque_existential_0 + 5740
13 libswiftFoundation.dylib | globalinit_33_5692656F4C05BA2A580AE9322E9FB0A6_func56 + 33376
14 O2O | createURLs (SocketEngine.swift:0)
15 O2O | init (SocketEngine.swift:189)
16 O2O | 0x000000010099c000 + 8457484
17 O2O | 0x000000010099c000 + 8458116
18 O2O | connect (SocketIOClient.swift:0)
19 O2O | connect (SocketIOClient.swift:0)
20 O2O | -[SocketIOManager connect] (SocketIOManager.m:126)

**Comment by leehonn** [comment]
Thank you,sir.I have solved the question. App can crash Because of querystring urlcode.Your urlcode method of SocketExtensions class has less allowdCharacters.If client has other characters in pragrams, percentEncodedQuery of urlWebSocket would crash.
