### ISSUE TITLE
Could not complie with Objective C project - Xcode 9.4

### ISSUE THREAD

**Issue by MD04-TanTan** [socketio/socket.io-client-swift#1069]
I installed socket.io-client-swift lib success from cocoapods (no errors) but then Xcode can not complie. Who can help me intergrated this lib into my objective c project. Thanks!

**Comment by huforrest** [comment]
@MD04-TanTan I have the similar problem. But I could not complie with Swift project (Swift 4, Xcode 9.4.1). And I installed Socket.IO-Client-Swift (13.2.1). I wonder whether Socket.IO-Client-Swift (13.2.1) support Swift 4.

**Comment by huforrest** [comment]
@MD04-TanTan I finally solved this problem. Here is my solution:
1 I go to Build Settings > Swift Language Version, and I set the swift version to 4.1
2 In Podfile I changed Socket.IO-Client-Swift version to 13.3.0 like this pod 'Socket.IO-Client-Swift', '~> 13.3.0'
3 pod update

**Comment by nuclearace** [comment]
@MD04-TanTan Is your problem solved?

**Comment by WeilerCode** [comment]
@MD04-TanTan add `use_frameworks!` to Podfile

**Comment by nitishmaropost** [comment]
@huforrest : Thanks. This fixed the issue.
