### ISSUE TITLE
socket.io-client-swift & cocoa pods

### ISSUE THREAD

**Issue by rpwilsonrph** [socketio/socket.io-client-swift#107]
I am importing the code into an Objective-C project. Cocoa pods imports correctly. It compiles and links correctly but it will not generate the .h when the Swift is sitting in the Pods project. If I move the code to the app project, the .h generates correctly. Is there a trick to getting the .h generated without having to move the Swift code into the app project?

**Comment by nuclearace** [comment]
This is a question I have no idea how to answer, I don't really use CocoaPods much.

**Comment by NachoSoto** [comment]
@rpwilsonrph what do you mean by "it will not generate the .h"? What header are you referring to?

**Comment by danipralea** [comment]
@rpwilsonrph the header file is automatically generated. See http://swiftoverload.com/using-swift-in-your-objective-c-project/
