### ISSUE TITLE
How do I achieve a call back using emit function

### ISSUE THREAD

**Issue by huforrest** [socketio/socket.io-client-swift#1074]
By using socket.io-client-swift, how do I achieve a call back on the client side using emit function? Just like this:

// client code
socket.emit('ferret', 'tobi', (data) => {
  console.log(data); // data will be 'woot'
});

// server code
io.on('connection', (socket) => {
    socket.on('ferret', (name, fn) => {
      // send ACK response
      fn('woot');
    });
});

**Comment by huforrest** [comment]
The client code I have posted above is written in javascript, what I wanna know is that how to write it in socket.io-client-swift. It seems that socket.io-client-swift only provides the following two functions:
open func emit(_ event: String, _ items: SocketData...)
open func emit(_ event: String, with items: [Any])

**Comment by nuclearace** [comment]
If you want to emit with an ack it would look like.

```swift
socket.emitWithAck("canUpdate", cur).timingOut(after: 0) {data in
   // do something with data
}
```
