### ISSUE TITLE
SocketManger.config

### ISSUE THREAD

**Issue by tradingstratagem** [socketio/socket.io-client-swift#1078]
Hello,

I think there is a small issue when the SocketManager.config is modified.

Here is my test, I initialise the SocketManager as follows:
`self.socketManager = SocketManager(socketURL: URL(string: "https://example.com")!, config: [
            .log(false),
            .compress
            ])
`

Then I update the config and add the connectParams:
`
self.socketManager?.config = [
                .connectParams(connectParameters)
            ]
`

At this point when i Try to connect, the SocketManager removes the secure flag and tries to connect to "**http**://example.com" rather than "**https**://example.com"

I have to explicit pass the **secure(true)** param when modifying the config like this:
`self.socketManager?.config = [
               .secure(true),
                .connectParams(connectParameters)
            ]
`

I think this is probably a bug because if I pass the connectParams on the initialisation and I don't change the config it works without passing **secure(true)**.

**Comment by nuclearace** [comment]
Yeah this looks like a bug.
