### ISSUE TITLE
Multiple Connections

### ISSUE THREAD

**Issue by lucianocn** [socketio/socket.io-client-swift#108]
Every time I connect SocketIO (even using as a property) it creates a new connection and do not disconnect old ones. How can I force it to keep only one connection?

    @property (nonatomic, retain) SocketIOClient *socketIOClient;
    ....
    _socketIOClient = [[SocketIOClient alloc] initWithSocketURL:@"localhost" options:nil];

**Comment by nuclearace** [comment]
How are you closing the old socket?

**Comment by ninehundredt** [comment]
I have also been having issues with the disconnect function. How can I enable logging to investigate further? Thanks in advance.

**Comment by nuclearace** [comment]
```swift
let socket = SocketIOClient(socketURL: "blah", opts: ["log": true])
```

**Comment by ninehundredt** [comment]
Appreciate it!

**Comment by hanishabsigh** [comment]
@lucianocn @ninehundredt have you guys made any progress on this?

**Comment by nuclearace** [comment]
I haven't been able to reproduce it.

**Comment by lucianocn** [comment]
@hanishabsigh I solved handling the socket in a singleton and disconnecting it when necessary. So it do not multiply the connections each connect.
