### ISSUE TITLE
Pod V13.3.0 - Complier Error in Xcode 10 ( beta 10 )

### ISSUE THREAD

**Issue by JadianZheng** [socketio/socket.io-client-swift#1081]
## Same to title, I meet the follow error.
![screen shot 2018-09-04 at 15 59 21](https://user-images.githubusercontent.com/3894891/45018291-512a3300-b05c-11e8-9fc1-39c02b6ecb66.png)
Hope for help, thank you.

**Comment by nuclearace** [comment]
@JadianZheng Make sure the SWIFT_VERSION flag is set to 4 or higher.

**Comment by JadianZheng** [comment]
@nuclearace I had set the swift version to 4.2 or 4 before the error happen. 

## But as you say, I try the follow step, the error disappear: 
1. Remove `Pods` and `Podfile.lock`
2. Clear `builds` and `Deived Data` 
3. Reset the target's `swift version` to 4
4. Reinstall all pods
**(Hope this can help others)**
