### ISSUE TITLE
ERRORS AFTER UPDATING SOCKET 

### ISSUE THREAD

**Issue by ramtal** [socketio/socket.io-client-swift#1082]
After updating Socket.io  i am getting below issues

1.DefaultSocketLogger.Logger -error -Cannot call value of non-function type 'Bool'
2.Method 'setConnected' with Objective-C selector 'setConnected:' conflicts with setter for 'connected' with the same Objective-C selector
3.Cannot use instance member 'socket' within property initializer; property initializers run before 'self' is available

**Comment by nuclearace** [comment]
Duplicate of #1081
