### ISSUE TITLE
socket.io连接，获取视频流h264

### ISSUE THREAD

**Issue by CxyBlue** [socketio/socket.io-client-swift#1084]
第一个视频流返回数据
视频流H264:(
    <>
)
接着第二个正常，
视频流H264:(
    <00000001 6742801e da06c186 806d0a11 50000000 0168ce06 e2>
)
第三个返回显示一大半，并不全
视频流:(
    <00000001 65b840a7 fff84184 500023f0 021ba4b1 8ae37d91 2b52d3ac 04000383 80f9a1fe bef1840f e02328f9 f9efdbc1 91bf3c12 7f32a0ad 7afc331b 7a5eff9e 15a7c38f fa5b8bd2 8f7d3a9b b65373d3 9e1568ad e78cf7ff fe1340ba 00191b4d 8b5e565f 1728cbc6 1b520c4d 5ee23bf1 85f243ff fa89c30e fa0c00ee cda23160 7f2e7650 8adec3c9 44a2f075 df195799 139f9788 53328b91 11e1e231 5e624dda 8ada8ace afd26e4d ffffce09 70022ab7 90708694 3283d137 4e6ffc0c 4be3f801 055b6879 357ce9d1 9064ff73 78ed1182 bfbfe02f ffb15759 b277f440 08bbffd7 a81dc27f 801beb08 e513af36 1db4b1ba dc30de84 ae9abc28 fb6557cd c1b5f53d f40074f8 751945d2 7a82ff8b eff69fd5 b1713330 d304eb2f 7cf126aa 74345fff f1515857 800c9e72 f0ccf3d0 fcfd3978 bc01b5c4 e4c71e5c dd349813 6d3a582b 4fc5ee71 ee766f6c ffbe10e3 fc089b96 e60dbe99 86650638 02c992eb 8725af7f ac194bd6 a231ff80 09ab8e5e 199e7cd5 fa6f43c7 a3a0ef7f 0dd7ff95 ae8bffc7 f010fc04 c0615c92 55e1ff55 3f006d5f e6110fbf 40c230ad dedd7fe2 816af25a ad02740a 74d3e18d 9b4d0ff9 fcffc16c 64d9a15f 7de36c46 d3dffffc 89e141d 到这没了
这算不算是丢包？？

**Comment by lianxiang1** [comment]
你们用的接收中文 会不会乱码？该怎么处理

**Comment by nuclearace** [comment]
Bug reports should be submitted in english.
