### ISSUE TITLE
connect socketIO with options in swift

### ISSUE THREAD

**Issue by sanyamjain65** [socketio/socket.io-client-swift#1085]
I am trying to use socketIO for one of my projects. I need to use following options while connecting to my socketIO server.

 let socketConfig = SocketIOClientOption.self
    socketConfig.forceNew(true)
    socketConfig.reconnects(true)
    socketConfig.reconnectAttempts(10)
    socketConfig.reconnectWait(6000)
According to socketIO docs (https://github.com/socketio/socket.io-client-swift) i am not able to find a way to pass SocketIOOptions while connecting. i have been trying to use below code to connect but it fails due to absence of these options

let manager  = SocketManager(socketURL: URL(string: "myurl:9476")!, config: [.log(true), .connectParams(["key":"value"])])
        let socket = manager.defaultSocket
SocketIO version used:- 'Socket.IO-Client-Swift', '~> 13.3.0'

**Comment by nuclearace** [comment]
@sanyamjain65 Configs are added on the manager, and are passed down to sockets.

**Comment by liuhuan3344** [comment]
Thank you. You're done.

**Comment by liuhuan3344** [comment]
Thank you. Deal with it.

**Comment by liuhuan3344** [comment]
Thank you.

**Comment by sanyamjain65** [comment]
I figured out the solution.
The way to include options has been revised in the latest version.
I did the following and it worked:-

    manager  = SocketManager(socketURL:  URL(string:"myurl:123")!, config: [.log(true), .forceNew(true), .reconnectAttempts(10), .reconnectWait(6000), .connectParams(["key":"value"]), .forceWebsockets(true), .compress])
    socket = manager?.defaultSocket

**Comment by sanyamjain65** [comment]
@nuclearace Thanks for the help.
