### ISSUE TITLE
Why does IOS client code use isoLatin1?

### ISSUE THREAD

**Issue by kkwd** [socketio/socket.io-client-swift#1087]
Why does IOS client code use isoLatin1?

**Comment by nuclearace** [comment]
What? The client doesn't use isoLatin1, it uses unicode. And the latest version of the client only works with socket.io 2.0, since the way that unicode was encoding changed between 1 and 2.

**Comment by kkwd** [comment]
The ISO terminal is a small end encoding.

**Comment by nuclearace** [comment]
Once strings get to you, they should be standard Swift strings, which are fully unicode compatible. What issues are you seeing?

**Comment by kkwd** [comment]
Android and Web Chinese normal, IOS client Chinese garbled, server UTF-8

**Comment by nuclearace** [comment]
What server version? The current version of the client only supports socket.io 2.0. If your server is 1.0 you will see garbled unicode, since there was a breaking change between 1 and 2.

**Comment by lianxiang1** [comment]
hi I have the same problem @nuclearace 
`//NSData *jsonData = [jsonString dataUsingEncoding:NSUTF8StringEncoding];
    
    NSData *jsonData = [jsonString dataUsingEncoding:NSISOLatin1StringEncoding];`

When I use NSUTF8StringEncoding to parse callback data ，Chinese is messy code. but ,use NSISOLatin1StringEncoding is right.

**Comment by nuclearace** [comment]
@lianxiang1 What server version? See my above post.

**Comment by kkwd** [comment]
Other project versions of server 1.7.16 https://github.com/mrniko/netty-socketio

**Comment by nuclearace** [comment]
Looks like that only supports socket.io 1.0, so the current version of the client will not work with it, you'll see your issue. You'll have to use the [1.0 branch](https://github.com/socketio/socket.io-client-swift/tree/1.0-swift4). Note that it's no longer supported however.

**Comment by nuclearace** [comment]
Looks like there's an issue on that project about it. https://github.com/mrniko/netty-socketio/issues/566

**Comment by kkwd** [comment]
Thank you

**Comment by lukes-qbsw** [comment]
My solution. It is not perfect, but I can use last version of this library with netty-socketio server.

```
let commentUUID = socket.on(kSocketComments) { data, ack in
            guard let message = data.first as? String else { return }
            if let data = message.data(using: String.Encoding.isoLatin1), let newMessage = String.init(data: data, encoding: String.Encoding.utf8) {
                print("socket comments message: \(newMessage)")
            }
        }
```
