### ISSUE TITLE
The socket. on method does not execute

### ISSUE THREAD

**Issue by liuhuan3344** [socketio/socket.io-client-swift#1091]
The socket. on method does not execute, but the socket is already connected. What's the problem, please?
<img width="825" alt="ee2d3644-8664-48a1-8859-374b91ff8cad" src="https://user-images.githubusercontent.com/20061688/45615360-da9b2580-ba9e-11e8-83f6-3616b9d4de83.png">

<img width="900" alt="44c5b4bf-fa9d-4a1d-b514-3a26252f3e9a" src="https://user-images.githubusercontent.com/20061688/45615346-d1aa5400-ba9e-11e8-98af-002477433a60.png">

**Comment by nuclearace** [comment]
@liuhuan3344 Make sure you store the `SocketManager`, if that isn't properly retained, nothing will connect.
