### ISSUE TITLE
Thread 3: signal SIGABRT while using SocketIO

### ISSUE THREAD

**Issue by sanyamjain65** [socketio/socket.io-client-swift#1093]
HI,
I am trying to create a dynamic framework in swift which uses SocketIO to connect to nodejs server and share data.
SocketIO is successfully installed and compiled via Cocoapods in my framework. Framework is build successfully but when i use this framework in one of my app i got the error "Thread 5: signal SIGABRT"
where i instantiate the SocketManager.
`let manager  = SocketManager(socketURL:  URL(string: "myURL")!, config: [.log(true), .compress])`
i tried to print the description of manager in my debugger output console and it says 

> Printing description of self.manager:
expression produced error: error: /var/folders/bc/pr38clts7b963ddftc9zc1n00000gn/T/expr13-2fc3c6..swift:1:99: error: use of undeclared type 'SocketIO'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Swift.ImplicitlyUnwrappedOptional<SocketIO.SocketManager>>(bitPattern: 0x1059e03e0)!.pointee)

I am not able to figure what i am doing wrong......Please help me real quick i have deadlines to meet.

**Comment by nuclearace** [comment]
@sanyamjain65 I'm not sure what's going on here. I would double check that you've followed the standard CocoaPods installation. (The one in the README makes assumptions that you know how to use CocoaPods)

**Comment by sanyamjain65** [comment]
@nuclearace i found what the problem was.
If any third party libraries/ frameworks are used in a dynamic framework then those libraries/frameworks should also be present in the app your custom framework is used.
hence, i just needed to install the SocketIO framework using cocoapod in the app in which i was installing my custom framework.
and also thanks for your help.
