### ISSUE TITLE
Socket Connection is disconnected after app goes to background

### ISSUE THREAD

**Issue by aamerkhalid** [socketio/socket.io-client-swift#1094]
Hi
I am developing an app for getting data in real time but after app goes to background Socket Connection disconnect. 
after switching internet Wifi to 4G my connection again disconnect.

**Comment by nuclearace** [comment]
Yes, background execution is not explicitly supported with this library. You can try various ways of tricky iOS to giving you a little bit more time in the background, but generally iOS will close connections that go into the background.
