### ISSUE TITLE
not able to compile on Xcode10

### ISSUE THREAD

**Issue by bignuctsl** [socketio/socket.io-client-swift#1095]
**Crash info**
dyld: Symbol not found: __T0BOWV
  Referenced from: /Users/admin/Library/Developer/CoreSimulator/Devices/4D4A399D-C727-47D7-BA5E-236CE5DAD713/data/Containers/Bundle/Application/8A531D63-C0BB-4C17-9DC1-49A8D135A8A3/DingGuaGua.app/Frameworks/Starscream.framework/Starscream
  Expected in: /Users/admin/Library/Developer/CoreSimulator/Devices/4D4A399D-C727-47D7-BA5E-236CE5DAD713/data/Containers/Bundle/Application/8A531D63-C0BB-4C17-9DC1-49A8D135A8A3/DingGuaGua.app/Frameworks/libswiftCore.dylib
 in /Users/admin/Library/Developer/CoreSimulator/Devices/4D4A399D-C727-47D7-BA5E-236CE5DAD713/data/Containers/Bundle/Application/8A531D63-C0BB-4C17-9DC1-49A8D135A8A3/DingGuaGua.app/Frameworks/Starscream.framework/Starscream

**use Cartfile install**    Xcode9 no problem

**Comment by JessieWu0921** [comment]
I have the same issue. the same crash info

**Comment by tutu1990** [comment]
I have the same issue. the same crash info
