### ISSUE TITLE
how to connect url like " ws://123.207.167.163:9010/ajaxchattest "

### ISSUE THREAD

**Issue by FLGiOS** [socketio/socket.io-client-swift#1098]
NSURL*url = [NSURL URLWithString:@"ws://123.207.167.163:9010"];

        _manager = [[SocketManager alloc] initWithSocketURL:url config:@{@"log" : @YES, @"forcePolling" : @YES, @"nsp" : @"/ajaxchattest"}];
        _client = _manager.defaultSocket;
        //连接SOCKET
        [_client on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
            NSLog(@"socket connected");
        }];

it does not work!

**Comment by nuclearace** [comment]
@FLGiOS Is this a socket.io server? This library won't work with any WebSocket server. If you need that, checkout https://github.com/daltoniam/Starscream.
