### ISSUE TITLE
Allow . to match any character, including line separators.

### ISSUE THREAD

**Issue by hanishabsigh** [socketio/socket.io-client-swift#11]
First...thank you for this library. I was experiencing an issue in which a large incoming event wasn't being passed to the appropriate on: handler. No error was thrown. After some investigation, I narrowed it down to regex operations that weren't outputting valid json, thus leading the NSJSONSerialization to fail. Here is an example of the regex, although it happens a few times within the library:

    var mutMessage = RegexMutable(stringMessage)
    let messageGroups = mutMessage["(\\d*)\\/?(\\w*)?,?(\\d*)?(\\[.*\\])?"].groups()

The end of the regex uses a . to match any character, but by default it does not match line separators. If the intent is to include them, SwiftRegex lets us set the option NSRegularExpressionOptions.DotMatchesLineSeparators. I attempted a pull request to do the following but it wasn't working for me:

    var mutMessage = RegexMutable(stringMessage)
    let messageGroups = mutMessage["(\\d*)\\/?(\\w*)?,?(\\d*)?(\\[.*\\])?",NSRegularExpressionOptions.DotMatchesLineSeparators].groups()

I must be missing something, I thought that subscript would work but it crashes for me. The following did work:

    var mutMessage = RegexMutable(stringMessage)
    var swiftRegex = SwiftRegex(target: mutMessage, pattern: "(\\d*)\\/?(\\w*)?,?(\\d*)?(.*)?", options: NSRegularExpressionOptions.DotMatchesLineSeparators);
    let messageGroups = swiftRegex.groups()

Also, it could be helpful to include a warning when the event parsing fails. Thanks!

**Comment by nuclearace** [comment]
@hanishabsigh can you provide a message that fails to get parsed. You can uncomment https://github.com/socketio/socket.io-client-swift/blob/master/SwiftIO/SocketEngine.swift#L409 to see messages before they get sent to the socket.io-client parser.

**Comment by nuclearace** [comment]
I'm actually finding a few problems with regex. Mostly due to the differences between NSString and String.

**Comment by hanishabsigh** [comment]
My object that fails is very large, here is an example I was able to track down:

The following fails:

    "42[\"auto\",{\"message_of_the_date\":\"line one\nline two\"}]"

The following succeeds:

    "42[\"auto\",{\"message_of_the_date\":\"line one line two\"}]"

The line break in the message of the day causes the parsing of the groups to break.

**Comment by hanishabsigh** [comment]
@nuclearace I just noticed you made some parsing changes, this was tested prior to those changes, thanks

**Comment by nuclearace** [comment]
@hanishabsigh It seems to work for me on the latest. Please note #13 though. Since it can cause the regex to fail sometimes. Which is why I changed some things.

**Comment by hanishabsigh** [comment]
@nuclearace This still isn't working for me, incoming messages can't even get passed the following line: https://github.com/socketio/socket.io-client-swift/blob/e932d0a26ba81573545ca055660dcb41e277e0fe/SwiftIO/SocketParser.swift#L224

Replacing line 224 with the following worked:

    let messageGroups = stringMessage["(\\d*)\\/?(\\w*)?,?(\\d*)?\\[\"(.*?)\",?(.*?)?\\]$", NSRegularExpressionOptions.DotMatchesLineSeparators].groups()

**Comment by nuclearace** [comment]
@hanishabsigh try after 44e27810766a6ff4879d888bbab220ea8ef6073b

**Comment by hanishabsigh** [comment]
Checking against the latest commit isn't working, something about the changes in SwiftRegex. So far from what I can tell regex.firstMatchInString in the groups method isn't returning anything. Still investigating. Thanks

**Comment by nuclearace** [comment]
This client is able to get this for me:
```javascript
socket.emit("jsonTest", {foo: "string\ntest test"})
```

**Comment by hanishabsigh** [comment]
Ok, fixed it by changing the following:

    final var targetRange: NSRange {
        return NSRange(location: 0,length: countElements(target))
    }

To this:

    final var targetRange: NSRange {
        return NSRange(location: 0,length: target.utf16Count)
    }

I think the error I was experiencing was happening because my json had variable-width Unicode characters. Found someone having the same issues with swift on StackOverflow: http://stackoverflow.com/questions/25882503/how-can-i-use-nsregularexpression-on-swift-strings-with-variable-width-unicode-c

**Comment by nuclearace** [comment]
@hanishabsigh so does https://github.com/socketio/socket.io-client-swift/commit/c67e7a3003fc5e9c218335fedec02b643dd7fcfb fix it

**Comment by hanishabsigh** [comment]
Yes, that commit fixes it, thanks.

**Comment by Katafalkas** [comment]
![screen shot 2015-03-19 at 13 12 34](https://cloud.githubusercontent.com/assets/1636440/6729297/a31bafc6-ce39-11e4-92f7-137aeaa84357.png)
![screen shot 2015-03-19 at 13 13 00](https://cloud.githubusercontent.com/assets/1636440/6729300/afffa9fe-ce39-11e4-9871-377c98e53ab7.png)

```
From Xcode 6.3 beta 3 release notes:
>`utf16Count` is removed from String. Instead use count on the UTF16 view of the String. (17627758)
```
