### ISSUE TITLE
Change connectParams doesn't work 

### ISSUE THREAD

**Issue by tradingstratagem** [socketio/socket.io-client-swift#1100]
Hi,

I'm trying to change the connectParams after I disconnect but is not working.

`
self.socketManager?.config = [
    .connectParams(connectParameters)
]
`
The first time that the code is execute works, then I disconnect the socket, update the params and reconnect again and the parameters passed are the same as the previous connection.

Any suggestions?
Could be a bug?

**Comment by nuclearace** [comment]
What params, and what version are you using?

**Comment by tradingstratagem** [comment]
Params: strings, like token:<jwt token>
Version: 13.3.1

**Comment by tradingstratagem** [comment]
any news here?

**Comment by canaksoy** [comment]
`class SocketIOManager: NSObject {
    
    static let sharedInstance = SocketIOManager()
    
    var manager : SocketManager! // SocketManager(socketURL: chatUrl)
    var socket: SocketIOClient!
    
    private override init() {
        
        super.init()
    }
    
    func establishConnection() {
        socket.connect()
    }
    
    func closeConnection() {
        socket.disconnect()
    }
    
    func createManager() {
        manager = SocketManager(socketURL: AppCache.shared.socketUrl, config: [.log(true), .forceNew(true), .compress, .connectParams([
            "token" : AppCache.shared.token,
            "conversation_id": AppCache.shared.convID
            ]) ])
        socket = manager.socket(forNamespace: "/chat")
    }
    
    func releaseManager() {
        manager = nil
        socket = nil
    }
    
}`

using manager like this. solved my same problem

**Comment by elliotstokes** [comment]
Ive also found the same issue.

**Comment by ffleandro** [comment]
What should be the correct for to call `connect` or `disconnect`?
On the manager or the socket?
