### ISSUE TITLE
Swift4.2

### ISSUE THREAD

**Issue by lixiang1994** [socketio/socket.io-client-swift#1101]
And .podspec Add s.swift_version = "4.2" , Please

**Comment by stardustWK** [comment]
1 should remove `.swift-version` file
2 in `Socket.IO-Client-Swift.podspec` file should remove `s.pod_target_xcconfig = {
      'SWIFT_VERSION' => '4.0'
  }`,  and add `s.swift_version = '4.2'`

**Comment by stardustWK** [comment]
for the user, an other solution: add code in your podfile
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
      if ['socket.io-client-swift'].include? target.name
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.2'
          end
      end
  end
end
```
