### ISSUE TITLE
使用 cocoapods 安装后，创建的swift 的controller 不能创建

### ISSUE THREAD

**Issue by FLGiOS** [socketio/socket.io-client-swift#1104]
![2018-10-09 1 39 10](https://user-images.githubusercontent.com/15762711/46648720-e1621780-cbc8-11e8-9179-c4094e98e201.png)
![2018-10-09 1 39 24](https://user-images.githubusercontent.com/15762711/46648723-e626cb80-cbc8-11e8-8c8e-57681444b987.png)

**Comment by nuclearace** [comment]
This doesn't look like an issue with this library.
