### ISSUE TITLE
the tripartite framework （**socket.io-client-swift**）is error

### ISSUE THREAD

**Issue by OuMeng1991** [socketio/socket.io-client-swift#1107]
I use a tool（**CocoaPods**） to manage the tripartite framework （**socket.io-client-swift**）,But the inside of the file is error. Error please look at pictures.  How should I solve it？thank you.

![65708d36-5f79-410b-9da4-13bfd8cc923e](https://user-images.githubusercontent.com/14834283/46778316-c36df180-cd45-11e8-87eb-5db16553511e.png)
![c7644af7-e1c7-486d-9035-6c63f9a7e274](https://user-images.githubusercontent.com/14834283/46778317-c4068800-cd45-11e8-8d64-dd1cef580100.png)
![cb523114-045b-46d8-b8c9-ccb76c2a5798](https://user-images.githubusercontent.com/14834283/46778318-c4068800-cd45-11e8-80c2-b417b7f20b5f.png)
![d5c94ae6-fc52-46d5-9d1a-da74728ef45c](https://user-images.githubusercontent.com/14834283/46778319-c4068800-cd45-11e8-8e01-1bc20c7e588c.png)

**Comment by nuclearace** [comment]
Make sure you do a clean CocoaPods install and check all Swift versions, this happens if the Swift version is not set correct. It should be a min of Swift 4.

**Comment by OuMeng1991** [comment]
> Make sure you do a clean CocoaPods install and check all Swift versions, this happens if the Swift version is not set correct. It should be a min of Swift 4.

Thanks!This problem has solved.
