### ISSUE TITLE
No such module 'Starscream'

### ISSUE THREAD

**Issue by balkrishanyadav** [socketio/socket.io-client-swift#1108]
Hello ,
 I downloaded ios client socket.io and drag source folder in to my app and try to build then getting error No such module 'Starscream'
 When i have added manually new version of socket.io-client-swift

Please reply for the same.

**Comment by nuclearace** [comment]
Installing from source is no longer supported. You should use one of the package managers to install the lib.

**Comment by pulkitbabbar34** [comment]
Hello, Can you tell me from where I should use the package managers to install the lib.
