### ISSUE TITLE
Emit Dictionary in Objective-C

### ISSUE THREAD

**Issue by TalhaAkkas** [socketio/socket.io-client-swift#111]
In objective-c emitObj (active pod) method gives warning.
I patched it for current repo.  
![screen shot 2015-07-06 at 09 37 58](https://cloud.githubusercontent.com/assets/632596/8516885/ba64d71e-23c2-11e5-91b9-8e44dc67b209.png)

**Comment by nuclearace** [comment]
This isn't really a problem. The reason it takes an array is because socket.io lets you send multiple items per message. With Swift it's easy to get around using variadic parameters. I'm not aware of an easier Objective-C solution than to use the equivalent array of AnyObject.

```swift
// Swift
public func emit(event:String, _ items:AnyObject...)

// Objective-C
public func emit(event:String, withItems items:[AnyObject])
```
