### ISSUE TITLE
Socket.IO-Client-Swift/SocketIO.modulemap' not found

### ISSUE THREAD

**Issue by ChiragBhutani1988** [socketio/socket.io-client-swift#1111]
I have installed Socket.IO swift client by using cocoapods in one of my existing projects which already uses pods as dependency manager using the following syntax 
    pod 'Socket.IO-Client-Swift', '~> 13.3.0'

When I build my project I get the following error :-

fatal error: module map file '/Users/.../Library/Developer/Xcode/DerivedData/BCFramework-gonnmbjihouijhdwfmfuaicivlmn/Build/Products/Debug-iphonesimulator/Socket.IO-Client-Swift/SocketIO.modulemap' not found

Please help as I am not able to find the answer to this issue using google.

**Comment by nuclearace** [comment]
Are you using the latest Xcode and a clean CocoaPods install?

**Comment by ChiragBhutani1988** [comment]
I am using it in one of my existing project. Earlier I was using an old version of Socket.io client and now I have deleted the old files which I had added manually and I am trying to update it using cocoapods.

I am using XCode10.0 and I am using an existing podfile for this. I didn't understand the meaning of "a clean CocoaPods install". Please explain.
