### ISSUE TITLE
Connecting via SocketManager, how to specify resources?

### ISSUE THREAD

**Issue by Rishat7c** [socketio/socket.io-client-swift#1113]
In Java, when creating a connection, you can specify the resource where we will apply. Unfortunately in the Swift documentation I did not find it :(
Apparently, it looked bad.

I have a server which is located on the connection web server
```JavaScript
io.set("http://localhost:3000", "/api");
```

How the connection happens in Java:
```Java
IO.Options opts = new IO.Options ();
opts.query = "api";
socket = IO.socket ("https: // localhost: 3000", opts)
```

How I try to connect to Swift
```Swift
let manager = SocketManager (socketURL: URL (string: "https: // localhost: 3000")! config: [.log (true), .compress])
```
In the class of SokketManager, I did not find the necessary parameter about the resource for me, where should I shove it when connecting "/api"?

**Comment by nuclearace** [comment]
If I remember the server api, what you want is to use the [path](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:8SocketIO0A14IOClientOptionO4pathACSScACmF) option.

```swift
SocketManager(socketURL: someURL, config: [.path("/api")])
