### ISSUE TITLE
Feature request - Option for using web sockets via Network.framework

### ISSUE THREAD

**Issue by OneSman7** [socketio/socket.io-client-swift#1114]
Hello! Apple released a cool framework for working with sockets - Network.framework.

Starscream library on which this library depends will introduce support for using this framework in near future. See https://github.com/daltoniam/Starscream/issues/521 and new `WSStream` implementation - `NetworkStream`.

These future changes are already available in a separate branch.

It will be great to have a `SocketIOClientOption` to use this new socket implementation on iOS 12 if we wish to opt to it. This option may be marked by `@available(iOS 12.0, *)` attribute.

**Comment by nuclearace** [comment]
I'm not sure Network is going to be long term future. Starscream is actually thinking about moving to [NIO](https://github.com/apple/swift-nio) and [NIO Transport Services](https://github.com/apple/swift-nio-transport-services). Which would allow this lib to be used from all Swift supported platforms, not just Apple ones.

**Comment by nuclearace** [comment]
But regardless, I plan to keep Starscream up-to-date. So if Starscream goes with Network, so to will this lib.

**Comment by OneSman7** [comment]
Oh. I see, I was not aware of the plans, just researched about a concrete framework.

I saw that Starscream abstracted the transport into streams (implementations of `WSStream` protocol).

So I thought that it will be a good idea to have an option in this lib to select which stream to use. Thus every client will be able to adjust configuration based on its platform and other parameters.

**Comment by OneSman7** [comment]
If you mean that it will be supported as soon as Starscream releases this functionality I can close this issue.

**Comment by nuclearace** [comment]
Yes, if Starscream releases a new version that includes `Network`, it'll be incorporated into this lib.

**Comment by OneSman7** [comment]
Ok. closing this issue.
