### ISSUE TITLE
No such module found 'CommonCrypto' ->13.3.1 version

### ISSUE THREAD

**Issue by khimani91** [socketio/socket.io-client-swift#1115]
No such module found "CommonCrypto"
Pod Startscream in "Websocket.swift" file line no 24

**Comment by nuclearace** [comment]
@khimani91 Make sure you do a clean pod install.

**Comment by khimani91** [comment]
I have used Xcode 9.4.1 and I have done this command also still error...

**Comment by nuclearace** [comment]
Hm... It looks like Starscream doesn't support Xcode 9 anymore. That's a bit annoying they did it in a minor version.

**Comment by huapeng222** [comment]
Lock this link
https://github.com/daltoniam/Starscream/issues/575
add pod 'Starscream', '<= 3.0.5'
