### ISSUE TITLE
SocketManager(socketURL.. Method not found.

### ISSUE THREAD

**Issue by balkrishanyadav** [socketio/socket.io-client-swift#1116]
Hello 
I am implementing socket client for iOS with swift 4.2. I am getting error for create socket object using socket URL.
![screen shot 2018-10-23 at 6 29 18 pm](https://user-images.githubusercontent.com/6735695/47362237-99c3ab80-d6f1-11e8-85c1-11f24407d931.png)

let manager = SocketManager(socketURL: URL(string: "http://localhost:8080")!, config: [.log(true), .compress])
let socket = manager.defaultSocket

**Comment by nuclearace** [comment]
@balkrishanyadav You should probably read the [12to13](https://nuclearace.github.io/Socket.IO-Client-Swift/12to13.html) guide as well as the [FAQs](https://nuclearace.github.io/Socket.IO-Client-Swift/faq.html). The example on the readme also shows how to create clients.
