### ISSUE TITLE
Cannot send emoji

### ISSUE THREAD

**Issue by wchuang** [socketio/socket.io-client-swift#1117]
Hi all, 

I got an error message when I sending an emoji string, there is the error message from Socket.io: `SequelizeDatabaseError: Incorrect string value: '\xF0\x9F\x98\x8E' for column 'content' at row 1`.

This is because when the emoji string be encoded to UTF8 string which is 4 bytes, but Socket.io is not support this? And I have some confuses why there are database access in Socket.io?

The Socket.io version is using 13.3.1.

Does anyone face this situations? 
Would appreciate for your advice. 💯

**Comment by nuclearace** [comment]
What version of the server is this? This sounds like some socket.io 1.0 vs 2.0 issue. 2.0 had a breaking change in the way unicode was sent over the wire.

**Comment by wchuang** [comment]
Many thanks for your reply. 
I will ask our backend engineer. But is it the server side's issues? Because it's be intercepted by socket.io swift client. So it cannot send anymore.

**Comment by Frankloll** [comment]
It still cannot send the Emoji. We use the latest version of Socket.io both on iOS client and server side.
Does anyone face this situation? Please give me some hint, thanks. :))

**Comment by wchuang** [comment]
It still cannot send the Emoji. We use the latest version of Socket.io both on iOS client (Objective-C) and server side.
Does anyone face this situation? Please give me some hint, thanks. :))

**Comment by nuclearace** [comment]
@wchuang I'm not able to reproduce this. I'm able to send and receive emoji just fine with the latest client and socket.io versions.
