### ISSUE TITLE
No such module CommonCrypto

### ISSUE THREAD

**Issue by dlpigpen** [socketio/socket.io-client-swift#1121]
Thanks for making a nice library. I got this error after I pod install successfully. Please give me a hint for help.

<img width="695" alt="screen shot 2018-11-14 at 11 05 57 am" src="https://user-images.githubusercontent.com/5404685/48459604-74f8ba80-e7fd-11e8-8055-93b58cb98e55.png">

**Comment by AmitPrajapatiagile** [comment]
Facing same issue!!

**Comment by AmitPrajapatiagile** [comment]
I was facing same issue. Solved!!
add pod 'Starscream', '<= 3.0.5'

**Comment by dlpigpen** [comment]
@AmitPrajapatiagile am
 it works for me. Thanks

**Comment by choumingg** [comment]
> I was facing same issue. Solved!!
> add pod 'Starscream', '<= 3.0.5'

it works for me. Thanks

**Comment by devtechvalens** [comment]
not worked for me

**Comment by yordivd** [comment]
i created a file in platforms/ios 
named: Podfile
with 1 line of content in it: pod 'Starscream', '<= 3.0.5'
but i'ts not changing anything? Am i doing something wrong?

**Comment by mostafaayman010030** [comment]
> pod 'Starscream', '<= 3.0.5'

when i added it this error appered
The version of CocoaPods used to generate the lockfile (1.7.5) is higher than the version of the current executable (1.5.2). Incompatibility issues may arise

**Comment by AmitPrajapatiagile** [comment]
@mostafaayman010030 Remove .lock file and again install the pod.
