### ISSUE TITLE
Swift 2 branch is not working

### ISSUE THREAD

**Issue by lightsprint09** [socketio/socket.io-client-swift#113]
I manually downloaded the Swift 2 branch and drag it into my project. After updating to HEAD of the branch (on Friday) no events were fired. Downgrading to an older version solved my error

**Comment by nuclearace** [comment]
Seems to be working for me.

**Comment by nuclearace** [comment]
@lightsprint09 Which version did you downgrade to?

**Comment by lightsprint09** [comment]
I think I downloaded the version during WWDC about 3-4 weeks ago

**Comment by nuclearace** [comment]
If your git branch is detached from HEAD if you do `git status` it should tell you what commit you're on.

**Comment by lightsprint09** [comment]
I donwloaded it manually. So there is no checkout point...

**Comment by Spriter** [comment]
I got the same problem as @lightsprint09. Any solution so far ?

**Comment by nuclearace** [comment]
Okay, I think I broke namespaces.

**Comment by lightsprint09** [comment]
namespaces seem to stop working again.

**Comment by nuclearace** [comment]
How are you trying to join the namespace?

**Comment by lightsprint09** [comment]
```
socket = SocketIOClient(socketURL: baseURL.absoluteString, opts: nil)
   socket!.on("update") {data, ack in
     dispatch_async(dispatch_get_main_queue()) {
     updateCallback(self.gameSerializer.deserializeGame(data!.firstObject as! NSDictionary))
   }
   }
        
        socket!.connect()
        socket!.nsp = "\(game.name)"
        socket!.joinNamespace()```

**Comment by nuclearace** [comment]
How about

```swift
socket!.nsp = "/\(game.name)")
```
