### ISSUE TITLE
Can't use SocketManager

### ISSUE THREAD

**Issue by nghminh163** [socketio/socket.io-client-swift#1133]
I install Socket.IO with Cocoapod but I can't use SocketManager. When I call SocketManager, xcode error:"'SocketManager' is unavailable: cannot find Swift declaration for this class". 
![image](https://user-images.githubusercontent.com/24296523/49699934-35f63300-fc0a-11e8-9c8b-6bf152e39138.png)
I think it's bug. Help me when you can. Thanks

**Comment by nuclearace** [comment]
Have you tried doing a clean install of your dependencies? Also make sure your Swift versions are set correctly in your targets.

**Comment by nghminh163** [comment]
i fixed by update xcode. Thanks a lots
