### ISSUE TITLE
send parameters about connect websocket 

### ISSUE THREAD

**Issue by wfy-answer** [socketio/socket.io-client-swift#1138]
hello,  i want ask you a question,  when i use this package ,i want send some parameters ,just like : http://localhost:8080?name=tom&id=123 , how to write code?

**Comment by nuclearace** [comment]
Use [connectParams](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:8SocketIO0A14IOClientOptionO13connectParamsyACSDySSypGcACmF)

**Comment by nuclearace** [comment]
@wfy-answer It would look something like:

```objective-c
NSDictionary* opts = @{@"connectParams": @{@"something": @"someValue"}};
```

**Comment by wfy-answer** [comment]
> @wfy-answer It would look something like:
> 
> ```objc
> NSDictionary* opts = @{@"connectParams": @{@"something": @"someValue"}};
> ```

thank you so much , last night my colleagues and me star your project ,haha
