### ISSUE TITLE
Unable to get the client working in OS X Console App on Yosemite

### ISSUE THREAD

**Issue by ddreier** [socketio/socket.io-client-swift#114]
I have this server app:
````
var app = require('http').createServer();

app.listen(8900);

var io = require('socket.io')(app);

io.sockets.on('connection', function(socket) {
	console.writeline('connection!');	
});
````

And I'm trying to get this little bit of Swift to connect:
````
import Foundation

println("Hello, World!")

let socket = SocketIOClient(socketURL: "localhost:8900")

socket.connect()

socket.onAny {println("got event: \($0.event) with items \($0.items)")}
socket.on("connect") {data, ack in
    println("socket connected")
}
````

But I have been unable to get it to connect. If I don't turn on logging I just get "Hello, World!", and if I do turn on logging I get the following:
````
Hello, World!
2015-07-07 21:43:57.842 SocketIOClientTest[13862:468956] SocketClient: Adding engine
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
````

I feel like I'm just missing something necessary to get it working (this is basically my first time using Xcode and programming in Swift).

Thanks!

**Comment by nuclearace** [comment]
If this this is just a straight OS X command line project you'll need to call CFRunLoopRun() at the end of main.swift I believe. Also, don't add handlers after calling connect. While they'll probably get added before it connects, it's better if you add them before.

**Comment by nuclearace** [comment]
I'll look more into it tomorrow though

**Comment by ddreier** [comment]
That did it! I don't know why (yet), but it's working now. That's the great thing about working on a new platform. :P

**Comment by nuclearace** [comment]
It's because by default with OS X command line programs they don't have a run loop, the program runs until it reaches the end of main.
