### ISSUE TITLE
event handler not called

### ISSUE THREAD

**Issue by kunwar231** [socketio/socket.io-client-swift#1140]
Socket events are logged but event handler are not called.
Sample code            
 self.socket.on(GeneralChat.gotMsg.rawValue) { (resp, emitter) in
            
            print(resp)
            completion(resp)       
}   
self.socket.connect()

**Comment by peihsendoyle** [comment]
the same here, and did not know why. Some events works, but some events don't work. But when debug (slowly), the completion handler is called (don't know why)??
<img width="1383" alt="Screen Shot 2019-03-27 at 1 54 53 PM" src="https://user-images.githubusercontent.com/7514128/55056149-ef80f300-5097-11e9-8fea-7b323d4ca329.png">

**Comment by kunwar231** [comment]
> Socket events are logged but event handler are not called.
> Sample code
> self.socket.on(GeneralChat.gotMsg.rawValue) { (resp, emitter) in
> 
> ```
>         print(resp)
>         completion(resp)       
> ```
> }
> self.socket.connect()

make sure you are defining the event handlers before connecting to the socket
