### ISSUE TITLE
No such module 'CommonCrypto'

### ISSUE THREAD

**Issue by OYQ** [socketio/socket.io-client-swift#1145]
I create a new project and just use :pod 'Socket.IO-Client-Swift', '~> 13.3.0'. But it build failed in file Starscream/WebSocket.swift.

![20190108154743](https://user-images.githubusercontent.com/16029650/50816827-bf5d6a00-135c-11e9-84e0-915e52203200.png)

The error message is ：
![20190108154631](https://user-images.githubusercontent.com/16029650/50816795-a05ed800-135c-11e9-9552-2ede00ca302d.png)

If adding  "pod 'Starscream', '<= 3.0.5' ", error show in cocoapods 
![20190108154936](https://user-images.githubusercontent.com/16029650/50816902-02b7d880-135d-11e9-8c4d-458e6a459365.png)

It resolved in Xcode10 with swift 4.2.But my project must support in Xcode9.

thx

**Comment by nuclearace** [comment]
Unfortunately Starscream broke SemVer with one of their versions. You'll have to use an older version of the client, or use the latest xcode. Starscreams's maintainers have stated they're not going to fix this.
