### ISSUE TITLE
Event Sending Failure 

### ISSUE THREAD

**Issue by sauvikatinnofied** [socketio/socket.io-client-swift#115]
In my current project some socket clients are connected to a common `namespace` in server side. All are listening to some events. One event is initiates by a user and sent to the server side. Server is emitting the event, so that all other clients are informed of that.

Most of the time things happen as expected. But sometimes we are facing the following scenarios,
  1. Event sending failed to the server side from a device initiating an event.
  2. Event is successfully sent to server side but sockets connection from all/ some other clients failed to  receive that event.
What may be reason behind that? Is there a proper way out ?

We are expecting maximum 100 individual devices to be connected to a specific  `namespace` at a time. Please help us.

**Comment by nuclearace** [comment]
I don't think this one is going to be easy to debug. My only suggestion would be to turn on socket logging and see if a client is trying to send/receive the events that fail.
