### ISSUE TITLE
_SwiftValue appears when focus on socket "statusChage" method in OC

### ISSUE THREAD

**Issue by webMing** [socketio/socket.io-client-swift#1152]
Hi nuclearace,I find this problem still exists. I`m sure my new version is v14.0.0
the same question is here: #1147

![](https://raw.githubusercontent.com/webMing/SFImages/master/SFImages/2E8B37B2-626E-40D0-9448-38979C1BC1DE.png)

The _SwiftValue type still can`t convert any OC type. @nuclearace

**Comment by nuclearace** [comment]
See [the test case](https://github.com/socketio/socket.io-client-swift/blob/master/Tests/TestSocketIOObjc/SocketObjectiveCTest.m#L105). It shows how to use the new form.
