### ISSUE TITLE
Socket Not listening when app is in background

### ISSUE THREAD

**Issue by RohitJoshi293** [socketio/socket.io-client-swift#1174]

**Comment by nuclearace** [comment]
Background execution is not supported. You'll need to use [alternative means](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html) when the app goes into the background.

**Comment by RohitJoshi293** [comment]
@nuclearace can u please suggest me something for get socket connected after terminate app. I want real time data when app is not running so i can send local notification.
