### ISSUE TITLE
xCode 10.2 + Carthage update = build error

### ISSUE THREAD

**Issue by Yelles** [socketio/socket.io-client-swift#1177]
Hi,

Not able to build with Carthage update, 

error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Starscream iOS')

seems that the last Xcode dropped support of Swift 3

**Comment by paulosaure** [comment]
Duplicate : https://github.com/socketio/socket.io-client-swift/issues/1175

**Comment by Yelles** [comment]
> Duplicate : #1175

Not really...

**Comment by nuclearace** [comment]
Yeah I found that reference while updating for the [next release](https://github.com/socketio/socket.io-client-swift/pull/1176). It should be fixed in the next release.

**Comment by zarochintsev** [comment]
I also ran into this problem. When will it be fixed?

**Comment by zarochintsev** [comment]
Yes, very nice, thanks.

**Comment by Gx952743985** [comment]
怎么解决的看不懂啊
