### ISSUE TITLE
Socket emit completion handler not called

### ISSUE THREAD

**Issue by peihsendoyle** [socketio/socket.io-client-swift#1178]
<img width="1383" alt="55056149-ef80f300-5097-11e9-8fea-7b323d4ca329" src="https://user-images.githubusercontent.com/7514128/55133918-e5272d80-5159-11e9-8ea9-ab0be9c8cb21.png">

It didn't step to the completion handler. When I debugged it (step by step slowly), it get called. I don't know the reason, please check it.

**Comment by nuclearace** [comment]
Hm, I think this might be a logic bug in the engine.

**Comment by sangnvus** [comment]
Hi Nuclearace
Can you tell me this version already support HTTP Proxy?

**Comment by sangnvus** [comment]
I tested with the previous version. It does not work when client connect to server via HTTP proxy and Socket Proxy
