### ISSUE TITLE
Carthage build is broken on 13.3.1 version

### ISSUE THREAD

**Issue by intoxicated** [socketio/socket.io-client-swift#1181]
I'm using xcode 10.1 and today I found that building with carthage has been broken due to swift version. The dependency "Starscream" recently updated its version to 3.1 and set its swift version to 5, does this mean I can't build with swift 4.2?

**Comment by intoxicated** [comment]
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Starscream')

Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Starscream')

** ARCHIVE FAILED **

so I guess once you set SWIFT_VERSION to specific version, its no longer to build with prior version of swift

**Comment by nuclearace** [comment]
You need to update to Xcode 10.2
