### ISSUE TITLE
Unable to install v15

### ISSUE THREAD

**Issue by NarasimhaDo** [socketio/socket.io-client-swift#1182]
We're trying to migrate from v14 to v15 and receiving following errors : 

error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Starscream')

error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'Socket.IO-Client-Swift')

Is there anything we're missing?

**Comment by nuclearace** [comment]
You need to update to Xcode 10.2.
