### ISSUE TITLE
Data size ~ 4MB is taking very long time to emit (~4 Mins).

### ISSUE THREAD

**Issue by InfiniteDreamz** [socketio/socket.io-client-swift#1184]
How can i use 'compress' SocketIOClientOption here. I am facing this problem during contact syncing process where I need to send around 12k contacts to the server. Sometimes it gets disconnected in b/w the process. However, on reattempting everything goes well.

**Comment by nuclearace** [comment]
You just need to pass the compress option when you create a manager. That being said, the time it takes to send things is dependent on the network connection the device has. The framework has little control over how long it takes to send messages.

**Comment by InfiniteDreamz** [comment]
@nuclearace Thanks for your response. So, I can expect this option to help me out there. Let me test it with my backend devs. I will get back to you for any further query. Thanks again !!
