### ISSUE TITLE
Receiving Unicode 

### ISSUE THREAD

**Issue by sujuCrystal** [socketio/socket.io-client-swift#1186]
Receive Chinese message, but received like this”\U00e8\U00b5\U009e\U00e4\U00ba\U0086\U00e4\U00bd\U00a0\U00e7\U009a\U0084\U00e8\U00af\U0084\U00e8\U00ae\U00ba”
Some say set @"doubleEncodeUTF8":@true, I tried ,but not solved
Xcode 10.2  Swift 5.0

**Comment by jaykon** [comment]
> Receive Chinese message, but received like this”\U00e8\U00b5\U009e\U00e4\U00ba\U0086\U00e4\U00bd\U00a0\U00e7\U009a\U0084\U00e8\U00af\U0084\U00e8\U00ae\U00ba”
> Some say set @"doubleEncodeUTF8":@true, I tried ,but not solved
> Xcode 10.2 Swift 5.0

how you solved this problem?

**Comment by sujuCrystal** [comment]
> > Receive Chinese message, but received like this”\U00e8\U00b5\U009e\U00e4\U00ba\U0086\U00e4\U00bd\U00a0\U00e7\U009a\U0084\U00e8\U00af\U0084\U00e8\U00ae\U00ba”
> > Some say set @"doubleEncodeUTF8":@true, I tried ,but not solved
> > Xcode 10.2 Swift 5.0
> 
> how you solved this problem?

**Comment by sujuCrystal** [comment]
> > Receive Chinese message, but received like this”\U00e8\U00b5\U009e\U00e4\U00ba\U0086\U00e4\U00bd\U00a0\U00e7\U009a\U0084\U00e8\U00af\U0084\U00e8\U00ae\U00ba”
> > Some say set @"doubleEncodeUTF8":@true, I tried ,but not solved
> > Xcode 10.2 Swift 5.0
> 
> how you solved this problem?

Server use version need Socket.IO 2.0+

**Comment by singelet** [comment]
Receive Chinese message, but received like this”\U00e8\U00b5\U009e\U00e4\U00ba\U0086\U00e4\U00bd\U00a0\U00e7\U009a\U0084\U00e8\U00af\U0084\U00e8\U00ae\U00ba”
Some say set @"doubleEncodeUTF8":@true, I tried ,but not solved
Xcode 10.2 Swift 5.0, Server use version need Socket.IO 2.0+.

how you solved this problem?
