### ISSUE TITLE
Socket constantly showing new connections even when only one client is connected

### ISSUE THREAD

**Issue by CandiceWright** [socketio/socket.io-client-swift#1189]
Hi! I am having an issue with sockets constantly disconnecting and reconnecting endlessly when only one connection should be being made. I can never pinpoint when it happens, but it usually happens at least once day. My server logs just show constant connections (I will show the screenshot below).  

<img width="441" alt="Screen Shot 2019-04-22 at 3 11 52 PM" src="https://user-images.githubusercontent.com/46908197/56535823-78f9d880-6511-11e9-9110-c12be6d8e2ad.png">

My socket manager is as follows:
let manager = SocketManager(socketURL: URL(string: serverUrl)!, config: [.log(false), .forcePolling(false), .reconnects(true), .secure(true)])

I looked online for a solution and someone mentioned that it could be due to a mismatch in socket.io versions between the client and the server. I am not sure if this is the case, or could solve my problem because I have no control over the socket version being used on the swift client. However, I am using socket version 2.2.0 on my server and I am using socket.io-swift-client v13.2.1  

For my application, I always need to have a reference to a user's socket. And when this repeated connect/disconnect happens, the server can no longer make a correlation between a user and its socket, which causes my application to have some unexpected behavior. I'd greatly appreciate any help with this. Thank you

**Comment by nuclearace** [comment]
@CandiceWright Without some logs from the client, it's a bit hard to pinpoint what this could be. Also, if you can use Swift 5 in your project, I'd strongly recommend updating to a newer version.

**Comment by CandiceWright** [comment]
Hi! The issue actually happened to be due to me using secure(true) in my Socket Manager. When I took this out, it works as expected. Thank you
