### ISSUE TITLE
over 95 errors on import

### ISSUE THREAD

**Issue by akinnuwa** [socketio/socket.io-client-swift#119]
Hello guys,
I just manually copied the swift files to my product directory and all sorts of errors are popping up over 95 of them. I did a product clean but nothing helps. What could be wrong? I am trying to use this client in an Objective-C project
<img width="710" alt="screen shot 2015-07-13 at 11 42 29 pm" src="https://cloud.githubusercontent.com/assets/8429120/8662547/e13e0ac6-29b8-11e5-9b3b-b9b04b37169c.png">

Errors like these

**Comment by nuclearace** [comment]
Are you on Xcode 6.4? Sounds like a Swift version error.

**Comment by akinnuwa** [comment]
I'm on Xcode 6.0.1

**Comment by nuclearace** [comment]
You'll need the latest version of Xcode, or find a version of the client that works with that version.

**Comment by nuclearace** [comment]
Also note that older versions of the client are probably buggy
