### ISSUE TITLE
Declaration problem

### ISSUE THREAD

**Issue by ahmadLshraby** [socketio/socket.io-client-swift#1201]
Hello,

I have a problem with socket declaration
I get a source code to test socket chat and it was working perfect
let socket = SocketIOClient(socketURL: URL(string: "http://chat.chhaileng.com:1111")!, config: [.log(false), .forceWebsockets(true), .nsp("/chat")])

when I copy this line of code to my project, it gives me errors and can't accept it

**Comment by nuclearace** [comment]
That's a pretty old init for the client. You should check out the current [docs](https://nuclearace.github.io/Socket.IO-Client-Swift/index.html) for how to use the library. The example in the readme is a pretty basic example.
