### ISSUE TITLE
RxSocket.io 

### ISSUE THREAD

**Issue by OmeraWasTaken** [socketio/socket.io-client-swift#1205]
Hello 👋,

I am wondering have you think about using https://github.com/RxSwiftCommunity/RxStarscream to create a RxSocket.io. It's seems really cool I will try to create something like that but let me know if you plan to do it too. I am really interesting about it 😃

**Comment by nuclearace** [comment]
@OmeraWasTaken I don't have any plans to create something like, but you're more than welcome to try your hand at it!
