### ISSUE TITLE
Should update v9.x socket.io 1.0 with swift 5 

### ISSUE THREAD

**Issue by stardustWK** [socketio/socket.io-client-swift#1206]
I know socket.io 1.0 swift client was unmaintained([#1065](https://github.com/socketio/socket.io-client-swift/issues/1065), [#1021](https://github.com/socketio/socket.io-client-swift/issues/1021)),  but it **should** **support**, because  
1) many server not use js version, many java server use socket.io with third party library like [netty-socketio](https://github.com/mrniko/netty-socketio) which is only support 1.0
2) [java client](https://github.com/socketio/socket.io-client-java) which is only support 1.0 and widely used by Android client
3) [c++ client]() which is only support 1.0 and widely user by Desktop app client

iOS client if use the last 2.0 version,  message to server has utf8 encode issue. if iOS client use the v9.x (1.0) version, have to down to swift 3.0 which is unsupported by Xcode 10 later. So iOS client only use c++ client, I think this is unexceptable.

**Comment by nuclearace** [comment]
I don't currently maintain v1 support anymore, and I don't really have any plans to change that. 

That being said, if you want, you can adapt the 1.0 branch to support Swift 5. And if you want to make a PR for that, I can create a socket1 Swift 5 branch.

**Comment by stardustWK** [comment]
ok， I noticed repo has a 1.0-swift4 branch which can convert to swift 5 easily

**Comment by chimeiaiwangliang** [comment]
@stardustWK would you show me how to convert the 1.0-swift4 branch to swift 5?
