### ISSUE TITLE
Can not connect successfully in iOS 9

### ISSUE THREAD

**Issue by Beck-Sisyphus** [socketio/socket.io-client-swift#121]
Can't get connect working with the following code, any suggestion how to configure it correctly?

{

    let socket = SocketIOClient(socketURL: "**.*.***.***/8080")

    @IBAction func socket(sender: UIButton) {

        socket.emitWithAck("hello") (timeout: 3) { data in
            print("hello \(data)")
        }
        
        socket.emit("hello", "world")
        
        socket.onAny {print("Got event: \($0.event), with items: \($0.items)")}
        
        let loginDic = [
            "user_id"   : "beck",
            "fb_id"     :  FBSDKAccessToken.currentAccessToken().userID,
            "fb_token"  : FBSDKAccessToken.currentAccessToken().tokenString]

        do {
            let loginJSONData = try NSJSONSerialization.dataWithJSONObject(loginDic, options: NSJSONWritingOptions.PrettyPrinted)
            
            let loginJSONText = NSString(data: loginJSONData, encoding: NSASCIIStringEncoding)
            
            socket.emitWithAck("fb_login", loginJSONText!) (timeout: 3) { data in
                print(data)
            }

        } catch let error as NSError {
            print(error)
        }
        
        socket.connect()
    }

}

**Comment by nuclearace** [comment]
Well for one I think your socketURL is a little off.

```swift
let socket = SocketIOClient(socketURL: "1.1.1.1:8080")
```

Also, I wouldn't try emitting until after the socket is connected. And I wouldn't connect until all your handlers are added.

**Comment by Beck-Sisyphus** [comment]
Hi  nuclearance,

Thanks for the reply. I've changed to :8080, and move the socket to ViewDidLoad. This new line appears:

> Got event: connect, with items: nil

Sometimes it is error message:

> Got event: reconnect, with items: Optional((
    "connection closed by server"
))
Got event: reconnectAttempt, with items: Optional((
    "-1"
))

But all my emit functions are still not working yet. Can I say the connection is established?

**Comment by nuclearace** [comment]
Are your emits called before the socket actually connects? If you need them to be called as soon as the socket is connected you can put them into a handler for "connect".

**Comment by Beck-Sisyphus** [comment]
I tried, but no ack comes back still. 

''''
socket.on("connect") {data, ack in
            print("socket connected")
            print(data)
            print(ack)
        }
''''

Is there any environment setup I should look into?

**Comment by JAManfredi** [comment]
Im not 100% sure why yet, but I couldn't connect using the library in Objective-C or Swift using the exact same example thats given in the README. After further investigation the deinit() for the client and then the engine was being called. After further investigation I fixed this by changing the weak reference in the SocketEngine class to strong, ie. var client:SocketEngineClient? instead of weak var client:SocketEngineClient? 

However this doesn't make sense because it should theoretically cause a retain cycle having a strong reference from client to engine and back again, no? Instead it seems to be keeping the main object (SocketIOClient) instantiated which definitely shouldn't be happening in the first place. 

Any thoughts?

**Comment by nuclearace** [comment]
@Beck-Sisyphus It's up to the server to respond/request an ack. If the event isn't supposed to respond with one then it won't send one, and then ack will be nil.

@JAManfredi If the client's deinit is being called then it's going out of scope. You always want to make sure that the client is in scope. Changing the engine's reference to strong is causing a reference cycle, so neither of them get released.

The example on the README is assuming you put it into main.swift and then add a run loop via `CFRunLoopRun()`

**Comment by Beck-Sisyphus** [comment]
@nuclearace Good call. I'm calling my teammate to add a callback to respond to me. So can you tell if the connection is on after I call socket.connect() ?

**Comment by nuclearace** [comment]
Once the `connect` event is emitted the socket is connected.

**Comment by JAManfredi** [comment]
@nuclearace Thanks for the reply Erik. I understood what was going wrong as well as what removing the weak reference did, however why would the client be going out of scope? Im not so sure I completely see why this is happening though. I declared a property in the AppDelegate which is being used to control the connection. The 3rd party libraries worked fine like this, which Is why Im so confused I guess. Im sure theres something simple Im missing here.

**Comment by nuclearace** [comment]
I'm not sure, I'd have to see how you're actually declaring the socket and where.

**Comment by Beck-Sisyphus** [comment]
I realize that there are multiple forms of emit in socketIO, so I wonder if a JSON file is needed, or I should pass parameters separately to emit? I changed my client side a bit:

server side:

   soc.on("fb_login", function(req, cb) {
    // FIXME: query sanitization
    // this is a potential security flaw!!
    var fb_token = req.fb_token || null;
    var fb_id = req.fb_id || null;
    var user_id = req.user_id || null;
    var fb_res;  // stores fb's response json

    if (!fb_token || !fb_id) {
      console.error("[fb_login] No fb_token or fb_id provided");
      return cb({status: false});
    }

client side:

          socket.emitWithAck("fb_login",
                ["fb_token"  :  FBSDKAccessToken.currentAccessToken().tokenString],
                ["fb_id"     :  FBSDKAccessToken.currentAccessToken().userID],
                ["user_id"   :  "beck"]) (timeout: 4) { data in
                print(data)
            }

**Comment by Beck-Sisyphus** [comment]
BTW I realize there is no need to create JSON file by ourself. Just pass in a dictionary and Socket IO will handle for you. 

reference: http://socket.io/blog/socket-io-on-ios/
Sending JSON section

**Comment by Beck-Sisyphus** [comment]
I realize there is no need to create a JSON file by ourselves, socket IO handles that for you. Just pass in a dictionary and it will be good.

reference: http://socket.io/blog/socket-io-on-ios/
Sending JSON section

**Comment by Beck-Sisyphus** [comment]
My server side is asking if he decodes JSON emit correctly; if not, what is the correct syntax to write?

   soc.on("fb_login", function(req, cb) {
      var fb_token = req.fb_token || null;
      var fb_id = req.fb_id || null;
      var user_id = req.user_id || null;

      if (!fb_token || !fb_id) {
          console.error("[fb_login] No fb_token or fb_id provided");
          return cb({status: false});
      }
   }

**Comment by nuclearace** [comment]
I don't quite get what you're asking. What do you mean the correct syntax?

**Comment by Beck-Sisyphus** [comment]
I should say in this way. In the Node.js, how to read a JSON key and extract the value afterwards

**Comment by nuclearace** [comment]
```javascript
var json = {
    test: "test",
    bob: 1
}

for (key in json) {
    console.log(key)
}
```

You mean something like this?

**Comment by imton** [comment]
I can't connect neither under iOS 9. 
````
The operation couldn’t be completed. No such file or directory
````

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/issues/182 I ran into this error message here

**Comment by Gopabandhu17** [comment]
getting following error while calling connect() :-

2019-02-25 16:26:36.081620+0530 DemoSocket[10289:198937] LOG SocketIOClient{/}: Handling event: error with data: ["Could not connect to the server."]
error
2019-02-25 16:26:38.000812+0530 DemoSocket[10289:198937] LOG SocketManager: Trying to reconnect
2019-02-25 16:26:38.001480+0530 DemoSocket[10289:198937] LOG SocketIOClient{/}: Handling event: reconnectAttempt with data: [-3]
2019-02-25 16:26:38.001989+0530 DemoSocket[10289:199052] LOG SocketEngine: Starting engine. Server: http://192.168.0.71/
2019-02-25 16:26:38.002238+0530 DemoSocket[10289:199052] LOG SocketEngine: Handshaking
2019-02-25 16:26:38.002777+0530 DemoSocket[10289:199052] LOG SocketEnginePolling: Doing polling GET http://192.168.0.71/socket.io/?transport=polling&b64=1
2019-02-25 16:26:38.016625+0530 DemoSocket[10289:199052] ERROR SocketEnginePolling: Error during long poll request
2019-02-25 16:26:38.016801+0530 DemoSocket[10289:199052] ERROR SocketEngine: Error
2019-02-25 16:26:38.016984+0530 DemoSocket[10289:198937] ERROR SocketManager: Error
2019-02-25 16:26:38.017153+0530 DemoSocket[10289:198937] LOG SocketIOClient{/}: Handling event: error with data: ["Error"]
