### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS Crash

### ISSUE THREAD

**Issue by zntfdr** [socketio/socket.io-client-swift#1219]
Hi all,
I work for a company that provides a framework which embeds Socket.IO (v13.1.1).

Recently we've been receiving reports from one of our customers that the framework is causing crashes, you can find an example example of crashlog from the client attached below, both the client and I have been trying to reproduce the issue without any success for a couple of weeks, and this is why I'm now opening this issue to try to find other leads from your side.

I've explored previous Socket.IO issues and it seems that something similar happened in Socket.IO in 2016-7, however the version that my company uses has been released in early 2018 where all of those issues have been already solved. 
Other issues that I see in this repo are about threading, however we're always using the same thread for Socket.io-related things (as far as I can tell).

The crash happens when the app is in the foreground, it affects all iOS versions, and can happen multiple times in the same device. 
I can ask for more information if needed, any help would be greatly appreciated!

Thank you in advance ❤️ 

Here's the crashlog:
```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x8000000000000028
VM Region Info: 0x8000000000000028 is not in any region.  Bytes after previous region: 9223372025580486697  
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO            0000000283730000-00000002a0000000 [456.8M] rw-/rwx SM=ZER  
--->  
      UNUSED SPACE AT END
n
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [436]
Triggered by Thread:  0

Thread 0 Crashed:
0   OurFramework        specialized Set._Variant.remove(_:) + 40
1   OurFramework       	SocketAckManager.executeAck(_:with:onQueue:) + 184
2   OurFramework       	SocketAckManager.executeAck(_:with:onQueue:) + 184
3   OurFramework       	SocketIOClient.handleAck(_:data:) + 528
4   OurFramework       	SocketIOClient.handlePacket(_:) + 596
5   OurFramework       	specialized SocketManager._parseEngineMessage(_:) + 704
6   OurFramework       	partial apply for closure #1 in SocketManager.engineDidClose(reason:) + 32
7   OurFramework       	thunk for @escaping @callee_guaranteed () -> () + 28
8   libdispatch.dylib 	_dispatch_call_block_and_release + 32 (init.c:1372)
9   libdispatch.dylib 	_dispatch_client_callout + 20 (object.m:511)
10  libdispatch.dylib 	_dispatch_main_queue_callback_4CF + 1012 (inline_internal.h:2441)
11  CoreFoundation    	__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1813)
12  CoreFoundation    	__CFRunLoopRun + 1888 (CFRunLoop.c:3113)
13  CoreFoundation    	CFRunLoopRunSpecific + 452 (CFRunLoop.c:3247)
14  UIFoundation      	-[NSHTMLReader _loadUsingWebKit] + 1728 (NSHTMLReader.m:2562)
15  libobjc.A.dylib   	-[NSObject performSelector:withObject:] + 68 (NSObject.mm:2171)
16  Foundation        	__NSThreadPerformPerform + 340 (NSThread.m:1259)
17  CoreFoundation    	__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1980)
18  CoreFoundation    	__CFRunLoopDoSource0 + 92 (CFRunLoop.c:2015)
19  CoreFoundation    	__CFRunLoopDoSources0 + 260 (CFRunLoop.c:2059)
20  CoreFoundation    	__CFRunLoopRun + 988 (CFRunLoop.c:2922)
21  CoreFoundation    	CFRunLoopRunSpecific + 452 (CFRunLoop.c:3247)
22  GraphicsServices  	GSEventRunModal + 108 (GSEvent.c:2245)
23  UIKitCore         	UIApplicationMain + 216 (UIApplication.m:4353)
24  ClientApp       	main + 92 (main.m:35)
25  libdyld.dylib     	start + 4
```
Note: `ClientApp` and `OurFramework` are just placeholders to for the real app name and framework.

**Comment by patmalt** [comment]
I had a similar crash (#1193), but when handling the ack. We were able to solve this crash by dispatching any interaction with an instance of `SocketIOClient` onto the `manager.handleQueue`.

**Comment by zntfdr** [comment]
I no longer follow this project so the issue can be closed, thanks for the support!
