### ISSUE TITLE
[Question] Example for emitWithAck for ObjC?

### ISSUE THREAD

**Issue by mp3il** [socketio/socket.io-client-swift#123]
Hi guys,

Thanks for this fantastic library, I'm looking for a way to make sure that the data I'm sending to the server is being received and if not, to store it and later re-send it.

I didn't found the right way to use emitWithAck (on objc), any example for that?

thanks.

**Comment by mp3il** [comment]
Sorry, found in the example,
closing.

**Comment by samyakjain** [comment]
Can you share the example

**Comment by nuclearace** [comment]
It's on the read me 

```objective-c
[socket emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
    [socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
});
```
