### ISSUE TITLE
Emit Function not working on some ios devices

### ISSUE THREAD

**Issue by PiaoFeifei1994** [socketio/socket.io-client-swift#1232]
Hello Socket IO Team.
I am developing one objective c project with socket io library.
But I faced one strange problem.
It is just SocketIOClient emit issue.
After connecting to node js socket io server, I have emitted with some parameters.
But it works on some devices and not working on any devices.
I can not know about the reason.

This is my code.

NSURL* url = [[NSURL alloc] initWithString:_chatserver];
    _manager = [[SocketManager alloc] initWithSocketURL:url config:@{@"log": @YES, "compress": @YES}];
    _ChatSocket = _manager.defaultSocket;
    NSArray *cur = @[@{@"username":[Config getOwnNicename],
                       @"uid":[Config getOwnID],
                       @"token":[Config getOwnToken],
                       @"roomnum":[dic valueForKey:@"uid"],
                       @"stream":[dic valueForKey:@"stream"],
                       }];
    [_ChatSocket on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
        [_ChatSocket emit:@"conn" with:cur];
    }];
    [_ChatSocket connect];

So I need your help.
Thanks

**Comment by nuclearace** [comment]
Can you post some logs from a client that doesn't send?
