### ISSUE TITLE
crash ：App init (SocketEngine.swift:)

### ISSUE THREAD

**Issue by GitHubZHH** [socketio/socket.io-client-swift#1239]
??? | 000000000000000000 + 0
-- | --
??? | 000000000000000000 + 0
 ??? | 0x00000000240008ff + 0
 libdyld.dylib | dyld_stub_binder + 60
 libswiftDispatch.dylib | _$sSo17OS_dispatch_queueC8DispatchE5label3qos10attributes20autoreleaseFrequency6targetABSS_AC0D3QoSVAbCE10AttributesVAbCE011AutoreleaseI0OABSgtcfC + 1076
 App | init (SocketEngine.swift:37)
 App | 0x00000001000c8000 + 2781848
 App | connect (SocketManager.swift:0)
 App | connectSocket (SocketManager.swift:214)
 App | _$s8SocketIO0A7ManagerC07connectA0yyAA0A8IOClientCFToTm + 48
 App | connect (<compiler-generated>:0)
.....

public let engineQueue = DispatchQueue(label: "com.socketio.engineHandleQueue") ？？？？

    /// Starts the connection to the server.
    open func connect() {
        engineQueue.async {
            self._connect()
        }
    }

**Comment by mahesh-khokhar** [comment]
Don't call in the queue. It should be always in the main thread.

**Comment by GitHubZHH** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9910841/66493336-73f10b80-eae8-11e9-9416-2c66577e4c69.png">

YES，It is always in the main thread.

**Comment by nuclearace** [comment]
Could you post some logs from the client?

**Comment by MillerJiang538** [comment]
> Could you post some logs from the client?

Socket push data is incomplete. I don't know whether it's a server problem or a client problem. It flashes back when parsing. Please tell me how to solve it, thank you!

**Comment by MillerJiang538** [comment]
> Could you post some logs from the client?

I don't know if it is the problem of socket sticking. How to solve it!
