### ISSUE TITLE
Socket.On() Listeners do not fire but emit works fine.

### ISSUE THREAD

**Issue by pathanparvezkhan** [socketio/socket.io-client-swift#1240]
I am facing some issues regrading socket.on() listeners they do not listen the events but when i emit the message it sent fine to server but listeners do not fire for it. Socket is connected and connect listener is fired successfully but other listeners do not fire after emit.

Please find below my code:

let manager = SocketManager(socketURL: URL(string: "https://socket-qa.coreiot.cloud/web-1")!, config: [.log(true), .compress])

var socket:SocketIOClient!

override func viewDidLoad() {
        super.viewDidLoad()
       
        self.socket = manager.defaultSocket

        self.addHandlers()
        self.socket.connect()
}

func addHandlers() {
        self.socket.onAny{
            print("Got event: \($0.event), with items: \(String(describing: $0.items))")
        }
        self.socket.on(clientEvent: .connect) {data, ack in
            print("socket connected")
        }
        self.socket.on(clientEvent: .disconnect) {data, ack in
            print("socket disconnected")
        }
        self.socket.on("5d7c6d5c601b7f000d884a4a"){data, ack in
            if let name = data[0] as? String{
                print(name)
            }
        }
        self.socket.on("5d820db4fa7692000e759ab6"){data, ack in
            if let name = data[0] as? String{
                print(name)
            }
        }
        self.socket.on("connect"){data, ack in
            self.socket.emit("join", ["room": "devices"])
        }
    }

**Comment by nuclearace** [comment]
Can you post some logs from the client?

**Comment by pathanparvezkhan** [comment]
I have fixed the issue by adding below line.
self.socket = manager.socket(forNamespace: "/web-1") 

Now, It works fine.
