### ISSUE TITLE
I need open  #1156,This bug still exists with `Multiple Reconnect` and `Multiple Connect`

### ISSUE THREAD

**Issue by ssyzh** [socketio/socket.io-client-swift#1243]
like #1156 ，but I don't think it solves the problem @nuclearace。

**Comment by ssyzh** [comment]
version: 15.1.0
iOS 12.4.0 - iOS 13.0
iphone 8 and iphone X

this steps:
Connect the socket
Retreat to the background for about 3 minutes
Back to the front

I need help

**Comment by shivamsharma-1996** [comment]
@ssyzh Hi, 
I need to know can this socket.io framework ,that was last updated with **swift 5.0**, work with **Xcode 11 and swift 5.1** ??

**Comment by shivamsharma-1996** [comment]
@ssyzh I've tried it in a Xcode 11 project with swift 5.1 compiler.

But it shows "could not compile module, compiled for swift 5.0 compiler , on a swift 5.1 compiler"
