### ISSUE TITLE
Foreground service don't stop in iOS

### ISSUE THREAD

**Issue by uedsonreis** [socketio/socket.io-client-swift#1247]
I'm using socket.io-client in react-native to start a chat room, when the app enters in foreground mode the socket keeps working, no problem, but when I disconnect the socket yet the foreground mode still stays active. I have tried a lot of ways but none deactivated the foreground service.

Follow the code who call the socket:

    socket = null;

    socketConnection = (url) => {
        socket = io(url, { forceNew: true });
            
        socket.on('connect', () => {
            console.warn("Connected: ", socket.connected);
        });
        socket.on('reconnect', () => {
            console.warn("Reconnected: ", socket.connected);
        });
        socket.on('disconnect', () => {
            console.warn("Disconnected: ", socket.disconnected);
        });
    }

    emit = (event, args ) => {
        socket.emit(event, args);
    }

    on = (event, fn) => {
        socket.on(event, fn);
    }

    socketDisconnect = () => {
        socket.disconnect();
    }

If anyone could help me.

**Comment by nuclearace** [comment]
I think you want the [regular](https://github.com/socketio/socket.io-client) client?
