### ISSUE TITLE
Unable to run socket.io in background mode iOS 13

### ISSUE THREAD

**Issue by akkitech** [socketio/socket.io-client-swift#1248]
Hi @nuclearace could you help us with socket.io running in the background for iOS 13? Whenever app is going to background, socket connection is getting lost within 5 seconds.

Thanks.

**Comment by akkitech** [comment]
Background in a sense, when user minimises the app.

**Comment by nuclearace** [comment]
Background execution via this framework is not officially supported on iOS. In the past I think people tried using things like VoIP settings, but I'm not sure that works anymore.

Unless something has changed in iOS 13, you'll need to use something like [APN](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html)
