### ISSUE TITLE
Version update latest 15.1, swift3.0 update 5.0, link failure

### ISSUE THREAD

**Issue by hum0506** [socketio/socket.io-client-swift#1249]
Hey, here I met a problem, swift3.0 upgrade to 5.0, then Xcode11 IOS13, pod installation is normal, I am from 8 + version upgrade to 15.1, the link has been failure, used to be normal, various methods are debugging, the new demo could not connect, it took me a others to address the connection is successful, my connection is not successful, would it be possible is a question of server version is not compatible with up and down?

    private var manager : SocketManager?
    private var socket : SocketIOClient?

        self.manager = SocketManager(socketURL: URL(string: "http://101.71.36.214:9900")!, config: [.compress])
        self.socket = self.manager!.defaultSocket

        self.socket!.on(clientEvent: .connect) {data, ack in
            print("socket connected === socket ok")
        }
        self.socket!.on("currentAmount") {data, ack in
            guard let cur = data[0] as? Double else { return }
            
            self.socket!.emitWithAck("canUpdate", cur).timingOut(after: 0) {data in
                self.socket!.emit("update", ["amount": cur + 2.50])
            }

            ack.with("Got your currentAmount", "dude")
        }
        
        self.socket!.connect()

**Comment by 20120608** [comment]
sir,Solved?

**Comment by jin404861445lan** [comment]
the same problems
