### ISSUE TITLE
iOS13 15.2.0 Crash!

### ISSUE THREAD

**Issue by MillerJiang538** [socketio/socket.io-client-swift#1251]
[issue_crash_912f6c7d67914f0799ae7e9931c49de2_DNE_0_v2.txt](https://github.com/socketio/socket.io-client-swift/files/3823390/issue_crash_912f6c7d67914f0799ae7e9931c49de2_DNE_0_v2.txt)
This is my log! When we use this SDK, our application appears to crash. Please check and repair, thanks!

**Comment by MillerJiang538** [comment]
It's crash in this function!

    mutating func read(count: Int) -> String {
        let readString = String(message.utf16[currentIndex..<message.utf16.index(currentIndex, offsetBy: count)])!

        advance(by: count)

        return readString
    }

**Comment by MRsJackYang** [comment]
Can you connect successfully? Why can't I connect successfully with 15.2.0.

**Comment by MillerJiang538** [comment]
> Can you connect successfully? Why can't I connect successfully with 15.2.0.

Yes, I can. Take a look at your creation method. 
You can refer to this blog!

**Comment by 20120608** [comment]
老哥，为什么15.2.0  连上服务器立马就断开了
