### ISSUE TITLE
Example for getting `timingOut` callback ?

### ISSUE THREAD

**Issue by DouglasHennrich** [socketio/socket.io-client-swift#1252]
There's a example on how can I retrieve that timeout callback when using `socket.emitWithAck(...).timingOut(...)` ?
Thanks

**Comment by nuclearace** [comment]
What exactly are you trying to do?

**Comment by DouglasHennrich** [comment]
I'm trying to emit again if I don't receive the callback from backend

**Comment by DouglasHennrich** [comment]
```swift
socket.emitWithAck("some-event", [payload]).timingOut(after: 5) { data in 
   ...
}

// after 5 seconds if I don't receive the callback, trigger something to let me know that the event doesn't return
```

**Comment by nuclearace** [comment]
In that case you'd want to have the handler check for the `SocketAckStatus.noAck` sentinel, and then call whatever calls this.

**Comment by DouglasHennrich** [comment]
But how I do that? Can you show me an example? I can't figure it out =/

**Comment by nuclearace** [comment]
```swift
class Testing {
    let manager: SocketManager!
    let socket: SocketIOClient!

    func handleAckCall(data: [Any]) {
        guard let f = data.first as? String, f != SocketAckStatus.noAck.rawValue else {
            self.sendMessage()
        }
    }

    func sendMessage() {
        socket.emitWithAck("test").timingOut(after: 1) {[weak self] data in
            self?.handleAckCall(data: data)
        }
    }
}
```

Something like this might work

**Comment by DouglasHennrich** [comment]
So I have to do `f != SocketAckStatus.noAck.rawValue` to know if I got timout or not. Inside the closure 🤔

**Comment by DouglasHennrich** [comment]
I will try it, Thanks 😄

**Comment by nuclearace** [comment]
@DouglasHennrich Yes, I'll put something in the readme examples to cover this

**Comment by DouglasHennrich** [comment]
Thanks for responses and example. Also I need to cast the first element to `String` to check that
