### ISSUE TITLE
Plan to support Starscream v4

### ISSUE THREAD

**Issue by patmalt** [socketio/socket.io-client-swift#1258]
I am experiencing many crashes similar to https://github.com/daltoniam/Starscream/issues/588 in my app. The Starscream maintainers claim in this issue that the crash is fixed due to their rewrite and release of version 4.0.0 (https://github.com/daltoniam/Starscream/pull/653).

This major release is incompatible with the current implementation of `socket.io-client-swift` and will require changes to this library. Additionally,  the new version of Starscream is incompatible with Objective-C.

Is there a desire from `socket.io-client-swift` to upgrade Starscream to 4.0.0?

**Comment by nuclearace** [comment]
I’ll look into upgrading

**Comment by patmalt** [comment]
I started the effort here: https://github.com/emersonsoftware/socket.io-client-swift/tree/starscream-v4

**Comment by patmalt** [comment]
@nuclearace Any updates on the plan to support v4?

**Comment by nuclearace** [comment]
@patmalt I haven't had time to look into yet, but I'd welcome a PR to see what it might look like. Otherwise I don't have a specific timeline. Dropping Obj-c support is something that I'd like to avoid if possible, but wouldn't be dealbreaker I guess.

**Comment by NikitaBorodkin** [comment]
Hello!
I'd highly appreciate Starscream v4 support! Any updates so far? :)

**Comment by nuclearace** [comment]
I plan to start working on this this weekend. The big decision needed is whether to continue supporting Obj-C in some fashion, or just abandon that compatibility. I think I'll try to maintain that support, but if it gets too ugly, might have to abandon it.

**Comment by patmalt** [comment]
given the name of this library, it may be appropriate to drop support for objc?

**Comment by NikitaBorodkin** [comment]
I really think it's time to drop Obj-C support! :)

**Comment by cyambo-talkspace** [comment]
Is there any word on when this will be released?

**Comment by patmalt** [comment]
Is there any way the community could assist with the effort?

**Comment by lseidman-talkspace** [comment]
We are getting a significant number of crashes from Starscream v3, and would really appreciate if the library could be updated to use v4.  Is there any update on if or when that will happen?

**Comment by patmalt** [comment]
Has there been any progress on this? Is there any way the community can help get us to v4?

**Comment by morithil** [comment]
Hi, I am also experiencing the same crashes with Starscream and eagerly await the update to include v4, would love to know progress. Do let us know if the community can contribute :)

**Comment by nuclearace** [comment]
I've been doing some exploration. I've come to the conclusion that the next version of the library will be dropping support for Objective-C. This will allow for a simpler lib and hopefully allow for more swiftier style API.

**Comment by patmalt** [comment]
I have a working implementation here: https://github.com/emersonsoftware/socket.io-client-swift/tree/v4

There are somethings I just commented out that need lots of work. I have not run this code in production either.

**Comment by congnd** [comment]
Is there any plan for the next version that will use the newer version of Starscream?

**Comment by DHCC-DH** [comment]
Support **Starscream v4**

**Comment by morithil** [comment]
Hi @nuclearace , any updates on Starscream v4 support?

**Comment by nuclearace** [comment]
fyi https://github.com/socketio/socket.io-client-swift/pull/1309

**Comment by nuclearace** [comment]
`v16.0.0` is been released.
