### ISSUE TITLE
carthage build error: Building for iOS, but the linked framework 'Starscream.framework' was built for macOS

### ISSUE THREAD

**Issue by datacosmos** [socketio/socket.io-client-swift#1278]
After a xcode update to 11.4 I get an Error on carthage update:

> 
>     /usr/bin/codesign --force --sign - --timestamp=none /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/Starscream/3.1.1/Build/Products/Release-iphonesimulator/Starscream.framework
> 
> ** BUILD SUCCEEDED **
> 
> /usr/bin/xcrun xcodebuild -project /Users/.../Carthage/Checkouts/socket.io-client-swift/Socket.IO-Client-Swift.xcodeproj -scheme SocketIO -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/socket.io-client-swift/v15.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/bb/s61_db312pnd9j462g788g_c0000gp/T/socket.io-client-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/.../Carthage/Checkouts/socket.io-client-swift)Command line invocation:
>     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project /Users/.....Carthage/Checkouts/socket.io-client-swift/Socket.IO-Client-Swift.xcodeproj -scheme SocketIO -configuration Release -derivedDataPath /Users/....Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/socket.io-client-swift/v15.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/bb/s61_db312pnd9j462g788g_c0000gp/T/socket.io-client-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO
> 
> User defaults from command line:
>     IDEArchivePathOverride = /var/folders/bb/s61_db312pnd9j462g788g_c0000gp/T/socket.io-client-swift
>     IDEDerivedDataPathOverride = /Users/..../Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/socket.io-client-swift/v15.2.0
> 
> Build settings from command line:
>     CARTHAGE = YES
>     CLANG_ENABLE_CODE_COVERAGE = NO
>     CODE_SIGN_IDENTITY =
>     CODE_SIGNING_REQUIRED = NO
>     GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
>     ONLY_ACTIVE_ARCH = NO
>     SDKROOT = iphoneos13.4
>     SKIP_INSTALL = YES
>     STRIP_INSTALLED_PRODUCT = NO
> 
> note: Using new build system
> note: Building targets in parallel
> note: Planning build
> note: Constructing build description
> error: Building for iOS, but the linked framework 'Starscream.framework' was built for macOS. (in target 'SocketIO' from project 'Socket.IO-Client-Swift')

Any ideas how to fix this?

**Comment by BenjaminDigeon** [comment]
I have the same problem 😞

**Comment by datacosmos** [comment]
Could anybody please give a hint? How can I debug this?
Is this Project abandoned?

**Comment by BenjaminDigeon** [comment]
You need to edit the SocketIO xcodeproj and link the Starscream ios framework with a iOS target and the Starscream MacOS framework with a MacOS Target.

SocketIO have only one target for both plateform, but that don't seem to work anymore with the last version of Xcode. If i have some time this week i'm gonna make a PR for this.

**Comment by datacosmos** [comment]
@BenjaminDigeon: could you please explain me how you have done that? 
I tried to copy the target and linked to the iOS build, but it still complains about the macos framework in the original target.
And how do I rebuild the carthage packages without overwriting the changes I have done?

**Comment by BenjaminDigeon** [comment]
So you need to modify the xcode project in the Checkout folder and link the Starscream ios to SocketIO then build only the iOS framework with Carthage `carthage build --platform ios` then link the starscream mac os to SocketIO then build only macos `carthage build --platform macos`

Not the best way i know but it's has work for me.

**Comment by datacosmos** [comment]
@BenjaminDigeon: Thank you very much for your quick response! It works now. 

@all:
However it would be nice if this will be fixed.. But I doubt a bit if this will happen - it seems that the project is not very active anymore :(

I hope this lib is not abandoned?  What would be an alternative?

**Comment by nuclearace** [comment]
Will fix as part of the upgrade to starscream 4 in #1258

**Comment by westito** [comment]
The problem can be solved with current version: If you want to build only for iOS, '--platform ios' param will solve the problem. But, you must clear the Carthage cache (rm -rf ~/Library/Caches/org.carthage.CarthageKit) before. Otherwise Carthage will use the - wrong -cached build.
