### ISSUE TITLE
Crash in WebSocket.swift iOS 8.4

### ISSUE THREAD

**Issue by FangYiXiong** [socketio/socket.io-client-swift#128]
Hi, there is a crash in websocket.swift. Xcode 6.4 + iOS 8.4.
Any one encounter the same issue?
<img width="1076" alt="2015-07-27 5 18 50" src="https://cloud.githubusercontent.com/assets/6135847/8902503/cabccd34-3483-11e5-8c9c-9499c4774b57.png">
<img width="924" alt="2015-07-27 5 18 06" src="https://cloud.githubusercontent.com/assets/6135847/8902505/cc3eea0c-3483-11e5-8a85-c1b2f311786a.png">

**Comment by nuclearace** [comment]
What conditions does this happen?

**Comment by zhangqippp** [comment]
run into the same problem in iOS 8.3 and iOS 7.x, once in a while, have no idea why it happened

**Comment by nuclearace** [comment]
Kinda need more information, some logs would be nice.

**Comment by nuclearace** [comment]
Also merging with #116 since they're probably the same thing.
