### ISSUE TITLE
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE crash on iOS 10

### ISSUE THREAD

**Issue by cyrilchandelier** [socketio/socket.io-client-swift#1285]
I don't have much details about this crash, but it's been happening on iOS 10 where the app seems to crash as soon as the socket connects.

<img width="1236" alt="Screen Shot 2020-05-04 at 9 47 08 AM" src="https://user-images.githubusercontent.com/820515/80991263-97fd9c80-8dec-11ea-8653-59054184313e.png">

Did you ever see that? Any known workaround?

The closest I found in the issues was to make sure all the interactions with the socket were done on the handleQueue, I tried setting my own dispatch queue and used it everything the socket is called, still crashing.

Note: I don't have an iOS 10 device to test, this has been reported by one of my most valued customer, I can only see the crash in Crashlytics.

**Comment by newloran2** [comment]
I have the same problem, and i able to simulate in one iPhone 5 and one iPhone 5c.
If I use and iPhone 6 with iOS 10.3.1 the crash doesn't happen.
if in the Starscream framework  i use -Onone   SWIFT_OPTIMIZATION_LEVEL in the  build settings the crash not happend

**Comment by Patrick-Remy** [comment]
Same issue here, reproducible on an iPhone 4 with iOS 9.3.5, not in the simulator with iOS 10.3.1. It crashes immediately while/after handshaking (as from log output).

**Comment by Saulenco** [comment]
Same here on iPad 4 with 10.3.3 it's reproducible, had tried changing the threads of `handleQueue` used only main, no success, crashes on connect
![Screenshot 2020-05-19 at 15 30 01](https://user-images.githubusercontent.com/8323284/82326554-b31ffd00-99e5-11ea-82d6-7c0a60a7a97d.png)

**Comment by tom555cat** [comment]
Crash on iPhone5 iOS 10.3.4 with SocketIO build on Xcode 11.4.1, but not crash with SocketIO build on Xcode 10.x.x.

**Comment by Saulenco** [comment]
so just downloaded xCode 11.5 and this issue is no more
