### ISSUE TITLE
Multiple Errors when using in XCode 7

### ISSUE THREAD

**Issue by dsbcourtney** [socketio/socket.io-client-swift#129]
Should this run in  Swift Project in XCode 7? I am getting multiple errors when trying to build. Things like:

Type 'String' does not conform to protocol 'CollectionType'

'#' has been removed from Swift; double up  to make the argument label

Thanks in advance

**Comment by nuclearace** [comment]
You'll need to use the Swift-2 branch

**Comment by dsbcourtney** [comment]
Thanks. Should there be some error messages if it fails a connection?

**Comment by nuclearace** [comment]
There'll be an `error` event emitted.

**Comment by Beck-Sisyphus** [comment]
![screen shot 2015-07-27 at 9 28 21 am](https://cloud.githubusercontent.com/assets/5952569/8911539/e88f7c36-3441-11e5-8c46-de429e02db29.png)

**Comment by nuclearace** [comment]
Probably because you're not using the Swift-2 branch
