### ISSUE TITLE
WatchOS is not compiling 

### ISSUE THREAD

**Issue by lightsprint09** [socketio/socket.io-client-swift#130]
CFHTTPMessage and other C-APIs are missing.

Any solution? Is this wort an apple radarß

**Comment by nuclearace** [comment]
I wouldn't think it would be useable from watchOS in the first place. Do the watches even have networking capabilities? I thought you would have to use the iPhone and push stuff to the watch.

**Comment by lightsprint09** [comment]
The new OS fully supports NSURLSession and is capable of connection over WIFI autonomously. I found a post at the dev-forum where they describe that CFNetwork should be available soon. This should solve the problem.

**Comment by someoneAnyone** [comment]
NSURLSession is supported... what dependency does socket.io have on CFNetwork? Sorry but I don't understand.

**Comment by lightsprint09** [comment]
in https://github.com/socketio/socket.io-client-swift/blob/master/Source/WebSocket.swift there is a lot of CF-Stuff...

**Comment by SimpleApp** [comment]
Is this thread the final word regarding watchOS support ?

**Comment by nuclearace** [comment]
I would say yes, since it's a WebSocket issue.

**Comment by SimpleApp** [comment]
Ok thanks. 
Just for info, judging by this https://madebymany.com/blog/apple-watch-what-can-you-do-with-it post, it seems like some build of SocketRocket was at some point building on watchkit. I've asked this project for a status on watchOS, because their podspec also don't mention watchos...
