### ISSUE TITLE
Question | Does all the socket events work on main thread by default ? What if I don't manually uses handleQueue. 

### ISSUE THREAD

**Issue by aidevpk** [socketio/socket.io-client-swift#1304]
Hi @nuclearace, 

Thanks for building this wonderful library. I am facing one issue #1290 and have went through some relevant issues as well. 
Currently all my listeners are working on default thread and Queue.  I did not bind the calls in any any queue or thread. Consider this as an example: 

`self.socket?.on(EventListnerKeys.insufficientInfo.rawValue, callback: { (data, ack) in
            print_debug("Error, Insufficient Info:-")
            print_debug(data)
        })`

I'm also checking socket connection status in multple places in my application like this: 

`if SocketIOManager.instance.socket?.status == .connected{
               // Perform some action
                }`

However, all my emits are working on different threads. 
So few of them are using default thread | default queue and few of them are running on background thread. I thought running them on main thread will impact the performance. But now I'm in a doubt if this was correct. 

Consider following as a scenerio where I'm receiving muliple message objects: 
`DispatchQueue.global(qos: .background).async { 
    // Save message in DB 
    // emit acknowledgement to server
   }`

Can you please help me to solve the mentioned issue above. How should I modify my current implementation ?

**Comment by nuclearace** [comment]
By default the library will use the main queue for callbacks. So best practice is probably to use some other queue other than the main one for the `handleQueue`. And do all your interactions with the socket/manager on that queue. Emitting from different queues is probably risky, especially if they're ack'd emits.
