### ISSUE TITLE
Starscream update

### ISSUE THREAD

**Issue by MircoManiero** [socketio/socket.io-client-swift#1305]
Hi, 
is it possible to have an update of starscream dependency to 4.0.4 version?
Thanks.

**Comment by nneuberger1** [comment]
Were getting crashes on WebSocket write that I'm wondering if this library upgrades the Starscream API to 4.0.4 that possibly might fix any crash issues.

**Comment by morithil** [comment]
Still waiting for this update :( It would fix a lot of issues
