### ISSUE TITLE
Why ack block is NULL?

### ISSUE THREAD

**Issue by yuhua-chen** [socketio/socket.io-client-swift#131]
Hi there,
I use the sample code :
```
[self.socket on:@"currentAmount" callback:^(NSArray* data, void (^ack)(NSArray*)) {
    double cur = [[data objectAtIndex:0] floatValue];

    [self.socket emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
        [self.socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]]
    });

    ack(@[@"Got your currentAmount, ", @"dude"]);
}];
```

but I always got **EXC_BAD_ACCESS** on `ack(@[@"Got your currentAmount, ", @"dude"]);`. It said the ack() is NULL. I can't figure out. Did anyone occur this issue before? Thanks ;)

**Comment by nuclearace** [comment]
The ack will be null if the server didn't request an ack.

**Comment by yuhua-chen** [comment]
hmm...gotcha. And I found the reference in the [docs](http://socket.io/docs/). Thanks :smiley:
