### ISSUE TITLE
EXC_BAD_ACCESS (code=EXC_I386_GPFLT)  error while connecting through custom iOS framework

### ISSUE THREAD

**Issue by anooj1483** [socketio/socket.io-client-swift#1311]
I've created a framework with a dependency of Socket.IO-Client-Swift v15.2.0. Getting EXC_BAD_ACCESS (code=EXC_I386_GPFLT) error while connecting through framework. The implementation of socket.io inside my custom framework is as follows,

```
public class Client : NSObject {
    public static let shared = Client();
    private var socketManager:SocketManager!;
    private var socket:SocketIOClient!;

    override init() {
            super.init()            
     }

    public func connect(url:String, params:[String:String]){
        let _url = URL(string: url)!
        let configParams:SocketIOClientConfiguration = [.log(true), .forcePolling(true), .connectParams(params),.compress,.secure(true)];
        self.socketManager = SocketManager(socketURL: _url, config: configParams);
        self.socket = self.socketManager.socket(forNamespace: "/socket.io");
        self.socket?.connect();
        listenEvents();
    }
}
```

Usage in framework integrated project,

```
import MyFramework

class FirstViewController: UIViewController {
    override func viewDidLoad() {
         super.viewDidLoad();
         let parameters = self.getParams();
         Client.shared.connect(url:"https://domain",params:parameters);
    }
}
```

Screenshot of error:

<img width="1394" alt="Socket_error_inside_framework" src="https://user-images.githubusercontent.com/6260395/100194707-333a9880-2f1c-11eb-90ba-49f5b1397801.png">

After upgrading the **socketio version (3.x) in nodejs server and changing the swift client version to 16.0.0-beta2, this issue is resolved**. **But android client doesn't support version 3.x**. So ended up in downgrading it to 2.x in server and v15.2.0 in swift client. 

Is there any way to resolve this issue with server socket version 2.x and swift client version 15.2.0 ?

FYI, Xcode version: 11.5. Tried in both simulator and physical device.

**Comment by nuclearace** [comment]
`v16.0.0` is been released. Make sure you add `.version(.two)` to options if your server is still socket.io 2.0.
