### ISSUE TITLE
EIO - Engine.IO url param

### ISSUE THREAD

**Issue by mmilosevic** [socketio/socket.io-client-swift#1314]
First of all, thanks for the great socket.io client. :)

I have two questions about the `EIO` param inside the Engine.IO [url](https://github.com/socketio/engine.io-protocol#urls). 

1. what is the version the current client supports
2. is there a reason why it is not included inside the handshake request

Thanks.

**Comment by mmilosevic** [comment]
Any updates on this one?

**Comment by nuclearace** [comment]
@mmilosevic Version 16 of this client is going to support both EIO 3 and 4 and will send that as part of the handshake. Not including it was a mistake.
