### ISSUE TITLE
Socket-io iOS client says it's connected to server, despite “connection” event not firing on the server

### ISSUE THREAD

**Issue by spideymans** [socketio/socket.io-client-swift#1318]
I am having trouble wrapping my mind around this problem with my very basic Socket-IO setup. In short, the iOS client (running Socket.IO-Client-Swift), seems convinced that it has successfully connected to the socket on the server: The SocketIOClient has a status of `connected`. However, on the server the `connection` event is never fired.

When running the code below the iOS client prints `Socket status: connected` to the console once every 15 seconds or so, indicating that it has successfully connected to the server, and that the connection is maintained.

However, on the server, it appears that the "connection" event is never fired. `NEW CONNECTION` is never printed to the console on the server. The only console output is `Server is running on port 4400...`, indicating that the server is ready to accept connections.

When attempting to connect to the server via a web browser, `NEW CONNECTION` is printed to the console of the server, as expected. It appears that the problem is with the iOS code.

The complete code for the client and server is below. 

Client:
```
class GMSockets {    
    private var manager: SocketManager = SocketManager(socketURL: URL(string: "ws://localhost:4400")!, config: [.log(false), .compress])
    private var socket: SocketIOClient
    
    init() {        
        self.socket = self.manager.defaultSocket
        self.socket.on(clientEvent: .connect) { (data, ack) in
            print("Socket status: \(self.socket.status)")
            self.socket.emit("testEvent", "Hello")
        }
        self.socket.connect()
    }
    
}

```

Server:
```
let port = 4400;

var express = require('express');
var app = express();
var server = require('http').Server(app);
var io = require('socket.io')(server);

server.listen(port);
console.log(`Server is running on port ${port}...`);

io.sockets.on("connection", function(socket) {
    console.log("NEW CONNECTION")

    socket.on("testEvent", function(data) { 
        console.log("Test event recieved")
    })
})
```

I am using Socket.IO-Client-Swift version 15.2.0 on the iOS client, and Socket.io version 3.0.4 on the server.

**Comment by sharvilak11** [comment]
We're facing the same issue. Socket.io 3.x in the backend is not supported yet by this library. That's what we concluded.

**Comment by spideymans** [comment]
> We're facing the same issue. Socket.io 3.x in the backend is not supported yet by this library. That's what we concluded.

I can confirm that downgrading socket.io to 2.3.0 (the last 2.x.x release) has fixed the issue. 

The readme which reads, `Supports socket.io 2.0+ (For socket.io 1.0 use v9.x)`, was last update 14 months ago, which was before the release of socket.io 3.0. This documentation will need to be updated to reflect socket.io-client-swift's incompatibility with socket.io 3.0.

**Comment by anismansuri63** [comment]
If you are still facing above issue and you are using 15.2, try using 
pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :tag => 'v16.0.0-beta2'

**Comment by BrenoAquino** [comment]
I tried to use this tag (and branch socket.io-3), but i still not receiving any connected event. Did you also receive errors like that?

**Comment by nuclearace** [comment]
`v16.0.0` is been released. Make sure you put `.version(.two)` in options if your server is on 2.0.
