### ISSUE TITLE
Printing description of callback: expression produced error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=EXC_I386_GPFLT). The process has been returned to the state before expression evaluation.

### ISSUE THREAD

**Issue by 623034345** [socketio/socket.io-client-swift#1319]
Printing description of callback:
expression produced error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=EXC_I386_GPFLT).
The process has been returned to the state before expression evaluation.
![image](https://user-images.githubusercontent.com/21259873/103199642-39aa9e80-4926-11eb-8117-80f8fb2c3fdf.png)

**Comment by nuclearace** [comment]
This most likely happened because you were accessing the client on a queue that isn't the `handleQueue`
