### ISSUE TITLE
Help wanted: How to pass in query string when connecting to socketio endpoint?

### ISSUE THREAD

**Issue by qbig** [socketio/socket.io-client-swift#132]
Can just append "?token=xxx" to the socketio url?

**Comment by nuclearace** [comment]
```swift
let socket = SocketIOClient(socketURL: "localhost:8080", opts: ["connectParams": ["thing": "value"]])
```

You could use `connectParams`

**Comment by guapollo** [comment]
what's the object-c way to do this?

**Comment by nuclearace** [comment]
```objective-c
SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL: @"localhost:8080" opts: @{@"connectParams": @{@"thing": @"value"}}];
```

**Comment by guapollo** [comment]
Works! Thanks!

**Comment by nigharsh** [comment]
Updated for 2017

```
var socket = SocketIOClient(socketURL: URL(string: "localhost:8080")!, config: [.connectParams(["<key>" : "<value>"])])
```

**Comment by mohdsafadsaal** [comment]
Hi ,
I don't find socket io client with this params. 
Is there any alternative method to pass query parameters on connect method ?

**Comment by nuclearace** [comment]
@mohdsafadsaal The config stuff has moved to the `SocketManager` in the latest version.

**Comment by anuroopkanayil** [comment]
how to use connect parameters in swift 4

**Comment by bdavid68** [comment]
@nuclearace Can you please provide the demo using `SocketManager`?
I am getting difficulty to connect to socket server with authorization header.
Appreciate your help!

**Comment by nuclearace** [comment]
@bdavid68 It's crude, but this shows some basic usage: https://github.com/nuclearace/socket.io-client-testing/blob/master/Sources/main.swift
