### ISSUE TITLE
Can we receive event arguments as raw strings, to then parse into Swift structs using Codable?

### ISSUE THREAD

**Issue by spideymans** [socketio/socket.io-client-swift#1322]
On the Socket.io JS client, arguments sent with incoming events are encoded as plain strings. This makes it trivial to parse incoming data to a JSON object using `JSON.parse(data)`:
```
socket.on('news', (data) => {  
   console.log(data);
   console.log(JSON.parse(data));
});
```

Now on the iOS client, I'd love to be able to accomplish the equivalent task:
1. Get the arguments associated with an incoming event as a raw string 
2. Encode that string into a Swift Struct via the Codable protocol. 

It seems very difficult (if not impossible) to do this with socket.io-client-swift.

It appears that socket.io-client-swift encodes argument data into Swift's `Any` type utilizing an NSMutableDictionary. This is a nice convenience feature, but if you've got a model that already conforms to Codable, it makes constructing structs from the incoming argument data very challenging.

Of course, we could put the data into a dictionary, and then use that dictionary to construct the struct, but for large and complicated models, this can be a time consuming and error prone venture.

Now I've noticed that the `parseEngineMessage(_ msg: String)` function in the `SocketManager` class receives incoming messages as a raw string. This means that, as long as the string as JSON formatted, we could use the Codable protocol to construct Swift objects if we had access to this string.

Is there any reason in particular why we cannot access the raw string? And if not, is there any way to gain access to it for processing?

**Comment by nuclearace** [comment]
You could just encode the struct to a string and send that. Socket.Io receives what it gets. If you send an object you get an object back

**Comment by nuclearace** [comment]
There's also https://nuclearace.github.io/Socket.IO-Client-Swift/Protocols/SocketData.html

**Comment by spideymans** [comment]
> You could just encode the struct to a string and send that. Socket.Io receives what it gets. If you send an object you get an object back

This worked. Thanks so much for your quick response! Saved me a lot of unnecessary work 👍
