### ISSUE TITLE
Create own socket 

### ISSUE THREAD

**Issue by PrashantKT** [socketio/socket.io-client-swift#1328]
How to create or open new socket  and connect 
I mean in localhost

**Comment by nuclearace** [comment]
The readme has an example for connecting to localhost.

**Comment by PrashantKT** [comment]
@nuclearace  I have checked demos  But for that we need to start the localhost , How can I start localhost with 8080 port ?

**Comment by nuclearace** [comment]
Something like `const io = require('socket.io')(8080);`. Check the socket.io server docs for server info
