### ISSUE TITLE
Swift 2 from objc Missing method on

### ISSUE THREAD

**Issue by imton** [socketio/socket.io-client-swift#133]
Doesn't like "NormalCallback", how can I solve it? 

````swift
public func on(event: String, callback: NormalCallback) {
````

**Comment by nuclearace** [comment]
It's because Objective-C doesn't have variadics and apparently Swift 2 makes it so it won't bridge to NSArray. Really quite annoying. I'll have to make a separate API for Objective-C like I do for emit.

**Comment by nuclearace** [comment]
Should be fixed. I'm going to look into a better solution. I really want to use Swift's variadics, but it annoys me to have two APIs.

**Comment by imton** [comment]
@nuclearace thanks! Right now I just build everything over the swift API and consume my one from objc part. But yeah, it'd be great to have it working on objc directly.

**Comment by nuclearace** [comment]
Eh, I'm not going to, but I'd rather just drop support for Objective-C. The Swift API is much better. But most places still seem to use Objective-C, so I'll try to make the Objective-C API as clean as I can.

**Comment by imton** [comment]
@nuclearace I wish too but it is not that easy in real-world. :) thanks
