### ISSUE TITLE
Unable to request ack with iOS client

### ISSUE THREAD

**Issue by codechimera** [socketio/socket.io-client-swift#134]
Hey there!
I'm trying to request an ack with the iOS client, and it's not working (or I'm not doing something correctly).
I'm writing using Swift 1.2, targeting iOS 7, with the latest socket.io-client-swift cloned from the repo. My node server is running on iojs 2.5.0. My Socket.io version on the server is 1.3.5.

According to the Socket.IO iOS client announcement blog, the proper way to request an ack is:
````swift
socket.emitWithAck("needsAck", "test").onAck {data in
    println("got ack with data: (data)")
}
````
However, this gives me the error `'OnAckCallback' does not have a member named 'onAck'`.

Looking through the code, I think the right thing to do is this:
````swift
func emit(message: String, payload: [String: AnyObject], callback:AckCallback) {
        if socket.connected {
            NSLog("Emitting message '\(message)' with payload \(payload), requesting ack")
            socket.emitWithAck(message, payload) (timeoutAfter: 5, callback: callback)
        }
}

func checkAuthorized() {
    let uuid = UIDevice.currentDevice.identifierForVendor.UUIDString
    emit('authorized', ["uuid": uuid]) { (response: NSArray?) -> Void in
        NSLog("Response: \(response)")
    }
}
````

Unfortunately, this doesn't seem to work. When I enable logging on the client, it says that it's sending to the server, but my server doesn't respond. At first I thought this was a server coding issue, but I am doing it correctly per the docs:
````javascript
socket.on('authorized', function(data, response) {
        console.log('Handling authorization request: %j', data);

        // send it to the handler for processing
        handleClientAuthorized(data, function(err, result) {
            if (err) {
                log.error('Error handling authorization request: %j', err);
                response(err);
            } else {
                // response is the string 'success' or 'fail'
                response(result);
            }
        });
});
````

So, when I run `checkAuthorized()`, I properly get the log entry about emitting the message. However, I never get a response, and my server doesn't show any authorization request coming in.
I am able to emit and receive standard events with no ack, so I know that the socket server and transport is working for the most part; the only issue seems to be this. 

Edit: I do properly get the timeout `NO ACK` response after 5 seconds, if that helps.

Thanks for your time!

**Comment by codechimera** [comment]
Alright, so it looks like if I surround what I send to the server in an array, this works:

````swift
    func emit(message: String, json: String, callback: (response: String?) -> Void) -> Void {
        if connected() {
            NSLog("Emitting message '\(message)' with JSON payload \(json), requesting ack")
            let ack = socket.emitWithAck(message, [json])
            ack(timeoutAfter: 5, callback: { (response: NSArray?) -> Void in
                if let str = response?.firstObject as? String {
                    if str == "NO ACK" {
                        NSLog("No ack from server")
                        callback(response: nil)
                    } else {
                        callback(response: str)
                    }
                } else {
                    NSLog("Unexpected response from server: \(response)")
                    callback(response: nil)
                }
            })
        }
    }
````

However this isn't needed for non-ack functions like this:
````swift
    func emit(message: String, json: String) {
        if connected() {
            NSLog("Emitting message '\(message)' with JSON payload \(json)")
            socket.emit(message, json)
        }
    }
````

I'm fine with working around it, as shown in my first function, but I am curious if this is intended. 

Thanks!

**Comment by nuclearace** [comment]
Yeah the blogpost is a bit outdated now. But I'm having trouble reproducing. Wrapping the data in array actually sends the data inside an array for me.

**Comment by nuclearace** [comment]
You can try launching your server with

`DEBUG=* node index.js` to see what's actually going on.

**Comment by codechimera** [comment]
Yeah, I'm seeing it coming in as an array in the socket.io debug statements, but it doesn't come in as an array to my code. I must be doing something somewhere else that I've forgotten about (it's been a while since I've worked on this project). I don't think this was an issue with socket.io. 

Thanks for your time, and sorry for the bother!
