### ISSUE TITLE
[Need Help] Compatible with server socket.io 0.9.16

### ISSUE THREAD

**Issue by chienpm304** [socketio/socket.io-client-swift#1354]
My server is using socket.io **v0.9.16**, which our **socket.io-client-swift** version is adaptive with it?

**Comment by nuclearace** [comment]
That version is so old, I’m not sure the swift client ever worked with it.

**Comment by FernandoReynoso** [comment]
Hi @chienpm304 !
Did you find any solution to this? I'm facing the same issue.
