### ISSUE TITLE
Swift 2 Branch Strange Late Connect Behavior Question

### ISSUE THREAD

**Issue by davecom** [socketio/socket.io-client-swift#136]
If I initially connect in the same function where my .on() handlers are then they fire correctly.  If I connect from a different method that is executed later in the program's lifetime, the .on() handlers that I originally defined are not called, although emitting works correctly (verified on another end).

Why would I be running into issues pertaining to where my .on() handlers are defined as long as they're defined before connect()?

**Comment by nuclearace** [comment]
The only issue I could foresee with adding handlers somewhere where you're not connecting is you're actually adding handlers to a different socket instance. Because I generally always have an `addHandlers` method that attaches the handlers, and connect somewhere else.

**Comment by davecom** [comment]
Yeah, my socket is an ivar, so I don't think that's the issue.  I've simplified my example significantly to show it here:
```
let socket = SocketIOClient(socketURL: "myServerNotPostedPubliclysAddress")
```
```
func applicationDidFinishLaunching(aNotification: NSNotification) {
        //setup socket
        socket.on("connect") {data, ack in
            print("socket connected")
        }
        
        socket.on("message") {data, ack in
            print("message received")
        }
        
        if let r = room {
            roomField.stringValue = r
            socket.connect() //message received works here
            socket.emit("create", r)
        }
    }
```
```
@IBAction func connectToRoom(sender: AnyObject!) {
            if let r = room {
                socket.connect() // no message received works here, but emits work after this
                socket.emit("create", r)
            }
    }
```

In either case, emit works fine and other clients (web/JavaScript) get my emits fine.  The issue is the on handler for "message" is not called when connect() is called from another method.  It's bizarre I know.  Looking for any ideas.
