### ISSUE TITLE
Version 2.4.1 breaks objective-c interoperability

### ISSUE THREAD

**Issue by alikaragoz** [socketio/socket.io-client-swift#137]
Looks like commit ffbe1e4ec4b59021cbc7ee8682c2813f85948520 is breaking objective-c interoperability.

Here is what I'm getting in the generated `SocketIO-Swift.h` file:
<img width="1355" alt="screen shot 2015-08-05 at 17 57 16" src="https://cloud.githubusercontent.com/assets/1283783/9090653/d01752f8-3b9b-11e5-94f7-1f603f0fe3b6.png">

I'm using Carthage.

Any idea @nuclearace ?

Thank you

**Comment by nuclearace** [comment]
Stupid Objective-C

**Comment by nuclearace** [comment]
It's because of some changes that'll be made in Swift 2 I believe.
