### ISSUE TITLE
can't connect to server with parameter

### ISSUE THREAD

**Issue by guapollo** [socketio/socket.io-client-swift#138]
Hi,

We are using parameters to connect to the server, but the connect always failed after called "[socket connect]", but if we called the "[socket connect]" twice, we could get the server connected, but still could not received any message from server, could you give some advises? 

relevant code are as below:
```objective-c
    NSDictionary *dict = @{
                           @"roomcode":_roomCode,
                           @"clienttype":@"student",
                           @"clientcode":[[NSUserDefaults standardUserDefaults] objectForKey:Code],
                           @"clientname":[[NSUserDefaults standardUserDefaults] objectForKey:Name]
                           };

    NSDictionary *optionsDic = @{
                        @"connectParams":dict
                        };

SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:WEBSOCKET_CHATURL options:optionsDic];

  [socket on:@"connect" callback:^(NSArray* data, void (^ack)(
        NSLog(@"success");        
    }];

[socket connect];
```

**Comment by nuclearace** [comment]
Is the socket a property of some object/controller? You can also try turning on logging via the log option.

**Comment by nuclearace** [comment]
Also, are you declaring the socket locally? Because the socket should be a property of an object.
