### ISSUE TITLE
Closing socket

### ISSUE THREAD

**Issue by Ulianko** [socketio/socket.io-client-swift#139]
Hi, I have problems with closing socket. When I leaving app, Im closing socket closeWithFast:YES (from onother operation queue) Ive also tryied closing it with NO on main queue. Problem is Ive receive disconnect handler, but server still things that Im online. On android platforms it works in seconds. By me sometimes 30seconds. I think socket is not closed correctly. What is the best practise ? How should I do to close it correctly ?

**Comment by nuclearace** [comment]
I think this is a case of Apple's not allowing multitasking. I think you're calling close but then your app gets suspended. So maybe create a background task and then close the task when you get a disconnect from the server.

**Comment by Ulianko** [comment]
Thank you for your quick answer. Ive just tried your solution but its the same anyway. Ive create background task which will last at least 5 minutes.

**Comment by Ulianko** [comment]
Youre right, problem is with entering background state. When I close it from running application there is no problem. But Ive tried your solution with background task, but nothing changed.

**Comment by nuclearace** [comment]
Yeah, this is where I'm not entirely sure what the best thing to do is. I'm not an iOS developer. I just know Swift, and wrote the library in Swift. If you want and try and follow what I did in the app I based this on here's the start of the shutdown process.

https://github.com/nuclearace/CytubeChatiOS/blob/1.1/CytubeChat1.0/AppDelegate.swift#L40 Again, I have no idea if this was good or not, it just seemed to work.

**Comment by Ulianko** [comment]
Okay Ive spent some hours with this and it turns out that it has problems with closing socket in background. Forget about closing it in didEnterBackground .. Ive made simple call from one of my screens and when I calling it from main queue it is working perfectly .. when I call it from `dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{`

its not working stable

**Comment by Ulianko** [comment]
Will you look at this bug ?

**Comment by nuclearace** [comment]
I'm not sure how to go about making this better. This is mostly because iOS doesn't play nice with background execution. There might be things I could do if this library were only for iOS, but it's also for OS X (and in the future, maybe open source Swift)

**Comment by Ulianko** [comment]
Hi, Ive just found the problem. I think socket engine is deallocated before this happend `                    SocketLogger.log("Writing poll: %@ has data: %@", client: this,
                        args: msg, data == nil ? false : true)
                    this.sendPollMessage(msg, withType: type, datas: data)
`
When I commented out line 160 (SocketIOClient.swift): engine = nil ... it works well also from background task...

**Comment by Ulianko** [comment]
Should I make pull request ?

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/commit/0fd8a9540bd78280a9ad775fac5cfed1d778e671

**Comment by Ulianko** [comment]
thank you
