### ISSUE TITLE
socket.io LINUX TCP

### ISSUE THREAD

**Issue by c8439** [socketio/socket.io-client-swift#142]
Client connects to the SOCKET.IO, on-line users, due to the instability of the user network signal, dropped the, and Linux system the user TCP did not release out, the user to connect again socket.io Linux system in adding a TCP.
![t03v3t m oens a fr5hppj](https://cloud.githubusercontent.com/assets/13691096/9188045/346bac82-400a-11e5-91f1-c122eed6d4d5.jpg)

**Comment by c8439** [comment]
Online users only hundreds of TCP, there were more than 5000, but also continue to add, established
![7 syucl3l 32 cuupa6f3u6](https://cloud.githubusercontent.com/assets/13691096/9188049/3ee2d62c-400a-11e5-9e1d-f5dde5d70c4d.jpg)

**Comment by nuclearace** [comment]
Probably a problem with engine.io
