### ISSUE TITLE
Generated header file throws undefined symbols "_OBJC_CLASS_$__TtC22Socket_IO_Client_Swift14SocketIOClient"  when trying to use Socket.io-client-swift in ObjectiveC

### ISSUE THREAD

**Issue by singhamit089** [socketio/socket.io-client-swift#143]
I downloaded the v2.4.2 (https://github.com/socketio/socket.io-client-swift/releases/tag/v2.4.2) then added it to my Objective C project folder.

have set following in Build Settings -> Swift Complier - Coder Generation section
1.) Install Objective-C Compatibility Header -> YES
2.) Objective-C Bridging Header -> "Haven't touched it, it's just blank, as mentioned in the instruction"
3.) Optimization Level -> Fastest[-O]

Now, the header file is generated and I write following in my ViewController to import it.

#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>

In my ViewController I have created 

@property(nonatomic) SocketIOClient *socketIO; 

and use it as per the TicTacToe Example provided.

The issue I am facing is, while I try to compile the project, it fails saying ...

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC22Socket_IO_Client_Swift14SocketIOClient", referenced from:
      objc-class-ref in LiveScoreViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

Here LiveScoreViewController is my ViewController, I am unable to figure out where exactly is the problem here ?

This is the section which compiler is unable to find in "Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h"

#####################################

SWIFT_CLASS("_TtC22Socket_IO_Client_Swift14SocketIOClient")
@interface SocketIOClient : NSObject <SocketEngineClient>
@property (nonatomic, readonly, copy) NSString * __nonnull socketURL;
@property (nonatomic, readonly) dispatch_queue_attr_t __null_unspecified handleAckQueue;
@property (nonatomic, readonly) dispatch_queue_t __null_unspecified handleQueue;
@property (nonatomic, readonly) dispatch_queue_attr_t __null_unspecified emitQueue;
@property (nonatomic, readonly) BOOL closed;
@property (nonatomic, readonly) BOOL connected;
@property (nonatomic, readonly) BOOL connecting;
@property (nonatomic) SocketEngine * __nullable engine;
@property (nonatomic, copy) NSString * __nonnull nsp;
@property (nonatomic, copy) NSDictionary * __nullable opts;
@property (nonatomic) BOOL reconnects;
@property (nonatomic, readonly) BOOL reconnecting;
@property (nonatomic) NSInteger reconnectWait;
@property (nonatomic, readonly) BOOL secure;
@property (nonatomic, readonly, copy) NSString * __nullable sid;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithSocketURL:(NSString * __nonnull)socketURL options:(NSDictionary * __nullable)options;

/// Closes the socket. Only reopen the same socket if you know what you're doing.
/// Will turn off automatic reconnects.
/// Pass true to fast if you're closing from a background task
- (void)closeWithFast:(BOOL)fast;

/// Connect to the server.
- (void)connect;

/// Connect to the server. If we aren't connected after timeoutAfter, call handler
- (void)connectWithTimeoutAfter:(NSInteger)timeoutAfter withTimeoutHandler:(void (^ __nullable)(void))handler;

/// error
- (void)didError:(id __nonnull)reason;

/// Same as close
- (void)disconnectWithFast:(BOOL)fast;

/// Same as emit, but meant for Objective-C
- (void)emit:(NSString * __nonnull)event withItems:(NSArray * __nonnull)items;

/// Same as emitWithAck, but for Objective-C
- (void (^ __nonnull)(uint64_t, void (^ __nonnull)(NSArray * __nullable)))emitWithAck:(NSString * __nonnull)event withItems:(NSArray * __nonnull)items;
- (void)engineDidClose:(NSString * __nonnull)reason;

/// Leaves nsp and goes back to /
- (void)leaveNamespace;

/// Joins nsp if it is not /
- (void)joinNamespace;

/// Removes handler(s)
- (void)off:(NSString * __nonnull)event;

/// Adds a handler for an event.
- (void)on:(NSString * __nonnull)event callback:(void (^ __nonnull)(NSArray * __nullable, void (^ __nullable)(NSArray * __nonnull)))callback;

/// Removes all handlers.
/// Can be used after disconnecting to break any potential remaining retain cycles.
- (void)removeAllHandlers;

/// Adds a handler that will be called on every event.
- (void)onAny:(void (^ __nonnull)(SocketAnyEvent * __nonnull))handler;

/// Same as connect
- (void)open;
- (void)parseSocketMessage:(NSString * __nonnull)msg;
- (void)parseBinaryData:(NSData * __nonnull)data;

/// Trieds to reconnect to the server.
- (void)reconnect;
@end

#####################################

I should also mention, there is a warning in the generated file, for following property

@property (nonatomic, readonly) dispatch_queue_t __null_unspecified handleQueue;

says incompatible dispatch_queues.

**Comment by nuclearace** [comment]
What xcode version are you using.

**Comment by nuclearace** [comment]
Probably using a new version of Xcode

**Comment by danipralea** [comment]
I have the same issue
