### ISSUE TITLE
"masked and rsv data is not currently supported" leads to crash on ACK

### ISSUE THREAD

**Issue by stephensilber** [socketio/socket.io-client-swift#145]
I'm using Objective-C in my project, and I am getting a large number of crashes based on this "masked and rsv data is not currently supported" error. In my logs, I see that I get this error right before my ACK is processed, and I then get a crash due to the data response object not being an NSArray. After some investigating, it looks like the data response object is a `Swift._SwiftDeferredNSArray`. Unfortunately, I'm unable to even use a temporary workaround like `if (![data isKindOfClass:[NSArray class]])` because it returns true even when it's a `Swift._SwiftDeferredNSArray`. 

```
2015-08-15 20:52:37.095 AppName[43787:273775] ### ERROR: (
    "masked and rsv data is not currently supported"
)
2015-08-15 20:52:37.112 AppName[43787:245014] -[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7f88860bcc10
(lldb) po data
@"0 objects"

(lldb) po [data class]
Swift._SwiftDeferredNSArray

(lldb) po [data isKindOfClass:[NSArray class]]
true

(lldb) po data.count
1

(lldb) po data[0]
[{"success":true,"started":false
```

Is there anything I can do to at least avoid trying to use this data, or even better, to help this corrupted data from calling the ACK completion block?

Crash logs:
```
Fatal Exception: NSInvalidArgumentException
-[__NSCFString objectForKeyedSubscript:]: unrecognized selector sent to instance 0x1688fb9e0

Thread : Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x0000000182d05a94 __exceptionPreprocess
1  libobjc.A.dylib                0x000000019774ff80 objc_exception_throw
2  CoreFoundation                 0x0000000182d0c7ac __methodDescriptionForSelector
3  CoreFoundation                 0x0000000182d0974c ___forwarding___
4  CoreFoundation                 0x0000000182c0d8ac _CF_forwarding_prep_0
5  SkillCoin                      0x00000001000f7048 __48-[SCSocketManager sendUserLocation:withHeading:]_block_invoke (SCSocketManager.m:420)
6  Socket_IO_Client_Swift         0x0000000100602e0c Socket_IO_Client_Swift.SocketAckManager.(executeAck (inout Socket_IO_Client_Swift.SocketAckManager) -> (Swift.Int, items : Swift.Optional<Swift.Array<Swift.AnyObject>>) -> ()).(closure #1) (SocketAckManager.swift:63)
7  libdispatch.dylib              0x0000000197f6d84c _dispatch_call_block_and_release
8  libdispatch.dylib              0x0000000197f6d80c _dispatch_client_callout
9  libdispatch.dylib              0x0000000197f72e9c _dispatch_main_queue_callback_4CF
10 CoreFoundation                 0x0000000182cbcd90 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
11 CoreFoundation                 0x0000000182cbabf8 __CFRunLoopRun
12 CoreFoundation                 0x0000000182be98a0 CFRunLoopRunSpecific
13 GraphicsServices               0x000000018dc44088 GSEventRunModal
14 UIKit                          0x000000018827e0d4 UIApplicationMain
15 AppName                      0x00000001000f84ec main (main.m:14)
16 libdyld.dylib                  0x0000000197f9e8b8 start
```

**Comment by nuclearace** [comment]
I think this is a limitation of the WebSockets library I use. Try forcing polling as a workaround until I can investigate further.

**Comment by nuclearace** [comment]
Also could be related to something I just fixed/updated

**Comment by stephensilber** [comment]
hard to say for sure, but after letting our tests run longer than usual, we didn't get any errors. We generally got 5+ errors in that time period.

**Comment by nuclearace** [comment]
After the last update?

**Comment by stephensilber** [comment]
yeah, after updating to 2.4.3 it seems to be fixed

**Comment by wadayamada** [comment]
I had the same error.

> websocket disconnected: masked and rsv data is not currently supported

- client: [socketio/socket.io-client-swift](https://github.com/socketio/socket.io-client-swift): v15.2.0
- server: [socketio/socket.io](https://github.com/socketio/socket.io): v4.4.1

I downgraded the server's version and it solved the problem.
- server: [socketio/socket.io](https://github.com/socketio/socket.io): v3.0.0
