### ISSUE TITLE
Error: compiling for iOS 10.0, but module 'Starscream' has a minimum deployment target of iOS 11.0

### ISSUE THREAD

**Issue by shuftipro** [socketio/socket.io-client-swift#1453]
After Recent updates to starcream cause the following problems when using version 16.0.1. and pushing .framework to cocoapods

**"- ERROR | [iOS] xcodebuild:  Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: error: compiling for iOS 10.0, but module 'Starscream' has a minimum deployment target of iOS 11.0: /Users/programmersforce/Library/Developer/Xcode/DerivedData/App-dxunzexturfkbccfansroziukkks/Build/Products/Release-iphonesimulator/Starscream/Starscream.framework/Modules/Starscream.swiftmodule/x86_64-apple-ios-simulator.swiftmodule"**

My project's minimum deployment is already iOS 12.0

**Noticed:**
Starscream.podspec has: s.ios.deployment_target = '11.0' 
Socket.IO-Client-Swift.podspec has: s.ios.deployment_target = '10.0'

**Comment by nuclearace** [comment]
Should be fixed in 16.1.0
