### ISSUE TITLE
New release to solve the Starscream compile issue

### ISSUE THREAD

**Issue by xmollv** [socketio/socket.io-client-swift#1454]
Hi all! 

Could we have a X.X.2 release to solve [the issue with Starscream](https://github.com/daltoniam/Starscream/issues/975)? The fix has landed on master, but there's not a release yet and SPM keeps pulling the wrong Starscream (unless you point the Socket.io dependency to `master`). The fix: https://github.com/socketio/socket.io-client-swift/commit/d7846b31a215211e595292425a2fdd6d16177faf.

Thanks!

**Comment by machl** [comment]
There is even better fix from maintainers to test in `development` branch. Let's hope they will release it soon.

**Comment by nuclearace** [comment]
Pushed 16.1.0. Only breaking change should be it no longer supports iOS 11 (Don't think this was possible anymore anyway)
