### ISSUE TITLE
pod for Xcode 7 and Swift 2.0

### ISSUE THREAD

**Issue by TofPlay** [socketio/socket.io-client-swift#147]
Hi,
Do you have a pod (for CocoaPods) for Xcode 7 and Swift 2.0?
Even a beta version

**Comment by nuclearace** [comment]
No, if you need swift 2.0 you'll need to manually install it from the repo.

**Comment by TofPlay** [comment]
The source code is compatible with Swift 2.0?

**Comment by nuclearace** [comment]
If you checkout the swift 2 branch it is.

**Comment by TofPlay** [comment]
Great :+1: :smile:
