### ISSUE TITLE
websocket has a question like this

### ISSUE THREAD

**Issue by gpr321** [socketio/socket.io-client-swift#153]
///Connect to the websocket server on a background thread
    public func connect() {
        if isCreated {
            return
        }
        dispatch_async(queue,{
            self.didDisconnect = false
        })
        
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT,0), {
            self.isCreated = true
            // net work is not normal , is always block here, and the WebSocketObject can not dealloc
            self.createHTTPRequest()
            self.isCreated = false
        })
        
        /** can i modify like this
        weak var wself = self;
        dispatch_async(socketconnect_queue!, {
            wself?.isCreated = true
            wself?.createHTTPRequest()
            wself?.isCreated = false
        })
        */
    }

**Comment by nuclearace** [comment]
I don't understand what problem you're running into

**Comment by gpr321** [comment]
WebSocket the connect function,when i do connect operation,it always block at the "self.createHTTPRequest()",but when when my controller is dealloced the thread was still block at the "self.createHTTPRequest()", but i modify like this :
 /** can i modify like this
    weak var wself = self;
    dispatch_async(socketconnect_queue!, {
        wself?.isCreated = true
        wself?.createHTTPRequest()
        wself?.isCreated = false
    })
    */
it works, what i want to ask is : is there any problem fix like this??

**Comment by nuclearace** [comment]
I don't know if that will cause any problems, I didn't create the websocket library.

**Comment by daltoniam** [comment]
I happen to stumble across this... I fixed this in my latest check in here:

https://github.com/daltoniam/Starscream/commit/f46e64b1792421f8b5583628b23f4fb9c172d351

**Comment by nuclearace** [comment]
Thanks
