### ISSUE TITLE
Import with Carthage into objective-c project

### ISSUE THREAD

**Issue by hsavit1** [socketio/socket.io-client-swift#157]
Hi

What does the #import line look like when you bring SocketIO in from Carthage into an obj-c project

**Comment by nuclearace** [comment]
Isn't it something like

```objective-c
#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>
```

**Comment by NachoSoto** [comment]
@hsavit1 you probably want to use the modern module syntax:
```objc
@import SocketIO
```
