### ISSUE TITLE
Apple warning

### ISSUE THREAD

**Issue by umbrella-sultan-ramazanov** [socketio/socket.io-client-swift#160]
Hello!
In my app I use socket.io and all work correctly. But every build in TestFlight Apple sent me email with warning «Missing Push Notification Entitlement». Maybe you or someone had such a problem and help me solve this situation?

**Comment by nuclearace** [comment]
I have no idea, this doesn't seem like it would be because of this library.

**Comment by umbrella-sultan-ramazanov** [comment]
Yes, this very strange, but I tested in two app. All was normal, TestFlight build created successfully, but when I include socket.io library (other than that, nothing has changed) Apple started send email every build. It is not critical, but the annoying and unexplainably.

**Comment by lightsprint09** [comment]
I got this mail as well.
I did not think that socket.io caused this. But it could be.

**Comment by umbrella-sultan-ramazanov** [comment]
After last library updates, Apple stopped send warning emails. This still inexplicably but issue was solved.
