### ISSUE TITLE
dyld`dyld_fatal_error

### ISSUE THREAD

**Issue by gaetanm** [socketio/socket.io-client-swift#162]
I installed the the framework with CocoaPods and I had no error during the installation process. But when I run my app I have this following error:

> dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/gaetan/Library/Developer/Xcode/DerivedData/iNetSoulCLI-csspsnkcpbbeejfllwpzkbqdqaet/Build/Products/Debug/Socket_IO_Client_Swift.framework/Versions/A/Socket_IO_Client_Swift
  Reason: image not found
(lldb)

I'm a total beginner with Swift and Xcode so I have no clue about what to do to solve this. I already tried things like clean + build but I still have the issue.

I'm using Xcode 6.4 on OS X Yosemite.

**Comment by nuclearace** [comment]
I remember getting an error like this before. I don't remember what I did to fix it... I think it has to do with dynamic frameworks

**Comment by mbelkin** [comment]
I'm experiencing the same thing — any ideas? What's strange is I noticed it builds to my phone just fine but won't run on the simulator.

**Comment by ibrahimennafaa** [comment]
Same here ...

**Comment by artemcarabash** [comment]
Had the same Problem, to solve it  just drag and drop your SocketIOClientSwift.framework to General tab Embedded Binaries.
![screen shot 2016-03-02 at 16 00 21](https://cloud.githubusercontent.com/assets/16085964/13464129/f1c029fe-e08f-11e5-9be2-e9006eea4b19.png)
