### ISSUE TITLE
Xcodeproject fails to build in Xcode 7

### ISSUE THREAD

**Issue by adi2412** [socketio/socket.io-client-swift#163]
Hi,

I'm new to iOS development and I was trying to use the Socket IO library. I noticed that I was not even able to build the project and any project using the socketIO framework. I get some 35 errors. However, the same project builds without errors in Xcode 6. Can anyone please help me figure out what's wrong here?

**Comment by nuclearace** [comment]
You'll need to check out the Swift 2 branch if you want Swift 2 support

**Comment by adi2412** [comment]
Sorry. Thanks for your help!

**Comment by adi2412** [comment]
So do I need to import it manually? I'm not quite sure how to import this to my project.

Thanks for your help!

**Comment by nuclearace** [comment]
I would suggest manually installing it
