### ISSUE TITLE
Chat Connection

### ISSUE THREAD

**Issue by mkaya93** [socketio/socket.io-client-swift#168]
Hi,

I can connect with this client but I have a issue. 

I have this code for the web client.

users[data.to].emit('whisper', {msg: msg, nick: socket.username, name: data.uname});

but I need the send to messages from users like this.What should I do ? Sorry for this little question.And Thanks For your helps

**Comment by nuclearace** [comment]
The emit would be

```swift
socket.emit("whisper", ["msg": msg, "nick": s.username, "name": data.uname])
```

**Comment by mkaya93** [comment]
Hi again,

yes I did this before but I couldn't send the message with this emmit.

            self.mySocket.emit("whisper", ["msg": "test", "nick": "nick", "name": "Name"])

**Comment by nuclearace** [comment]
Define couldn't send. Were you getting a compile error? Or the server wasn't receiving the message

**Comment by mkaya93** [comment]
server wasn't receving the message

**Comment by nuclearace** [comment]
Does the socket successfully connect to the client? Have you made sure that you're scoping the socket correctly? I feel like 80% of the time people say it doesn't work is because they don't understand how scope and ARC work in Swift.

**Comment by nuclearace** [comment]
Any progress?
