### ISSUE TITLE
authorization query

### ISSUE THREAD

**Issue by Katafalkas** [socketio/socket.io-client-swift#17]
Are there plans to add authorisation query in `opts` ?

**Comment by nuclearace** [comment]
You can add any query parameters with the `connectWithParams` method. Unless I'm misunderstanding what it is.

**Comment by nuclearace** [comment]
```swift
socket.connectWithParams([
    "test": 2.1,
    "d": "dassdfasdfasd"
    ])
```
For example

**Comment by chirag04** [comment]
@nuclearace can these params be set in the header instead of querystring or both.

The server looks at the cookie in the header for authentication. 

ios client can pass the cookie using this method if you send these params in the header.

**Comment by nuclearace** [comment]
I'll look into it

**Comment by nuclearace** [comment]
@Katafalkas @chirag04 Is ab77d72 what you're looking for? I haven't had time to test it yet. I have to learn how.

**Comment by Katafalkas** [comment]
@nuclearace `connectWithParams` was what I was looking for. The error was on my side, messed up jwt signatures.

**Comment by chirag04** [comment]
@nuclearace ab77d7260e3f8647ffbac9905a9e22ab8633c4b8 worked like a charm. 

Can you merge it in the master with some documentation around it?

**Comment by khanhankkhan** [comment]
what replaces 'connectWithParams' on the newest version of socket io for swift 1.2 client ??

**Comment by nuclearace** [comment]
The connectParams option

**Comment by guy-a** [comment]
connectWithParams was only sending params on re-connect, for me.
connectParams works great!

Thanx
