### ISSUE TITLE
Socket with only connect event does not work

### ISSUE THREAD

**Issue by adi2412** [socketio/socket.io-client-swift#171]
I have this code using the Socket IO Swift 2 code-

    SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:3000" opts:nil];
    
    [socket onObjectiveC:@"connect" callback:^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"socket connected");
    }];
    [socket connect];

For some reason the socket does not connect. But if I copy the sample code given in the README as is(with the currentAmount event and everything) the same socket connects. I can't figure why this happens.

**Comment by nuclearace** [comment]
Are you sure that the client isn't being released?
