### ISSUE TITLE
Cannot compile on Objective-C project

### ISSUE THREAD

**Issue by danipralea** [socketio/socket.io-client-swift#178]
Hello and thank you for this awesome project!
I have integrated it successfully into the project (no more errors with the swift files), but I still have errors when creating the SocketIOClient object entirely.

I have enabled modules, imported the Swift umbrella file (that matches the product name + "-Swift.h") and I still get the errors. Can someone please give me a lead?
![screenshot 2015-09-15 19 51 10](https://cloud.githubusercontent.com/assets/768893/9883504/25e222d2-5be3-11e5-8828-669b94845740.png)
![screenshot 2015-09-15 19 51 41](https://cloud.githubusercontent.com/assets/768893/9883517/372a7f4e-5be3-11e5-9897-039365574822.png)
![screenshot 2015-09-15 19 52 35](https://cloud.githubusercontent.com/assets/768893/9883539/53e5834a-5be3-11e5-82bf-f975dc24a0d8.png)
![screenshot 2015-09-15 19 52 16](https://cloud.githubusercontent.com/assets/768893/9883542/56a194c0-5be3-11e5-8cd9-06dfc972880f.png)

This is the entire Module section:
![screenshot 2015-09-15 19 53 37](https://cloud.githubusercontent.com/assets/768893/9883560/78a9cc86-5be3-11e5-8773-f4a6b18fd97c.png)

Just as a question - isn't the class supposed to have @objc in front of the Swift classes?

Thanks in advance!

**Comment by nuclearace** [comment]
You're probably missing some forward declaration.

```objective-c
#ifndef SwiftIOObjc_Tester_h
#define SwiftIOObjc_Tester_h

@class SocketIOClient;

@interface Tester : NSObject

@property (readwrite, nonatomic) SocketIOClient* socket;

- (id)init;
- (void)connect;
- (void)sendMessage:(NSString*)msg;

@end

#endif
```

**Comment by NachoSoto** [comment]
Did you `@import SocketIO;`?

**Comment by danipralea** [comment]
That's the .m file I have the screenshot for.
And yes, I have imported the Gogogab-Swift.h file into the .m file of my Service Singleton.

Thank you for your quick response.

**Comment by nuclearace** [comment]
@NachoSoto I believe he's copying the swift files directly. In which case you don't need define modules, just import the auto-generated Swift bridging header, and forward declare the type.

**Comment by danipralea** [comment]
Yes, I forgot to say that I copied the files directly.

**Comment by nuclearace** [comment]
Try adding

```objective-c
@class SocketIOClient;
```

**Comment by danipralea** [comment]
I did. Now I have 'Receiver 'SocketIOClient' for class message is a forward declaration'.
![screenshot 2015-09-15 20 04 33](https://cloud.githubusercontent.com/assets/768893/9883828/15a80204-5be5-11e5-8eaa-c4a79dc52971.png)

**Comment by nuclearace** [comment]
Okay, I guess you only need `@class` when you're doing it in a header file.

This works for me

```objective-c
@import Foundation;
#import "SwiftIOObjc-Swift.h"

@interface Tester : NSObject 

@property (readwrite, nonatomic) SocketIOClient* socket;

- (id)init;
- (void)connect;
- (void)sendMessage:(NSString*)msg;

@end

@implementation Tester : NSObject

- (id)init
{
    if (self = [super init]) {
        self.socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:8080" opts:@{@"log": @NO, @"connectParams": @{@"thing": @"value"}}];
        
        [[self socket] onAny:^(SocketAnyEvent* event) {
            // NSLog(@"Got event: %@, with items: %@", event.event, event.items);
        }];
        
        [[self socket] onObjectiveC:@"connect" callback:^(NSArray* data, void (^ack)(NSArray*)) {
            NSLog(@"socket connected");
        }];
        
        [[self socket] onObjectiveC:@"currentAmount" callback:^(NSArray* data, void (^ack)(NSArray*)) {
            double cur = [[data objectAtIndex:0] floatValue];
            
            [[self socket] emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
                [[self socket] emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
            });
            
            ack(@[@"Got your ack, ", @"dude"]);
            NSLog(@"Sent ack");
        }];
    }
    
    return self;
}

- (void)connect
{
    [[self socket] connectWithTimeoutAfter: 5 withTimeoutHandler: ^{
        NSLog(@"Client failed to connect");
    }];
}

- (void)sendMessage:(NSString*)msg
{
    for (int i = 0; i < 1004000; i++) {
        [[self socket] emit:@"test" withItems:@[msg]];
    }
}

@end

**Comment by umbrella-sultan-ramazanov** [comment]
In new version "options" must to be changed to "opts". Nuclearace, please change Example for Obj-C in README. This will reduce the number of questions and problems.

**Comment by danipralea** [comment]
Thank you for clearance :+1:

**Comment by nuclearace** [comment]
Changed. Does this fix your problem?
