### ISSUE TITLE
Simple SocketIO example doesn’t connect anymore after upgrade to 3.0.1

### ISSUE THREAD

**Issue by edimoldovan** [socketio/socket.io-client-swift#182]
Hi,

I have a very simple project here: https://github.com/edimoldovan/socketio-hapi/tree/master/client
which was working fine till I upgraded it to Swift2 and the 3.0.1 but now it doesn’t anymore without any error. Would anyone have a minute or two to have a look at the code? Should I be doing anything different?

Thanks,
Eduárd

**Comment by nuclearace** [comment]
What do you mean doesn't work anymore without an error? What's the error you're getting

**Comment by edimoldovan** [comment]
No error, it doesn't connect anymore.

--
ed
himself@eduardmoldovan.com
@edimoldovan

**Comment by nuclearace** [comment]
If you turn on logging for the client what does it say

**Comment by edimoldovan** [comment]
Happy to try that, but seams that I don’t know how to enable that in the options. Could you help wit that? I read the docs, this is probably not the right way to do it as nothing happens:
```    let socket = SocketIOClient(socketURL: "10.0.1.3:8001", opts: [
        "logger": "SocketLogger”])```

**Comment by nuclearace** [comment]
```swift
let socket = SocketIOClient(socketURL: "10.0.1.3:8001", opts: ["log": true])
```

**Comment by edimoldovan** [comment]
Here’s the log output:
```2015-09-17 18:43:54.672 ws[66554:14313675] Log SocketIOClient: Adding handler for event: connect
2015-09-17 18:43:54.673 ws[66554:14313675] Log SocketIOClient: Adding handler for event: yo
2015-09-17 18:43:54.673 ws[66554:14313675] Log SocketIOClient: Adding engine
2015-09-17 18:43:54.674 ws[66554:14313675] Log SocketEngine: Starting engine
2015-09-17 18:43:54.674 ws[66554:14313675] Log SocketEngine: Handshaking
2015-09-17 18:43:54.675 ws[66554:14313675] Log SocketEngine: Doing polling request
2015-09-17 18:43:54.722 ws[66554:14313780] ERROR SocketIOClient: The operation couldn’t be completed. No such file or directory
2015-09-17 18:43:54.726 ws[66554:14313780] Log SocketIOClient: Handling event: error with data: (
    "The operation couldn\U2019t be completed. No such file or directory"
)
2015-09-17 18:43:54.726 ws[66554:14313780] Log SocketIOClient: Handling event: reconnect with data: (
    "The operation couldn\U2019t be completed. No such file or directory"
)
2015-09-17 18:43:54.726 ws[66554:14313780] Log SocketIOClient: Starting reconnect
```

**Comment by nuclearace** [comment]
What does your server look like? Are you using any middleware? Is it the node.js implementation of socket.io?

**Comment by nuclearace** [comment]
Also, are you pointing directly at the socket.io server?

**Comment by edimoldovan** [comment]
This is the repo: https://github.com/edimoldovan/socketio-hapi/tree/master/server-harmony
Also the simple server one works, the harmony is the es6 one. 

And yes, pointing directly to the socket.io server on port 8001.

**Comment by nuclearace** [comment]
So the simple server works, but when you try and use harmony stuff it doesn't work?

**Comment by edimoldovan** [comment]
No, it doesn’t work with any, harmony is just syntactically different.

**Comment by nuclearace** [comment]
It works for me if I change the server to

```javascript
server.connection({
  port: 8000,
  labels: ["api"]
});
server.connection({
  port: 8001,
  labels: ["chat"]
});
```

And point the client to localhost:8001

**Comment by edimoldovan** [comment]
Indeed it does. but that is a bit strange isn’t it, the ip I had there is my local machine’s ip in the local network. 
If you try a `ifconfig` in terminal and provide the IP you see there into the above server connection, does that work for you?

**Comment by nuclearace** [comment]
Yes it does

**Comment by edimoldovan** [comment]
OK, this means that the issue is probably with my machine, network. Thanks a lot for the trouble, I am closing the issue.

**Comment by nuclearace** [comment]
Although, I will say that your example used iOS, and I tested using OS X.

**Comment by nuclearace** [comment]
But in theory, it shouldn't matter. Since the client is written agnostic of OS

**Comment by edimoldovan** [comment]
True, but the fact that localhost works for me from the emulator, my local machine ip doesn’t, is really strange.
