### ISSUE TITLE
Calling close method does not fire "disconnected" event

### ISSUE THREAD

**Issue by yannickl** [socketio/socket.io-client-swift#184]
Hi,

With the new version of the client (`3.x`) I notice a change during the close behaviour. In the `2.x` version when I called the `close(fast: Bool)` method I received a `disconnected` event and now there is anything due to this [line](https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/SocketIOClient.swift#L140) : 
```swift
status = SocketIOClientStatus.Closed
```

I need to know when the client is disconnected (in my callback) for all cases (event from server, or from local). If I remove this line the behaviour is the same like before and everything is ok.

Is it relevant for you to remove this line because the engine will call the `engineDidClose` callback to then call the `didDisconnected` or the `tryReconnect` method ?

**Comment by nuclearace** [comment]
I think I'm going to tweak the closing stuff

**Comment by nuclearace** [comment]
Should be fixed in the latest master
