### ISSUE TITLE
[ERROR] SocketIOClient: Invalid HTTP upgrade

### ISSUE THREAD

**Issue by yannickl** [socketio/socket.io-client-swift#188]
Hi,

I'm facing an issue that I don't understand and I need help. With the new version of the client I have random connection problem which display these logs:

```
Log SocketIOClient: Adding handler for event: disconnect
Log SocketIOClient: Adding handler for event: error
Log SocketIOClient: Adding engine
Log SocketEngine: Starting engine
Log SocketEngine: Handshaking
ERROR SocketIOClient: Invalid HTTP upgrade
Log SocketIOClient: Handling event: error with data: (
    "Invalid HTTP upgrade"
)
Log SocketIOClient: Disconnected: Invalid HTTP upgrade
Log SocketEngine: Engine is being closed. Fast: 1
Log SocketIOClient: Handling event: disconnect with data: (
    "Invalid HTTP upgrade"
)
Log SocketEngine: Got message: 40
Log SocketParser: Parsing 0
Log SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
Log SocketIOClient: Socket connected
Log SocketIOClient: Handling event: connect with data: 
Got event: connect, with items: nil
Log SocketIOClient: Client is being deinit
Log SocketEngine: Engine is being closed. Fast: 1
Log SocketEngine: Engine is being deinit
```

On the server (node.js 4.1.0, socket.io 1.3.7) I have a "handshake" and a `connection`  event. It happens on iOS 8.x and 9.x (iPads).
With the previous version and swift 1.x everything  worked well, but now it randomly failed. Have you some ideas?

**Comment by nuclearace** [comment]
What are your options for creating the client? Are you forcing polling?

**Comment by nuclearace** [comment]
I'm having trouble reproducing on OS X

**Comment by yannickl** [comment]
Here the client options:

```swift
let options = [
   "reconnects": false,
   "reconnectAttempts": 0,
   "log": true,
   "connectParams": params,
   "forceWebsockets": true
]
````

The server options:

```javascript
  var options = {
    pingTimeout: 3000,
    pingInterval: 10000,
    transports: ['websocket'],
    allowUpgrades: true,
    cookie: false
  };
```

The problem occurred randomly, I can't reproduce it voluntary but it happens very often.

**Comment by nuclearace** [comment]
And what are params?

**Comment by yannickl** [comment]
Here is an example of the parameters:

```swift
[
    "created": "2015-09-21T19:31:33+0200",
    "nonce": "W5TVkz7sxqUsY36KgekNQEVNt6LymyICgoUoTbh7ehQ=",
    "passwordDigest": "M2NmMTFjMjMyNTY3NDIwOWE1NTA4MDhiZDc2NjRmMjM5ZmViNmFlOGJiZmNjOTUwZmRkNTg3Mzg3MzI0ODkwMA==",
    "playerId": "1",
    "role": "a",
    "teamColor": "r"
    "username": "a"
]
```

**Comment by nuclearace** [comment]
I can't seem to reproduce on OS X. Until I can get around to testing iOS you might try setting up your server to the default, which is polling and websockets. And forcing the client to use polling.

Also, are you using a default node http server?

**Comment by nuclearace** [comment]
Is this only happening with real devices?

**Comment by yannickl** [comment]
I didn't try yet with an "empty" server. I'm going to test with an empty one, but this is strange because it worked fine before with Swift 1.3 and the previous version of the client.

It seems to work with the simulator, but with my iPads (air iOS8.4 and iOS9, mini 2 iOS8.4 and iOS9) it works one time in five.

**Comment by nuclearace** [comment]
Have you tried any other devices?

**Comment by yannickl** [comment]
I just tried with an empty project (client and server side) and I have the same issue (but very, very rarely 1 time in 30-40). I tried with my iPhone 6 and I have the same issue.

Here the client code:

```swift
import UIKit
import Socket_IO_Client_Swift

class ViewController: UIViewController {
  let socket = SocketIOClient(socketURL: "192.168.0.11:3000", opts: [
    "log": 1,
    "forceWebsockets": 1,
    "reconnectAttempts": 0,
    "reconnects": 0,
    "connectParams": [
      "created": "2015-09-21T21:27:01+0200",
      "nonce": "ZEC+2jS0ZPU9HdJ5/JH41435dtN0dIVTorw/Xi2UAtQ=",
      "passwordDigest": "N2E0NDQ1ZjJjMGJiYWE3YjI4OWE0OTZkOTg2Nzc2NzVkMzczZjM2MjMzODNiZjliODA1OWZmZDRhZTFjYjQzMg==",
      "playerId": 1,
      "role": "p",
      "teamColor": "r",
      "username": 1
    ]])

  override func viewDidLoad() {
    super.viewDidLoad()

    socket.onAny { (event: SocketAnyEvent) -> Void in
      print("Got event: \(event.event), with items: \(event.items)")

    }

    socket.connect()
  }
}
```

The server code:
```javascript
var app = require('http').createServer(handler)
var io = require('socket.io')(app);

function handler (req, res) {
  res.end();
}

app.listen(3000);

io.on('connection', function (socket) {
  console.log("connection");
});

**Comment by nuclearace** [comment]
I suspect this one is going to be tough to pinpoint

**Comment by nuclearace** [comment]
I'm also having a hard time reproducing on my iPhone 6 plus

**Comment by yannickl** [comment]
Do you have the same problem?

I don't think the issue comes from the server because it works fine with the previous version. I don't hope it comes from the Swift compiler (I had this kind of issue in release mode with another library in swift 1.2). I'll investigate more deeply the code tomorrow.

**Comment by nuclearace** [comment]
I wasn't able to reproduce. So it's probably some weird edge case

**Comment by stephensilber** [comment]
I had the same problem and temporarily worked around it by disabled "forceWebsockets" which I previously had set to true for a different issue with the socket.io library

**Comment by nuclearace** [comment]
It may also be helpful to turn on logging for the node server. 

`DEBUG=* node index.js`

**Comment by NachoSoto** [comment]
I can confirm this is a regression: I just upgraded from 07f9d4f548dd612b60268985dd6dc718fe7c0c54 to f933b7addc0461a77f1069abed1d60791526376d without changing any code and I'm unable to connect to my server, with this very same error.

**Comment by nuclearace** [comment]
That's weird... I don't really see anything in that change that should've broken anything

**Comment by nuclearace** [comment]
What does your connection to your test server look like? I'm able to connect to it fine the way I'm setting the client up.

**Comment by NachoSoto** [comment]
> That's weird... I don't really see anything in that change that should've broken anything

Note that I don't know which commit in [this commit range](https://github.com/socketio/socket.io-client-swift/compare/07f9d4f548dd612b60268985dd6dc718fe7c0c54...f933b7addc0461a77f1069abed1d60791526376d) broke it, all I know is that the regression is from one commit to the other.

> What does your connection to your test server look like?

I'm connecting to the server with these options:
```swift
let options: [String : AnyObject] = [
	"forceWebsockets": true,
	"log": false,
	"reconnectAttempts": 3
]
```

So note that I'm forcing web sockets. On the server (using `Netty-socketio`) I have:
```java
private static Configuration createConfig() {
    final Configuration config = new Configuration();
    config.setTransports(Transport.WEBSOCKET);

    return config;
}
```

**Comment by nuclearace** [comment]
It _shouldn't_ matter, but what platform are you using the client on?

**Comment by nuclearace** [comment]
Because there's nothing in that range that should cause an invalid HTTP upgrade (there was nothing touched dealing with handshaking) and I can't reproduce it on OS X.

**Comment by nuclearace** [comment]
Also, I don't think `config.setTransports(Transport.WEBSOCKET)` only sets WebSockets. Because I seem to still be able to connect using forced polling.

**Comment by yannickl** [comment]
Here you can find a server log (with the sample code I post before):

```
  engine handshaking client "7SoqEoiPqclvUN9yAAAG" +15s
  engine:socket sending packet "open" ({"sid":"7SoqEoiPqclvUN9yAAAG","upgrades":[],"pingInterval":25000,"pingTimeout":60000}) +0ms
  engine:socket flushing buffer to transport +1ms
  engine:ws writing "0{"sid":"7SoqEoiPqclvUN9yAAAG","upgrades":[],"pingInterval":25000,"pingTimeout":60000}" +0ms
  engine:transport setting request +0ms
  socket.io:server incoming connection with id 7SoqEoiPqclvUN9yAAAG +11s
  socket.io:client connecting to namespace / +0ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +0ms
  socket.io:socket joining room 7SoqEoiPqclvUN9yAAAG +0ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +15s
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  engine:socket sending packet "message" (0) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "40" +0ms
connection
  socket.io:socket joined room 7SoqEoiPqclvUN9yAAAG +1ms
  socket.io:client client close with reason transport close +59ms
  socket.io:socket closing socket - reason transport close +0ms
  socket.io:client ignoring remove for 7SoqEoiPqclvUN9yAAAG +0ms
```

The server running on a Mac OSX 10.10.5.

**Comment by nuclearace** [comment]
There's nothing really in that log that looks out of the ordinary other than the transport close.

**Comment by yannickl** [comment]
Yes I know, that's strange, but it can help us to focus on the client side (I guess).

**Comment by nuclearace** [comment]
For reference, this is where the invalid HTTP upgrade message comes from https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/WebSocket.swift#L332

**Comment by nuclearace** [comment]
And the last thing around then that might have something to do with it is https://github.com/socketio/socket.io-client-swift/commit/d6e1510cbf6f7524e6985ceb98bbb78784494dca

**Comment by nuclearace** [comment]
Okay the websocket version in master should basically be the same as it is in the source repo. Minus the combined file for security. So if it still happens in the latest master. It could be a problem with the library itself.

**Comment by yannickl** [comment]
It seems to work now! I'll see if in the next few days it'll be still ok. :+1:

**Comment by yannickl** [comment]
Unfortunately the problem is still here... It seems happen less often but  I still have "Invalid HTTP upgrade" error.

**Comment by nuclearace** [comment]
https://github.com/daltoniam/Starscream/issues/123

**Comment by NachoSoto** [comment]
Same here

**Comment by nuclearace** [comment]
How about the latest master?

**Comment by yannickl** [comment]
The first tests are positives. I'll keep you in touch in the next few days. :+1:

**Comment by yannickl** [comment]
Today I had no problem, so it seems to be ok now. Thank you!

**Comment by gafurovmsk** [comment]
> Is this only happening with real devices?

Hi! I have the same problem! And yes, this reproduced with only real devices. Everything is fine in simulators.
