### ISSUE TITLE
Got message: Cannot GET //socket.io/?transport=polling&amp;b64=1

### ISSUE THREAD

**Issue by sunlymaster** [socketio/socket.io-client-swift#189]
When I use the latest version in my project. Why I used url like this @"http://xxx.xxx.xx/", then I got this 

Log SocketEngine: Got message: Cannot GET //socket.io/?transport=polling&amp;b64=1

but when I changed url like this @"http://xxx.xxx.xx:tls". It works well. I feel confused about this.

**Comment by lightsprint09** [comment]
did but try ` ///socket.io/?transport=polling&b64=1`

**Comment by nuclearace** [comment]
It's probably because of the last / in your first url
