### ISSUE TITLE
Error parsing message: 1

### ISSUE THREAD

**Issue by Ulianko** [socketio/socket.io-client-swift#19]
Ive got these message when I tried emit to server. 		
```socket.on("connect") {data, ack in
println("socket connected")
socket.emit("conf")```

Do you know what is message 1?

**Comment by nuclearace** [comment]
What

**Comment by nuclearace** [comment]
Oh, does the socket not get anymore events after that?

**Comment by Ulianko** [comment]
Yes, no events at all

**Comment by nuclearace** [comment]
Because a message of 1 would be disconnect event.

**Comment by nuclearace** [comment]
Try adding

```swift
socket.onAny {println("got event: \($0.event) with items \($0.items)")}
```

**Comment by Ulianko** [comment]
But Im not disconnected. I also didnt received disconnect callback.

**Comment by Ulianko** [comment]
Yes I have it there. Also some debug NSLogs
2015-03-18 22:48:49.915 CallMe[71146:3725427] Engine got message: 40
got event: connect with items nil
socket connected
2015-03-18 22:48:58.380 CallMe[71146:3725392] Engine got message: 3probe
2015-03-18 22:48:58.483 CallMe[71146:3725427] Engine got message: 6
2015-03-18 22:48:58.570 CallMe[71146:3725408] Engine got message: 41
2015-03-18 22:48:58.572 CallMe[71146:3725408] Error parsing message: 1
2015-03-18 22:49:14.913 CallMe[71146:3725408] Engine got message: 3

**Comment by nuclearace** [comment]
`41` means it's a message. And the message is `1`. Which is the disconnect event.

**Comment by Ulianko** [comment]
Ok so server tell me disconnect but lib cant parse it and disconnect socket ?

**Comment by nuclearace** [comment]
I'm writing a handler for the disconnect event. But getting a disconnect event usually means the server is doing it on purpose. As most of the time if it's an error you won't get anything.

**Comment by Ulianko** [comment]
Ok, thanks

**Comment by nuclearace** [comment]
Added handler. Now, unless you can provide evidence that something's going on with the client that's causing the server to disconnect (which is highly possible) I'm going to close this.
