### ISSUE TITLE
Q: Do namespaces reuse the existing connection?

### ISSUE THREAD

**Issue by asapach** [socketio/socket.io-client-swift#190]
Is there a pool of connections that can be shared between namespaces on the same endpoint?

**Comment by nuclearace** [comment]
As it's written right now, each socket will create one connection.

**Comment by nuclearace** [comment]
Is there an explicit need for this feature?

**Comment by asapach** [comment]
Yes, we were implementing a native mobile (iOS) app on top of an existing socket.io endpoint and it came as a surprise that the iOS client doesn't have parity with the browser version. We have many namespaces as a way of multiplexing multiple logical streams of data -- and having a separate connection for each stream sounds like a massive waste of resources.

**Comment by nuclearace** [comment]
I'll have to look into it. The swift client isn't written as a rewrite of the browser version. It was written from scratch to comply with the socket.io protocol.
