### ISSUE TITLE
tvos support

### ISSUE THREAD

**Issue by tbaranes** [socketio/socket.io-client-swift#191]
Do you think to update your pod or carthage to support this new platform soon? Or a branch to avoid breaking the master until CocoaPods release a version working with tvos? 

I don't think you will have any issue to handle it with the current version.

**Comment by nuclearace** [comment]
I'll look into it.

**Comment by nuclearace** [comment]
Is CocoaPods currently broken?

**Comment by tbaranes** [comment]
The last release they have is not supporting tvos, so if you release a new pod supporting tvos right now, that will broke your pod. They have a workout allowing us to work on the tvos using CocoaPods, that's why I think a branch will be a good start waiting they release the tvos support.
