### ISSUE TITLE
Possible crash when closing connection

### ISSUE THREAD

**Issue by codingrhythm** [socketio/socket.io-client-swift#193]
I am experiencing some random crashes while closing connections.

I investigated a bit further of this crash, and the cause of crash seems like requests are still being sent after session is invalid.

line 116 in SocketEngine.swift
```swift
public func close(fast fast: Bool) {
        Logger.log("Engine is being closed. Fast: %@", type: logType, args: fast)

        pingTimer?.invalidate()
        closed = true

        ws?.disconnect()

        if fast || polling {
            write("", withType: PacketType.Close, withData: nil)
            client?.engineDidClose("Disconnect")
        }

        stopPolling()
}
```

Calling of `write("", withType: PacketType.Close, withData: nil)` in this function will call `flushWaitingForPost() ` in a different thread, and stopPolling() method will invalid session in current thread. 

So it's possible that session will become invalid before `session.dataTaskWithRequest.resume ` in `func flushWaitingForPost()` is called.

In most scenarios, it should be just fine. But if you set session delegate , it will crash with error like `Attempted to create a task in a session that has been invalidated` since invalid session will also break the delegate.

my current work around is, instead of calling `session.invalidateAndCancel()` I call `session.finishTasksAndInvalidate()`.  but it will also crash in `func doRequest()` as it will be called by the dataTask in `flushWaitingForPost()`.

Any Ideas?

It seems the crash only happens in iOS9, or I just cannot replicate in iOS8, don't know why.

**Comment by nuclearace** [comment]
So even if you change so finishTasksAndInvalidate, it still sometimes crashes in doRequest?

**Comment by codingrhythm** [comment]
Yes. The reason is in the callback block of datatask in flushWaitForPost method will call doRequest method. session waits the first datatask to complete and then invalidate itself, the second datatask within doRequest method will crash. As all datatasks are invoked from different thread, the order of execution is not guaranteed.

**Comment by nuclearace** [comment]
I don't think flushWaitForPost calls doRequest. It'll call itself though.

**Comment by nuclearace** [comment]
Have you tried adding a check for closed here? https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/SocketEngine.swift#L349 I think that would stop the recursion

**Comment by nuclearace** [comment]
Also, do you have some example code that can reproduce the problem semi-regularly?

**Comment by codingrhythm** [comment]
@nuclearace Hi Erik, Thanks for your reply. I made a demo application to show case the crash.
https://github.com/codingrhythm/socketio-crash
The crash happens every time when you click the disconnect button after you connect with delegate. It happens in iOS 9.

**Comment by codingrhythm** [comment]
flushWaitingForPost() calls doPoll(), doPoll() calls doRequest()

**Comment by nuclearace** [comment]
Does the latest master fix it? I'm going to refactor polling stuff shortly.

**Comment by codingrhythm** [comment]
@nuclearace this fixed the crash during disconnecting, however it crashes again with same error when I am trying to connect after disconnecting.

check the demo app
https://github.com/codingrhythm/socketio-crash

1. Connect with delegate
2. Disconnect
3. Connect again (crash)

**Comment by nuclearace** [comment]
I'm actually having difficulty reproducing it for some reason with your example.

**Comment by nuclearace** [comment]
Okay, I was able to reproduce with forced polling

**Comment by nuclearace** [comment]
Can you check the latest master?

**Comment by codingrhythm** [comment]
Works like charm! Cheers! You are the best!

**Comment by Amitmundra** [comment]
Hi,
I am facing similar type of issue in XMPPManager(Objective C) library, when close the connection and reconnect again then crashes ouured, May you help me to solve this issue?
