### ISSUE TITLE
Receiving errors as strings fails to call error event handlers

### ISSUE THREAD

**Issue by hanishabsigh** [socketio/socket.io-client-swift#196]
My understanding is, per the Socket.io protocol, socket.io errors are not required to be json objects, as described here: https://github.com/socketio/socket.io-protocol#error.

Currently our servers are sending string errors that fail to call the error handler and be processed by our app. This fails when the following json parsing lines fail: https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/SocketParser.swift#L128.

My logs show the following:

```
Log SocketEngine: Got message: 44"ERRORMESSAGE"

Log SocketParser: Parsing 4"ERRORMESSAGE"

Log SocketParser: Decoded packet as: SocketPacket {type: 4; data: ["ERRORMESSAGE"]; id: -1; placeholders: -1; nsp: /}

ERROR SocketIOClient: Error: ["ERRORMESSAGE"]
```

JSON parsing failures should be handled differently for type 4 socket.io error events.

**Comment by nuclearace** [comment]
Yeah, I would like to say this is a flaw in the protocol. Allowing a mixed types is a problem for languages that are statically typed.

**Comment by nuclearace** [comment]
Check if the latest master fixes your case. There's still the ugly problem if you try and include binary data in the error message

**Comment by hanishabsigh** [comment]
@nuclearace That works, thanks for the quick response!

**Comment by hanishabsigh** [comment]
@nuclearace Can you tag a new release and bump the podspec when you get a chance? Thanks!
