### ISSUE TITLE
Event handler data argument - [AnyObject] vs AnyObject

### ISSUE THREAD

**Issue by cgilboy** [socketio/socket.io-client-swift#200]
Hi! Thank you for this sweet library.

I have been working in parallel using socket.io client in JS and socket.io client in Swift and I noticed a disparity between the types that my event handlers were consuming. In the interest of enabling shared logic, it would be ideal to have the data type of the event handler to match between JS and Swift. 

It appears that the current JS socket.io client event handler expects a JSON object type:
```
socket.on('news', function (data) {
    console.log(data);
});
```

And the Swift socket.io client event handler expects an [AnyObject]:
```
socket.on("news") {data, ack in
    if let cur = data[0] as? String {
...
   }
}
```

Looking through the parsing code, it looks like the Swift event handling mechanisms are used internally for parsing incoming events and in those internal calls, the event name and payload are packed into the array. I can see the usefulness in that. To keep that usefulness in tact, it is possible for the Swift library to unpack the data object from its array before calling its `NormalCallback`s, and change the type signature of `NormalCallback` to `(AnyObject, SocketAckEmitter?) -> Void`.  Is that something that you and/or the community is interested in? If so I can put together a PR.

**Comment by nuclearace** [comment]
This would only work if socket.io didn't allow you to have multiple values in the event handler

```javascript
socket.on('news', (data1, data2, data3) => {});
```

Is fine in JavaScript

However, since Swift is statically typed, there's no nice way of doing this besides using an array.

**Comment by cgilboy** [comment]
Thanks for your reply!  

So using an array in Swift allows you to mimic a variable argument event handler in JS. Is that desirable because Socket.io actually allows emitting events with multiple data arguments, or because socket.io supports a generic event emitter/receiver interface? I'm not sure where to find documentation on this sort of thing.

**Comment by nuclearace** [comment]
Yes, using an array allows you to mimic the variable arguments that JavaScript has. Also, I didn't know about that when I first created the library, so for a little while, it actually was the case that it was AnyObject instead of [AnyObject]

**Comment by cgilboy** [comment]
Gotcha. I'm now looking at the Java socket.io implementation and I see the same pattern. Thanks :)
