### ISSUE TITLE
SSL connection problem

### ISSUE THREAD

**Issue by larten** [socketio/socket.io-client-swift#202]
Hi,

When I'm using the library with http URL, all working fine.
But after I set the certificate on server and try with https, it can't connect.
The certificate is trusted and not selfsigned.

```swift
2015-10-07 15:38:29.810 xxx[21640:120992] CFNetwork SSLHandshake failed (-9806)
2015-10-07 15:38:29.811 xxx[21640:120992] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)
SocketIOManager got event: error, with items: Optional((
    "An SSL error has occurred and a secure connection to the server cannot be made."
))
Got event: error, with items: Optional((
    "An SSL error has occurred and a secure connection to the server cannot be made."
))
SocketIOManager got event: reconnect, with items: Optional((
    "An SSL error has occurred and a secure connection to the server cannot be made."
))
Got event: reconnect, with items: Optional((
    "An SSL error has occurred and a secure connection to the server cannot be made."
))
```

I checked and SocketIOClient.secure is true and the rest API is on same URL and I can communicate via Alamofire.

Can you help me?

**Comment by nuclearace** [comment]
How are you creating the socket

**Comment by larten** [comment]
The API developer is away, but I will post if he will be available.
On the client side:
```swift
self.socket = SocketIOClient(socketURL: url)
        
        print("SocketUrl: \(socket.socketURL), secure: \(socket.secure)")
    
        self.socket.onAny {
            print("SocketIOManager got event on \(self.tag): \($0.event), with items: \($0.items)")
            self.cb(event: $0.event, items: $0.items);
        }
```
where url starts with https.

The strange is, that in browser client it's working without any ssl exception (and browser show certificate as trusted).

**Comment by larten** [comment]
The backend code:

```javascript
var fs = require('fs');
var https = require('https');
var querystring = require('querystring');
var express = require('express'), app = module.exports.app = express();

var sslOptions = {
    key: fs.readFileSync(__dirname + '/ssl/xxx.com.key'),
    cert: fs.readFileSync(__dirname + '/ssl/xxx.com.crt'),
    ca: fs.readFileSync(__dirname + '/ssl/godaddy.bundle.crt')
};

var server = https.createServer(sslOptions, app);
var io = require('socket.io').listen(server);  //pass a http.Server instance
server.listen(8080);  //listen on port 8080
```

**Comment by nuclearace** [comment]
I know that iOS 9 changed some things regarding SSL stuff. Are you using a weak key exchange? Also you could try implementing the NSURLSessionDelegate that implements one of the appropriate methods.

**Comment by larten** [comment]
Sorry, but I don't know what is weak key exchange :)

Secure communication and certificates are not my strong part. Do you have any more hint about custom NSURLSessionDelegate?

**Comment by nuclearace** [comment]
Not really, I haven't really experimented using SSL. But I suspect that if you implement the `URLSession(_:didReceiveChallenge:completionHandler:)` for NSURLSessionDelegate you'll be able to learn more

**Comment by Sealos** [comment]
@larten, try this:
* Disable ATS (Via NSAllowsArbitraryLoads in your Info.plist), check if you can establish a connection, but it's not recommended to leave it disabled.
* If you have OS X v10.11 (El Capitan), theres a curl command available to check if your certificate fulfills all the ATP requirements, for example, even if you have a certificate and its not self signed, it could have issues with Certificate Transparency, or the certificate TLS version

**Comment by nuclearace** [comment]
Any progress?

**Comment by larten** [comment]
Not yet. The application is now on review by Apple without SSL socket. If they don't accept this, then I must solve this problem.

@Sealos This time this is disabled, but I'm affraid Apple will push back.
I'm using now Yosomite, but I plan to upgrade and I will check it. Thanks!

**Comment by Sealos** [comment]
@nuclearace I haven't found any issue using this on SSL, it's most likely an ATP issue.

**Comment by JAManfredi** [comment]
Im having this same issue as well.

**Comment by nuclearace** [comment]
Probably related to https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

**Comment by Sealos** [comment]
@JAManfredi check your Info.plist configuration (My previous comment explains this)
```swift
private let url = "https://x:3000"
let socket = SocketIOClient(socketURL: url)

func setupSocketIO() {
    socket.on("connect") { data, ack in
        logger("socket connected")
        socket.emit("chat message", "what")
    }

    socket.on("chat message") { data, ack in
        logger(data)
    }

    socket.connect()
}
```

Produces the following:
```
SocketHelper.swift(18): socket connected
SocketHelper.swift(23): [what sent by server.]
```

**Comment by nuclearace** [comment]
Any progress on this?

**Comment by larten** [comment]
No.
The app went through the Apple review, so now it stay on http with disabled ATS (NSAllowsArbitraryLoads).

**Comment by nuclearace** [comment]
Closing since it's probably related to ATP
