### ISSUE TITLE
lib will crash when connect to a server that don't have IOJS server running

### ISSUE THREAD

**Issue by yyppaag** [socketio/socket.io-client-swift#203]
<img width="809" alt="screen shot 2015-10-09 at 5 05 39 pm" src="https://cloud.githubusercontent.com/assets/520787/10407999/4a77f194-6ea8-11e5-9fc4-23fd8d964a51.png">

**Comment by nuclearace** [comment]
What server are you using?

**Comment by yyppaag** [comment]
ubuntu  + nginx (proxy)

**Comment by nuclearace** [comment]
Well then what socket.io server where you running?

**Comment by yyppaag** [comment]
No socket.io server is running. just normal domain like (www.google.com).

**Comment by nuclearace** [comment]
What version of socket.io are you using?

**Comment by yyppaag** [comment]
Version 3.1.4,  XCode 7 && swift 2.0

**Comment by nuclearace** [comment]
What's the message that's causing the crash? You can turn on logging

**Comment by yyppaag** [comment]
can not assume that name can use  dataUsingEncoding,  sometimes it just cann't .    For this situation , you can just connect to www.google.com, and you will get the crash.

**Comment by yyppaag** [comment]
I think no matter whatever server I connect to is,  lib should not crash...

**Comment by nuclearace** [comment]
Okay, I see what you're saying. I would say it's an error to point to a server that isn't a socket.io server. But I can look into seeing what can be done

**Comment by yyppaag** [comment]
Thank you !
