### ISSUE TITLE
Importing with Carthage

### ISSUE THREAD

**Issue by meismyles** [socketio/socket.io-client-swift#204]
After following the instructions for importing the framework using Carthage, then adding the framework in 'Linked Frameworks and Libraries', is there something else I need to do/add/import?

I've got `import SocketIO` in my class but when trying `let socket = SocketIOClient(...)` I get `'SocketIOClient' is unavailable: cannot find Swift declaration for this class`.

The only thing available seems to be `SocketIOClientStatus`. Probably me being stupid.

**Comment by nuclearace** [comment]
Sounds like another issue I've seen, make sure you're on the latest version of Xcode

**Comment by nuclearace** [comment]
Also does carthage support Swift 2?

**Comment by meismyles** [comment]
Yeah it should work fine with Swift 2 as far as I'm aware. Other Swift 2 frameworks are working fine with it. I'm on the latest version of Xcode too.

Is this just an issue I'm having or is everyone unable to add the framework using Carthage?

**Comment by nuclearace** [comment]
Okay, I'm seeing the problem now. Weird

**Comment by nuclearace** [comment]
Only seems to happen on the iOS build of carthage

**Comment by meismyles** [comment]
Hmm, weird.

**Comment by nuclearace** [comment]
Should be fixed in 3.1.6

**Comment by meismyles** [comment]
3.1.6 of what? This framework or?

**Comment by nuclearace** [comment]
Yes this framework

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/releases/tag/v3.1.6

**Comment by meismyles** [comment]
Getting these errors now when running `carthage update --platform iOS`:

    *** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "iPhone Distribution" is not installed
    *** WARNING: Skipping build for "iphoneos" SDK because the necessary signing identity "iPhone Distribution" is not installed

Other frameworks build fine still, just this one thats giving that error.

**Comment by nuclearace** [comment]
Do you have an Apple developer's license?

**Comment by meismyles** [comment]
Yeah

**Comment by nuclearace** [comment]
Weird, it didn't give me any errors when I built it. ![](https://i.imgur.com/XgHfGae.png)

**Comment by meismyles** [comment]
Hmm, will have to have a look in the morning, see if anyone else is having a similar issue.

**Comment by meismyles** [comment]
Never did this get working. Could this be anything to do with you potentially code signing the project to your developer account (if you have on) when you build it? And then it looking for your details when I try to build it?

**Comment by nuclearace** [comment]
No idea. These options are why I advocate just copying Swift project files, or using gitmodules.

**Comment by YilunLiu** [comment]
I have the same issue.
*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "iPhone Distribution" is not installed
*** WARNING: Skipping build for "iphoneos" SDK because the necessary signing identity "iPhone Distribution" is not installed


It happens when I build for TvOs or iOS. Everything works fine for building for Mac.

**Comment by nuclearace** [comment]
@NachoSoto Any ideas?

**Comment by NachoSoto** [comment]
Looks like the signing identity is set to the distribution certificate instead of development for those targets.

**Comment by nuclearace** [comment]
So they should all be set to developer?

**Comment by NachoSoto** [comment]
Yes, and set to "not code sign" for simulator.

**Comment by YilunLiu** [comment]
Setting distribution code signing to developer fixed the problem for iOS

**Comment by meismyles** [comment]
Doesn't solve it for me. Still getting the same error.
