### ISSUE TITLE
Having an issue installing cocoapod of the project

### ISSUE THREAD

**Issue by alinandrews** [socketio/socket.io-client-swift#208]
I am running on cocoapods 0.39 version
My minimum deployment target is 8.0 and I run script
"source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'Socket.IO-Client-Swift', '~> 3.1.4' # Or latest version"

I get the same issue as above user.

[!] Unable to satisfy the following requirements:

    Socket.IO-Client-Swift (~> 3.1.4) required by Podfile Specs satisfying the Socket.IO-Client-Swift (~> 3.1.4) dependency were found, but they required a higher minimum deployment target.

**Comment by nuclearace** [comment]
Never heard of that issue before

**Comment by nuclearace** [comment]
Anymore feedback on this?

**Comment by AlexChesters** [comment]
IIRC this CocoaPods issue is related to not having a high enough deployment target, @alinandrews I'd change the line:
`pod 'Socket.IO-Client-Swift', '~> 3.1.4' # Or latest version"`
To read:
`pod 'Socket.IO-Client-Swift', '~> 4.1.2'`

And see if the issue still occurs

**Comment by alinandrews** [comment]
Guys 
Thanks for the follow ups. I wee offline for some weeks to see the messages.The issue was only from my end in the cocoa pods.  I had resolved it 
Great follow up to fix the issue. Thanks. 
Sent from Outlook




On Thu, Nov 19, 2015 at 2:15 PM -0800, "Alex Chesters" <notifications@github.com> wrote:












IIRC this CocoaPods issue is related to not having a high enough deployment target, @alinandrews I'd change the line:

pod 'Socket.IO-Client-Swift', '~> 3.1.4' # Or latest version"

To read:

pod 'Socket.IO-Client-Swift', '~> 4.1.2'



And see if the issue still occurs

**Comment by spa-sandeep** [comment]
@alinandrews How you Solve this issue ?  I am also Getting Same

**Comment by alinandrews** [comment]
I don't remember now. I believe, I did cocoa pods complete re installation
and did the following in podfile.

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Socket.IO-Client-Swift', '~> 3.1.4' # Or latest version

It did work.
