### ISSUE TITLE
Is there a way to use this library as engine.io client?

### ISSUE THREAD

**Issue by DominikPalo** [socketio/socket.io-client-swift#209]
We are using engine.io server library on the Node.js server with some custom extensions, so it is not compatible with socket.io. Currently I'm developing native apps for different platforms, so I need to implement engine.io client functionality into these apps. For windows app, I used the [EngineIoClientDotNet](https://github.com/Quobject/EngineIoClientDotNet) library and it works without problems. But for OS X app (Swift 2) I didn't find any client library with pure engine.io functionality. So it is possible to use this one (without parsing data packets directly to events and other socket.io functionality)? Or it is planned to create also separate engine.io client for Swift?

**Comment by nuclearace** [comment]
You may be able to use an adapted version of https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/SocketEngine.swift
