### ISSUE TITLE
Joining a namespace needs a Ack option.

### ISSUE THREAD

**Issue by drekka** [socketio/socket.io-client-swift#210]
I'm trying to use a namespace like this:

    [_socket joinNamespace:ESTIMATION_NAMESPACE];
    [_socket emit:@"JoinProject" withItems:@[@(project.projectId), _user]];

The problem I am encountering is that there is no Ack on joining a namespace. So the emit goes through before the namespace is connected to. No error is thrown.

I think namespace joining needs an Ack option so that I can embed the emit in a callback and only execute it after the namespace has been successfully joined. 

The only other option appears to be using a `socket.on(@"connect"...` and testing the name space inside it before called the relevant code.

**Comment by nuclearace** [comment]
Yeah, I would say that if you can, start the socket already on the namespace (if you know it beforehand). Or have some special logic inside your connect handler. Since the way socket.io confirms joining a namespace is with a connect event
