### ISSUE TITLE
Xcode code highlighting crashes

### ISSUE THREAD

**Issue by lightsprint09** [socketio/socket.io-client-swift#214]
Xcode crashes a lot while editing files from socket.io

**Comment by nuclearace** [comment]
Yeah, I ended up setting my default crash reporting to not do anything. It's really quite annoying. I have no idea why it's doing it.

**Comment by nuclearace** [comment]
It's obviously not something wrong with the library though. Since it's not crashing the compiler.

**Comment by lightsprint09** [comment]
Is this fixed?

**Comment by nuclearace** [comment]
I have no idea how to fix this. This is some bug with Xcode, since the project compiles fine.

**Comment by lightsprint09** [comment]
ok. But some changes in the project must be related with the highlight failures I guess

**Comment by nuclearace** [comment]
I ended up just doing `defaults write com.apple.CrashReporter DialogType Server` so it wouldn't pop up the dialog everytime. This used to happen a lot in the early versions of Swift.

**Comment by NachoSoto** [comment]
This is a bug in `Xcode 7`, fixed in `Xcode 7.1 beta 3`

**Comment by lightsprint09** [comment]
7.1 should be released alongside iOS 9.1 during the next hours
