### ISSUE TITLE
Fails to compile; WebSocketDeleate undeclared

### ISSUE THREAD

**Issue by MikaalSky** [socketio/socket.io-client-swift#217]
Can't compile app with Swift 2.0, iOS 9 on Xcode 7.
SocketEngine.swift
![Error](http://take.ms/3V6hc)

**Comment by nuclearace** [comment]
How did you import the project

**Comment by MikaalSky** [comment]
Drag and drop, add to target

**Comment by nuclearace** [comment]
Did you add the WebSocket.swift file

**Comment by MikaalSky** [comment]
Oh, oops!
