### ISSUE TITLE
how could i send json data and receive data like readLine?

### ISSUE THREAD

**Issue by cmnewfan** [socketio/socket.io-client-swift#218]
Hi.

My  socket server process json data,so i need to send json data to server. should i use emit to do this? i don't know what the event in emit means.

the other question is that the data from server ends with \n,so how could i read message like that?

Thanks in advance.

**Comment by nuclearace** [comment]
Is this server an actual socket.io server? Or is it just a raw websockets server? Because this library needs a socket.io server.

**Comment by cmnewfan** [comment]
it is not a socket.io server, i guess i can not use this library with the server
