### ISSUE TITLE
Event on "connect" not called

### ISSUE THREAD

**Issue by amincheloh** [socketio/socket.io-client-swift#22]
Socket connected to server but "connect" event not called.

**Comment by nuclearace** [comment]
I don't need more information than it wasn't called. 

Try adding

```swift
socket.onAny {println("got event: \($0.event) with items \($0.items)")}
```

**Comment by hiddenmin** [comment]
i found problem when connect with [netty-socketio](https://github.com/mrniko/netty-socketio) it said

client did not complete upgrade - closing transport

**Comment by nuclearace** [comment]
Hm, I'll have to look into it
