### ISSUE TITLE
delegate NSURLSession

### ISSUE THREAD

**Issue by dtorguet** [socketio/socket.io-client-swift#224]
I'm using version 2.4.5 Objective-C and I implemented the delegate method 
"- (void)URLSession: didReceiveChallenge: completionHandler:"
but never called, could you help me please?.
this is my code:
"SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"https://xx.xxx.255.xx/xatsocket/socket.io/1/" options:@{@"log": @YES, @"forcePolling": @YES}];
    [socket on:@"connect" callback:^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"socket connected");
    }];
    [socket on:@"currentAmount" callback:^(NSArray* data, void (^ack)(NSArray*)) {
        double cur = [[data objectAtIndex:0] floatValue];
        [socket emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
            [socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
        });
        ack(@[@"Got your currentAmount, ", @"dude"]);
    }];
    [socket connect];"
It is possible to indicate SocketIOClient that I will be a delegate of his sessionDelegate?
Thank you

**Comment by nuclearace** [comment]
First off, your socket url looks wrong. It looks like you should be using the `Path` option. You can use the SessionDelegate option to set a delegate. Also you should update to the latest version

```swift
let socket = SocketIOClient(socketURL: "https://xx.xxx.255.xx/", options: [.Path("xatsocket"), .SocketDelegate(self))
```

**Comment by dtorguet** [comment]
Ups! Thanks very much.
Could you write it in objective-C please

**Comment by nuclearace** [comment]
```objective-c
SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"https://xx.xxx.255.xx/" options:@{@"path": @"https://xx.xxx.255.xx/", @"socketDelegate": self}];
```

**Comment by dtorguet** [comment]
Thanks very much! ;)))

**Comment by dtorguet** [comment]
Sorry but (@"socketDelegate": self )no work!  I updated to v4.0.4 also I try with (@"SessionDelegate": self)  but neither worked.
SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"https://xx.126.255.xx/" options:@{@"path": @"xatsocket/", @"SessionDelegate": self, @"log": @YES, @"forcePolling": @YES}];
 never call to NSURLSessionDelegate.
any idea that does not work?
I need to call URLSession: didReceiveChallenge: completionHandler:
My class have the protocol implemented.
@interface DetailsViewController : UIViewController<NSURLSessionDelegate,NSURLSessionDownloadDelegate, NSURLSessionTaskDelegate>
and the protocol's method too.
Thanks

**Comment by nuclearace** [comment]
```swift
SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"" options:@{@"path": @"xatsocket", @"socketDelegate": self}]
``` 

Seems to work for me

```objective-c
@interface Tester : NSObject <NSURLSessionDelegate>

@property (readwrite, nonatomic) SocketIOClient* socket;

- (id)init;
- (void)connect;
- (void)sendMessage:(NSString*)msg;
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * __nullable credential))completionHandler;

@end
```

**Comment by dtorguet** [comment]
sorry but for me, (@"socketDelegate": self) no work!
that's a pitty!

**Comment by nuclearace** [comment]
Are you sure that your class is implementing NSURLSessionDelegate

**Comment by dtorguet** [comment]
yes, this is my code in a ViewController
.h
#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>
@interface DetailsViewController : UIViewController<NSURLSessionDelegate>
.m
 - (void)viewDidLoad {
self.socket = [[SocketIOClient alloc] initWithSocketURL:@"https://xx.126.255.xx/" options:@{@"path": @"xatsocket", @"socketDelegate": self}];
    [self.socket on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
        NSLog(@"socket connected");
    }];
    [self.socket on:@"currentAmount" callback:^(NSArray* data, SocketAckEmitter* ack) {
        double cur = [[data objectAtIndex:0] floatValue];
    [self.socket emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
    [self.socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
        });
    [ack with:@[@"Got your currentAmount, ", @"dude"]];
    }];
     [self.socket connect];
}
#pragma mark - NSURLSessionDelegate
- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * credential))completionHandler{
    if([challenge.protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust]){
        if([challenge.protectionSpace.host isEqualToString:@"xx.126.255.xx"]){
            NSURLCredential *credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];
            completionHandler(NSURLSessionAuthChallengeUseCredential,credential);
        }
    }
}
any idea?

**Comment by nuclearace** [comment]
I don't know Objective-C well, but don't you have declare protocol conformance with

```objective-c
@interface Tester : NSObject <NSURLSessionDelegate>
```

**Comment by dtorguet** [comment]
yes I write 
'<addr>'@interface DetailsViewController : UIViewController <NSURLSessionDelegate>

**Comment by luzianscherrer** [comment]
Did you ever get this working? I am having the exact same issue, the delegate is not getting called despite having set

`    [params setObject:self forKey:@"sessionDelegate"];
`

I'm using the same object for dataTaskWithRequest connections and there the `- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler
` does get called.
