### ISSUE TITLE
NSData in JSON

### ISSUE THREAD

**Issue by jgimenez** [socketio/socket.io-client-swift#225]
It looks like I can receive NSData values inside a JSON but I can't send them. I don't get an error but the server disconnects with "client error". Probably something is wrong when encoding, but I could not get to the end of the issue.

Here is a way to reproduce:

        let socket = SocketIOClient(socketURL: "localhost:1235", options: [.Log(true), .ForcePolling(true)])
        
        socket.on("connect") {data, ack in
            let data = NSData()
            socket.emit("boom", ["x":data])
        }

**Comment by nuclearace** [comment]
That seems to work for me. Is this a node.js server?

**Comment by jgimenez** [comment]
Yes, in my package.json I'm using `"socket.io": "~1.3.7"`

**Comment by nuclearace** [comment]
![](https://i.imgur.com/pmZ86gk.png) Seems to work for me

**Comment by jgimenez** [comment]
I'm trying to figure out how to reproduce then. Will reopen if I find out. Thanks for your time.
