### ISSUE TITLE
Logger instance

### ISSUE THREAD

**Issue by robinhayward** [socketio/socket.io-client-swift#230]
Looks like SocketLogger.swift has a polluting global variable called Logger:

var Logger: SocketLogger = DefaultSocketLogger()

**Comment by nuclearace** [comment]
That should be scoped internal, so it'll only be visible if you include the source files directly

**Comment by robinhayward** [comment]
I don't use Cocoapods so yes, the files are in my (Swift) project

**Comment by robinhayward** [comment]
It's not always possible to use Cocoapods, it's a shame no one is interested in manually installable source these days.

**Comment by nuclearace** [comment]
I moved Logger into a static variable. And my prefered way of installing Swift libraries is via copying

**Comment by robinhayward** [comment]
Ah awesome, sorry, I just mis-interpreted 'closed' as the end of the discussion.

Thanks very much!
