### ISSUE TITLE
Socket io client can't emit sometimes

### ISSUE THREAD

**Issue by Antowkos** [socketio/socket.io-client-swift#231]
I install this framework via cocoapods and use it in objective-c. Everything works fine, but sometimes the client's status is `SocketIOClientStatusConnected`, but it can't send messages. Server also detect my connection and can send message to me. I use `emit:withItems:` method for sending messages. 

For catching this i implement disconnection on `applicationDidEnterBackground` and connection on `applicationDidBecomeActive`. After that i just minimize and maximize application and try to send message to server. Unfortunately it absolutely random and i can't give you some stable steps for reproducing it.

**Comment by nuclearace** [comment]
You only get about 5 seconds of background execution before you app is suspended. There's multiple closed issues about this. It's just something inherent in iOS.

**Comment by Antowkos** [comment]
I know about few seconds of background execution. You didn't understand me right. 

The bug happens **sometimes**. It could happen even right after successful connection without minimize/maximize app. I try to describe it again:

Implementation of `SocketIOClient` created and connected. Status is `SocketIOClientStatusConnected`. I can receive messages from server. But `emit:withItems:` method not work.

**Comment by nuclearace** [comment]
Where are you trying to emit from? When you say that it could happen even right after a successful connection does that mean putting emits into a `connect` event handler?

**Comment by nuclearace** [comment]
Also, have you tried turning on logging?

```Objective-C
SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:8080" options:@{@"log": @YES}];
```

```swift
let socket = SocketIOClient(socketURL: "localhost:8080", options: [.Log(true)])
```

**Comment by Antowkos** [comment]
Nope. I emit sometime after connection. But before emit i check socket client's status and it's `SocketIOClientStatusConnected`. Actually it doesn't matter when i will emit after this bug occur. I won't be able to emit until reconnect.

About logging - I will try to turn it on, but i'm not sure it will say something. I subscribe to `error` event but it never happens.

**Comment by nuclearace** [comment]
Hm, that's a good suggestion, right now `error` is only used on connection failures. But it might be good to emit it for other non-fatal errors

**Comment by Antowkos** [comment]
Hi again. I tried to turn on logs and i can see the following when everything is ok: 
```
Log SocketIOClient: Emitting: 2["myEvent",{"id":600}]
Log SocketEngine: Writing ws: 2["myEvent",{"id":600}] has data: 0
Log SocketEngine: Sending ws: 2["myEvent",{"id":600}] as type: 4
```

But when the bug occur i can see only this
`Log SocketIOClient: Emitting: 2["myEvent",{"id":600}]`

In both cases after all i see this staff:
```
...
Log SocketEngine: Writing poll:  has data: 0
Log SocketEngine: Sending poll:  as type: 2
Log SocketEngine: POSTing: 1:2
Log SocketEngine: Doing polling request
Log SocketEngine: Got polling response
Log SocketEngine: Got message: 3
Log SocketEngine: Doing polling request
Log SocketEngine: Writing poll:  has data: 0
Log SocketEngine: Sending poll:  as type: 2
Log SocketEngine: POSTing: 1:2
Log SocketEngine: Doing polling request
Log SocketEngine: Got polling response
Log SocketEngine: Got message: 3
Log SocketEngine: Doing polling request
Log SocketEngine: Writing poll:  has data: 0
Log SocketEngine: Sending poll:  as type: 2
...
```

So i don't see any errors or something like that. Just silence after emit.

**Comment by nuclearace** [comment]
Does this happen if you force WebSocket?

**Comment by Antowkos** [comment]
I tried to force WebSockets and now i can't catch this bug. It works more stable and faster. What exactly does this `forceWebsockets` option do?

**Comment by nuclearace** [comment]
The default socket.io connection starts with HTTP long-polling and then upgrades to WebSocket if it can. Forcing WebSockets causes it to skip the long-polling

**Comment by nuclearace** [comment]
My guess is you were causing some weird race condition, which is hard to reproduce. If you could provide a minimal example project where it happens that would be helpful

**Comment by DanteCore** [comment]
I have the same bug, after each "connect" I have to emit new client configurations to my server, but sometimes emit action doesn't perform.

        socket.on("connect") {data, ack in
           socket.emit("updateSession", /*some token*/)
        }

**Comment by nuclearace** [comment]
If you turn on logging does it say that it's emitting?

**Comment by DanteCore** [comment]
In the right case I have: 
Log SocketIOClient: Emitting: 2["updateSession",{"user":"565c56588712008d324bd01e"}]
Log SocketEngine: Writing ws: 2["updateSession",{"user":"565c56588712008d324bd01e"}] has data: 0
Log SocketEngine: Sending ws: 2["updateSession",{"user":"565c56588712008d324bd01e"}] as type: 4
But its hardly to reproduce incorrect case

**Comment by patriksharma** [comment]
Hello , 

Does anyone knows what is this bug. I'm facing same issue. I got connected and authenticated true using emit. When I call another event to change password , its not showing any output to me.

`let PasswordDict: [String : AnyObject] = [
        
        "newPassword" :"123456" as AnyObject,
        "password" :"654321" as AnyObject
        
        ]
self.hubConnection.emit("USER_CHANGE_PASSWORD", with: [tmp as Any])`

Log response : 
```
Emitting: 2["USER_CHANGE_PASSWORD",{"newPassword":"123456","password":"654321"}]
2016-09-28 15:22:07.017 FApp[21664:1267871] LOG SocketEngine: Writing poll: 2["USER_CHANGE_PASSWORD",{"newPassword":"123456","password":"654321"}] has data: false
2016-09-28 15:22:07.018 FApp[21664:1267871] LOG SocketEnginePolling: Sending poll: 2["USER_CHANGE_PASSWORD",{"newPassword":"123456","password":"654321"}] as type: 4
2016-09-28 15:22:07.018 FApp[21664:1267871] LOG SocketEnginePolling: Created POST string: 71:42["USER_CHANGE_PASSWORD",{"newPassword":"123456","password":"654321"}]
2016-09-28 15:22:07.018 FApp[21664:1267871] LOG SocketEnginePolling: POSTing
2016-09-28 15:22:07.019 FApp[21664:1267871] LOG SocketEnginePolling: Doing polling request
2016-09-28 15:22:07.353 FApp[21664:1268409] LOG SocketEngine: Writing poll:  has data: false
2016-09-28 15:22:07.354 FApp[21664:1268409] LOG SocketEnginePolling: Sending poll:  as type: 2

```
