### ISSUE TITLE
Memory leak when using from obj-c 

### ISSUE THREAD

**Issue by art-of-dreams** [socketio/socket.io-client-swift#233]
Hi. It seems like obj-c method initWithSocketURL:options: creates leaks every time you use it in 4.1.1 version.
<img width="1018" alt="screenshot 2015-11-12 01 41 15" src="https://cloud.githubusercontent.com/assets/6998763/11116362/47f1fc48-8943-11e5-95b5-8dd4a9cb622d.png">

All fine if you use initWithSocketURL:opts: method from version 3.1.6.

**Comment by nuclearace** [comment]
Probably related to how the NSDictionary is turned into a Set<SocketClientOptions>. That being said, it's most likely a bug in Swift. Since there's no capture lists being done that could leak. Also, using Instruments to do memory debuging for Swift is kinda sketchy.

**Comment by art-of-dreams** [comment]
Yea, i'm not very experienced in swift, just noticed this leak in my obj-c app and decided let you know. So is it better to use version 3.1.6 from obj-c?

**Comment by nuclearace** [comment]
It's hard for me to recommend using old versions. If you think it's important to avoid this leak I would recommend using a small Swift class that holds your socket

**Comment by art-of-dreams** [comment]
Clearly, thanks for the reply.
