### ISSUE TITLE
Secure?

### ISSUE THREAD

**Issue by Lincolnnus** [socketio/socket.io-client-swift#234]
Hi, specified https in the socketURL and also added secure for the options. However, it still doesn't connect. I check again, there is another field for secure which still shows false whatever I do. So strange.
<img width="753" alt="screen shot 2015-11-15 at 12 00 24 pm" src="https://cloud.githubusercontent.com/assets/978867/11167152/da5284dc-8b90-11e5-83e6-e7a0f717dc48.png">

**Comment by nuclearace** [comment]
Hm, are you sure it's not Apple's new App Transport Security? It'll only connect to secure connections that meet a certain criteria. You can add handlers for `error` and `disconnect` to see if it's failing

Also, your connect method looks like you've just picked up Swift. Here's a better one using a capture list and avoiding force unwrapping.

```swift
func connect() {
    socket.on("connect") {[weak self] (data, ack) -> Void in
        print("finish connect")
        self?.socket.emit()
    }
    
    socket.on("auth") {[weak self] (data, ack) -> Void in
        print("finish auth")
    }
    
    socket.connect()
}
```

**Comment by nuclearace** [comment]
Any updates?

**Comment by Lincolnnus** [comment]
Hi Erik,

The bug was from the server end, we've fixed that. Seems the secure flag
does not matter.

Thanks for your advise on the Swift code.

On Tuesday, 1 December 2015, Erik Little <notifications@github.com> wrote:

> Any updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io-client-swift/issues/234#issuecomment-160720545>
> .
>


-- 
Best Regards,
Shaohuan Li
