### ISSUE TITLE
Crashes on SocketEventHandler.executeCallback

### ISSUE THREAD

**Issue by cqin5** [socketio/socket.io-client-swift#235]
I received multiple crash reports that trace back to **SocketEventHandler.executeCallback** and I wonder why this happened. 

Fairly new at reading crash reports, so I'm not sure if there were things wrong with my event handlers. 

Didn't have that problem when testing with my own devices though.

**Comment by nuclearace** [comment]
This doesn't really tell me anything. I would at least need a line number for where it's crashing

**Comment by nuclearace** [comment]
Any updates?

**Comment by cqin5** [comment]
@nuclearace Sorry that I forgot about this. Please mark it as resolved. :)

**Comment by aly-irshad** [comment]
Hello @nuclearace ,

Having the same type of crash on SocketEventHandler.executeCallback in SocketIOClient.swift line no 430  and unable to track the reason. The screenshot might help you to understand whats the issue.

![screen shot 2018-01-26 at 6 07 46 pm](https://user-images.githubusercontent.com/20099371/35440088-e89f7390-02c3-11e8-885a-293b35b126ea.png)

**Comment by avaneeshkawasthi** [comment]
@nuclearace can you help me with that issue...i am facing the same issue faced by @alimirshad
