### ISSUE TITLE
Invalid namespace

### ISSUE THREAD

**Issue by janroures** [socketio/socket.io-client-swift#236]
hello, been trying to connect to a namespace manually in swift client using socket.joinNamespace("/"+whatever), however, i always get the error message "Invalid namespace". Anyone found a solution for this? Any help is appreciated.

**Comment by janroures** [comment]
i've also tried joining with         

socket = SocketIOClient(socketURL: path, options: [.Log(true), .ForcePolling(true), .Nsp("/whatever")]) 
and
socket = SocketIOClient(socketURL: path, options: [.Log(true), .ForcePolling(true), .Nsp("whatever")])

but non of these work either. thanks.

**Comment by nuclearace** [comment]
Does the server have those namespaces open?

**Comment by janroures** [comment]
sometimes they are, sometimes they aren't. is it possible to "open" a namespace from the client?

btw, thanks for such a quick response.

**Comment by nuclearace** [comment]
Not that I'm aware of

**Comment by janroures** [comment]
then, how is it that I can open it from the browser client but not the ios app? My goal is that the user has to join a namespace of his choice. any approach for this? thanks

**Comment by nuclearace** [comment]
How are you joining from the browser?

**Comment by janroures** [comment]
var socket = io.connect('http://"ip":"port"/'+whatever);

that's what I'm using

**Comment by nuclearace** [comment]
Because when I test socket.io-client against a namespace the server doesn't have open it doesn't connect

**Comment by nuclearace** [comment]
Or rather it looks like it goes to the default namespace handler but doesn't emit a `connect` event

**Comment by janroures** [comment]
that's odd. Is there any way to send data to the server along the connect event? Would like to send the namespace "name" so I can open it from the server before joining from the client. Thanks.

**Comment by nuclearace** [comment]
There's `connectParams`

**Comment by janroures** [comment]
Will look into it. Thanks.

**Comment by nuclearace** [comment]
Any updates?

**Comment by nuclearace** [comment]
Closing because of lack of updates

**Comment by dpakthakur** [comment]
let manager = SocketManager(socketURL: URL(string: SOCKET_URL)!, config: [.log(true), .compress])
let socket = manager.socket(forNamespace: "/whateverNamespace");

**Comment by onizukaspm** [comment]
> Or rather it looks like it goes to the default namespace handler but doesn't emit a `connect` event

i did the same test: connecting to server with a not exist namespace, i can see server return '/xxx, ,invalid namespace', but it is not an 'error' or a 'connect_error', and no 'connect' event been emited. The most weird thing is i can receive almost all broadcast event (default namespace) even i don't on() them. i can do nothing in this scenario, because of no event emited. Maybe socket.io-client should handle 'invalid namespace' as a connection error, and close the connection. 

really appreciated if anyone will reply
