### ISSUE TITLE
Compatibility problem with sails.js v0.11.x

### ISSUE THREAD

**Issue by cwoloszynski** [socketio/socket.io-client-swift#239]
I am using this library (thanks for the great work!) with sails.js.  I am seeing an incompatibility with sails.js.  See http://stackoverflow.com/questions/32590533/connect-sails-io-with-an-ios-swift-app

The fix on the server side basically forces the server to not test the API version from the client. I'd prefer to fix the client to say it is 0.11.0 or greater and make sure that the code meets those requirements.  

Can you suggest how to use the library to send the right parameters when connecting to a Sails.js v0.11 server?  I think it is looking for 'query[__sails_io_sdk_version]' to be '0.11.0' in the handshake.  I am not sure how to set that with this library.  Sorry if this is a newbie question.

**Comment by nuclearace** [comment]
I have no idea what sails.js does differently than a default socket.io server. But you can send custom parameters with `connectParams`

**Comment by cwoloszynski** [comment]
Thanks for the pointer to connectParams.  

For those that might have the same question, I used the following code to address this issue.  

```
self.socket = SocketIOClient(socketURL: baseWebSocketServerURL, 
options: [SocketIOClientOption.ConnectParams(["__sails_io_sdk_version":"0.11.0"])])
```

This allowed me to use Sails.js v0.11.0 without having to modify the server.
