### ISSUE TITLE
"The request timed out."

### ISSUE THREAD

**Issue by NBibikov** [socketio/socket.io-client-swift#244]
Hello. Please help me! I do chat IOS app and chat already working. But for some time it stopped. Now I can not connect to the server - get the error "The request timed out."

Thank. I use swift library in objective-c code

my serverURL is @"https://xxx:8888/";
This is my code

```
self.socket = [[SocketIOClient alloc] initWithSocketURL:serverURL options:@{@"log": @YES, @"forcePolling": @YES}];

        [self.socket on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
            DDLogVerbose(@"socket CONNECTED!");
            
            NSDictionary* arguments   = @{@"user_id"        : userID,
                                          @"nickname"       : fullName};
            
            [self.socket emit:@"connecting" withItems:@[arguments]];
            
            // Emit supscribe for server know that this client online
            NSDictionary* arguments2   = @{@"room"  : userID,
                                           @"personal"    : @YES};
            [self.socket emit:@"subscribe" withItems:@[arguments2]];
            
            //Socket off connect
            [self.socket off:@"connect"];
            
        }];

        [self configureSocketError];
        [self configureSocketAllNotReadMessages];
        [self configureSocketGetMessagesForSidebar];
        [self configureSocketDisconnect];
        
        [self.socket connect];
```

and on server side only
```
info: listening on *:8888
info: listening on *:8888
info: listening on *:8888
info: listening on *:8888
info: listening on *:8888
info: listening on *:8888
```

**Comment by AlexChesters** [comment]
Do you ever make a connection? Does this line `DDLogVerbose(@"socket CONNECTED!");` ever get called?

**Comment by NBibikov** [comment]
No connection is not established

**Comment by nuclearace** [comment]
Does your server pass the new requirements for SSL? Also make sure your server is configured properly

**Comment by NBibikov** [comment]
I have disabled SSL with line "Allow Arbitrary Loads" in info.plist. is that correct? About server settings - Android client has connection and works well. Can this be  with wrong settings on server?

**Comment by AlexChesters** [comment]
@NBibikov I don't believe that "disables" SSL, it merely allows HTTP connections to be made

**Comment by NBibikov** [comment]
Oh, ok! what i need do on client side or server side for check SSL?
