### ISSUE TITLE
SocketEngine message parser problem

### ISSUE THREAD

**Issue by medisean** [socketio/socket.io-client-swift#245]
Normal message like this:
4"\"name\":\"hello\""

SocketEngine: Line 411
 message.removeAtIndex(message.startIndex),then message like this:
"\"name\":\"hello\""

 But in SocketParse method parseString(message: String), you still check if the first char is Int. And of course this is not true. 
I guess this is a bug?

**Comment by nuclearace** [comment]
How would the default client handle a message of unknown type? Because an engine message of `4{"name:\"hello\"}"` would become an invalid client packet

**Comment by sharjeel-ahmed** [comment]
So is this a bug or not? my on event not being fired.

**Comment by nuclearace** [comment]
This is probably unrelated to your on not being fired.
