### ISSUE TITLE
emit with NSDictionary

### ISSUE THREAD

**Issue by ilandbt** [socketio/socket.io-client-swift#247]
Hi,
I need to emit with a key value structure (NSDictionary).
Is there a way to do this?

Thanks,
Ilan

**Comment by nuclearace** [comment]
```swift
let dict = ["someKey": true]
socket.emit("someEvent", dict)
```

**Comment by ilandbt** [comment]
Works... thanks.

**Comment by weirdyu** [comment]
I need to emit NSDictionary by use Objective-C, how could do?
