### ISSUE TITLE
Remove event handler function missing

### ISSUE THREAD

**Issue by Katafalkas** [socketio/socket.io-client-swift#25]
Hey. is it possible to add `off` function that would remove event handler ? Or is it there and I just can not find it.

**Comment by nuclearace** [comment]
I'll add it. It's like 3 lines of code

**Comment by Katafalkas** [comment]
Cheers ! This will work for me, altho it might be a problem for someone who has multiple handlers for the same event, and want to remove a specific handler.

**Comment by nuclearace** [comment]
There's no good way to deal with that though. It would probably require redoing handlers.
