### ISSUE TITLE
Swift Compiler Error 'Segmentation fault 11' when creating custom SocketLogger

### ISSUE THREAD

**Issue by hanishabsigh** [socketio/socket.io-client-swift#251]
I keep getting a Swift compiler error similar to the one found [**here**](http://stackoverflow.com/questions/31863462/swift-compiler-error-segmentation-fault-11-generics-conform-to-protocol) when using this code:

```
import Socket_IO_Client_Swift

class CustomSocketLogger: SocketLogger {
  func log(message: String, type: String, args: AnyObject...) {
    
  }

  func error(message: String, type: String, args: AnyObject...) {
    
  }
}
```

Am I doing something wrong? If so, can anybody show an example of how to create a custom SocketLogger in Swift? Thanks!

**Comment by nuclearace** [comment]
Doing something like

```swift
private class CustomLogger : SocketLogger {
        var log = true
    
    /// Normal log messages
    func log(message: String, type: String, args: AnyObject...) {
        print(message)
    }
    
    /// Error Messages
    func error(message: String, type: String, args: AnyObject...) {
        print(message)
    }
}
```

Works for me

**Comment by hanishabsigh** [comment]
It was happening because I wasn't giving `log` a value. The only other difference you had was setting the class to `private`, but that didn't make any difference. I think that is a very odd error... but it works now, thanks!
