### ISSUE TITLE
ignores connectParams in obj-c project

### ISSUE THREAD

**Issue by vyacheslavk** [socketio/socket.io-client-swift#252]
I have obj-c project with pods, when i try to connect to server 
`
@"forceWebsockets" : @TRUE,
@"connectParams":@[@{@"token" :token}, @{@"app-type" : @"client"}, @{@"client-type" : @"ios"}],
`

server is getting /?transport=websocket

I have same parameters on android app and all working well

**Comment by nuclearace** [comment]
works for me 
```objective-c
self.socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:8080" options:@{@"connectParams": @{@"hello": @"test"}}];
```
have you made sure you're only sending strings in connect params

**Comment by vyacheslavk** [comment]
Yes! Thx. that solved my problem
