### ISSUE TITLE
Is there a  Object-C  library??

### ISSUE THREAD

**Issue by Niue** [socketio/socket.io-client-swift#253]
Because bridging headers aren't allowed in frameworks , so I cannot use it in my Object-C framework. Could you develop a  Object-C library ??

**Comment by AlexChesters** [comment]
You can use this library in Objective-C quite easily

**Comment by nuclearace** [comment]
I really have no desire to create a purely Objective-C version of this. Swift offers compatibility with Objective-C, and is much nicer to write in.
