### ISSUE TITLE
Support for Rooms?

### ISSUE THREAD

**Issue by KCastiglione** [socketio/socket.io-client-swift#26]
Is there support for rooms functionality?

http://socket.io/docs/rooms-and-namespaces/

If yes can you please add examples/HOWTOs [Objective-C example too ]!

**Comment by nuclearace** [comment]
Rooms are something done on the server. 

```javascript
io.sockets.on("connection", function(socket) {
    socket.join("testRoom")
}

**Comment by nuclearace** [comment]
https://github.com/nuclearace/Socket.IO-Client-Swift/issues/19

**Comment by MobileDev418** [comment]
Is there support for join event on a client?
