### ISSUE TITLE
cant compile the project with the current sdk. 

### ISSUE THREAD

**Issue by orensha** [socketio/socket.io-client-swift#264]
socketIOClient has many errors such as:

- use of undeclared type 'SocketEngineSpec'
- use of unresolved identifier 'SocketIOClientStatus'  

and 34 more. what to do?

**Comment by nuclearace** [comment]
What is the current sdk. Because it works fine with Xcode 7.2. You probably forgot to add stuff to your target

**Comment by orensha** [comment]
Hi, i changed the to Xcode 7.2 and now the swift files compile.
but i have another problem. I’m using the ‘connected’ variable of ‘SocketIOClient’  but in the current sdk it doesn’t apear. what other option do i have replacing it? thanks
On Dec 16, 2015, at 5:42 PM, Erik Little <notifications@github.com<mailto:notifications@github.com>> wrote:


What is the current sdk. Because it works fine with Xcode 7.2. You probably forgot to add stuff to your target

**Comment by nuclearace** [comment]
You have to check the `status` of the socket. https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClientStatus.swift#L28

**Comment by orensha** [comment]
Thanks it works.
On Dec 22, 2015, at 4:58 PM, Erik Little <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to check the status of the socket. https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClientStatus.swift#L28
