### ISSUE TITLE
On the IOS 8.3 cannot be used(Objective-C )

### ISSUE THREAD

**Issue by benben-hello** [socketio/socket.io-client-swift#266]
The target “Demo” contains source code developed with an earlier version of Swift. Choose “Convert” to update the source code in this target to the latest Swift syntax. This action can be performed later using “Convert to Latest Swift Syntax” in the Edit menu.

**Comment by nuclearace** [comment]
What version of xcode are you using

**Comment by benben-hello** [comment]
Version 7.2

**Comment by benben-hello** [comment]
Version 7.2

**Comment by nuclearace** [comment]
I'm not sure why it would say that. How are you including the library?

**Comment by benben-hello** [comment]
Yes, IOS9 without any problem but in 8.3 will not compile

**Comment by AlexChesters** [comment]
I'm using `socket.io` fine on iOS 8 and above using Cocoapods, @benben-hello how have you installed the library?
