### ISSUE TITLE
Framework lacks callback for emit. 

### ISSUE THREAD

**Issue by ka05** [socketio/socket.io-client-swift#267]
I may have functionally misunderstood the way that I am supposed to use socket.io but I created a node server and web client with socket.io and within the web client I primarily used emit() and relied upon the callbacks for everything. Maybe that approach is wrong, but either way I believe it would be valuable to have a callback option for the emit function in swift. If this functionality exists already please point me in the right direction, otherwise can you please add it and provide brief documentation? Thank you

**Comment by nuclearace** [comment]
If the api you're using sends acks for emits you can use emitWithAck. Which should be in the example on the readme

**Comment by ka05** [comment]
Please excuse my ignorance but I don't understand what acks are or how i would use them in my api. Ive looked around a bit but I cant find anything about how to make my api send acks. Could you please point me in the right direction?

**Comment by nuclearace** [comment]
```swift
socket.emitWithAck("canUpdate", cur)(timeoutAfter: 0) {data in
    // after the server acks
}
```

**Comment by ka05** [comment]
Okay thanks but what are acks? and how can I implement that on the server?

**Comment by nuclearace** [comment]
```javascript
 socket.on("ackack2", function(data, int, ack) {
        console.log("got ackack2")
        console.log(data)
        ack("got ackack2")
})
```

```swift
socket.emitWithAck("ackack2", 1, 5)(timeoutAfter: 0) {data in print(data[0]}
```

**Comment by ka05** [comment]
Okay I have just tried that and im still not getting anything back. Additionally nothing is being logged out on the server when the emit in the swift code is called. I must be doing something very wrong

**Comment by nuclearace** [comment]
Your server code has too many arguments for that emit. It should only have two.

**Comment by ka05** [comment]
Okay I thought so. I originally only had (data, ack) but I looked at the example you provided earlier and it said (data, int, ack). I was thrown off by that but tried it anyways. I just tried by taking out the "int" argument and it still doesnt work.

**Comment by nuclearace** [comment]
Does the socket even connect? I notice in your example it doesn't look like you're setting the port for the client.

**Comment by ka05** [comment]
Yeah, it connects. For some reason Heroku does port forwarding so when i hit https://uno-server.herokuapp.com it connects without needing the port but the emits dont seem to be working.

**Comment by nuclearace** [comment]
I'm not sure what else to say, all my tests seem to be working

**Comment by ka05** [comment]
Thanks, I just tried by running my server locally and it worked so it must be something to do with heroku. Sorry I wasted your time with this issue.
