### ISSUE TITLE
Namespaces don't appear to be supported

### ISSUE THREAD

**Issue by ka05** [socketio/socket.io-client-swift#269]
I have a namespace declared on my server as the following.

```
var app = express();
server = app.listen(3000);
var io = require('socket.io').listen(server);
var loginIO = io
  .of('/login')
  .on("connection", function(socket){
    var loggedIn = false,
        socketId = socket.id;

    socket.on('validateLogin', function(data, fn){
      console.log("validate login called");
      data.socketId = socketId;
      users.validateLogin(data, {
        success:function(user){
          loggedIn = true;
          fn({valid:true, user:new coreData.User(user)});
        },
        error:function(){
          fn({valid:false});
        }
      })
    });
});
```

I've tried connecting via the following swift code:
```
let socket = SocketIOClient(socketURL: "localhost:3000/login", options:["log": true])
```
It will not connect and instead returns html. Ive made sure that I do not have any routing code that would send html when the users goes to "localhost:3000/login"

Is there a way to connect to the "/login" namespace that Im unaware of or is that functionality just missing as of now? If it is missing can you please add this functionality? Thank you kindly

**Comment by ka05** [comment]
I thought I should mention that I did see the other issues regarding namespaces but they were all for Objective C and Im trying to do this in swift, just in case you thought this was a duplicated issue.

**Comment by nuclearace** [comment]
You can't connect to a namespace using the url. You have to use the Nsp(String) option.

```swift
let socket = SocketIOClient(socketURL: "localhost:8080", options: [.Nsp("/login")])
```

**Comment by ka05** [comment]
Thank you. my apologies for missing that.
