### ISSUE TITLE
obj-c  interface

### ISSUE THREAD

**Issue by abo** [socketio/socket.io-client-swift#27]
Did SocketIOClient.swift L 217
> public func emitObjc(event:String, withItems items:[AnyObject]) {

should be

> public func emitObjc(event:String, withItems items:AnyObject) {

?

**Comment by nuclearace** [comment]
No, because Objective-C doesn't have variadic functions you have to use an array

**Comment by abo** [comment]
how can i emit `{ hello: 'world' }` in objective-c , not `[{ hello: 'world' }]` ,

**Comment by nuclearace** [comment]
You can't, but it shouldn't be sent as [{hello: "world"}].

Because

```swift
func emit(event:String, items:AnyObject...) {}
```

is actually the same as

```swift
func emit(event:String, items:[AnyObject]) {}
```

But with some syntactic sugar so you can do `emit("test", 1, 2, 3, 4, "test" 2.2)`

**Comment by nuclearace** [comment]
Although you're right, it's not right
