### ISSUE TITLE
Updating connection opts on a existing connection, before reconnecting. 

### ISSUE THREAD

**Issue by ffager83** [socketio/socket.io-client-swift#271]
Hi,

I'm stuck with a problem, have tried allot of different things but still cannot get it to work. And honestly, I don't even know if this is supported. I tried to search for something similar, but haven't found anything exactly like this. 
Anyway.. I'll try to describe the issue.

1. On app launch, app checks for token and if no token was found, shows the login screen. (Socket is already connected to our API, without any tokens sent to it, with limited access to api functions) 
2. User logins and on a successful login: 

  - Receives a token.
  - Current Socket session is set to authenticated=true on the backend and gets access to all functions. (But the connection from the client side is still initially connected without the token as a cookie to be sent in SocketIOClientOptions.)

3. The received token is saved in the phone for later use.

4. And if the app is closed (terminated) and re-opened the saved token will be used as a cookie and sent with the socket handshake. And the backend will validate token and if valid, again, sets the connection to an authenticated connection. User regains all access and can continue using the app. And on connection loss and automatic reconnect, everything works as expected, since the saved token is sent as the cookie on the initial connection (after the app launched after termination). 

So far so good. This all works as expected.

Now, IF the user logs in and is still on the initial connection that was done without the token sent as a cookie for handshake, and the network connection is lost or backend restarts (..for whatever reason?!).
- Socket.io client automatically try to reconnect.
- But the connection isn't set to authenticated = true on a successfully reconnect on the backend since no token was sent with the reconnect request. So user will be in limbo mode, without any permissions to do anything until terminates app and re-opens it. 

So now finally to the main question:
- Can I update the already existing connection options for a socket connection? (For example, directly after login, when the token is received add it to say socket.options so it can be used on next possible reconnect event.)

I tried: 
cookie is a valid NSHTTPCookie object. 
socket.options.insert(.Cookies([cookie]))
and also to self.socketOptions
But the new options doesn't show up on the backend log (handshake, headers, cookies ... ). 

My default socket client and options are: 
socketOptions = [.Log(false), .Secure(true), .ForceWebsockets(true), .Reconnects(true), .ReconnectWait(2)]
socket = SocketIOClient(socketURL: remoteAPI.URL, options: self.socketOptions)
(tried secure true/false, tried polling/websockets, always the same issue..)
With ForceNew(true) I got a little bit closer, but then I had multiple connections. 

Hope someone has some good pointers on this.
Thank you!

**Comment by nuclearace** [comment]
Right now I think you'd have to readd the socket with the new options.

**Comment by ffager83** [comment]
Thank you nuclearace for the quick reply! 

Hmm, I need to look into that again then. Last time that caused multiple events (duplicates) after reconnect, but I'll try to figure something out. Dunno why, afaik, I only had one connect() listed. 

If you ever have the time and figure out a solution to this, that would be much appreciated, but I guess this could be listed as a "more exotic" case..aka. not a everyday issue, so my guess is that the priority for this will be kept pretty low. :) 

Anyway, keep up the good work!

**Comment by nuclearace** [comment]
Well it wouldn't involve much, just changing the availability of connectParams to public. I just didn't anticipate someone needing to change them after the connection is established.

**Comment by ffager83** [comment]
Heh, well yeah..thats what I suspected as well. 
I'll take a look at that, but not sure if thats something I manage to change/fix. 

But at least good to know where to start looking. thx

**Comment by ffager83** [comment]
Well, I'll be damned.. I got it working! 
Changing connectParams to public from private fixed this issue. 
The "issue", more like special feature request.. 

This doesn't enable me to send the token as a cookie, but as a query string, which for the moment is just as good! The backend already has support for token as a cookie or as query string. 

Big thanks to you @nuclearace for this! I owe you one..  :beer:

**Comment by nuclearace** [comment]
4ed4681cc413d1aa9e052ad45a87b04a9d82bb0c
