### ISSUE TITLE
Socket Connection Not working with distributed build

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [socketio/socket.io-client-swift#274]
Hi, when I create and enterprise build and install that ipa file in my real device, the socket connection doesn't work, but if I run the code from xcode works!, I'm using swift 2.0. Do I need to add some particular configuration for the distributed build? . I'm `Using Socket.IO-Client-Swift (4.1.2)`

**Comment by nuclearace** [comment]
Make sure you're not pointing to localhost or another host that the device cannot reach.

**Comment by cesar-oyarzun-m** [comment]
yeah I'm sure that I'm not pointing to localhost and yes the device can reach the host. I'm using HTTPS connection, do I have to add 
    
    <key>NSAppTransportSecurity</key>
		<dict>
    	<key>NSAllowsArbitraryLoads</key>
    	<true/>

it works when I run with xcode in the same device, but when I do enterprise build it won't work

**Comment by nuclearace** [comment]
If your server's TLS connection doesn't conform to Apple's new security requirements you might need that.

**Comment by cesar-oyarzun-m** [comment]
Thanks, I have try different ways still not luck. Do you think maybe server side?. Is really weird that the HTTPS rest call works but the socket io doesn't.

    <key>NSExceptionDomains</key>
    <dict>
    <key>api.com</key>
    <dict>
      
      <key>NSIncludesSubdomains</key>
      <true/>
      
      <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
      <true/>
      
      <key>NSTemporaryExceptionMinimumTLSVersion</key>
      <string>TLSv1.1</string>
    </dict>
  </dict>
and 

    <key>NSAppTransportSecurity</key>
    <dict>
    
    <key>NSAllowsArbitraryLoads</key>
      <true/>
    </dict>

**Comment by nuclearace** [comment]
My only other thought is that you're not giving the right URL

**Comment by cesar-oyarzun-m** [comment]
mmm the URL is right bc I'm testing with Xcode and run the app and everything works, but when I do the build for Ad-hoc distribution doesn't work.

**Comment by cesar-oyarzun-m** [comment]
@nuclearace I'm checking the logs of my app that is already install in the Ipad. I'm getting

    Jan 11 11:41:43 Exton-iPad-Mini networkd[90] <Error>: -[NETAWDManager reportStats:metricID:] AWDServerConnection newMetricContainerWithIdentifier failed for metric 2686983, server 0x12ce2f150, not reporting:
	<AWDLibnetcoreTCPConnectionReport: 0x12ce34f30> {
	    cellularFallbackReport =     {
	        dataUsageSnapshotsAtNetworkEvents =         (
	                        {
	                bytesIn = 5400;
	                bytesOut = 2100;
	            }
	        );
	        "fallbackTimer_msecs" = 0;
	        fellback = 0;
	        networkEvents =         (
	            "NETWORK_EVENT_DATA_STALL_AT_APP_LAYER"
	        );
	        "timeToNetworkEvents_msecs" =         (
	            3640
	        );
	    };
	    clientIdentifier = "scala.Exp-Retail";
	    connectionStatisticsReport =     {
	        DNSAnswersCached = 1;
	        "DNSResolvedTime_msecs" = 5;
	        RTTvariance = 42;
	        "appDataStallTimer_msecs" = 3;
	        appReportingDataStallCount = 1;
	        "bestRTT_msecs" = 113;
	        betterRouteEventCount = 0;
	        bytesDuplicate = 720;
	        bytesIn = 6400;
	        bytesOut = 2100;
	        bytesOutOfOrder = 0;
	        bytesRetransmitted = 770;
	        cellularFallback = 0;
	        cellularRRCConnected = 0;
	        connected = 1;
	        connectedInterfaceType = "INTERFACE_TYPE_WIFI";
	        "connectionEstablishmentTime_msecs" = 106;
	        connectionReuseCount = 0;
	        "currentRTT_msecs" = 109;
	        "flowDuration_msecs" = 43552;
	        interfaceType = "INTERFACE_TYPE_WIFI";
	        kernelReportedStalls = 0;
	        kernelReportingConnectionStalled = 0;
	        kernelReportingReadStalled = 0;
	        kernelReportingWriteStalled = 0;
	        packetsDuplicate = 0;
	        packetsIn = 12;
	        packetsOut = 12;
	        packetsOutOfOrder = 0;
	        packetsRetransmitted = 0;
	        "smoothedRTT_msecs" = 106;
	        synRetransmissionCount = 0;
	        tcpFastOpen = 0;
	        "timeToConnectionEstablishment_msecs" = 112;
	        "timeToConnectionStart_msecs" = 6;
	        "timeToDNSResolved_msecs" = 6;
	        "timeToDNSStart_msecs" = 1;
	        trafficClass = 0;
	    };
	    delegated = 0;
	    reportReason = "REPORT_REASON_DATA_STALL_AT_APP_LAYER";
	}
    [467] <Warning>: Log SocketEngine: Sending ws:  as type: 2
    [467] <Warning>: ERROR SocketIOClient: The operation couldn’t be completed. Socket is not connected
    [467] <Warning>: Log SocketIOClient: Handling event: error with data: (
	    "The operation couldn\U2019t be completed. Socket is not connected"
	)
    [467] <Warning>: Log SocketIOClient: Handling event: reconnect with data: (
	    "The operation couldn\U2019t be completed. Socket is not connected"
	)
    [467] <Warning>: Log SocketIOClient: Starting reconnect

**Comment by nuclearace** [comment]
Looks like some kind of network issue

**Comment by cesar-oyarzun-m** [comment]
@nuclearace I fix that problem I'm connecting to different network now I don't have that message and my logs looks like that I'm connected, but I still can't receive or send messages in the socket connection

    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: [Fabric] Unable to locate application icon
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: [Crashlytics] Version 3.5.0 (97)
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Adding handler for event: connect
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Adding handler for event: disconnect
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Adding handler for event: message
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Adding engine
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Starting engine
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Handshaking
    Jan 11 12:12:40 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Doing polling request
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got polling response
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got message: 0{"sid":"jixyAl2ETXQDGt2jAHdc","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Doing polling request
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got polling response
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Doing polling request
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got message: 40
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketParser: Parsing 0
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Socket connected
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Handling event: connect with data: (
	)
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Sending ws: probe as type: 2
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got message: 3probe
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Upgrading transport to WebSockets
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Sending poll:  as type: 6
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: POSTing: 1:6
    Jan 11 12:12:41 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Doing polling request
    Jan 11 12:12:42 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got polling response
    Jan 11 12:12:42 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Sending ws:  as type: 5
    Jan 11 12:12:42 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Flushing probe wait
    Jan 11 12:12:42 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got message: 6
    to log backtraces.
    Jan 11 12:13:06 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Writing ws:  has data: 0
    Jan 11 12:13:06 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Sending ws:  as type: 2
    Jan 11 12:13:06 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got message: 3
    Jan 11 12:13:12 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketIOClient: Emitting: 2["message",{"payload":{"uuid":"60137e95-d5ab-4480-9716-e6188cde838a"},"channel":"organization","name":"fling","type":"broadcast"}]
    Jan 11 12:13:12 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Writing ws: 2["message",{"payload":{"uuid":"60137e95-d5ab-4480-9716-e6188cde838a"},"channel":"organization","name":"fling","type":"broadcast"}] has data: 0
    Jan 11 12:13:12 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Sending ws: 2["message",{"payload":{"uuid":"60137e95-d5ab-4480-9716-e6188cde838a"},"channel":"organization","name":"fling","type":"broadcast"}] as type: 4
    Jan 11 12:13:31 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Writing ws:  has data: 0
    Jan 11 12:13:31 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Sending ws:  as type: 2
    Jan 11 12:13:31 -iPad-Mini Exp_Retail[472] <Warning>: Log SocketEngine: Got message: 3

**Comment by nuclearace** [comment]
Looks like you are emitting, so my guess is you're not interacting with your api correctly.

**Comment by cesar-oyarzun-m** [comment]
@nuclearace I found the problem, when I do the distribution build for some reason the token is empty, here is the code for the connection.
    
    public  class SocketManager {
    
    public var socket = SocketIOClient(socketURL: hostUrl, options: ["log": true,
        "reconnects": true,
        "reconnectAttempts": 5,
        "reconnectWait": 5,
        "connectParams": ["token":"test","test":tokenSDK]])
 
     public func start_socket() -> Promise<Bool> {
      self.socket.connect()
    }

there is some other way of passing the params?
