### ISSUE TITLE
Reconnect cannot reconnect because already connected

### ISSUE THREAD

**Issue by alexeyhippie** [socketio/socket.io-client-swift#279]
Getting after update to 5.0.0 (haven't upgraded a few months)

If set reconnects to "true" like this 

```swift
let socket = SocketIOClient(socketURL: url,
                options: ["log": true])
            socket.reconnects = true
            socket.reconnectWait = kReconnectionTimeout
```

when app gets [Time out] error (for example when you put app run on pause), app trying to reconnects and calls __open__ method of __SocketEngine__

```swift
public func open(opts: [String: AnyObject]? = nil) {
        connectParams = opts
        
        if connected {
            DefaultSocketLogger.Logger.error("Tried to open while connected", type: logType)
            client?.didError("Tried to open engine while connected")

            return
        }

        DefaultSocketLogger.Logger.log("Starting engine", type: logType)
        DefaultSocketLogger.Logger.log("Handshaking", type: logType)

        resetEngine()
        ...
```

and it ends up because connected is true

**Comment by alexeyhippie** [comment]
```swift
forceNew = true
```
helps of course

**Comment by PeterL1n** [comment]
I think I experienced the similar problems. It crushes the program a lot.

**Comment by PeterL1n** [comment]
ForceNew does not help

**Comment by PeterL1n** [comment]
I downgraded to 5.3.0 and it works fine. The problem only exists in 5.3.1

It is not hard to recreate the issue at all. It is extremely common that my app crushes using slow 4G network.

You can set a button to reconnect, and press it multiple times.
Other conditions that will cause it fails include when the there is a socket request and you turn down the server in the middle, the app will crush.

5.3.1 is too unstable, I recommend taking it down

**Comment by nuclearace** [comment]
What do you mean "a button to reconnect," like a button that calls reconnect?

**Comment by nuclearace** [comment]
@alexeyhippie you can see if the latest master is any better. If it is I can push a new version. If you're using cocapods you can do `pod 'Socket.IO-Client-Swift'', :git => 'https://github.com/socketio/socket.io-client-swift.git'`

@PeterL1n I haven't been able to reproduce your crashes. Do you have a crashlog or better yet a line number?

**Comment by alexeyhippie** [comment]
Hey, @nuclearace 

thanks, I tried the same with 5.3.1 - if forceNew is false then app connects well, but after first disconnect it keeps connects and disconnects right after connection established, with [Ping timeout] error. if forceNew is true - it reconnects well.

**Comment by nuclearace** [comment]
Try the latest master. I haven't released a version with the new code because I'm unsure if it's going to break things even more. It seems to work for me

**Comment by alexeyhippie** [comment]
Yes, this is actually was latest master, sorry for misleading. So there is no error I got on 5.0.0, but instead it keeps connects and immediately disconnects with ping timeout error.

**Comment by alexeyhippie** [comment]
In fact, git says that there is no difference in sources for 
-    pod 'Socket.IO-Client-Swift', '~> 5.3.1'
and 
-    pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git'

**Comment by nuclearace** [comment]
Really? Because https://github.com/socketio/socket.io-client-swift/compare/v5.3.1...master shouldn't be on 5.3.1

**Comment by nuclearace** [comment]
Is there an easy way to reproduce this?

**Comment by nuclearace** [comment]
I went ahead and pushed a new version.

**Comment by alexeyhippie** [comment]
Don't know why, pod didn't download any difference between  '~> 5.3.1' :git => 'https://github.com/socketio/socket.io-client-swift.git'

Now, in 5.3.2, there is no original error, so I think this issue is solved. But there is another with failed reconnection and ping timeout, if forceNew = false. 

Here is logs: 

2016-02-05 14:50:28.089 Xeepic[63209:26247342] LOG SocketIOClient: Trying to reconnect
2016-02-05 14:50:28.090 Xeepic[63209:26247342] LOG SocketIOClient: Handling event: reconnectAttempt with data: (
    "-1"
)
2016-02-05 14:50:28.091 Xeepic[63209:26247342] ERROR SocketEngine: Engine tried opening while connected. Assuming this was a reconnect
2016-02-05 14:50:28.091 Xeepic[63209:26247342] LOG SocketEngine: Engine is being closed.
2016-02-05 14:50:28.091 Xeepic[63209:26247342] LOG SocketEngine: Sending ws:  as type: 1
2016-02-05 14:50:28.092 Xeepic[63209:26247342] LOG SocketEngine: Starting engine
2016-02-05 14:50:28.094 Xeepic[63209:26247342] LOG SocketEngine: Handshaking
2016-02-05 14:50:28.406 Xeepic[63209:26257168] LOG SocketEngine: Got message: 0{"sid":"qeKxVTXkLt2Piq6XAAfV","upgrades":[],"pingInterval":500,"pingTimeout":5000}
2016-02-05 14:50:28.407 Xeepic[63209:26257168] LOG SocketEngine: Got message: 40
2016-02-05 14:50:28.407 Xeepic[63209:26257168] LOG SocketIOClient: Should parse message: 0
2016-02-05 14:50:28.408 Xeepic[63209:26257168] LOG SocketParser: Parsing 0
2016-02-05 14:50:28.408 Xeepic[63209:26257168] LOG SocketParser: Decoded packet as: SocketPacket {type: 0; data: []; id: -1; placeholders: 0; nsp: /}
2016-02-05 14:50:28.409 Xeepic[63209:26257168] LOG SocketIOClient: Socket connected
2016-02-05 14:50:28.409 Xeepic[63209:26257168] LOG SocketIOClient: Handling event: connect with data: (
)
2016-02-05 14:50:28.910 Xeepic[63209:26247342] LOG SocketIOClient: Starting reconnect
2016-02-05 14:50:28.910 Xeepic[63209:26247342] LOG SocketIOClient: Handling event: reconnect with data: (
    "Ping timeout"
)

it repeats each 5 seconds, as timeout


Probably there is something wrong with settings on server side. What ping timeout and ping period should be used, you think?

**Comment by nuclearace** [comment]
I would just stick with whatever the defaults are

**Comment by alexeyhippie** [comment]
Thanks, I will check it with project server guys. 
But these logs aren't something unusual in this case?

**Comment by nuclearace** [comment]
Might be a bug in the ping counter. I'm starting to regret making the engine reusable. Seems to cause more problems than it's worth

**Comment by alexeyhippie** [comment]
Update: 
setup default period (25000) and timeout (60000) on server side fix the second issue. 
Even more, I found out that this reconnect bug appears only when I set app flow on pause (i.e through debugger) and not appears if connection fails because of network.

**Comment by prgorasiya** [comment]
Disconnecting manager first works for me.
My code is as follow
```
socket?.onAny { (data) in
            if data.event == "reconnectAttempt" {
                self.socketManager?.disconnect()
                self.connectSocket()
            }
        }
```
