### ISSUE TITLE
Import Issue on Obj-C with Cocoapod

### ISSUE THREAD

**Issue by ctc316** [socketio/socket.io-client-swift#282]
The tutorial for obj-c project importing this library by Cocoapod is not quite working on me. I'm using Xcode 7.2  & Cocoapod 0.39.0. And my installed library has both its product name and product module name as "Socket_IO_Client_Swift". So under my circumstance, the import way should be 

<b> --> #import \<Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h\> </b>
<br>

![2016-01-19 2 23 20](https://cloud.githubusercontent.com/assets/8285764/12411265/3bceaaa6-beb8-11e5-8088-65d2c17bf9be.png)

![2016-01-19 2 33 34](https://cloud.githubusercontent.com/assets/8285764/12411449/b5adb186-beb9-11e5-962b-13c39afe3568.png)

**Comment by AlexChesters** [comment]
in [v5.2.0](https://github.com/socketio/socket.io-client-swift/releases/tag/v5.2.0) the project name was changed, you'll have to update your cocoapods installation of the library to 5.2.0 or above.

Then you can import like in your example

**Comment by nuclearace** [comment]
If `#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>` works then you're on pre-5.2.0

**Comment by xclidongbo** [comment]
/Users/lidongbo/Desktop/Foundation/IOS/Test_SocketIO/Test_SocketIO/ViewController.m:15:9: 'Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h' file not found
