### ISSUE TITLE
Crashes on deinit since 5.2.0

### ISSUE THREAD

**Issue by tomizimobile** [socketio/socket.io-client-swift#283]
I've got a `UIViewController` that contains a `SocketIOClient`, and everything works fine in versions < 5.2.0, but since the updates to `WebSocket`, I get one of three different crashes every time that this viewController is deinitted - 
[backtrace.txt](https://github.com/socketio/socket.io-client-swift/files/97740/backtrace.txt)
[backtrace2.txt](https://github.com/socketio/socket.io-client-swift/files/97742/backtrace2.txt)
[backtrace3.txt](https://github.com/socketio/socket.io-client-swift/files/97743/backtrace3.txt)

I'm calling `SocketIOClient.disconnect()` in my `deinit` method, but I did notice that if I take that out, I only seem to get the first crash.

**Comment by nuclearace** [comment]
Have you tried 5.2.1, there was a bug fix in it.

**Comment by nuclearace** [comment]
Oh wait, I'm seeing these too

**Comment by nuclearace** [comment]
You can use `.ForcePolling(true)` as a temporary workaround.

**Comment by tomizimobile** [comment]
Great, thanks for the quick response.

**Comment by nuclearace** [comment]
I filed a bug report here, as I think it's a problem with the WebSocket library: https://github.com/daltoniam/Starscream/issues/158

**Comment by nuclearace** [comment]
I released a new version that reverts to an older websockets version until it's fixed.
