### ISSUE TITLE
Using Socket.IO Client framework within an Obj-C static library

### ISSUE THREAD

**Issue by andyshephard** [socketio/socket.io-client-swift#285]
I'd like to add the Socket.io client within a static library in my project, that I'm using for API development. As the static library houses all of the API calls, it makes it easier to drag and drop into another project whenever we need to make the same calls for another app.

Swift files don't work well with static libraries, and so I tried to build the framework product and add this to the static library, but I'm still getting errors:

- ld: framework not found SocketIOClientSwift for architecture arm64

I've tried to edit the Socket.IO Client project to ensure it's building for all architectures, but still getting the error. Is there any way to use the Socket.IO Client within a static library, or will I have to try something else?

**Comment by nuclearace** [comment]
Swift doesn't support static libraries because its ABI isn't stable.
