### ISSUE TITLE
App crash V.5.2.3

### ISSUE THREAD

**Issue by Abreu0101** [socketio/socket.io-client-swift#286]
When I try to close (deprecated) or disconnect the Socket or set the property to nil,  the app crash. I'm using the last version (v.5.2.3), before a I was using a minor version to swift 1.2, but I've to update to Xcode 7 and that part of code, stop working:

```
func stopSocket(){
         if let socket = self.socket{
            socket.removeAllHandlers()
            self.socket = nil
        }
}
```

**Comment by nuclearace** [comment]
What's the crash log?

**Comment by Abreu0101** [comment]
Thank for replay and sorry for the delay, now it's working, I only changed to (I will notify if the problem persist, but in this moment is working fine):
func stopSocket(){
         if let socket = self.socket{
            socket.removeAllHandlers()
        }
        self.socket?.disconnect()
}
