### ISSUE TITLE
Version Stability - Sockets

### ISSUE THREAD

**Issue by jeremybrowning** [socketio/socket.io-client-swift#287]
How stable is 4.1.6 versus any of the version in the 5.X range? I ask because we are considering moving this library to a production app where the sockets are fundamental to its operation. Lately, you've released several updates after 5.0 was released and the crash that was reverted in 5.2.2 gave us pause.

**Comment by nuclearace** [comment]
v5.2.3 _should_ be as stable as 4.X since that bug in websocket got reverted. That being said, I have no idea if #286 a bug in the client or if it's because of the way it's being used. And I can't seem to reproduce it.

**Comment by nuclearace** [comment]
v5.0.0 did fix a small memory leak caused by reflection though. But it wasn't a massive leak. It would only become a problem if you somehow created tons of clients.
