### ISSUE TITLE
When passing in a valid URL, init adds extra "/".

### ISSUE THREAD

**Issue by someoneAnyone** [socketio/socket.io-client-swift#288]
Hi! I'm working on an iOS app that leverages your library and I'm running into a small problem, that I've created work around for but thought the team might want to be aware of it.

In my app users' enter a URL to their site and the app connects to it... I do a lot of validation to the url to make sure it reachable, etc. and it creates a valid NSURL.

I then use that NSURL to create a socket connection to that site. When I do sometimes there is a trailing "/" and sometimes there isn't.

My workaround for that problem was to manually detect and trim that off but I also thought the library could be improved to handle such a case by adopting NSURL as an init parameter or by creating one in the the init.

Here is my sample code...

```Swift
let urlString = "http://foobar.com/"
let url = NSURL(string: urlString)
  // Create a socket.io client with a url string.
self.socket = SocketIOClient(socketURL: url.absoluteString, options: [.Log(true), .ForcePolling(false)])
```
and here is where the extra "/" seems to be added.
```Swift
self.options.insertIgnore(.Path("/socket.io"))
```

Is there some option I missed?

Thanks!

**Comment by nuclearace** [comment]
Going to require some refactoring, since the engine does a lot of manipulations with the URL because of engine.io. So I'll just do a quick hack to drop trailing /s

**Comment by someoneAnyone** [comment]
If you're moving towards using NSURL as a parameters you might be interested in the:
```swift
let urlString = "http://foobar.com/"
let url = NSURL(string: urlString)!

// https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSURL_Class/#//apple_ref/occ/instm/NSURL/URLByAppendingPathComponent:
url.URLByAppendingPathComponent("socket.io")
```
Extensions... they cleanly manipulate url strings... there is also NSURLComponents which offers other higher level query building.

**Comment by nuclearace** [comment]
I used a mixture of both
