### ISSUE TITLE
 SocketEngine: Got message: {"statusCode":404,"error":"Not Found"}

### ISSUE THREAD

**Issue by susena** [socketio/socket.io-client-swift#291]
let socket = SocketIOClient(socketURL: "188.166.230.9:8170/?token=032361d52e7ce3bc11cc843e", options: ["log": true])
self.socket.connect()

**Comment by nuclearace** [comment]
You can't have a query in the url. Instead you have to use ConnectParams

```swift
let socket = SocketIOClient(socketURL: "188.166.230.9:8170", options: [.ConnectParams(["token": "032361d52e7ce3bc11cc843e"), .Log(true)])
```
