### ISSUE TITLE
Its the client able to have multiple socket connections?

### ISSUE THREAD

**Issue by someoneAnyone** [socketio/socket.io-client-swift#292]
I need to maintain multiple connections to different socket.io servers. Is the library capable of this?
Seem to be connecting to each server but I'm only getting one "dataUpdate" event.

For example...

```Swift
 // Create a socket.io client with a url string.
var sockets: [SocketIOClient]?
   for (index, url) in sites.enumerate() {
            let socket = SocketIOClient(socketURL: url.absoluteString, options: [.Log(false), .ForceNew(true), .ForcePolling(false)]))
sockets.append(socket)
}
```

**Comment by nuclearace** [comment]
Be sure that you're adding handlers for each socket.

**Comment by someoneAnyone** [comment]
Sorry I over simplified the example. I add handlers and get connect Events for each but then only one will continue to get updates.

**Comment by nuclearace** [comment]
Have you tried turning on logging

**Comment by someoneAnyone** [comment]
I've tried several different ways of establishing separate socket connections but i seem to get one (the first one) ever stay connected and return data.

**Comment by nuclearace** [comment]
I haven't been able to reproduce. There shouldn't be anything tying the sockets together. Is it always the same server that's connecting or is it always the first socket.

**Comment by someoneAnyone** [comment]
ok, I'll keep debugging... thank you for checking.

**Comment by someoneAnyone** [comment]
I found a bug in my code where the same property was being recycled instead of created for each connection. Sorry about that.
