### ISSUE TITLE
connectParams Objective-C

### ISSUE THREAD

**Issue by andyshephard** [socketio/socket.io-client-swift#293]
Does the 'connectParams' dictionary parameter work when using the library in Objective-C

Connecting to the web socket server seems to work without the 'connectParams' parameter, however, when trying to add that parameter, the SocketEngine either gets stuck on 'Handshaking', or the socket just disconnects immediately.

This is how I'm structuring the parameters to attach to [[SocketIOClient alloc] initwithSocketURL:options:]

{
    connectParams =     {
        EIO = 3;
        interview = 56a934834abd36db5b68bcb5;
        "picture_url" = "https://creativ-dev.s3.amazonaws.com/users/default.png";
        sid = tt4fUiAUZXCva104AAAN;
        transport = websocket;
        "user_api_token" = m0d9evBJiG8rrwHUxWQd671dOPQvUVvc;
        "user_id" = 5698d5ce438063b9499a37c5;
        "user_name" = "Andrew Shephard";
    };
    forceWebsockets = 1;
    log = 1;
    reconnectAttempts = 0;
}

**Comment by nuclearace** [comment]
Adding sid and transport to the params is unnecessary, the engine will add those separately.

**Comment by andyshephard** [comment]
Sure, I've removed those two parameters and it's functioning now.
I have it working on a local instance with no problem, the remote instance required me to add the 'secure' flag, but the communication is working now.

Thank you!
