### ISSUE TITLE
Sending NSData succeed on iPhone 5 but failed on iPhone 6 and above

### ISSUE THREAD

**Issue by PeterL1n** [socketio/socket.io-client-swift#294]
Here is my code

```
let imageData: NSData = "Hello".dataUsingEncoding(NSUTF8StringEncoding)
socket.emitWithAck("user/settings/changeProfilePicture", imageData)(timeoutAfter: config.TimeoutLong) {res in
            callback(self.parseJSON(res))
        }
```

I use Netty-Socket.IO as my socket.io server.
It succeed on iPhone 4, iPhone 4s, and iPhone 5
but it failed on devices that are above iPhone 5s and iPad, both in stimulator and on real device.

I do not exclude the possibility that the server causes the problem
But Is there any reason for why some device succeed and other did not?
Does socket-client treat binary differently on different device?

**Comment by PeterL1n** [comment]
I found out that when using iPhone 5 or older device, the client sends out Base64
But when on iPhone 5s or newer device, the client does not convert NSData to Base64, but something else.

Is there any reason for this?

If I convert the data to base64 myself
`
let base64String:String = imageData.base64EncodedStringWithOptions(.Encoding64CharacterLineLength)
`
then send out the base64String, the server can work on all device.

**Comment by nuclearace** [comment]
It'll only convert it to base64 if it's using polling. Otherwise it'll send it raw through websockets

**Comment by PeterL1n** [comment]
However, I did turned on ForceWebSockets, and on the server side, it looks like it was using Websockets.

**Comment by PeterL1n** [comment]
Problem solved. It is a server side bug.

**Comment by satyamub** [comment]
@PeterL1n I am experiencing this same issue.. I am able to implement a normal chat interface however when it comes to image sending and receiving... I am not able to understand how to do it.

I am able to understand the concept after seeing this however I am not sure what to change at server end. Can you please help me with code snippets!!

**Comment by satyamub** [comment]
Did you implement any method in server to get the images?
How do you retrieve the image at client side?

**Comment by nuclearace** [comment]
Here's some code that I have that tests sending images. All it does is send an image to the client which the client just sends back, but I use it to make sure sending NSData doesn't corrupt it.

```javascript
// Wait for imageTest event to start the test
socket.on("imageTest", ack => {
    console.log("Got image test")
    fs.readFile("CaTBHah.png", (err, data) => {
        ack(data)
    })
})

socket.on("imageTestSend", img => {
    fs.writeFile("CaTBHah2.png", img)
})
```

```swift
socket.emitWithAck("imageTest")(timeoutAfter: 0) {data in
    guard let img = data[0] as? NSData else { fatalError("Error getting image") }
    socket.emit("imageTestSend", img)
}
```

**Comment by satyamub** [comment]
@nuclearace can't client send image and server receive then sends back!!!

**Comment by nuclearace** [comment]
Yeah, it would look mostly the same. You just have to turn your image into NSData and emit it

**Comment by PeterL1n** [comment]
@satyamub 
It is the same as sending string and receiving string.
I send NSData on the iOS side, and receive byte[] on the server.

**Comment by satyamub** [comment]
Thats true @PeterL1n .. I just want to see the code snippet while sending and the function signature and implementation at server. I am novice in node thats why don't know what to write.

I think at client end 

 let base64String:String = imageData.base64EncodedStringWithOptions(.Encoding64CharacterLineLength) //Conversion

        socket.emit("image", nickname, base64String)

Not sure what to write at server side.

Please rectify me if I am wrong in above statement and my question!!

**Comment by PeterL1n** [comment]
@satyamub 
There are two ways of transferring data using socket.io
One is to send binary bits directly, and another is to send base64String.
I would recommend just sending binary bits, because it is smaller than base64String.

1. For sending binary bits:
You don't convert UIImage to base64String. Instead, convert UIImage to NSData.

Afterward, directly send the NSData to the server:
```
let data: NSData = (some data here)
socket.emit("image", nickname, data)
```

On the server, you will receive the byte[], and do whatever you need with it. If you want to store it to the disk, then search google how to write byte[] to disk.

2. Base64String
If you insist to use base64String, then convert UIImage to base64String like what you have done.
Send the String to the server
```
let base64String: String = (your base64String)
socket.emit("image", nickname, base64String)
```

You will receive a String parameter on JAVA server. You need to convert it back to byte[], then do whatever you need

I can't give you codes, because currently I am not at my computer.

**Comment by satyamub** [comment]
@PeterL1n just one question I wanted to ask if that the below will work If I will send NSData to Server 

**Server side code**
    clientSocket.on('images', function(clientNickname, data){
    var currentDateTime = new Date().toLocaleString();
    var dataType = "imageType"
   delete typingUsers[clientNickname];
    io.emit("userTypingUpdate", typingUsers);
    io.emit('newChatMessage', clientNickname, data, currentDateTime,dataType);
  });

**Comment by satyamub** [comment]
@PeterL1n ... Sir can you please help in doing the server side code

**Comment by PeterL1n** [comment]
@satyamub Oh I am sorry. I thought you were using Java server.
I do not have experience with receiving data in node js
