### ISSUE TITLE
How to enable ssl? (question)

### ISSUE THREAD

**Issue by rachelxj** [socketio/socket.io-client-swift#295]
Hi, I want to enable ssl, but I don't know if it's ready to use or not. I couldn't make it work. Here is my code:

SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURLString:@"https://192.168.0.102:3000" options:@{@"log": @YES, @"forcePolling": @YES, @"selfSigned":@YES, @"Secure":@YES}];

I got this error:
ERROR SocketEnginePolling: The operation couldn’t be completed. (NSURLErrorDomain error -1202.)

**Comment by nuclearace** [comment]
If your server doesn't follow apple's guidelines for secure connections the connection will probably get rejected. And in the case of self-signed certs I think you'll need to set a sessionDelegate to handle the challenge

**Comment by rachelxj** [comment]
Can you please give me an example of sessionDelegate?

**Comment by nuclearace** [comment]
I'm not sure myself, you'll have to google

**Comment by CheerCc** [comment]
hi, @rachelxj ,now i have the same problem with yours. i want to encrypt my data use SSL too,my company will buy an authentication cert to encrypt.Do you solve this problem?If you have some methods to do, please tell me how to do.Thanks

**Comment by rachelxj** [comment]
Hi @CheerCc , I think you can just replace the url with the domain you used to apply to the cert, it'll be working.
