### ISSUE TITLE
I need to emit NSDictionary by use Objective-C, how could I do?

### ISSUE THREAD

**Issue by weirdyu** [socketio/socket.io-client-swift#296]

**Comment by nuclearace** [comment]
The same way you would using swift. But using objective-c syntax. There should be an example on the readme

**Comment by nuclearace** [comment]
Actually I forgot you have to enclose everything in an NSArray first.

**Comment by nuclearace** [comment]
But the objective-c example on the readme does cover sending a nsdictionary
