### ISSUE TITLE
Trailing slash in path

### ISSUE THREAD

**Issue by sveinhal** [socketio/socket.io-client-swift#297]
There is a regression in b67b6abbdfaa87abcf86ae7ec72da0f951e73b7a where the `.Path` option is interpreted differently before and after the commit in question. Before b67b6abbdfaa87abcf86ae7ec72da0f951e73b7a, a path of `/some/path` would make `createURLs()` return e.g polling url `https://example.com:443/some/path/?transport=polling&b64=1`, but after it returns `https://example.com:443/some/path?transport=polling&b64=1`. Note the slash between the path and the query string!

I guess this is a regression, since it worked before, and don't any more. Also, on the server side, the server is created without the explicit slash in the path parameter. Adding a slash to the path parameter fixes the issue.

**Comment by nuclearace** [comment]
No this isn't a regression. Paths are required to add a trailing /

**Comment by nuclearace** [comment]
I guess I can add a check and add one if it's missing

**Comment by sveinhal** [comment]
It _is_ a regression (something that used to work, that doesn't anymore), but I guess it is a regression by design. Which is fine, as long as the behaviour is documented.

**Comment by DanielRuf** [comment]
This breaks some setups for example when we use the mattermost API.
