### ISSUE TITLE
can i use socket with push notifications ??

### ISSUE THREAD

**Issue by KhaledAld** [socketio/socket.io-client-swift#299]

**Comment by AlexChesters** [comment]
Try to provide more information about what are you trying to achieve, this question is very ambigious and similar to #298.

**Comment by nuclearace** [comment]
https://developer.apple.com/notifications/ I really have no idea, I've never used push notifications, but I would assume no, since that would require background execution

**Comment by KhaledAld** [comment]
@nuclearace  Thx ^_^
