### ISSUE TITLE
Maybe use Starscream instead ?

### ISSUE THREAD

**Issue by Katafalkas** [socketio/socket.io-client-swift#3]
https://github.com/daltoniam/starscream Is fully swift.

**Comment by nuclearace** [comment]
The reason I didn't use starscream goes back to #2. And from the fact that I've had trouble trying to use full Swift frameworks. Although looking at the API, it is nice that it separates between Strings and Data. Which would simplify some of the client.

**Comment by nuclearace** [comment]
Another reason I didn't use starscream is that using Swift frameworks automatically means you're limited to iOS 8+.

**Comment by nuclearace** [comment]
Actually, it's really easy to just include starscream. So I might do that
