### ISSUE TITLE
WebSocket.swift:602. EXC_BAD_ACCESS KERN_INVALID_ADDRESS (Crashed: engineHandleQueue)

### ISSUE THREAD

**Issue by centurionas** [socketio/socket.io-client-swift#30]
Hi,

Our app is written in ObjC for iOS 7+, but we are getting this crash. This crash appears in a different place then previously reported:

Thread : Crashed: engineHandleQueue
0  libswiftCore.dylib             0x000000010131d814 swift_unknownRetainUnowned + 40
1  DevAuctionataLive              0x00000001000b86f4 DevAuctionataLive.SocketEngine.(parseEngineMessage in _4DCD037EFB1C27BE04F82A88FF07B400) (DevAuctionataLive.SocketEngine)(Swift.String) -> () (SocketEngine.swift:470)
2  DevAuctionataLive              0x00000001000b86f4 DevAuctionataLive.SocketEngine.(parseEngineMessage in _4DCD037EFB1C27BE04F82A88FF07B400) (DevAuctionataLive.SocketEngine)(Swift.String) -> () (SocketEngine.swift:470)
3  DevAuctionataLive              0x00000001000bb744 protocol witness for DevAuctionataLive.WebSocketDelegate.websocketDidReceiveMessage <A : DevAuctionataLive.WebSocketDelegate>(DevAuctionataLive.WebSocketDelegate.Self)(DevAuctionataLive.WebSocket, text : Swift.String) -> () in conformance DevAuctionataLive.SocketEngine : DevAuctionataLive.WebSocketDelegate (SocketEngine.swift:605)
4  DevAuctionataLive              0x000000010010df60 DevAuctionataLive.WebSocket.((processResponse in _8EBB333CEB46C95CC2731D7C6BDBCF21) (DevAuctionataLive.WebSocket) -> (DevAuctionataLive.WebSocket.WSResponse) -> Swift.Bool).(closure #1) (WebSocket.swift:602)
5  libdispatch.dylib              0x0000000198959994 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x0000000198959954 _dispatch_client_callout + 16
7  libdispatch.dylib              0x00000001989640a4 _dispatch_queue_drain + 1448
8  libdispatch.dylib              0x000000019895ca5c _dispatch_queue_invoke + 132
9  libdispatch.dylib              0x0000000198966318 _dispatch_root_queue_drain + 720
10 libdispatch.dylib              0x0000000198967c4c _dispatch_worker_thread3 + 108
11 libsystem_pthread.dylib        0x0000000198b3922c _pthread_wqthread + 816

**Comment by nuclearace** [comment]
What conditions is this happening? First message? Randomly? When I specific message happens?

**Comment by centurionas** [comment]
It happens quite randomly and crashes in different places. Therefore I created 3 different issues.

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/issues/29
