### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by raghavsai508** [socketio/socket.io-client-swift#301]
Thread : Crashed: NSOperationQueue 0x7fcaf97eec20 :: NSOperation 0x7fcafb829f90 (QOS: LEGACY)
0  libswiftCore.dylib             0x103fe656c swift_unknownRelease + 28
1  Location App                   0x100147cd8 specialized specialized _arrayOutOfPlaceUpdate<A, B where ...> (inout A, inout _ContiguousArrayBuffer<A.Element>?, Int, Int, B) -> () (SocketEngine.swift)
2  Location App                   0x100144a5b specialized Array._copyToNewGrownBuffer<A>(Int) -> () (SocketEngine.swift)
3  Location App                   0x10013f3be specialized SocketEngine.close(String) -> () (SocketEngine.swift)
4  Location App                   0x10013f51e specialized SocketEngine.didError(String) -> () (SocketEngine.swift:272)
5  Location App                   0x10013d3d6 @objc SocketEngine.didError(String) -> () (SocketEngine.swift)
6  Location App                   0x10014e1e1 SocketEnginePollable<A where ...>.(doLongPoll<A where ...> (A) -> (NSURLRequest) -> ()).(closure #1) (SocketEnginePollable.swift:121)
7  Location App                   0x10014d791 partial apply for SocketEnginePollable<A where ...>.(doLongPoll<A where ...> (A) -> (NSURLRequest) -> ()).(closure #1) (SocketEnginePollable.swift)
8  CFNetwork                      0x1017056b5 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
9  CFNetwork                      0x101717a02 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 302
10 Foundation                     0x100eff304 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
11 Foundation                     0x100e3b035 -[NSBlockOperation main] + 101
12 Foundation                     0x100e1df8a -[__NSOperationInternal _start:] + 646
13 Foundation                     0x100e1db9b __NSOQSchedule_f + 194
14 libdispatch.dylib              0x104a4c4a7 _dispatch_client_callout + 8
15 libdispatch.dylib              0x104a360e8 _dispatch_queue_drain + 1048
16 libdispatch.dylib              0x104a35aa0 _dispatch_queue_invoke + 595
17 libdispatch.dylib              0x104a373b8 _dispatch_root_queue_drain + 565
18 libdispatch.dylib              0x104a3717c _dispatch_worker_thread3 + 98
19 libsystem_pthread.dylib        0x104d7f68f _pthread_wqthread + 1129
20 libsystem_pthread.dylib        0x104d7d365 start_wqthread + 13

**Comment by andrewkouri** [comment]
What was the problem?

**Comment by S2V** [comment]
@andrewkouri related issue https://github.com/socketio/socket.io-client-swift/issues/356
