### ISSUE TITLE
swift_unknownRetainUnowned crash on failed websocket connection

### ISSUE THREAD

**Issue by CFKevinRef** [socketio/socket.io-client-swift#302]
`[SocketIOClientSwift.WebSocket retain]: message sent to deallocated instance`

This happens in the operation block submitted at the end of `initStreamsWithData()`. The websocket is deallocated before that 5-second timer is up, and the crash occurs at `self.cleanupStream()` when trying to reference `self`.

Locally I changed the self capture from unowned to weak, and now I just return from the block if self is nil. Not sure if this is the correct fix, though.

**Comment by nuclearace** [comment]
Like https://github.com/socketio/socket.io-client-swift/commit/2a25027077f3de92eb842482ee2595c11c6455ab ?

**Comment by CFKevinRef** [comment]
Pretty much like that, yes.

**Comment by CFKevinRef** [comment]
Fixed in 2a25027, thanks!
