### ISSUE TITLE
fatal error: This should never happen

### ISSUE THREAD

**Issue by soufianeEssabbane** [socketio/socket.io-client-swift#303]
Hi, i'm having a problem with a kind of random crash that happens continuously don't know exactly why, i'm using socket-io client in an objective c project i'm getting "Pods/Socket.IO-Client-Swift/Source/SwiftRegex.swift, line 27" ? can you PLEAAAASE tell me what maybe the cause ? did I did something wrong ?

**Comment by soufianeEssabbane** [comment]
ocketIOClientSwift	
SocketLogger.swift line 53
SocketLogger<A where ...>.(abstractLog in _5A5B34CAD36769831C85A7C9760DE2EE)<A where ...>(String, message : String, type : String, args : [AnyObject]) -> ()
9
SocketIOClientSwift	
SocketLogger.swift line 40
SocketLogger<A where ...>.log<A where ...>(String, type : String, args : [AnyObject]...) -> ()
10
SocketIOClientSwift	
SocketLogger.swift line 39
protocol witness for SocketLogger.log<A where ...>(String, type : String, args : [AnyObject]...) -> () in conformance DefaultSocketLogger
11
SocketIOClientSwift	
SocketParsable.swift line 157
SocketParsable<A where ...>.parseSocketMessage<A where ...>(String) -> ()
12
SocketIOClientSwift	
SocketIOClient.swift line 443
SocketIOClient.(parseEngineMessage(SocketIOClient) -> (String) -> ()).(closure #1)
13
SocketIOClientSwift	
SocketAckManager.swift line 0
thunk

**Comment by nuclearace** [comment]
Should be fixed in the latest master

**Comment by soufianeEssabbane** [comment]
Hi, thank you for the replay.

I'm using cocoapods and i did install the latest version "pod 'Socket.IO-Client-Swift', '~> 5.3.2'" but doesn't seems to be working ? my app crashes like all the time randomly. can you please explain why this is happening ? (just so that I understand).
to get it working should I download the master repo ? 

again thanks

**Comment by nuclearace** [comment]
I don't know how you managed to cause that unless you're running on a potato. But you can try 5.3.3

**Comment by soufianeEssabbane** [comment]
I'm using it in an objective c project, declaring socketIO Client as a property in my delegate. I start connexion at launch like this : 
     self.socket = [[SocketIOClient alloc] initWithSocketURL:url options:@{@"log": @YES, @"forcePolling": @YES}];
        
        [self.socket on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
                [_socket emit:@"id" withItems:@[userId]];
        }];
        
        [self.socket on:@"ping" callback:^(NSArray* data, SocketAckEmitter* ack) {
            

                [_socket emit:@"pong" withItems:@[@{@"sender":userId}]];
        }];
        
        [self.socket on:@"newMessage" callback:^(NSArray* data, SocketAckEmitter* ack) {
            if (data) {
                
                NSDictionary * message = (NSDictionary*)[data objectAtIndex:0];
                    [self.socket emit:@"delivered" withItems:@[@{@"_id":sktMessage.socketMessageId}]];
                }
            }
        }];
        
        [self.socket connect];

**Comment by soufianeEssabbane** [comment]
the update seems to be working

**Comment by soufianeEssabbane** [comment]
thanks (please if you see something wrong in my code tell me)
