### ISSUE TITLE
@"connect" event never arrive but client seems connected

### ISSUE THREAD

**Issue by zevarito** [socketio/socket.io-client-swift#305]
Hi,

I am using the lib with Objective-C. and Socket.IO 1.4.5.

After call `connect` method the event called `connect` never get's called, but my server app log shows the client were actually connected and once I close the IOS app the server logs the user has leave.

Any clue? Thanks.

**Comment by nuclearace** [comment]
Is the socket a property of a class. Most of the time people complain about events not being emitted the socket is being released because it isn't being stored as a property.

**Comment by zevarito** [comment]
It is an ivar, I will try it as a property, thanks!

On Monday, 8 February 2016, Erik Little <notifications@github.com> wrote:

> Is the socket a property of a class. Most of the time people complain
> about events not being emitted the socket is being released because it
> isn't being stored as a property.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io-client-swift/issues/305#issuecomment-181618439>
> .
>


-- 
Sent from Gmail Mobile

**Comment by zevarito** [comment]
It worked, thanks!
