### ISSUE TITLE
Socket crash on production

### ISSUE THREAD

**Issue by Division** [socketio/socket.io-client-swift#306]
Hi. After switching to the socket.io-client-swift app began crashing on the production. It never happened during testing but I see crash reports on Fabric. The app is built with swift optimization disabled.
The app is written in Objective-C.

<img width="951" alt="screen shot 2016-02-10 at 19 15 20" src="https://cloud.githubusercontent.com/assets/320958/12955213/af210cbe-d02a-11e5-8b11-6a2407f60b44.png">

Any ideas how to fix or at least to reproduce it?

**Comment by nuclearace** [comment]
What version are you using?

**Comment by Division** [comment]
I'm using version 5.3.1

**Comment by Division** [comment]
Less often it is crashing withlike this:
<img width="955" alt="screen shot 2016-02-10 at 20 05 35" src="https://cloud.githubusercontent.com/assets/320958/12956667/c693b78c-d031-11e5-8cb7-9b7bcfae5090.png">

**Comment by nuclearace** [comment]
Those crashes should be fixed in 5.3.3

**Comment by Division** [comment]
Thank you a lot. I will update.

**Comment by Division** [comment]
Was it the same issue in 5.3.1? Occures when server forces the polling mode.
Can I expect it to be fixed in 5.3.3?

![screen shot 2016-02-11 at 11 14 39](https://cloud.githubusercontent.com/assets/320958/12972818/eef11592-d0b0-11e5-9576-af0a09c1a418.png)
![screen shot 2016-02-11 at 11 18 57](https://cloud.githubusercontent.com/assets/320958/12975937/d2f8144a-d0c8-11e5-99e5-49cf89465de1.png)

**Comment by nuclearace** [comment]
Hm, 0f70079382b1e1b50e0f74400c954a1f9af53a77 might fix those two crashes, but I'm not sure
