### ISSUE TITLE
how can i get timeout event

### ISSUE THREAD

**Issue by jb522185660** [socketio/socket.io-client-swift#309]
how can i get timeout event after emit/on action!

**Comment by nuclearace** [comment]
You can use emitWithAck, but that requires the server to actually ack, otherwise everything with timeout

**Comment by Sudheeshvs** [comment]
I am using below method for getting acknowledgement from sever.
self.socket.emitWithAck("event", event.object) (timeoutAfter: 0, callback: {data in
var eventJson : JSON = JSON(data)[0]
})
Here i use timeout value as 0.
when i use this approach i am not getting No Ack, get getting response.
But rare chance i will not get the response. Please help me how to handle this.

Another simple question how to know the socketIO version number using Swift.
