### ISSUE TITLE
WebSocket.swift:283. EXC_BAD_ACCESS KERN_INVALID_ADDRESS (Crashed: engineHandleQueue)

### ISSUE THREAD

**Issue by centurionas** [socketio/socket.io-client-swift#31]
Hi,

Our app is written in ObjC for iOS 7+, but we are getting this crash. This crash appears in a different place then previously reported:

Thread : Crashed: engineHandleQueue
0  libswiftCore.dylib             0x00000001012b24e8 swift_getObjectType + 24
1  DevAuctionataLive              0x00000001000b1748 DevAuctionataLive.WebSocket.((disconnectStream in _8EBB333CEB46C95CC2731D7C6BDBCF21) (DevAuctionataLive.WebSocket) -> (Swift.Optional<ObjectiveC.NSError>) -> ()).(closure #1) (WebSocket.swift:283)
2  DevAuctionataLive              0x00000001000b1748 DevAuctionataLive.WebSocket.((disconnectStream in _8EBB333CEB46C95CC2731D7C6BDBCF21) (DevAuctionataLive.WebSocket) -> (Swift.Optional<ObjectiveC.NSError>) -> ()).(closure #1) (WebSocket.swift:283)
3  libdispatch.dylib              0x00000001968bd3ac _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x00000001968bd36c _dispatch_client_callout + 16
5  libdispatch.dylib              0x00000001968c74c0 _dispatch_queue_drain + 1216
6  libdispatch.dylib              0x00000001968c0474 _dispatch_queue_invoke + 132
7  libdispatch.dylib              0x00000001968c9224 _dispatch_root_queue_drain + 664
8  libdispatch.dylib              0x00000001968ca75c _dispatch_worker_thread3 + 108
9  libsystem_pthread.dylib        0x0000000196a992e4 _pthread_wqthread + 816

**Comment by nuclearace** [comment]
What conditions is this happening? First message? Randomly? When I specific message happens?

**Comment by centurionas** [comment]
It happens quite randomly and crashes in different places. Therefore I created 3 different issues.

**Comment by nuclearace** [comment]
WebSocket.swift:602
SocketEngine.swift:470

Listing issues here

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/issues/29
