### ISSUE TITLE
[Bug] Version 5.4.x

### ISSUE THREAD

**Issue by lucianocn** [socketio/socket.io-client-swift#310]
Hi,
Sometimes the socket stops to respond to events, even with status connected, on version 5.4.x.
I downgraded SocketIO to version 5.0.x and my app is working fine.

Does anyone are also having this same problem?

Thanks,

**Comment by nuclearace** [comment]
Did you figure this out?

**Comment by lucianocn** [comment]
@nuclearace the real issue is the #311.
I thought it was a problem with version 5.4.x, but it is happening with all versions.
