### ISSUE TITLE
'unhandled socket.io url' from server side.

### ISSUE THREAD

**Issue by gamugamu** [socketio/socket.io-client-swift#312]
Hi, 

I'm trying to using SocketIOClient, but for some reason, it doesn't work on iOS.

I have first implemented server-code and a js script client code in order to test the socket connection. And it worked well. The client get the 'connect' event and all the emit call are working.
I have also tested client code on a web file, and they all worked on Chrome or Safari. 

But for some reason, the same code logic isn't working on ios:
The url and port are working because the server side detect a connection, but for some reason, the server-side logs an **"unhandled socket.io url"** as info. And from my ios code I get an **"Could not connect to server"** .

I don't understand why I get this error: I'm using the latest version of socket.io (**socket.io 1.4.5 and socket.io-client 1.4.5 from js, Socket.IO-Client-Swift 5.4.1 on iOS**)
).

Do you have an idea why I can perform a connection between iOs client and server where it works on plain js?

Thanks in advance.

**Comment by nuclearace** [comment]
What's the code you're using to connect with the js client?

**Comment by nuclearace** [comment]
And also the Swift client

**Comment by gamugamu** [comment]
My sorries, after further research I found out I wasn't using the latest version of socketio from the server side. Upgrading it and it work nicely now. Thank you for your reactivity!
