### ISSUE TITLE
how to get event's name and event's data from SocketPacket object returned from parseData()?

### ISSUE THREAD

**Issue by thesugarrush** [socketio/socket.io-client-swift#313]
Hello,

Got a question regarding how to get event's name and event's data from SocketPacket object returned from parseData()?

Server emitted the following event and data to the client side 
```
2016-02-19 10:49:38.665 - LOG SocketEngine: Got message: 42 
["channel-found",[{"name":"my channel",,"jwt":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ey...IjoiRE","size":"1"}]]
```

And on client side (iphone apps), I implemented the following in my swift 2.0 code to extract the eventName as string, and eventData as NSDictionary. 
```
 socket.on("channel-found") {serverData, ack in
            let eventName = serverData[0] as? String
            let eventDataDict = serverData[1] as? NSDictionary
            print("eventName = \(eventName)");
            print("eventDataDict = \(eventDataDict)");
```

I got this error msg, for using the serverData[1]:
```
fatal error: Array index out of range.
```

I then run the serverData.count and it returns array of size 1. This makes me scratch my head because, shouldnt I be looking at serverData as an NSArray object type of size 2?

It seems that the data from the server is indeed in NSArray format  when the server emits the event to the client. But the SocketParser process somehow changed that to something else(?).
```
2016-02-19 10:49:38.666 -LOG SocketParser: 
Decoded packet as: SocketPacket {type: 2; data: [channel-found, (
        {
        jwt = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.ey...IjoiRE";
        name = testios;
        size = 1;
    }
)]; id: -1; placeholders: -1; nsp: /}
```

From SocketParsable.swift:

```    
// Parses data for events
    private func parseData(data: String) -> Either<String, [AnyObject]> {
        let stringData = data.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
        do {
            if let arr = try NSJSONSerialization.JSONObjectWithData(stringData!,
                options: NSJSONReadingOptions.MutableContainers) as? [AnyObject] {
                    return .Right(arr)
            } else {
                return .Left("Expected data array")
            }
        } catch {
            return .Left("Error parsing data for packet")
        }
    }
```

Sorry if this is a dumb question as I am pretty new to Swift and IoS programming. Question is how to get what I need: the eventName into a String, and the eventData to some sort of Dictionary?

A quick search found this [commit and closed issue] (https://github.com/socketio/socket.io-client-swift/issues/69l). Probably (un)related?

Thank you in advance.

**Comment by nuclearace** [comment]
It looks like the server is sending an Array, so your serverData[1] is wrong. It should be serverData[0] as? NSArray. Which looks like it contains an array of dictionaries

**Comment by thesugarrush** [comment]
nuclearance,

thank you..thank you.

I got it to work by doing this like u suggested:
```
socket.on("channel-found") {data, ack in
            let eventDataTemp = data[0] as? NSArray;
            let eventData = eventDataTemp![0] as? Dictionary<String, String>;
            print("eventName = \(eventData!["name"]!)");
            print("eventNJwt = \(eventData!["jwt"]!)");
```

Hopefully this will help somebody else that has similar issue. I am closing this issue now.
