### ISSUE TITLE
retrieve messages back from server to swift app 

### ISSUE THREAD

**Issue by LamourBt** [socketio/socket.io-client-swift#314]
I am having trouble to retrieve messages back into the app, so far I am successful sending message from the app to server and also displaying them into the console.log() by using 
`self.socket.emit("chat", textToSend)` 

To retrieve I tried this code but nothing happens

 ```
 socket.on("chat") { (T :[AnyObject], ack :SocketAckEmitter) -> Void in
            print(ack )
            print(T.count)
            
        }
```

I tried to use the websocket delegate `websocketDidReceiveMessage` still nothing happend

**Comment by nuclearace** [comment]
Are you sure the server sending an event named chat?

**Comment by LamourBt** [comment]
Yes I am sure, once I run the application on both my emulator and my phone, the console.log() of the server show that I have two connections and I could send messages from both devices and i will see the messages that I have sent in the console.log of the server. the problem is that I cannot retrieve the messages back into the client  where I pushed them into an data structure to populate my UITableView

**Comment by nuclearace** [comment]
Just because one client sends a message to the server doesn't mean it gets sent to all clients. The server has to send another message.

**Comment by LamourBt** [comment]
So when the server receive the message, I broadcast it to everyone `socket.broadcast.emit({username:socket.username,message:data});`

**Comment by nuclearace** [comment]
Don't you have to include the event name? I'm not sure on the server api.

**Comment by nuclearace** [comment]
But I'm pretty sure this is a server problem

**Comment by LamourBt** [comment]
I could use it like that also, `socket.broadcast.emit("chat",{username:socket.username,message:data});`

But how to get the message from the client side ?

**Comment by nuclearace** [comment]
If the server is properly sending the messages adding a handler for `chat` should work.

```swift
socket.on("chat") {data, ack in }
```

**Comment by LamourBt** [comment]
so where you think i should call it this because I did try that code in the viewDidLoad() but it was not called

**Comment by nuclearace** [comment]
If you look at my example I have a method that adds the handlers. https://github.com/nuclearace/socket.io-client-swift-example/blob/master/TicTacIOiOS/ViewController.swift#L25

**Comment by nuclearace** [comment]
You can turn on logging for the socket to see if it's even getting the message.

**Comment by nuclearace** [comment]
```swift
let socket = SocketIOClient(socketURL: NSURL(), options: [.Log(true)])
```

**Comment by LamourBt** [comment]
`2016-02-20 13:24:55.125 IOSocket[13926:960515] LOG SocketEngine: Writing poll:  has data: 0
2016-02-20 13:24:55.128 IOSocket[13926:960515] LOG SocketEnginePolling: Sending poll:  as type: 2
2016-02-20 13:24:55.128 IOSocket[13926:960515] LOG SocketEnginePolling: Created POST string: 1:2
2016-02-20 13:24:55.130 IOSocket[13926:960515] LOG SocketEnginePolling: POSTing
2016-02-20 13:24:55.132 IOSocket[13926:960515] LOG SocketEnginePolling: Doing polling request
2016-02-20 13:24:55.156 IOSocket[13926:961108] LOG SocketEnginePolling: Got polling response
2016-02-20 13:24:55.156 IOSocket[13926:961108] LOG SocketEnginePolling: Doing polling request
2016-02-20 13:24:55.157 IOSocket[13926:960976] LOG SocketEngine: Got message: 3
message to send is what are you doing ?
2016-02-20 13:24:55.783 IOSocket[13926:959965] LOG SocketIOClient: Emitting: 2["chat","what are you doing ?"]
2016-02-20 13:24:55.785 IOSocket[13926:959965] LOG SocketEngine: Writing poll: 2["chat","what are you doing ?"] has data: 0
2016-02-20 13:24:55.786 IOSocket[13926:959965] LOG SocketEnginePolling: Sending poll: 2["chat","what are you doing ?"] as type: 4
2016-02-20 13:24:55.787 IOSocket[13926:959965] LOG SocketEnginePolling: Created POST string: 33:42["chat","what are you doing ?"]
2016-02-20 13:24:55.789 IOSocket[13926:959965] LOG SocketEnginePolling: POSTing
2016-02-20 13:24:55.789 IOSocket[13926:959965] LOG SocketEnginePolling: Doing polling request`

**Comment by LamourBt** [comment]
As you can see the message was sent and i try to add the call `socket.on("chat"){contents,akc in }` but nothing happened

**Comment by nuclearace** [comment]
The message is sent, but the only message that the engine looks like it's getting is "3 message to send is what are you doing ?" which doesn't look like a valid socket.io packet. What server version are you using?

**Comment by LamourBt** [comment]
I sent the message "what are you doing?" and the version is **socket.io@1.4.5**

**Comment by nuclearace** [comment]
Does this same server code work for the JS client? Because I think something's not right with your server code.

**Comment by LamourBt** [comment]
do you mean if i am using this server to connect with my swift application? and if that's the question yes I am

**Comment by nuclearace** [comment]
No, I mean does this server work with a JavaScript client? Because I don't think your server is right.

**Comment by LamourBt** [comment]
I am not really sure on that but i did install **node.js** on the server then **socket.io**.

**Comment by nuclearace** [comment]
This is the code I tested sending a message to all clients on a server.

```javascript
io.sockets.on("connection", (socket) => {
    socket.on("message", (msg) => {
        io.emit("message", msg)
    })
}
```

**Comment by LamourBt** [comment]
this code is outside of the  io.on("connection")  or inside.... and also i dont need to call it into my application right

**Comment by nuclearace** [comment]
The important bit is `io.emit("message", msg)` which sends a message to all connected clients

**Comment by nuclearace** [comment]
Which actually seems to the same thing as your `socket.broadcast.emit`. Which I got working fine, so either your event names don't match up, or your client is being released too early because it isn't a property.

**Comment by LamourBt** [comment]
found the problem you were right it was a server problem i should not use `socket.broadcast.emit("chat",{username:socket.username,message:data})` instead i should have used **io.emit() **. Thank you

**Comment by nuclearace** [comment]
I think `socket.broadcast.emit` sends the message to all sockets except `socket`

**Comment by MobileDev418** [comment]
same problem.
On my client.js file is working fine. here is an example.
socket.on('messagehistory', function (messages) {
    console.log(messages);
});
-------------------------------------------------------------------------------------
But on my swift side, I can't get anything.
socket.on("messagehistory") { messages, ack in
    print(messages)
});

I did connect the socket server successfully.
socket.on("connect") { data, ack in
    self.socket.emit("authentication", access_token)
    self.socket.on("authenticated"){ data, ack in
        print("authenticated success")
        self.socket.emit("join", room)
    }
}

socket.on('messagehistory', function (messages) {
    console.log(messages);
});

socket.connect()

Please give me advise.
