### ISSUE TITLE
Basic client crashes when connected with namespace nsp option

### ISSUE THREAD

**Issue by KCastiglione** [socketio/socket.io-client-swift#32]
If nsp option is added, it crashes. This same code works without nsp.

      
      - (void)viewDidLoad {
          [super viewDidLoad];
          // Do any additional setup after loading the view, typically from a nib.
          socket = [[SocketIOClient alloc] initWithSocketURL:@"http://10.0.1.236:4000" options:@{@"nsp":@"/kwik"}];
          
          [socket on: @"connect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {
              NSLog(@"connected");
              [socket emitObjc:@"echo" withItems:@[@"echo test"]];
              [[socket emitWithAckObjc:@"ackack" withItems:@[@"test"]] onAck:0 withCallback:^(      NSArray* data) {
                  NSLog(@"Got data");
              }];
          }];
          [socket on:@"data" callback:^(NSArray* data, void (^ack)(NSArray*)) {
              NSLog(@"data:%@", data);
          }];
          [socket connect];
      }

Here is screenshot of crashlog. 

![screen shot 2015-03-26 at 2 20 24 pm](https://cloud.githubusercontent.com/assets/96905/6857400/cfa5e90a-d3c3-11e4-8715-1e2f8bbcda2e.png)

**Comment by nuclearace** [comment]
Don't add the / to the nsp. Just add "kwik"

**Comment by nuclearace** [comment]
I'll make it so adding it doesn't cause it to crash though

**Comment by KCastiglione** [comment]
Thanks that fixed it.
