### ISSUE TITLE
"The request timed out" when I try connect to my host

### ISSUE THREAD

**Issue by brendomaciel** [socketio/socket.io-client-swift#321]
When I try to connect to my host I get an error that says "The request timed out."

This is my code:

```
class ViewController: UIViewController {
    
    let socket = SocketIOClient(socketURL: NSURL(string:"http://myhost.com:8900")!)

    override func viewDidLoad() {
        super.viewDidLoad()
        
        addHandlers()
        socket.connect()
    }

    func addHandlers() {
        socket.on("connect") {[weak self] data, ack in
            print("Test")
        }
        
        socket.onAny {print("Got event: \($0.event), with items: \($0.items)")}
    }

}
```

My server is running node.js with the example code.

**Comment by nuclearace** [comment]
Have you made sure that your url is the correct url for the socket.io server?

**Comment by brendomaciel** [comment]
Yes I do. Also I tested with the ports 8080 and 8900 (as the example).

**Comment by nuclearace** [comment]
Well, a request timing out is indicative of a connection problem. Either the wrong url or some other connection issue.

**Comment by brendomaciel** [comment]
A detail: I am using the simulator. But in my application, I realize requests to load other data via GET and they work. But when I try to make a connection using the Socket.IO it does not work.

**Comment by nuclearace** [comment]
If your socket.io is on localhost then you'll have to use the IP of your computer, instead of localhost. Otherwise if your socket.io server isn't using https it's likely to fail because of iOS's restrictions on secure connections.

**Comment by brendomaciel** [comment]
My server is using HTTP only. But the flag "App Transport Security Settings -> Allow Arbitrary Load" with value "YES" does not disable these iOS security restrictions. If they are unset, the request is not allowed.

**Comment by nuclearace** [comment]
I'm not sure, this seems like a configuration problem.

**Comment by brendomaciel** [comment]
What are the possible configuration errors?

**Comment by nuclearace** [comment]
Wrong url or port or something inbetween messing it up.

**Comment by brendomaciel** [comment]
Ok, thanks for the support.

**Comment by shirishbankar1** [comment]
What was the solution you found.
