### ISSUE TITLE
How to send message to individual using this socket.io is Swift

### ISSUE THREAD

**Issue by satyamub** [socketio/socket.io-client-swift#322]
Hi All,
I have trying to use to this library to send and receive message.

I am seeing that Library is using below line to end message however its like broadcast, What I am trying to do a is a unicast.

**socket.emit("chatMessage", nickname, message)**

Please suggest!!!

**Comment by nuclearace** [comment]
This would be done server-side. The client can only send messages directly to the server, not to other clients.
