### ISSUE TITLE
Socket stuck in connecting after airplane mode

### ISSUE THREAD

**Issue by AndrewBoryk** [socketio/socket.io-client-swift#323]
I set up socket for my iOS application, and I ran into an issue. When a user goes into airplane mode, let's say for 30 seconds, and then comes out of airplane mode; I try to connect socket, yet it gets stuck in connecting. I try closing the connection and reconnecting, yet it doesn't work. I have to kill the app and try again. Any reason for this?

**Comment by satyamub** [comment]
@AndrewBoryk have you tried to lock and device and check if the user stays online?

**Comment by AndrewBoryk** [comment]
@satyamub I have the connection set to disconnect if user locks screen or goes to home screen.

**Comment by AndrewBoryk** [comment]
Is there a way to stop socket from connecting, disconnect it, and try to connect again?

**Comment by nuclearace** [comment]
You can try just recreating the socket, and connect that one.

**Comment by AndrewBoryk** [comment]
How do you recommend best practice for recreating the socket?

I'm trying to do:

[self.socket disconnect];
self.socket = nil;
[self socketOn];

(socketOn basically sets up the socket, so in essence:

NSDictionary *connectOptions = [[NSDictionary alloc] initWithObjectsAndKeys:@YES, @"forceWebsockets", @5, @"secure", @YES, @"log", connectParams, @"connectParams", nil];
                
self.socket = [[SocketIOClient alloc] initWithSocketURL:url options:connectOptions];

and then [socket connect]

**Comment by AndrewBoryk** [comment]
You can close this issue, I updated to your latest commit and everything is fixed. I was around 2 months behind
