### ISSUE TITLE
absoluteString crash

### ISSUE THREAD

**Issue by sagardesai16** [socketio/socket.io-client-swift#325]
Hi

I have just updated pod to 5.5.0
when i try to connect socket - app crashes

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString absoluteString]: unrecognized selector sent to instance 0x1005f0900'
*** First throw call stack:
(0x182031900 0x18169ff80 0x18203861c 0x1820355b8 0x181f3968c 0x100b9a7a0 0x100b9b6ac 0x100b9b7b4 0x1000b37f4 0x1000b3138 0x182685e14 0x1829d8334 0x18292b100 0x18291b348 0x1829da728 0x100c95bb0 0x100c9b658 0x181fe8bb0 0x181fe6a18 0x181f15680 0x183424088 0x186d8cd90 0x1000e3e5c 0x181ab68b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any help would be appreciated

**Comment by jb522185660** [comment]
how do to solve it，I have the same problem
