### ISSUE TITLE
Sending Images

### ISSUE THREAD

**Issue by LamourBt** [socketio/socket.io-client-swift#327]
I am sending images from client (swift) to server. The operation succeeded however the image take too much time to load back in UI (waiting time was like 1 min or 2 mins). Main idea idea is as soon as send the image it should load into the UI.  

**In the client, the following code is :**
`let sendingImage:UIImage = pickedImage
            let imageData = UIImagePNGRepresentation(sendingImage)
            let base64encoding = imageData?.base64EncodedStringWithOptions(.Encoding64CharacterLineLength)
            socket.emit("images", base64encoding!)`

**To query the image back into my UIImageView**
`socket.on("images") { objects, ack in
    for each in objects{
    let binaryImage = each["binaryImage"] as? String
    let decodedData = NSData(base64EncodedString: binaryImage!, options: NSDataBase64DecodingOptions.IgnoreUnknownCharacters)
    let returnImage  = UIImage(data: decodedData!)
       }
    }`
**In the Server, I have this**
 `socket.on("images",function(data){
       console.log("BinaryImage is processing...");
       io.emit("images",{binaryImage:data});
     });`

**Comment by nuclearace** [comment]
Not sure how this is a library problem

**Comment by LamourBt** [comment]
It's not a library problem but I was hoping to find a better way to do it ...

**Comment by satyamub** [comment]
@LamourBt can you please let me know where have you put this below code

socket.on("images",function(data){ console.log("BinaryImage is processing..."); io.emit("images",{binaryImage:data}); });

**Comment by LamourBt** [comment]
@satyamub yes I had to resize the image from the client side then send it
