### ISSUE TITLE
Socket.io version mismatch

### ISSUE THREAD

**Issue by dani5447** [socketio/socket.io-client-swift#328]
After some work getting my client to connect I've run into an issue with socket version mismatches. We're using a sails js backend which has socket.io version 11, but it seems this library uses version 9. Is there any easy way to update the version to be compatible, or do you have any plans to update? I couldnt see any version information in the library so I'm not sure how difficult it would be.

Here is part of the console output I get when I try to emit a message to the server:

> [{
>     code = "SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ";
>     details = "Sails v0.11.x is not compatible with the socket.io/sails.io.js client SDK version you are using (0.9.0). Please see the v0.11 migration guide on http://sailsjs.org for more information.";
>     message = "Failed to parse incoming socket.io request.";
>     name = "Error (SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ):";
>     stack = "Error (SAILS:HOOK:SOCKETS:PARSE_VIRTUAL_REQ):: Failed to parse incoming socket.io request.

**Comment by nuclearace** [comment]
Socket.io is currently on version 1.4.5 iirc. This library should work with socket.io 1.0+

**Comment by dani5447** [comment]
Alright it may be something with how sails js is doing sockets then that is incompatible. Thanks!

**Comment by zabaat** [comment]
just in case someone hits this in the future
http://stackoverflow.com/questions/32590533/connect-sails-io-with-an-ios-swift-app/42050944#42050944
