### ISSUE TITLE
A lot of warning when using xcode 7.3 to build

### ISSUE THREAD

**Issue by JunfeiW** [socketio/socket.io-client-swift#329]
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:862:50: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:885:62: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:899:60: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1013:91: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1031:86: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketEngine.swift:505:31: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketIOClient.swift:470:45: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:862:50: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:885:62: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:899:60: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1013:91: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1031:86: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketEngine.swift:505:31: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketIOClient.swift:470:45: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:862:50: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:885:62: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:899:60: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1013:91: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1031:86: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketEngine.swift:505:31: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketIOClient.swift:470:45: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:862:50: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:885:62: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:899:60: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1013:91: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/WebSocket.swift:1031:86: warning: 'var' parameters are deprecated and will be removed in Swift 3
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketEngine.swift:505:31: warning: use '#selector' instead of explicitly constructing a 'Selector'
/Users/junfei/Documents/projects/ios/Mango2/Carthage/Checkouts/socket.io-client-swift/Source/SocketIOClient.swift:470:45: warning: use of string literal for Objective-C selectors is deprecated; use '#selector' instead

**Comment by JunfeiW** [comment]
Version 7.3 (7D175)

**Comment by nuclearace** [comment]
I'm about to push a new version

**Comment by nuclearace** [comment]
Should be fixed
