### ISSUE TITLE
How to pass data to emitObjc?

### ISSUE THREAD

**Issue by KCastiglione** [socketio/socket.io-client-swift#33]
what is the right way to emit with data?
emitObjc accepts only an NSArray.

        [socket emitObjc:@"echo" withItems:@[@"echo test"]];

how do i pass a dictionary like this?

    [self.socketIO sendEvent:@"add-user" withData:@{@"username":self.username}];

**Comment by nuclearace** [comment]
Pass everything inside an array. This is how I emulate variadic parameters in objc.

```swift
func test1(a:AnyObject...) {}
func test2(b:[AnyObject]) {}
```
Those two functions are basically the same, but in Swift you can do
```swift
test1(1, "test", ["foo": "bar"], 2.2)
```

Which will be the same as

```swift
test2([1, "test", ["foo", "bar"], 2.2])
```

**Comment by KCastiglione** [comment]
OK Thanks, this worked:


         [socket emitObjc:@"add-user" withItems:@[ @{@"username":@"user1", @"key":@"key1"} ] ];
