### ISSUE TITLE
Can't build fresh install from cocoapods

### ISSUE THREAD

**Issue by eh1255** [socketio/socket.io-client-swift#331]
I installed the latest version of socket.io using cocoapods in a new (completely empty) project, but it does not build. I have an older version that I manually installed in a previous project that I am currently able to use, but it would be great to have the newest version too.

The problem is in line 508 and 509 in SocketEngine.swift

<img width="912" alt="build error" src="https://cloud.githubusercontent.com/assets/17945242/13953746/d5d6ed80-f080-11e5-9d83-0ac9ebf141a8.png">

**Comment by nuclearace** [comment]
You need to Xcode 7.3 for the latest version

**Comment by eh1255** [comment]
I should have noticed that there was an update to Xcode. Thanks for the pointer!
