### ISSUE TITLE
Why always themselves disconnected with the server, and will not be automatic reconnection

### ISSUE THREAD

**Issue by benben-hello** [socketio/socket.io-client-swift#332]
Why always themselves disconnected with the server, and will not be automatic reconnection

**Comment by nuclearace** [comment]
What? Can you explain a bit more

**Comment by sagardesai16** [comment]
Socket connection is closed whenever we try to switch the network, say switching from wifi to 3G.
It tries to reconnect.but unable to reconnect. can you please help

**Comment by nuclearace** [comment]
I haven't looked at it in awhile, but the solution I had for the app I used this on was to check when there was a change from wifi to cell and re-add the socket. Because iirc I couldn't figure out a platform neutral way to handle it

**Comment by benben-hello** [comment]
When I reading the source code, I found that when I call disconnect method the 'reconnects = false', but when I again call the connect method I have not found   the 'reconnects = true',So, I don't know the reason is because of this

**Comment by benben-hello** [comment]
@sagardesai16 Did you solve this problem?
