### ISSUE TITLE
app crashing on the production

### ISSUE THREAD

**Issue by amen160** [socketio/socket.io-client-swift#333]
Hi. After switching to the socket.io-client-swift app began crashing on the production. It never happened during testing but I see crash reports on Fabric. The app is built with swift optimization disabled.
The app is written in Objective-C.
![screen shot 2016-03-25 at 17 17 52](https://cloud.githubusercontent.com/assets/6201829/14042629/4bf8b032-f2ae-11e5-8973-4f8c38ddca04.png)

**Comment by nuclearace** [comment]
Without a reliable way to reproduce even a line number isn't very helpful. It's most likely some sort of race condition.
