### ISSUE TITLE
Sending cookie

### ISSUE THREAD

**Issue by BTopbas** [socketio/socket.io-client-swift#334]
I have auth with cookie in my socket server. Php web service is no problem. But ios application cant auth because i think server cant get cookies. 

I look up readme and docs and i see .Cookie parameter for socket. Now ı am trying this code.

```
let cookieStorage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
let cookies = cookieStorage.cookies
let socket = SocketIOClient(socketURL: NSURL(string: "http://77n.us:3000")!, options: [.Log(true), .ForcePolling(true), .Cookies(cookies)])
```
But i got this error 
Cannot invoke initializer for type 'SocketIOClient' with an argument list of type '(socketURL: NSURL, options: _)'

**Comment by nuclearace** [comment]
It's probably because .Cookies is typed as `.Cookies([NSHTTPCookie])`, but NSHTTPCookieStorage.cookies returns an optional. So you'll have to unwrap that optional

**Comment by BTopbas** [comment]
Tiny example for unwrapping? I add ! to end of cookies. No error but also cant auth. I print cookies debug console so i am sure i have cookies. but failing to add socket.

**Comment by BTopbas** [comment]
Okey. My fault. I forget to implement redis. Everything is working. Thanks for help.

**Comment by msobhanasim** [comment]
Hi @BTopbas ... I am also having a same issue while connecting to the backed server... I followed your comments but I am confuse on your statement "Okey. My fault. I forget to implement redis. Everything is working. Thanks for help." What is "redis" here and can you provide a code you used to solve the issue... I will be grateful... 

Regards
M Sobhan Asim
