### ISSUE TITLE
Where/How can i get status/callback of successfully connected to server ?

### ISSUE THREAD

**Issue by kshrikant** [socketio/socket.io-client-swift#337]
Hello @nuclearace first of all thank you for this library so far its working fine for me. The issue currently I'm facing is 

    `func applicationDidBecomeActive(application: UIApplication)
    {
        SocketIOManager.sharedInstance.establishConnection()
    }`

I would like to know status 

` func establishConnection()
{
    socket.connect()
}
  `
I want to know whether my client is successfully connected to server or not ? 
Where in which file i can get status ? Because once ill get callback of success then only i want to go ahead i.e. my other events like joinChatRoom, sendMessage. Please help me. I also checked

```
public func connect(timeoutAfter timeoutAfter: Int, withTimeoutHandler handler: (() -> Void)?) {
        assert(timeoutAfter >= 0, "Invalid timeout: \(timeoutAfter)")

        guard status != .Connected else {
            DefaultSocketLogger.Logger.log("Tried connecting on an already connected socket",
                type: logType)
            return
        }

        status = .Connecting

        if engine == nil || forceNew {
            addEngine().open()
        } else {
            engine?.open()
        }

        guard timeoutAfter != 0 else { return }

        let time = dispatch_time(DISPATCH_TIME_NOW, Int64(timeoutAfter) * Int64(NSEC_PER_SEC))

        dispatch_after(time, handleQueue) {[weak self] in
            if let this = self where this.status != .Connected {
                this.status = .Closed
                this.engine?.close("Connect timeout")

                handler?()
            }
        }
    }
```

But i didnt find any status.

**Comment by nuclearace** [comment]
You can add an event handler for `connect` that will be fired when the socket connects

**Comment by kshrikant** [comment]
Sorry @nuclearace  i didnt get you can please explain me through code ?

**Comment by aniketc-gslab** [comment]
@kshrikant when you call, say

socket.connect()

to listen to the successful connection establishment to the server you have to add a handler like the following

socket.on("connect") {data, ack in
    print("socket connected")
 }

**Comment by kshrikant** [comment]
Thank you it worked for me.... @nuclearace @aniketc-gslab firstly i was doing the same but it was not coming inside socket.on ("connect"). Now it working fine.

**Comment by alishaker** [comment]
Hello,

Actually the problem is it keeps triggering this function, all i want is to listen when the socket is connected, i don't want to keep triggering it, it has to be triggered one time
