### ISSUE TITLE
打包framework不兼容7.2.1版本xcode

### ISSUE THREAD

**Issue by yinzhaoqing** [socketio/socket.io-client-swift#339]
报错如下：
dyld: Library not loaded: @rpath/libswiftCore.dylib
 Referenced from: /Users/(*****)/Library/Developer/CoreSimulator/Devices/*****/data/Containers/Bundle/Application/*****/My.app/Frameworks/RealmSwift.framework/RealmSwift
 Reason: Incompatible library version: RealmSwift requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0 
在不升级xcode的情况下怎么解决问题呢，因为有多部门协同开发，同时升级xcode不太现实，求解决办法

**Comment by nuclearace** [comment]
Not a library issue
