### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by ripitrust** [socketio/socket.io-client-swift#34]
I am getting a lot of Swift Compiler issue after install the library using cocoapod:

/Users/Chris/Documents/Development/Xcode/SIOSwift/Pods/Socket.IO-Client-Swift/SwiftIO/SocketEngine.swift:29:16: error: 'countElements' has been renamed to count
        return countElements(self)
               ^~~~~~~~~~~~~
               count
Swift.countElements:1:36: note: 'countElements' has been explicitly marked unavailable here
@availability(*, unavailable) func countElements<T : _CollectionType>(x: T) -> T.Index.Distance
                                   ^
/Users/Chris/Documents/Development/Xcode/SIOSwift/Pods/Socket.IO-Client-Swift/SwiftIO/SocketEngine.swift:134:43: error: 'AnyObject' is not convertible to 'String'; did you mean to use 'as!' to force downcast?
                    let valueEsc = (value as String).stringByAddingPercentEncodingWithAllowedCharacters(
                                    ~~~~~~^~~~~~~~~
                                          as!
/Users/Chris/Documents/Development/Xcode/SIOSwift/Pods/Socket.IO-Client-Swift/SwiftIO/SocketEngine.swift:226:23: error: 'countElements' has been renamed to count
            let len = countElements(packet)
                      ^~~~~~~~~~~~~
                      count
Swift.countElements:1:36: note: 'countElements' has been explicitly marked unavailable here
@availability(*, unavailable) func countElements<T : _CollectionType>(x: T) -> T.Index.Distance
                                   ^
/Users/Chris/Documents/Development/Xcode/SIOSwift/Pods/Socket.IO-Client-Swift/SwiftIO/SwiftRegex.swift:141:28: warning: closure parameter prior to parameters with default arguments will not be treated as a trailing closure
    func substituteMatches(substitution: (NSTextCheckingResult, UnsafeMutablePointer<ObjCBool>) -> String,

**Comment by nuclearace** [comment]
The CocoaPods version only does Swift 1.1. If you're using Swift 1.2 you'll need to manually install the [1.2](https://github.com/socketio/socket.io-client-swift/tree/1.2) branch

**Comment by ripitrust** [comment]
After I added the swift1.2 version there are still one error and one warning 

 /Users/Chris/Documents/Development/Xcode/SIOSwift2/SIOSwift2/SwiftIO/SocketPacket.swift:205:21: error: 'NSMutableArray' is not implicitly convertible to '[AnyObject]'; did you mean to use 'as' to explicitly convert?
        self.data = newArr
                    ^
                           as [AnyObject]
/Users/Chris/Documents/Development/Xcode/SIOSwift2/SIOSwift2/SwiftIO/SwiftRegex.swift:141:28: warning: closure parameter prior to parameters with default arguments will not be treated as a trailing closure
    func substituteMatches(substitution: (NSTextCheckingResult, UnsafeMutablePointer<ObjCBool>) -> String,

Not sure if this is caused by my library error ?

thanks
