### ISSUE TITLE
Lock iphone disconnect socket and automatic reconnect

### ISSUE THREAD

**Issue by vandai91** [socketio/socket.io-client-swift#340]
Hi @nuclearace  , i have a question 

my code is objective C 

When I connect socket first time to server , server respond success , after i lock my device then i unlock my device , i dont call function "connect server" any more , but when i see log in xcode , your framework automatic reconnect to my server and show my log , so how do i fix this not auto reconnect to my server.

**Comment by nuclearace** [comment]
Create the socket with `.Reconnects(false)`
