### ISSUE TITLE
Event handler called multiple times - Socket.io swift

### ISSUE THREAD

**Issue by utkarshs07** [socketio/socket.io-client-swift#341]
Hello there

right now i'm working on google webRTC (Conferencing) iOS app and using socket.io as a signaling protocol.

For individual management of signaling between users, i need to create socket per client. 

At first client side i am creating two channels, one is public (for public-ally broadcasted messages) and one is my own private (using my id as a namespace). See - **"initChannel"** and **"createMyChannel"**.

when new user joins room, i get **'newParticipant'** event in public channel, using new user id i create a private channel to send private messages to that particular user's channel which is already created by that client when he/she joined the room. See - **"WRTCSignalingType"** switch case.

everything working fine except when i send message to user's private channel after receiving **'newParticipant'**, at receiver side below handler called several times 

```
[self.myChannel on:@"message" callback:^(NSArray * data, SocketAckEmitter * ack) {
        NSLog(@"Data >>> %@", data);
    }];
```

i don't get it why is this happening ... is message emitting multiple times or something else or is this library's bug.

please help... it's just driving me crazy.

```
@interface WRTCMultiPeerConnection ()

@property (strong, nonatomic) SocketIOClient *channel;
@property (strong, nonatomic) SocketIOClient *myChannel;

@property (copy, nonatomic) NSString *room;
@property (copy, nonatomic) NSString *participant;
@property (copy, nonatomic) NSURL    *socketUri;

@property (nonatomic, strong) NSArray *iceServers;

@property (nonatomic, strong) NSDictionary *connectionOptions;

@property (nonatomic, strong) NSMutableDictionary *peerToConnectionMap;
@property (nonatomic, strong) NSMutableDictionary *offerChannels;

@end

@implementation WRTCMultiPeerConnection

- (instancetype)initConferenceCallWithRoom:(NSString *)room nickname:(NSString *)nickname delegate:(id <WRTCMultiPeerConnectionDelegate>)delegate options:(WRTCMediaConfiguration *)options {

    self = [super init];
    if (self) {
        
        self.delegate       = delegate;
        self.room           = room;
        self.socketUri      = [[NSURL alloc] initWithString:kSocketUrl];
        self.participant    = nickname;
        self.connectionOptions = @{@"log" : @YES};
        
        self.peerToConnectionMap = [NSMutableDictionary new];
        self.offerChannels       = [NSMutableDictionary new];

        [self initChannel];
        [self createMyChannel];
    }
    
    return self;
}


#pragma mark - Socket.io

- (void)createMyChannel {
    
    self.myChannel = [[SocketIOClient alloc] initWithSocketURL:self.socketUri options:@{@"log" : @NO, @"nsp" : [NSString stringWithFormat:@"/%@", self.participant]}];
    
    [self.myChannel on:@"connect" callback:^(NSArray * data, SocketAckEmitter * ack) {
        NSLog(@"Private channel connected.");
    }];
    
    [self.myChannel on:@"message" callback:^(NSArray * data, SocketAckEmitter * ack) {
        NSLog(@"Data >>> %@", data);
    }];
    
    [self.myChannel connect];
}

- (void)initChannel {
    
    self.channel = [[SocketIOClient alloc] initWithSocketURL:self.socketUri options:self.connectionOptions];
    
    [self.channel on:@"connect" callback:^(NSArray * data, SocketAckEmitter * ack) {
        NSDictionary *packet = @{kRoom : self.room,kFrom : self.participant};
        [self.channel emit:@"create_join" withItems:@[packet]];
    }];
    
    [self.channel on:@"room.created" callback:^(NSArray * data, SocketAckEmitter * ack) {
        
    }];
    
    [self.channel on:@"room.join" callback:^(NSArray * data, SocketAckEmitter * ack) {
        //NSLog(@"User send request to join room");
    }];
    
    [self.channel on:@"room.joined" callback:^(NSArray * data, SocketAckEmitter * ack) {
        
        //NSLog(@"Room Joined");
        
        if (data.count) {
            
            NSDictionary *message = [data firstObject];
            
            if (message && [message[kFrom] isEqualToString:self.participant]) {
                NSDictionary *packet = @{kType : kEventTypeNewParticipant, kFrom : self.participant};
                [self.channel emit:@"message" withItems:@[packet]];
            }
        }
    }];
    
    [self.channel on:@"message" callback:^(NSArray * data, SocketAckEmitter * ack) {
        
        NSLog(@"\n\nMessage recieved in Public channel >> %@ Data >> %@", self.participant, data);
        
        if (data.count) {
            
            NSDictionary *message = [data firstObject];
            
            if (message) {
                
                WRTCSignalingType signalType = [self signalTypeStringToEnum:message[kType]];
                
                switch (signalType) {
                        
                    case WRTCSignalingTypeNewParticipant:
                    {
                        NSString *otherUserId = message[kFrom];
                        
                        if (![self.offerChannels hasValueForKey:otherUserId]) {
                            
                            //NSLog(@"\n\nRecieved New Participant from >>> %@", otherUserId);
                            
                            self.offerChannels[otherUserId] = [[SocketIOClient alloc] initWithSocketURL:self.socketUri options:@{@"log" : @YES, @"nsp" : [NSString stringWithFormat:@"/%@", otherUserId]}];
                            
                            [self.offerChannels[otherUserId] on:@"connect" callback:^(NSArray * data, SocketAckEmitter * ack) {
                                NSLog(@"\n\nPrivate channel connected for user %@", otherUserId);
                                
                                //NSLog(@"\n\nTotal offer channels %@", self.offerChannels);
                                
                                NSDictionary *packet = @{kType : @"offer", kFrom : self.participant, @"sdp" : @"Test Connect"};
                                [self.offerChannels[otherUserId] emit:@"message" withItems:@[packet]];
                            }];

                            [self.offerChannels[otherUserId] connect];
                        }
                    }
                        break;
                    default:
                        break;
                }
            }
        }
    }];
    
    [self.channel connect];
}
```

**Comment by nuclearace** [comment]
The only reason the event handler would be called more than once is because the server sent the message more than once. So check your server code, because it's probably not set up correctly

**Comment by utkarshs07** [comment]
Hey thanks for quick reply :) found the bug. 

Actually the problem was - I was connecting with the server using same namespace again & again but wasn't disconnecting properly before creating a new connection so event handlers were still there. Now i am generating random string for each connection, it's working fine now.

**Comment by utkarshs07** [comment]
I'm facing one more problem, I'd be glad if you advise me..

As i mentioned above that I'm working on webRTC and signaling using socket.io.

Case is there're multiple participants in a room and i need to communicate with them privately so i'm creating n-1 private connections using namespace feature.

As you can see in above code.. when i get **WRTCSignalingTypeNewParticipant** event, It means new participant joined the room, so in this event i'm getting that user's id and using that id i'm creating a private socket of that user and storing into NSMutableDictionary for further use.

After successful call/answer signaling a delegate method gets fired and at this stage i need to share some network information with user using that user's private socket which i've previously created, connected and stored in Dictionary.

so when i fetch that socket connection from Dictionary and emit network info into that connection sometimes not received by other client or sometimes works.

i'm also checking status of connections it's showing disconnected ..

i am little confused here. what should i do in this case?

i think it's some kinda reconnect issue ...

or is it because of i'm doing something wrong in my code ? is process of storing in Dictionary and fetching doing something wrong?

**Comment by nuclearace** [comment]
It could be, I've never tried storing sockets in a dictionary. But I wouldn't think it would cause a problem.

**Comment by nuclearace** [comment]
Did you ever resolve this>

**Comment by AhtashamImtiyaz** [comment]
Hey @utkarshs07, How did you solve this problem? Did you generated the random string in the server side or client side?

**Comment by muh-azharudheen** [comment]
@utkarshs07 , how did you solve this problem. any workaround with this.

**Comment by ankitsainisoftobiz** [comment]
The problem is that your socket is still listening to events even after your disconnected it.
you can solve this by calling socket.off("event_name") for all added events when you disconnect from the socket.

**Comment by ShaikBaji1911** [comment]
how to send offer sdp
