### ISSUE TITLE
SocketEngine.swift #selector error

### ISSUE THREAD

**Issue by Ezechiele** [socketio/socket.io-client-swift#342]
Hello everyone, when i import socket.io.client-swift to my project, either manually or via cocoapods, when i try to compile (without writing any code) xCode gives me 3 errors in this line of code:

```
                self.pingTimer = NSTimer.scheduledTimerWithTimeInterval(pingInterval, target: self,
                    selector: #selector(SocketEngine.sendPing), userInfo: nil, repeats: true)
```

1)Expected expression in list of expressions
2)Expected ',' seprarator
3)Missing argument for parameter 'selector' in call

I think they're all related to the same problem but i cannot figure it out by my self the solution :(

**Comment by nuclearace** [comment]
Are you on Xcode 7.3?

**Comment by Ezechiele** [comment]
No i'm on 7.2.1, my fault sorry i thought i had updated xCode
