### ISSUE TITLE
can't send emit to server, but already connected (obj-c)

### ISSUE THREAD

**Issue by myusuf08** [socketio/socket.io-client-swift#346]
any body know about send this? help please ..

no log call back from server ..

**Comment by nuclearace** [comment]
This is too vague. Can you give more information?

**Comment by myusuf08** [comment]
test

**Comment by myusuf08** [comment]
first, i already connect socket with this code

NSURL* url = [[NSURL alloc] initWithString:@"mylink"];
    SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:url options:@{@"log": @YES, @"forcePolling": @YES}];
[socket connect];

second: i send emit with json object and set json object as dictionary

 NSMutableDictionary *params ..
[socket emit:@"checkMe" withItems:[NSArray arrayWithObject:params]];


and only this i got in my log

 LOG SocketEnginePolling: POSTing
LOG SocketEnginePolling: Doing polling request
LOG SocketEngine: Writing poll:  has data: 0
 LOG SocketEnginePolling: Sending poll:  as type: 2
Created POST string: 1:2


there is no log from server, but i already send emit

please help :(

**Comment by myusuf08** [comment]
NSString *socketID = [[NSUserDefaults standardUserDefaults]objectForKey:@"socketID"];
    [socket on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
        NSMutableDictionary *params = [[NSMutableDictionary alloc]initWithDictionary:@{@"sid":socketID}];
        //
        NSDictionary * auth = @{@"isAuthenticated":checkisAuthenticated,@"credentials":@{@"uid":checkcredentialsuid,@"id":checkcredentialsid,@"exp":checkcredentialsexp,@"valid":checkcredentialsvalid,@"iat":checkcredentialsiat}};
        //
        NSDictionary * info = @{@"lastseen":wholastseen,@"username":whousername,@"status":whostatus,@"email":whoemail,@"createdAt":whocreatedAt,@"cellphone":whocellphone,@"active":whoactive,@"profile":@{@"middleName":whoprofilemiddleName,@"lastName":whoprofilelastName,@"birthday":whoprofilebirthday,@"sex":whoprofilesex,@"cover":whoprofilecover,@"status":@{@"message":whoprofilestatusmessage,@"postedAt":whoprofilestatuspostedAt},@"pictureResId":whoprofilepictureResId,@"rel":whoprofilerel,@"firstName":whoprofilefirstName,@"avatar":@{@"stockId":whoprofileavatarstockId,@"avatarId":whoprofileavataravatarId}}};
        //
        [params setObject:auth forKey:@"auth"];
        [params setObject:info forKey:@"info"];
        [socket emit:@"checkMe" withItems:[NSArray arrayWithObject:params]];
        NSLog(@"socket connected ");
        
    }];

**Comment by nuclearace** [comment]
Are you sure the socket is a property and not a local variable?

**Comment by myusuf08** [comment]
im using local variable in my func, and i call my func in viewdidload, so i
must set global varial that socket? Like this?
@property(strong.nonatomic)socket *socket ??

**Comment by myusuf08** [comment]
still not get anything from server after send emit , i already set property..

my friend succes implement this in android, and him tes send with my data json object and work(get notif from server after send emit)

maybe i fail send emit?

btw,in my log emit send 4 time , is this right?

first, LOG SocketIOClient: Emitting: 2
sec,LOG SocketEngine: Writing poll: 2
thr,LOG SocketEnginePolling: Sending poll: 2
four,LOG SocketEnginePolling: Created POST string: 809:42

help please

**Comment by nuclearace** [comment]
Those log messages don't really help. Are you sure you're sending the data correctly? It could be you're not understanding the api correctly.

And yes, the socket has to be a property, otherwise it'll be released when it goes out of scope

**Comment by myusuf08** [comment]
yes im sure, my json data is correct , because i already test in android using socketio too,

maybe u hv more example code to send emit in obj-c ?

how can i know , emit has already send?and how to know log from server when emit sucess send?

**Comment by nuclearace** [comment]
There's objective-c on the README. The only way to know the server got a message is if you do emitWithAck, and if the server knows it should send an ack back

**Comment by myusuf08** [comment]
i using this,
[self.socket emitWithAck:@"checkMe" withItems:[NSArray arrayWithObject:params]];
        [ack with:[NSArray arrayWithObject:params]];

but emit not sending,

i just need to listen in this :

[self.socket on: @"checkMe|response"  callback:^(NSArray * item, SocketAckEmitter * emitt) {
        NSLog(@"checkme successfull %@",item);
    }];

but no respon :(

**Comment by nuclearace** [comment]
Oh, you're using emitWithAck, which is probably not what you want.

```objective-c
[socket emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
    [socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
});
```

emitWithAck returns a closure which takes a timeout and a callback. You have to call that callback before the emit will send. Also note that just because you're using emitWithAck, the server doesn't have to ack it, the server has to be coded to send back an ack.

**Comment by oikios** [comment]
i also meet this question. my android colleague did success. but i did always wrong. it's the same to you.  how did you solve this eventually？ help.
