### ISSUE TITLE
Issue with SocketURL 

### ISSUE THREAD

**Issue by NidhiJoshi7** [socketio/socket.io-client-swift#347]
Hi, I am doing socket for first time. so may be it's not issue from ur end.. or it can be.. Can you please guide me for this issue... I am using below code for socket... but it showing me this error :  Cannot invoke initializer for type 'SocketIOClient' with an argument list of type '(socketURL: String, options: [String : Dictionary<String, String>])'

var mysocket : SocketIOClient = SocketIOClient(socketURL: "http://198.211.104.210:5000", options: ["connectParams": ["token": "1"]])

Can you please tell me what to do with this?

**Comment by nuclearace** [comment]
```swift
let mySocket = SocketIOClient(socketURL: NSURL(string: "http://localhost:8080")!, options: [.ConnectParams(["token": "1"])])
````
