### ISSUE TITLE
how to use SSLSecurity?

### ISSUE THREAD

**Issue by CheerCc** [socketio/socket.io-client-swift#348]
hey,now i want to use your framework in my Objc-C project,i use SocketIOClient class to communicate,but now i need to use certificates when i am communicating to server,i really do not know how to use certificates with SocketIOClient.If you have free time,please help me to solve this problem,3Q

**Comment by nuclearace** [comment]
What do you mean? Shouldn't iOS handle certs

**Comment by nuclearace** [comment]
The only time I think you'd have to worry is if you're using a self-signed cert, or your cert doesn't meet Apple's requirements.

**Comment by CheerCc** [comment]
during i communicate to server,i want to use  authentication certificates to encrypt my data(by SSLSecurity),but i only find this certificates property in WebSocket.swift,but now i just use SocketIOClient to communicate,so i do not know how to use the certificates property in the SocketIOClient class

**Comment by nuclearace** [comment]
Oh I think I see, `ws` isn't public. 

I guess you can do:

```swift
(client.engine as? SocketEngine)?.ws?.security = SSLSecurity(usePublicKeys: true)
```

Until I expose ws on SocketEngineSpec

**Comment by CheerCc** [comment]
sorry,can you tell me how to use in Obj-C, just know Swift a little,3Q very much.
in Obj-C like this ? 
`socket.engine.ws.security`

**Comment by nuclearace** [comment]
Well you'll have to cast socket.engine to SocketEngine

**Comment by nuclearace** [comment]
I don't know Objective-C well enough to show you how

**Comment by CheerCc** [comment]
OK,Thank you anyway,i try it

**Comment by rajeevwhiz** [comment]
@CheerCc Can you share how you resolve this? Why did you do to pin the certificate? I am trying to pin a self-sign certificate and running into similar issue.

**Comment by CheerCc** [comment]
@rajeevwhiz
Hi, I think you can't use a self-sign certificate, because Apple don't allow this operation.If you want to try by a self-sign certificate, I suggest you can add this parameter "selfSigned" to config. I had used authentication certificates to connect test our server, whatever I do, also failed. In fact, I just connect the server domain, and the domain name is same with our authentication certificates.And connect success.I think, you can communicate with server staff, tell him to allow Apple's requirements.
