### ISSUE TITLE
Swift Compiler error 

### ISSUE THREAD

**Issue by ripitrust** [socketio/socket.io-client-swift#35]
After I added the swift1.2 version there are still one error and one warning

/Users/Chris/Documents/Development/Xcode/SIOSwift2/SIOSwift2/SwiftIO/SocketPacket.swift:205:21: error: 'NSMutableArray' is not implicitly convertible to '[AnyObject]'; did you mean to use 'as' to explicitly convert?
self.data = newArr
^
as [AnyObject]
/Users/Chris/Documents/Development/Xcode/SIOSwift2/SIOSwift2/SwiftIO/SwiftRegex.swift:141:28: warning: closure parameter prior to parameters with default arguments will not be treated as a trailing closure
func substituteMatches(substitution: (NSTextCheckingResult, UnsafeMutablePointer) -> String,

Not sure if this is caused by my library error ?

**Comment by nuclearace** [comment]
That should've been fixed in 1.2 https://github.com/socketio/socket.io-client-swift/blob/1.2/SwiftIO/SocketPacket.swift#L207

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/commit/d308111a8fd4529bf3971632322acf2da56dff20

**Comment by ripitrust** [comment]
yeah 
this is correct 

thanks
