### ISSUE TITLE
EmitWithAct not working with completion handler 

### ISSUE THREAD

**Issue by NidhiJoshi7** [socketio/socket.io-client-swift#350]
I am using this Code to send message to server and get response in data.. I am not able to fetch data from response. Please help me to solve this response. 

socket.emitWithAck("contactSync", dict) (timeoutAfter: 0) { data in               

 print("Data ------- ")
                print(data)
                
            }

Thanks in advance.

**Comment by nuclearace** [comment]
Are you sure that the server API is supposed to ack? emitWithAck will only get an ack if the server sends one.

**Comment by nuclearace** [comment]
Anything more on this?
