### ISSUE TITLE
Website still points to old 3rd party project

### ISSUE THREAD

**Issue by JosephDuffy** [socketio/socket.io-client-swift#351]
I couldn't find a comments section to post this, so I thought I'd post it here.

On the [Socket.IO FAQ](http://socket.io/docs/faq/) the iOS lbriary points to [SIOSocket](https://github.com/MegaBits/SIOSocket). This project does then mention that there's the official project, but it might be best to update the website to point directly to the official client?

**Comment by nuclearace** [comment]
@rauchg This is something for you I think.

**Comment by nuclearace** [comment]
I can't do anything about this. It's up to @rauchg to change that link.
