### ISSUE TITLE
How do I know if socket connection dropped

### ISSUE THREAD

**Issue by petrorington** [socketio/socket.io-client-swift#353]
When the app is in foreground mode on iOS, socket connection is working great.
After the app goes background and goes foreground again, I see the socket connection is dropped and it automatically tries to reconnect.
How can I recognize that the socket connection is dropped with handlers?
I tried with onAny with Obj-C, but I just see the logs, "reconnect", "reconnectAttempt" and "connect".
I want to know when it's dropped.

**Comment by petrorington** [comment]
@nuclearace Do you know how to check if socket connection is valid or not?

**Comment by nuclearace** [comment]
You can add handlers for `connect`, `disconnect`, `reconnect` and `reconnectAttempt` if you want to know different statuses.

**Comment by petrorington** [comment]
@nuclearace Yes, I'm familiar with those handlers.
But the problem is that they are not called when the app is in background.
So I couldn't catch when the connection is dropped.
When the app goes foreground again, I see the socket connection status is still valid.
I'm checking status property (SocketIOClientStatus) and it's Connected though.

**Comment by nuclearace** [comment]
Right, because iOS doesn't allow background execution but under certain cases.

**Comment by mbalex99** [comment]
I'm wondering why disconnect never gets fired. When I go to airplane mode `reconnect` and `reconnectAttempt` gets fired but `disconnect` doesn't get fired.

**Comment by hahaGitHub** [comment]
@mbalex99 
1.After the app goes background and goes foreground again，what do you do ,so it can automatically tries to reconnect.
2. I can not see the logs, "reconnect", "reconnectAttempt" and "connect".when i close the wifi ,i just see the log,"error".

**Comment by mbalex99** [comment]
@hahaGitHub I don't do anything, it's automatically attempting to connect.

**Comment by hahaGitHub** [comment]
thanks.
i use the latest version.when i change the wifi,it's automatically attempting to connect.
when goes background and goes foreground again,it can not automatically to connect.

**Comment by rodericj** [comment]
I've had a similar issue to what @petrorington described above. My current assumption is that the connected state is stored in a file or something and the file only gets removed on explicit disconnect. 

Our workaround would be to explicitly disconnect the socket so that we as a client have a bit more of a deterministic experience with the library, though the viability of this for our specific needs is unknown.

**Comment by nuclearace** [comment]
@rodericj explicit disconnection is probably the safest way to do things.

**Comment by HenryHengZJ** [comment]
any updates on this? Is explicit disconnection the only way?
