### ISSUE TITLE
Why i can not connect to sever by SocketIOClient?

### ISSUE THREAD

**Issue by CheerCc** [socketio/socket.io-client-swift#354]
hi,  I am using the lib with Objective-C.
I have make the socket as a strong property of  class.

`@property(nonatomic, strong) SocketIOClient *socketIO;`

In my project there are two severs, one is the local sever,the other is cloud sever. Now the pi(a hardware to control my curtain or window in my company) in my local sever is WebSocket, the cloud is socket.io.
When i connect to cloud server,it's ok.I connect to my local sever(use WebSocket),i use the class of WebSocket,it's ok,but i use the SocketIOClient, the method of `on:@"connect"` never been called.
i use SocketIOClient like this.
`self.socketIO = [[SocketIOClient alloc] initWithSocketURL:[[NSURL alloc] initWithString:url] options:@{@"log": @YES,@"forcePolling": @YES, @"forceWebsockets" : @YES}];`

the local can't send any message for my project.If you have free time,please help me to solve this problem.Thanks

**Comment by nuclearace** [comment]
When you say your local server is WebSocket, does that mean it's a plain WebSocket server? Because if that's so, you'll have to use the WebSocket class for it. SocketIOClient is only for socket.io servers.

**Comment by CheerCc** [comment]
Thanks for your reply.Yes, my local sever is WebSocket.So whether the SocketIOClient can't take it compatible with WebSocket,even if i add the `@"forceWebsockets" : @YES` in the `init` method?
 When i use the framework of SIOSOCKET, no matter local and cloud,both of them is OK.i don't know the  difference between yours and  SIOSOCKET.

**Comment by nuclearace** [comment]
Socket.io is a technology that's built on polling/WebSocket. It has its own protocol for sending messages, so a basic WebSocket server isn't going to follow that protocol. This library is meant for interfacing with socket.io servers, not plain WebSocket servers. You can use Starscream (what this library uses for WebSocket) if you want to connect to a plain WebSocket server.

**Comment by CheerCc** [comment]
OK.Thanks for your suggestion.I will try it.
