### ISSUE TITLE
SocketParser.swift won't compile on Xcode 7.3 

### ISSUE THREAD

**Issue by orensha** [socketio/socket.io-client-swift#357]
downloaded the latest socket.io but i'm getting 29 errors on SocketParser.swift.
using Xcode 7.3.

**Comment by nuclearace** [comment]
What version are you using?

**Comment by nuclearace** [comment]
Because that file doesn't exist anymore.

**Comment by orensha** [comment]
had a mix of the older version. thanks.

**Comment by orensha** [comment]
but i got another problem now. what replaces the 'connected' variable in 'SocketIOClient' ?

**Comment by nuclearace** [comment]
The status property

**Comment by orensha** [comment]
yes but how does it work? what do i compare it with>

**Comment by nuclearace** [comment]
You compare it with https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClientStatus.swift#L28

**Comment by nuclearace** [comment]
`socket.status == .Connected`

**Comment by orensha** [comment]
I'v tried it, but i think my problem is that my project doesn't recognize the new swift files. thanks ill check it out.

**Comment by orensha** [comment]
ok found the problem with this line. because im writing in objective c i cant use the swift syntax and use "_socketIOClient.status == .Connected", instead there is the objective c translation of the enum: "_socketIOClient.status == SocketIOClientStatusConnected".

**Comment by orensha** [comment]
now using the new sdk. im trying to connect but get this logs:

 LOG SocketIOClient: Adding handler for event: connect
 LOG SocketIOClient: Adding handler for event: update
 LOG SocketIOClient: Client is being released

why client being released?

**Comment by nuclearace** [comment]
I should add a FAQ somewhere. I'm almost certain it's because you're forgetting about ARC. The socket needs to be a property of a class, local variables won't work since they'll be released as soon as the socket goes out of scope.

**Comment by orensha** [comment]
thanks man. forgot to set it as a property of the class. cheers.
