### ISSUE TITLE
Weird issue while emitting and receiving data from socket swift to socket js.

### ISSUE THREAD

**Issue by gamugamu** [socketio/socket.io-client-swift#359]
I have already implemented several time socket-io with no issue. But this time I have encountered two problem:

I have a socket iOS client, and a socket js client both relying on a python server (flask socket-io).

I can receive data from the js client to the iOS client, but the inverse is not working (iOS to js)

 when I send my message from js to iOS, the message field is suffixed with Emit:
For example if my js-client is emmiting:
` socket.emit('chatService', 'some message');
`
In my iOS code, I must write [socket on:] with the field "chatServiceEmit" (Note I must add the 'Emit' suffix). Like this:
```
// chatService field is not okay, must write as chatServiceEmit in order to make it work.
    [_socket on: @"chatServiceEmit"
      callback: ^(NSArray* data, SocketAckEmitter* ack) {
          NSLog(@"receipt: %@", data);
    }];
```

But I think I can live with it,  my big problem here is that all my messages I emit from my iOS client are not received by my js Client. But from my python shell, I see that the POST are emitted by my iOS client, so the pipe is working. I think my message field are transformed again. But I have no way to get the right key. I have tried to suffix it like in iOS client, but with no luck.
For example:
```
// obj-c client code
    [_socket emit: @"test"
        withItems: @[@"data battleship from ios"]];
```

This one is never received:
	```
// js client code
socket.on('test', function(message) {
			console.log('------ receipt service' + message);
		});
```

Do you have any idea?
For info, I use in js: 1.4.5 / 2016-01-26

And from iOS, I had to perform a manual installation because I couldn't install it via pod or other dependency manager. I used the git code, compiled and installed it as a swift dependancy  like you suggested (from github: -hash version 9b566fd).
If that can help you, I think the problem come from the swift socket version. Because I have already tried with a pod version and it worked like a charm. I'm using https connection too, but I don't think this is an issue here.

**Comment by gamugamu** [comment]
Please @nuclearace, this is not urgent. I have found for the moment a workaround passing my data from iOS to my python socket server, and then resending it to my js client. Using my socket python server as a bridge fixed the issue.

Since it is involving flask socket-io, which you didn't code, iOS and js client side, and specific version of each code. Finding the bug could be really a mess there. The fact that my pi server can receive my iOS message, I'm actually into the idea that the bug could be inside flask-socketio. Anyway, the bridge workaround is maybe the right way to perform this in my specific case. Thank you anyway for your nice library.

**Comment by mjracca** [comment]
I have almost the same issue, and to fix this is urgent.

It seams like when sending an event with simple NSStrings it work's fine, but when I send a json string then the other platform doesn't receive the event.

Any way of fixing this?

**Comment by gamugamu** [comment]
I don't think the problem is related with this issue. But since a json is just a string with a specifique format,  it may be the way you encode it, or its size. Did you try a simple test, sending a nsstring like: @"{\'key\':\'value\'}".
Since this is a socket communication, it won't surprise me if it is about the json size.

**Comment by nuclearace** [comment]
Sending a JSON string like `socket.emit("jsonStringTest", "{\"myEvent\":\"Cute Without the \\\"E\\\" (Cut From the Team)\"}")` works fine for me.

**Comment by nuclearace** [comment]
You ofc have to call `JSON.parse` in the server to convert it though.

**Comment by nuclearace** [comment]
@gamugamu I don't think this is a problem with this client, because it would happen on node.js servers as well. And emitting is a fairly straightforward task that has tests to verify the correct strings are being created https://github.com/socketio/socket.io-client-swift/blob/master/SocketIO-MacTests/SocketBasicPacketTest.swift. I've had problems reported with the flask-socket.io implementations before.
