### ISSUE TITLE
Client connecting multiple times  when proxied through nginx

### ISSUE THREAD

**Issue by KCastiglione** [socketio/socket.io-client-swift#36]
Sometimes it connects more than 3 times. If I connect directly to the socket.io it connects only once.

multiple connects:

        10.0.1.236 - - [27/Mar/2015:10:27:03 -0700] "GET /socket.io/?transport=polling&b64=1         HTTP/1.1" 200 100 "-" "socket/1 CFNetwork/711.2.23 Darwin/14.0.0"
        10.0.1.236 - - [27/Mar/2015:10:27:03 -0700] "GET /socket.io/?transport=polling&sid=vb1yUHmUr59l6el6AAAP HTTP/1.1" 200 4 "-" "socket/1         CFNetwork/711.2.23 Darwin/14.0.0"
        10.0.1.236 - - [27/Mar/2015:10:27:03 -0700] "POST /socket.io/?transport=polling&sid=vb1yUHmUr59l6el6AAAP HTTP/1.1" 400 45 "-" "socket/1         CFNetwork/711.2.23 Darwin/14.0.0"
        

Objective-C client code:

      - (void)viewDidLoad {
          [super viewDidLoad];
          // Do any additional setup after loading the view, typically from a nib.
          socket = [[SocketIOClient alloc] initWithSocketURL:@"http://socket.xxx.com"       options:@{@"nsp":@"kwik"}];
          
          [socket on: @"connect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {
              NSLog(@"connected");
          
              [socket emitObjc:@"add-user" withItems:@[ @{@"username":@"username"} ] ];
          }];
          [socket on:@"data" callback:^(NSArray* data, void (^ack)(NSArray*)) {
              NSLog(@"data:%@", data);
          }];
          [socket connect];
      }

nginx config:

    server {
        listen       80;
        server_name socket.xxx.com;
        location /socket.io {
            proxy_pass http://localhost:5000/socket.io;
            proxy_redirect off;
            proxy_buffering off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }

**Comment by nuclearace** [comment]
I have no idea how to set up nginx, can you provide a server that does this? Also, does this work with the javascript client correctly?

**Comment by KCastiglione** [comment]
sure, i can. is there a way to send a private message to you?

**Comment by KCastiglione** [comment]
yes it works with javascript and also works with https://github.com/pkyeck/socket.IO-objc correctly

**Comment by nuclearace** [comment]
just email me at nuclear.ace@gmail.com

**Comment by KCastiglione** [comment]
sent.

**Comment by nuclearace** [comment]
Seems to be some kind of race condition with polling

**Comment by nuclearace** [comment]
Workaround - have it force WebSockets

```swift
let socket = SocketIOClient(socketURL: "localhost:8080", options: [ "forceWebsockets": true])
```

**Comment by nuclearace** [comment]
Actually it looks like nginx is doing some kind of caching?

**Comment by KCastiglione** [comment]
i have turned off the proxy buffering off

if i connect using  https://github.com/pkyeck/socket.IO-objc
it works fine without any race condition and connects only once.

nginx config

        location /socket.io {
            proxy_pass http://colo4.thesocialsoft.com:5000/socket.io;
            proxy_redirect off;
            proxy_buffering off;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }

**Comment by nuclearace** [comment]
I'll try to fix it tomorrow. Basically it's trying to poll constantly and getting a reply each time.

**Comment by KCastiglione** [comment]
OK great. thanks.


it is a really basic setup.
here is the complete nginx server config, just proxies to socket.io running on port 5000 in localhost. if you want to try from your local machine anytime.

        worker_processes  auto;
        
        events {
            worker_connections  1024;
        }
        
        http {
            server {
                listen       80;
                location /socket.io {
                    proxy_pass http://localhost:5000/socket.io;
                    proxy_redirect off;
                    proxy_buffering off;
        
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "Upgrade";
                }
            }
        }

**Comment by nuclearace** [comment]
It is a cache problem.

**Comment by KCastiglione** [comment]
thanks for the patch, it seems to be better, connections come to node instance only once.

But nginx still gets multiple requests. Is this OK? 




       ==> node.log <==
       Sat Mar 28 2015 16:14:00 GMT-0700 (PDT): connected        CDdF50Bmvmqb3kxBAAL1
       Sat Mar 28 2015 16:14:00 GMT-0700 (PDT): added tEPn 1 clients now        connected
       
       ==> /opt/local/logs/access_kwik.log <==
       10.0.1.22 - - [28/Mar/2015:16:13:59 -0700] "GET /socket.       io/?transport=polling&b64=1 HTTP/1.1" 200 100 "-" "kwik/1        CFNetwork/711.2.23 Darwin/14.0.0"
       10.0.1.22 - - [28/Mar/2015:16:14:00 -0700] "GET /socket.       io/?transport=polling&sid=CDdF50Bmvmqb3kxBAAL1&b64=1 HTTP/1.1" 200 4        "-" "kwik/1 CFNetwork/711.2.23 Darwin/14.0.0"
       10.0.1.22 - - [28/Mar/2015:16:14:00 -0700] "POST /socket.       io/?transport=polling&sid=CDdF50Bmvmqb3kxBAAL1 HTTP/1.1" 200 2 "-"        "kwik/1 CFNetwork/711.2.23 Darwin/14.0.0"
       10.0.1.22 - - [28/Mar/2015:16:14:00 -0700] "GET /socket.       io/?transport=polling&sid=CDdF50Bmvmqb3kxBAAL1&b64=1 HTTP/1.1" 200        15 "-" "kwik/1 CFNetwork/711.2.23 Darwin/14.0.0"
       10.0.1.22 - - [28/Mar/2015:16:14:00 -0700] "POST /socket.       io/?transport=polling&sid=CDdF50Bmvmqb3kxBAAL1 HTTP/1.1" 200 2 "-"        "kwik/1 CFNetwork/711.2.23 Darwin/14.0.0"

**Comment by oreace** [comment]
> i have turned off the proxy buffering off
> 
> if i connect using https://github.com/pkyeck/socket.IO-objc
> it works fine without any race condition and connects only once.
> 
> nginx config
> 
> ```
>     location /socket.io {
>         proxy_pass http://XXXX:5000/socket.io;
>         proxy_redirect off;
>         proxy_buffering off;
> 
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "Upgrade";
>     }
> ```

THANK YOU SO MUCH
