### ISSUE TITLE
Why socket event “new message” calling multiple times ?

### ISSUE THREAD

**Issue by kshrikant** [socketio/socket.io-client-swift#360]
@nuclearace 

I'm working on socket first time. I'm getting message from server on event

 ` socket.on("new message")`

Here are the steps which I'm doing 

**Step 1:**

    socket.connect()

On successful connection I'm joining group using

**Step 2:**

     socket.emit("joinRoom",groupId,userId,message)

and then using 

**Step 3:**

    socket.emit("send message", groupId,userId,mobileNo,type,message)

Now once I'm done with sending message the server is broadcasting the same message that is m calling from

	 override func viewDidAppear(animated: Bool)
		{
			super.viewDidAppear(animated)
			SocketIOManager.sharedInstance.getChatMessage
				{ (messageInfo) -> Void in
				dispatch_async(dispatch_get_main_queue(), { () -> Void in
				
	
				})
			}

		}

And here is method of socket `getChatMessage` which is calling multiple times once I'm done with sending message.

        func getChatMessage(completionHandler: (messageInfo: [String: AnyObject]) -> Void) 
		{

			socket.on("new message")
			{
			(dataArray, socketAck) -> Void in
			
			
				var messageDictionary = [String: AnyObject]()
			
			
				let temp = dataArray[0]
		  
				
			   completionHandler(messageInfo: messageDictionary)
			}

    	}

I am not getting any clue whether I missing something in my code or the problem with event `socket.on("new message")`. Can anyone suggest me solution for this ?

**Comment by kshrikant** [comment]
@nuclearace any idea ? Please can u tell me how to resolve this ?

**Comment by nuclearace** [comment]
Is the problem that the socket that sends the message is receiving it as well? Because if that's the case you're using the wrong method on the server.

**Comment by kshrikant** [comment]
Yes, After receiving message from server it is broadcasting as well.Is that issue from server ?

**Comment by nuclearace** [comment]
Did you figure this out?

**Comment by adnanafzal565** [comment]
Please provide any solution for this.

**Comment by hardikdarji** [comment]
Hi @nuclearace 
I have also the same issue. 
Please help with this

**Comment by hardikdarji** [comment]
Hello I solve...
below is fix for me.
When Disconnect...

```
func disconnect() -> Self {
        socket.removeAllHandlers()
        manager.defaultSocket.disconnect()
        return self
    }
```
