### ISSUE TITLE
Socket keep on trying to connect and always fails

### ISSUE THREAD

**Issue by MishraVikas1** [socketio/socket.io-client-swift#365]
Socket IO always oscillate between connecting and disconnected mode, but never connects. i.e. it always hangs between socketConnecting() & socketDisconnected() method.

Connect to *******
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
Disconnecting @   -------**************************------------- socket.on() with attempt >=5 
connected !!!!!!!!!!!!!!
Connected to *****
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
Connect to ********
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
Disconnecting @   -------**************************------------- socket.on() with attempt >=5 
Connect to **********
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
Disconnecting @   -------**************************------------- socket.on() with attempt >=5 
connected !!!!!!!!!!!!!!
Connected to **********
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
disconnected !!!!!!!!!!!!!!
Disconnecting @   -------**************************------------- socket.on() with attempt >=5

**Comment by MishraVikas1** [comment]
I fixed this by making below changes in library files (SocketIOClient.swift)

func didDisconnect(reason: String) {
        guard status != .Disconnected else { return }

        DefaultSocketLogger.Logger.log("Disconnected: %@", type: logType, args: reason)

        status = .Disconnected
        reconnects = true    

        // Make sure the engine is actually dead.
        engine?.disconnect(reason)
        handleEvent("disconnect", data: [reason], isInternalMessage: true)
    }

Changed reconnects to true from false. 
Will this change have any side effects? If no, plz update in git repo so we can use this through cocoapods again.

**Comment by nuclearace** [comment]
This was originally done because re-using sockets after calling disconnect wasn't supported. I think it can be changed safely.
