### ISSUE TITLE
What does "currentAmount" mean

### ISSUE THREAD

**Issue by wuzhenli** [socketio/socket.io-client-swift#366]
[socket on:@"currentAmount" callback:^(NSArray* data, SocketAckEmitter* ack) {
    double cur = [[data objectAtIndex:0] floatValue];

    [socket emitWithAck:@"canUpdate" withItems:@[@(cur)]](0, ^(NSArray* data) {
        [socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
    });

    [ack with:@[@"Got your currentAmount, ", @"dude"]];
}];
-------------
What does "currentAmount"@"canUpdate"、@"update"、@"dude" mean？Thank you!

**Comment by nuclearace** [comment]
They're just strings, `canUpdate` and `update` would be events for this api, while `dude` is just string data.
