### ISSUE TITLE
socket.io and engine.io

### ISSUE THREAD

**Issue by arden** [socketio/socket.io-client-swift#369]
if my server side base on engine.io，and my mobile side used the socket.io-client-swift, that could support communication with the server side based on engine.io?

**Comment by nuclearace** [comment]
You'd have to write your own engine client that conforms to https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketEngineClient.swift

**Comment by nuclearace** [comment]
And the engine conforms to https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketEngineSpec.swift
