### ISSUE TITLE
onAny in Objective-C

### ISSUE THREAD

**Issue by KCastiglione** [socketio/socket.io-client-swift#37]
can you please give an example of how onAny works in Objective-C
code auto completes this way: 

how do I access event and data received?

    [socket onAny:^{
        
    }];

Thanks

**Comment by nuclearace** [comment]
I'll have to write a method for obj-c, since onAny uses a tuple. Which aren't accessible from Obj-c

**Comment by nuclearace** [comment]
I think you'd do

```objective-c
[socket onAnyWithHandler: ^(SocketAnyEvent* e) {
    e.event;
    e.items;
}];
```

**Comment by nuclearace** [comment]
That's after latest commit

**Comment by nuclearace** [comment]
Objective-C is so terribly ugly. The Swift version is so much nicer.

**Comment by KCastiglione** [comment]
thanks for the fix! Objective-C was terrible, but once used to it, it is awesome!

If i have an event defined, and also have onAny, both are getting hit.
This is totally fine, but just want to make sure it is the expected behavior.


        [socket on:@"data" callback:^(NSArray* data, void (^ack)(   NSArray*)) {
           NSLog(@"data:%@", data);
       }];
       [socket onAny:^(SocketAnyEvent* e) {
           NSLog(@"%@", e.event);
           NSLog(@"%@", e.items);
       }];
   

In this case it hits both onAny, and also on - both get executed.

**Comment by nuclearace** [comment]
On any is always called first.

**Comment by KCastiglione** [comment]
great thanks works well!

**Comment by trungnguyen1791** [comment]
I can't find "SocketAnyEvent" after using pods? Maybe u missing something here

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/blob/master/SwiftIO/SocketAnyEvent.swift#L27 Is public and `@objc` so it should be available to Objective-C
