### ISSUE TITLE
how to add session or other parameter during my connecting ???

### ISSUE THREAD

**Issue by ysfox** [socketio/socket.io-client-swift#370]
In my project,first connecting,i must pass user's session id and roomId,so i join the request url like blow
`NSURL* url = [[NSURL alloc] initWithString:[NSString stringWithFormat:@"http://192.168.12.101:3000?SESSION=%@&formId=%ld",authModel.sessionId,roomId]];`
but the result is conneted ok but our server don't get the request sessionId and roomId,
how can do do it,can you give some suggestion!TKS

**Comment by ysfox** [comment]
In Java servion,I sove it like this 
I join th session and formId in my url,Java connected is OK and our server get the session and formId,Now problem is in iOS,I can't send the session and formId?how can do it? TKS!!!
`    private void initSocket() {
        String si = null;
        this.spHelper = new SharedPreferencesHelper(_this, "niugu_config");
        if (httpController.isLogin())
            si = spHelper.getString("session");
        LogUtil.e("session=" + si);
        try {
            socket = IO.socket(NetUrl.SOCKET_URL + "?SESSION=" + si + "&formId=" + roomId);
            socket.on(Socket.EVENT_CONNECT,
                    args -> {
                        LogUtil.e("已进入房间:" + roomId + "\n" + String.valueOf(args));
                    })
                    .on(Socket.EVENT_DISCONNECT,
                            args -> {
                                LogUtil.e("已退出房间:" + roomId + "\n" + String.valueOf(args));
                            })
                    .on("niugu", args -> {
                        for (Object obj : args) {
                            String msgStr = String.valueOf(obj);
                            LogUtil.e("【收到新消息】" + msgStr);
                            try {
                                org.json.JSONObject jObj = new org.json.JSONObject(msgStr);
                                if (jObj.getString("action").equals("createMessage")) {//todo 其他的action?
                                    NgMsg ngMsg = JSONObject.parseObject(jObj.getString("data"), NgMsg.class);

                                    Message msg = new Message();
                                    msg.what = 111;
                                    Bundle bd = new Bundle();
                                    bd.putSerializable("msg", ngMsg);
                                    msg.setData(bd);
                                    newMsg.sendMessage(msg);
                                }
                            } catch (JSONException e) {
                                e.printStackTrace();
                            }
                        }
                    });
            socket.connect();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }`

**Comment by nuclearace** [comment]
There's the .ConnectParams([String: AnyObject]) option

**Comment by ysfox** [comment]
I use object-c Bridge model，in bridge.h can‘t find ConnectParams method...

**Comment by ysfox** [comment]
the swift.h bridge file like blow,no find connectParams...method


`/// Not so type safe way to create a SocketIOClient, meant for Objective-C compatiblity. If using Swift it's recommended to use init(socketURL: NSURL, options: Set<SocketIOClientOption>)
- (nonnull instancetype)initWithSocketURL:(NSURL * __nonnull)socketURL options:(NSDictionary * __nullable)options;

/// Connect to the server.
- (void)connect;

/// Connect to the server. If we aren't connected after timeoutAfter, call handler
- (void)connectWithTimeoutAfter:(NSInteger)timeoutAfter withTimeoutHandler:(void (^ __nullable)(void))handler;
- (void)didConnect;
- (void)didDisconnect:(NSString * __nonnull)reason;`

**Comment by ysfox** [comment]
you mean is like this ???

`        NSURL* url = [[NSURL alloc] initWithString:[NSString stringWithFormat:@"http://192.168.12.101:3000"]];
        SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:url options:@{@"forcePolling": @YES}];
        
        [socket.engine setConnectParams:@{@"SESSION": authModel.sessionId, @"formId": @(self.roomId)}];
        [socket on:@"connect" callback:^(NSArray* data, SocketAckEmitter* ack) {
            CFLog(@"%@-------%@",data,ack);
        }];
        
        [socket on:@"niugu" callback:^(NSArray* data, SocketAckEmitter* ack) {
            CFLog(@"%@-------%@",data,ack);
        }];
        
        [socket connect];`

**Comment by ysfox** [comment]
how to set parameters during my first connected our servers????
I set the parameters in cookies,but get worry!

**Comment by nuclearace** [comment]
Like it says in the readme, SocketIOClientOptions have to be turned into a dictionary in Objective-C

```objective-c
NSDictionary* options = @{@"connectParams": @{@"someThing": @1}};
```
