### ISSUE TITLE
VoIP socket getting disconnected in background.

### ISSUE THREAD

**Issue by zmz2** [socketio/socket.io-client-swift#371]
I'm using Socket.io for communication between my VoIP app and my nodejs server. 

I've enabled the voip option for my socket, but it still seems to get disconnected about 30 seconds after the app moves to the background.

Is there some other configuration necessary to keep the socket alive?

Here is my initialization code

socket = SocketIOClient(socketURL: socketURL, options: [.ForceWebsockets(true), .Log(false), .VoipEnabled(true)])

initSocketHandlers() //this simply adds a bunch of listeners to the socket.

socket.connect()

**Comment by nuclearace** [comment]
Have you set the background execution permissions?

**Comment by zmz2** [comment]
Yes, I used to use a VoIP library called Sinch and it worked perfectly, so I know that I have the correct permissions. 

I am trying to switch over to socket io so I can detect presence and send custom messages.

**Comment by nuclearace** [comment]
Background execution is the one thing I'm never sure of, since I've not really tried and getting it working myself. And I really wouldn't ever think to use socket.io for VoIP.

**Comment by zmz2** [comment]
Alright, I guess I'll try the underlying web socket library used here. 

I'm trying to stay swifty and Apple hasn't ported the socket stuff well yet.
