### ISSUE TITLE
connect to a web socket after getting a cookie

### ISSUE THREAD

**Issue by Siretfel** [socketio/socket.io-client-swift#377]
Hi,

quite new to the field and I would like to ask your advice on how to use the library and if my scenario can run successfully with socket.io swift client.

I sending a post request to http://1.2.3.4/Login, which returns an empty response but a cookie in the header. I am storing the cookie value in memory. 

Second step is to connect to the web socket. What I have done so far is:

```
socket = SocketIOClient(socketURL: NSURL(string: "http://1.2.3.4")!, options: [
            "reconnects": false,
            "reconnectAttempts": 1,
            "reconnectWait": 10,
            "log":true,
            "voipEnabled": true,
            "extraHeaders": ["Connection": "Upgrade", "Upgrade": "websocket", "OSC_USERID": "eleftherios.labros"],
            "path": "/webservice/",
            "cookie": "23434234",
            "forceWebsockets": 1
        ])

        socket!.connect()
```
 
The client fails to connect and here is the log

> 2016-05-27 18:51:32.742 osmo_swift[3778:191891] LOG SocketEngine: Starting engine
> 2016-05-27 18:51:32.742 osmo_swift[3778:191891] LOG SocketEngine: Handshaking
> (lldb) po urlRequest
> <CFHTTPMessageRef 0x7f9644ac8830(0x7f9644ac8840)> { GET request, url ws://1.2.3.4/webservice/ }
> 
> 2016-05-27 18:51:50.101 osmo_swift[3778:192197] ERROR SocketEngine: write wait timed out
> 2016-05-27 18:51:50.102 osmo_swift[3778:192197] ERROR SocketIOClient: write wait timed out
> 2016-05-27 18:51:50.102 osmo_swift[3778:192197] LOG SocketIOClient: Handling event: error with data: (
>     "write wait timed out"
> )

I am trying to send a 

> "Connection": "Upgrade"

in the header that it is not sent (in the trace I saw that Connection: keep alive is sent). 

Moreover when I removing the forceWebsockets option, the url is http:// and not ws:// the connection is made, however it is considered bad request because the "Connection: Upgrade" is missing.

Any advice on how to proceed here? 

Thanks

**Comment by nuclearace** [comment]
I think you want something like Starscream, which is just a WebSocket client.
