### ISSUE TITLE
Handling event error

### ISSUE THREAD

**Issue by arashdoescode** [socketio/socket.io-client-swift#379]
I have this problem that whenever I tried to emit onJob, it's not working

Got this error whenever I'm trying to emit

```
Handling event: error with data: (
    "Tried emitting onJob when not connected"
)
```

As far as I concerned I already connect it in delegate

Here is the code

```
import UIKit
import SocketIOClientSwift

class SocketIOManager: NSObject {
    static let sharedInstance = SocketIOManager()
    
    let socket = SocketIOClient(socketURL: NSURL(string: "https://testing.herokuapp.com")!, options: [.Log(true), .ForcePolling(true)])
    
    
    override init() {
        super.init()
    }
    
    
    func establishConnection() {
        socket.connect()
    }
    
    
    func closeConnection() {
        socket.disconnect()
    }
    
    func onJob(lat: String, long: String) {
        socket.emit("onJob", lat, long)
    }
}
```

**in app delegate**

```
func applicationDidBecomeActive(application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
        SocketIOManager.sharedInstance.establishConnection()
    }

```

**in a view controller**
Whenever someone presses a button then socket will emit to the server

`SocketIOManager.sharedInstance.onJob("12", long: "12")`

**Comment by nuclearace** [comment]
Have you tried checking whether it's actually connected or not?

**Comment by arashdoescode** [comment]
How do i do that?

**Comment by nuclearace** [comment]
```swift
if socket.status == .Connected { }
```

**Comment by arashdoescode** [comment]
If it is not connected what are the possibilities?

**Comment by arashdoescode** [comment]
The problem is currently is with the authorization library that Im using on the serverside, which is socket.io-jwt, it requires the authorization headers. So basically my approach will be to emit the token from the authentication back to the front end.

```
socket.on('authorized', function(data) {
    socket.emit('token', data);
});
```

Tell me whether this approach is safe to do?
