### ISSUE TITLE
Rework Objective-C API

### ISSUE THREAD

**Issue by nuclearace** [socketio/socket.io-client-swift#38]
Since a lot of people seem to be using it from Objective-C.

**Comment by KCastiglione** [comment]
Awesome!

**Comment by nuclearace** [comment]
Ehhhh, I thought about doing delegation with Objective-C (rather than using blocks) since I don't like how Objective-C translates Swift functions. Also, I'm not an Objective-C dev, my Swift knowledge is 100x more than Objective-C.

Thoughts?

![](https://i.imgur.com/CNXJr7K.png)

**Comment by KCastiglione** [comment]
For now blocks are working fine and not missing anything.

**Comment by nuclearace** [comment]
Hm, what would you have tweaked so that it works better with Objective-C?

**Comment by KCastiglione** [comment]
Don't have any inputs to make it better, works great as of now.
