### ISSUE TITLE
Anyone have any experience on how to emit the token from IOS/swift to server ?

### ISSUE THREAD

**Issue by arashdoescode** [socketio/socket.io-client-swift#382]
It's been 4 hours, but for somehow I couldn't fix this problem, I can't send the token to the server no matter what I do

Serverside code

```
io.use(socketioJwt.authorize({
  secret: config.SECRET,
  handshake: true
}));

  io
    .on('connection', function(socket) {


  })
   .on('authenticated', function(socket){
   console.log('connected & authenticated: ' + JSON.stringify(socket.decoded_token));
    socket.on('onJob', function(data) {
      console.log(data);
    });
});
```

Client-side code - IOS/SWIFT
```

import SocketIOClientSwift
import KeychainAccess

class SocketIOManager: NSObject {
    static let sharedInstance = SocketIOManager()

    let socket = SocketIOClient(socketURL: NSURL(string: "https://testing.herokuapp.com")!,
                                                     options: [.Log(true)])

    override init() {
        super.init()

    }


    func establishConnection(token: String) {
        socket.on("connection") {data, ack in
            self.socket.emit("authenticated", token);
        }
    }

    func closeConnection() {
        socket.disconnect()
    }

    func genieOnJob(lat: String, long: String) {
        socket.emit("genieOnJob", lat, long)
    }


}

```
So technically whenever someone tap a button on the clientside, then I will call establishConnection and provide with a token.

Anyone have any experience on how to fix this problem?

**Comment by nuclearace** [comment]
You can use the ConnectParams option to provide connection parameters

**Comment by arashdoescode** [comment]
Is this the only way?

**Comment by nuclearace** [comment]
Probably, since the library is most likely looking for the jwt during the connection

**Comment by arashdoescode** [comment]
I keep getting this error

Handling event: error with data: (
        {
        code = "credentials_required";
        message = "No Authorization header was found";
        type = UnauthorizedError;
    }
)

**Comment by arashdoescode** [comment]
import UIKit
import SocketIOClientSwift
import KeychainAccess

class SocketIOManager: NSObject {
    static let sharedInstance = SocketIOManager()
    
    let keychain = Keychain(server: "https://testing.herokuapp.com", protocolType: .HTTPS)
    
    var token: String {
        get {
            return String(keychain["token"])
        }
    }
    
    lazy var socket: SocketIOClient = SocketIOClient(socketURL: NSURL(string: "https://testing.herokuapp.com")!,
                                                     options: [.Log(true), .ConnectParams(["Authorization": self.token])])
        
    override init() {
        super.init()
        
    }
    
    
    func establishConnection() {
        socket.connect()
    }

    func closeConnection() {
        socket.disconnect()
    }
    
    func onJob(lat: String, long: String) {
        socket.emit("onJob", lat, long)
    }
    
    
}

**Comment by nuclearace** [comment]
Okay I lied, you want to use `case ExtraHeaders([String: String])` since it's expecting it to be apart of the header.

**Comment by arashdoescode** [comment]
I tried Extraheaders before ConnectParams, still getting errors. I even wrote a stackoverflow question, but couldn't find an answer. I'm screwed :( 

Here's the question

http://stackoverflow.com/questions/37549701/secret-or-public-key-must-be-provided-ios-swift-socket-io-jwt

Btw I couldn't find this open source tag on SO

**Comment by nuclearace** [comment]
how do you do it with js

**Comment by arashdoescode** [comment]
I took directly from this open sourced library https://github.com/auth0/socketio-jwt

Assumed that libraries has been called.

```
io.use(socketioJwt.authorize({
  secret: config.SECRET,
  handshake: true
}));

io
     .on('connection', function(socket) {

      })
	.on('authenticated', function(socket){
	   console.log('connected & authenticated: ' + socket.decoded_token);
           socket.on('genieOnJob', function(data) {
          console.log(data);
    });
});
```

**Comment by nuclearace** [comment]
For your ConnectParams try using ["token": token]

**Comment by arashdoescode** [comment]
I did that already, if you take a look at SO question.

**Comment by nuclearace** [comment]
Did you solve this?

**Comment by arashdoescode** [comment]
Already solved it, thanks Erik

**Comment by nithinreddygaddam** [comment]
Can you please tell me how you solved this problem? and did you create an Auth0 account for your application?

**Comment by spartangian** [comment]
I had the same problem. But I already made it work. In my situation I just did this:

var socket = SocketIOClient(socketURL: URL(string: "https://blah-blah.io")!, config: SocketIOClientConfiguration(arrayLiteral: SocketIOClientOption.connectParams(["jwt": self.token])))

FYI: I am using swift 3 and updated xcode

**Comment by myusuf08** [comment]
how you solve this ?

**Comment by ngaddamLogitech** [comment]
Send the token string using emit like an other regular string

**Comment by AdnanMunir** [comment]
> Send the token string using emit like an other regular string

ngaddam can you please share your code ?

manager = SocketManager(socketURL: URL(string: url)!, config: [.secure(true),.log(true),.forceNew(true),.forceWebsockets(true),.extraHeaders(["Authorization":"Bearer \(token)"])])
        
     
        socket = manager.defaultSocket
socket.connect()


but its not working

**Comment by ngaddamLogi** [comment]
You can check my server code in here: https://github.com/nithinreddygaddam/Server-SocketChat/blob/master/index.js

it is an iOS chat application built using socket.io. The server code and iOS application is made public for your reference.

**Comment by gDeep1** [comment]
Following configs worked for me. My server implementation was expecting 'websocket' as transporter while it is set to 'polling' by default. Once i forced Websockets, it made the connection.

```
SocketManager(
            socketURL: socketURL,
            config: [
                .log(true),
                .compress,
                .secure(true),
                .extraHeaders(["auth": "\(token)"]),
                .forceWebsockets(true)
            ]
        )
```
