### ISSUE TITLE
Crash on All devices running iOS 7.x

### ISSUE THREAD

**Issue by engWaleedQ** [socketio/socket.io-client-swift#383]
All my users on iOS 7 are having the same crash over and over 

#0
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE 0x0000000000c0993c
 Raw
0
libswiftCore.dylib	
swift_initClassMetadata_UniversalStrategy + 439
17
libswiftCore.dylib	
_TTSf4n_n_n_d___TFVs6MirrorCfT6legacyPs11_MirrorType_11subjectTypePMP_20makeSuperclassMirrorGSqFT_GSqS____S_ + 1220
18	OpenSooq	
SocketIOClientOption.swift line 0
SocketIOClientOption.description.getter
19	OpenSooq	
SocketIOClientOption.swift line 60
SocketIOClientOption.hashValue.getter
20	OpenSooq	
SocketIOClientOption.swift line 59
protocol witness for Hashable.hashValue.getter in conformance SocketIOClientOption
21	OpenSooq	
SocketIOClientOption.swift line 0
specialized _VariantSetStorage.nativeUpdateValue(A, forKey : A) -> A?
22	OpenSooq	
SocketIOClientOption.swift line 0
static Set<A where ...>.NSDictionaryToSocketOptionsSet(NSDictionary) -> Set<SocketIOClientOption>
23	OpenSooq	
SocketIOClient.swift line 107
@objc SocketIOClient.init(socketURL : String, options : NSDictionary?) -> SocketIOClient
24	OpenSooq	
OSChatManager.m line 87
-[OSChatManager connectSocket]

**Comment by nuclearace** [comment]
That looks to be a problem with Swift itself on iOS 7. In which case the only solution would be to avoid that code path by using the Swift initializers, which would mean using a Swift class. That being said, support for iOS is probably something that is going to be dropped from this library in the near future.

**Comment by arashdoescode** [comment]
@nuclearace What do you mean support will be dropped?

**Comment by AlexChesters** [comment]
@arashdoescode I'm assuming @nuclearace did a typo, and meant to write iOS 7?

**Comment by nuclearace** [comment]
Yes.

**Comment by shanshuiren** [comment]
I have the same problem. Any solution?

**Comment by nuclearace** [comment]
@shanshuiren are you using it from Objective-C? Because it looks like the problem is related to Swift on iOS 7.  In which case the only way to avoid it would be to avoid that code path by using the SocketIOClientOption initializer.

**Comment by shanshuiren** [comment]
@nuclearace  Yes, i'm using it from Objective-C.
