### ISSUE TITLE
Where exactly should i establish a connection to make the connection persist?

### ISSUE THREAD

**Issue by arashdoescode** [socketio/socket.io-client-swift#386]
I'm wondering where exactly should i do 

`socket.connect`

Currently I made a class solely just for socket's events

```
class SocketIOManager: NSObject {
    static let sharedInstance = SocketIOManager()
    
    lazy var socket: SocketIOClient = SocketIOClient(socketURL: NSURL(string: "https://testing.herokuapp.com")!,
                                                     options: [.Log(true), .ConnectParams(["token": self.token])])
   
        
    override init() {
        super.init()
        
    }
    
    
    func establishConnection() {
        socket.connect()
    }

    func closeConnection() {
        socket.disconnect()
    }   
}
```

Where exactly should I call `SocketIOManager.sharedInstance.establishConnection` ?

and one more thing, if I instantiate a new socket object on every view controller, would the socket knows one another? or i just need to do` socket.connect` once?

**Comment by nuclearace** [comment]
It's entirely up to you where to call the connect. But sockets are independent of each other, so you'd have to call connect on each of them.

**Comment by arashdoescode** [comment]
For your advise in app.delegate, where should i put it? let say if put the app in background and whenever trying to connect it again ,the socket will lost it connection

**Comment by nuclearace** [comment]
That's because iOS doesn't let you do background execution for this kind of thing unless you do some trickery involving VoIP which probably isn't what you're doing.

**Comment by arashdoescode** [comment]
Just for clarity, if i establish the connection in any screen, the connection will persist in any other screen? only if the app still active?

**Comment by nuclearace** [comment]
As long as the app is in the foreground and the socket isn't released, then it should remain connected.
