### ISSUE TITLE
socket.on does not listen to the event

### ISSUE THREAD

**Issue by arashdoescode** [socketio/socket.io-client-swift#387]
I have tested so many times, but it seems that socket.on doesn't run.

Here's the scenario

1. First I emit a certain datas to the server
2. I run the server, and it shows the data correctly
3. On one of the View Controller, there is an `on` event , but it seems at this step it doesn't run the code

**SocketIO class**

```
class SocketIOManager: NSObject, {
    static let sharedInstance = SocketIOManager()   
    let keychain = Keychain(server: "https://testing.herokuapp.com", protocolType: .HTTPS)
 
    var token: String {
        get {
            if let realToken = keychain["token"] {
                return String(realToken)
            } else {
                return ""
            }
            
        }
    }
    
    lazy var socket: SocketIOClient = SocketIOClient(socketURL: NSURL(string: "https://testing.herokuapp.com")!,
                                                     options: [.Log(true), .ConnectParams(["token": self.token])])
    
    let locationManager = CLLocationManager()
    let marker = GMSMarker()
    var mapView = GMSMapView()
        
    override init() {
        super.init()
        
    }
    
    
    func establishConnection() {
        socket.connect()
    }

    func closeConnection() {
        socket.disconnect()
    }
    
    func onJob(lat: Double, long: Double) {
        socket.emit("onJob", ["latitude": lat, "longtitude": long])
    }
    
    func testListening() {
        // This code doesn't run
        socket.on("onJob") { data, ack in
            print(data)
            print("Run something here")
            
        }
    }
    
    
}

```

View Controller 1 -> Emit

Let say a user press a button, then it will emit

`SocketIOManager.sharedInstance.onJob(position.target.latitude, long: position.target.longitude)
`

View Controller 2 -> On

` SocketIOManager.sharedInstance.testListening()`

Just for your understanding, I established the connection whenever the user has logged in.

**Comment by nuclearace** [comment]
Is your event handler being added? Also I see that your emit is the same as the event you're expecting from the server, is that correct?

**Comment by arashdoescode** [comment]
Sorry for the late reply, I made a mistake on my part. Thank you for pointing that out.

**Comment by itkith** [comment]
I am trying to create a  common class to listen message from socket when user is on different view controller or app is in background mode. Socket.on is not hitting on receiving of message. Kindly help?

**Comment by Humbhiashwani** [comment]
I am trying to create a common class to listen message from socket when user is on different view controller or app is in background mode. Socket.on is not hitting on receiving of message. Kindly help?
