### ISSUE TITLE
Getting event for Google-site-verification

### ISSUE THREAD

**Issue by hughesne** [socketio/socket.io-client-swift#388]
Just getting started with this library and looks very promising for my need.  Im trying to do a simple connect and never get a connect event.  Are all socket connects going to send back a "connect" or is there something else it could be?  But I did the .onAny and getting some socket.io site back.  What exactly is this, which makes me think this is my actual issue?

My code:

let socket = SocketIOClient(socketURL: NSURL(string: [redacted], options: [.Log(true), .ForcePolling(true)])
            
            socket.on("connect") {data, ack in
                print("socket connected")
                socket.emit("sendCmd", bodyStr)
            }
            
            socket.onAny {print("Got event: \($0.event), with items: \($0.items)")}
            socket.connect()

Snippet of the "Got event"
Got message: 
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="google-site-verification" content="6hwSNwrfOBp3YhFBHWy08L12QeMTLpqNI3LvIB4lZEI" />
<title>Socket.IO</title>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="http://socket.io/xmlrpc.php">

<link rel="alternate" type="application/rss+xml" title=" &raquo; Feed" href="http://socket.io/feed/" />
<link rel="alternate" type="application/rss+xml" title=" &raquo; Comments Feed" href="http://socket.io/comments/feed/" />

**Comment by nuclearace** [comment]
Are you sure you're pointing to a socket.io server?
