### ISSUE TITLE
Use of base64

### ISSUE THREAD

**Issue by LamourBt** [socketio/socket.io-client-swift#389]
Hello guys, 
Let's say my app is uploading and retrieve many files into AWS S3 (images, and video) using socket.io. As I know so far on all client sides (IOS, Android), I could only send data to the server only if they are convert to base64 (even though i could send it using binary, many said that base64 is fast than binary)... My question is that the best way to do it ? since on the server time, I have to decode the data to put into the s3 and this kind of took sometimes

Any Ideas? I would really appreciate.

**Comment by nuclearace** [comment]
This library can send NSData directly. That being said it will turn it into base64 if the transport being used is http-polling. But as far as the server and client they will get binary. If you emit base64 then you'll be doing the decoding manually on the server.

**Comment by LamourBt** [comment]
From your experience, which approach you think is better and efficient (let's say a lot images are being transfer and retrieved), sending NSDATA from client to server, then on the server i decode then save it into database. Or sending as Base64

**Comment by nuclearace** [comment]
I've never done profiling on it. I just send NSData since it's less code.
