### ISSUE TITLE
on @"connect" is not emitted

### ISSUE THREAD

**Issue by pwnsdx** [socketio/socket.io-client-swift#39]
Hello,
When I'm using SocketIO with Objective-C the "connected" NSLog does not appear.

Here is my code:

```
    self.socket = [[SocketIOClient alloc] initWithSocketURL:@"http://10.211.55.3"
                                                    options:nil
                                   /* options:@{
                                        @"reconnects": @true, // Default is true
                                        @"reconnectAttempts": @5, // Default is -1 (infinite tries)
                                        @"reconnectWait": @5, // Default is 10
                                        @"nsp": @"/socket.io/", // connects to the specified namespace. Default is /
    }*/];
    
    [self.socket onAny:^{
        NSLog(@"Test");
    }];
    
    [self.socket on: @"reconnect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"reconnect");
    }];
    
    [self.socket on: @"connect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"connected");
//        [self.socket emitObjc:@"echo" withItems:@[@"echo test"]];
//        [[self.socket emitWithAckObjc:@"ackack" withItems:@[@"test"]] onAck:0 withCallback:^(NSArray* data) {
//            NSLog(@"Got data");
//        }];
    }];
    
    // Connect ?
    [self.socket connect];
```

In Debug navigator I noticed that socket.io was able to contact the server:
![screen shot 2015-03-31 at 19 02 51](https://cloud.githubusercontent.com/assets/2057765/6924394/8a4ce5e8-d7d8-11e4-9716-7c016de5bba9.png)

Can someone help me to figure out what is the problem please? Thanks!

**Comment by nuclearace** [comment]
Is the onAny method ever called?

**Comment by nuclearace** [comment]
Also I note that your socketURL doesn't specify a port. Is your socket.io server running on port 80? I've had people complain about running socket.io behind nginx.

**Comment by pwnsdx** [comment]
Hello,

Yes my server is running on port 80. I do not use nginx but Express.

Thanks.

**Comment by nuclearace** [comment]
Hm, I seem to be able to connect to a socket.io server on port 80 fine

**Comment by pwnsdx** [comment]
Very strange :/

With my code?

**Comment by nuclearace** [comment]
Hm, when I try to use the IP in your code I don't get any messages.

**Comment by tzapu** [comment]
hi,
i am also having the same problem, no messages at all, not even "connected"
using example tic tac toe server, swify project works fine, objc project does nothing. node server sees the connection and issues 'adding player'
cheers

```
SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"http://localhost:8900" options:nil];
    NSLog(@"before connect");
    [socket on: @"connect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"connected");
        //[socket emitObjc:@"echo" withItems:@[@"echo test"]];
        //[[socket emitWithAckObjc:@"ackack" withItems:@[@"test"]] onAck:0 withCallback:^(NSArray* data) {
            NSLog(@"Got data");
        //}];
    }];
    
    [socket onAny:^(SocketAnyEvent* e) {
        NSLog(e.event);
        NSLog(@"%@", e.items);
    }];

    [socket connect];

```

**Comment by pwnsdx** [comment]
Oh, interesting as I still don’t know how to fix that :/

**Comment by nuclearace** [comment]
@tzapu @pwnsdx where are you declaring your socket? It sounds like it's being deallocated before it's supposed to.

**Comment by tzapu** [comment]
oh boy, i feel so silly, you are completely correct. i am declaring the socket now as a global @property and am getting events fine.

thank you very much
