### ISSUE TITLE
Can't find about disconnection or heartbeat

### ISSUE THREAD

**Issue by mbalex99** [socketio/socket.io-client-swift#390]
I'm trying to record a timestamp of the last connection with the server. 
I'm simulating a loss of connectivity by going on **airplane mode** 

I can't seem to get a disconnected event 

```swift
socket.on("disconnect"){ data in
     //NEVER GETS FIRED WHEN LOSING CONNECTION
}
```

```swift
socket.on("pong"){ data  in
     // ALSO NOTHING
}
```

```swift
socket.on("heartbeat"){ data in 
     // nothing
}
```

How would I record a timestamp of the last reliable connection with the server? I'm trying to retrieve missed messages. The problem is that I can't rely on sequential data since I might commit some data from push notifications so there will missing gaps of data.

**Comment by nuclearace** [comment]
I've seen other people say airplane mode doesn't signal a disconnection. Not sure if that's a problem with this library or something else though since disconnections are signaled from the networking. But if you need to record connection stuff you'd have to modify the Engine since it's responsible for pongs.

**Comment by mbalex99** [comment]
@nuclearace Thanks for the quick reply but how do you listen for reserved events from the server. 
Heartbeats should be from the server -> client and then the client responds back?

Are you saying I have to do this on the server side?

```javascript
setInterval(() => {
    socket.forEach(s => {
          s.emit('heartbeat', {})
    });
})
```

**Comment by nuclearace** [comment]
I'm not aware of a socket.io heartbeat event. I know that engine.io has a ping/pong mechanism.
