### ISSUE TITLE
Using socket.io-client-swift in an Objective-C framework.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-swift#393]
Hi,

We are trying to integrate your socket.io-client-swift library into our existing Objective-C framework which will be released to other developers to integrate into their applications.

Is this scenario considered when you develop socket.io-client-swift? Is there anything special (compared with integrating socket.io-client-swift into an app) we need to consider?

Thanks!

**Comment by nuclearace** [comment]
I'm not sure. I know there's some problem where you can't make it a static framework.

**Comment by hifall** [comment]
Right. In Xcode 7.3, after I added the swift files and tried to compiled my framework, it errored: Swift is not supported for static libraries.

But maybe we can compile your lib into a framework first, then link to it? Haven't tried that yet. Just a thought.

**Comment by drekka** [comment]
@hifall Change your build target from a static library to a framework. You can then use socket.io in it without issues. You can also build socket.io as a framework as import that. In my project I'm building socket.io and other frameworks using carthage without issues.

**Comment by hifall** [comment]
@drekka, thanks for the hint. But any chance you could provide a bit more detail on "Change your build target from a static library to a framework", or provide any pointer to it? I am building my framework following this link: https://github.com/jverkoey/iOS-Framework.

Thanks!

**Comment by drekka** [comment]
Whoa. That information is really out of date - don't do that :-) 

Building a framework these days is dead simple. In Xcode add a new target using the Framework & Library/Cocoa Touch Framework template. Then just add your code like you would for a static library. XCode will build a *.framework file ready for use. 

I did a quick search and found this article: [https://robots.thoughtbot.com/creating-your-first-ios-framework](https://robots.thoughtbot.com/creating-your-first-ios-framework) It seems to be very good in that it shows how easy it is, then goes on to handling dependencies, CocoaPods and  Carthage support, and testing. Pretty much everything you would do as part of building an API.

**Comment by hifall** [comment]
@drekka, thanks for getting back to me! I am indeed not up to date on iOS framework building these days. I will definitely do some research in this area by following your link shortly.

Again, thanks for the link.

**Comment by bhartsb** [comment]
I too am trying to get this library working from Objective-C.  I've added a framework, added the swift source files, and built the framework.  Then I added the @objc prefix to the SocketIOClient.swift class, but still obj-c is not seeing it.  The documentation herein regarding this seems to be missing a lot of steps.

**Comment by drekka** [comment]
Hi @bhartsb - it sounds like you are using socket.io from Swift. Which class are you adding @objc to?

**Comment by bhartsb** [comment]
I have an objective c project that I want to use the swift library in.  I found out that there's a auto generated bridging header file that I have to include in my objective-C file that I want to use this swift library from.  Not withstanding I'm not sure that this is even the correct library to use since I'm using websockets.I saw other issues where another library for specifically websockets was being mentioned.

**Comment by drekka** [comment]
ok. Can't speak for web sockets, but here is basically what I did to use the socket.io framework:

1. Build the socket.io/socket.io-client-swift project using [carthage](https://github.com/Carthage/Carthage). 

    1. Add `github "socketio/socket.io-client-swift"` to my project's **Cartfile**.

    1. Run `carthage update`

1. Add the resulting framework into my project as I would for any other framework.

1. Add an import:

    ```
    #import <SocketIOClientSwift/SocketIOClientSwift-Swift.h>
    ```

1. Instantiate socket:
    ```object
    SocketIOClient *socket = [[SocketIOClient alloc] initWithSocketURL:_serverURL options:@{@"log":@YES}];
    // Configure the socket ...
    ```

Hope that helps.

**Comment by bhartsb** [comment]
Thanks!

**Comment by langyapojun** [comment]
why have not oc,if use swift to create static framework,it will be add libSwiftBridge.a,has 100M+

**Comment by ZvOlCuOk2009** [comment]
I'm adding a dependency, and get the following error:

*** Building scheme "Starscream" in Starscream.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/admin/Test\ Tiras/Carthage/Checkouts/Starscream/Starscream.xcodeproj -scheme Starscream -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.2_8E2002/Starscream/3.0.3 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2r/nmnc_7gx06j5b51q854nm48h0000gn/T/Starscream SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/admin/Test Tiras/Carthage/Checkouts/Starscream)
