### ISSUE TITLE
IPv6-only network Support

### ISSUE THREAD

**Issue by adnanawan12** [socketio/socket.io-client-swift#394]
Currently I am not able to connect with IPv6-only network that is now required by Apple in order to approve the app.

https://developer.apple.com/news/?id=05042016a

At WWDC 2015 we announced the transition to IPv6-only network services in iOS 9. Starting June 1, 2016 all apps submitted to the App Store must support IPv6-only networking. Most apps will not require any changes because IPv6 is already supported by NSURLSession and CFNetwork APIs.

If your app uses IPv4-specific APIs or hard-coded IP addresses, you will need to make some changes. Learn how to ensure compatibility by reading Supporting IPv6 DNS64/NAT64 Networks and watch Your App and Next Generation Networks.

**Comment by adnanawan12** [comment]
https://developer.apple.com/news/?id=05042016a

At WWDC 2015 we announced the transition to IPv6-only network services in iOS 9. Starting June 1, 2016 all apps submitted to the App Store must support IPv6-only networking. Most apps will not require any changes because IPv6 is already supported by NSURLSession and CFNetwork APIs.

If your app uses IPv4-specific APIs or hard-coded IP addresses, you will need to make some changes. Learn how to ensure compatibility by reading Supporting IPv6 DNS64/NAT64 Networks and watch Your App and Next Generation Networks.

**Comment by nuclearace** [comment]
I'm able to connect to a url that points to an ipv6 address fine. ![](https://i.imgur.com/fWeEpcM.png)

I do see a crash when you use an ipv6 address directly though.

**Comment by adnanawan12** [comment]
The problem occurs when you are behind NAT64/DNS64 network. In other words when you are using IPv6-only Networks (not url pointing to IPv6 adress). 

Go through the following documents to test the app (Test for IPv6 DNS64/NAT64 Compatibility Regularly
)

https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1

![internetsharing_ipv6_2x](https://cloud.githubusercontent.com/assets/6416296/16044225/059bafa6-325d-11e6-9335-eb9057f3771b.png)

**Comment by nuclearace** [comment]
Well theoretically this library doesn't make any assumptions. It's based on NSURLSession and NSStream.
