### ISSUE TITLE
sessionDelegate parameter has no effect

### ISSUE THREAD

**Issue by luzianscherrer** [socketio/socket.io-client-swift#395]
In order to implement SSL pinning for my socket.io connection, I'm trying to get the sessionDelegate parameter working. Here's how I'm setting it:

`NSMutableDictionary *params = [NSMutableDictionary new];`
...
`[params setObject:self forKey:@"sessionDelegate"];`
...
`self.socket = [[SocketIOClient alloc] initWithSocketURL:[NSString stringWithFormat:@"%@%@", kBackendUrl, kBackendSocketApiUrlPath] options:params];`

The object containing that code does implement the `<NSURLSessionDelegate>` protocol. The method that I'm interested in would be:

`- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
                                             completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * __nullable credential))completionHandler;
`

But it never gets called. Am I missing something here?

**Comment by nuclearace** [comment]
Are you also forcing Websockets?

**Comment by luzianscherrer** [comment]
Yes.
Am 14.06.2016 15:21 schrieb "Erik Little" <notifications@github.com>:

**Comment by luzianscherrer** [comment]
Very helpful, thanks! You are absolutely right, when I remove the `forceWebsockets` parameter the `NSURLSessionDelegate` does get called as expected. But now I wonder: how can I get SSL pinning working when I need to have `forceWebsockets` enabled?

**Comment by nuclearace** [comment]
No idea, since I don't know what SSL pinning is.

**Comment by luzianscherrer** [comment]
It's as simple as this: normally any SSL certificate which is issued by a CA that is in the iOS truststore is allowed. With SSL pinning you just allow that one specific certificate that you expect from your server. This is usually done in the `- (void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential * __nullable credential))completionHandler;` callback.

**Comment by nuclearace** [comment]
Looks like you might have to change something in here https://github.com/socketio/socket.io-client-swift/blob/master/Source/WebSocket.swift#L876

**Comment by luzianscherrer** [comment]
Thanks for that pointer. Looks like it's about time to learn Swift :/

**Comment by nuclearace** [comment]
Actually you may be able to just add a custom SSLCert before you call the connect method.

```swift
socket.engine?.ws?.security = // However you create an SSLSecurity
```
 But I don't how that works so you're on your own.

**Comment by nuclearace** [comment]
Erm, actually no. Because the engine isn't added until after.

**Comment by luzianscherrer** [comment]
But the comment 

> parameter usePublicKeys: is to specific if the publicKeys or certificates should be used for SSL pinning validation

above the init method looks somewhat promising...

**Comment by nuclearace** [comment]
Yeah, I'm adding an option to make it easy to set this.

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/commit/e163598ee6e6535cad73b7a8f0e2962ff2542f0e See if the latest development with that `.Security` option fixes it.

**Comment by luzianscherrer** [comment]
Cool, thanks. I'll do that but it will take some time... I'll get back to you asap.

**Comment by nuclearace** [comment]
Although I just noticed that I need to make one change.

**Comment by nuclearace** [comment]
Unrelated: You should definitely learn swift. It's much more pleasant to write in than Objective-C imo.

**Comment by luzianscherrer** [comment]
Unrelated: that's what I'm hearing all the time :)

**Comment by luzianscherrer** [comment]
Sorry I'm not really getting it. The idea would be to pass in an instance of a SSLSecurity object as parameter "security", right? But how could I do that since SSLSecurity is declared as a private class?

**Comment by nuclearace** [comment]
It should be public in the dev branch

**Comment by luzianscherrer** [comment]
Ah, I was just about to write that SSLSecurity should extend NSObject in order to be able to access it from Obj-C...

But currently I'm fighting with another problem: I'm having some difficulties upgrading to the latest version (was using 4.1.5 before). I was using `#import <Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h>
` before and have now changed to `#import <SocketIOClientSwift/SocketIOClientSwift-Swift.h>`. The latter contains the correct definitions for the new stuff (SSLSecurity, etc) but somehow the former seems to still get used or referenced because when I click on one of your methods, Xcode jumps to the former. I've tried clean/rebuild many times and I'm currently not sure what this is all about.

**Comment by nuclearace** [comment]
Strange, but honestly I have not used this library from Objective-C, so I'm not sure how to fix that.
