### ISSUE TITLE
SSL Error using Swift 3 branch

### ISSUE THREAD

**Issue by mercury** [socketio/socket.io-client-swift#401]
I am getting the error `ERROR SocketEngine: An SSL error has occurred and a secure connection to the server cannot be made.` when tried with new Xcode 8 and Swift 3. I was trying to connect to non SSL URL but that shouldn't be a problem as I was able to make REST calls to the same URL.

**Comment by nuclearace** [comment]
Well since iOS 9 App Transport Security should have forced you to either Allow Arbitrary Loads or use SSL. I did notice that this was happening on macOS now though.
