### ISSUE TITLE
socket crash when network goes off or tries to reconnect

### ISSUE THREAD

**Issue by MishraVikas1** [socketio/socket.io-client-swift#402]
Whenever a fluctuation occurs in network connection, socket library causes a crash.
By putting "exception breakpoint", it captures fault in "WebSocket.swift" at line 133.

private var canDispatch: Bool {
        mutex.lock()
        let canWork = readyToWrite
        mutex.unlock()
        return canWork
    }
It crashes at =====>> mutex.lock()

**Comment by nuclearace** [comment]
Would be a bug in the Websocket library.
