### ISSUE TITLE
Unable to Trigger an Automatic Reconnection Attempt in v.6.1.3

### ISSUE THREAD

**Issue by jimmychaohc** [socketio/socket.io-client-swift#406]
Hello good people of swift socket io!

In v.6.1.2, whenever socket loses connection to the server, it would automatically reconnect
Example:
"Error" : [The operation couldn’t be completed. Connection reset by peer]
"ReconnectAttempt" : [-1]
"Error" : [The operation couldn’t be completed. (NSURLErrorDomain error -1001.)]
"ReconnectAttempt" : [-2]
...

Then eventually when the server is back up, it will reconnect and trigger the "connected" event.

However since v.6.1.3, it doesn't do that anymore. I was wondering if this is an intentional change? If so, how can I re-initiate the reconnect? I've tried setting .Reconnects(true) and nothing happens :(

**Comment by nuclearace** [comment]
Does it emit a disconnect immediatly?

**Comment by nuclearace** [comment]
Try 6.1.4, I found a bug in disconnections.

**Comment by jimmychaohc** [comment]
I just tested 6.1.4 and it is working. Thanks!!
