### ISSUE TITLE
disconnect, reconnect and reconnectAttempt don't fired.

### ISSUE THREAD

**Issue by hahaGitHub** [socketio/socket.io-client-swift#407]
i add handlers for connect, disconnect, reconnect,error and reconnectAttempt because i want to know different statuses.
1.when i close the wifi, the error handler is fired,and i find the socket status is also SocketIOClientStatusConnected. when i open the wifi,t reconnect,and connect are not fired.
2.when the app goes to background, disconnect is not fired.
please tell me why. thanks.

**Comment by nuclearace** [comment]
Going into the background with the socket connected is considered undefined behavior, since background execution is not permitted. I'll have to test turning off the wifi though.

**Comment by hahaGitHub** [comment]
thank you for your answer.i am waiting for the other answer.

also i find the versions, 6.1.3 and 6.1.2,are different.

**Comment by nuclearace** [comment]
Does it work in 6.1.2?

**Comment by hahaGitHub** [comment]
yes.it works in 6.1.2.

**Comment by nuclearace** [comment]
Try 6.1.4

**Comment by hahaGitHub** [comment]
ok.thanks.

**Comment by hahaGitHub** [comment]
thanks.the 6.1.4 works well.
