### ISSUE TITLE
Connection takes up to a minute

### ISSUE THREAD

**Issue by nhebling** [socketio/socket.io-client-swift#409]
Hi,

i have a socket.io (v1.4.5) server running and with my website everything works fine.
Now I tried to connect via my iPad app to the server using this lib. It also works, but after the connection has been initiated it takes up to a minute until the log says "connected" and my app is able to receivce messages.

I'm using Swift 3 version and code looks like in the example, just that I added the secure=true option as  my domain is using SSL.

Is there anything I can do, do debug this further down, to see what happens and why it takes so long?
Thanks

**Comment by nuclearace** [comment]
Anything further on this?

**Comment by nhebling** [comment]
After a few hours try and error, I removed socket.io and now I'm just using plain websockets. I had to do this radical step as I could not invest more time and the socket connection is an essential part of the app.

Maybe I will give it a try in a few month, but as of now socket.io not used by me anymore.
