### ISSUE TITLE
Error while during linking.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-swift#410]
I am seeing the following issue while trying to link to your library to an iOS app, on Xcode 7.3.1:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC8SocketIO14SocketIOClient", referenced from:
      objc-class-ref in DetailViewController.o
ld: symbol(s) not found for architecture arm64

I can't figure out what the problem is. Can you shed some light here?

**Comment by nuclearace** [comment]
I've seen that error, but it was a long time ago, so I don't remember how to fix it.

**Comment by langyapojun** [comment]
i have same problem,pls quickly check this,my project use it
