### ISSUE TITLE
I connected and joined room and also get history messages, but i cannot get  new message instantly

### ISSUE THREAD

**Issue by NickWarrior** [socketio/socket.io-client-swift#412]

**Comment by nuclearace** [comment]
What?

**Comment by NickWarrior** [comment]
Can you give me some advice

**Comment by NickWarrior** [comment]
[self.client on:@"new_message" callback:^(NSArray * _Nonnull data, SocketAckEmitter * _Nonnull ack) {}];
why this fuction not be invoke

**Comment by NickWarrior** [comment]
Problem is solved, beacuse fuction invoke corretly

**Comment by i-am-chris** [comment]
how do you join a "room" in obj-c

**Comment by nuclearace** [comment]
Joining rooms is done serverside.

**Comment by i-am-chris** [comment]
yes. i have this on server side:

`io.sockets.on('connection', function (socket) {


	// when the client emits 'adduser', this listens and executes
	socket.on('adduser', function(username){
		// store the username in the socket session for this client
		socket.username = username;
    console.log(username);
		// store the room name in the socket session for this client
		socket.room = 'room1';
		// add the client's username to the global list
		usernames[username] = username;
		// send client to room 1
		socket.join('room1');
		// echo to client they've connected
		socket.emit('updatechat', 'poppins', 'you have connected to '+socket.room);
		// echo to room 1 that a person has connected to their room
		socket.broadcast.to('room1').emit('updatechat', 'poppins', username + ' has connected to this room');
		socket.emit('updaterooms', rooms, 'room1');

	});

	// when the client emits 'sendchat', this listens and executes
	socket.on('sendchat', function (data) {
		// we tell the client to execute 'updatechat' with 2 parameters
		io.sockets.in(socket.room).emit('updatechat', socket.username, data);
    console.log(socket.username + ' say: '+data);

	});
});`


How do i listen on "room1" and emit to that room (broadcast) ?
