### ISSUE TITLE
SSL + base64 = wrong base64 received by server

### ISSUE THREAD

**Issue by giacgbj** [socketio/socket.io-client-swift#413]
I have a strange behavior only when I use TLS:

SocketIOClientOption.Secure(true)

When I send a JSON which includes base64 fields, the plus sign ("+") characters are replaced by spaces when received by a Java Netty server.

Without TLS it works properly.

Have you experienced such an issue?

**Comment by nuclearace** [comment]
I've never seen this before. Are you sending the JSON as a Dictionary or a String?

**Comment by giacgbj** [comment]
let jsonStr = [this is the JSON as a String]

and this is the JSON I send with emitWithAck:

let jsonToSend = try! NSJSONSerialization.JSONObjectWithData(jsonStr.dataUsingEncoding(NSUTF8StringEncoding)!, options: .AllowFragments)

**Comment by nuclearace** [comment]
Does it have to be sent as a string? The client can automatically turn Dictionaries and Arrays into JSON strings.

**Comment by giacgbj** [comment]
No, I cannot send it as a string.

What's strange is that without TLS it works properly. 

Could it be due to the fact that when I use Secure(true) I can't use ForceWebsockets(true)?

**Comment by nuclearace** [comment]
Why can't you force websockets and use secure?

**Comment by giacgbj** [comment]
If I enable it, I can't even connect to the server. 

The logs are:

LOG SocketEngine: Starting engine. Server: https://[OMISSIS]
LOG SocketEngine: Handshaking
CFNetwork SSLHandshake failed (-9807)
ERROR SocketEngine: The operation couldn’t be completed. (OSStatus error -9807.)
ERROR SocketIOClient: The operation couldn’t be completed. (OSStatus error -9807.)
LOG SocketIOClient: Handling event: error with data: (
    "The operation couldn\U2019t be completed. (OSStatus error -9807.)"
)
LOG SocketIOClient: Starting reconnect
LOG SocketIOClient: Handling event: reconnect with data: (
    "The operation couldn\U2019t be completed. (OSStatus error -9807.)"
)
LOG SocketIOClient: Trying to reconnect
LOG SocketIOClient: Handling event: reconnectAttempt with data: (
    "-1"
)
LOG SocketEngine: Starting engine. Server: https://[OMISSIS]
LOG SocketEngine: Handshaking
CFNetwork SSLHandshake failed (-9807)
ERROR SocketEngine: The operation couldn’t be completed. (OSStatus error -9807.)
ERROR SocketIOClient: The operation couldn’t be completed. (OSStatus error -9807.)
LOG SocketIOClient: Handling event: error with data: (
    "The operation couldn\U2019t be completed. (OSStatus error -9807.)"
)

The error "OSStatus -9807" seems to be related to the fact that I'm using a self-signed certificate, so I added an handler which accepts such a certificate using "SocketIOClientOption.SessionDelegate". Unfortunately, the connection only works if I don't set ForceWebsockets(true).

**Comment by nuclearace** [comment]
Are you also using the .SelfSigned option? It's only used by the Websocket library.

**Comment by giacgbj** [comment]
Unfortunately, I didn't use it because of "Don't do this, iOS will yell at you" :D
What did you really mean?

.SelfSigned option solves both the connect and the base64 problems.

Obviously, I won't use a self-signed certificate in production environments, but I was obliged to use it during the developing phase.

If you think that the behaviors I had using the options in such ways are normal, I'll close this issue.

**Comment by nuclearace** [comment]
Just to make sure it isn't a problem with polling, does it work if you're not using SSL and forcePolling?

**Comment by giacgbj** [comment]
It worked: I tested it before using SSL.

**Comment by nuclearace** [comment]
And that was with the forcePolling option, right?

**Comment by giacgbj** [comment]
I thought you meant neither using SSL nor forcePolling. 
To be clear, without using SSL:

ForceWebsockets(false)
ForcePolling(false)

OK

***

ForceWebsockets(false)
ForcePolling(true)

KO (plus signs replaced by spaces in base64)

***

ForceWebsocket(true)
ForcePolling(false)

OK

***

ForceWebsocket(true)
ForcePolling(true)

OK

**Comment by nuclearace** [comment]
So it's a problem with polling

**Comment by nuclearace** [comment]
Hm, it seems to work with socket.io on node.js

**Comment by nuclearace** [comment]
Anything more on this?
