### ISSUE TITLE
how to sendPing by SocketIOClient?

### ISSUE THREAD

**Issue by CheerCc** [socketio/socket.io-client-swift#414]
Hi, @nuclearace ,
    Now I use the SocketIOClient to connect webSocket server, and add the option `@"forceWebsockets" : @YES`. I need to send Ping to server every 10s. In WebSocket.Swift, i find the func `writePing` to send Ping to server. I want to know how to achieve this function that send Ping to server every 10s by SocketIOClient. Looking forward to your reply.Thanks.

**Comment by nuclearace** [comment]
The ping isn't something that you control on the client side. It's controlled on the server.

**Comment by CheerCc** [comment]
So you mean that server send ping to my client side, and when i recevice the ping this  library will reply pong to server automatically?

**Comment by nuclearace** [comment]
The server tells the client what the ping interval is during the handshaking.

**Comment by CheerCc** [comment]
OK , Thanks, i think i have idea to solve my problem. Thanks for your reply.
