### ISSUE TITLE
crash on ios9+

### ISSUE THREAD

**Issue by stevenlfg** [socketio/socket.io-client-swift#415]
![4004b39a-e961-4979-af86-109210d2b8ca](https://cloud.githubusercontent.com/assets/7380905/16554591/790b688c-4202-11e6-8861-33c3b97e4e5b.png)

**Comment by stevenlfg** [comment]
is this problem same to this one?https://github.com/socketio/socket.io-client-swift/issues/406

**Comment by nuclearace** [comment]
No, that's different.

**Comment by stevenlfg** [comment]
What do you think is the main reason for the problem？

**Comment by stevenlfg** [comment]
I find that struct SocketAck did not  implement the protocol Comparable.Is this reason?
![9fe777ee-8250-486f-9b8e-e5d2617cbd81](https://cloud.githubusercontent.com/assets/7380905/16580691/40e1fb20-42d8-11e6-83d9-a120a5afc1d1.png)

**Comment by nuclearace** [comment]
No, this is probably a case of different dispatch queues modifying something

**Comment by stevenlfg** [comment]
@nuclearace Can you tell me a solution to avoid this problem？Thank you !

**Comment by stevenlfg** [comment]
Because the problem of this crash is the occasional,I've changed some in this file. This can avoid the problem?
![b7a34df3-1050-41d8-b771-0f9c37b5abfb](https://cloud.githubusercontent.com/assets/7380905/16755726/3f764f2a-4832-11e6-89b3-b22cbdc6433f.png)

**Comment by nuclearace** [comment]
That may fix it, it may not. It's some race condition based on improper access to the ack manager.

**Comment by nuclearace** [comment]
I've changed some things in the dev branch if you want to test those out.

**Comment by stevenlfg** [comment]
@nuclearace ok,thank you very much!
