### ISSUE TITLE
Allow to specify a custom subclass of WebSocket

### ISSUE THREAD

**Issue by serieuxchat** [socketio/socket.io-client-swift#419]
We would like to use the socket.io-client, but we are doing our own content encryption by implementing a subclass of WebSocket.
The SocketEngine class is final and does not allow us to override createWebsocketAndConnect() in order to instantiate our WebSocket subclass.

Would it be possible to provide means to supply a custom subclass of WebSocket to the SocketEngine?

**Comment by nuclearace** [comment]
Well, right now it's not really designed with adding a custom WebSocket. So in the time being you'll have to fork and change the code. But I'm going to look into making it so you can swap out engines/websockets/etc

**Comment by serieuxchat** [comment]
Thanks very much for the quick reply! We are currently just using Starscream plain web sockets, but being able to use socket.io would be just awesome! For now I am, indeed, planning to just fork and change the code (probably by just removing the final requirement). But being able to use a web socket subclass without modifying the code would be great (if it's done in a future release). Have a great day!

**Comment by nuclearace** [comment]
This should be possible now in a limited way by subclassing `WebSocket` and overriding things and then overriding the `connect` method on the client.
