### ISSUE TITLE
Wrapping error when importing socketIO into Objective-C project

### ISSUE THREAD

**Issue by EduardoAlberti** [socketio/socket.io-client-swift#420]
I getting the following error when compiling SocketIO into my obj-c project with XCode
`Type argument 'SecKeyRef' (aka 'OpaqueSecKeyRef *') is neither an Objective-C object nor a block type` on line `- (NSArray<SecKeyRef> * _Nonnull)publicKeyChainForTrust:(SecTrustRef _Nonnull)trust;`

I solve the issue by removing the '< SecKeyRef >' part from this file:'MyProject-Swift.h' but I don't think it is the correct way to do it.
Do you have any clue how to solve this the proper way.

**Comment by hdoom** [comment]
Prepend `@nonobjc` to the field and the method on lines 58 and 244 in SSLSecurity.swift.
Seems to be a bug in Swift (https://forums.developer.apple.com/message/47692#47692).

**Comment by EduardoAlberti** [comment]
Cool, thank you.

**Comment by dorabod2006** [comment]
`@property (nonatomic, copy) NSArray<SecKeyRef> * _Nullable pubKeys;`

How to use `@nonobjc` in that line?

@EduardoAlberti

**Comment by hdoom** [comment]
That's exactly how it works for me. Did you try _Project - Clean_ and purging your _DerivedData_ folder before rebuilding? (I'm using Xcode 7.3.1 / Swift 2.2.1 btw)

**Comment by dorabod2006** [comment]
Thanks @hdoom !
I clear my _DeivedData_ folder and build project again. It's pass _SecKeyRef's Problem_.

Now **The Xcode show error** this below.
> Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC19SocketIOClientSwift14SocketIOClient", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I run my project in _Simulator iPhone 6s Plus_
