### ISSUE TITLE
Hello! Can I use this library for Stomp ?

### ISSUE THREAD

**Issue by alexsanderkhitev** [socketio/socket.io-client-swift#423]
Hello! Can I use this library for Stomp ?

**Comment by nuclearace** [comment]
What is stomp?

**Comment by alexsanderkhitev** [comment]
@nuclearace It's the STOMP Websocket

**Comment by nuclearace** [comment]
If it's a server, no. This requires a socker.io server. You can check out Starscream if you want a straight websocket library. 

If it's a Swift websocket library, there's no way currently to switch out the default websocket.
