### ISSUE TITLE
Regular crashes in func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent) 

### ISSUE THREAD

**Issue by roma86** [socketio/socket.io-client-swift#426]
I do not know how to clarify this crash.
When app used long time and connection is not stable (many reconnection attempts) this crash happens

![screen](https://api.monosnap.com/rpc/file/download?id=Dez2gJ9VowAQSJrjsgrNtL8McdtYbl)

**Comment by nuclearace** [comment]
This would be a Starscream problem I believe.

**Comment by roma86** [comment]
@nuclearace i can not get you point. Can you explain, please?

**Comment by nuclearace** [comment]
This is a crash in the websocket dependency. https://github.com/daltoniam/Starscream

**Comment by roma86** [comment]
Thankyou. Should i redirect this issue to the repo you are linked, or this is no way to determine the problem from such raw description and one screenshot?

**Comment by nuclearace** [comment]
I am not an expert on Starscream, so it would be best to redirect it there. I follow that repo so I'll see any discussion of the issue as well.
