### ISSUE TITLE
I added socket.io-client-swift in oc project, import the Source folder after being given webscoketdemo-swift.h: 197: 12: Type argument 'SecKeyRef' (aka 'struct __SecKey *') is neither an Objective-C object nor a block type, how to solve?

### ISSUE THREAD

**Issue by jingweili911** [socketio/socket.io-client-swift#428]
I added socket.io-client-swift in oc project, import the Source folder after being given webscoketdemo-swift.h: 197: 12: Type argument 'SecKeyRef' (aka 'struct __SecKey *') is neither an Objective-C object nor a block type, how to solve?
I see that there are import Security SSLSecurity.swift。

**Comment by jingweili911** [comment]
My projects have achieved mixed oc and swift, and just add socket.io-client-swift inside the Source file will be given Type argument 'SecKeyRef' (aka 'struct __SecKey *') is neither an Objective-C object nor a block type, it is not what is missing library file, or in what setting did not do Xcode.

**Comment by nuclearace** [comment]
See https://github.com/socketio/socket.io-client-swift/issues/420
