### ISSUE TITLE
Compiler errors in xcode beta 3

### ISSUE THREAD

**Issue by orozkoinsider** [socketio/socket.io-client-swift#430]
Hi all!

I am trying the latests development version in the swift 3 branch with xcode 8 beta 3 and the project is not compiling due to an amount of differences in swift.

In previous versions I was able to correct the differences suggested by xcode. But seems that now there are even more.

I tried specifying the use legacy swift flag but doesn't work with the legacy or non legacy versions.

<img width="324" alt="captura de pantalla 2016-07-20 a las 18 51 55" src="https://cloud.githubusercontent.com/assets/645151/16995192/55c2af88-4eab-11e6-920e-205793ea2df3.png">

**Comment by nuclearace** [comment]
Are you sure you're on the Swift 3 branch?

**Comment by orozkoinsider** [comment]
Sorry @nuclearace it was my fault, I wasn't using the correct branch.

I noticed that there was a redeclaration of allowedURLCharacterSet and urlEncode, removing the files just worked for me.

Thanks!
