### ISSUE TITLE
closeConnection Socket.io related problem!

### ISSUE THREAD

**Issue by ChinaArJun** [socketio/socket.io-client-swift#431]
I returned to the IOS a sub interface on the first level, exit socket.io service, when I once again into and call socket.connect (), he will not perform the corresponding method and error:  SocketEnginePolling: Tried to do polling request when not supp

**Comment by nuclearace** [comment]
What version?

**Comment by ChinaArJun** [comment]
@nuclearace Is the latest version

**Comment by ChinaArJun** [comment]
Thank you very much for your reminder, I am mistaken, the company is currently using the old version, I found the answer in the new version, in the
CloseConnection func () {
Socket.disconnect ()
/ / Add new means
Socket.didConnect ()
}
Thank you

**Comment by nuclearace** [comment]
Can I close this then?

**Comment by ChinaArJun** [comment]
yes
