### ISSUE TITLE
Xcode 8 and carthage - fails to build

### ISSUE THREAD

**Issue by drekka** [socketio/socket.io-client-swift#432]
Just tried to build socket-ii-swift wit Xcode 8 and carthage. Got this log:

    The following build commands failed:
	Check dependencies
    (1 failure)
    warning: no umbrella header found for target 'SocketIO-iOS', module map will not be generated
    warning: no umbrella header found for target 'SocketIO-iOS', module map will not be generated
    A shell task (
        /usr/bin/xcrun xcodebuild -project /Users/derekclarkson/projects/crux-Clients/Carthage/Checkouts/socket.io-client-swift/Socket.IO-Client-Swift.xcodeproj 
            -scheme SocketIO-iOS 
            -configuration Release 
            -sdk iphoneos 
            ONLY_ACTIVE_ARCH=NO 
            BITCODE_GENERATION_MODE=bitcode 
            CODE_SIGNING_REQUIRED=NO 
            CODE_SIGN_IDENTITY= 
            CARTHAGE=YES 
            clean build
    ) failed with exit code 65:
    ** CLEAN FAILED **

**Comment by nuclearace** [comment]
Xcode 8 is still beta, so I don't know if Carthage works with it yet

**Comment by drekka** [comment]
Understand. So far, it's been working fine on another machine and a different project. However I've not tried to work with anything that involves the system Security framework.

**Comment by nuclearace** [comment]
Is this fixed by that recent merge?

**Comment by drekka** [comment]
Yep. Thanks. Look like everything is good now.

**Comment by drekka** [comment]
Nuts. It's back. I may have been mistaken about it being fixed. I'm using the development branch of socket.io-swift.

**Comment by drekka** [comment]
Okies. Switched over to the Swift3 branch and it appears to be working. I think this may be something to do with Swift 2.3 vs 3.0 or some other silliness 👍

**Comment by drekka** [comment]
Okies. I switched to the Swift3 branch and it looks like it's solved the problem. Looks like it's a Swift version issues or something similar.
