### ISSUE TITLE
Keep socket connection alive when iphone is on lock screen (UIApplicationStateInactive).

### ISSUE THREAD

**Issue by valtambok** [socketio/socket.io-client-swift#433]
Every time I lock my device and access it again, the socket logs: "The network connection was lost.". I'm assuming, that by default, the socket connection is interrupted every time the app is inactive and the device is on lock. How do you bypass this behaviour and allow the socket connection to be kept alive even when the device is on the lock screen?

**Comment by nuclearace** [comment]
iOS doesn't let you do background execution for this kind of thing.

**Comment by valtambok** [comment]
I see. Thank you @nuclearace
