### ISSUE TITLE
I just pulled the latest code and I'm now getting compilation errors

### ISSUE THREAD

**Issue by drekka** [socketio/socket.io-client-swift#434]
he following build commands failed:
	CompileC /Users/derekclarkson/Library/Developer/Xcode/DerivedData/crux-Lib-cdgilgtlztacqkacuggyhlcspzik/Build/Intermediates/crux-Lib.build/Release-iphoneos/Crux.build/Objects-normal/armv7/CRXServer.o crux/CRXServer.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/derekclarkson/projects/crux-Clients/Carthage/Checkouts/crux-lib/Carthage/Build/iOS/SocketIOClientSwift.framework/Headers/SocketIOClientSwift-
Using Xcode build from Xcode 7.3.1 and Carthage I'm getting this error from the compilation of a library that is using socket.io-swift. This has previously compiled with no problems so I'm not sure what the problem is at the moment.

    Swift.h:143:37: error: type argument 'SecKeyRef' (aka 'struct __SecKey *') is neither an Objective-C object nor a block type
    /Users/derekclarkson/projects/crux-Clients/Carthage/Checkouts/crux-lib/Carthage/Build/iOS/SocketIOClientSwift.framework/Headers/SocketIOClientSwift-Swift.h:197:12: error: type argument 'SecKeyRef' (aka 'struct __SecKey *') is neither an Objective-C object nor a block type
    /Users/derekclarkson/projects/crux-Clients/Carthage/Checkouts/crux-lib/crux/CRXServer.m:12:9: fatal error: could not build module 'SocketIOClientSwift'
    A shell task (/usr/bin/xcrun xcodebuild -project /Users/derekclarkson/projects/crux-Clients/Carthage/Checkouts/crux-lib/crux-Lib.xcodeproj -scheme crux -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
    ** BUILD FAILED **

It appears that Swift cannot understand the security key structs. The project I'm using socket.io-swift in is an Objective-C projects. So it comes in via the generated headers. I've included the security framework in both projects, but the error keep manifesting.

Any ideas?

**Comment by nuclearace** [comment]
If you take out the APPLICATION_EXTENSION_API_ONLY from the build does it work?

**Comment by nuclearace** [comment]
Does https://github.com/socketio/socket.io-client-swift/tree/development branch work?

**Comment by drekka** [comment]
Hi, nope. Develop is showing the

    type argument 'SecKeyRef' (aka 'struct __SecKey *') is neither an Objective-C object nor a block type

Error as well.

**Comment by drekka** [comment]
Looks like problem is in Source/SSLSecurity.swift line 224 where it returns an array of SecKeyRef. Fine for Swift, but doesn't translate to Objective-C because SecKeyRef is a struct and you cannot put a struct into a NSArray. Might have to wrap them in NSValues or make this code private so Objective-C cannot see it.
