### ISSUE TITLE
xcode 8 errors

### ISSUE THREAD

**Issue by acMaia** [socketio/socket.io-client-swift#437]
I just tried building my app using xcode 8 and got multiple erros in socket.io client.
Is there something I can do to build, or do I just need to wait?
![screen shot 2016-07-27 at 14 51 36](https://cloud.githubusercontent.com/assets/10814249/17177557/e07d7ece-5409-11e6-847f-4d40bc722eb1.png)

**Comment by nuclearace** [comment]
Try the swift3 branch

**Comment by parasdaff** [comment]
I have tried using swift3 branch but still facing issues.
![screen shot 2016-08-03 at 2 40 23 pm](https://cloud.githubusercontent.com/assets/20792433/17360267/595796ee-5988-11e6-8eb1-a8565ba4a236.png)

**Comment by nuclearace** [comment]
I'm not sure, if you have Xcode setup right, and are on the swift3 branch, it should compile.

**Comment by parasdaff** [comment]
@nuclearace  i am using the same branch, here is the pod i am using to pull from branch swift3
pod 'Socket.IO-Client-Swift',:git =>'https://github.com/socketio/socket.io-client-swift', :branch => 'swift3'

**Comment by nuclearace** [comment]
I've never tried to use CocoaPods with betas, could be something related to that.

**Comment by jamescahall** [comment]
I'm getting 33 errors and 4 warnings myself and can't compile using the .swift files directly (no cocoa pods).

<img width="290" alt="screen shot 2016-08-15 at 2 20 45 pm" src="https://cloud.githubusercontent.com/assets/1072563/17680128/921c97b2-62f3-11e6-95c5-b8dd3238d91a.png">
<img width="289" alt="screen shot 2016-08-15 at 2 21 02 pm" src="https://cloud.githubusercontent.com/assets/1072563/17680129/92361624-62f3-11e6-8d63-fd24a0eba160.png">

**Comment by nuclearace** [comment]
Are you on the swift3 branch

**Comment by jamescahall** [comment]
Yes

**Comment by jamescahall** [comment]
Issue compiling in beta 6

**Comment by nuclearace** [comment]
Oh I haven't updated it for that beta yet

**Comment by nuclearace** [comment]
Downloading it now

**Comment by nuclearace** [comment]
This might take awhile, swiftc seems to want to segfault on something now

**Comment by Pourias** [comment]
I have the same problem here.. (I'm using SWIFT3 branch Xcode8 IOS10) but keep getting all the errors which I think is Swift3 related.  Loosk like its around error handling
![screen shot 2016-08-19 at 12 50 42 pm](https://cloud.githubusercontent.com/assets/11410911/17822395/d281afa2-660b-11e6-8ade-0a7709040974.png)

**Comment by nuclearace** [comment]
I don't think your project is setup right.

**Comment by jamescahall** [comment]
When do you expect to have the compilation issues for Beta 6 resolved?  We'd like to start prepping for iOS 10 release.

**Comment by nuclearace** [comment]
It should work for the most part, except for websocket SSL. 

https://github.com/socketio/socket.io-client-swift/blob/swift3/Source/WebSocket.swift#L310 Crashes swiftc, so you'll have to wait for betaX for them to fix that.

**Comment by nuclearace** [comment]
I also noticed that JSONerialization is now turning Booleans into 0's and 1's, so some of the tests fail now. But until I read somewhere that this was intentional, and won't cause problems for sending json, I would be wary.

**Comment by nuclearace** [comment]
On that note, it might be related to https://github.com/apple/swift/pull/4366

**Comment by jamescahall** [comment]
Any update?  We'd like to be able to prep for the next iOS release and have had to remove this library until it's fixed.

**Comment by nuclearace** [comment]
The swift3 branch should compile on beta6.

**Comment by minoue10** [comment]
Sooo Xcode 8 GM is out today 😬  When can we expect this to be fixed and merged? I'd prefer not having to refer to a branch for this anymore.

**Comment by nuclearace** [comment]
Depends, is swift 3 going to be released as default on Xcode 8? What about Swift 2.3?

**Comment by minoue10** [comment]
@nuclearace  from https://developer.apple.com/swift/blog/?id=36
> Swift 3 is the primary development language supported within Xcode 8

**Comment by williamgp** [comment]
Not compiling in Xcode 8 GM- getting a few of these errors:
Passing non-escaping parameter 'callback' to function expecting an @escaping closure

**Comment by nuclearace** [comment]
@minoue10 Then when Xcode is released publicly it'll be merged into master and a new version will come out.

**Comment by jamescahall** [comment]
Developers need to submit apps before public versions are out.  The GM is basically the public version.

**Comment by minoue10** [comment]
@nuclearace The GM for Xcode 8 was released yesterday: https://developer.apple.com/xcode/
Just wondering when we can expect a new version :) Love your library, I'd just like to be able to test my app on Xcode 8 and on iOS 10 simulators as soon as possible, since iOS 10 will be released to the public next Tuesday (9/13).

**Comment by nuclearace** [comment]
I'll also have to check and see if CocoaPods supports it yet. I'd hate to merge it now and then find out that I have to do some annoying stuff to tell CocoaPods where to find the right toolchain to build it.

**Comment by nuclearace** [comment]
And another minor thing is that I'll have to turn off travis-ci until they update. But I would have to do that regardless, last time it took them about a week or two to update to Xcode.

**Comment by nuclearace** [comment]
Looks like they need to update xctools for Xcode8.

**Comment by Lukafin** [comment]
I also can't build my project with SocketIO in Xcode 8 GM.

**Comment by nuclearace** [comment]
Are you on the development branch? I'll be dropping a new version when Xcode 8 is release proper.

**Comment by Lukafin** [comment]
No i am on master branch (using just pod 'Socket.IO-Client-Swift').
Should i try with dev. branch?

**Comment by minoue10** [comment]
@nuclearace what do you mean by 
>when Xcode 8 is released proper.
?
Xcode 8 is already out on the Mac App Store, so that's as proper as it's going to get, I think.

Also, Xcode 7 isn't compatible with iOS 10 devices (and iOS10 was released today), so I'd really like to move to Xcode 8 as soon as possible.

**Comment by nuclearace** [comment]
When I wrote that it wasn't out yet. I'm downloading it now.

**Comment by williamgp** [comment]
At what point will the Swift 3 branch become the Master?

**Comment by Lukafin** [comment]
Swift 3 branch doesn't exist anymore.

**Comment by clOudbb** [comment]
Plz tell me , Should I use which branch in xcode 8 release version? thxxxx😁

**Comment by nuclearace** [comment]
Swift 3 code is in development now. There'll probably be a new release today

**Comment by nuclearace** [comment]
As I suspected would happen, CocoaPods sucks and is broken for Xcode 8.

**Comment by nuclearace** [comment]
Figured out how to kerjiggle CocoaPods into pushing the new version.

**Comment by Lukafin** [comment]
Have you pushed your latest changes to dev. branch yet?

**Comment by nuclearace** [comment]
Yes

**Comment by Lukafin** [comment]
I tried with the latest code and i get "module file was created by an older version of the compiler, rebuild and try again".  So the error "No such module SocketIOClientSwift" is gone but i have a new one. Any idea?

**Comment by nuclearace** [comment]
What Xcode are you on? 

Also I had to use CocoaPods 1.1.0rc2. And it still messed up git remotes... I can't wait till the swift package manager is mature enough where I can drop CocoaPods.

**Comment by Lukafin** [comment]
Xcode 8 (final). 
I tried now with  CocoaPods 1.1.0rc2 and i am stuck in the middle of "pod update" (takes forever). Will try again later. 
And yes, i agree with you and cant wait until swift package manager is included in Xcode.

**Comment by harry1064** [comment]
I have update the SocketIOClientSwift to 8.0.0 and using Xcode 8 when i build the project i got this
![screen shot 2016-09-16 at 5 13 49 pm](https://cloud.githubusercontent.com/assets/6297435/18584893/453a2eb2-7c31-11e6-9c72-1d1061941599.png)

**Comment by DrBeak1** [comment]
Just tried to switch today (xcode 8, cocoapods 1.1.0rc2, socketio 8.0.1) and getting 36 errors.
<img width="507" alt="screen shot 2016-09-20 at 1 34 35 pm" src="https://cloud.githubusercontent.com/assets/1033734/18688327/b5d90314-7f38-11e6-9d0d-9b206f0c8d78.png">

Not sure what I did wrong ... I've read through this thread and many others. Nothing seems to work.

**Comment by nuclearace** [comment]
If you want to use Swift 2.3 you'll have to use the swift2.3 branch.

**Comment by vikiBenHaim1** [comment]
Hi, 
I downloaded the new Socket IO Client Swift version , and added the changes according the documentation and now it's worked.
Thanks.

**Comment by DrBeak1** [comment]
@vikiBenHaim1 you were able to get things working using swift 3.0 (aka, master)?

**Comment by brianfang** [comment]
@vikiBenHaim1 What is documentation you referred so that you get things done ? thanks.

**Comment by ErMaheshwari** [comment]
Hi I am using latest socket-io for swift 3.0 , I am able to connect my local host, but when i am emiting the message , its not emiting.
