### ISSUE TITLE
Cannot get it working with SSL 

### ISSUE THREAD

**Issue by udayvatturi** [socketio/socket.io-client-swift#440]
This library is not working with SSL. 
nsurlsession/nsurlconnection http load failed (kcfstreamerrordomainssl, -9813) error in ios. 
Without SSL its working perfectly. 

Not sure its an issue.

**Comment by nuclearace** [comment]
Your cert might not be compliant to Apple's standards.

**Comment by lzantal** [comment]
Got this same issue when I started on my project this week. 
You can't use self signed certificate with iOS. Even setting setting 
"App Transport Security Settings" in Info.plist doesn't work for some reason. I just grabbed a wildcard ssl and it runs fine now.

**Comment by udayvatturi** [comment]
Thank You. I will try that.
