### ISSUE TITLE
(SIGTRAP) TRAP_BRKPT

### ISSUE THREAD

**Issue by alexvimodev** [socketio/socket.io-client-swift#444]
0	libobjc.A.dylib 0x398f28e0 objc_crashlog() + 118
1	libobjc.A.dylib 0x399013c7 weak_register_no_lock + 180
2	libobjc.A.dylib 0x399016ff objc_storeWeak + 108
!	3	TestApp 0x001537d0 _TFC4TestApp9WebSocketP33_F90942689E0E867729C78BA17580A3B517processRawMessagefTGSPVs5UInt8_9bufferLenSi_T_ (WebSocket.swift:743)
4	TestApp 0x00150a04 _TFC4TestApp9WebSocketP33_F90942689E0E867729C78BA17580A3B512dequeueInputfT_T_ (WebSocket.swift:411)
5	TestApp 0x0015a2c4 _TTSf4g_n_n___TFC4TestApp9WebSocket6streamfTCSo8NSStream11handleEventVSC13NSStreamEvent_T_ (WebSocket.swift:391)
6	TestApp 0x0015086c _TToFC4TestApp9WebSocket6streamfTCSo8NSStream11handleEventVSC13NSStreamEvent_T_ (WebSocket.swift:0)
7	CoreFoundation 0x2f100a4b _signalEventSync + 116
8	CoreFoundation 0x2f141fab ___signalEventQueue_block_invoke + 12
9	libdispatch.dylib 0x39dda833 _dispatch_call_block_and_release + 8
10	libdispatch.dylib 0x39ddaded _dispatch_queue_drain$VARIANT$up + 442
11	libdispatch.dylib 0x39ddb297 _dispatch_queue_invoke$VARIANT$up + 36
12	libdispatch.dylib 0x39ded88d _dispatch_root_queue_drain + 74
13	libdispatch.dylib 0x39dedb21 _dispatch_worker_thread2 + 54
14	libsystem_pthread.dylib 0x39f1cbd3 _pthread_wqthread + 296
15	libsystem_pthread.dylib 0x39f1ca98 start_wqthread + 6

**Comment by nuclearace** [comment]
WebSocket problem.

**Comment by alexvimodev** [comment]
Is there any option to resolve this problem ? Or can you give me some input to debug and fix it from my end ?

**Comment by nuclearace** [comment]
I don't develop the websocket library, so I'm not really sure. If you can come up with a way to reproduce it 95% of the time I might be able to look at it.

**Comment by alexvimodev** [comment]
The problem is; it is not happening in my phones... :(
If I found, I will update you..
