### ISSUE TITLE
SSL pinning not working for me

### ISSUE THREAD

**Issue by christianlanz** [socketio/socket.io-client-swift#445]
I'm trying to get ssl pinning up and running, but that does not work for me.

``` swift
// Initializing socket io client
let socket = SocketIOClient(socketURL: NSURL(string: "https://my.app.tld")!, options: [
  .Log(false),
  .Secure(true),
  .Security(SSLSecurity())
])
```

I placed the certificate in DER format inside the main.bundle. When debugging everything looks good, the client finds the certificate file and loads it. But if I intercept the connection with Charles (https://www.charlesproxy.com/) everything works fine - but it shouldn't as the certificate should be pinned.

I also tried CER / PEM format of the certificate, but then it instantly crashes because the binary data can not be converted to `SecCertificateCreateWithData`:

``` swift
/* ... */
collect.append(SecCertificateCreateWithData(nil,cert)!)
/* ... */
```

The certificate file is ok because I also use it with Alamofire and it works fine.

What am I doing wrong?

**Comment by nuclearace** [comment]
You'll probably have to configure your SSLSecurity correctly. Which I don't know how to do, since I've never done this.

**Comment by christianlanz** [comment]
There is not much to configure with `SSLSecurity`. The only parameter that can be supplied to the constructor is `usePublicKeys` - which is by default `false`.

```swift
public convenience init(usePublicKeys: Bool = false) { /*... */ }
```

But I don't want to use public keys, I want to use certificates. So I guess `usePublicKeys` should be `false`.

**Comment by nuclearace** [comment]
There's a property called pubKeys where you put your keys.

**Comment by bot2600** [comment]
Have you verified it is connecting with web sockets? From what I see if it stays polling SSLSecurity is not called. I haven't tried loading the certs from my bundle, but I have built them passing NSData to SSLCert and passing that array to SSLSecurity and had it work fine.

**Comment by 2h4u** [comment]
I have the same problem as @christianlanz.

As you can see I pass the cert manually to the SSLSecurity constructor and everything works fine. But as soon as I try to intercept the connection (perform an man in the middle attack) with an SSL Proxy, socketio acceps the certificate from the SSL-proxy and I can see the everyting in plaintext -> ssl pinning isnt working.

Here is my code:

      let paths = Set([".der", ".DER"].map { fileExtension in
        Bundle.main.paths(forResourcesOfType: fileExtension, inDirectory: nil)
        }.joined())

      var certs = [SSLCert]()

      for path in paths {
        if let certificateData = try? Data(contentsOf: URL(fileURLWithPath: path)) as Data {
          let certificate = SSLCert(data: certificateData)
          certs.add(certificate)
        }
      }

      socket = SocketIOClient(socketURL: URL(string: "https://examplehost.com")!, config: [
        .log(true),
        .secure(true),
        .forceNew(true),
        .security(SSLSecurity(certs: certs, usePublicKeys: false))
        ])


Is there a flag that I need to set or is there something else missing?

**Comment by irakliitavadze** [comment]
@christianlanz did you resolve your problem?

**Comment by christianlanz** [comment]
@irakliitavadze Yeah, I got it working with this code:

```
socket = SocketIOClient(socketURL: URL(string: "<url here>")!, config: [
        .log(false),
        .secure(true),
        .forceNew(true),
        .forceWebsockets(true), // SSL pinning works only on forcedWebsockets. Do not set it to false and do not remove this line!
        .security(SSLSecurity(usePublicKeys: true))
        ])
```

**Comment by satishVekariya** [comment]
same problem, none of solution work!!!1
