### ISSUE TITLE
SEGV_MAPERR: App crashes

### ISSUE THREAD

**Issue by alexvimodev** [socketio/socket.io-client-swift#446]
Please help me to fix this issue.

iOS: 9.3.3
Model: iPhone 7,2

0	libobjc.A.dylib 0x0000000182601b90 objc_msgSend + 12
!	1	TestApp 0x00000001001a7eec TestApp.WebSocket.((dequeueWrite in _F90942689E0E867729C78BA17580A3B5) (__ObjC.NSData, code : TestApp.WebSocket.OpCode) -> ()).(closure #1) (WebSocket.swift:776)
2	Foundation 0x0000000183944540 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 12
3	Foundation 0x0000000183896870 -[NSBlockOperation main] + 92
4	Foundation 0x0000000183886e48 -[__NSOperationInternal _start:] + 600
5	Foundation 0x0000000183946934 __NSOQSchedule_f + 220
6	libdispatch.dylib 0x00000001829d547c _dispatch_client_callout + 12
7	libdispatch.dylib 0x00000001829e14c0 _dispatch_queue_drain + 860
8	libdispatch.dylib 0x00000001829d8f80 _dispatch_queue_invoke + 460
9	libdispatch.dylib 0x00000001829e3390 _dispatch_root_queue_drain + 724
10	libdispatch.dylib 0x00000001829e30b0 _dispatch_worker_thread3 + 108
11	libsystem_pthread.dylib 0x0000000182bed470 _pthread_wqthread + 1088
12	libsystem_pthread.dylib 0x0000000182bed020 start_wqthread + 0

**Comment by nuclearace** [comment]
WebSocket problem

**Comment by alexvimodev** [comment]
Is there any option to resolve this problem ? Or can you give me some input to debug and fix it from my end ?
