### ISSUE TITLE
App crashes when I receive huge data from server

### ISSUE THREAD

**Issue by alexvimodev** [socketio/socket.io-client-swift#448]
Hi,

Today I have updated the socketio library for iPhone. My app is crashing whenever I receive huge data from server. Please check the attached screenshots for more information.

Now, I have added some limitation for the response data size.

Regards,
Alex.

![screen shot 2016-08-09 at 11 58 21 am](https://cloud.githubusercontent.com/assets/13148573/17506764/2b9d271e-5e29-11e6-8fb5-b6dc71d474f0.png)
![screen shot 2016-08-09 at 12 01 27 pm](https://cloud.githubusercontent.com/assets/13148573/17506765/2baf9322-5e29-11e6-849c-7c3b9fe8c1fe.png)

**Comment by nuclearace** [comment]
Yeah, are you on the current version? I think this is a known issue with the WebSocket library, but I thought it was fixed.

**Comment by alexvimodev** [comment]
Yes... Today only I downloaded the source from github.
