### ISSUE TITLE
Forcing websockets.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-swift#449]
Hi,

I have a question regarding connecting speed. Since Socket.IO defaults to long polling and upgrades to web sockets if available -- does setting ForceWebsockets to true upon calling connect speed up? Any downside setting ForceWebsockets to true?

Thanks!

**Comment by nuclearace** [comment]
I don't know if it increases speed of connect, socket.io starts sending stuff as soon as the polling is up, there's a slight pause during the upgrade. The reason it uses polling first is because some firewalls/proxies block websockets. So polling lets socket.io work behind those.

**Comment by 18756035271** [comment]
How to set up cookie in objective
