### ISSUE TITLE
Single swift client creates excessive sockets on server in bad network.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-swift#450]
I've seen this a few times: in a poor network, the socket.io swift client could create multiple sockets (around 10) on the server. Most of the sockets don't last long though -- they die out one by one soon except a single one which is the "active" one.

I haven't investigated this well enough to find the real cause yet. But my guess is: the client sends a request to connect, and doesn't receive a response in time due to poor network, then it sends another request to connect, and so on. Some of the requests actually arrive at the server, and create sockets on it, it's just that the server's responses don't arrive at the client.

For now, we only have a few clients connected to the server. And the server seems able to handle such a scenario without a problem. But it feels glitchy, and could cause some trouble for the server if it's handling thousands of clients, and some of them "burst" create multiple sockets like mentioned above.

Does my guess make sense to you? If so, what are your thoughts on the possible fix?

Thanks!

**Comment by nuclearace** [comment]
Are these from the WebSocket? If it's not, there's probably little I could do since I use NSURLSession for polling.

**Comment by hifall** [comment]
Would a backoff algorithm help? That is, if a reconnect fails, increase the wait time before trying to reconnect again. This would reduce "socket congestion" on the server.

**Comment by hifall** [comment]
@nuclearace, what you do mean by "Are these from the WebSocket?"

I am using websockets, rather than long polling.

**Comment by nuclearace** [comment]
If you're doing `.ForceWebsockets(true)` then they are from the WebSocket. There's already a `.ReconnectWait` option for the socket. Also you can probably override the OS's TCP connect timeout max.

**Comment by hifall** [comment]
I am not using .ForceWebsockets(true).

Also, I have already used .ReconnectWait(25) to mitigate this issue on our end. It turned out that the ~10 sockets came down to ~5 at the moment.

**Comment by nuclearace** [comment]
If you don't use `.ForceWebsockets` then it's probably starting with polling and then upgrading to websockets.
