### ISSUE TITLE
Re-using socket after seeing NSPOSIXErrorDomain, code: 57.

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-swift#452]
In the following scenario, a socket.io-client-swift integrated app creates an extra socket upon seeing an NSPOSIXErrorDomain error:

1 start the app, then open a stream to connect to the socket.io server, and a socket is created. Let's call this socket A;
2 the app goes to background for 1 minute. This time span is long enough for me to reproduce this issue. Your mileage might vary;
3 bring the app to foreground again;
4 now the OS finds that the stream is idle long enough, and calls the NSStreamDelegate's stream method with NSPOSIXErrorDomain error, code 57, and message "The operation couldn’t be completed. Socket is not connected";
5 the stream method calls disconnectStream, which in turn calls SocketIOClient.tryReconnectWithReason, which calls connect() to create another socket on the server. Let's call this socket B;
6 now we have 2 sockets on the server, A and B, created by the same app. But socket A will soon be detected by the server to be dead, since the stream has been disconnected, and no heartbeat is sent to the server anymore. Socket A will be removed by the server, while socket B will be the active socket responsible for signalling for the app.
7 each time this background/foreground business happens, an extra socket is created. If one repeats this process multiple times, which is quite typical for an average app user, multiple extra sockets are created.

Now my question is: is it possible to keep using socket A in such a scenario? That would save creating another socket. I have tested mobile Safari, and it did NOT seem that it created an extra socket on the server, after being idle long enough so that the original socket was disconnected. So it seems to me that mobile Safari's behaviour is better with regard to socket use.

Thanks!

**Comment by nuclearace** [comment]
This would be a question for https://github.com/daltoniam/Starscream. I don't maintain the WebSocket dependency.
