### ISSUE TITLE
Why I can't use SSLSecurity successfully?

### ISSUE THREAD

**Issue by CheerCc** [socketio/socket.io-client-swift#457]
Hi,I use Security(SSLSecurity) like this
`NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"cloud.schideron.com.cn" ofType:@"key"];
    NSData *certData = [NSData dataWithContentsOfFile:cerPath];
    SSLCert *cert = [[SSLCert alloc] initWithData:certData];
    SSLSecurity *security = [[SSLSecurity alloc] initWithCerts:@[cert] usePublicKeys:YES];`

The server IP is `https://192.168.10.131:5001`.
But I can't connect to server, do I need to add `@"Secure" : @YES`? Or do I need to add some property in the Info.plist about NSAppTransportSecurity?
The log is `LOG SocketIOClient: Handling event: error with data: (
    "Engine URLSession became invalid"
)`

**Comment by nuclearace** [comment]
I don't think you want to set `usePublicKeys` to true. Have you tried setting that to false?

**Comment by CheerCc** [comment]
yeah.I try to set usePublicKeys to NO.It still not connect to server.The log is `CFNetwork SSLHandshake failed (-9807)`.So I think maybe the problem that  the version of  SSL is not same with server.In your library the SSL version is ?

**Comment by CheerCc** [comment]
Now my option is like this 
`    NSString *cerPath = [[NSBundle mainBundle] pathForResource:@"cloud.schideron.com.cn" ofType:@"cer"];
    NSData *certData = [NSData dataWithContentsOfFile:cerPath];
    SSLCert *cert = [[SSLCert alloc] initWithData:certData];
    SSLSecurity *security = [[SSLSecurity alloc] initWithCerts:@[cert] usePublicKeys:NO];
    NSDictionary *socketOptionsDict = @{@"forceNew" : @YES,
                                        @"reconnects": @YES,
                                        @"forceWebsockets" : @YES,
                                        @"Security" : security,
                                        @"log" : @YES
                                        };`.
In the WebSocket.swift, I see only the func `public func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent)` has call the property `security`.I guess whether my connection still without SSL?

**Comment by nuclearace** [comment]
`CFNetwork SSLHandshake failed` Probably means that you're doing something wrong. You have to make sure that everything is done according to Apple's security specs, or it won't work. SSL stuff is done using Apple's frameworks.

**Comment by monobono** [comment]
Just to be sure: Option name keys need to be in cammelCase eg. 'security' instead of 'Security'

**Comment by wxwlcp** [comment]
@AlexCai21 Did you solve this problem？
