### ISSUE TITLE
Socket emit is not working

### ISSUE THREAD

**Issue by suhair** [socketio/socket.io-client-swift#458]
I use the emit method as follows. If i remove the socket.connect() from the sendTextMessage method then emit is not triggered on the server side. If connect is called inside the method it works for sometime and then stops. sendTextMessage is triggered by button tap. Any help is appreciated. 
    
```
class SocketIOManager: NSObject {
    static let sharedImstance = SocketIOManager()
    var socket: SocketIOClient = SocketIOClient(socketURL: NSURL(string: "http://localhost:3030")!, options: [.Log(false), .ForcePolling(true)])
    
    
    override init() {
        super.init()
    }
    
    
    func establishConnection(){
        socket.connect()
        
        
        socket.on("hello") { (data, ack) in
            print("Hello is triggered", data);
        }
        
        sendTextMessage()
    }
    
    func closeConnection(){
        socket.disconnect()
    }
    
    
    func sendTextMessage(){
        socket.connect()
        socket.emit("connectUser", "Dummy data")
        
    }
    
    
}
```
In the above code connect is triggered twice and hence two sockets are connected with the server and it seems wrong to me. Please help me. Thanks.

**Comment by nuclearace** [comment]
There's a reason there's a `connect` event that gets fired. You never want to call `connect()` on a socket twice. You also never want to try and emit before a socket is connected. Pretty much all methods on the client are async. So once you call `connect()` it'll go on its way.  So you're probably hitting https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClient.swift#L222

You want to do

```swift
socket.on("connect") {data, ack in
    // Doing any sending that needs to be done
}
```

**Comment by suhair** [comment]
@nuclearace  thanks for quick response. `sendTextMessage` method is called way after the connection is established in response to a button tap so I can't wrap the emit method inside the on handler, right?. I am not hitting the not connected error without wrapping it on connect handler. 

```
func sendTextMessage(){
        socket.emit("connectUser", "Dummy data")
}
```

This does not trigger the emit on the server. I checked the same event through browser and it works fine. Thanks again for reply.

**Comment by nuclearace** [comment]
You'll need to establish the connection before they could ever hit the button to send the message in that case. Your establishConnection method shouldn't be calling `sendTextMessage()`, because connect is async, so it'll more likely than not not be connected when it tries to send.

**Comment by suhair** [comment]
That's done for debugging and ignore it. I am establishing connection inside the app delegate as follows.


 ```
   func applicationDidBecomeActive(application: UIApplication) {
        
        SocketIOManager.sharedImstance.establishConnection()
        
        
    }
```

I am logging the connection and disconnection events on the server. Server shows connection established and then i trigger the button to emit as above. It does not show disconnection until i move the app to background when i disconnect the socket so i think the connection is already active when the sendTextMessage and emit is triggered.

**Comment by nuclearace** [comment]
So does it not emit when you push the button? Have you added handlers for `error` or `disconnect`

**Comment by suhair** [comment]
Have not added the handlers for error and disconnect on the iOS. I will try it now. Just tried to move the code from app delegate to viewDidLoad of the view controller and it works as expected triggering the emt event on the server.

```
override func viewDidLoad() {
        super.viewDidLoad()
        SocketIOManager.sharedInstance.establishConnection()
 }
```

**Comment by suhair** [comment]
When I establish connection inside app delegate i get the following error after the app is idle for some time.

```
Communications error: <OS_xpc_error: <error: 0x107ff7b40> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x107ff7ef0> { length = 22, contents = "Connection interrupted" }
}>
```

This does not happens when the connection is established inside viewDidLoad.

**Comment by nuclearace** [comment]
Okay, yeah I've never tried connecting from an AppDelegate.

**Comment by suhair** [comment]
Thanks @nuclearace.
