### ISSUE TITLE
Capture self in acknowledgement callback

### ISSUE THREAD

**Issue by ahallora** [socketio/socket.io-client-swift#46]
Hi!

First of all, thank you so much for releasing the official socket.io iOS framework. I was waiting long and hard for this baby! :smiley:   

I have a somewhat finished app already, written in objective-c, so I'm using your framework by simply importing the swift-files with (which seems to working quite beautifully):
```objective-c
#import <swift_objc-Swift.h> // my testbed project is called "swift-objc"
```

However, I have problems addressing the "self" (= viewcontroller) in the completion handler of emits with acknowledgement. My testbed code looks like this:
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];    
    SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:1337" options:nil];
    [socket connect]; // this is needed to invoke my "connect" handler - btw, not specified in the example code atm   

    // simple connect and emit back
    [socket on: @"connect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {        

        // but emit back with an acknowledgement of receipt
        [socket emitWithAckObjc:@"ackack" withItems:@[@"hello world"]](10, ^(NSArray* data) {
            NSLog(@"Got ack: %@", data);

            // now update my label - but I can't because of a "EXC_BAD_ACCESS" error
            self.mylabel.text = @"self is lost?";
        }); 
    }];
}
```

I've tried:
- specifying self as a weakSelf before invoking the socket blocks
- calling a method instead of writing directly to a ui control
- setting viewcontroller as strong self in completion callback

None of them seems to work. My node server is working correctly and is not the cause to any of the problems I'm experiencing.

Xcode debugs/breaks to this line in https://github.com/socketio/socket.io-client-swift/blob/master/SwiftIO/SocketAckMap.swift#L36 with the error message:
> Thread 1: EXC_BAD_ACCESS (code=2, address=0x7b0b4034)

Do you have any suggestions how to capture self?

**Comment by nuclearace** [comment]
Thanks for the good issue report.

I don't really know Objective-C well, but from your test code it looks like you're creating a local variable named socket and working with that. Once `socket` goes out of scope it should be released.

Does this happen if you make the socket a member of the viewcontroller?

I usually have the socket be a member of the viewcontroller, and then do things like in the `viewDidLoad` https://github.com/nuclearace/socket.io-client-swift-example/blob/master/TicTacIOiOS/ViewController.swift#L28

**Comment by nuclearace** [comment]
Also, I should note I have no idea if Objective-C blocks are as powerful as Swift closures.

**Comment by ahallora** [comment]
Thanks for a quick reply - I will look into it and report my findings. :smile: 

I know less swift than objective-c so I have my work cut out for me. :smile:

**Comment by nuclearace** [comment]
Hm, actually I'm getting this too. From Objective-C

**Comment by nuclearace** [comment]
What's weird is this seems to work in Swift.

**Comment by nuclearace** [comment]
Also the code it's highlighting isn't the problem.

**Comment by nuclearace** [comment]
Swift 1.2 seems to get the line right, but I still can't figure out why it's happening

**Comment by nuclearace** [comment]
What's even weirder is that it doesn't seem to happen when I do something crazy like

```objective-c
SocketIOClient* gSocket;

void testSocketAck()
{
    gSocket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:8080" options:nil];
    
    [gSocket on: @"connect" callback: ^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"connected");
        [gSocket emitWithAckObjc:@"ack" withItems:@[@1]](1, ^(NSArray* data) {
            NSLog(@"Got ack");
            NSLog(@"%@", data[0]);
            [gSocket emitObjc:@"test" withItems:@[]];
        });
    }];
    
    [gSocket connect];
}
```

**Comment by nuclearace** [comment]
Ugh, I found a really ugly workaround.

If you have a global variable that references your object, and then use that inside blocks it works.

**Comment by nuclearace** [comment]
@ahallora Actually I think I've found a solution

```objective-c
- (void) sendMessage {
    __block int i;
    
    [[self socket] emitWithAckObjc:@"ack" withItems:@[@1]](1, [^(NSArray* data) {
        NSLog(@"Got ack");
        
        [[self socket] emitObjc:@"test" withItems:@[]];
        i = 1 + 1;
    } copy]);
}
```

**Comment by nuclearace** [comment]
This is actually a problem with Swift-Objective-C compatibility. I worked out a small demo here.

https://gist.github.com/nuclearace/5d3d1737002f12be6109

**Comment by ahallora** [comment]
Awesome, it works! Thank you so much! :+1: :smiley:
