### ISSUE TITLE
Swift 3 branch not compiling 

### ISSUE THREAD

**Issue by Pourias** [socketio/socket.io-client-swift#462]
I have had different issues with getting the Swift 3 branch to compile.
I have made some change mainly on WebSocket.swift file.

Please take a look at the attached file and feel free to update the swift3 branch if you think the changes are correct.

Thank you for a great work on socketio for swift.

[WebSocket.swift.zip](https://github.com/socketio/socket.io-client-swift/files/428433/WebSocket.swift.zip)

**Comment by nuclearace** [comment]
I've already made a lot of those changes I believe.
