### ISSUE TITLE
Error when using @import SocketIOClientSwift;

### ISSUE THREAD

**Issue by mavris** [socketio/socket.io-client-swift#464]
When using: 
@import SocketIOClientSwift;
I am getting the error: "Module SocketIOClientSwift" not found".
I installed SocketIO with CocoaPods

**Comment by nuclearace** [comment]
Has it been built yet?

**Comment by mavris** [comment]
No.
I did something wrong or it's something with cocoapods?

**Comment by nuclearace** [comment]
It's been awhile since I've used cocoapods. But I would double check that you aren't doing something weird.

**Comment by EddieLukeAtmey** [comment]
Hi, I just upgrade to xcode 8 and using socketIO 8 (latest) and this is happening. Can you help me please (I use cocoapods). How did you fix this?
