### ISSUE TITLE
Pattern for repeat emit?

### ISSUE THREAD

**Issue by hifall** [socketio/socket.io-client-swift#467]
We are building an app where  we emit an critical event and must make sure the event is delivered in order for the app to function properly. If the event is not delivered, we need to repeat emitting until the number of retries have reached a specified upper limit.

What's a good pattern to implement such a function?

**Comment by nuclearace** [comment]
You could use acks if you have control over the server and could write it to use them. Otherwise I'm not sure of a good way.
