### ISSUE TITLE
Possibility to reconnect with a different URL

### ISSUE THREAD

**Issue by rmnblm** [socketio/socket.io-client-swift#470]
I am building an app where it is possible to change the Socket URL at runtime. A few ViewControllers have registered callbacks on different socket events. The problem here is obvious: When I'm creating a new SocketIOClient instance, the `SocketEventHandler` 'handlers' in `SocketIOClient.swift` is empty and all my callbacks are gone. There should be the possibility to reconnect to a different URL while preserving all handlers. Am I the only one who's in need for this or is there already a good workaround? 🙈

There could be two different solutions I could think of
- Offer a method called `connect(newSocketURL: URL)` which sets the socketURL instance variable and call `addEngine().connect()` to start a new engine with the new URL
- Offer a method to transfer the current `[SocketEventHandler]` array called `handlers` from one socket to another to preserve these handlers

**Comment by nuclearace** [comment]
Or you could have a method that just adds your handlers for a socket. I don't like the idea of reusing sockets, I didn't originally build it to do that, it was tacked on later, I don't think it's that great.

`func addHandlersForSocket(socket: SocketIOClient)`

**Comment by rmnblm** [comment]
Reusing sockets isn't that great, you're right, but hopefully you understand the problem I'm facing here. I don't really understand your suggestion, could you provide me some implementation details on how you'd do it? ☺️

**Comment by LeonardoRick** [comment]
Hi, I'm willing to reconnect to a different url too from my client. rebuild all definition of the handlers will be a huge cost to me. Is there a way to do that nowadays?
