### ISSUE TITLE
Examples on how to use binary from an iOS client to a Node.js server

### ISSUE THREAD

**Issue by rmnblm** [socketio/socket.io-client-swift#471]
As a newbie with socket.io in Swift I'm totally missing some examples to send an image or even stream the whole display from an iOS device to a Node.js server. Can anybody help? 😌

**Comment by nuclearace** [comment]
Google how to turn a UIImage to NSData, or if it's already on the filesystem you can just get the data directly. Then you can just emit it.

**Comment by rmnblm** [comment]
I was able to send and receive the buffer from an iOS Device to a Node.js server and then displaying it in a React.js component. Maybe someone needs these snippets in the future and will be grateful.

**iOS Client**
Method body to create a UIImage
```
UIGraphicsBeginImageContext(CGSize(width: bounds.size.width, height: bounds.size.height))
layer.render(in: UIGraphicsGetCurrentContext()!)
let image: UIImage = UIGraphicsGetImageFromCurrentImageContext()!
UIGraphicsEndImageContext()
return image
```
Method body to create a Data object
```
let image = canvasView.getImage() // calling above method
let data = UIImageJPEGRepresentation(image, 1.0)
SocketIOManager.sharedInstance.sendDisplayStream(data!)
```
Emit the data
```
func sendDisplayStream(_ data: Data) {
    socket?.emit("deviceDisplayStream", data)
}
```

**Node.js server**
Receive the data and forward it to a specified room
```
socket.on('deviceDisplayStream', buffer => {
    server.in('room1').emit('deviceDisplayStream', buffer);
});
```

**React Component**
Receive the data and create a local URL to reference
```
SocketClient.on('deviceDisplayStream', buffer => {
      console.log(buffer);
      const blob = new Blob([buffer], { type: 'image/jpeg' });
      const urlCreator = window.URL || window.webkitURL;
      const imageUrl = urlCreator.createObjectURL(blob);
      this.setState({ url: imageUrl });
});
```
Render method to display the image
```
render() {
    return (
      <div>
        <img src={this.state.url} alt="test" />
      </div>
    );
  }
```
