### ISSUE TITLE
Some Wrong about socket.io

### ISSUE THREAD

**Issue by xclidongbo** [socketio/socket.io-client-swift#476]
[http://bugly.qq.com/share/VdApuy](url)

**Comment by nuclearace** [comment]
What

**Comment by xclidongbo** [comment]
2016-08-31 15:07:31.139 iphoneLive[3763:1005694] LOG SocketIOClient: Disconnected: Got unknown error from server <html>

<head><title>404 Not Found</title></head>

<body bgcolor="white">

<center><h1>404 Not Found</h1></center>

<hr><center>nginx/1.6.3</center>

</body>

</html>

2016-08-31 15:07:31.139 iphoneLive[3763:1005011] LOG SocketEnginePolling: Doing polling request
2016-08-31 15:07:31.140 iphoneLive[3763:1005011] Attempted to create a task in a session that has been invalidated
2016-08-31 15:10:55.842 iphoneLive[3763:1005694] LOG SocketEngine: Engine is being closed.
2016-08-31 15:10:55.843 iphoneLive[3763:1005694] LOG SocketEnginePolling: Created POST string: 1:1
2016-08-31 15:10:55.843 iphoneLive[3763:1005694] ERROR SocketEnginePolling: Tried to do polling request when not supposed to
2016-08-31 15:10:55.843 iphoneLive[3763:1005694] LOG SocketIOClient: Handling event: disconnect with data: (
    "Got unknown error from server <html>
\n<head><title>404 Not Found</title></head>
\n<body bgcolor=\"white\">
\n<center><h1>404 Not Found</h1></center>
\n<hr><center>nginx/1.6.3</center>
\n</body>
\n</html>
\n"
)
2016-08-31 15:10:55.914 iphoneLive[3763:1005011] Bugly:  Trapped uncaught exception 'NSGenericException', reason: 'Task created in a session that has been invalidated' 
(
	0   CoreFoundation                      0x0000000182f7edc8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001825e3f80 objc_exception_throw + 56
	2   CFNetwork                           0x000000018356b110 <redacted> + 144
	3   iphoneLive                          0x0000000100371194 _TFE10iphoneLivePS_20SocketEnginePollable9doRequestfTCSo12NSURLRequest12withCallbackFTGSqCSo6NSData_GSqCSo13NSURLResponse_GSqCSo7NSError__T__T_ + 1052
	4   iphoneLive                          0x0000000100370d5c _TFE10iphoneLivePS_20SocketEnginePollable10doLongPollfCSo12NSURLRequestT_ + 236
	5   iphoneLive                          0x000000010034922c _TFC10iphoneLive12SocketEngine7connectfT_T_ + 2308
	6   iphoneLive                          0x0000000100349fe4 _TToFC10iphoneLive12SocketEngine7connectfT_T_ + 40
	7   iphoneLive                          0x000000010032186c _TFC10iphoneLive14SocketIOClient7connectfT12timeoutAfterSi18withTimeoutHandlerGSqFT_T___T_ + 764
	8   iphoneLive                          0x0000000100321564 _TFC10iphoneLive14SocketIOClient7connectfT_T_ + 52
	9   iphoneLive                          0x0000000100321ba4 _TToFC10iphoneLive14SocketIOClient7connectfT_T_ + 40
	10  iphoneLive                          0x0000000100311860 __26-[moviePlay addNodeListen]_block_invoke_2.971 + 204
	11  iphoneLive                          0x0000000100305028 __54-[moviePlay requestNetworkForSetNodejsInfoByComplete:]_block_invoke + 544
	12  iphoneLive                          0x0000000100275c28 __52-[NetworkTools requestWithParameters:success:error:]_block_invoke + 104
	13  iphoneLive                          0x000000010012fefc __71-[NetworkManager requestNetworkWithServerUrl:parameters:success:error:]_block_invoke + 324
	14  iphoneLive                          0x000000010037caa0 __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.97 + 212
	15  iphoneLive                          0x000000010039f064 __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 + 224
	16  libdispatch.dylib                   0x0000000102351a7c _dispatch_call_block_and_release + 24
	17  libdispatch.dylib                   0x0000000102351a3c _dispatch_client_callout + 16
	18  libdispatch.dylib                   0x00000001023574e4 _dispatch_main_queue_callback_4CF + 2096
	19  CoreFoundation                      0x0000000182f34d50 <redacted> + 12
	20  CoreFoundation                      0x0000000182f32bb8 <redacted> + 1628
	21  CoreFoundation                      0x0000000182e5cc50 CFRunLoopRunSpecific + 384
	22  GraphicsServices                    0x0000000184744088 GSEventRunModal + 180
	23  UIKit                               0x0000000188146088 UIApplicationMain + 204
	24  iphoneLive                          0x00000001002f7f08 main + 124
	25  libdyld.dylib                       0x00000001829fa8b8 <redacted> + 4
)
2016-

**Comment by nuclearace** [comment]
Are you sure you're pointing at a socket.io server? That looks like you're hitting nginx.

**Comment by Calvin-Huang** [comment]
@xclidongbo  You need to specify your socket-server path and namespace by setting SocketIOClient with options.

case Nsp(String) // The namespace to connect to. Must begin with /. Default is `/`
case Path(String) // If the server uses a custom path. ex: `"/swift/"`. Default is `""`

From my experience, our socket.io opened on `http://xxx.domain.xxx/socket.io/?productId=2312` by socket.io default value.
And I tried to use the url with query to connect to socket.io server just like what I did in js version. But I failed.
```
let socket = SocketIOClient(socketURL: NSURL(string: "http://xxx.domain.xxx/socket.io
/?productId=2312")!)
```
In Socket.IO-Client-Swift swift, we need to assign namespace and connect params manually.
```
let socket = SocketIOClient(socketURL: NSURL(string: "http://xxx.domain.xxx/")!, config: [.Nsp("/socket.io/"), .ConnectParams(["productId": 2312]))
```

**Comment by nuclearace** [comment]
The client should add the default socket.io path for you. /socket.io/ isn't a namepsace, it's the `.Path`.

**Comment by Calvin-Huang** [comment]
@nuclearace  Sorry, You're right. That's the `.Path`.
But in our server side code is namespace indeed.
```
io.of('/socket.io/').on('connection', function (socket) {
 


  var productId = socket.handshake.query.productId;
  console.log("socket connected，productId:" + productId);
  var redisClient = redis.createClient();
  redisClient.subscribe('productDetail:' + productId);
 
  redisClient.on('message', function(channel, message) {
    console.log("Send message: "+ message + " -> " + '「productDetail' + productId + '」');
    socket.emit(channel, message);
  });
 
  socket.on('disconnect', function() {
    redisClient.quit();
  });
 
});
```
