### ISSUE TITLE
Cross Platform Connection Issue

### ISSUE THREAD

**Issue by nhjariwala** [socketio/socket.io-client-swift#477]
First of all thanks a lot for great library and lot of hard work. 
I want to create socket communication with Client (Mobile Application - Android and iOS) and Server (CapeSoft NetTalk Software).

**CapeSoft NetTalk**

![nettalkdemo](https://cloud.githubusercontent.com/assets/11612197/18119522/bf820804-6f78-11e6-9b0d-086c3ab7af5c.jpg)

In which **NetSimple Object** there is **Server** utility. It looks like below image

![serverdemo](https://cloud.githubusercontent.com/assets/11612197/18119563/e3af1db6-6f78-11e6-82f4-09a5189ad645.jpg)

I want to send data and receive data between my Client (i.e iOS application) and Server but I am not able to do so.
I am able to send data from my iOS app to socket.io server using below code

**SocketIOManager**

    class SocketIOManager: NSObject {
        static let sharedInstance = SocketIOManager()
    
        var socket: SocketIOClient = SocketIOClient(socketURL: NSURL(string: "http://Url:Port")!)
        
        override init() {
            super.init()
        }
    
        func establishConnection() {
            socket.connect()
        }
        func sendMessage(user: String) {
             socket.emit("connectUser", user)
        }
        func closeConnection() {
            socket.disconnect()
        }
    }

**ViewController**

    class ViewController: UIViewController {

        override func viewDidLoad() {
            super.viewDidLoad()
            // Do any additional setup after loading the view, typically from a nib.
         }
         override func didReceiveMemoryWarning() {
             super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
         }

         @IBAction func btnConnect(sender: UIButton) {	
             SocketIOManager.sharedInstance.establishConnection()
         }

         @IBAction func btnDisconnect(sender: UIButton) {
             SocketIOManager.sharedInstance.closeConnection()
         }
    
         @IBAction func btnMsg(sender: UIButton) {
             SocketIOManager.sharedInstance.sendMessage(txtInput.text!)
         }
    }

**Server**

        var app = require('express')();
        var http = require('http').Server(app);
        var io = require('socket.io')(http);
        http.listen(Port, function(){
	      console.log('Listening on *:Port');
        });
	       io.on('connection', function(clientSocket){
	       console.log('connected');
	       clientSocket.on('disconnect', function(){
	              console.log('disconnected');
	        });	
                var clientNickname;
	         clientSocket.on("connectUser", function(clientNickname) {
		      var message = "User " + clientNickname + " was connected.";
		      console.log(message);
	         });
        });

Above code works fine but I am not able to communicate with CapeSoft NetTalk Server(i.e shown on Image above).

Can anyone please help ?

**Comment by nuclearace** [comment]
What is a nettalk server? Does it use socket.io? This library only connects to socket.io servers.

**Comment by nhjariwala** [comment]
@nuclearace Thanks for  your response.
**_NO_** Nettalk Server doesn't used socket.io.
Is there any cross platform client library available for Server that don't use socket.io ?
Sorry for bothering you.

**Comment by nuclearace** [comment]
What do you mean server? An http client? WebSocket client? If you just want to interface with HTTP just use NSURLSession. Starscream is good if you want a WebSocket client.
