### ISSUE TITLE
Strange crash everytime on iPhone 4S

### ISSUE THREAD

**Issue by MihaelIsaev** [socketio/socket.io-client-swift#478]
Hello,

Can anyone help with this issue?

![2016-09-01_13-27-03](https://cloud.githubusercontent.com/assets/1272610/18162676/72401e98-7048-11e6-9d4d-31a59a101ae7.png)

It crashes everytime on iPhone 4S. But on simulator everything is ok.
Project built in debug mode with

```
Optimization level: None [-Onone]
```

I use latest version from master branch.

**Comment by nuclearace** [comment]
Looks like a websocket error.
