### ISSUE TITLE
swift3 branch compile errors

### ISSUE THREAD

**Issue by hahaGitHub** [socketio/socket.io-client-swift#487]
![2016-09-08 4 38 39](https://cloud.githubusercontent.com/assets/12423630/18342719/c1e89782-75e2-11e6-8289-d9ccb3883b22.png)
![2016-09-08 4 38 45](https://cloud.githubusercontent.com/assets/12423630/18342722/c3fa8d82-75e2-11e6-9ca8-c9bce8025154.png)

**Comment by nuclearace** [comment]
It compiles fine for me.

**Comment by hahaGitHub** [comment]
i used xcode7 and socket-io-client. now i use Xcode 8 beta 6,and i downloaded swift3 branch ,to replace previous version io files,and then build error.
what else i need to set?

**Comment by nuclearace** [comment]
You need the Xcode GM now.

**Comment by LamourBt** [comment]
@nuclearace  when would the full swift 3.0 be available ?

**Comment by tbaranes** [comment]
What is the swift3 branch? I found only the 2.3 one

**Comment by nuclearace** [comment]
The swift3 branch has been merged into development

**Comment by vincedev** [comment]
HI,

Tried using the merged changes for Swift 3 on macOS.
I have errors when compiling.

The compiler complains about symbols unavailable for macOS under 10.10 (namely `DispatchQueue.global(qos:)`, `DispatchQoS.QoSClass.default` in `SSLSecurity.swift`).

Socket IO's deployment target is set to macOS 10.9.

**Comment by keab42** [comment]
Is there a rough ETA on the swift 3 branch hitting master?

**Comment by nuclearace** [comment]
Sometime today

**Comment by nuclearace** [comment]
Should be up now.

**Comment by okankocyigit** [comment]
@hahaGitHub how did you solve this?
