### ISSUE TITLE
podspec v2.0.1 has no source_files

### ISSUE THREAD

**Issue by banjun** [socketio/socket.io-client-swift#49]
The podspec for v2.0.1 seems to be published with `SwiftIO/**/*.swift`, but it does not match any files on current v2.0.1 tag.
Could you please `pod trunk push` again on v2.0.1 to update the spec or publish next version?

https://github.com/CocoaPods/Specs/blob/master/Specs/Socket.IO-Client-Swift/2.0.1/Socket.IO-Client-Swift.podspec.json

**Comment by nuclearace** [comment]
oops

**Comment by nuclearace** [comment]
I think I fixed it?

**Comment by nuclearace** [comment]
Although I forgot to update the description to say it supports Swift 1.2, oh well, I'll do that next version.

**Comment by banjun** [comment]
:+1: 2.0.2 works correctly. Thanks!
