### ISSUE TITLE
It can't work in the Xcode8 version.

### ISSUE THREAD

**Issue by wy358688217** [socketio/socket.io-client-swift#492]
It can't work in the Xcode8 version.

**Comment by nuclearace** [comment]
Is your project a Swift 3 project, and are you using the current version?

**Comment by San-Jeevan** [comment]
Yeah, alot of errors. But it appears your library is not the only one struggling to adapt to Swift3.
I really cannot afford to lose time so I am currently downgrading both to iOS9 and Xcode7

**Comment by nuclearace** [comment]
I mean, it's been updated to Swift 3. How are you including the library?

**Comment by San-Jeevan** [comment]
CocoaPods.
I did pod install.
Look it may just be me and it all works for everyone else. I am now back in xcode7 so I can debug the swift3 issues.

All I did was launch xcode8. select stay with swift 2.3.
Go to this library and chose SWIFT_LEGACY YES in build settings. (otherwise it gave build errors)

**Comment by nuclearace** [comment]
Ah, that's why. You'll have to use Swift 2.3 branch. v8.0.0 is Swift 3.0. 2.3 is only meant to be jumping point to Swift 3.

**Comment by LamourBt** [comment]
@nuclearace is socket.io is fully ready for swift 3.0 ios 10.0 ?

**Comment by vikmis007** [comment]
![screen shot 2016-09-15 at 9 24 06 am](https://cloud.githubusercontent.com/assets/12694597/18537905/54975008-7b26-11e6-888e-2e4656f85377.png)
Still unable to install Socket 8.0.0 . See the attached screenshot

**Comment by nuclearace** [comment]
There is no swift3 branch now. Master is swift3 ready

**Comment by vikmis007** [comment]
will it work with 1.1.0.rc.2 pod version??

**Comment by nuclearace** [comment]
That's what I used to push the update. It messed with my remotes though.

**Comment by HaraldBregu** [comment]
I have the same problem, i updated Xcode to 8 and socket.io-client-swift do not work anymore.
How can i use it now? It is any solution?

**Comment by nuclearace** [comment]
@HaraldBregu What Swift version is your project. v8.0.0 of the client is for Swift 3. Check the README for other versions of Swift.

**Comment by HaraldBregu** [comment]
@nuclearace 
I used "pod 'Socket.IO-Client-Swift', '~> 8.0.0'" to support swift 3 and xcode 8.x and now seams that there are no issues. 
But to use it if i add this class @import SocketIO; i cant use SocketIOClient with issue "no visible @interface for SocketIOClient"

**Comment by EddieLukeAtmey** [comment]
I'm just here to verify that it **CAN** work with xcode 8. I've imported this to my project, using cocoapod of course. At first, I also struggle with the module not found. I did a clean up:

1. Close project.
2. Delete pod files, delivered files, pod frameworks, workspace file
3. pod install
4. Reopen workspace, upgrade swift syntax if xcode ask for, build a few times.

After that, the "module not found" goes away. Not sure if I did anything more than that.

In pod, I just declare `pod 'Socket.IO-Client-Swift`

**Comment by wy358688217** [comment]
![990342a7-070d-4ea1-a234-3f3638161796](https://cloud.githubusercontent.com/assets/12620260/18587735/0344b3ae-7c56-11e6-81df-1e59bdf9a787.png)
![cd0bc274-b933-4613-a7f2-fc69bd49ee3a](https://cloud.githubusercontent.com/assets/12620260/18587736/037e4f74-7c56-11e6-9170-ec56b879d5b2.png)
I was the OC project, tried a variety of methods finally compiled successfully, but failed to run

**Comment by nuclearace** [comment]
@wy358688217 I've seen that happen when you try and use Swift frameworks in command-line applications. It has to do with Swift frameworks aren't static, they have to be bundled with the app.

**Comment by wy358688217** [comment]
@nuclearace But mine not command-line applications. So ,how to fixed?

**Comment by nuclearace** [comment]
Make sure you're including the Framework properly.

**Comment by wy358688217** [comment]
![e9accb38-4ecb-410d-bc0d-280608228419](https://cloud.githubusercontent.com/assets/12620260/18591237/62043a00-7c64-11e6-99fa-903f570d5306.png)
 @nuclearace My solution is to select YES, and then it can work.

**Comment by leewaycn** [comment]
but now ,there comes a new problem . In swift 3 and Xcode 8.all these steps can't work.
while I add the files (in swift3 version8) into my project written in OC, the bridge file won't auto be generated .
as I thought for more than two weeks , I did as the Carthage ways or I want to build a framework of Socket.IO ,but finally all this works can't do as I thought.

Now ,can somebody figure what is the point to fix my problem? thx.

**Comment by faouzi-laburo** [comment]
I have many issues with my project Swift 2.2 in Xcode8, the library SocketIO client Swift generates many error, I did an update of cocoapods and library but I still have those errors, I have convert syntax to Swift 2.3 but the errors are still there. I do not want to convert swift 3 for the time being.

Here is a picture of errors :

![issuessocket](https://cloud.githubusercontent.com/assets/23121307/19807037/729ff630-9d1e-11e6-9425-ece59f7e555f.png)


I thank you in advance and sorry for English errors.
