### ISSUE TITLE
My App Objective-C (base) + swift code crash at launch in release mode.

### ISSUE THREAD

**Issue by dorabod2006** [socketio/socket.io-client-swift#494]
My app base on Objective-C  immediately crashes when launch app in release mode. But when I run the app in debug mode, it launches correctly.

**Comment by nuclearace** [comment]
What version of Xcode and the client?

**Comment by dorabod2006** [comment]
Xcode version7 7.3.1 and what's client?

**Comment by nuclearace** [comment]
Well, you need xcode 8 for the 8.0.0 version.

**Comment by dorabod2006** [comment]
**really?**
OK, I am going to try.

**Comment by dorabod2006** [comment]
and if I use socket.io-client **7.0.3** but still have this problem.
How I fix this problem?

**Comment by nuclearace** [comment]
What's the crash?
