### ISSUE TITLE
Swift 3 Log levels seem to always be on

### ISSUE THREAD

**Issue by nouellette** [socketio/socket.io-client-swift#496]
I disabled the logs using this syntax:
![image](https://cloud.githubusercontent.com/assets/6297832/18571568/60cff900-7b81-11e6-8674-2260c4f2d509.png)

Followed the code to the switch statement and saw the log get set to false but my console is still hammered with verbose logging.

**Comment by nuclearace** [comment]
Can you post some logs?

**Comment by nouellette** [comment]
It's just new logging using Swfit 3 in xcode simulators. My mistake, so many references to sockets i just assumed. Closing issue.
