### ISSUE TITLE
ERROR SocketIOClient: Got unknown error from server

### ISSUE THREAD

**Issue by slashpook** [socketio/socket.io-client-swift#497]
Hi,

I have strange error when compiling last code version of socket.io for swift 3.0.
Here is my code : 

self.mainSocket = SocketIOClient(socketURL: URL(string: URL_BASE_SOCKET)!, config: [.log(true), .forcePolling(true)])
        
        //CONNEXION
        self.mainSocket!.on(SOCKET_CONNECTED) { (data: [Any], ack: SocketAckEmitter) in
            print("Socket - CONNEXION")
        }
        
        self.mainSocket!.connect()

I have got an error message like this : 

**2016-09-16 11:50:36.770438 [5244:705811] ERROR SocketIOClient: Got unknown error from server** 

But the version of socket.io for swift 2.3 work perfectly.
Can you see what is the problem ? 

Regards,

**Comment by nog31** [comment]
Same problem !!! got message : Socket.io 1.0 now available....with all in HTML, like the socket.io webpage...

**Comment by slashpook** [comment]
It seems that if I use **(forceNew:true)** as parameter, it's work
