### ISSUE TITLE
Is it support swift 3？

### ISSUE THREAD

**Issue by xclidongbo** [socketio/socket.io-client-swift#499]
After the upgrade Xcode8, a lot of errors.

**Comment by xclidongbo** [comment]
Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

pod 'Socket.IO-Client-Swift', '~> 8.0.0'
```

Cocoapods Version:0.39


When I open the Project use .xcworkspace,there is some alert "Convert to Current Swift Syntax".
Is it support swift 3?

**Comment by xclidongbo** [comment]
I update Cocoapods version.
Now is 1.0.1.

iPHone 6 is OK,but iPhone 5,there is two errors:

```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$__TtC8SocketIO14SocketIOClient", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by nuclearace** [comment]
Looks like a simulator thing.

**Comment by xclidongbo** [comment]
@nuclearace 
It's some problem about cocoapods 1.0.1.
if I use 'use_frameworks!',  .h file cant create.
