### ISSUE TITLE
Objective-C support

### ISSUE THREAD

**Issue by lightsprint09** [socketio/socket.io-client-swift#5]
It is not possible to instantiate an IO-Client in an Objective-C class and pass it to child Swift classes (for example: ViewController passes the an central IO-Client to model classes) because of missing ```@objc``` in the IO-Client implementation.

**Comment by nuclearace** [comment]
I can look into making it work better with Objective-C, but I didn't write the client to explicitly work with Objective-C. Since I don't really like Objective-C.

**Comment by nuclearace** [comment]
@lightsprint09 I changed some things and added some new methods that should be accessible from Objective-C.
