### ISSUE TITLE
Is it support swift 3？

### ISSUE THREAD

**Issue by jb522185660** [socketio/socket.io-client-swift#500]
A lot of error when build with Xcode 8!

**Comment by nuclearace** [comment]
It supports Swift 3. Which is in Xcode 8. Is your project a Swift 3 project?

**Comment by Chaser-Z** [comment]
Yeah.There are many error in  Xcode 8

**Comment by ilandbt** [comment]
i get this error when added to xcode 8 swift 3.

> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by rheza** [comment]
I can confirm, there is a lot of error on Xcode 8. Any suggestion guys ?

**Comment by JunfeiW** [comment]
I don't know what kind of tools you are using? I use carthage, which works fine

**Comment by JunfeiW** [comment]
But when build there are a lot of warning about buffer

**Comment by rheza** [comment]
@JunfeiW 
I can't even update my carthage now,

"*** Building scheme "SocketIO-tvOS" in Socket.IO-Client-Swift.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
warning: no umbrella header found for target 'SocketIO-tvOS', module map will not be generated"

**Comment by nuclearace** [comment]
The library has been updated for Swift 3. I think most people's problems is that they're using package managers which are slow to update for Swift. Which is why I'd suggest git submoduling.

**Comment by rheza** [comment]
Should i just add this library manually, instead of using  package managers ?

Thanks

**Comment by nuclearace** [comment]
At least until the package managers catch up with Swift 3.

**Comment by btelintelo** [comment]
another safety tip: import SocketIO is new...used to be import SocketIOClientSwift.  At first I thought it was some crazy cocoapods problem.

**Comment by rheza** [comment]
another tip also, if you add the framework manually, you don't need to have import SocketIO on top of file.

**Comment by JunfeiW** [comment]
@rheza,  I just use  ios platform, so about tvOS, I'm not sure about it.

**Comment by jb522185660** [comment]
I found I can use it now.Drag all socket io file into the project,then convert to swift 3.0.Maybe any syntax need to be change manually.
