### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Dohab** [socketio/socket.io-client-swift#504]
Hi,
I get this error:

dyld: Library not loaded: @rpath/SocketIO.framework/SocketIO
  Referenced from: /var/containers/Bundle/Application/DC23476B-F0A6-4A53-B4DA-1ACFC262FA80/webs.app/webs
  Reason: image not found

**Comment by Dohab** [comment]
More explanation:
I'm running Xcode 8.0
Swift 3

case 1:
When I use the master build, every thing is cool, running smoothly on the emulator.
But my iPhone is running on 9.3, So when I change the target to 9.3 in both my project and socket.io project, I get dyld: library not loaded error.

case 2:
When I use branch 2.3 , targeting 9.3, I get Module compiled with Swift 2.3 cannot be imported in Swift 3.0 error

**Comment by nuclearace** [comment]
`dyld: Library not loaded` happens when you aren't properly embedding the library in your app.

**Comment by Dohab** [comment]
@nuclearace 
You are right, but If that the case, then why it works when I set the Deployment target to 10, but not when 9.3 is selected in the project it self?

**Comment by Dohab** [comment]
Ok,
I fixed it by adding "New Copy Files Phase" under Build Phases.
