### ISSUE TITLE
8.0.1 crash

### ISSUE THREAD

**Issue by brightsider** [socketio/socket.io-client-swift#505]
<img width="1423" alt="crash" src="https://cloud.githubusercontent.com/assets/4996231/18663280/810068ba-7f26-11e6-8b92-5a27f06deaaf.png">

**Comment by Gagster** [comment]
Hi, Where can I get the version 8.0.1?
I've tried to use pod, but it saids that the latest one is 8.0.0 
: (  plz Help~
