### ISSUE TITLE
Argument labels '(socketURL:, options:)' do not match any available overloads

### ISSUE THREAD

**Issue by EstefaniaTenntaDiaz** [socketio/socket.io-client-swift#509]
hi!, i am try to connect with "connectParams"
`let socket      = SocketIOClient(socketURL: URL(string: "http://localhost:5000")!, options: ["connectParams": ["user_id": "myuserid", "otherparam": "otherparam"]])`

this work before swift 3, help me please!!

**Comment by nuclearace** [comment]
Use the config constructor like in the readme

**Comment by EstefaniaTenntaDiaz** [comment]
thanks!, this work for me :D 

`let socket = SocketIOClient(socketURL: URL(string: "http://localhost:5000")!, config: [.log(true), .forcePolling(true), .connectParams(["user_id": "myuserid", "otherparam": "otherparam"])])`
