### ISSUE TITLE
Use of subscripts causes Xcode builds to fail

### ISSUE THREAD

**Issue by exclsr** [socketio/socket.io-client-swift#51]
When importing the Socket_IO_Client_Swift library, and having code like below, Xcode 6.2 will not be able to compile the project.

```swift
import Socket_IO_Client_Swift

class Test {
    func causesSegmentationFaultOnCompile() {
        let array = NSArray()
        for item in array {
            let breaks = item["name"] // This line causes the compile failure
            let fine = item.valueForKey("name") // This works fine
        }
    }
}
```
Attempting to build this results in: "Swift Compiler Error: Command failed due to signal: Segmentation fault: 11"

The stack dump from Xcode is like so:
```
0.	Program arguments: ... 
1.	While type-checking 'causesSegmentationFaultOnCompile' at /Test.swift:5:5
2.	While type-checking declaration at /Test.swift:8:13
3.	While type-checking expression at [/Test.swift:8:26 - line:8:37] RangeText="item["name"]"
```

This happens in 1.5.2 and 1.1.2. I used a Podfile, like so: 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Socket.IO-Client-Swift', '1.5.2'
```

**Comment by nuclearace** [comment]
I'm confused, the library itself is causing this generic problem with arrays?

Because your test code is rather silly, that loop would never execute. Can you provide an example of how you're using it with the library.

Also look into upgrading to Xcode 6.3/Swift 1.2. Because I'm not going to be applying fixes to pre-2.0

**Comment by exclsr** [comment]
Your questions are reasonable. I admit this issue does appear ridiculous upon first glance. Please allow me to elaborate:

1. Yes, the library itself is causing the problem. Removing the import statement causes the build to succeed.

2. Yes, the test code is silly, and the loop would never execute. Here is the point: The only interaction this code has with the library is that this code is in the same project as the "import Socket_IO_Client_Swift" statement. This code could be in a different file, and the compile error still occurs. 

However, to satisfy your question: Imagine I have a json object represented somewhere in my Swift code. That json could be something like this:

```javascript
{
    "things": [{
        "foo": 1
    },{
        "foo": 2
    }]
}
```
In Swift I could then do something like:
```swift
if let json = NSJSONSerialization.JSONObjectWithData(...) as? NSDictionary {
  if let array = json["things"] as? NSArray {
    for thing in array {
      let foo = thing["foo"]
      // Do something with foo
    }
  }
}
```

I also agree that Swift 1.2 is the future. Perhaps we've discovered an issue with the Apple compiler.

**Comment by nuclearace** [comment]
That's really strange, I don't think I'm doing anything that should interfere with NSArray

**Comment by exclsr** [comment]
I'm downloading Xcode 6.3 now to test it with that. I'll continue investigating.

**Comment by exclsr** [comment]
This works fine with Xcode 6.3 and version 2.0.2 of this library.

**Comment by nuclearace** [comment]
That's strange, well if it works I'll close the issue
