### ISSUE TITLE
SocketIOClient for Object-c couldn't init

### ISSUE THREAD

**Issue by Samuel-liuse** [socketio/socket.io-client-swift#510]
NSURL\* url = [[NSURL alloc] initWithString:stringUrl];
    self.socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"log": @YES, @"forcePolling": @YES}];

this two lines in oc, the self.socket could not be init,it's alway be nil when it running in phone,but in simulator it’s be well.
why?I'm in hurry for the problem,I need to release the version two days after,please help～

**Comment by Samuel-liuse** [comment]
supplement
I check the sdk ,i find

NSURL* url = [[NSURL alloc] initWithString:stringUrl];
self.socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"log": @YES, @"forcePolling": @YES}];

this two lines could not perform the swift fuc:
public init(socketURL: NSURL, config: SocketIOClientConfiguration = [])
on the phone,but still work well on simulator.

On Monday i need to release the version to appStore,please help...

**Comment by Praphin** [comment]
Same issue here. Please help me out

**Comment by nuclearace** [comment]
Stuff that works in simulator but fails on devices is usually a Swift issue. My Objective-C tests seem to init the socket.

**Comment by Krystel** [comment]
I'm facing the same issue with the init in Objective-c. It doesn't seem to connect.

Did anyone find a solution yet?

**Comment by leewaycn** [comment]
I have the same problem these days .and I want to build a framework,but it doesn't work.can anybody help ? and tell me how to build a framework by the way.

**Comment by leewaycn** [comment]
dyld: Library not loaded: @rpath/MySocketIO.framework/MySocketIO
  Referenced from: /var/containers/Bundle/Application/21EA20A0-7ACD-4D7A-BD25-8C90201A7E40/DemoSwiftForSocketFramework.app/DemoSwiftForSocketFramework
  Reason: image not found

**Comment by nuclearace** [comment]
Be sure to embed the framework.

**Comment by leewaycn** [comment]
I had dragged the framework in my projects. but no helps.
