### ISSUE TITLE
Cannot init Swift 3

### ISSUE THREAD

**Issue by damionvega** [socketio/socket.io-client-swift#513]
The initializer in readme fails to compile in Xcode 8.0 (8A218a)

![screenshot 2016-09-26 17 21 32](https://cloud.githubusercontent.com/assets/7221494/18855181/0c3e34ac-840e-11e6-86df-46cf5cf09d4b.png)

**Comment by nuclearace** [comment]
what's the type of URL.host?

**Comment by nuclearace** [comment]
I've noticed a lot of times that error is actually a lie.

https://github.com/nuclearace/socket.io-client-swift-spm-example/blob/master/Sources/main.swift#L4

**Comment by damionvega** [comment]
Oh sorry, it's just a struct prop which is a string (project under NDA)
```
struct URL {
  static var host = "http://api.myproject.co"
  // ...other URLs
```

**Comment by nuclearace** [comment]
`socketURL` needs to be a URL, not a string.

**Comment by damionvega** [comment]
Gotcha. Do you know what this means (copied from readme)?
![screenshot 2016-09-26 18 22 45](https://cloud.githubusercontent.com/assets/7221494/18856232/518c1e22-8416-11e6-8181-156a5f9b9591.png)

**Comment by nuclearace** [comment]
What version of the client are you using?

**Comment by damionvega** [comment]
8.0.2

**Comment by nuclearace** [comment]
If you take everything of the init like:

```swift
let url = URL(string: "http://localhost:8080/")!
let config = [.log(true), .forcePolling(true)] as SocketIOClientConfiguration
let socket = SocketIOClient(socketURL: url, config: config)
```
Does it give the same error?

**Comment by damionvega** [comment]
Yes. Is there a different URL initializer?
![screenshot 2016-09-26 18 30 14](https://cloud.githubusercontent.com/assets/7221494/18856355/4cfab278-8417-11e6-8e68-51e2c14ffe4a.png)

**Comment by nuclearace** [comment]
Are you importing Foundation?

**Comment by damionvega** [comment]
Nevermind, the problem is my URL class is colliding with it. Thanks for your help 😄

**Comment by nuclearace** [comment]
Ah, you'll have to do `Foundation.URL` if there's a collision.
