### ISSUE TITLE
Need to convert again after pod install

### ISSUE THREAD

**Issue by wangiv2** [socketio/socket.io-client-swift#514]
When i use xcode8 to build the project with socket.io, every time need to convert again after pod install. I wanna to know if the version 8.0.2's code is already support swift3.0, if yes, why i need to convert again after pod install? thanks in advances.

**Comment by nuclearace** [comment]
What version of cocoapods are you using?

**Comment by wangiv2** [comment]
after add below code in the end of pod file is resolved
*************************************************
post_install do |installer|
 installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
         config.build_settings['SWIFT_VERSION'] = '3.0'
     end
 end
**************************************************
