### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by brightsider** [socketio/socket.io-client-swift#516]
I have this crash on 8.0.0, but maybe this is reproduced on 8.0.2.

2  CFNetwork                      0x1872ea328 -[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]
3  SocketIOClientSwift            0x100a8dcfc SocketEnginePollable.doRequest(NSURLRequest, withCallback : (NSData?, NSURLResponse?, NSError?) -> ()) -> () (SocketEnginePollable.swift:105)
4  SocketIOClientSwift            0x100a8dae0 SocketEnginePollable.doLongPoll(NSURLRequest) -> () (SocketEnginePollable.swift)
5  SocketIOClientSwift            0x100a837c4 SocketEngine.connect() -> () (SocketEngine.swift)
6  SocketIOClientSwift            0x100a84124 @objc SocketEngine.connect() -> () (SocketEngine.swift)
7  SocketIOClientSwift            0x100a951d0 specialized SocketIOClient.connect(timeoutAfter : Int, withTimeoutHandler : () -> ()?) -> () (SocketIOClient.swift:144)
8  SocketIOClientSwift            0x100a94980 SocketIOClient.(_tryReconnect in _C2E9ECF58A55152EB119E72DB3CA1482)() -> () (SocketIOClient.swift:440)
9  SocketIOClientSwift            0x100a96384 specialized SocketIOClient.engineDidClose(String) -> () (SocketIOClient.swift)
10 SocketIOClientSwift            0x100a93ad8 @objc SocketIOClient.engineDidClose(String) -> () (SocketIOClient.swift)
11 SocketIOClientSwift            0x100a8467c SocketEngine.(sendPing in _F4E64ABD190088B0EB4A328626563DF0)() -> () (SocketEngine.swift:477)
12 SocketIOClientSwift            0x100a88884 SocketEngine.((sendPing in _F4E64ABD190088B0EB4A328626563DF0)() -> ()).(closure #1) (SocketEngine.swift)

<img width="869" alt="2016-09-27 9 12 28" src="https://cloud.githubusercontent.com/assets/4996231/18862081/8c7a665c-8492-11e6-89ee-88b625aec28f.png">

**Comment by nuclearace** [comment]
Probably fixed in the DispatchQueue refactor.
