### ISSUE TITLE
How to cancel in-flight emitWithAck

### ISSUE THREAD

**Issue by bhartsb** [socketio/socket.io-client-swift#517]
How can once cancel an in-flight emitWithAck?

Specifically:
1) How can one disconnect the socket and cancel any in-flight emitWithAck(s) where upon a subsequent reconnect none of the pending emits happen and none of the corresponding Ack hanlders (blocks/closures) are called?
2) How can one disconnect the socket and insure upon reconnect that the pending emits do happen and the corresponding Ack handers are called?

iOS developer tools allow one to simulate bad network conditions for testing.  What I'm doing is setting the packet loss to 100%, calling several emitWithAcks, and then after a timeout, disconnecting the socket, and then subsequently reconnecting.

It seems that forcing a disconnect after a timeout will for case 1) cause the Acks not to be called, but the emit part still goes through.  I want to cancel the inflight emit and not have it resume.

If for case 2 I wanted the emit to resume (which it does) then I'd also want the ack to be called (which it isn't).

When my timeout happens I currently do the following:
SocketIOClient\* socketIOSwift = [self getSocketIOObj];
    [socketIOSwift disconnect];
    [socketIOSwift removeAllHandlers];
    socketIOSwift = nil;

I note that if I comment out the line with removeAllHandlers then only the first emit gets through upon reconnect.  If it is left in then all emits go through upon reconnect. I'm not clear on why this might be?

Finally can someone elaborate on setReconnects:?

Thanks.

**Comment by nuclearace** [comment]
There's not really a way to stop an emit once it's called, the pipeline for sending is done asynchronously, and the emit packet could be anywhere from still in the parser to in a buffer waiting to send. As for handlers being called after disconnect, I don't think they currently check the socket's status. You could add your own check in your handler for the socket's status. As for removeAllHandlers, I don't think it currently removes ackHandlers, just event handlers. I did that because normally ack handlers are transient and shouldn't be lasting too long.

**Comment by bhartsb** [comment]
So what I have is a messaging app, and when I simulate a poor network connection, and try to send multiple msgs (text, audio, or photo), it is desirable to have some timeout, mark the msgs that didn't send undelivered, and provide the user the option to resend or not.  If I can't stop the original emit once it is called then the next time they do connect the old emit will fire anyway, even if the user didn't say resend. That is the reason for in-flight cancelling.  Also after a disconnect and reconnect, the message fires, is received by the server but the ack callback doesn't happen.  This is odd because the server responds back to the awk method specified.  It is like the server has the wrong (old) connection info for the awk.  Ideas???

The workaround could be that I send with each emitWithAck a timeout time and if when the server receives the message, and it is after this timeout time, it drops the message.  This would accomplish almost the same thing as being able to cancel the in-flight emit.    

Also what is setReconnects:?
