### ISSUE TITLE
can no longer override isvalid on SSLSecurity

### ISSUE THREAD

**Issue by bot2600** [socketio/socket.io-client-swift#519]
I don't know an easy answer to this, but if you were doing custom validation on isvalid (for instance pinning on fingerprints instead of deploying certs) SSLSecurity would need to be changed to be open, but I think that is too much, a lot of the internals would need to be changed to be final I guess.

I'll make the changes and make a PR if you are interested in the changes, I am going to have to make them locally anyhow.

**Comment by nuclearace** [comment]
I don't care about opening that class, so if you want to make a PR that's fine.

**Comment by bot2600** [comment]
ok, I'll just open that class and that one method
