### ISSUE TITLE
Secure Socket over mobile network

### ISSUE THREAD

**Issue by BhawnaBhandari24** [socketio/socket.io-client-swift#525]
Hi,
I am trying to make a secure connection over the mobile network. Is there any possibility to achieve this using the framework. I was able to make the connection to the server but it is not going over mobile network. Also after making the successful connection need to send a GET/POST request. Any help would be appreciated.

**Comment by nuclearace** [comment]
If you setup TLS properly, this framework will work.

**Comment by BhawnaBhandari24** [comment]
I am pretty new to socket programming.  The final goal is to load a webView which should go over mobile network. Should i be using WebSockets for that or is there any documentation i can go through before trying to address the issue.

**Comment by BhawnaBhandari24** [comment]
I tried this but when i switch to wifi the request does not route through mobile network

socket = SocketIOClient(socketURL: URL(string: "https://xxx.xxx.xxx:22790")!, config: [.log(true),.secure(true),.path("/vzconnect/cdi/v1/authorize/"),.connectParams(["auth_request":"ew0KCSJpc3MiOiAiNjg2MzNjYjMtZjFhNy00MDJiLWFjZDMtYjAzMDZiYjY5MWQwIiwNCgkiYXVkIjogImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC92emNvbm5lY3QvIiwNCgkiY2xpZW50X2lkIjogIjY4NjMzY2IzLWYxYTctNDAyYi1hY2QzLWIwMzA2YmI2OTFkMCIsDQoJInJlZGlyZWN0X3VyaSI6ICJodHRwOi8vZXhhbXBsZS5jb20iLA0KCSJzY29wZSI6ICJvcGVuaWQiLA0KICAgICAgICAicmVfdHlwZSI6InRlIiwNCgkibm9uY2UiOiAibi0wUzZfV3pBMk1qIiwNCgkiZXhwIjogMTU3Nzg2NTYwMDAwMCwNCgkic2lkIjogIjUxZjY3MTRiLTIzZGYtNDYwMC04MTI2LWU2NjM3OWZjZjgyNiIsDQoJImNkaSI6IHsNCgkJIm1lcmNoYW50aWQiOiAiMjAxNDUwIiwNCgkJIm1lcmNoYW50bmFtZSI6ICJOaWtlIiwNCgkJImltX3VzZWNhc2UiOiAibWMiDQoJfSwNCgkiY3B1YiI6IHsNCgkJInZmcCI6ICI0ZDU0NTE3YTRkNDQ1OTMyNGY0ODc3Nzg0ZDZhNDEzMTRkNDQ0MTc3NGQ3NzRlNmE1OTM1M2EwYjBkZjRiYWI3ZDFkMDFlYWZkNmQ4Y2IxMGM5ZTcwNTlmOGQxZDZhZDA5MDA5MjRkNjE2MmViOGIxYWQzMWU0Ig0KCX0NCn0=","r":"f"])])
        socket?.on("connect") {data, ack in
            print("socket connected")
        }
        socket?.connect()

On mobile network : 
I am getting the response

On wifi : 
2016-09-30 11:29:18.664474 MobileIDOverWifi[815:146386] [] nw_socket_connect connectx failed: [64] Host is down
2016-09-30 11:29:18.666594 MobileIDOverWifi[815:145950] ERROR SocketEnginePolling: Could not connect to the server.
2016-09-30 11:29:18.666803 MobileIDOverWifi[815:145950] ERROR SocketEngine: Could not connect to the server.
2016-09-30 11:29:18.666950 MobileIDOverWifi[815:145950] ERROR SocketIOClient: Could not connect to the server.

Let me know if something can be done.

**Comment by nuclearace** [comment]
Looks like it can't connect to the server?
