### ISSUE TITLE
Swift 3 Issues

### ISSUE THREAD

**Issue by maximoufaev** [socketio/socket.io-client-swift#526]
Hey im trying to install this via cocoapods using the latest versions which should be swift 3 compatible but im getting large amounts of errors. Im not sure if im doing something wrong here or if its something else the versions im trying to get with the pod install is 8.0.2  version. Thanks in advance.

**Comment by nuclearace** [comment]
What version of cocoapods?

**Comment by martinpfannemueller** [comment]
I cannot compile at the moment either. I suppose we have the same problem. Xcode wants me to convert the Swift code to version 3.0. However, as you state you are already using Swift 3. I am using Cocoapods version 1.1.0.rc.2 and I require version 8.0.2. I e.g. tried to remove the Pods folder and use "pod install" as well as setting the build target to iOS 10 for testing. Any ideas?

**Comment by maximoufaev** [comment]
I have cleared it up. I had to change the projects minimum target to iOS 10.0 and that cleared out all the swift issues.
