### ISSUE TITLE
Swift2.3 can't use

### ISSUE THREAD

**Issue by RozenAstrayChen** [socketio/socket.io-client-swift#528]
HI ,my project is swift2.3 and i use swift2.3 branch .it has 10 error
![2016-10-03 12 01 47](https://cloud.githubusercontent.com/assets/19503080/19027276/3696c194-8961-11e6-9b20-50156f501585.png)

**Comment by petemillermultimedia** [comment]
"me too".  I'm not ready to move to Swift 3.0, how do I get a working pod for Swift 2.3?

**Comment by aksperiod** [comment]
+1

**Comment by nuclearace** [comment]
@RozenAstrayChen Are you on Xcode 8? The swift2.3 branch compiles fine there.

@petemillermultimedia You can have cocoapods point at a branch I believe.

**Comment by aksperiod** [comment]
@nuclearace I am Xcode 8 beta 6 and getting the same errors when trying to build. I am upgrading to Xcode 8 release version and I will let you know what happens.

![screen shot 2016-10-06 at 9 42 25 am](https://cloud.githubusercontent.com/assets/9045234/19155169/70cc7696-8bab-11e6-8dc4-e703e576a240.png)

**Comment by petemillermultimedia** [comment]
I'm setting my podfile to
  pod 'Socket.IO-Client-Swift', '7.0.3'
which is the version shown under the swift2.3 branch. Is that the correct way to point to the branch?

**Comment by aksperiod** [comment]
Upgraded to Xcode X release, same problem.

Same as @petemillermultimedia my podfile included:
`    pod 'Socket.IO-Client-Swift', '7.0.3'`

**Comment by nuclearace** [comment]
Yeah, that's not going to work. http://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by aksperiod** [comment]
Ah, thanks a bunch.

For anyone else who finds this problem use:

`pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift2.3'`

**Comment by RozenAstrayChen** [comment]
i slove this problem , i download  file and copy to my project will be used! Thx
