### ISSUE TITLE
No visible @interface for SocketIOClient delcares emitWithAck:withItems

### ISSUE THREAD

**Issue by Praphin** [socketio/socket.io-client-swift#533]
Call backs are not working for EmitwithAck

![screen shot 2016-10-05 at 5 28 33 pm](https://cloud.githubusercontent.com/assets/6714897/19112253/674c69da-8b21-11e6-977d-7946f09992bd.png)

Pls help me out

**Comment by nuclearace** [comment]
What version are you on? The current version looks like https://github.com/socketio/socket.io-client-swift/blob/master/SocketIO-MacTests/SocketObjectiveCTest.m#L38

**Comment by nuclearace** [comment]
Ah, I need to update the readme.

**Comment by Praphin** [comment]
Worked.
            

[self.socket emitWithAck:@"canUpdate" with:@[@{ @"email"  : @"test",            
                                                       }]](0, ^(NSArray* data){
                });

Thanks u so much :)
