### ISSUE TITLE
why not compatible with armv7. in Xcode 8 and 

### ISSUE THREAD

**Issue by leewaycn** [socketio/socket.io-client-swift#534]
ld: warning: ignoring file /Users/daniao/Desktop/Fmscms_app_8.26_xcode8/SocketIO.framework/SocketIO, file was built for arm64 which is not the architecture being linked (armv7): /Users/daniao/Desktop/Fmscms_app_8.26_xcode8/SocketIO.framework/SocketIO
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$__TtC8SocketIO14SocketIOClient", referenced from:
      objc-class-ref in BBLivePushViewController+BBNodejs.o
      objc-class-ref in BBLivePlayPCViewController+BBNodeJS.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iphonist** [comment]
check the 'edit scheme'. whether debug-mode or not
