### ISSUE TITLE
Module SocketIO not found

### ISSUE THREAD

**Issue by DrBeak1** [socketio/socket.io-client-swift#535]
I've imported the SocketIO swift client via cocoapods. I had no problems until recently. Now when any time I try to make changes to the class in which I'm importing socketio I get 'module socketio not found' error the second I start typing. Then I cmd+s to save and the error goes away. Everything builds fine. The issue this causes for me is that I don't have the autocomplete of methods happening; in fact, my class things that my `SocketIOClient` object is an `int` until I click save.

<img width="1605" alt="screen shot 2016-10-05 at 10 36 09 am" src="https://cloud.githubusercontent.com/assets/1033734/19124440/0ebd692e-8ae8-11e6-906f-5e4afbe7d61e.png">

Anyone else come across this?

**Comment by nuclearace** [comment]
Sounds like Xcode being dumb, which isn't unusual.

**Comment by DrBeak1** [comment]
@nuclearace I definitely agree with that. Any suggestions for getting this working? I've tried everything I can think of; from removing all cocoapods and reinstalling, to adjusting framework and header search paths, cleaning the build, deleting derived data ... nothing seems to work.

**Comment by DrBeak1** [comment]
Solution noted [here](https://github.com/CocoaPods/CocoaPods/issues/6018)
