### ISSUE TITLE
SWIFT 3.0 VERSION ISSUES

### ISSUE THREAD

**Issue by sravanzeal** [socketio/socket.io-client-swift#538]
i upgraded to swift 2.3 to swift 3.0 so it shows with lots of errors

**Comment by nuclearace** [comment]
Be sure you're up-to-date and you're using the latest version of cocoapods

**Comment by VergaraF** [comment]
Which is the latest version? I even did pod update and it still gives me the option to upgrade from 2.3 to 3 and lots of errors after doing so.

**Comment by kingcompany** [comment]
I am having the same issue. It wants to upgrade from 2.3 to 3.0 and then many errors appear. I also have the latest pods version. Any ideas?

**Comment by VergaraF** [comment]
Import the Swift files manually, that would do it. Not the best choice, but it seems to fix it just fine.

**Comment by nuclearace** [comment]
Or git submodule

**Comment by chunxigege** [comment]
but it doesn't work ,i met same error

**Comment by NE90683** [comment]
@nuclearace 
I'm having the same issue , socket.io did used in our project , every thing is ok in xcode7 .
when I upgrade the xcode to 8.1 , reopen our project , the xcode alert one tips which require Convert to current Swift syntax , but socket.io is managed  use cocoaPods, so i can't modify the socket.io source code.  

the the some information in this following list ：
  pod 'Socket.IO-Client-Swift', '~> 6.1.3' ,
  MacOS Sierria Version 10.12(16A323) ,
  Xcode 8.1  ,
 CocoaPods version 1.0.1

Please help me.
