### ISSUE TITLE
Xcode 8 Errors

### ISSUE THREAD

**Issue by tolgaytoklar** [socketio/socket.io-client-swift#539]
I downloaded swift2.3 branch and i am using xCode 8 with swift 2.3. I can't compile my project because i am getting errors in the following image.

![ekran resmi 2016-10-12 15 20 36](https://cloud.githubusercontent.com/assets/767253/19309797/b866ae98-908f-11e6-9f2e-77cb6b2832e9.png)

How to fix?

**Comment by cms5x** [comment]
Try to use this: ```  - Socket.IO-Client-Swift (from `https://github.com/socketio/socket.io-client-swift`, branch `swift2.3`)``` instead of `~> 7.0.3` as the swift2.3 branch seems to have some changes ahead of 7.0.3

**Comment by nuclearace** [comment]
Yes, you have to use the swift2.3 branch.
