### ISSUE TITLE
Using this client with self signed certificates

### ISSUE THREAD

**Issue by ramki982** [socketio/socket.io-client-swift#54]
I'd need to pass a optional NSURLSessionDelegate to the societ client and in turn to the socket engine so that this can be used to handle the call "func URLSession(session: NSURLSession,
        task: NSURLSessionTask,
        didReceiveChallenge challenge: NSURLAuthenticationChallenge,
        completionHandler: (NSURLSessionAuthChallengeDisposition,
        NSURLCredential!) -> Void)"

This will help dealing with Servers having self-signed certificates that is typically the case in SSL servers in dev mode.

I have made the code changes locally - could i request to pull a branch in which these changes can be made

**Comment by nuclearace** [comment]
Sure open a pull request and I'll review it and make comments. And when it looks good I'll merge it.

**Comment by ramki982** [comment]
Thanks a bunch

**Comment by ramki982** [comment]
Done @nuclearace - i have created a pull request.Let me know your thoughts

**Comment by nuclearace** [comment]
@ramki982 I merged it

**Comment by ramki982** [comment]
oh ok great thanks

**Comment by ramki982** [comment]
Thanks Erik

On Friday 17 April 2015, Erik Little <notifications@github.com> wrote:

> Closed #54 <https://github.com/socketio/socket.io-client-swift/issues/54>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/socketio/socket.io-client-swift/issues/54#event-283851492>
> .
>


-- 
Sent from Gmail Mobile
