### ISSUE TITLE
Q: WatchOS 3 support

### ISSUE THREAD

**Issue by szuniverse** [socketio/socket.io-client-swift#540]
Hi

do you guys planning to support watchOS 3.0? If yes, when will it be available?

**Comment by nuclearace** [comment]
Last I checked watchOS couldn't be supported because of some things used in the websocket dependency not being available on it.

**Comment by szuniverse** [comment]
What kind of dependecies?

**Comment by nuclearace** [comment]
I believe NSStream.

**Comment by szuniverse** [comment]
Thanks
