### ISSUE TITLE
createRequestForPostWithPostWait causes a Crash

### ISSUE THREAD

**Issue by K-Leon** [socketio/socket.io-client-swift#541]
I just received in Crashlytics a crashteport indicated that something with SocketEnginePollable is causing a crash. I'm using Swift 2.3 Branch.

`SocketEnginePollable.swift line 62
SocketEnginePollable.(createRequestForPostWithPostWait() -> NSURLRequest).($defer #1)() -> ()`

`#0
Crashed: com.socketio.engineHandleQueue
EXC_BREAKPOINT 0x0000000100f21dc0
SocketEnginePollable.(createRequestForPostWithPostWait() -> NSURLRequest).($defer #1)() -> ()`

`
#31. Crashed: com.socketio.engineHandleQueue

0  libswiftCore.dylib             0x100f21dc0 _TTSf4s_s_d_d___TFs18_fatalErrorMessageFTVs12StaticStringS_S_Su_T_ + 40
1  libswiftCore.dylib             0x100f2cb88 _TTSf4s_n_d_n___TTSg5GVs12_ArrayBufferSS_GS_SS_s16_ArrayBufferTypes_SS_GVs17IndexingGeneratorGS_SS__GS1_GS_SS__s13GeneratorTypes_SS_SiSis16ForwardIndexTypes_SiSis18_SignedIntegerTypes_SiSis33_BuiltinIntegerLiteralConvertibles_Si_GVs12_SliceBufferSS_GS6_SS_s14CollectionTypes_GS1_GS6_SS__GS1_GS6_SS__S2_s_SS_SiSiS3_s_SiSiS4_s_SiSiS5_s_Si_GS6_SS_GS6_SS_s9IndexablesGS6_SS_s12SequenceTypes_GS1_GS6_SS__GS1_GS6_SS__S2_s_SS_SiSiS3_s_SiSiS4_s_SiSiS5_s_Si_GS6_SS__SS_SS_SS_GVs15EmptyCollectionSS_GS10_SS_S7_s_GVs14EmptyGeneratorSS_GS11_SS_S2_s_SiSiS3_s_SiSiS4_s_SiSiS5_s_Si_GVs5SliceGS10_SS__GS12_GS10_SS__S8_sGS12_GS10_SS__S9_s_GS1_GS12_GS10_SS___GS1_GS12_GS10_SS___S2_s_SS_SiSiS3_s_SiSiS4_s_SiSiS5_s_Si_GS12_GS10_SS___SS_SS___TFEsPs16_ArrayBufferType7replaceuRd__s14CollectionTypewx7ElementzWd__9Generator7Element_rfT8subRangeGVs5RangeSi_4withSi10elementsOfqd___T_ + 872
2  scanner                        0x1000cfce0 SocketEnginePollable.(createRequestForPostWithPostWait() -> NSURLRequest).($defer #1)() -> () (SocketEnginePollable.swift:62)
3  scanner                        0x1000cfc64 SocketEnginePollable.createRequestForPostWithPostWait() -> NSURLRequest (SocketEnginePollable.swift:84)
4  scanner                        0x1000d19a0 SocketEnginePollable.flushWaitingForPost() -> () (SocketEnginePollable.swift:148)
5  scanner                        0x1000d2cb4 SocketEnginePollable.sendPollMessage(String, withType : SocketEnginePacketType, withData : [NSData]) -> () (SocketEnginePollable.swift:222)
6  scanner                        0x1000c9ed0 SocketEngine.upgradeTransport() -> () (SocketEngine.swift:498)
7  scanner                        0x1000c9c7c SocketEngine.handlePong(String) -> () (SocketEngine.swift:406)
8  scanner                        0x1000ca920 SocketEngine.parseEngineMessage(String, fromPolling : Bool) -> () (SocketEngine.swift:441)
9  scanner                        0x1000cadb0 @objc SocketEngine.parseEngineMessage(String, fromPolling : Bool) -> () (SocketEngine.swift)
10 scanner                        0x10007f6d8 SocketEngineWebsocket.websocketDidReceiveMessage(WebSocket, text : String) -> () (SocketEngineWebsocket.swift:57)
11 scanner                        0x1000cc924 protocol witness for WebSocketDelegate.websocketDidReceiveMessage(WebSocket, text : String) -> () in conformance SocketEngine (SocketEngineWebsocket.swift:55)
12 scanner                        0x1000ba5e4 WebSocket.(processResponse(WebSocket.WSResponse) -> Bool).(closure #1) (WebSocket.swift:745)
13 scanner                        0x100088ad4 thunk (SocketIOClient.swift)
14 libdispatch.dylib              0x18fb05200 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x18fb051c0 _dispatch_client_callout + 16
16 libdispatch.dylib              0x18fb13444 _dispatch_queue_serial_drain + 928
17 libdispatch.dylib              0x18fb089a8 _dispatch_queue_invoke + 652
18 libdispatch.dylib              0x18fb13940 _dispatch_queue_override_invoke + 360
19 libdispatch.dylib              0x18fb1538c _dispatch_root_queue_drain + 572
20 libdispatch.dylib              0x18fb150ec _dispatch_worker_thread3 + 124
21 libsystem_pthread.dylib        0x18fd0d2c8 _pthread_wqthread + 1288
22 libsystem_pthread.dylib        0x18fd0cdb4 start_wqthread + 4
`

Best regards and thank you for your hard work!

Edit: I added a Screenshot of the Stacktrace
![image](https://cloud.githubusercontent.com/assets/2196713/19407907/1282e7e4-92b0-11e6-84db-3f83656c4660.png)

**Comment by snehasen1990** [comment]
facing same issue!!!!

**Comment by DonorRaja** [comment]
facing same issue my also any one plz help ...

**Comment by nuclearace** [comment]
Probably fixed in the DispatchQueue refactors.
