### ISSUE TITLE
crash on Xcode 8.1 beta 3

### ISSUE THREAD

**Issue by TaoistKing** [socketio/socket.io-client-swift#542]
* thread #1: tid = 0xc076, 0x0000000182eadb90 libobjc.A.dylib`objc_msgSend + 16, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)

    frame #0: 0x0000000182eadb90 libobjc.A.dylib`objc_msgSend + 16

    frame #1: 0x0000000101e349d8 libswiftDispatch.dylib`(extension in Dispatch):__ObjC.DispatchQueue.init (label : Swift.String, qos : Dispatch.DispatchQoS, attributes : (extension in Dispatch):__ObjC.DispatchQueue.Attributes, autoreleaseFrequency : (extension in Dispatch):__ObjC.DispatchQueue.AutoreleaseFrequency, target : Swift.Optional<__ObjC.DispatchQueue>) -> __ObjC.DispatchQueue + 92

    frame #2: 0x000000010112f2a0 SocketIO`SocketIO.SocketIOClient.init (socketURL : Foundation.URL, config : SocketIO.SocketIOClientConfiguration) -> SocketIO.SocketIOClient + 360

    frame #3: 0x000000010112fb10 SocketIO`SocketIO.SocketIOClient.init (socketURL : __ObjC.NSURL, config : Swift.Optional<__ObjC.NSDictionary>) -> SocketIO.SocketIOClient + 776

**Comment by kikolobo** [comment]
Can you turn on Thread Sanitizer in XCODE. This crash might be related to:
https://github.com/socketio/socket.io-client-swift/issues/531

It looks like an object is being deallocated before it is used : EXC_BAD_ACCESS

**Comment by TaoistKing** [comment]
@kikolobo Maybe Not. I rebuilt socket.io framework with Xcode 8.1 beta3, and it works well Now.
There might be something different from Xcode 8.0 and 8.1, framework which built by 8.0 can't be used with 8.1.
