### ISSUE TITLE
Background Connect

### ISSUE THREAD

**Issue by shoaibhussan** [socketio/socket.io-client-swift#546]
Hellow all,
i want my app to keep alive its socket connection with server in background,
please let me know if there is any fix

Thanks in advance

**Comment by shoaibhussan** [comment]
Thanks to God,i have done it with few lines of code,no i can send and recieve data even in background.

**Comment by nuclearace** [comment]
How did you do it? It's not something I explicitly support.

**Comment by shoaibhussan** [comment]
Just added following lines of codes in appdelegate and it started work.
```
- (void)applicationDidEnterBackground:(UIApplication *)application {
    UIApplication *app = [UIApplication sharedApplication];
    UIBackgroundTaskIdentifier bgTask;
    bgTask = [app beginBackgroundTaskWithExpirationHandler:^{
        [app endBackgroundTask:bgTask];
    }];
}
```
