### ISSUE TITLE
Crashes with Xcode 8

### ISSUE THREAD

**Issue by Shayeeb** [socketio/socket.io-client-swift#547]
SocketExtension class function toJSON crashes because of optional data inside [Any].The below screenshot presents the data and the exact code line where it crashes.Please give the solution.Thanks
![screen shot 2016-10-21 at 12 36 39 am](https://cloud.githubusercontent.com/assets/22047032/19574129/8e1711a8-9726-11e6-80c7-620f8d55c696.png)
]

**Comment by nuclearace** [comment]
Are you trying to send optionals inside of json? Because that will fail. JSONSerialization can't handle Optional. You have to make sure you only send values that can be in JSON, or NSNull.

**Comment by Shayeeb** [comment]
Im not sending the JSON optionals.Its how the updated library is functioning.I have the same project with Socket IO library version for swift 2 and its working fine.Its only when i updated the library to 3 its generating these optionals.

**Comment by Shayeeb** [comment]
Thanks for your help.Somehow a dictionary with optional phone number value was being created and it was creating the issue.
