### ISSUE TITLE
Crash due to race condition in SocketEngine.createWebsocketAndConnect

### ISSUE THREAD

**Issue by yxztj** [socketio/socket.io-client-swift#549]
(One of the crashes in #463 )
There are 2 threads calling createWebsocketAndConnect at the same time(when reconnecting), leading to race condition.

In engineHandleQueue thread, SocketEngine would recreate the websocket on SocketEngine.websocketDidDisconnect.
<img width="1024" alt="screen shot 2016-10-19 at 4 19 19 pm" src="https://cloud.githubusercontent.com/assets/3334458/19584156/f5dab620-9774-11e6-9eb9-841a2fbdb22d.png">

Meanwhile, on main thread SocketIOClient is also creating websocket in _tryReconnect:
<img width="1282" alt="screen shot 2016-10-19 at 4 19 26 pm" src="https://cloud.githubusercontent.com/assets/3334458/19584162/feb85d1a-9774-11e6-9d26-6fa26fd04b2e.png">

Should there be a lock?

**Comment by nuclearace** [comment]
That doesn't make sense though, unless maybe reconnect wait is like 0? That is the only way I could think those queues would clash from that method.

**Comment by kikolobo** [comment]
I think this is very possible... Even if wait time is not 0.. Remember that race condition does not mean that things happen at the same time, it means that the same thing happens on multiple threads. So I guess this method should only be called from one thread?

**Comment by yxztj** [comment]
@nuclearace We are using default parameters for socket io client. I tried but still don't have a solid repro for this, since race condition is a random edge case. But we are facing this issue for several months. I couldn't find a clue until reviewing all threads in the crash report.

Can we limit that websocket creating could only been performed on specific thread? Or is there any particular consideration when _tryReconnect decides to dispatch on the main thread?

**Comment by yxztj** [comment]
@nuclearace Sorry for pushing but this is currently the No.1 crash in our app(over 1k incidents). Can we have a quick fix or workaround for the issue? Thanks.

**Comment by nuclearace** [comment]
I currently don't have enough bandwidth to investigate this thoroughly. And this could take some effort to debut. If it's only a problem with polling you could try forcing websockets. But beyond that idk

**Comment by nuclearace** [comment]
My other workaround is what I did for the app I made this for. I turned off automatic reconnecting, and instead handled reconnecting myself.

**Comment by yxztj** [comment]
@nuclearace Thanks. I'm turning off the automatic reconnecting too and see if the amount of crashes gets down.

**Comment by nuclearace** [comment]
Probably fixed in the DispatchQueue refactors.
