### ISSUE TITLE
socket.io-client-swift optimize upload image speed

### ISSUE THREAD

**Issue by beobungbu** [socketio/socket.io-client-swift#550]
I'm maintaining an iOS Application, it have a function to allow user streaming and chat, send image like Facebook live.

At send image method, someone who did it before was encode UIImage taken from camera or library to base64 string and add to NSDictionary, then they emit to socket. I think it is bad idea because base64 heavier than NSData, and send to server at one time.

I think i can separate binary data to n parts then emit to server at one time, then, server receive and join all of them to image file. I think it will faster than normal emit.

but in fact, i have no experience with socket, so i don't know my solution will good or not. So, how do you think about it ? Do you have any idea for speed up upload process?

**Comment by nuclearace** [comment]
You'd have to test it out.
