### ISSUE TITLE
file upload in socket.io

### ISSUE THREAD

**Issue by patriksharma** [socketio/socket.io-client-swift#551]
Hello,
I'm building chat App , Now I need to upload file to server. 

I tried creating bytearray , NSdata but none of them working in upload.

Can anyone please share example of uploading file to server

**Comment by patriksharma** [comment]
@nuclearace  why closed that issue ? I never received any response on that ?

**Comment by nuclearace** [comment]
What do you mean none are working in upload? You should be able to send the file by turning it into NSData and sending that.

```swift
guard let a = try? Data(contentsOf: myURL) else { return }

socket.emit("event", a)
```

**Comment by alibinpasha** [comment]
I have a question related to this ? 
I am currently working on Chat Application, how can i send my Image file as buffer
