### ISSUE TITLE
Xcode 8 + Swift 2.3

### ISSUE THREAD

**Issue by pikciu** [socketio/socket.io-client-swift#553]
Hi,
I can not build SocketIO in Xcode 8.0. I used branch 2.3 `pod 'Socket.IO-Client-Swift', '= 7.0.3'`. My project is written in Swift 2.3.
![screen shot 2016-10-25 at 15 43 56](https://cloud.githubusercontent.com/assets/7328289/19688408/df30f44a-9ac9-11e6-9f32-a206fdd601ab.png)

**Comment by nuclearace** [comment]
You need the Swift2.3 branch.

**Comment by nuclearace** [comment]
Also, you should move to swift 3 asap. Swift 2.3 is just meant to be a temporary version while you update to 3. And I'll likely be dropping support for it in the future.

**Comment by pikciu** [comment]
I think you should update your README :P 
`pod 'Socket.IO-Client-Swift', '= 7.0.3'`
didn't work for me (idk why). I had to use:
`pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift2.3'`
Funny thing is that in both cases it installed v7.0.3...

I cannot update to swift 3. I'm using few pods and not all of them supports swift 3 :/
Anyway thanks for info.
