### ISSUE TITLE
Objective-C - emitWithAck:with:timeOutAfter:callback selector not available

### ISSUE THREAD

**Issue by partikles** [socketio/socket.io-client-swift#555]
When we try to add emitWithAck
```
[[socket emitWithAck:@"canUpdate" with:@[@(cur)] timingOutAfter:0 callback:^(NSArray* data) {
        [socket emit:@"update" withItems:@[@{@"amount": @(cur + 2.50)}]];
    }];
```
 got following error

**No visible @interface for 'SocketIOClient' declares the selector 'emitWithAck:with:timingOutAfter:callback'**

Not sure to add callback method for emitWithAck selector

**Comment by nuclearace** [comment]
I might have goofed the readme. It's not one method. Check the swift version and you'll clearly see it's two methods.

**Comment by nuclearace** [comment]
Yeah looks like I messed up the objc example on the readme

**Comment by partikles** [comment]
Thanks. I don't know much about swift. May I know, how to add callback method in Objective-C version.

**Comment by nuclearace** [comment]
I don't know objc that well. But emitWithAck returns an object that you call timingOutAfter on.

**Comment by partikles** [comment]
I think this the correct version of Objective-C in readme file
```
[socket on:@"currentAmount" callback:^(NSArray* data, SocketAckEmitter* ack) {
             double cur = [[data objectAtIndex:0] floatValue];
             
             OnAckCallback *callback = [self.socket emitWithAck:@"canUpdate" with:@[@(cur)]];
             
             [callback timingOutAfter:0 callback:^(NSArray* data) {
                 [socket emit:@"update" with:@[@{@"amount": @(cur + 2.50)}]];
            }];
              [ack with:@[@"Got your currentAmount, ", @"dude"]];
            }];
```
