### ISSUE TITLE
Last iOS version Swift3 compatible not accessible via Cocoapods

### ISSUE THREAD

**Issue by martinprot** [socketio/socket.io-client-swift#556]
We're very annoyed here.
By installing Socket.io framework with Cocoapod, which is the commonest way to install iOS frameworks, we end up with a Swift < 2.3 version.
My cocoapods version is 1.1.1

Our project is in Objective-c

We produced the problem on a blank project. 
[SocketTest.zip](https://github.com/socketio/socket.io-client-swift/files/557991/SocketTest.zip)

Here's the Podfile: 

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'SocketTest' do
    pod "Socket.IO-Client-Swift"
end
```

Cocoapods says `Using Socket.IO-Client-Swift (8.1.0)`, which is the latest version. but Xcode wants to convert the lib to Swift 2.3 or Swift 3, and is unable to compile sources. [According to your Cocoapod page](https://cocoapods.org/pods/Socket.IO-Client-Swift), 8.1 should be written in Swift 3.

This is a very annoying problem because impossible to revert anything.

**Comment by nuclearace** [comment]
Not sure what to say. 8.1 is most defiantly written in swift 3. And I was able to validate and push the update with whatever the current version of cocoapods is

**Comment by martinprot** [comment]
Hi
Please try with the Xcode project enclosed in my previous message.
I tried to manually include socket.io sources in my project. Xcode tries to convert to Swift 3, and says "no source need to be changed", and it compiles correctly.
I have the feeling there's a problem with the cocoapod project configuration

Ah, and i'm using XCode 8.1 GM, don't know if related.

**Comment by nuclearace** [comment]
Might be. Usually have to create a new branch for new versions. 8.1 might be using swift 3.0.1 which is why it'd want to update.

**Comment by nuclearace** [comment]
Oh I see. I think I PR had this fixed. I'll test development, and if it's fixed there I'll merge development and bump the version.

**Comment by nuclearace** [comment]
Looks like development fixes some issues, I'l merge it.

**Comment by martinprot** [comment]
Thanks for your feedback, please tell me when it's merged !

**Comment by nuclearace** [comment]
It was merged a few days ago.

**Comment by martinprot** [comment]
Yes, I can confirm, the problem is solved ! 👍
