### ISSUE TITLE
Module 'SocketIO' not found

### ISSUE THREAD

**Issue by vadimlukutin** [socketio/socket.io-client-swift#559]
When Integrate SocketIO from CocoaPods or from Framework project I have in both situations error (Module 'SocketIO' not found).

**Comment by nuclearace** [comment]
What version are you using?

**Comment by lazarte** [comment]
Using Socket.IO-Client-Swift (6.1.2) from pod have this issue

**Comment by pkuhonker** [comment]
I also has the problem .Fixed?

**Comment by TestSmirk** [comment]
this same to me. Fixed?

**Comment by TestSmirk** [comment]
restart XCode is fine to use `. xcworkspace ` file.
