### ISSUE TITLE
Compile Error While integrating the Swift client into Objective C Project.

### ISSUE THREAD

**Issue by Harigharan** [socketio/socket.io-client-swift#56]
I am getting many compilation error in that Swift client while integrating the Swift client into Objective C Project. And also i checked with the sample project "https://github.com/nuclearace/socket.io-client-swift-example" that also have same compilation issues.

can you guide how to resolve this issue?

**Comment by nuclearace** [comment]
What version of Xcode are you using.

**Comment by Harigharan** [comment]
I am using XCode 6.2.

**Comment by nuclearace** [comment]
That's why, I updated the project for Swift 1.2, which requires the Swift compiler in Xcode 6.3. If you can't upgrade to 6.3 you'll have to use the last Swift 1.1 release.

https://github.com/socketio/socket.io-client-swift/releases/tag/v1.5.2

**Comment by Harigharan** [comment]
Thanks for the quick response. I will update my xcode to 6.3 and update you.

**Comment by Harigharan** [comment]
I updated the XCode Version to 6.3. compilation issues is fixed. thanks for the information..
