### ISSUE TITLE
Crash at init on Xcode 8.1 with Swift 3.0.1

### ISSUE THREAD

**Issue by bogdanbalta** [socketio/socket.io-client-swift#560]
Since updating to Xcode 8.1 it crashes with EXC_BAD_ACCESS(code=1, address=0x20) on initialization in SocketIOClient.swift at property declaration:
private let logType = "SocketIOClient".

Note: I am using Objective C initializer: 
(nonnull instancetype)initWithSocketURL:(NSURL * _Nonnull)socketURL config:(NSDictionary * _Nullable)config;
and sending valid NSURL and NSDictionary objects.

**Comment by nuclearace** [comment]
Are you using a sessionDelegate config option? Might be related to #552

**Comment by bogdanbalta** [comment]
It was an issue after updating pods, it was badly compiled. Cleaning, remaking and recompiling pods project after update from 8.0.2 to 8.1.1 fixed this issue.
