### ISSUE TITLE
if write use_frameworks! in cocopods,the network indicator will never end

### ISSUE THREAD

**Issue by huangrun** [socketio/socket.io-client-swift#561]
My project is wrote in objective-C ,and managed by cocopods,I have to write use_frameworks! in podfile if i install this libary,but when i have done this,i found the network indicator will never end,And if i import it manually and remove use_frameworks words in the podfile,it works well. BTW.i use [AFNetworkActivityIndicatorManager sharedManager].enabled = YES;Thans!

**Comment by nuclearace** [comment]
What?

**Comment by huangrun** [comment]
The network indicator in the status bar is rotating all the time because i use cocodpods to install the library,I find that install the library manually will solve the problem.I want to know whether someone have the problem? and how to solve it perfectly,thanks!

**Comment by nuclearace** [comment]
I'm not sure that it'd be this library... I try not to do anything that is tied to a specific platform.
