### ISSUE TITLE
My app is keep crashing at engineDidClose () (SocketIOClient.swift:258)

### ISSUE THREAD

**Issue by jfalexvijay** [socketio/socket.io-client-swift#562]
Hi,

      Yesterday, I have updated socket io library in my app. Now I am keep getting a crash.

Is there any quick fix for it ? ("engineDidClose () (SocketIOClient.swift:258)")

    Crash Report:
Hardware Model: iPhone7,2
Process: MyApp [1478]
Path: /var/containers/Bundle/Application/1F9E9E78-183E-49CA-9AFC-391C2B88C79C/MyApp.app/MyApp
Identifier: com.MyApp.MyApp
Version: 3
Marketing Version: 1.2
Code Type: ARCHITECTURE_UNKNOWN

Date/Time: 2016-11-03 17:19:19 +0000
OS Version: 10.0.2 (14A456)
Report Version: 104

Exception Type: SIGTRAP
Exception Codes: TRAP_BRKPT at 0x186e25f60

Crashed Thread

0	libdispatch.dylib 0x1cdb84d0 _dispatch_barrier_sync_f_slow + 520
!	MyApp 0x0023d3d0 engineDidClose () (SocketIOClient.swift:258)
2	MyApp 0x00237fd8 _TToFC4MyApp14SocketIOClient14engineDidClosefT6reasonSS_T__merged + 50
3	MyApp 0x0025b6d4 closeOutEngine () (SocketEngine.swift:172)
4	MyApp 0x0025c3d8 disconnect () (SocketEngine.swift:0)
5	MyApp 0x00258914 _TToFC4MyApp12SocketEngine8didErrorfT6reasonSS_T__merged + 50
6	MyApp 0x0023b7b0 didDisconnect () (SocketIOClient.swift:188)
7	MyApp 0x0027b38c handlePacket (pack) (SocketIOClient.swift:0)
8	MyApp 0x0027bea0 parseSocketMessage () (SocketParsable.swift:0)
9	MyApp 0x00240ad4 partial apply forwarder for MyApp.SocketIOClient.(parseEngineMessage (Swift.String) -> ()).(closure #1) (SocketParsable.swift:0)
10	libdispatch.dylib 0x1cda9097 _dispatch_call_block_and_release + 8
11	libdispatch.dylib 0x1cdb5ec5 _dispatch_queue_serial_drain + 838
12	libdispatch.dylib 0x1cdac379 _dispatch_queue_invoke + 564
13	libdispatch.dylib 0x1cdb635d _dispatch_queue_override_invoke + 284
14	libdispatch.dylib 0x1cdb7a91 _dispatch_root_queue_drain + 376
15	libdispatch.dylib 0x1cdb78b7 _dispatch_worker_thread3 + 104
16	libsystem_pthread.dylib 0x1cf5d947 _pthread_wqthread + 1166
17	libsystem_pthread.dylib 0x1cf5d49c start_wqthread + 6

**Comment by wenssh** [comment]
Came up with the same crash, the version is 8.1.1

**Comment by MeGaPk** [comment]
+1, in 8.1.1 i have same problem
But maybe solution.... In engineDidClose() method just comment self.waitingPackets.removeAll()

**Comment by MeGaPk** [comment]
Update:
I get same crash, when server send data, like "Your auth data failed" and make disconnect.

**Comment by ridvank** [comment]
I have the same issue here on XCode 8.1. App is crashed when disconnect.

**Comment by oinsider** [comment]
Same here

**Comment by nuclearace** [comment]
Should be fixed in 8.1.2

**Comment by kirualex** [comment]
any way to mitigate the crash in the meantime?
