### ISSUE TITLE
I have problem with swift 2.3 in xcode 8.1

### ISSUE THREAD

**Issue by kilirushi** [socketio/socket.io-client-swift#566]
![screen shot 2016-11-07 at 9 05 02 pm](https://cloud.githubusercontent.com/assets/17327812/20060476/e5462314-a52d-11e6-87dc-648005e2b6db.png)
![screen shot 2016-11-07 at 9 04 19 pm](https://cloud.githubusercontent.com/assets/17327812/20060454/d20fed84-a52d-11e6-9183-d71722999ced.png)

**Comment by nuclearace** [comment]
You need the swift 2.3 branch, not 7.0.3.

**Comment by kilirushi** [comment]
Thanks you so much. I fixed it.
