### ISSUE TITLE
Socket emit issue

### ISSUE THREAD

**Issue by ali-nawaz-dev** [socketio/socket.io-client-swift#569]
Hi,

I need help on this, I am emitting data over socket and getting these logs, can i get help on this please. 

[893:83130] LOG SocketIOClient: Emitting: 2["chat message","12","HI"]
2016-11-09 11:43:40.988 XXXX [893:83130] LOG SocketEngine: Writing ws: 2["chat message","12","HI"] has data: false

**Comment by nuclearace** [comment]
Those logs look like the emit is working. What's the issue?

**Comment by ali-nawaz-dev** [comment]
Thanks for response.. I have connected socket with server as this

stIOsocketClient = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"log": @YES, @"forcePolling": @NO,@"forceNew":@YES, @"connectParams": @{@"ns": @"/company/1"}}];

It made connection with server and start emitting but server has no data or request to receive.
Please note "/company/" is a namespace.
