### ISSUE TITLE
How to upload image to server

### ISSUE THREAD

**Issue by patriksharma** [socketio/socket.io-client-swift#570]
Hello ,

I have to upload image to server.
this is my payload
`{ type: “IMAGE”, data: { size: Long, name: String, modifiedOn: String, file: ByteArray } }
`
When i try to send bytearray as NSData of UIImage. Its not working and start showing me binary data.

Bit confused. Didn't found any good example of uploading image to server, please help

**Comment by nuclearace** [comment]
Where does it show binary data? And how are you sending "bytearray  as NSData of UIImage"? You'll want to turn that UIImage into a png, jpg or some other kind of image representation before you send it. You can google how to do that. But once you have NSData representing the image in a common format, you can send that. And then the server/other clients can do with that what they want.
