### ISSUE TITLE
Can't emit a dictionary

### ISSUE THREAD

**Issue by vshahpledge** [socketio/socket.io-client-swift#571]
Our socket.io api is expecting a dictionary as the top level object, but all of the emit calls in socket.io-swift only accept an array of items.

Server is expecting
```
    {
        token: abcdefg
        version: 1.1.0
    }
```

Server is getting
```
    [{
        token: abcdefg
        version: 1.1.0
    }]
```

Proposal: add another emit method that accepts non-array items.

**Comment by nuclearace** [comment]
How are you emitting?

**Comment by vshahpledge** [comment]
My emit call looked like this:
```
    let authDict = ["token": self.keychainManager.token,
                            "version": "1.1.0"]
    self.io.emit("authentication", authDict)
```

**Comment by vshahpledge** [comment]
I've submitted a PR: #572

**Comment by vshahpledge** [comment]
You can see the issue here:

```
public func emit(_ event: String, _ items: SocketData...) {...}
public func emitWithAck(_ event: String, _ items: SocketData...) -> OnAckCallback {...}
```

both emit methods only accept arrays of SocketData.

**Comment by nuclearace** [comment]
Right but that's because you can do

```javascript
socket.emit("someEvent", 1, {"test": 1}, true)
```

And then do

```javascript
socket.on("someEvent", (int, obj, bool) => { })
```

In JavaScript.

**Comment by nuclearace** [comment]
If you're getting something enclosed in an array that means something is broken with the encoder. Either they've changed the socket.io protocol on me or something else is going on.

**Comment by vshahpledge** [comment]
In Swift when you do that it wraps everything in an items array. If you look at the source, the emit method forwards its call to something a little more explicit:

```
/// Sends a message to the server, requesting an ack. Use the onAck method of SocketAckHandler to add
/// an ack.
public func emitWithAck(_ event: String, _ items: SocketData...) -> OnAckCallback {
        return emitWithAck(event, with: items)
}
```

The method it's calling (the one defined for use in Objective-C) only accepts an array of items:

```
public func emit(_ event: String, with items: [Any])
```

**Comment by nuclearace** [comment]
Right, and in the socket.io protocol data is the format `2["someEvent", arg1, arg2, arg3]`. Which is why I do https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClient.swift#L211.

So that when it gets to https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketPacket.swift#L89 it turns it into that proper format.

**Comment by nuclearace** [comment]
And there are tests for the parsing and encoding, so I would hope I would catch failures if it's a code change that broke something.

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/blob/master/SocketIO-MacTests/SocketBasicPacketTest.swift#L48

**Comment by vshahpledge** [comment]
Turns out I was calling the wrong method in my own code. Instead of calling [this](https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClient.swift#L200) I should've been calling [this](https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClient.swift#L205) from my own methods since my own method already wrapped the arguments in an array.

I apologize for my hastiness. Thanks for helping me troubleshoot this.

**Comment by nuclearace** [comment]
Yeah the reason there are two methods is to take advantage of Swift's variadic parameters so make the api more like the JavaScript client.
