### ISSUE TITLE
Connect Local server through SSL

### ISSUE THREAD

**Issue by AlexCai21** [socketio/socket.io-client-swift#573]
Hi, I have a question about SSL. The condition is like this:
I have two connections in app, one is connected to the server in WAN through domain, this domain is `https://abc.com`.
Other connection is connected to the local hardware in LAN through IP Address, this IP Address can be 'https://192.168.10.10', 'https://192.168.10.11' and any address, address and hostname are dynamic.

The domain of SSL certificate is 'abc.com'.

 When I connect to WAN server through SSL, it's successfully.
 But when I connect to LAN device through SSL, it's also alert me 'CFNetwork SSLHandshake failed (-9807)'.

So I want to know when I connect to local IP Address, what steps do I need to config? Or do I use SSL without mandatory authentication certificate domain name?
Thanks.

**Comment by nuclearace** [comment]
Might have to setup some exception for TLS for that domain. Apple's security requirements are pretty strict. Pretty much everything on iOS needs to be SSL.
