### ISSUE TITLE
How to send token with objective c code?

### ISSUE THREAD

**Issue by alims** [socketio/socket.io-client-swift#574]
I tried for send token this code but not found "options or opts" method

> self.socket = [[SocketIOClient alloc] initWithSocketURL:@"http://localhost/" options:@{@"connectParams": @{@"foo": @"bar", @"this": @"that"}}

I want to send token into _query? 

>   _query: 
   { transport: 'polling',
     b64: '1' },

How to send token  with this code?
> `    SocketIOClient* socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"token": @"q23432423ksd23jwkdjsjdkjsdk"}];`

**Comment by mohammedalicelik** [comment]
use .extraHeaders

**Comment by alims** [comment]
I used "connectParams".Its worked.Thx for your solution
