### ISSUE TITLE
How can i catch the socket timeout in emitWithAck

### ISSUE THREAD

**Issue by iHunterX** [socketio/socket.io-client-swift#580]
i tried to research about it but no result, can you show me how can I know when the request time out 

right now im using this method

>                 `if str == "NO ACK" {
>                     ////No response data goes here!!!!
>                     isErrorString = "No data"
>                     completionHandler(false,isErrorString)
>                 } else {
>                     ////response data goes here!!!!
>                     guard let avail = Resp.firstObject as? Bool else {return}
>                     isErrorString = nil
>                     completionHandler(avail,isErrorString)
>                 }`
>

**Comment by Meonardo** [comment]
@iHunterX I set the request timeout interval by myself.
I store the request object in a container object, when I got a response I remove it from its container.
So the timeout count down by 0, I check the object if it exist in the container, if it do exist I define the request is TIMEOUT.(I m new to this if there is a callback method do tell me!)
