### ISSUE TITLE
fatal error: cannot increment beyond endIndex

### ISSUE THREAD

**Issue by vivalei** [socketio/socket.io-client-swift#583]
parsePollingMessage crash: fatal error: cannot increment beyond endIndex.

**Comment by nuclearace** [comment]
Need more information than this.

**Comment by WangBoX** [comment]
step：
1、this.parsePollingMessage(str)

2、let str = reader.read(count: n)
                
                handleQueue.async { self.parseEngineMessage(str, fromPolling: true) }

3、let readString = message[currentIndex..<message.characters.index(currentIndex, offsetBy: count)]
crash：fatal error: cannot increment beyond endIndex

**Comment by shacharudi** [comment]
Did anyone found a solution for this?

**Comment by nguyenhunga5** [comment]
I have same error :(

**Comment by vivalei** [comment]
temporary handle:       
        let currentPosition = message.distance(from: message.startIndex, to: currentIndex)
        let totalLength = message.distance(from: message.startIndex, to: message.endIndex)
        let maxCount = min(count, totalLength - currentPosition)
        
        let readString = message[currentIndex..<message.characters.index(currentIndex, offsetBy: maxCount)]

**Comment by vivalei** [comment]
**temporary handle：**
```
   let currentPosition = message.distance(from: message.startIndex, to: currentIndex)
        let totalLength = message.distance(from: message.startIndex, to: message.endIndex)
        let maxCount = min(count, totalLength - currentPosition)
        
        let readString = message[currentIndex..<message.characters.index(currentIndex, offsetBy: maxCount)]
        
        advance(by: maxCount)
```

**Comment by vivalei** [comment]
Check your socketIO client configure follow your server:
For example，
@"forcePolling":@NO,
@"forceWebsockets":@YES,

**Comment by nuclearace** [comment]
Probably related to #716
