### ISSUE TITLE
Unable to setup socket1.6.0 for ios version of objective C

### ISSUE THREAD

**Issue by pankug** [socketio/socket.io-client-swift#584]
I am using Socket.io v1.6.0 for my server side .able to make it configure for my website.
However, when we try to access it from iOS App (objective c) with server URL, I am receiving following error. 

**We are able to connect to demo servers ws://sandbox.kaazing.net/echo and wss://echo.websocket.org through App .** 

I am using socket.io-objc library for iOS.

Error  : 
Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 502" UserInfo={NSLocalizedDescription=received bad response code from server 502, HTTPResponseStatusCode=502}

We have tried using the socket-client-swift library in our App. But It seems that it is written in 3.0.1 Swift. My Xcode supports only 3.0.0 so I am  unable to integrate it in our App.

**Comment by nuclearace** [comment]
Upgrade Xcode then? And what library are you using? This library or some other library?
