### ISSUE TITLE
tcp ip example

### ISSUE THREAD

**Issue by zaferaydn** [socketio/socket.io-client-swift#585]
hello there.

i feel socketioclient supports only web sockets. if not, how can i connect to a tcp server with an ip address and port simply?

SocketIOClient constructor takes URL type. When i wrote "ip:port" instead of http, logs tell that "App Transport Security has blocked a cleartext HTTP..." and it cannot connect to the server.

can you direct me to an example which uses ip address and tcp port to connect to a tcp server?

thanks.

**Comment by nuclearace** [comment]
This library isn't a raw socket library. It's for socket.io.
