### ISSUE TITLE
Timeout interface.

### ISSUE THREAD

**Issue by adevios** [socketio/socket.io-client-swift#587]
Could you increase web socket timeout up to 15-30 sec please or better provide some interface for doing this? Now it’s hardcoded to 5 sec and on “weak” networks it always fails to connect (5%+ packet loss).

Suggestions:
1) increase timeout up to 15-30 sec.
2) provide an interface for configuring.

Thanks in advance!

**Comment by ffleandro** [comment]
Is anyone working on this or could point me in the right direction?
This is a must have when using weak connections, on the `socke.io-java-client` we have the following properties:

```
val opts = IO.Options()
opts.reconnection = true
opts.reconnectionDelay = 2000
opts.timeout = 60000
```
