### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by fulang0208** [socketio/socket.io-client-swift#588]
i user swift 3 version, if i set double encode utf8 true, the Chinese string will be a unreadable code when created post string, like this:
`Created POST string: 118:42["join.room",{"target":{"room":"fbcf75c7b408e5e1fb061e92b173e924"},"userType":"student","userName":"æµè¯è§ç1"}]`

**Comment by nuclearace** [comment]
Indeed, because socket.io double encodes strings for some reason. If you're not using the node.js based server you can turn that off.

**Comment by nuclearace** [comment]
It should still be received by the server correctly.

**Comment by fulang0208** [comment]
thanks, i have resolve this problem,  i set force polling false, it correct
