### ISSUE TITLE
Socket is not working in 3G always reconnects coming

### ISSUE THREAD

**Issue by sarankumar291** [socketio/socket.io-client-swift#589]
Iam using config List <==> config: [.reconnects(false), .forceNew(true)])
Please help me

**Comment by nuclearace** [comment]
What exactly is happening?

**Comment by sarankumar291** [comment]
@nuclearace Socket is stable on good internet connection like on 4g and faster wi-fi but when the device is connected to slower network, 3g and 2g socket connection is unstable. its getting disconnecting and reconnecting often.
