### ISSUE TITLE
App crashes as "doDisconnect (error) (WebSocket.swift:153)"

### ISSUE THREAD

**Issue by jfalexvijay** [socketio/socket.io-client-swift#592]
I am using v.8.1.2. Sometime my app is crashing in websocket.swift line 153. 
I don't have any exact scenario to reproduce this issue. Please help me on this.

Name	: SIGSEGV
Reason	: SEGV_MAPERR

    Crashed Thread

0	libobjc.A.dylib 0x0000000182b85bd0 objc_msgSend + 12
!	1	MyApp 0x00000001001c2ac8 doDisconnect (error) (WebSocket.swift:153)
2	MyApp 0x00000001001c5940 processOneRawMessage () (WebSocket.swift:0)
3	MyApp 0x00000001001bcd28 processRawMessagesInBuffer (pointer, bufferLen) (WebSocket.swift:0)
4	MyApp 0x00000001001bc560 dequeueInput () (WebSocket.swift:466)
5	MyApp 0x00000001001bc344 processInputStream () (WebSocket.swift:444)
6	MyApp 0x00000001001c66a4 stream (aStream, eventCode) (WebSocket.swift:390)
7	MyApp 0x00000001001bc138 stream () (WebSocket.swift:0)
8	CoreFoundation 0x000000018345a644 _signalEventSync + 188
9	CoreFoundation 0x00000001834c9f04 ___signalEventQueue_block_invoke + 20
10	libdispatch.dylib 0x0000000182f59630 _dispatch_call_block_and_release + 20
11	libdispatch.dylib 0x0000000182f595f0 _dispatch_client_callout + 12
12	libdispatch.dylib 0x0000000182f65634 _dispatch_queue_drain + 860
13	libdispatch.dylib 0x0000000182f5d0f4 _dispatch_queue_invoke + 460
14	libdispatch.dylib 0x0000000182f67504 _dispatch_root_queue_drain + 724
15	libdispatch.dylib 0x0000000182f67224 _dispatch_worker_thread3 + 108
16	libsystem_pthread.dylib 0x000000018316d470 _pthread_wqthread + 1088
17	libsystem_pthread.dylib 0x000000018316d020 start_wqthread + 0

**Comment by nuclearace** [comment]
You'll need to find a reproducible case. If you can find one then you should open an issue on the websocket's repo.

**Comment by jfalexvijay** [comment]
Sorry, I forgot to mention... It is not happening in my phone.. It is happening only in my customers phone. I for this using a bug reporter API.

I will try to find out how to reproduce this issue.
