### ISSUE TITLE
init can not succeed

### ISSUE THREAD

**Issue by hsh0107** [socketio/socket.io-client-swift#597]
in swift 3.0 I init like this
   SocketInstance = SocketIOClient.init(socketURL: URL.init(string: NetWork.ShareInatance.urlPath("socketConnet", type: .socket))!, config: [SocketIOClientOption.connectParams((dic as? [String : AnyObject])!)])

can not succeed

**Comment by hsh0107** [comment]
log error

**Comment by hsh0107** [comment]
in swift 2.3 I init like this
 SocketInstance = SocketIOClient(socketURL: URL(string: NetWork.ShareInatance.urlPath("socketConnet",type:.socket))!, options: [SocketIOClientOption.connectParams(dic as! [String : Any])])

**Comment by nuclearace** [comment]
What is the error?

**Comment by hsh0107** [comment]
just print error, I dou not know

**Comment by nuclearace** [comment]
Doing someone like

```swift
let instance = SocketIOClient(socketURL: URL(string: "")!, config: [.connectParams([:])])
```

works.

**Comment by hsh0107** [comment]
in swift 3.0 let instance = SocketIOClient(socketURL: URL(string: "")!, config: [.connectParams([:])]) can not work

**Comment by nuclearace** [comment]
It works for me. Are you on the latest version?

**Comment by hsh0107** [comment]
Yes，in swift 2.2 let instance = SocketIOClient(socketURL: URL(string: "")!, config: [.connectParams([:])]) ，it work，but I write with swift 3.0 I init let instance = SocketIOClient(socketURL: URL(string: "")!, config: [.connectParams([:])]) can not work，it does not work
