### ISSUE TITLE
SSLCert not visible in Objective-C code

### ISSUE THREAD

**Issue by monobono** [socketio/socket.io-client-swift#598]
When using the SSLCert class: 
`SSLCert *cert = [[SSLCert alloc] initWithData:certData];`

I get the following error:
`Use of undeclared identifier 'SSLCert'`

The Socket.io client is integrated via CocoaPods. All other classes work fine and are visible in Objective-C files.

**Comment by nuclearace** [comment]
I'll fix that. It should be noted however that the WebSocket library I use _is not_ written to be Objective-C compatible. So if you're using things from it, I would highly recommend using Swift.
