### ISSUE TITLE
Sometimes, the Chinese message that sended to server is mojibake

### ISSUE THREAD

**Issue by DreamcoffeeZS** [socketio/socket.io-client-swift#599]
Sometimes, the Chinese message that sended to server is mojibake. How can I solve the problem?

**Comment by nuclearace** [comment]
Is this a node.js server? Is it getting to the server garbled or is it just the log that looks messed up? socket.io currently double encodes utf-8. Although that should be getting fixed soon.

**Comment by DreamcoffeeZS** [comment]
I send the  same chinese character sometimes it is correctly returned, sometimes it is messed up. 
the message in http request is ok but when nodejs received , log print  or  send back are all messed up. And I can't find a patten how to repeat the bug. Sometimes ok sometimes not. half half chance

**Comment by nuclearace** [comment]
You can try adding `.forceWebsockets(true)` to the config. That should avoid the double encoding problem. What version of socket.io are you on?

**Comment by DreamcoffeeZS** [comment]
forceWebsockets(true)  DoubleEncodeUTF8 all tried, doesn't  work. problem still there. I am using v8.2.0 iOS  client.

**Comment by nuclearace** [comment]
What version of the server?

**Comment by DreamcoffeeZS** [comment]
latest version

**Comment by lazybetrayer** [comment]
I have the same problem, but in my case `.forceWebsockets(true)` fixes the problem.

**Comment by shacharudi** [comment]
I was having similar problems sending Emoji and Hebrew characters, using .forceWebsockets(true) solved it. thanks!

**Comment by nuclearace** [comment]
socket.io 2.0 fixes some unicode issues.
