### ISSUE TITLE
How to get parameters of connection event?

### ISSUE THREAD

**Issue by oney** [socketio/socket.io-client-swift#60]
On app
```
socket.connectWithParams(["token": "ABAE1W14YUEYT"])
```

My question is how to get parameters on server
```
io.on('connection', function (socket) {
  console.log('connection param: ' + socket.handshake.query.token);
});
```
Is it right?

**Comment by yannickl** [comment]
Yes you can retrieve parameters via the `socket.handshake.query` property in the connection `callback`.

If you want use a middleware (e.g. for authentication) you will need to follow this one:

```javascript
io.use(function (socket, next) {
    var token = socket.request._query.token;
}
```

It works fine for me.
