### ISSUE TITLE
Socket.IO malloc: *** error: can't allocate region

### ISSUE THREAD

**Issue by Saulenco** [socketio/socket.io-client-swift#600]
Hi I have some issue dequeueInput function
![3bc16a82-b195-11e6-994f-836f850466fe](https://cloud.githubusercontent.com/assets/8323284/21347309/b6a0e6bc-c6b0-11e6-8c3c-beba1852647f.png)

as you can see in the image. The app works fine on the simulator but on real device i keep getting this crash.

i changed the: `var combine = NSData(data: fragBuffer) as Data`
into: `var combine:Data = fragBuffer`
but i guess that is not thread safe .

can you please suggest other solution?

**Comment by nuclearace** [comment]
Does this happen with large payloads? This is an issue with the websocket library itself.

**Comment by Saulenco** [comment]
the data that i receive is around the 2- 3 Mb
a small example 
`NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(2261002) failed`

**Comment by nuclearace** [comment]
https://github.com/daltoniam/Starscream/pull/289 Looks like a known issue.

**Comment by Saulenco** [comment]
Thanks dude that helped , i guess that my google search skills still suck :)
