### ISSUE TITLE
iOS App connected to server using Simulator but not through iPhone

### ISSUE THREAD

**Issue by bhatti-saqib** [socketio/socket.io-client-swift#609]
I am trying to connect iOS App with socket.io-client-swift to my local server. Connection is made successfully when on Simulator. But when I try to connect the server through iPhone, it doesn't connect.

**Comment by nuclearace** [comment]
Make sure you're using the correct host.

**Comment by Mekonom** [comment]
Connect your mobile phone to local network where your server runs , then get your server local ip , give this ip in your ios project as host.

**Comment by harianbu** [comment]
I had this same problem ..what I can do...
