### ISSUE TITLE
SocketIOClientConfiguration.swift won't compile

### ISSUE THREAD

**Issue by orensha** [socketio/socket.io-client-swift#612]
Hey, i'm using socket socket.io-client-swift-8.2.0 and cant compile it. im using Xcode version 8.2.1.
thats the error im getting.

![screen shot 2017-01-29 at 10 13 28 am](https://cloud.githubusercontent.com/assets/16323011/22402790/a6135c6a-e60b-11e6-9929-a84f08c17c69.png)

**Comment by MeGaPk** [comment]
@orensha can you please show your pod file for  example?

**Comment by orensha** [comment]
Hi, i didnt use pods, i dragged the source files to the projects. but i tried to use pods after your answer and got all of this errors
![screen shot 2017-01-30 at 6 03 30 pm](https://cloud.githubusercontent.com/assets/16323011/22430380/b50228c6-e716-11e6-8402-723aaf5f7e0b.png)

thats the pod file
![screen shot 2017-01-30 at 6 06 36 pm](https://cloud.githubusercontent.com/assets/16323011/22430443/ec8e527e-e716-11e6-8b48-23aa2a939c11.png)

**Comment by jaykon** [comment]
the same problem,is there any solution?

**Comment by jaykon** [comment]
i have the same problem when using cocoapod.
but everything is fine when i just download zip from github and copy files to my project.

**Comment by nuclearace** [comment]
Maybe cocoapods is setting the wrong swift version?
