### ISSUE TITLE
xcode 8.3 not compiling. Solution.

### ISSUE THREAD

**Issue by MeGaPk** [socketio/socket.io-client-swift#614]
For work socket io on xcode 8.3 beta, need:
In struct: SocketIOClientConfiguration
Rename from `Array<SocketIOClientOption>.Generator` to `Array<SocketIOClientOption>.Iterator`

**Comment by shams-ahmed** [comment]
@MeGaPk any chance you can submit a PR?

**Comment by nuclearace** [comment]
This should be fixed in development. I'll move it to master when 8.3 is released.

**Comment by MeGaPk** [comment]
@nuclearace thanks!

**Comment by SanjithKanagavel** [comment]
Is this fixed ? I still see this happening in xcode 8.3.

**Comment by nuclearace** [comment]
Make sure you're on the latest version

**Comment by yonivav** [comment]
happens to me too.
what should i do ?

**Comment by SanjithKanagavel** [comment]
Yes. It happened in latest version. You can unblock and make the changes compiler requests. And it should work.
