### ISSUE TITLE
Upload Image/Video via stream using Socket.io-stream server

### ISSUE THREAD

**Issue by SahebRoy92** [socketio/socket.io-client-swift#615]
So this is what my backend code looks like 

     socket.on('uploadimage', function (data) {
       console.log(data);
       stream = ss.createStream();
       ss(socket).emit('file', stream);
	   stream.pipe(fs.createWriteStream('uploadedfile.png'));
     }); 

I want to catch the backend stream`(ss(socket))` , in my native application(iOS) so that i can write the image data on it.

Is there any option to access the ss(socket) stream in the iOS native client side of the application? I want to use it for image/video upload. All I am getting option for emitting the whole data at once, which I think will not be a good option for sending large file.

http://stackoverflow.com/q/41958118/3755838

**Comment by nuclearace** [comment]
Does this even work in the js-client? I've never seen this done before.

**Comment by nuclearace** [comment]
Doesn't seem like it would, since you're passing some JavaScript object, instead of a JSON object.

**Comment by SahebRoy92** [comment]
Yes, It does work 
We are using this code in client JS to send the image through socket server from this - https://www.npmjs.com/package/socket.io-stream

     socket.emit('uploadimage', { my: 'data' });
       ss(socket).on('file', function(stream) {
       fs.createReadStream('abc.png').pipe(stream);
     });

**Comment by SahebRoy92** [comment]
From iOS when we are calling `socket.emit("uploadimage", "Test")` and we are getting this response

    SocketIOClient: Handling event: $stream with data: [file, {
    "$stream" = "a1ffe263-e821-4b19-a48d-6b22f8c275c9";
    }]
    SocketIOClient: Handling event: $stream-read with data: [a1ffe263-e821-4b19-a48d-6b22f8c275c9, 16384]

**Comment by nuclearace** [comment]
No, that isn't supported. That looks like an extension @nkzawa added on top of socket.io and socket.io-client, rather than a core aspect of socket.io. If it is a core feature I can look to implement it though.

I have no not looked at its implementation, but it probably does some wrapping around sending raw binary directly through socket.io, just exposing a stream interface.

**Comment by nuclearace** [comment]
If it is just an extension, you could probably reverse its protocol using this client. Or just build your own Swift version of it.

**Comment by SahebRoy92** [comment]
So, can you tell me the correct procedure to send image / stream video from iOS via Socketio? 
I have tried to compress image data and sent them directly but i am talking about large image ~2mb. What would be the correct approach?

**Comment by nuclearace** [comment]
Well, streaming video isn't something I'd do with socket.io in any case, you'd probably want to drop to raw UDP sockets and use RTP if you want to stream audio/video. But if you want to send images, you could split the data up if you're worried about it being too big. You just have to split it in a way you can reconstruct it.

**Comment by SahebRoy92** [comment]
So basically its all down to splitting data and sending them, reconstructing it in server side.
Using `emitData`. Ok that settles it then, I have been going nuts as to why isnt my iOS app cannot get the stream from my backend.

It settles it then I am closing this

**Comment by bhoopendrayash** [comment]
Does Socket.io provide video audio calls? Or it uses Any other protocol?

**Comment by Maverick-03** [comment]
Does it work with swift as well?
