### ISSUE TITLE
Compilation error in SocketTypes.swift

### ISSUE THREAD

**Issue by crickabhi** [socketio/socket.io-client-swift#616]
[SocketWithSwiftyJSON.zip](https://github.com/socketio/socket.io-client-swift/files/752079/SocketWithSwiftyJSON.zip)
I have added socket.io and swiftyjson manually to my project. But my app is not compiling and showing issue in SocketTypes.swift --> invalid redeclaration of JSON.
I have also attached the sample project.
<img width="956" alt="screen shot 2017-02-03 at 11 53 41 pm" src="https://cloud.githubusercontent.com/assets/10657329/22603198/5f6d89e2-ea6c-11e6-8369-01a99444083d.png">

**Comment by nuclearace** [comment]
Yeah if you manually add them like that JSON will conflict, it wasn't meant to be a public declaration.

**Comment by nuclearace** [comment]
You'll have to rename it.
