### ISSUE TITLE
crash on handle event

### ISSUE THREAD

**Issue by matanporeh** [socketio/socket.io-client-swift#617]
my app is using the latest socket.io swift client lib
i am getting error reports via crashlytics on the web socket class handle stream event method

Crashed: com.vluxe.starscream.websocket
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020

SocketIO	
WebSocket.swift line 0
@objc WebSocket.stream(Stream, handle : Stream.Event) -> ()

**Comment by hemanthalluri** [comment]
Could you please tell me how to include socket.io swift client lib in own project..?

**Comment by nuclearace** [comment]
This will probably be fixed in the refactoring being done for #661
