### ISSUE TITLE
Tried emitting newMessage when not connected swift

### ISSUE THREAD

**Issue by mhtranbn** [socketio/socket.io-client-swift#618]
Tried emitting newMessage when not connected swift, Hi everybody, i cant send message, when i try xcode log is: Tried emitting newMessage when not connected swift . Please support. Many thank.

**Comment by mhtranbn** [comment]
Many thanks @nuclearace 💯

**Comment by milan-mgu** [comment]
@mhtranbn  How did you solved ? please let me know.

**Comment by kinza88** [comment]
how did you solve this error? 
@nuclearace @mhtranbn @milan-mgu
