### ISSUE TITLE
Fix for excessive memory use caused by the receipt of an unusually large message

### ISSUE THREAD

**Issue by luzianscherrer** [socketio/socket.io-client-swift#619]
Could you please add https://github.com/daltoniam/Starscream/commit/3cc4a60e05dffaf280194d2a49ecfd5e921d74e5 for the next release of socket.io-client-swift? We are affected by the excessive memory use problem, it crashes with ```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(2807117) failed'```

**Comment by nuclearace** [comment]
Yep, it should already be in the development branch.
