### ISSUE TITLE
Carthage building error on 955ad84

### ISSUE THREAD

**Issue by hankbao** [socketio/socket.io-client-swift#62]
After fetching the latest commit (955ad8423fbf41c147b1434fdb0d6138db349da9) from carthage branch, got this building error:
`error: no such file or directory: '/SomeProject/Carthage/Checkouts/socket.io-client-swift/SocketIOClientSwift/SocketAckMap.swift'`

**Comment by nuclearace** [comment]
Try the latest version. I'm actually unsure on how to build for carthage. Carthage support was added by someone else

**Comment by hankbao** [comment]
Yep, the latest commit is OK now.

**Comment by nuclearace** [comment]
Can you actually incorporate the frameworks generated by carthage into a project? I tried once and it gave me some errors.

**Comment by hankbao** [comment]
I didn't get your point. In the carthage branch, SocketIO.xcodeproj has already contained the two frameworks as its targets.

**Comment by hankbao** [comment]
I've linked the iOS framework into my app and played it for a while. It's just fine. However I've not test the OS X framework.
