### ISSUE TITLE
ConnectParams socket 8.2.0

### ISSUE THREAD

**Issue by MarcSky** [socketio/socket.io-client-swift#623]
Hello!
I try to make connect with token. I use 
`public init(socketURL: URL, config: SocketIOClientConfiguration = [])`
but in body this func i dont see config connectParams. U a removed connectParams? How i can open connect with token?
`  var socket: SocketIOClient = SocketIOClient.init(socketURL: URL(string: RestApiURL.baseURL.rawValue)!, config: [.log(true), .connectParams(["token":"1"])])`

**Comment by nuclearace** [comment]
Connect should work. Have you turned on debugging on the server?
