### ISSUE TITLE
Crash socket after parseQueue

### ISSUE THREAD

**Issue by MeGaPk** [socketio/socket.io-client-swift#624]
Version: 8.2.0
How i get crash: Just run app, go home, after back to work, i see crash.

![screen shot 2017-03-01 at 09 07 50](https://cloud.githubusercontent.com/assets/892182/23449479/61f33110-fe5f-11e6-9d46-327b47590865.png)

![screen shot 2017-03-01 at 09 13 22](https://cloud.githubusercontent.com/assets/892182/23449565/dafc0f64-fe5f-11e6-8079-e9b970240706.png)
![screen shot 2017-03-01 at 09 13 04](https://cloud.githubusercontent.com/assets/892182/23449564/dafb8c2e-fe5f-11e6-9feb-c7ad617289a8.png)
![screen shot 2017-03-01 at 09 12 57](https://cloud.githubusercontent.com/assets/892182/23449563/daf990ea-fe5f-11e6-832f-f978b9962865.png)

Please look asap,  now i have opened xcode with this crash, If need, i can show more information.

**Comment by MeGaPk** [comment]
Options:
```
 NSDictionary *options = @{
                @"forceWebsockets": @(YES),
                @"forcePolling": @(NO),
                @"log": @(YES),
                @"token": token,
                @"appType": @"client",
                @"clientType": @"ios",
                @"extraHeaders": @{@"token": token, @"app-type": @"client", @"client-type": @"ios"},
                @"connectParams": @{@"token": token, @"app-type": @"client", @"client-type": @"ios"}
        };
```

**Comment by MeGaPk** [comment]
![screen shot 2017-03-01 at 09 26 35](https://cloud.githubusercontent.com/assets/892182/23449947/4397bc70-fe61-11e6-9439-41037c552246.png)

**Comment by MeGaPk** [comment]
![screen shot 2017-03-01 at 11 08 54](https://cloud.githubusercontent.com/assets/892182/23453411/f738551e-fe70-11e6-8005-60f2b8f3560b.png)

**Comment by nuclearace** [comment]
Do you have a way to reproduce?

**Comment by MeGaPk** [comment]
@nuclearace just long wait work with reconnecting every 2-5 minutes.

**Comment by nuclearace** [comment]
Probably fixed in the DispatchQueue refactors.
