### ISSUE TITLE
SocketIO pauses when app enters into background. ( Swift 3, iOS 10 ) 

### ISSUE THREAD

**Issue by hemanthalluri** [socketio/socket.io-client-swift#627]
I want to try local notifications using SOCKETIO., when the app is running on simulator everything is fine and displaying values even when the app enters into background. 
But when It's running on iPhone, when the app enters into background task suspends/ get paused. Please help me regarding this issue.

**Comment by nuclearace** [comment]
Right, because iOS doesn't allow background networking unless you have a certain permission enabled, and then you must start a background task.

**Comment by hemanthalluri** [comment]
Thanks for the quick reply @nuclearace , I added code in AppDelegate file 
    func applicationDidEnterBackground(_ application: UIApplication) {  
  // I placed  same code which I used in ViewContorller file 
 // But getting same output ( pauses when enter into background) 

 }

but the result is same. Is there any specific function in socketIO to re-excute from paused state, so that I call that function in AppDelegate

**Comment by hemanthalluri** [comment]
// This is my code.. But still same problem 

func applicationDidEnterBackground(_ application: UIApplication) {

            let socket = SocketIOClient(socketURL: URL(string: "http://ios-test.us-east-1.elasticbeanstalk.com")!, config: [.log(true), .forcePolling(true), .nsp("/random")])
        
            
            socket.on("connect") {data, ack in
                print("socket connected")
                
            }
            
            socket.on("currentAmount") {data, ack in
                if let cur = data[0] as? Double {
                    socket.emitWithAck("canUpdate", cur).timingOut(after: 0) {data in
                        socket.emit("update", ["amount": cur + 2.50])
                    }
                    
                    ack.with("Got your currentAmount", "dude")
                }
            }
            
            socket.reconnect()
            print("Fianlly Done///// Hemu")
            socket.on("capture") { dataArray, ack in
                
                for items in dataArray
                {
                    let receivedData  = items as! Int
                    let timeDate = DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .medium)
                    let filterData : Int = receivedData
                    if (filterData  <= 9 && filterData >= 1)
                    {
                        
                            let displayDate = "\(filterData) at \(timeDate)"
                            print("============================")
                            print(displayDate)
                            print("============================")
                            
                            // ===== Notifacations
                            
                        
                    }
                }
            }
            
            
        
        
    }

**Comment by NyeinEiEiTun** [comment]
I also happened same case like you. But in my case, i called soketio.run() function in the "applicationWillEnterForeground" function of AppDelegate.

**Comment by hemanthalluri** [comment]
HI @NyeinEiEiTun , I write **" socketio.run()"** but it shows error saying that no member is available. / And I also tried 

func applicationDidEnterBackground(_ application: UIApplication){

let socket = SocketIOClient(socketURL: URL(string: "http://ios-test.us-east-1.elasticbeanstalk.com")!, config: [.log(true), .forcePolling(true), .nsp("/random")])
        socket.run() // showing Error 
}

Please share some info.

**Comment by NyeinEiEiTun** [comment]
Please use "connect" .I am using this swift library from objective-c project. Here is my code.
<img width="984" alt="screen shot 2017-03-07 at 3 56 48 pm" src="https://cloud.githubusercontent.com/assets/26161959/23647083/ed686672-034e-11e7-97a8-8d40e9cc3ecf.png">

<img width="984" alt="screen shot 2017-03-07 at 3 56 48 pm" src="https://cloud.githubusercontent.com/assets/26161959/23647085/efaa399c-034e-11e7-8e22-78787be657a8.png">

we can connect or disconnect to socket.io

**Comment by hemanthalluri** [comment]
Even though I write socke.connect(), It ain't working. 

func applicationDidEnterBackground(_ application: UIApplication) {

        let socket = SocketIOClient(socketURL: URL(string: "http://ios-test.us-east-1.elasticbeanstalk.com")!, config: [.log(true), .forcePolling(true), .nsp("/random")])
    
    // socket.onAny {print("got event: \($0.event) with items \($0.items!)")}
        
        socket.on("connect") {data, ack in
            print("socket connected")
            
        }
        
        socket.on("currentAmount") {data, ack in
            if let cur = data[0] as? Double {
                socket.emitWithAck("canUpdate", cur).timingOut(after: 0) {data in
                    socket.emit("update", ["amount": cur + 2.50])
                }
                
                ack.with("Got your currentAmount", "dude")
            }
        }
        
// As you told @NyeinEiEiTun 
        socket.connect() // As you told 


        socket.on("capture") { dataArray, ack in
            
            for items in dataArray
            {
                let receivedData  = items as! Int
                let timeDate = DateFormatter.localizedString(from: Date(), dateStyle: .none, timeStyle: .medium)
                let filterData : Int = receivedData
                if (filterData  <= 9 && filterData >= 1)
                {
                    
                        let displayDate = "\(filterData) at \(timeDate)"
                        print("============================")
                        print(displayDate)
                        print("============================")
                        
                        // ===== Notifacations
                        
                    
                }
            }
        }
}

**Comment by hemanthalluri** [comment]
Nope.. Still not working.

**Comment by andrebraga** [comment]
Sure, because you're not heeding @nuclearace 's advice:

> Right, because iOS doesn't allow background networking unless you have a certain permission enabled, and then you must start a background task.

Please read on background tasks on iOS and the iOS background permissions. Hint:
`UIApplication beginBackgroundTask(withName taskName: String?, expirationHandler handler: (() -> Void)? = nil) -> UIBackgroundTaskIdentifier`

**Comment by DoktorBog** [comment]
I have same issues too! Socket service go to disconnect after 5 minute

**Comment by fukemy** [comment]
did someone solve it?

**Comment by rajdev** [comment]
> did someone solve it?
+1

Did anyone found a way to achieve this using the legacy VoIP capability?

**Comment by Akbar-khan-shinwari** [comment]
I am facing exactly the same issue, did anyone fix it.
