### ISSUE TITLE
chinese analysis error code 

### ISSUE THREAD

**Issue by yakirlee** [socketio/socket.io-client-swift#632]
8.3.0  chinese analysis error code 。

**Comment by nuclearace** [comment]
What?

**Comment by roshanman** [comment]
analysis chines error.

eg.
\U00e8\U0081\U0094\U00e9\U0080\U009a11 => èé11

**Comment by nuclearace** [comment]
Try adding the config `.doubleEncodeUTF8(true)`. I thought socket.io fixed the double encode error.

**Comment by nuclearace** [comment]
I changed the default back always double encode utf8, so should be fixed.
