### ISSUE TITLE
Creating a SocketIOClient consumes a reference from the sessionDelegate

### ISSUE THREAD

**Issue by peres** [socketio/socket.io-client-swift#633]
I'm using the current version of the library with a session delegate object from Objective-C.

It used to work fine until some months ago, but now every time I create a SocketIOClient, it consumes one reference to the session delegate. In fact, the `dealloc` method of the session delegate is invoked during creation of the SocketIOClient object, despite the strong references I'm holding.

The observed effects are:
- when the object that creates the SocketIOClient is also the session delegate, then the library crashes in `initWithSocketURL:config:`
- when an unretained object is the session delegate, then the library crashes in `initWithSocketURL:config:`
- when a strongly referenced object is the session delegate, then I can create the client and connection succeeds. Once I disconnect, and create a new SocketIOClient object with the same session delegate, then the library crashes in `initWithSocketURL:config:`
- in the same setup as above, but with an additional strong reference to the session delegate object, I managed to create the object twice, and got a crash on my third attempt

I hope this helps pinpoint the issue, which seems similar to #552.

**Comment by nuclearace** [comment]
What's the stacktrace for the crash?

**Comment by nuclearace** [comment]
Because this seems to work in Swift.

**Comment by peres** [comment]
Here is a stack trace for the case where I have a separate session delegate with no extra retains (the third in my list).

I didn't have Swift errors enabled in my breakpoint list yesterday, and from the Objective-C end it looked like it was crashing in `initWithSocketURL:config:`, but it's actually choking in `connect`. Sorry for the mishap.


```
Thread 1Queue : com.apple.main-thread (serial)
#0	0x00000001005c84b4 in swift_unknownRetain ()
#1	0x0000000100196e34 in initializeWithCopy for SocketIOClientOption ()
#2	0x00000001003fdaf4 in _ArrayBuffer.getElement(Int, wasNativeTypeChecked : Bool) -> A ()
#3	0x000000010040d8ec in Array.subscript.getter ()
#4	0x0000000100190918 in SocketIOClientConfiguration.subscript.getter at ~/SocketIOTest/socket.io-client-swift/Source/SocketIOClientConfiguration.swift:55
#5	0x0000000100193bec in protocol witness for IndexableBase.subscript.getter in conformance SocketIOClientConfiguration ()
#6	0x00000001003e78e0 in IndexingIterator.next() -> A._Element? ()
#7	0x0000000100144d00 in SocketEngine.init(client : SocketEngineClient, url : URL, config : SocketIOClientConfiguration) -> SocketEngine at ~/SocketIOTest/socket.io-client-swift/Source/SocketEngine.swift:86
#8	0x0000000100145c74 in SocketEngine.__allocating_init(client : SocketEngineClient, url : URL, config : SocketIOClientConfiguration) -> SocketEngine ()
#9	0x000000010015e8bc in SocketIOClient.addEngine() -> SocketEngineSpec at ~/SocketIOTest/socket.io-client-swift/Source/SocketIOClient.swift:123
#10	0x000000010015ec4c in SocketIOClient.connect(timeoutAfter : Int, withHandler : () -> ()?) -> () at ~/SocketIOTest/socket.io-client-swift/Source/SocketIOClient.swift:146
#11	0x000000010015e998 in SocketIOClient.connect() -> () at ~/SocketIOTest/socket.io-client-swift/Source/SocketIOClient.swift:130
#12	0x000000010015f03c in @objc SocketIOClient.connect() -> () ()
#13	0x0000000100021da8 in -[MyPushClient setupPushClient:] at ~/SocketIOTest/MyPushClient.m:110
#14	0x00000001000217fc in -[MyPushClient connect:] at ~/SocketIOTest/MyPushClient.m:69
#15	0x0000000100020d6c in -[ViewController connectButtonPressed:] at ~/SocketIOTest/ViewController.m:27
#16	0x0000000196ab8d30 in -[UIApplication sendAction:to:from:forEvent:] ()
#17	0x0000000196ab8cb0 in -[UIControl sendAction:to:forEvent:] ()
#18	0x0000000196aa3128 in -[UIControl _sendActionsForEvents:withEvent:] ()
#19	0x0000000196ab859c in -[UIControl touchesEnded:withEvent:] ()
#20	0x0000000196ab80c4 in -[UIWindow _sendTouchesForEvent:] ()
#21	0x0000000196ab3328 in -[UIWindow sendEvent:] ()
#22	0x0000000196a83da0 in -[UIApplication sendEvent:] ()
#23	0x000000019726d75c in __dispatchPreprocessedEventFromEventQueue ()
#24	0x0000000197267130 in __handleEventQueue ()
#25	0x0000000190b82b5c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#26	0x0000000190b824a4 in __CFRunLoopDoSources0 ()
#27	0x0000000190b800a4 in __CFRunLoopRun ()
#28	0x0000000190aae2b8 in CFRunLoopRunSpecific ()
#29	0x0000000192562198 in GSEventRunModal ()
#30	0x0000000196aee7fc in -[UIApplication _run] ()
#31	0x0000000196ae9534 in UIApplicationMain ()
#32	0x0000000100022424 in main at ~/SocketIOTest/main.m:14
#33	0x000000018fa915b8 in start ()

```

**Comment by nuclearace** [comment]
Weird. This doesn't seem to crash in Swift. Is this just with Objective-C? If so, not sure there's much I can do.

**Comment by peres** [comment]
I know that it's working with Swift, since the built-in delegate is written and managed in Swift and there is no crash in that case. I might try a Swift implementation in my app if I manage the time. By the way, should the delegate be a Swift object, or should the object holding the SocketIOClient be a Swift object? Or both?

It's a tricky convergence: I have Objective-C code defining an object bridged to Swift, and the object in question is possibly the only case in the whole of Foundation of a delegate *retained* by its user object (NSURLSession). It certainly leaves room for doubts.

**Comment by nuclearace** [comment]
I'm not sure if the object should be a Swift object. I don't think it would matter, but maybe it does.

**Comment by peres** [comment]
It turns out that the object that owns a SocketIOClient must be a Swift object if you want to use a custom session delegate. Tried both with a separate delegate object, and by making the owner the session delegate, too (i.e. the `self` case). Works in both. WTF.

Maybe this hints you at the problem. Or you might want to add it to the documentation. For me this case is closed.
