### ISSUE TITLE
 no such module 'Security'

### ISSUE THREAD

**Issue by bitbreakr** [socketio/socket.io-client-swift#634]
Hello, I tried to compile the lib in order to be used in a debian / linux project

I get the following output: 

/home/user/Development/socket-client/Packages/SocketIO-8.3.0/Source/SSLSecurity.swift:23:8: error: no such module 'Security'
import Security

Could you make it Linux compatible or fix that issue, It would be very kind. :)

**Comment by nuclearace** [comment]
I would love to. But that'd require the WebSocket dependency to be updated, which isn't something I actually maintain. (It's just included here manually.)
