### ISSUE TITLE
Namespace use

### ISSUE THREAD

**Issue by phwowcs** [socketio/socket.io-client-swift#64]
Hi all,

Could someone please give me an working example that uses namespace in Swift? I try it but not working. Thanks

**Comment by vordio** [comment]
set:
socket.nsp = "namespace" then connect

But how can I switch namespace?

**Comment by phwowcs** [comment]
This is my mistake, I declared 'socket'  in viewDidLoad() function so it was not working.

**Comment by nuclearace** [comment]
You can set the namespace when you create the socket

```swift
let socket = SocketIOClient(socketURL: "localhost", opts: ["nsp": "swift"])
```

And yeah, you'll need to declare the socket to be a member of a class or have global scope.
