### ISSUE TITLE
Wrong utf8 string encoding with Swift 3.1

### ISSUE THREAD

**Issue by betoHub** [socketio/socket.io-client-swift#640]
After the recent upgrade to xCode 8.3 and Swift 3.1, i upgraded socket.io-client-swift to the latest version (downloaded from GitHub 2 hours ago) and i upgraded the server to the last stable version (1.7.3), but now all the strings coming from emit are not encoded in utf8, it seems they're encoded with ISO latin1 and thus some characters are not correctly displayed..!

Is it a known problem or i did a mistake somewhere? Any tips..?

Thank you very much, socket.io is awesome ;)

**Comment by nuclearace** [comment]
Try using `doubleEncodeUTF8(true)`

**Comment by nuclearace** [comment]
Or just use the newest version, I reverted a change. I thought socket.io fixed the double encoding issue. Guess not.

**Comment by lishuanglong521** [comment]
推送出现乱码问题怎么解决

**Comment by betoHub** [comment]
Now it works!

**Comment by itzhangbao** [comment]
How did you get it to work? thk

**Comment by itzhangbao** [comment]
Using doubleEncodeUTF8 (true) doesn't work, it's still messy

**Comment by nuclearace** [comment]
This shouldn't be neeeded anymore with socket.io 2.0.

**Comment by itzhangbao** [comment]
@nuclearace I return to version 9.0.1, which can be displayed norm.

**Comment by sangnvus** [comment]
I have a problem with charset utf-8 with the latest version 1.15.3 built with xCode 10.3. When the message received from webclient or android client, it did not display correctly. Anyone got same problem like that and had a solution?

**Comment by malqadi88** [comment]
Actually, this issue happened when the socket did not upgrade to the web socket or when you make .forcePolling(true) 
and the library on the server-side version before 2.0 and the client version before 9.0
so I checked the commit when 
[https://github.com/socketio/socket.io-client-swift/commit/468d7b24533796d2abf6637aa7c03ba924f2b9ee](url)

so my fix was this 

`func processMessage(data: [Any]) {
        guard let item = data[0] as? [String: AnyObject] else { return }

        var newItem = item
        if let data = item.toJsonStringRepresentaiton?.data(using: String.Encoding.isoLatin1, allowLossyConversion: false), let text = String(data: data, encoding: .utf8), let newDic = text.toDictionary() {
            newItem = newDic
        }
        
        sendAcknowledgeForMessage(message: newItem)
        checkEventType(data: newItem)
    }`
    
    
    `extension Dictionary {
    var toJsonStringRepresentaiton: String? {
        guard let theJSONData = try? JSONSerialization.data(withJSONObject: self,
                                                            options: [.prettyPrinted]) else {
                                                                return nil
        }
        
        return String(data: theJSONData, encoding: .utf8)
    }
}`
