### ISSUE TITLE
Convert to JSON Format 

### ISSUE THREAD

**Issue by syedrazackimran** [socketio/socket.io-client-swift#641]
Hi .. i'm try to connect socket.io objective-c but i'm facing issues .. when i got message from server side i need to convert it to JSON format i don't know to how convert kindly do needfully

 SocketAnyEvent: Event: getdata items: Optional([{
    data =     {
        "{\"name\":\"remo\",\"age\":\"25\"}" = "";
    };
}])

**Comment by nuclearace** [comment]
If the sent data is JSON, it should automatically be converted into a Dictionary.

**Comment by syedrazackimran** [comment]
thanks for pervious question , i have another quires how can i stop emitting ! i need to stop emitting on particular time !

**Comment by nuclearace** [comment]
That's up to you to determine when to stop sending and disconnect.
