### ISSUE TITLE
Multiple connections but only one receive events

### ISSUE THREAD

**Issue by terenceLuffy** [socketio/socket.io-client-swift#644]
I have three sockets connected for three different namespaces, all use this configuration:
` [.handleQueue(sameQueue), .nsp(someNamespace), .connectParams(["token":token]), .forceWebsockets(true), .sessionDelegate(self as! URLSessionDelegate), .selfSigned(true)]`

The problem now is, it works well in iOS 10, but not in iOS 8 and 9. In there only one socket receive listener events, the other two sockets does not, but all the three sockets are connected. The strange thing is sometimes I can receive listener events from the other two after waiting a long time. So I suspect that maybe the queue problem, I tried to put the in three different queue even in main queue, but that doesn't make any difference. Would you be able to provide some helps? Thanks!

**Comment by nuclearace** [comment]
Are you sure that your handleQueue is not doing something that blocks the queue?

**Comment by terenceLuffy** [comment]
@nuclearace No, I tried to put them all in main queue, if it is blocked, the UI won't be responsive.

**Comment by terenceLuffy** [comment]
Oh, i will need to call `timingOut` otherwise the emit is not sent. And after calling it, the s2 is blocked. So issue is not solved.

**Comment by terenceLuffy** [comment]
@nuclearace I think I find out the cause.

The steps are:

Create three sockets s1, s2, s3
s1 connected event received, and then fire multiple emits
s2 connected event received, and then fire multiple emits
s3 connected event received, and then fire multiple emits

so far all success

then after less than 30 seconds, I received "["Ping timeout"]" for both s1 and s2, then it trigger reconnect event "reconnectAttempt" with attempted times and then it keeps failing for many times. During the retry, if s3 disconnected somehow, either s1 or s2 can connect. So I think the reason is s1, s2 and s3 (same server different namespaces) fighting for the only one channel to connect with, do you have any idea what might happen? Or do you have any example for multiple namespaces in web socket connections?

**Comment by terenceLuffy** [comment]
I finally found the problem!!!!!!

In WebSocket class, there is a static queue `private static let sharedWorkQueue = DispatchQueue(label: "com.vluxe.starscream.websocket", attributes: [])`, this queue is shared by all web sockets. This is the problem, the one who occupy this queue stop other web sockets go in, and this issue has been fixed in iOS 10, that's why it only works in iOS 10.

**Comment by AngeSohone** [comment]
Hi, please someone can share to me ressource or example code to use more than one socket in ios app.
I need to have 02 sockets

Thanks
