### ISSUE TITLE
pod issues

### ISSUE THREAD

**Issue by CoderTaoX** [socketio/socket.io-client-swift#645]
Use pod download, can not download the latest version, can only be downloaded to the 8.0.2 version.

And this “type ‘SocketIOClientConfiguration’ does not conform to protocol 'Collection'” and more question.

**Comment by nuclearace** [comment]
What version of Xcode are you using? You need the latest version.

**Comment by johnharutyunyan** [comment]
I also have this problem and  also have the latest version (Xcode 8.3.1) 
After pod install , Xcode give me 6 errors from Sockets

**Comment by lk321** [comment]
Update all packages to the latest version.

`pod update`
