### ISSUE TITLE
WebSocket.cleanupStream() crash and more.

### ISSUE THREAD

**Issue by MaxAdamyan** [socketio/socket.io-client-swift#646]
Hi I have my app in production, and I'm using Socket.IO client v8.3.3.
I have a lot crashes from user in Socket.IO module, and the most crashed parts are:
`WebSocket.cleanupStream()` in WebSocket.switf
`_inputStreamCallbackFunc` in CoreFoundation
and more.
Has this anything to do with me, or can I do something to prevent this crashes??
Thanks.

**Comment by nuclearace** [comment]
Need a reproducible case.

**Comment by MaxAdamyan** [comment]
I do not know the case but here is crush report:
`com.apple.main-thread
0  libsystem_kernel.dylib         0x187b78e64 __psynch_mutexwait + 8
1  libsystem_pthread.dylib        0x187c44c5c _pthread_mutex_lock_wait + 96
2  libsystem_pthread.dylib        0x187c44e64 _pthread_mutex_lock_slow + 300
3  CoreFoundation                 0x188aca2a4 _CFStreamUnscheduleFromRunLoop + 152
4  CoreFoundation                 0x188b3a118 _CFStreamSetDispatchQueue + 168
5  **                             0x100168e08 WebSocket.cleanupStream() -> () (WebSocket.swift:444)
6  **                             0x100169814 @objc WebSocket.__deallocating_deinit (WebSocket.swift:934)
7  **                             0x1000a5994 SocketEngine.createWebsocketAndConnect() -> () (SocketEngine.swift:248)
8  **                             0x1000a536c SocketEngine.connect() -> () (SocketEngine.swift:190)
9  **                             0x1000a60c8 @objc SocketEngine.connect() -> () (SocketEngine.swift)
10 **                             0x100118854 specialized SocketIOClient.connect(timeoutAfter : Int, withHandler : () -> ()?) -> () (SocketIOClient.swift:148)
11 **                             0x100116064 SocketIOClient._tryReconnect() -> () (SocketIOClient.swift:428)
12 **                             0x100119c3c specialized SocketIOClient.engineDidClose(reason : String) -> () (SocketIOClient.swift:412)
13 **                             0x100115a84 @objc SocketIOClient.didDisconnect(reason : String) -> () + 4296284804
14 **                             0x1000a6a3c SocketEngine.sendPing() -> () (SocketEngine.swift)
15 **                             0x1000a6fac SocketEngine.(sendPing() -> ()).(closure #1) (SocketEngine.swift)
16 libdispatch.dylib              0x187a369a0 _dispatch_client_callout + 16
17 libdispatch.dylib              0x187a43604 _dispatch_continuation_pop + 448
18 libdispatch.dylib              0x187a4fc1c _dispatch_source_latch_and_call + 204
19 libdispatch.dylib              0x187a388a0 _dispatch_source_invoke + 804
20 libdispatch.dylib              0x187a3b4a0 _dispatch_main_queue_callback_4CF + 668
21 CoreFoundation                 0x188b2d0c0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
22 CoreFoundation                 0x188b2acdc __CFRunLoopRun + 1572
23 CoreFoundation                 0x188a5ad94 CFRunLoopRunSpecific + 424
24 GraphicsServices               0x18a4c4074 GSEventRunModal + 100
25 UIKit                          0x18ed13130 UIApplicationMain + 208
26 **                             0x10008de9c main (SocketIOClientSpec.swift:27)
27 libdyld.dylib                  0x187a6959c start + 4`

**Comment by nuclearace** [comment]
Might be fixed in the 9.0.
