### ISSUE TITLE
pod install  the version is still 8.2.0 available

### ISSUE THREAD

**Issue by chunxigege** [socketio/socket.io-client-swift#647]
<img width="306" alt="75fa7512-3ca6-4969-8823-cbe730f8a2c9" src="https://cloud.githubusercontent.com/assets/8032681/24852277/799db884-1e09-11e7-86c8-c4c24ea8f916.png">

could you  update pod version to 8.3.3 ？

**Comment by nuclearace** [comment]
What version of Xcode are you using? https://cocoapods.org/pods/Socket.IO-Client-Swift Shows 8.3.3

**Comment by chunxigege** [comment]
xcode8.2.1

**Comment by chunxigege** [comment]
xcode 8.2.2

**Comment by nuclearace** [comment]
You need Xcode 8.3 to use the latest version.

**Comment by chunxigege** [comment]
thanks a lot ,I solved the problem by  Updating to latest version
