### ISSUE TITLE
Socket really new to this?

### ISSUE THREAD

**Issue by UmaMadhavi** [socketio/socket.io-client-swift#648]
how to send data array of information using Socket.io,because for the first time i am working with Sockets . Can anyone help me

**Comment by nuclearace** [comment]
```swift
socket.emit("myEvent", [1, 3, 5, 5])
```

**Comment by UmaMadhavi** [comment]
in the place of "my event" should i send api path?

**Comment by nuclearace** [comment]
You should probably read https://socket.io/docs/. It gives you an idea of how to use socket.io

**Comment by UmaMadhavi** [comment]
@nuclearace . I am not understanding that one . actually i have added my code like this

     let socket = SocketIOClient(socketURL: URL(string: "http://"+SERV_HOST_PORT+"/gs-guide-websocket/info?access_token=\(accessToken!)")!, config: [.log(true), .forcePolling(true)])
            
            socket.emit("/upsock/tripupdate/\(tripId!)", parameters)
            socket.on("connect") {data, ack in
            print("Connected...")
            }
        socket.connect()

In this scenario i am getting authentication failed full authorisation required to access. Can u please tell me where is my mistake.

**Comment by nuclearace** [comment]
Instead of manually adding your connect parameters to your URL you should use the `connectParams` option.

**Comment by UmaMadhavi** [comment]
when i add using connectParams it does not call at all.
