### ISSUE TITLE
Allow option to specify custom socket.io url path.

### ISSUE THREAD

**Issue by daniel-shin1104** [socketio/socket.io-client-swift#65]
First of all, amazing job here. Now I don't need to rely on creating webview to handle client side!

Currently, it seems like /socket.io, (default socket.io server path) is attached to the end of passed socketURL during init.

Since in socket.io server, path can be customized by passing 'path' key to options object, client should also support it.

I personally prefer to use '/io' path instead of '/socket.io' simply for simplicity and now returned url is "\(SERVER_URL)/io/socket.io".

**Comment by nuclearace** [comment]
@daniel-shin1104 does that work

**Comment by daniel-shin1104** [comment]
What I meant was to replace default path '/socket.io' by custom path. 

`var url = "\(self.client!.socketURL)\(self.socketPath)/socket.io/?transport="`

`self.socketPath` should replace '/socket.io' here instead of inserting one before it.

What can be done is to simply set '/socket.io' as default path if no custom path is specified since that's what server does.

**Comment by daniel-shin1104** [comment]
something like

`if let path = opts!["path"] as? String { self.socketPath = path } 
else { self.socketPath = '/socket.io'}`

**Comment by nuclearace** [comment]
How is the server set up so I can test it. Half of the stuff socket.io can do is poorly documented or isn't used much.

**Comment by daniel-shin1104** [comment]
http://socket.io/docs/server-api/#server#path(v:string):server

You can refer to the link. It explains the 'path' option on server-side

**Comment by nuclearace** [comment]
Weird, because that's how I thought I tested it, and it worked.

```JavaScript
var io = require('socket.io')(8080, {path: "/swift"})
```

```swift
let socket = SocketIOClient(socketURL: "localhost:8080", opts: ["path": "/swift"])
```

**Comment by nuclearace** [comment]
I think it works because socket.io is cleaning up my incorrect url and only looking at the end ?transport=

**Comment by daniel-shin1104** [comment]
That's because socket.io only looks at the first matching path and disregard the rest. So if you specified '/swift' as custom path in server, it will basically filter all '/swift/*' as socket.io bound http requests. And since other than the initial handshake, conventional url scheme has no significance in socket.io, it still is considered as valid connection and, therefore no error.

'(URL)/swift/socket.io' is what is being generated with your code and socket.io server filters for '(URL)/swift/*'.

If you log out the incoming http requests on your server, you will see the trailing '/socket.io' path.

While this isn't semantically significant, there is no reason to have this trailing path.

**Comment by Daniet** [comment]
hola
no he podido conectarse al web socket especifico, al usar este codigo me sale error al compilar 
    let socket = SocketIOClient(socketURL: URL(string: "http://172.20.2.73:5151")!, option["path":"/swift"], config: [.log(true), .forcePolling(true)])

**Comment by Spandana-Gajangi** [comment]
How to add path to socket io where socketIo and node server runs on same port.
like node server runs on http://someurl:3000
socket should run on http://someurl:3000/socket

**Comment by nuclearace** [comment]
It would be a combination of a url with the port and a `.path` config if the server is using a custom path.

**Comment by Weblogic14c** [comment]
@danishin https://primordial-arangojs.github.io/yjPBpGUDESJ7b6ioDsqtL4p3vU_odpmQ7j1CyIYbWMIk40Y8WoXanmz59g/
