### ISSUE TITLE
我会监听到多次一样的推送，怎么回事

### ISSUE THREAD

**Issue by lishuanglong521** [socketio/socket.io-client-swift#650]

**Comment by nuclearace** [comment]
Just going off of Google translate, but if you want to listen to an event, you just need to do.

```swift
socket.on("myEvent") {data in
  // My event code
}
```

**Comment by terenceLuffy** [comment]
@nuclearace He/she is asking why it receives multiple response for the same push. I guess the listener is added multiple times.

**Comment by musicabbage** [comment]
I got the same problem ➡️ #630 
but Im pretty sure I added the listener only 1 time, it usually happens on unstable network
