### ISSUE TITLE
emitWithAck

### ISSUE THREAD

**Issue by bhartsb** [socketio/socket.io-client-swift#652]
I tried updating my client sources but emitWithAck has changed.  Here's what used to work:

`
typedef void(^SocketIOCallback)(id argsData);

 SocketIOCallback cb = ^(id argsData) {
                
                if (argsData[0] == [NSNull null]){
                    return;
                }
                // do something with response
                NSLog(@"setDebugEvent_KV_InRedis was acknowledged by the server: %@", argsData[0]);
                
            };
            
            NSArray * a = [[NSArray alloc] initWithObjects:dict, nil];
            
            [socketIOSwift emitWithAck:@"setDebugEvent_KV_InRedis" with:a](0, cb);`

Can anyone shed light on how emitWithAck has changed, and the reasons for the changes (context), and generally how to re-write the above to work with the new emitWithAck.   Thanks.

**Comment by nuclearace** [comment]
Look at the readme
