### ISSUE TITLE
after Update Pod issue 

### ISSUE THREAD

**Issue by chirag225** [socketio/socket.io-client-swift#655]
I updated pod to pod 'Socket.IO-Client-Swift', '~> 8.3.3’  "Property with 'retain (or strong)' attribute must be of object type"   in SocketIO-Swift.h file 

and Could not build module 'SocketIO' Error facing 

I removed Derived data and did  clean project

**Comment by nuclearace** [comment]
What xcode version are you using?

**Comment by chirag225** [comment]
Xcode  8.3.2

**Comment by nuclearace** [comment]
Have you figured this out?

**Comment by chirag225** [comment]
Still facing this issue pod 'Socket.IO-Client-Swift',   xcode 8.3.3
 1 ) Could not build module 'SocketIO'
2 ) Property with 'retain (or strong)' attribute must be of object type for   @property (nonatomic, strong) dispatch_queue_t _Nonnull handleQueue;
