### ISSUE TITLE
Error: SocketIOClientConfiguration does not confirm to protocol 'Collection'

### ISSUE THREAD

**Issue by Nik20112** [socketio/socket.io-client-swift#664]
Hi,

I m facing build error in Xcode 8.3.2 but its working fine in Xcode 8.1. 

> pod 'Socket.IO-Client-Swift'

Please help me to resolve this issue.

Thanks
Nikunj

**Comment by nuclearace** [comment]
Make sure you're on the latest version.

**Comment by Nik20112** [comment]
Yes its resolved
Thanks
