### ISSUE TITLE
Distinguish better when ack times out

### ISSUE THREAD

**Issue by OneSman7** [socketio/socket.io-client-swift#667]
As I can see from the source code, when the ack times out, client will call callback with "NO ACK":

` onQueue.async() {
            ack?.callback?(["NO ACK"])
        }
`

Can we have this string as a global constant? Or another reliable way to check timing out?
(I suspect the string may change in the future without us knowing)

**Comment by nuclearace** [comment]
Totally agree with you.

**Comment by nuclearace** [comment]
@OneSman7 23c7641
