### ISSUE TITLE
Allow changes to SocketIOClientStatus of SocketIOClient to be observed

### ISSUE THREAD

**Issue by patmalt** [socketio/socket.io-client-swift#668]
Currently, there is no way for changes to status (SocketIOClientStatus) of SocketIOClient to be observed. I want to be able to react to changes of the status of the client. This will allow a better interoperability with reactive frameworks such as RxSwift.

There are several ways to accomplish this:
* allow status to be overridden
* add a delegate or callback to alert subscribers of changes
* Add dynamic to the declaration of status so KVO can be used

Before creating a fork and pull request, which method would be the most acceptable?

**Comment by nuclearace** [comment]
KVO is best avoided in Swift. Most idiomatic for this library would be a new system event that is on changes.

**Comment by patmalt** [comment]
Post a system wide notification?

**Comment by nuclearace** [comment]
But what is wrong with listening to `connect`, `disconnect`, `reconnect` and `reconnectAttempt`?These usually mean a status change.

**Comment by patmalt** [comment]
I am confused on what you mean. Is there an existing protocol for connect, disconnect, .. etc?

**Comment by nuclearace** [comment]
```swift
socket.on("connect") { ... }
socket.on("disconnect") { ... }
socket.on("reconnect") { ... }
socket.on("reconnectAttempt") { ... }
```

**Comment by patmalt** [comment]
I also want the ability to know when the socket is connecting. Do any of the previous events correspond to "connecting"?

**Comment by nuclearace** [comment]
Not directly. But the periods between calling `connect()` and receiving `connect` indicate connecting. Likewise, the period between receiving `reconnect` and a `connect` are connecting.

**Comment by patmalt** [comment]
I do not want to worry about handling additional state and the edge cases around this suggested method when status is already available. I just need a way to know the new status when it changes.

**Comment by nuclearace** [comment]
Simplest would be to add a `handleEvent("statusChange"...)` call at the end of this. But like I said, there's currently no connecting status.

**Comment by patmalt** [comment]
SocketIOClient is already handling all of state that I need. Adding ```handleEvent("xyz")``` will introduce unnecessary complexity to my code. In addition, I need the ```.connecting``` status found in SocketIOClientStatus, which you have stated does not exist for ```handleEvent```. I do not want to reason about when I am in a connecting state.

**Comment by nuclearace** [comment]
Right, I'm saying the way I would want this kind of feature added is through a new status and client event.

**Comment by nuclearace** [comment]
Which, unless someone raises a PR, will come after the clean up of the DispatchQueues.

**Comment by patmalt** [comment]
Ah, I see what you mean. Sorry for the confusion.

**Comment by nuclearace** [comment]
Also, I must've been smoking something. There is a connecting status, it is only set after calling `connect`, and this status change isn't announced.

**Comment by patmalt** [comment]
Right, I just want to be informed when the status field changes on SocketIOClient.

**Comment by nuclearace** [comment]
@patmalt 1eb39d6
