### ISSUE TITLE
won't reconnect when the app come back from background

### ISSUE THREAD

**Issue by obsobsobs** [socketio/socket.io-client-swift#67]
when i let the my app in the background for some seconds (so that iOS kill the socket connection) and after i go back in the app, the socket won't reconnect anymore !!!

can you please solve this problem ?

**Comment by nuclearace** [comment]
I'm not sure the best way to handle going into the background. My suggestion would be to close the socket, and then readd it when you come back.

**Comment by obsobsobs** [comment]
But the documentation says:
close(#fast:Bool) - Closes the socket. Once a socket is closed it should not be reopened

**Comment by nuclearace** [comment]
Right, that's why I said readd. I'm willing to hear any ideas on how to make coming back from the background better. 

The library itself is platform independent. I actually do most testing from OS X.

**Comment by obsobsobs** [comment]
ok thank you :D

**Comment by jlohiys** [comment]
> I'm not sure the best way to handle going into the background. My suggestion would be to close the socket, and then readd it when you come back.

when we come back, it wont give all the messages. Some messages are getting lost
