### ISSUE TITLE
Socket IO Client doesn't connect after long delay (24hrs approx) 

### ISSUE THREAD

**Issue by rajeevwhiz** [socketio/socket.io-client-swift#674]
Version Socket.IO-Client-Swift (8.3.3)

In applicationDidEnterBackground, I am calling `socket.disconnect()`
In applicationDidBecomeActive, I am calling `socket.connect()`

It all works fine while I use the app... and even when I move the app in the background / foreground... everything works as expected. 

However, my app is not able to connect to the server if I don't use it for 24hrs and then try to bring it up.. At this point nothing works.. Server doesn't even see any requests coming in!. Restarting the app or installing again on top on existing installed app doesn't solve the problem. Removing and installing the app (i.e. wiping the sandbox) solves the issue, so it's not a server side bug.

Any ideas / suggestions on how to fix this? Is this a known issue?

**Comment by rajeevwhiz** [comment]
Closing... found the issue.

**Comment by ishegg** [comment]
@rajeevwhiz you should post your solution anyway for posterity.

**Comment by alperkayabasi** [comment]
@rajeevwhiz I'm facing the same problem. What was the issue here and how did you solve it?
