### ISSUE TITLE
How do I register for unrequested updates?

### ISSUE THREAD

**Issue by bluemasterflows** [socketio/socket.io-client-swift#68]
When the socket sends me something and I don't expect it, how can I log that information?

It doesn't look like any of the "Events" are for that, and I don't see a way to register myself as a delegate to get updates. 

I can Emit a request and get back an ack, but what about updates that I didn't ask for?

Thanks!

**Comment by nuclearace** [comment]
Add an onAny handler

```swift
socket.onAny {println("got event: \($0.event) with items \($0.items)")}
```

**Comment by bluemasterflows** [comment]
Thanks, that's what I had, but since none of the Events in the documentation seemed to fit I assumed there was another way. Thanks!
