### ISSUE TITLE
HTTPS problem 

### ISSUE THREAD

**Issue by irakliitavadze** [socketio/socket.io-client-swift#682]
Hello.

I changed my base url on https. And after this my socket doesn't work.
In Info.plist I delete all notes about ATS.
I attached image with log, does anybody know how to resolve it?

Thank you.

```
_socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"log" : @YES,
                                                                     @"forcePolling" : @NO,
                                                                     @"secure": @YES,
                                                                     @"connectParams" : @{@"userId":@"12",
                                                                                          @"groupId":@"23"}}];
    
```
![screen shot 2017-05-10 at 21 37 58](https://cloud.githubusercontent.com/assets/22373943/25912699/44cd1622-35c9-11e7-9db5-ae3c73648915.png)

**Comment by irakliitavadze** [comment]
So problem was fixed on backend side. We added .key, .crt and https module. 
But one interesting moment on Android a socket works without changes on backend.

**Comment by nuclearace** [comment]
Probably because Apple is very strict about TLS.
