### ISSUE TITLE
How to include a custom authentication token AFTER connect

### ISSUE THREAD

**Issue by startupthekid** [socketio/socket.io-client-swift#684]
Once a client is connected, how can I attach custom headers that will be applied on the very next emit? 

I'm using the client to retrieve an authentication token and then I want to attach that token to the client but `.connectParams` and `.extraHeaders` are only sent on the original connection.

**Comment by nuclearace** [comment]
Sorry it took so long to get around to this. A note about this: it'll only affect the initial connection or when forcing http long-polling. Once a WebSocket connection is established the headers aren't sent again.
