### ISSUE TITLE
Error: Event Handler not called from Android to iOS

### ISSUE THREAD

**Issue by Nik20112** [socketio/socket.io-client-swift#685]
Hi,

I am working with Socket IO. I need to suggestion why event handler method is not called while sending data from android to iOS but when I send data from iOS to Android. But iOS side can't called event handler method. Below is my code. Also, I m not getting any error.

When add log in config its return me the below log:

> let socket = SocketIOClient(socketURL: URL(string: "https://v2.test.nl:3000")!, config: [.log(true), .forcePolling(true)])

> LOG SocketIOClient: Handling event: error with data: ["Tried emitting serie when not connected"]
> LOG SocketIOClient: Adding handler for event: raceresult
> 

Above log indicating the issue while socket connection?

Your help will be grateful for me.

> socket.connect()
> socket.on("connect") {data, ack in        
>             if activeId > 0 {
>                 SocketManager.singleton.connectToServerWithd(activeId, completionHandler: { (userList : [AnyObject]?) in
>                 })
>             }
>         }
> 
> socket.emit("Id", Id)
> socket.on("result") { (dataArray, socketAck) -> Void in
> NotificationCenter.default.post(name: NSNotification.Name(rawValue: "receivedResultNotification"), object: dataArray[0] as! [String: AnyObject]) }

Thanks
Nikunj

**Comment by nuclearace** [comment]
Not sure if it's your actual code, but adding handlers after calling connect is not good. You should add them before calling connect. Likewise, not sure if it's just the example code, but calling emit right after connect is most likely not going to emit anything, since connect becomes async.

**Comment by Nik20112** [comment]
Hi,
Thanks for the reply. Now I m successfully connected to Socket event handler method not called. While I am sending data from iOS to Android its working fine but while android send the data into iOS. So that time not called any socket methods at iOS Side.

Can you please help me on this? Please see the below code and let me know if anything wrong on this while receving the data.

```
import UIKit
import SocketIO

class SocketManager: NSObject {
    
    static var singleton = SocketManager()
    
    //let socket = SocketIOClient(socketURL: URL(string: BundleValues.sharedInstance.WebSocketURL() as String)!, options: [.Log(true), .ForcePolling(true), .Reconnects(true)])
    let socket = SocketIOClient(socketURL: URL(string: "https://test1234.nl:3000")!, config: [.log(true), .forcePolling(true)])
    override init() {
        super.init()
    }
    
    //MARK:- Establish socket connection
    func establishConnection(activeSerieId : Int) {
        
        socket.connect()
        socket.on("connect") {data, ack in
        
            if activeId > 0 {
                SocketManager.singleton.connectToServerWithId(activeId, completionHandler: { (userList : [AnyObject]?) in
                })
            }
        }
    }
    
    //MARK:- Close socket connection
    func closeConnection() {
        socket.disconnect()
    }
    
    //MARK:- Connecting to the Room using Id
    func connectToServerWithSerieId(_ activeId: Int, completionHandler:@escaping(_ userList : [AnyObject]?)->Void) {
        
        socket.emit("activeId", activeId)
        socket.on("activeresult") { (dataArray, socketAck) -> Void in
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "receivedRaceResultNotification"), object: dataArray[0] as! [String: AnyObject])
        }
    }
}

```

**Comment by nuclearace** [comment]
You should add all handlers before calling connect. Besides that, make sure your event names are correct.

**Comment by Nik20112** [comment]
Hi,
Please do me fever for this.
Please list out the all event handler methods for me and when I can cross check event name is correct or not? and below calling of event handlers is correct?

```
//MARK:- Establish socket connection
    func establishConnection(activeSerieId : Int) {
        
        socket.on("connect") {data, ack in
            
            if activeSerieId > 0 {
                SocketManager.singleton.connectToServerWithSerieId(activeSerieId, completionHandler: { (userList : [AnyObject]?) in
                })
            }
        }
        socket.connect()
    }
```

**Comment by nuclearace** [comment]
Check the API you're using and the event names you've added. You can also turn on logging and search for "handling event" to see the events the client is trying to handle. Or you can add an onAny handler.

```swift
socket.onAny {event in
    print(event.event)
}
```

**Comment by Nik20112** [comment]
Hi,
I have integrated ".onAny" event handler and logging and pulling as well but receiver side can't call the method and below log is there: Honestly, I don't know the issue where it is? Please help

```
<Warning>: LOG SocketEngine: Writing poll:  has data: false
<Warning>: LOG SocketEnginePolling: Sending poll:  as type: 2
 <Warning>: LOG SocketEnginePolling: Created POST string: 1:2
 <Warning>: LOG SocketEnginePolling: POSTing
<Warning>: LOG SocketEnginePolling: Doing polling POST https://test1234.nl:3000/socket.io/?transport=polling&b64=1&sid=fb6LRYy_xWH60vy1AASL
<Warning>: LOG SocketEnginePolling: Got polling response
<Warning>: LOG SocketEngine: Got message: 3
<Warning>: LOG SocketEnginePolling: Doing polling GET https://test1234.nl:3000/socket.io/?transport=polling&b64=1&sid=fb6LRYy_xWH60vy1AASL
29  syncdefaultsd[115] <Notice>: (Note ) marked "com.me.keyvalueservice" topic as "enabled" on <APSConnection: 0x15562150>
  <Warning>: LOG SocketEngine: Writing poll:  has data: false
  <Warning>: LOG SocketEnginePolling: Sending poll:  as type: 2
  <Warning>: LOG SocketEnginePolling: Created POST string: 1:2
  <Warning>: LOG SocketEnginePolling: POSTing
  <Warning>: LOG SocketEnginePolling: Doing polling POST https://test1234.nl:3000/socket.io/?transport=polling&b64=1&sid=fb6LRYy_xWH60vy1AASL
  <Warning>: LOG SocketEnginePolling: Got polling response
  <Warning>: LOG SocketEngine: Got message: 3
  <Warning>: LOG SocketEnginePolling: Doing polling GET https://test1234.nl:3000/socket.io/?transport=polling&b64=1&sid=fb6LRYy_xWH60vy1AASL
  locationd[69] <Notice>: Gesture EnabledForTopClient: 1 (SiriCalled)
  <Warning>: LOG SocketEngine: Writing poll:  has data: false
  <Warning>: LOG SocketEnginePolling: Sending poll:  as type: 2
  <Warning>: LOG SocketEnginePolling: Created POST string: 1:2
  <Warning>: LOG SocketEnginePolling: POSTing
  <Warning>: LOG SocketEnginePolling: Doing polling POST https://test1234.nl:3000/socket.io/?transport=polling&b64=1&sid=fb6LRYy_xWH60vy1AASL
 <Warning>: LOG SocketEnginePolling: Got polling response
 <Warning>: LOG SocketEngine: Got message: 3
 <Warning>: LOG SocketEnginePolling: Doing polling GET https://test1234.nl:3000/socket.io/?transport=polling&b64=1&sid=fb6LRYy_xWH60vy1AASL
  <Warning>: LOG SocketEngine: Writing poll:  has data: false

```
Update Code:
```
//MARK:- Establish socket connection
    func establishConnection(activeId : Int) {
        
        socket.on("connect") {data, ack in
            
            if activeId > 0 {
                SocketManager.singleton.connectToServerWithId(activeId, completionHandler: { (userList : [AnyObject]?) in
                })
            }
        }
        
        socket.onAny {event in
            debugPrint("onAny handler:::::",event.event)
        }
        
        socket.connect()
    }
    
    //MARK:- Close socket connection
    func closeConnection() {
        socket.disconnect()
    }
    
    //MARK:- Connecting to the Room using activeId
    func connectToServerWithActiveId(_ activeId: Int, completionHandler:@escaping(_ userList : [AnyObject]?)->Void) {
        
        socket.emit("activeId", activeId)
        socket.on("result") { (dataArray, socketAck) -> Void in
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "receivedRaceResultNotification"), object: dataArray[0] as! [String: AnyObject])
        }
    }


```

**Comment by nuclearace** [comment]
All I see in that log is pings and pongs. So it looks like you're connected successfully. I would make sure that you're using your API correctly.

**Comment by Nik20112** [comment]
Can you plz explain in details?

**Comment by nuclearace** [comment]
@Nik20112 Make sure that you're interfacing with your API correctly, i.e, if the server sends "hello_world", you've added a handler for "hello_world", and not "Hello_world".

You can search your whole log for the event names you're expecting to get. They should at least make it to the engine's parser. If they aren't, that indicates that you're connecting the wrong server or are not correctly authenticated with it. Authentication is something that is up to the programmer, it's not handled by the lib.

**Comment by Nik20112** [comment]
Thanks. Is any way how can I know that correct event name which is using by
server without contact to server guy?

On May 17, 2017 4:54 PM, "Erik Little" <notifications@github.com> wrote:

@Nik20112 <https://github.com/nik20112> Make sure that you're interfacing
with your API correctly, i.e, if the server sends "hello_world", you've
added a handler for "hello_world", and not "Hello_world".

You can search your whole log for the event names you're expecting to get.
They should at least make it to the engine's parser. If they aren't, that
indicates that you're connecting the wrong server or are not correctly
authenticated with it. Authentication is something that is up to the
programmer, it's not handled by the lib.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/socketio/socket.io-client-swift/issues/685#issuecomment-302061433>,
or mute the thread

**Comment by nuclearace** [comment]
Look through the logs and see what events are being sent, or print out what comes in the onAny handler. If those two don't work, you'll have to check your API.

**Comment by Nik20112** [comment]
Hi,
When I print the log inside onAny handler its returns me statusChange, connect and info events. All are events which is integrated at server side? and is it compulsory to call this method? But I have also add "raceresult" event name but can't print this method with this onAny handler so is there any issue from my side or server side?

**Comment by Nik20112** [comment]
Hi,

Please help me can't called "raceresult" event handler method while android send event to iOS but when I send event to android its working fine. I also checked the android code as well.

Am I missing something? Please help me to solve this issue.

```
func addHandlers(activeSerieId : Int) {
        debugPrint("addHandlers")
        debugPrint("Socket Details and Active Serie Id:::::",socket,activeSerieId)
        
        // Called on every event
        socket.onAny {debugPrint("got event: \($0.event) with items \($0.items)")}
        
        // Socket Events
        socket.on("connect") {data, ack in
            debugPrint("socket connected")
            
            // Sending messages
            self.socket.emit("serie", activeSerieId)
        }
        
        socket.on("raceresult") { (dataArray, socketAck) -> Void in
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "receivedRaceResultNotification"), object: dataArray[0] as! [String: AnyObject])
        }
        
        socket.connect()

    }
```

Thanks
