### ISSUE TITLE
Connect server TLS/SSL with custom certificates 

### ISSUE THREAD

**Issue by pbonato** [socketio/socket.io-client-swift#687]
Hello,
someone can help me? 
I need to make a connection to a server socket with TLS/SSL using a custom certificate give me by the CA ( I have a .CRT and .KEY files ) 

Some example code ?
Thanks

**Comment by nuclearace** [comment]
I've never tried, but it will probably involve fiddling with a custom URLSession delegate and the SSLSecurity stuff on the WebSocket. All of which I am not very familiar with.

**Comment by ffleandro** [comment]
Has anyone any sample code that can put me in the right direction?

**Comment by gyanoroprise** [comment]
How we can achieve TLS/SSL in swift 4.2
