### ISSUE TITLE
Objective - C custom path, how to do

### ISSUE THREAD

**Issue by fuchenxi** [socketio/socket.io-client-swift#688]

**Comment by nuclearace** [comment]
Should be able to translate the Swift way. config in objective-c is just a dictionary.

```swift
let socket = SocketIOClient(socketURL: url, config: [.path("/my/custom/path")])
```

[Path option](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:FO8SocketIO20SocketIOClientOption4pathFMS0_FSSS0_)

**Comment by fuchenxi** [comment]
`
_socketIO = [[SocketIOClient alloc] initWithSocketURL:[NSURL URLWithString:@"http://172.28.22.244:8888"]
                                                       config:@{@"log":@YES,
                                                                @"forcePolling":@YES,
                                                                @"path" : @"/pda/"}];

`
![default](https://cloud.githubusercontent.com/assets/24308071/26134904/69971db6-3ae4-11e7-8378-61a10cb34063.png)

**Comment by fuchenxi** [comment]
The original url is not with the path, when combined with path, print "Got unknow error from the service".But android is normal.

**Comment by nuclearace** [comment]
How does the android url look? Maybe you want a namespace and not a path?

**Comment by fuchenxi** [comment]
"http://172.28.22.244:8888/pda"

**Comment by nuclearace** [comment]
Yeah I think in the android client that's a namespace. (This is why I purposefully didn't use this feature, since it confuses namespacing and paths)

Try using the `.nsp(String)` option.

**Comment by nuclearace** [comment]
```objective-c
@{@"nsp":@"/pda"}
```

**Comment by fuchenxi** [comment]
Hah, the problem has been solved, thank you very much
