### ISSUE TITLE
NSCFArray and NSCFDictionary ?

### ISSUE THREAD

**Issue by obsobsobs** [socketio/socket.io-client-swift#69]
the data that i become from the parser are always of type NSCFArray and NSCFDictionary. It's not easy to modify the content of this classes.

my Question is: why you use NSJSONReadingOptions.AllowFragments?  

with NSJSONReadingOptions.MutableContainers it works like a charm ... i get then NSArrayM and NSDictionaryM

/************ class SocketParser *********/

// Parses data for events
    static func parseData(data:String) -> AnyObject? {
        var err:NSError?
        let stringData = data.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
        let parsed:AnyObject? = NSJSONSerialization.JSONObjectWithData(stringData!,
            options: NSJSONReadingOptions.AllowFragments, error: &err)
    }

**Comment by nuclearace** [comment]
Why not just do

```swift
socket.on("multipleItems") {data, ack in
    if var arr = data?[0] as? [AnyObject] {
        arr.append(5)
        println(arr)
    }
}

socket.on("jsonTest") {data, ack in
    if var json = data?[0] as? [NSObject: AnyObject] {
        json["bob"] = "bob"
        println(json)
    }
}
```

**Comment by obsobsobs** [comment]
because if you have an array of dictionaries, you have to cast them all too ... i spend 1 day to find a better solution i came to NSJSONReadingOptions.MutableContainers

**Comment by nuclearace** [comment]
Also, how did you find out the type of the things? When I try to reflect an array I get things like Swift._ArrayTypeMirror<Swift.Array<Swift.AnyObject>>.

Are you using it from Objective-C?

**Comment by nuclearace** [comment]
I'm not against this change, I'm just trying to remember why I did AllowFragments.

**Comment by obsobsobs** [comment]
i m using Swift, i debugged every step and i saw that they are NSCFArray and NSCFDictionary

if i cast them to a MutableDictionary... they won't work it crashes with: 

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[__NSCFDictionary setObject:forKey:]: mutating method sent to immutable object'
