### ISSUE TITLE
Compatibility with socket io 2.0

### ISSUE THREAD

**Issue by DenisLaboureyras** [socketio/socket.io-client-swift#691]
Hello,

Do you know if this client is compatible with the new socket io 2.0 ? 
I'm wondering if it can cause trouble if I upgrade my servers to this new version.

Kind regards, 
Denis

**Comment by nuclearace** [comment]
I haven't done extensive testing, but it should still work.

**Comment by nuclearace** [comment]
One thing is you'll need to pass `.doubleEncodeUTF8(false)`, since they fixed that in 2.0.

**Comment by DenisLaboureyras** [comment]
OK thanks for your answers ! I will test it

**Comment by nuclearace** [comment]
So further investigation reveals that indeed, the unicode change is fixed. But there's no way to make it backwards compatible. So I'll have to make a new major version for 2.0

**Comment by Codeido** [comment]
I don't understand if is possible for an app that use the v.1 of socket.io-client-swift to connect to a server that use the v.2. Do you have any suggestion about it?

**Comment by nuclearace** [comment]
@Codeido The newest version (10.0) should be compatible with 2.0. The main breaking change is with unicode encoding, so if you don't care if unicode becomes spaghetti, you can still use an older version.
