### ISSUE TITLE
Killing socketIO server fires .statusChange but not .disconnect

### ISSUE THREAD

**Issue by jamesriley101** [socketio/socket.io-client-swift#692]
Not sure if this is the intended behavior, but I've noticed that killing the socketIO server does not fire the .disconnect event. It does fire .status change. My client setup: 

```
class SocketIOManager: NSObject  {

  var socket: SocketIOClient = SocketIOClient(socketURL: URL(string: "http://localhost:8000")!, config: [.log(true)])

  func establishConnection() {
    ...
    self.socket.on(clientEvent: .statusChange) {data, ack in
          print("connection status changed: ", data)
    }
    self.socket.on(clientEvent: .disconnect) {data, ack in
          print("disconnect event happened: ", data)
    }
    self.socket.connect()
}
```
Running this, it works well, but killing my server (to imitate broken connection) will only cause the first print statement to execute. 

Using the .statusChanged event is fine, but I just wanted to report the behavior, because I saw that you have instructed people to use .disconnect in other issue threads. 

Thanks for building this, maintaining it, and addressing the issues!! 

EDIT: Fixed code indentation

**Comment by nuclearace** [comment]
`.disconnect` is fired when the client gives up reconnecting. `.reconnect` is what is fired when the socket will attempt to reconnect (such as the connection dropping).

**Comment by nuclearace** [comment]
https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketClientEvent.html
