### ISSUE TITLE
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

### ISSUE THREAD

**Issue by lakshmiat** [socketio/socket.io-client-swift#697]
We are using socket.io-client-swift in one of our project,our code consists of both objective c and swift.
XCode and swift versions are latest
when we tried to upload build to appstore ,we are  getting below mentioned issue.

Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

We tried below combinations are not able to upload to appstore.
1.Tried by adding cocopods but no solution.
2.Tried by down grading xcode to 8.0 also.

Guys it would be great if you help us with solution

**Comment by nuclearace** [comment]
Not sure how this library could cause that
