### ISSUE TITLE
self gets released while dispatch_async block executes.

### ISSUE THREAD

**Issue by daniel-shin1104** [socketio/socket.io-client-swift#70]
I saw lots of `dispatch_async() { [weak self]  .... }` blocks in code base where within those blocks, self is being forced unwrapped.

This can be a dangerous act if you don't retain those weak self properly by using `if let self = self` and my app crashes one out of 5 times because `self` was released while dispatch_async blocks were executing

for example,

SocketEngine.swift
```swift
public func write(msg:String, withType type:PacketType, withData data:ContiguousArray<NSData>?) {
        dispatch_async(self.emitQueue) {[weak self] in
          
            if self == nil || !self!.connected {
                return
            }
            
            if self!.websocket {
                SocketLogger.log("Writing ws: \(msg):\(data)", client: self!)
                self?.sendWebSocketMessage(msg, withType: type, datas: data)
            } else {
                SocketLogger.log("Writing poll: \(msg):\(data)", client: self!)
                self?.sendPollMessage(msg, withType: type, datas: data)
            }
        }
    }
```

Code checks if self is nil at the beginning and executes accordingly. But since you never used strong reference to that self after checking it isn't nil, there still is a possibility that it crashes app if self was released while, say, `SocketLogger.log("Writing ws: \(msg):\(data)", client: self!)` was executing since you try force unwrapping on self.

Safer and right way to do it is to use, `if let self = self { } else { }`. This way you retain pointer to self as long as newly created self is being used by the given block. I recommend switching from above pattern to `if let` pattern for all your codebase.

**Comment by daniel-shin1104** [comment]
Also not retaining pointer also caused compiler error for XCode6.3-beta unlike XCode6.3 GM. It is a good catch by compiler though I wonder why it was removed for GM..

**Comment by nuclearace** [comment]
Ugh, this is a pain in the ass. It's like the pyramid of doom all over again

**Comment by nuclearace** [comment]
```swift
dispatch_async(self.emitQueue) {[weak self] in
    if let this = self where this.connected {
        if this.websocket {
            SocketLogger.log("Writing ws: \(msg):\(data)", client: this)
            this.sendWebSocketMessage(msg, withType: type, datas: data)
        } else {
            SocketLogger.log("Writing poll: \(msg):\(data)", client: this)
            this.sendPollMessage(msg, withType: type, datas: data)
        }
    }
}
```
I do like how this one can be rewritten though.

**Comment by nuclearace** [comment]
Does that look to be a step in the right direction?

**Comment by nuclearace** [comment]
I'll do some testing later, but I must bed

**Comment by daniel-shin1104** [comment]
Looks good to me! Thanks for your work
