### ISSUE TITLE
Best way to reconnect after disconnect?

### ISSUE THREAD

**Issue by PHurtenbach** [socketio/socket.io-client-swift#700]
Hi,
what ist the best way to reconnect to the server after the connection is being closed?

I tried a simple connect() call of the SocketIOClient when clientEvent disconnect occurs but this ends in multiple connections to the server...

Thanks in advance!

**Comment by nuclearace** [comment]
What do you mean multiple connections? It shouldn't connect more than once per connect call. Have you added more than one connect handler?
