### ISSUE TITLE
Problems when connecting to an NGINX server (reversed proxy for my Node.js application)

### ISSUE THREAD

**Issue by ijean** [socketio/socket.io-client-swift#704]
Hi,

I have two problems (first one is the most pressing):

1. It seems that socket.io-client-swift always assume the server runs on the domain name root, e.g. 

`var socket = SocketIOClient(socketURL: URL(string: "https://example.com/")!)`

works, while the next instruction always seem to fail:

`var socket = SocketIOClient(socketURL: URL(string: "https://example.com/other_app/")!)`

although the server that listens at https://example.com/other_app/ works correctly when accessed from the browser. 

In the second case I found that the Swift client tries to get some resources from the domain root no matter if I set the path to be https://example.com or https://example.com/other_app/. Is this expected behaviour or am I doing something wrong ?

2. I've noticed that the Swift client sometimes enters in a loop when the connection with the server is lost, basically it keeps hitting the server with requests even after a successful reconnect. Interestingly, this doesn't happen all the time when the connection is lost, so  it is difficult to reproduce and debug. Any tips on why this could happen or how can I debug it ?

Thanks.

**Comment by nuclearace** [comment]
If you want to change the path of the server you need to use the `path` config.

**Comment by ijean** [comment]
Thanks.
