### ISSUE TITLE
Unicode Character

### ISSUE THREAD

**Issue by sinkync** [socketio/socket.io-client-swift#706]
Hello,

I'm using SocketIOClient for messaging. When I send unicode character, connection lost with error and can't connect anymore.

Error is 'Session ID unknown'

**Comment by nuclearace** [comment]
What client and server are you using? If you are using socket.io 2.0 you must use v10 of the client. If you're on socket.io you must use v9.

**Comment by sinkync** [comment]
Thanks a lot, It works. We re using socket.io on server and client v10. I downgraded to v9 and fixed.
