### ISSUE TITLE
如果我订阅多次一样的，为什么能接收多次一样的？

### ISSUE THREAD

**Issue by lishuanglong521** [socketio/socket.io-client-swift#709]

**Comment by musicabbage** [comment]
The handlers of SocketIOClient is an array, this means that how many times the target had been added into handlers, ALL of them will be executed, neither its the same object nor different

**Comment by nuclearace** [comment]
Right, the idea is you can add multiple handlers for the same event. If you only want one handler per event, make sure you only add it once. Or remove the one you add using one of the off methods.
