### ISSUE TITLE
Swift 4 Compatibility

### ISSUE THREAD

**Issue by TheSwifter** [socketio/socket.io-client-swift#710]
Hello guys,

I am using Socket.io in many iOS projects.

Just wondering when you are planning on migrating to swift 4 ?

Thanks.

**Comment by nuclearace** [comment]
There's already a Swift 4 branch for socket.io 2.0. But when Swift 4 is released proper I'll create a Swift 4 compatible version for socket.io 1.0+ and 2.0+.

**Comment by pekebyte** [comment]
Hi,

 I am kind of newbie on swift development, but I had done several projects with socket.io on web in the past.

I succesfully import your Swift 4 branch on my project adding this to my Podfile

`pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift.git', :branch => 'swift4.0'`

And had no problems building the project. Then I tried with this code

`let socket = SocketIOClient(socketURL: URL(string: "http://myserver.dev")!, config: [.log(true), .compress])
        
        socket.on(clientEvent: .connect) {data, ack in
            print("socket connected")
        }
        
        socket.connect()`

And this throws me the following message:

`OG SocketEnginePolling: Got poll message: 97:0{"sid":"aSEgh2S6EucfeQjGAAAN","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}2:40`

So I added to the config `.forceWebsockets(true)` and had this response:

`2017-09-12 18:57:19.594020-0400 marketplace[21821:2106484] LOG SocketEngine: Starting engine. Server: http://myserver.dev
2017-09-12 18:57:19.594191-0400 marketplace[21821:2106484] LOG SocketEngine: Handshaking
2017-09-12 18:57:19.622503-0400 marketplace[21821:2106484] LOG SocketEngine: Engine is being released`

No "socket connected" printed. How I can make this thing work? xD. 

Thanks in advance for any help provided.

**Comment by nuclearace** [comment]
@pekebyte looks like something the faq can help with. https://nuclearace.github.io/Socket.IO-Client-Swift/faq.html

**Comment by pekebyte** [comment]
Thanks a lot! It worked!.

**Comment by VKGraphics** [comment]
give me solution please ?
