### ISSUE TITLE
How to enable socket connecting for iOS background modes?

### ISSUE THREAD

**Issue by 2581827535** [socketio/socket.io-client-swift#712]
I want to keep socket connection alive after "applicationDidEnterBackground",
What is the correct way? And how to config the "Background Modes"? 
 Must the VOIP be enabled or not?
Show me the code, Thanks!

**Comment by nuclearace** [comment]
Background execution isn't something this library is meant for, because Apple is very strict about what you can do in the background. https://github.com/socketio/socket.io-client-swift/issues/627
