### ISSUE TITLE
Why don't use ping frame and pong frame to send/receive ping pong message? How to get the time interval between one ping and corresponding pong？

### ISSUE THREAD

**Issue by MKMichaelMK** [socketio/socket.io-client-swift#714]
1. I found the codes use text frame (%x1) to send send/receive ping pong message, by which payload data "3" means pong. Why don't use ping frame (%x9) and pong frame (%xA) to send/receive ping pong message? 
2. How to get the time interval between one ping and corresponding pong？I can't find any data contains this message in socket.io-client-swift. However, this is supported on other platforms. If this hasn't been supported, could you support this function?
Thank you!

**Comment by nuclearace** [comment]
Dup of #683.
