### ISSUE TITLE
Crash when server returns "404: Not Found"

### ISSUE THREAD

**Issue by OneSman7** [socketio/socket.io-client-swift#716]
Our server returns string "404: Not Found" if Socket.IO instance is not found  at specified url.
When client does a polling request, it attempts to interpret this string as a valid response and crashes.

It is not a critical issue since moving server instance is very rare. Just had a thought that you might want to make better checks for data correctness in _parsePollingMessage_.

**Comment by nuclearace** [comment]
Oh, yeah. If the server returns that from an engine request it will probably think that's a message since it starts with 4.
