### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by alvincrisuy** [socketio/socket.io-client-swift#717]
A lot of documentation issues are still existing.

**Comment by nuclearace** [comment]
What?

**Comment by nuclearace** [comment]
Most of the remaining documentation is in the WebSocket dependency, which I manually include here since it was easier in the early days of Swift to just include dependencies. I don't change it but for upstream changes.

**Comment by alvincrisuy** [comment]
In SocketIO-Swift.h

<img width="1278" alt="screen shot 2017-06-23 at 9 18 20 am" src="https://user-images.githubusercontent.com/7260700/27462715-5e256aea-57f5-11e7-8b51-379271da08f6.png">
<img width="1292" alt="screen shot 2017-06-23 at 9 19 19 am" src="https://user-images.githubusercontent.com/7260700/27462722-5ea31224-57f5-11e7-8a6c-e8684cdedaa5.png">
<img width="1256" alt="screen shot 2017-06-23 at 9 19 34 am" src="https://user-images.githubusercontent.com/7260700/27462718-5e3a325e-57f5-11e7-92da-84ef0781c6f5.png">
<img width="629" alt="screen shot 2017-06-23 at 9 19 47 am" src="https://user-images.githubusercontent.com/7260700/27462716-5e27137c-57f5-11e7-926f-7554269f308b.png">
<img width="1254" alt="screen shot 2017-06-23 at 9 20 01 am" src="https://user-images.githubusercontent.com/7260700/27462717-5e397c92-57f5-11e7-817a-0f02edd4e5af.png">
<img width="1245" alt="screen shot 2017-06-23 at 9 20 17 am" src="https://user-images.githubusercontent.com/7260700/27462721-5e9b8a9a-57f5-11e7-8713-6e815c13f86f.png">
<img width="624" alt="screen shot 2017-06-23 at 9 20 35 am" src="https://user-images.githubusercontent.com/7260700/27462719-5e544a40-57f5-11e7-8d9d-7586c06db34b.png">

Is it possible to remove this warnings?

**Comment by nuclearace** [comment]
Oh. I'm not sure. The documentation is written for Swift, so it doesn't always match up with the Objective-C interface.
