### ISSUE TITLE
ERROR: Invalid HTTP upgrade

### ISSUE THREAD

**Issue by thanhnt255** [socketio/socket.io-client-swift#720]
Hi,
When I use socketIO swift client to connect , I get error Invalid HTTP upgrade. My code below:

var socket: SocketIOClient = SocketIOClient.init(socketURL: URL(string: "wss://xxx:443/member")!, config: [.secure(true),.log(true), .forcePolling(true),.forceWebsockets(true),.extraHeaders(["Sec-WebSocket-Protocol":"notify","Origin":"https://abcxyz.com"])])
.....
socket.connect()

----------------------------------
But when I use Starscream lib, my app work fine:

socket = WebSocket(url: "wss://xxx:443/member")
            socket?.headers["Sec-WebSocket-Protocol"] = "notify"
            socket?.headers["Origin"] = "https://abcxyz.com"
            socket?.delegate = self
socket.connect()

Please give me some explain.
Thank you.

**Comment by nuclearace** [comment]
Is your server a plain WebSockets server? This library is not a plain WebSockets library; it's for socket.io.
