### ISSUE TITLE
Event Handler not calling

### ISSUE THREAD

**Issue by bharathreddy-97** [socketio/socket.io-client-swift#723]
I am trying to handle a event like following:
socket.on("myKey"){
     data,ack   in
   print(data[0])
}
I am connecting to socket by following code:
let socket = SocketIOClient(socketURL: URL(string: "my url string")!)
socket.connect()

I am not getting callback to the event. I tried the same with android(with same url and key) it is working fine. Did I have to do something else?
I am using XCode 8.3.3

**Comment by nuclearace** [comment]
Are you getting a connect event?

**Comment by bharathreddy-97** [comment]
yes i am getting connect event(empty array).

**Comment by bharathreddy-97** [comment]
In the .connect event ack no is -1. What might be the problem?

**Comment by bharathreddy-97** [comment]
I finally solved it. The problem was due to namespaces. My server was expecting a namespace. I added it like this in config options [.nsp("/mynamespacename")] and everything worked.
