### ISSUE TITLE
When not set nps,socket only send type 4 and not bussiness data

### ISSUE THREAD

**Issue by devliuhuan** [socketio/socket.io-client-swift#724]
Due to the use of the document is too simple, there is no mention set nps, and other examples are not set nps, resulting in the business data sent to the server in the log display area has been sent to all of the data, but only to send out a state 4, while the actual operational data is not sent, at present must be set up a NPs to normal use, should also be able to send out all data in the nps is not set.
由于使用文档太简单，根本没有提到设置nps的事，而且其他例子也没有设置nps，导致在向服务器发送业务数据时在日志区域显示已经发送了全部数据，但实际只发送出去一个状态吗4，而实际的业务数据却没有发送，目前是必须设置一个nps才能正常使用，应该在未设置nps时也能把全部数据发送出去

**Comment by nuclearace** [comment]
What?

**Comment by devliuhuan** [comment]
if not set nps，socket.io can not send any business data after it connected
