### ISSUE TITLE
how can i show return message in my UIlabel?

### ISSUE THREAD

**Issue by jonjes468250** [socketio/socket.io-client-swift#725]
excuse me 
I want show error message in my label 
(ex:testSocketIO[17721:348879] LOG SocketEngine: Got message: 42["auth_failed"])

which   can get return message?
emitWithAck or handleEvent

Thank you for your help

**Comment by nuclearace** [comment]
The `.error` client event communicates errors, however the API is inconsistent and I'm planning on standardizing it.
