### ISSUE TITLE
App get crash, when connecting to invalid url string.

### ISSUE THREAD

**Issue by vksid** [socketio/socket.io-client-swift#726]
I tried to connect to URL  "https//e7603afe.ngrok.io". App crashes while calling SocketIOClient constructor. I'm picking the url dynamically, there are chances that, app get invalid url. Socket should return some error or nil or it should throw some error which can be handle using try catch block. 

Is there any solution which can be used to avoid this problem ?

**Comment by nuclearace** [comment]
You should validate that your urls are correct before giving them to the client.

**Comment by vksid** [comment]
How can I validate url in iOS ?
canOpenUrl method in iOS return false for url "ws://example.com"
