### ISSUE TITLE
Can't connect to CryptoCompare web socket

### ISSUE THREAD

**Issue by timvermeulen** [socketio/socket.io-client-swift#727]
I'm probably missing something obvious. The url is wss://streamer.cryptocompare.com, as can be found on [their website](https://www.cryptocompare.com/api/#-api-web-socket-). I can connect to it fine using [this online socket.io client](http://amritb.github.io/socketio-client-tool/), but I can't get it to work using this library:

```
let url = URL(string: "wss://streamer.cryptocompare.com")!
let socket = SocketIOClient(socketURL: url, config: [.log(true)])
socket.connect()
```

The logs I'm getting are

```
LOG SocketIOClient: Handling event: statusChange with data: [SocketIO.SocketIOClientStatus]
LOG SocketIOClient: Adding engine
LOG SocketIOClient: Client is being released
LOG SocketEngine: Starting engine. Server: wss://streamer.cryptocompare.com
LOG SocketEngine: Handshaking
LOG SocketEnginePolling: Doing polling GET http://streamer.cryptocompare.com/socket.io/?transport=polling&b64=1
TIC TCP Conn Failed [1:0x61800017e600]: 1:60 Err(60)
HTTP load failed (error code: -1001 [1:60]) for Task <21F81135-348E-4508-95B3-419E2302AF3B>.<1>
Task <21F81135-348E-4508-95B3-419E2302AF3B>.<1> finished with error - code: -1001
ERROR SocketEnginePolling: The request timed out.
ERROR SocketEngine: The request timed out.
LOG SocketEngine: Engine is being released
```

**Comment by nuclearace** [comment]
This library isn't a WebSocket client. Check out https://github.com/daltoniam/Starscream (It's what this library uses for WebSocket.)

**Comment by yudevit** [comment]
@timvermeulen Hey Tim, did you manage to connect in the end? I'm having issues connecting to the same websocket but I'm trying in Python. Just wanted to follow up on this as you may have some useful info for me. Thanks!

**Comment by timvermeulen** [comment]
@yudevit I haven't attempted it since, sorry about that 😕

**Comment by IdeaCentricity** [comment]
Hey @timvermeulen 
replace URL(string: "wss://streamer.cryptocompare.com")!
with
URL(string: "https://streamer.cryptocompare.com/")! and it will connect without any issue.

But I am stuck at 

self.socket?.emitWithAck("SubAdd", [ "subs" : ["0~CCCAGG~BTC~USD"]]).timingOut(after: 0, callback: { (data) in
                print("data is : \(data)")
            })   

callback never called :(

**Comment by pandeyshivang** [comment]
Hi please guide me to connect this socket with streamer or else .I am very tired to connecting this issue with CryptoCompare web socket..

**Comment by timvermeulen** [comment]
Thanks @pandeyshivang, works great!

**Comment by imobdevtech** [comment]
@pandeyshivang have you do same thing in android because in iOS your solution works but in android it is not working .

**Comment by pandeyshivang** [comment]
@imobdevtech  follow this(Swift) implemention in JAVA and use [](https://github.com/socketio/socket.io-client-java)

**Comment by imobdevtech** [comment]
@pandeyshivang we already follow all the step which is swift but we stuck at emit statement , everytime we got **1 - bad request** . can you please that portion code if feasible

**Comment by pandeyshivang** [comment]
@imobdevtech wait...i'll share code

**Comment by imobdevtech** [comment]
@pandeyshivang finally find the solution thank you for your support

**Comment by pandeyshivang** [comment]
i think you were missing or wrong emit before soket.onlistener callback.

**Comment by cbadhrinath** [comment]
> @pandeyshivang finally find the solution thank you for your support

could you please post the correct solution you found. I'm having the same issue here.

**Comment by cbadhrinath** [comment]
Found the right way for Java version. The following should work:

JSONObject object = new JSONObject();
JSONArray arr = new JSONArray();
try {
arr.put("11~BTC'");
object.put("subs", arr);
socket.emit("SubAdd", object);
} catch (JSONException e) {
e.printStackTrace();
}

**Comment by pandeyshivang** [comment]
> Found the right way for Java version. The following should work:
> 
> JSONObject object = new JSONObject();
> JSONArray arr = new JSONArray();
> try {
> arr.put("11~BTC'");
> object.put("subs", arr);
> socket.emit("SubAdd", object);
> } catch (JSONException e) {
> e.printStackTrace();
> }

please try to use hashmap and arraylist instead of jsonobject and array

**Comment by cbadhrinath** [comment]
@pandeyshivang The performance is the same as HashMap and no extra overhead. 
Also, considering that we are dealing with actual JSON on the request, I highly recommend it.
The actual docs use JSONObject too.
https://github.com/socketio/socket.io-client-java - check the readme.
