### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ilandbt** [socketio/socket.io-client-swift#728]
Hi,

I have a webSocket manager singleton.

    class WebSocketManager {
        static let shared = WebSocketManager()
        var socket: SocketIOClient!

        init() {
            guard let url = URL(string: chatUrl)  else { return }
            socket = SocketIOClient(socketURL: url, config: [.log(addLog), .secure(true), .forcePolling(false)])
        }

I'm getting a memory leak on 

     socket = SocketIOClient(socketURL: url, config: [.log(addLog), .secure(true), .forcePolling(false)])
       
Am i doing something wrong? 

When i move the socket code from a singleton to my `UIVIewController`
all of the leaks disappear, except one in this line.

`self.config.insert(.path("/socket.io/"), replacing: false)`

in `SocketIOClient` class 

Thanks

**Comment by nuclearace** [comment]
I wouldn't trust Instruments for leak detections in Swift. I notice a lot of times it gives false positives (especially with String).

**Comment by ilandbt** [comment]
But my app is crashing in random places with the socket object.

**Comment by nuclearace** [comment]
Crashing for what reason?

**Comment by ilandbt** [comment]
see in image:
[https://image.ibb.co/jq1XNv/sio1.png](url)

its my crashlytics report.
it seems very random crashes but all of them are in SocketIO

**Comment by nuclearace** [comment]
Yeah that image doesn't help much diagnose why it might be crashing.

**Comment by ilandbt** [comment]
That's exactly my problem it crashes every time in a different location in SocketIo's code.

Thanks anyway.
