### ISSUE TITLE
Session ID unknown

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [socketio/socket.io-client-swift#731]
Hi,

I have added socket io code in my app but I am getting an issue and scenario of the issue is I connect the app with server but as I lock the phone I got following error 
{"code":1,"message":"Session ID unknown"}
Please let me know how to resolve the issue.

Thanks

**Comment by nuclearace** [comment]
Background execution isn't explicitly supported. Does it reconnect when the app comes back into the foreground?

**Comment by DaVincii** [comment]
For socket.io v2.0.3 (js client):
When you use socket.io on client side the client socket.io makes some network calls as explained:
1. When io.connect() is called, the  socket.io library makes a call to the server which looks like 
`?EIO=3&transport=polling&t=LqtOnHh`, server responds with something like  `"90:0{"sid":"pcJM_AEZirrJT-DuAAUy","upgrades[],
"pingInterval":3600000,"pingTimeout":3600000}2:40"`
here the server generates a socket object on server side and sends its id back to the client.
2. After this client makes call to the server which is something like 
`?EIO=3&transport=polling&t=LqtR6Rn&sid=0JFGcEFNdrS-XBZeAAXM`, this is the long poll call that client makes to the server, if you see here it is passing the sessionId which it received in first call above, if the call goes to same node which generated that sessionId, the node identifies the socket connection for which the request has been made and responds.

But behind ELB the call may go to some other node that didn't generate this sessioIs, in that case the node will not be able to identify the sessionId for which the call was made and hence responds with `{"code":1,"message":"Session ID unknown"}`

You will also see this error in case of long polling not getting answered or getting timeout.

**Comment by butterpuf** [comment]
@DaVincii Hi, Can you guid how we can simulate "Session ID unknown" error. That, the app create session with a node but request to some other node. Because I am facing this error a lot. But unable to find what I am doing wrong. Any test case that can help me?

**Comment by DaVincii** [comment]
@butterpuf  use stickiness to get rid of this problem

**Comment by vijeshv** [comment]
?EIO=3&transport=polling&t=LqtOnHh

what is the significance of t=LqtOnHh

is t a timestamp . but  how LqtOnHh is comuting?
