### ISSUE TITLE
Socket IO blocks main thread

### ISSUE THREAD

**Issue by theDude30** [socketio/socket.io-client-swift#732]
Hi,
It looks like when i connect with SocketIOClient it blocks some web service calls.
I tried the following and it did not work:
 [self.socket setHandleQueue:dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0)];

do you have any idea why is it blocking? and how to resolve that?

**Comment by nuclearace** [comment]
By default the socket uses the main queue. You can pass a different handle queue using the `handleQueue` option.

**Comment by nuclearace** [comment]
Also, setting the handleQueue to a concurrent queue will most likely cause a crash, it must be a serial queue.
