### ISSUE TITLE
Multiple connect events when joining one or many namespaces

### ISSUE THREAD

**Issue by matthewgoslett** [socketio/socket.io-client-swift#733]
I'm using a single socket for this application, and this socket can connect to one or many namespaces.

1. socket.connect() is called
2. The `clientEvent: .connect` event is emitted.
3. socket.joinNamespace("/foo") is called
4. The `clientEvent: .connect` event is emitted again.
5. socket.joinNamespace("/bar") is called
6. The `clientEvent: .connect` event is emitted again.

I would expect the event to only be called once, since the socket is already connected, and I've only just joined another namespace on this existing socket.
The business logic on connect shouldn't run every time a socket joins a namespace, unless there's a way to determine the namespace joined ("or connected to") in the connect event?

**Comment by nuclearace** [comment]
I'll add the connected namespace to the connect event's data.

```swift
socket.on(clientEvent: .connect) {data, ack in
  guard nsp = data[0] as? String else { return }
  // Use nsp
}
```
