### ISSUE TITLE
how to renew connectParams before reconnect in OC?

### ISSUE THREAD

**Issue by pkuhonker** [socketio/socket.io-client-swift#734]
My socket is inited by the follow codes. How to renew the token before socket reconnect caused by network restore? (Because the old token  may be expired ,must be renew) 
```
NSDictionary *mytoken = [NSDictionary dictionaryWithObjectsAndKeys:token, @"token", nil];
NSDictionary *opts = [NSDictionary dictionaryWithObjectsAndKeys:@YES,@"log",mytoken,@"connectParams",@YES,@"forceWebsockets", nil];
socket = [[SocketIOClient alloc] initWithSocketURL:url config:opts];
```
I guess i should do something like：
```
    [socket on:@"reconnectAttempt" callback:^(NSArray * data, SocketAckEmitter * ack) {
//        socket.config = ....
```
but, config property can't be used in OC?

**Comment by nuclearace** [comment]
You might be able to manually set the connect params on the engine. https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketEngineSpec.swift#L40

**Comment by pkuhonker** [comment]
3x！You are so nice! @nuclearace
