### ISSUE TITLE
No such module 'CommonCrypto'

### ISSUE THREAD

**Issue by b593771943** [socketio/socket.io-client-swift#736]
I copy the Source folder into your Xcode project, then this error occured, How to solve it,Please give me your addvice

**Comment by ambujshukla** [comment]
You can install the files via cocoapod. It has no issue like this.
pod 'Socket.IO-Client-Swift'

**Comment by nuclearace** [comment]
Yeah I need to remove the manual install from the readme. You'll have to some extra work to get manual install to work now, since it uses some system libraries that have to be linked in.

**Comment by KKKiller** [comment]
so what should if i want to use it manual,what is the extar work?

**Comment by nuclearace** [comment]
You have to add the zlib header as a private header for your project and change the Swift framework path to point to the zlib folder.

**Comment by KKKiller** [comment]
what should i do about CommonCrypto

**Comment by KKKiller** [comment]
About your reply   "You have to add the zlib header as a private header for your project and change the Swift framework path to point to the zlib folder."   
 I'm sorry to tell you  that  i don't know hot to make it. can you show me  step by step. such as how to add a private header to my project and how to point the folder.
  A thousand thanks!

**Comment by marcuschoong** [comment]
@KKKiller Do you able to solve it ?

**Comment by akdsouza** [comment]
For someone still having the issue, adding pod 'Starscream', '<= 3.0.5' solves the issue. See https://github.com/daltoniam/Starscream/issues/575
