### ISSUE TITLE
Swift - Cookie authentication

### ISSUE THREAD

**Issue by Nikiraf** [socketio/socket.io-client-swift#738]
Is it possible to connect to web socket with cookie authentication?
We have socket implementation on our server side with cookie authentication. Web client is using default cookie authentication. But I'm not sure how to implement it in iOS application.
Shell we change server side to use different authentication?

Thanks,
Alexander

**Comment by nuclearace** [comment]
There's a cookie's [option](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:FO8SocketIO20SocketIOClientOption7cookiesFMS0_FGSaCSo10HTTPCookie_S0_).

**Comment by rishbaranwal** [comment]
Hi Any update on this ?
