### ISSUE TITLE
Swift 4 Substring

### ISSUE THREAD

**Issue by bhaze31** [socketio/socket.io-client-swift#739]
In the function `handleBase64(message: String)` in `SocketEngine.swift` the new Substring type in Swift 4 leaves an error message `Type of expressions is ambiguous without more content`. The Data object needs a String, and as Substring is not directly related to String, the constant noPrefix needs to be cast as a String.

Documentation: https://developer.apple.com/documentation/swift/substring

Fix: `let noPrefix = String(message[message.index(message.startIndex, offsetBy: 2)..<message.endIndex])`

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/blob/swift4.0/Source/SocketEngine.swift#L224

**Comment by nuclearace** [comment]
Use the Swift 4 branch
