### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tolgay007** [socketio/socket.io-client-swift#74]
Hi

I have trouble with installation. I copied socket.io client folder to my project. When I try to compile them I am getting following errors: http://prntscr.com/70fkrc

Do you know how can I fix them ?

**Comment by nuclearace** [comment]
Are you using Xcode 6.3?

**Comment by tolgay007** [comment]
I am using 6.1.1

**Comment by nuclearace** [comment]
You need 6.3 or an earlier version of the socket.io-client

**Comment by tolgay007** [comment]
Oh, okay. Thank you.
