### ISSUE TITLE
Socket automatically gets connect disconnect frequently.

### ISSUE THREAD

**Issue by milan-mgu** [socketio/socket.io-client-swift#741]
I am using 10.2.0 socket.io client library. And i am facing frequent fluctuation of socket connecting and disconnecting automatically . 
Also My server is not able to receive emit event and my server socket version is 2.0.3.

**Comment by nuclearace** [comment]
Do you have some logs? Was this on Wifi? If it was on 3G/LTE that might be common, since those connections are going to be unreliable.

**Comment by kinza88** [comment]
@milan-mgu hey any solution to this?
