### ISSUE TITLE
pod install seems doesn't install correctly

### ISSUE THREAD

**Issue by goharika** [socketio/socket.io-client-swift#742]
I am installing via pods, but when I am trying to import SocketIO this return me no such module

**Comment by nuclearace** [comment]
What version of the client?

**Comment by goharika** [comment]
the last one, I haven't add version on pod so it should be last one. I have add from frameworks too, it seems working, but it mean I have done both pod install and manual too, in some cases apple reject such installations, or bringing errors

**Comment by vincelupo** [comment]
What is the latest version of it?    I can't seem to pod install v11.

```
use_frameworks!

target ‘SocketChat’ do
    pod 'Socket.IO-Client-Swift’,  '~> 11.0.0' # Or latest version
    pod 'Starscream', '~> 2.0.3'
end
```

**Comment by nuclearace** [comment]
The cocoapods website says 11.0.0 is there. Did you update the pod repo to make sure it's current?

**Comment by 9527001** [comment]
全是外国人吗

**Comment by 9527001** [comment]
The version of current cocoapods is 11.0.0 ? I'm 1.2.1 . why?

**Comment by 9527001** [comment]
@nuclearace

**Comment by srinivasgadda** [comment]
I am using the pod with 11.0.1 but still no such module error. I have noticed that the framework was not converted to Swift 3 syntax. When I try to convert, it is giving more than 150 errors in the pod project.

pod 'Socket.IO-Client-Swift', '~> 11.0.1'

**Comment by nuclearace** [comment]
It should most definitely be Swift 3 compatible. There's another branch for Swift 4 though.

**Comment by srinivasgadda** [comment]
I found the issue that the library's swift language version not defined. I went to Build Settings for the framework and chosen Swift 3 as swift language. Now, able to get it.

**Comment by nuclearace** [comment]
Oh, I must've accidentally removed that from the pod spec

**Comment by nuclearace** [comment]
@srinivasgadda I've updated to podspec and pushed a new version, so hopefully it resolves that issues without having to manually intervene.

**Comment by Spadille** [comment]
same issue with Xcode 8.33, swift 3 and cocopods 1.3.1, I tried every solution before but did not work

**Comment by nuclearace** [comment]
@Spadille what version and what is the error?

**Comment by Spadille** [comment]
@nuclearace It's version 11.1.1 and the error is 'no such module', thanks!

**Comment by goroya** [comment]
Me too on cocoapod 1.4.0.beta.1.

**Comment by nhnam** [comment]
try import #import <SocketIO/SocketIO-Swift.h> instead of #import <SocketIO/Socket.IO-Client-Swift.h>
