### ISSUE TITLE
Receiving Unicode String

### ISSUE THREAD

**Issue by syedrazackimran** [socketio/socket.io-client-swift#743]
"\U00e1\U009e\U009f\U00e1\U009e\U0098\U00e1\U009f\U0092\U00e1\U009e\U009b\U00e1\U009e\U0098\U00e1\U009f\U0092\U00e1\U009e\U0087\U00e1\U009e\U00bc\U00e1\U009e\U009a\U00e1\U009e\U0082\U00e1\U009f\U0092\U00e1\U009e\U009a\U00e1\U009e\U00bf\U00e1\U009e\U0084”

i'm receiving response like Unicode Character . character contain language string like chinese    . How to convert it as string !! i don't know !

**Comment by nuclearace** [comment]
What server version are you using? If it's socket.io 2.0+ make sure you're using client version 10+.  Else you'll want 9

**Comment by syedrazackimran** [comment]
thanks for your response !! i fixed that !!
