### ISSUE TITLE
see this .when i copy source to my project

### ISSUE THREAD

**Issue by huFly** [socketio/socket.io-client-swift#745]
<img width="743" alt="wx20170713-185100 2x" src="https://user-images.githubusercontent.com/8486300/28163094-46acf06a-67fc-11e7-9745-7a1eca4a0419.png">

**Comment by nuclearace** [comment]
See https://github.com/socketio/socket.io-client-swift/issues/736

**Comment by huFly** [comment]
oh, i solve it by add  "swift compiler -> import paths" with the zlib folder path . the wey like info.plist path, not the example of SocketIO-iOS

**Comment by marcuschoong** [comment]
I having the same problem but change the import paths to zlib folder doesn't work for me. please help
