### ISSUE TITLE
can't pod install.

### ISSUE THREAD

**Issue by supercartoon** [socketio/socket.io-client-swift#750]
i tried to install with pod. but i have an error.
i used 'pod 'Socket.IO-Client-Swift', '~> 10.2.0' # Or latest version' but terminal get error like below.

[!] Unable to satisfy the following requirements:

- `Socket.IO-Client-Swift (~> 10.2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Socket.IO-Client-Swift (~> 10.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by nuclearace** [comment]
Have you run `pod repo update`?

**Comment by supercartoon** [comment]
It's solved. thanks!

**Comment by oskarko** [comment]
@nuclearace you saved my day! Thanks!!

**Comment by akshayshikre** [comment]
Thanx
