### ISSUE TITLE
/Source/SocketEngineWebsocket.swift:27:8: No such module 'StarscreamSocketIO'

### ISSUE THREAD

**Issue by 18667366881** [socketio/socket.io-client-swift#753]
/Source/SocketEngineWebsocket.swift:27:8: No such module 'StarscreamSocketIO'

**Comment by SalvatoreAD** [comment]
Have you tried installing the pod?

pod 'Starscream', '~> 2.0.3'

**Comment by 18667366881** [comment]
thank

**Comment by 18667366881** [comment]
ERROR: handshake failed ... Server returned status code 403   Excuse me, what's the reason for that?

**Comment by nuclearace** [comment]
How did you install the lib?

>ERROR: handshake failed ... Server returned status code 403 
Idk, sounds like you're using your API wrong.

**Comment by tutanck** [comment]
I have the same problem here : 
![capture d ecran 2017-08-21 a 02 49 28](https://user-images.githubusercontent.com/15267552/29499929-8e0d7938-861b-11e7-8e8b-8196f26c92bf.png)

I tried to install the 'Starscream' pod ... Still not working

**Comment by nahuelnewsdeveloper** [comment]
I've the same error... please help

**Comment by tutanck** [comment]
@nahuelnewsdeveloper
Use the cocoapod to install socketIo instead of doing it manually. Using the pod will resolve dependencies and automatically install the StarsCream pod for you
