### ISSUE TITLE
How to import Starscream when I use the BridgingHeader to add SocketIOClient version 11.

### ISSUE THREAD

**Issue by NyeinEiEiTun** [socketio/socket.io-client-swift#755]
At the first I'm using previous version before 11 (swift 2.3) in xcode 8.2.1 in OS X EL Capitan. But now I have to upgrade OS Sierra and use xcode 8.3.3 for some projects. Then I also need to upgrade the swift version for current socketIO-client to swift3. But current project is written in objective-c. So Im using the bridging header file to manually add the socketIO. 

But I got some problems to use the latest version of socketIO-client (version11) because it had a dependency called Starscream and I could not add that manually to my project using bridging header. Could you please help me to add Starscream manually to the project using bridging header.
Regards and thanks.

**Comment by nuclearace** [comment]
Is the socket.io library itself being bridged? How did you install the library? Via CocoaPods?

**Comment by NyeinEiEiTun** [comment]
No I did not use the CocoaPods to install socket.io lib. I have imported swift files to objective-c project manually according to this link, https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html.

**Comment by nuclearace** [comment]
Okay. Manually installing is no longer officially supported since you have to fiddle with adding system libs. You can try version 10.0.1, which still had manual install, otherwise you'll have to use CocoaPods or the Swift Package Manager.

**Comment by NyeinEiEiTun** [comment]
which swift version is used in version 10.0.1?

**Comment by nuclearace** [comment]
3.1

**Comment by NyeinEiEiTun** [comment]
thanks so much for ur replies 👍

**Comment by nuclearace** [comment]
Is this solved?

**Comment by yirankege** [comment]
when i used the CocoaPods to install socket.io lib.i don't know how to import files in my project.i builded a new project to use the CocoaPods ,but it's still wrong.so i want to know how to  do that .

**Comment by NyeinEiEiTun** [comment]
@nuclearace Sorry for my late responses. Yes I could use 10.0.1 with swift 3. Now I can use xcode 8.3.2 for my projecct :). Thanks so much for your help

**Comment by yirankege** [comment]
@nuclearace  can you tell me how use  Cocoapod import my project?

**Comment by NyeinEiEiTun** [comment]
@yirankege u using swift or objective c?

**Comment by yirankege** [comment]
@nuclearace objective-c

**Comment by NyeinEiEiTun** [comment]
then tried to add use_framework! in your pod file

**Comment by yirankege** [comment]
@NyeinEiEiTun 
platform :ios, '8.0'
use_frameworks!

target ‘aaa’ do
pod 'Socket.IO-Client-Swift','~> 11.0'
end

it's my cocoapod‘s use.i think that's right.

**Comment by NyeinEiEiTun** [comment]
Yes you r right. But it doesn't work? What error did you got?

**Comment by yirankege** [comment]
Xcode 8 will not be able to build the targets “Socket.IO-Client-Swift” and “StarscreamSocketIO”, and certain editing features will not function properly until the Swift source code in these targets has been converted.

This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.


first my project is Objective-c and it need me to update my swift version ,so i don't understand this，i didn't do anything.

**Comment by NyeinEiEiTun** [comment]
which version of xcode are u using? xcode 8.2.1?

**Comment by yirankege** [comment]
xcode 8.3.3

**Comment by yirankege** [comment]
maybe the version i imported sokect.io is too low?

**Comment by NyeinEiEiTun** [comment]
I also have some problem in installing socket.io version 11 using cocoapods. Because I'm implementing objective c project and also have to use other objective-c pod libraries. If we install swift pod file in objective-c project, we need to use use_frameworks!. But using that causes other library won't work in my project. So I have decided not to install the socket.io using cocoa pods. 
But socket.io version 11 used starscreams as the dependency. So It is not okay for me to install manually. That's why I have decided to use socket.io version 10.0.1 as @nuclearace  suggested.

**Comment by yirankege** [comment]
yes,i think so,i just can't find the way to use cocoapod or Manual installation。

**Comment by NyeinEiEiTun** [comment]
Then u use the manual installation using socket.io version 10.0.1.
You can find the instructions for manual installation here. https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html.

to get the socket.io library files, You need to install socket.io version 10.0.1 using cocoapods. Then you file the socket.io pod file in ur project. Then copy that file and manually add to ur project. After copying that file, remove the socket.io from pod file again.

**Comment by yirankege** [comment]
that is not good idea, i even want to rewirte the project with swift.
i will try using you method first.

**Comment by yirankege** [comment]
@NyeinEiEiTun  thank you so much.

**Comment by NyeinEiEiTun** [comment]
If you can rewrite your project with swift, your problem would be solved. But I have no choice. That is my last option. 😆 😆 . You r welcome :)

**Comment by yirankege** [comment]
i thank i find the way.

**Comment by yirankege** [comment]
i builded a new project, project is objective-c. first new a file of swift and bulid a bridge file,then use cocoapod import socket.now i can use @import SocketIO in my objective-c file.it's done,now i can use socket.io on my project.

**Comment by NyeinEiEiTun** [comment]
@yirankege. 😲  You still need the bridging header after using the cocoapods?

**Comment by yirankege** [comment]
creation should be before use.

**Comment by NyeinEiEiTun** [comment]
Later, I will try ur way 👍
