### ISSUE TITLE
Library not loaded: @rpath/StarscreamSocketIO.framework/StarscreamSocketIO

### ISSUE THREAD

**Issue by BBK-PiJ-2016-11** [socketio/socket.io-client-swift#756]
`Library not loaded: @rpath/StarscreamSocketIO.framework/StarscreamSocketIO`

Getting this error after pulling the latest version with Carthage, didn't happen before. (few days ago)
Could someone please advise?

**Comment by nuclearace** [comment]
Oh, Carthage probably broke with the last thing. I'll have to figure out how to fix that.

**Comment by BBK-PiJ-2016-11** [comment]
Thanks for that @nuclearace !

**Comment by nuclearace** [comment]
If you add `github "nuclearace/Starscream" ~> 8.0.1` to the Cartfile does it help anything.

**Comment by BBK-PiJ-2016-11** [comment]
It does, thanks a lot!
