### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by pinkladywithcoco** [socketio/socket.io-client-swift#757]
Hi,

My home Socket.io server support only IPv4.

Will IPv6/IPv4 clients be able to connect to an IPv4 server??

If the IPv6 client connect from socket.io-client-swift to the url of my IPv4 server... will he be able to connect???

Can someone please confirm that...??

**Comment by nuclearace** [comment]
Usually you get both an IPv4 and IPv6 address, so everything should still work.

**Comment by pinkladywithcoco** [comment]
Hi nuclearace 

Many thanks for the prompt reply!

But my ISP just told me that they dont support IPv6 and only IPv4 is provided.

Will IPv6 clients still be able to connect to my server???

**Comment by nuclearace** [comment]
Like I said, most ISPs that support IPv6 will provide both a IPv6 and IPv4 address. And if they don't there's things like [6in4](https://en.wikipedia.org/wiki/6in4)

**Comment by pinkladywithcoco** [comment]
Thanks for confirming that :)

- Can Socket.io listen to both IPv6 and IPv4?  is so how???
