### ISSUE TITLE
use socket.connect() in v2.2.3 has a problem

### ISSUE THREAD

**Issue by Soniy7x** [socketio/socket.io-client-swift#76]
let socket = SocketIOClient(socketURL: "http://192.168.22.109:3000")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.socket.connect()
        println(socket.connecting)
        println(socket.connected)
    }

this result is false that connect server failed.

**Comment by nuclearace** [comment]
What is false? Does the socket still connect but connected says false?

**Comment by Soniy7x** [comment]
yes, connected says false but this was connected.

**Comment by nuclearace** [comment]
I'll look into it. But Connect is an async method. So it would make sense it would say false right there.

**Comment by Soniy7x** [comment]
I see. Thank U!
