### ISSUE TITLE
How can I access SSLSecurity.swift from my Objective-C project?

### ISSUE THREAD

**Issue by IbrahimKZ** [socketio/socket.io-client-swift#761]
I'm working with socket.io in my Objective-C project for 2 years.
Lately I need to integrate SSL pinning. I found this option in 

`[[SocketIOClient alloc] initWithSocketURL:serverURL config:@{... @"secure": [[SSLSecurity alloc] ...}`

but I can't call SSLSecurity class from Objective-C because it doesn't conform to NSObject.
How can I add SSL pinning to socket.io with certificate to my Objective-C project?

**Comment by ldbfrank** [comment]
No, can NOT.

**Comment by ldbfrank** [comment]
It seems the only way is that you should modify file SocketIOClient.swift directly.

**Comment by IbrahimKZ** [comment]
I have found solution using https://github.com/acmacalister/jetfire for Objective-C instead of SSLSecurity.

**Comment by nuclearace** [comment]
Oh, oops. This was one of the reasons I moved Starscream to a fork and out of this project. I think I can fix this.

**Comment by nuclearace** [comment]
Should hopefully be fixed in 11.0.1.

**Comment by ldbfrank** [comment]
Now, you could use Socket.io-client-swift 11.0.1 and Starscream 8.0.2 ! It good!

**Comment by ldbfrank** [comment]
Thanks nuclearace! I have tested, it work!
