### ISSUE TITLE
Get 11.0.1 source and Starscream, but compile error

### ISSUE THREAD

**Issue by ldbfrank** [socketio/socket.io-client-swift#765]
"No such module 'StarscreamSocketIO" when I compile the project after git clone 11.0.1 and Starscream.

**Comment by ldbfrank** [comment]
Oh, the Starscream from git is old version, I have download 8.0.2

**Comment by nuclearace** [comment]
What?

**Comment by ldbfrank** [comment]
Sorry, I have compiled successful. Thanks.
