### ISSUE TITLE
Socket.on ("RecieveMessage") not invoked to my side when other user send message

### ISSUE THREAD

**Issue by Harryiosdev** [socketio/socket.io-client-swift#766]
I ma new to Socket.io, Please help me out of it.

When other user send message  I he is receiving message at his side
socket.emit("send message", Message)
        socket.on("get message") { ( dataArray, ack) -> Void in
            self.socket.removeAllHandlers()
            completionHandler( dataArray[0] as? [String: AnyObject])
        }

but  at other Users side it not working, Other user 
 socket.on("get message") { ( dataArray, ack) -> Void in
            self.socket.removeAllHandlers()
            completionHandler( dataArray[0] as? [String: AnyObject])
        }
not invoking.
Anybody Plz guide me.
Thanks

**Comment by nuclearace** [comment]
The event names must match up. So if they send an event "send message" you have to have a handler for "send message".

**Comment by Harryiosdev** [comment]
Yes the event name is same thats why its working on sender side to receive message  but not working on receiver side to receive message.

**Comment by nuclearace** [comment]
What is your server doing? Is it rebroadcasting the message from one client to all the others?

**Comment by Harryiosdev** [comment]
Yes, I am using it for group chat in iOS and  , I want it to broadcast message  to other users

**Comment by Harryiosdev** [comment]
I am using this link to code in my app
http://www.appcoda.com/socket-io-chat-app/

**Comment by nuclearace** [comment]
What does your client code look like?

**Comment by Harryiosdev** [comment]
This is the code i used to send message and receives.

func sendTextMessage(Message: [String: String], completionHandler: @escaping (_ userList: [String: AnyObject]?) -> Void) {
        socket.emit("send message", Message)
        socket.on("get message") { ( dataArray, ack) -> Void in
            self.socket.removeAllHandlers()
            completionHandler( dataArray[0] as? [String: AnyObject])
        }
    }
    
Is there something wrong please let me know

**Comment by nuclearace** [comment]
It's generally bad form to add handlers in a method like this. Generally it's better to know what your handlers are upfront, and them once. But where is the socket object declared? If it's a local variable and not a property or global variable it's possible it's being released too early. It'll also help you if you can turn on logging for the client.

**Comment by Harryiosdev** [comment]
It means , your are saying that i need to remove the socket.on("get message") in the send message section an to code it separately like this
Please check it and confirm.
Aslo I need to turn on login for client?
Is it making sense?

func sendTextMessage(Message: [String: String], completionHandler: @escaping (_ userList: [String: AnyObject]?) -> Void) {
        socket.emit("send message", Message) 
    }
 

    func getChatMessage(completionHandler: @escaping (_ userList: [String: AnyObject]?) -> Void) {
       socket.removeAllHandlers()
        socket.on("get message") { ( dataArray, ack) -> Void in
            print(dataArray)
            print(ack)
            completionHandler( dataArray[0] as? [String: AnyObject])
        }
    }
    
Please confirm.

**Comment by nuclearace** [comment]
I mean you would only have one handler for that message, and you add it once. Otherwise you run the risk of getting an event when you don't have a handler for it, in which case it'll be lost.

Simplified example:

```swift
import SocketIO

let socket = SocketIOClient(socketURL: myUrl, config: [.log(true)])

func addHandlers() {
  self.socket.on("chatMessage") {data, ack in }
}

// somewhere addHandlers is called, and then connect is called
```

Beyond this help, I'm not sure what else to tell you.

**Comment by Harryiosdev** [comment]
I have initialised socket now with  .log as you mentioned.

Also made separate handler to get the message after sending.
But if i am not adding 
socket.removeAllHandlers()
before get message then i am getting 
the ist messt sending for its time,
2nd msg  two times, 
3rd msg three time,
when i came out of the group and again joining the group then i am getting in same sequence
Can you plz guide me in this

**Comment by nuclearace** [comment]
That sounds like you're adding the event handler multiple times... You need to add it _one_ time.  And if you're doing something complicated like dynamic events, you're going to have to make sure that you add the event handler before sending the event, and making sure that you remove the event after it is fired, or use the `.once` handler.

**Comment by Harryiosdev** [comment]
Thanks a lot  It works
Your effort is really appriciable
you are a genius......
Thanks again
