### ISSUE TITLE
Issue in Adding in Objective C Project - no such module StarscreamSocketIO

### ISSUE THREAD

**Issue by bfjfm2** [socketio/socket.io-client-swift#767]
I am using existing version of socket.io swift code in my objective-c project by copying swift files from the Source folder and it is working fine.

I am trying to update with latest **11.0.2** code like above method.

 During compiling it shows following error 
in **SocketIOClientOption.swift** 
**no such module StarscreamSocketIO**

May I know how to add source code in my existing Objective C project.

**Comment by nuclearace** [comment]
Manually adding is no longer supported since Starscream was moved to be a dependency. You'd have to copy the Starscream files and add some additional things to get the system modules working.

**Comment by bfjfm2** [comment]
I tried to add in pod file for my objective c project. After pod install got following warning

> [!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: Socket.IO-Client-Swift and StarscreamSocketIO


``
 platform :ios, '8.1'
def common_pods_for_target
    pod 'SBJson', '~> 4.0.1'
    pod 'googleapis', :path => '.'
    pod 'PHFComposeBarView', '~> 2.0.1'
    pod 'AFNetworking', '~> 2.0'
    pod 'PINCache', '~> 2.1'
    pod 'SVProgressHUD'
    pod 'StreamingKit'
    pod 'APAddressBook', '~> 0.3.1'
    pod 'libPhoneNumber-iOS', '~> 0.9.10'
    pod 'Parse', '1.15.0'
    pod 'ParseUI'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Digits' #,'~> 2.8.0'
    # Only pull in Phone Auth login features
    pod 'FirebaseUI/Phone', '~> 4.0'
    pod 'CLImageEditor/ResizeTool'
    #pod 'JSQMessagesViewController'#Chat Message View
    pod 'Socket.IO-Client-Swift', '~> 11.0.2' # Or latest version
    pod 'Branch'
end
target 'AppDev' do
common_pods_for_target
end
target 'AppLive' do
common_pods_for_target
end

**Comment by bfjfm2** [comment]
I think this is still an issue. Because before, I can able to add code directly and everything working fine. Now I can't able to add code directly.  This one blocks to upgrade my entire project.
