### ISSUE TITLE
Issue in Adding Socket.io swift Pod in Objective-C Project PodFile

### ISSUE THREAD

**Issue by bfjfm2** [socketio/socket.io-client-swift#768]
I tried to add in pod file for my objective c project. After pod install got following warning and can't able to compile. 

> [!] Pods written in Swift can only be integrated as frameworks; add use_frameworks! to your Podfile or target to opt into using it. The Swift Pods being used are: Socket.IO-Client-Swift and StarscreamSocketIO

platform :ios, '8.1'
def common_pods_for_target
pod 'Parse', '1.15.0'
pod 'ParseUI'
pod 'Fabric'
pod 'Crashlytics'
pod 'Digits'
pod 'Socket.IO-Client-Swift', '~> 11.0.2'
pod 'Branch'
end
target 'AppDev' do
common_pods_for_target
end
target 'AppLive' do
common_pods_for_target
end

**Comment by bfjfm2** [comment]
I managed to update all other pod files successfully and updated latest socket.io server also. The only problem of adding Socket.IO-Client-Swift 11.0.2 either by manual or by a pod.

**Comment by nuclearace** [comment]
Have you added `use_frameworks!` to your Podfile? That's what the error says and what's in the readme https://github.com/socketio/socket.io-client-swift#cocoapods-100-or-later.

**Comment by bfjfm2** [comment]
When I use use_frameworks! it creates issues in ParseUI pod and Google Speech pod. I can able to fix google speech pod but can't fix ParseUI pod. 

My only option to upgrade my ios client needs to add code directly. Any way that I can add code directly?

**Comment by nuclearace** [comment]
I'm sure it's possible, but I don't have the time to figure out the steps. Basically what you have to do is copy the client files, copy the starscream files, remove the imports for the starscream lib. And then figure out how to import the libraries it needs. The last part is what willl take the most effort

**Comment by bfjfm2** [comment]
I have commented import StarscreamSocketIO but it is showing error on commenting 
1.CZLib and 
2.CommonCrypto

[Socket.IO.11.0.2_Except_CZLib_And_CommonCrypto.zip](https://github.com/socketio/socket.io-client-swift/files/1211219/Socket.IO.11.0.2_Except_CZLib_And_CommonCrypto.zip)

**Comment by nuclearace** [comment]
Right, you'll have to take a look at https://github.com/nuclearace/Starscream/tree/socket.io to see how it includes those libraries.

**Comment by bfjfm2** [comment]
I will try but am not that expert. Is there is any way to export library as a framework?. So that I can include this project instead of source code.

**Comment by bfjfm2** [comment]
This how we do for Parse-SDK-iOS-OSX https://github.com/parse-community/Parse-SDK-iOS-OSX

Compiling for yourself

If you want to manually compile the SDK, clone it locally, and run the following commands in the root directory of the repository:

 # To pull in extra dependencies (Bolts and OCMock)
 git submodule update --init --recursive

 # To install all the gems
 bundle install

 # Build & Package the Frameworks
 rake package:frameworks
Compiled frameworks will be in 2 archives: Parse-iOS.zip and Parse-OSX.zip inside the build/release folder, and you can link them as you'd please.

**Comment by bfjfm2** [comment]
My friend helped me to move socket.io source code from pod to an swift project(without pod). From there I managed to import inside my objective-c project.

[socketIos.zip](https://github.com/socketio/socket.io-client-swift/files/1236136/socketIos.zip)
