### ISSUE TITLE
allowing SocketIOClient.status getter to be used from Objective-C in the Swift4 branch

### ISSUE THREAD

**Issue by fernandomorgan** [socketio/socket.io-client-swift#769]
Hi, will it be possible to add a @objc to 
public private(set) var status = SocketIOClientStatus.notConnected

in  SocketIOClient.swift?

I think that without this change, xcode9/swift4 with this branch will break the old behavior.
Thank you

**Comment by nuclearace** [comment]
Thanks, should be fixed.

**Comment by fernandomorgan** [comment]
👍 thank you!
