### ISSUE TITLE
Reconnecting on disconnect causes "Session ID unknown" error in v9.0+

### ISSUE THREAD

**Issue by thully** [socketio/socket.io-client-swift#770]
In our application, I have a handler that reconnects on disconnect:

socket.on("disconnect") { args, ack in
          self.socket.connect()
}

Since Socket.io-swift 9.0 (and later versions), I have been getting a "Session ID unknown" error when doing this reconnect. It eventually reconnects, but not after showing this error several times.

**Comment by nuclearace** [comment]
Reusing a socket has never been quite kosher for this library. Your best bet is to create a new socket after one disconnects.

**Comment by thully** [comment]
I am noticing this error on pre-9.0 versions as well, just not as often. The annoying thing is having to recreate the socket and re-add all the socket listeners - and my app has multiple components that use the same socket. Is there a way to get all the currently-registered listeners so that I can readd them to the new socket?

**Comment by kinza88** [comment]
@thully hey did you find any solution to your problem?
