### ISSUE TITLE
Xcode 9, swift 3.2 using SocketIoClient generates build errors

### ISSUE THREAD

**Issue by rainerstandke** [socketio/socket.io-client-swift#771]
Can't build using SocketClient in a swift 3.2 class in Xcode 9 beta. The first import statement gets 'Unknown type named import', as well as 'Expected ';' after top-level declarator'.

This is in a project was started in Obj-C, but already has a few Swift files.

Using SocketClient in an Objective-C file is fine.

Are there any work-arounds? Thanks!

**Comment by nuclearace** [comment]
No idea. I don't support Xcode betas officially until it releases. There's usually branches for new Swift versions (like the Swift 4 branch.) But including them in a project isn't supported.
