### ISSUE TITLE
no longer building, working

### ISSUE THREAD

**Issue by Nathan187** [socketio/socket.io-client-swift#772]
getting these errors all of a sudden when i try to build.  any help would be appreciated

..withheld/Carthage/Checkouts/Starscream/zlib/module.modulemap:1:8: error: redefinition of module 'CZLib'
module CZLib [system] {
       ^
..withheld/Carthage/Checkouts/socket.io-client-swift/Source/Starscream/zlib/module.modulemap:1:8: note: previously defined here
module CZLib [system] {
       ^
..withheld/Carthage/Checkouts/Starscream/zlib/module.modulemap:6:8: error: redefinition of module 'CommonCrypto'
module CommonCrypto [system] {
       ^
..withheld/Carthage/Checkouts/socket.io-client-swift/Source/Starscream/zlib/module.modulemap:6:8: note: previously defined here
module CommonCrypto [system] {

**Comment by nuclearace** [comment]
Most likely related to https://github.com/socketio/socket.io-client-swift/issues/754, which is waiting on upstream changes.

**Comment by nboyd-sportdx** [comment]
why is this closed?  problem persists...

**Comment by nuclearace** [comment]
Duplicate.

**Comment by nuclearace** [comment]
Also see if 11.1.0 with Starscream 8.0.3 fixes things.

**Comment by nboyd-sportdx** [comment]
tried it...not working

**Comment by nuclearace** [comment]
Actually, I wonder if this is related to the submodule this library is using. I'll reopen and take a closer look at Carthage.

**Comment by nuclearace** [comment]
Will fix #754 in.
