### ISSUE TITLE
I'm receiving my own messages

### ISSUE THREAD

**Issue by miktav** [socketio/socket.io-client-swift#775]
When my app emits a message, that message is being received on the same device. How can I emit a message that goes to all other devices, but not the same device that emitted it?

I set up my receiver like this:

        socket?.on("chat message") { [weak self] data, ack in
            NSLog("ChatManager: chat message received")
            if let text = data[0] as? String {
                // text contains the message I sent!
            }
        }

I emit like this:

        socket.emit("chat message", text)
        NSLog("ChatManager: chat message sent")

Is there some way when I receive a message that I can tell if it was sent from the current device? What am I missing? Thanks!

**Comment by nuclearace** [comment]
There's not really a way to solve this on the client side unless you send something in the payload that could be used to tell it was sent from that device. Otherwise you'll have to change the server so that it doesn't emit to the sending device.
