### ISSUE TITLE
[swift4] manually importing SocketIO 

### ISSUE THREAD

**Issue by d-theo** [socketio/socket.io-client-swift#785]
Hi, 

Before v11 I was used to update your library by drag&dropping the **Source/** files. It seems that it's not the case anymore with the `StarscreamSocketIO` dependency. Is there any way for me to continue to import the lib manually ? I can't really rely on Cocoapods as I have to provide an already compiled .framework

I tried to drag&drop ***.swift** files from `StarscreamSocketIO` but I still get a `No Such Module 'StarscreamSocketIO'`

**Comment by nuclearace** [comment]
This is no longer supported since it will require some fiddling and changing code around.

**Comment by DanteCY** [comment]
I have the same error,not now I'm reslove it.
1.downlod Starscream-master project
2.unzip and copy the contents  copy it to socket.io-client-swift-master/Source/Starscream/
3.replace import StarscreamSocketIO with import Starscream
ok
