### ISSUE TITLE
 Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by chirag225** [socketio/socket.io-client-swift#786]
pod 'Socket.IO-Client-Swift', '~> 11.1.0'     Xcode 8.3.3

1 ) Could not build module 'SocketIO'
2 ) Property with 'retain (or strong)' attribute must be of object type for @property (nonatomic, strong) dispatch_queue_t _Nonnull handleQueue;

**Comment by nuclearace** [comment]
Duplicate of #715
