### ISSUE TITLE
Socket.establishConnection() is not consistent when using connectParams with JWT

### ISSUE THREAD

**Issue by kacak9229** [socketio/socket.io-client-swift#788]
I'm using https://github.com/auth0/socketio-jwt to connect user to my node.js server and I'm using one round trip

My problem right now is that whenever user logs in on the IOS part, the `socket.establishConnection()` is not consistent, my theory is that the token is not yet ready even before the `socket.establishConnection()` gets invoked. 

I'm using Singleton design for my Socket.io class as many people pointed that out.

Here's the code on the `SocketManager.swift` part

```
import SocketIO

class SocketIOManager: NSObject {
    
    static let sharedInstance = SocketIOManager()
    var socket = SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .connectParams(["token": getToken()])]) // getToken() I got it from other file which is Constant.Swift

    func establishConnection() {
        socket.connect()
    }
    
    func closeConnection() {
        socket.disconnect()
    }
 
    
    
}


```
I'm using KeychainAccess to store the token and Constant.Swift file store all the global variables and functions so that I could call it on any Swift files.

`Constant.Swift`

```
import Foundation
import KeychainAccess

let keychain = Keychain(server: "www.example.com", protocolType: .https)

func getToken() -> String {
    if let token = keychain["token"] {
        return token
    }
    return ""
}
```

`LoginViewController.swift`

```
 @IBAction func facebookButtonClicked(_ sender: UIButton) {
       Alamofire.request("/login", method: .post, parameters: parameters, encoding: JSONEncoding.default)
            .responseJSON { response in
                if let value = response.result.value {
                    let json = JSON(value)
                   
                    self.keychain["token"] = String(describing: json["token"])
                    SocketIOManager.sharedInstance.establishConnection() 
                    self.segueToAnotherVC() // Segue to another screen, to simplify things i put it in a function
                }
        }


}
```

What should I do to make the connection consistent all the time, whenever user logs in?

**Comment by nuclearace** [comment]
Make sure that your token is set when calling establish connection, if not, don't try and connect.

**Comment by kacak9229** [comment]
What sort of method do you think I should implement to ensure that my token is set beforehand?
My current method is the best that I could come up with. Store it in a keychain then only do socket.connect.

Thanks
