### ISSUE TITLE
Issue with namespaces

### ISSUE THREAD

**Issue by amitarcher** [socketio/socket.io-client-swift#79]
Hi,

I tried this library with demo tictacio game  but its seems it has error while connecting with namespaces.
On debugging you are appending 0/ in namespaces as  "0/namesapce" I dont know why. can you help me to connect with namespaces

**Comment by nuclearace** [comment]
How are you creating the client?

**Comment by amitarcher** [comment]
Thanks it working but it's facing issue with 0.9.16 seems we need to upgrade socket.io.
Just one more thing
was getting error at line 224 socketengine.swift
 let req = NSMutableURLRequest(URL: NSURL(string: self.urlPolling! + "&sid=\(self.sid)&b64=1")!)

after replacing this with 
var __url = urlPolling + "&b64=1" as NSString;
        var urlStr : NSString = __url.stringByAddingPercentEscapesUsingEncoding(NSUTF8StringEncoding)!
        var polUrl : NSURL = NSURL(string: urlStr as String)!
        
        
        let reqPolling = NSMutableURLRequest(URL: polUrl)

its doing good thanks man

**Comment by nuclearace** [comment]
The client is expecting socket.io 1.0+

**Comment by nuclearace** [comment]
Should probably be escaping the url though

**Comment by nuclearace** [comment]
What does your url look like?
