### ISSUE TITLE
strange results in xcode when using this library

### ISSUE THREAD

**Issue by Nathan187** [socketio/socket.io-client-swift#790]
before i started using this library, it was compiling well and working well. when i integrated this library/framework...it was working well as well. then all of a sudden, i started to get this really weird and cryptic error:

:0: error: merge-module command failed with exit code 1 (use -v to see invocation)
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

it was like this for days. so i cleaned the derived folder, build folder, etc. tried to compile, no dice. i started to comment out the relevant code related to socket.io. then it compiled. then when i removed the comment text ('//'), it would again compile. however when i close xcode and then come back to work on the project, i have to do this work around all over again....wth???

probably not related to the socket.io library. just am up in arms with this problem.

**Comment by nuclearace** [comment]
Are you using Carthage? Because this sounds like #754

**Comment by Nathan187** [comment]
yes, i am using Carthage

github "nuclearace/Starscream" ~> 8.0.4
github "socketio/socket.io-client-swift" "development"

is working for me

**Comment by nuclearace** [comment]
Should be fixed in 11.1.2
