### ISSUE TITLE
Redefinition of module 'SSCZLib' e 'SSCommonCrypto'

### ISSUE THREAD

**Issue by freedoom1984** [socketio/socket.io-client-swift#791]
I add the socket.io with cartfile:

github "nuclearace/Starscream" ~> 8.0.4
github "socketio/socket.io-client-swift" ~> 11.1.1

When I add the static library and try the import I look this build error:
Redefinition of module 'SSCZLib'
Redefinition of module 'SSCommonCrypto'

Thanks

**Comment by nuclearace** [comment]
Duplicate of #754. If you add `github "socketio/socket.io-client-swift" "development"` Does it fix it? If yes I'll make a new release today.
