### ISSUE TITLE
Issue of OC importing a swift library by cocoapods.

### ISSUE THREAD

**Issue by TimorDjd** [socketio/socket.io-client-swift#793]
I've an OC project.When i import the 'socket.io-client-swift' library by cocoapods.I should write 'use_frameworks!' into my Podfile,and run pod install,it's successful.But I found that it can't find some library imported by cocoapods which before pod install 'socket.io-client-swift' library.It can't find .h file.But .h file truly exist.So how can i deal with it.

**Comment by nuclearace** [comment]
Are you using the workspace that cocoapods makes?

**Comment by TimorDjd** [comment]
Yes,I used workspace that cocoapods makes;

**Comment by nhnam** [comment]
It has been changed to #import <SocketIO/SocketIO-Swift.h>

**Comment by MD04-TanTan** [comment]
Could you tell me import socket.io-client-swift lib to objective c project? I installed it from cocoapods success but then xcode not complie
