### ISSUE TITLE
Conflicting zlib / CommonCrypto usages

### ISSUE THREAD

**Issue by hansemannn** [socketio/socket.io-client-swift#795]
Hey there,

I noticed that the modulemap delivered with the Cocoapods version of the library does not prefix the zlib and CommonCrypto library, causing redefinition-errors (at least in Xcode 9 which I am testing with) It can be resolved by prefixing it and replace the references, but as the Starscream library already fixed this by renaming it to `SSSCZLib` and `SSSCommonCrypto`, it might be worth updating to the latest library or resolve it here manually. Let me know if I should push a PR for it, thanks!

**Comment by nuclearace** [comment]
What version are you using? All the self collisions should be avoided. However, if you're trying to use Starscream AND this library in the same project you're going to have an issue. You'll have to use the fork that this library uses.

**Comment by hansemannn** [comment]
Mhh, the only library that uses Starscream as a dependency should be this one, that's why I'm wondering. I am using latest (10.2.0), so I'm not sure how any others are not running into this issue. Thanks for catching up btw!

**Comment by hansemannn** [comment]
What a second, 10.2.0 is oudated (11.2.1 is current). But when not specifying the version or using 11.2.1 in the Podfile, it throws an error:
```
[!] Unable to satisfy the following requirements:

- `Socket.IO-Client-Swift (~> 11.1.2)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Socket.IO-Client-Swift (~> 11.1.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Happening with `pod 'Socket.IO-Client-Swift', '~> 11.1.2'`, using `pod 'Socket.IO-Client-Swift'` autoselects 10.2.1. Thx!

**Comment by nuclearace** [comment]
Try `pod repo update`

**Comment by hansemannn** [comment]
That was a long way..Needed to upgrade CP, do a fresh setup, clean and repo-update. But it seems to grab the correct version now, thank you! :-)
