### ISSUE TITLE
Type of expression is ambiguous...

### ISSUE THREAD

**Issue by daver234** [socketio/socket.io-client-swift#797]
Anyone have a suggestion for how to overcome this issue in SocketEngine.swift? 
<img width="1020" alt="screenshot 2017-09-07 23 25 54" src="https://user-images.githubusercontent.com/5413207/30198722-0247502e-9424-11e7-990a-4f3b1b5052ae.png">

**Comment by nuclearace** [comment]
Are you trying to use the Xcode beta with Swift 4? If so, you have to use the Swift 4 branch.

**Comment by daver234** [comment]
Yep that is the problem.  Thanks.
