### ISSUE TITLE
missing required modules: 'SSCZLib', 'SSCommonCrypto'

### ISSUE THREAD

**Issue by jetricy** [socketio/socket.io-client-swift#798]
socket.io-client-swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: error: missing required modules: 'SSCZLib', 'SSCommonCrypto'
import StarscreamSocketIO

![wx20170910-065907](https://user-images.githubusercontent.com/4427339/30244677-9643d1ee-95f5-11e7-805d-f3bb66e976da.png)

**Comment by jetricy** [comment]
I've fixed it by reference the project  StarstreamSocket, like picture below.
![wx20170910-225556](https://user-images.githubusercontent.com/4427339/30250081-56d7f6b2-967b-11e7-9f80-21fc40f8050c.png)

**Comment by nuclearace** [comment]
How did you install the lib?

**Comment by gunjotSinghMansa** [comment]
I am also getting the same issue. I have installed the library with carthage. What to do?

**Comment by navy-xie** [comment]
In your 'Build Settings' -> 'Swift Compiler  - Search Paths' -> 'Import Paths', add the path of the fold 'zlib', for example, $SRCROOT/$PROJECT_NAME/zlib

**Comment by LeonidKokhnovich** [comment]
I still see the issue on the latest version: 13.1.0
