### ISSUE TITLE
导入框架问题

### ISSUE THREAD

**Issue by JoyGY** [socketio/socket.io-client-swift#799]
您好，我想问一下，上面介绍的是使用框架方法安装的，我的项目中使用的第三方都是手动导入的，我想请问一下，手动安装要怎么弄，我试着把源文件拖到工程中，但是发现并不管用，而且#import SocketIO的时候总是提示报错，我发现下载下来的源文件里面包括另一个框架Starscream.xcodeproj，我后来找到那个框架，自己手动添加进去，但是发现还是有问题，所以我也不知道应该如何手动添加这个框架到我的项目中去，希望知道的朋友帮忙解决一下，谢谢！

**Comment by JoyGY** [comment]
补充一下，我的是swift的项目

**Comment by maweis1981** [comment]
I thought you can use cocoapods or Carthage to manage your depends thirdparty library, that is a good habit.
good luck.

**Comment by nuclearace** [comment]
I don't understand chinese. So not sure what this issue is saying.

**Comment by Kienty** [comment]
I use cocoapods to manage the third party, but the following error appears according to the document
`[!] CocoaPods could not find compatible versions for pod "Socket.IO-Client-Swift":
  In Podfile:
    Socket.IO-Client-Swift (~> 15.2.0)

None of your spec sources contain a spec satisfying the dependency: `Socket.IO-Client-Swift (~> 15.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.`
