### ISSUE TITLE
79 Errors while adding SocketIOClientSwift folder to a new Swift project in Xcode

### ISSUE THREAD

**Issue by sauvikatinnofied** [socketio/socket.io-client-swift#80]
I have just created a new Swift project and added the SocketIOClientSwift folder to my project, getting 79 errors coming from swift files coming from SocketIOClientSwift. I am sure, I am making some mistakes. What is proper way to add them to avoid errors?

![screen shot 2015-05-12 at 3 09 18 pm](https://cloud.githubusercontent.com/assets/5868927/7584205/62be7544-f8b9-11e4-9327-f9e1681e8078.png)

**Comment by nuclearace** [comment]
Use an Xcode version that has swift 1.2. Or use an earlier version of the client.

**Comment by sauvikatinnofied** [comment]
Thank you very much @nuclearace. I just updated my Xcode to v6.3.1.Project built successfully.
