### ISSUE TITLE
Socket emit not working.

### ISSUE THREAD

**Issue by danielsGit** [socketio/socket.io-client-swift#800]
Here is my code.
override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        socket.on("connect") {data, ack in
            print("my socket connected")
            
            var param = [String: Any]()
            param["client_id"] = 33
            
            self.socket.emit("client_connect", param)
            self.socket.emit("get_workers")
        }
        
        socket.on("get_all_workers") { (data, ack) in
            print("Get All Workers")
        }
        
        socket.on(clientEvent: .disconnect) { (data, ack) in
            print("Socket disconnected")
        }
        
        socket.connect()
    }

"My Socket Connected" logged successfully but "Get All Workers" doesn't logged. Socket name and url are correct and working fine in android version. Can you plz help me what is wrong?

**Comment by nuclearace** [comment]
I can't see anything wrong here. Try turning on logging and see if you notice anything

**Comment by danielsGit** [comment]
Well, turning on logging means?
let socket = SocketIOClient(socketURL: URL(string: "http://neeleez.com:8383/client")!, config: [.log(false), .compress])

I need to set the false as true?

**Comment by danielsGit** [comment]
This is my full code.
var socket = SocketIOClient(socketURL: URL(string: "http://206.225.95.239:8383/client")!)
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        socket.on("connect") {data, ack in
            print("my socket connected")
            
            // var param = [String: Any]()
            // param["client_id"] = 33
            
            self.socket.emit("client_connect", ["client_id": 33])
            self.socket.emit("get_workers")
        }
        
        socket.on("get_all_workers") { (data, ack) in
            print("Get All Workers")
        }
        
        socket.on(clientEvent: .disconnect) { (data, ack) in
            print("Socket disconnected")
        }
        
        socket.connect()
    }

it logs "my socket connected" but "Get All Workers" doesn't logged. Any suggestion would be appreciate.

**Comment by nuclearace** [comment]
Yes it should be `.log(true)`.

**Comment by danielsGit** [comment]
No error in my code? Actually server seems ok because android is working fine. I think this issue is coming from iOS client. 
in server console, it doesn't logged me as connected but in iOS client side, "my socket connected" logged.
Any clue from this?

**Comment by nuclearace** [comment]
Maybe something in your `self.socket.emit("client_connect", ["client_id": 33])` emit? If something in that does authentication such that an emit of `get_workers` won't do anything, maybe there's something wrong there.
Another thing is if your url is using a namespace, i.e `http://someurl.com/mynamesapce` in the JS and Android client would be done with the `.nsp(String` option in this client.

**Comment by nuclearace** [comment]
Ah yes, I see in your above comment you're doing something like that. 

```swift
var socket = SocketIOClient(socketURL: URL(string: "http://206.225.95.239:8383/client")!)
```
should actually be
```swift
var socket = SocketIOClient(socketURL: URL(string: "http://206.225.95.239:8383")!, options: [.nsp("/client")])
```
Sorry I missed that before.

**Comment by nuclearace** [comment]
I should probably put something in the FAQ about that.

**Comment by danielsGit** [comment]
Yes it works. Thanks a lot.

**Comment by mahesh-khokhar** [comment]
could you tell me why we need to used nsp with socket URL? I have same issue my socket is working in android well but not working in ios.
