### ISSUE TITLE
HOW TO DETECT WHEN SOCKET LOST CONNECT ANY TIME

### ISSUE THREAD

**Issue by mrrobo1510** [socketio/socket.io-client-swift#802]
Hi nuclearace, i have a problem in at here, i using socketio/socket.io-client-swift install fom cocoapods, your lib is wonderful, but i don't know why socket sometime lost connection socket in a long time but internet still work well.Current I don't know how to detect when lost connect socket and reconnect. Could support for me .Thanks

**Comment by nuclearace** [comment]
If you add a event handler for the `.disconnect` or `.reconnect` client events you should get some indication.

**Comment by mrrobo1510** [comment]
ok. i'll check and contact to you soon if have a problem incurred. thanks for your support

**Comment by mrrobo1510** [comment]
Hi  nuclearace, i was try some event but it not work. I will describe so you can better understand more how our application scenario. I have 2 phone register socket IO also, phone 1 will send data to phone 2 through socket , phone 2 will wait and received data from phone 1. But sometime phone 1 or phone 2 will lost connect socket also, so phone 1 will not send success or phone 2 will not received success. So  i think how to resolve in your lib we will know when  socket lost connection and reconnect , as you say handle event .disconnect or .reconnect  , but it not work.You can check the below code.Please give me any solution about that..Thanks you again!

    **[socketIO on:@"connect_error" callback:^(NSArray * arrdata , SocketAckEmitter * ack) {
        NSLog(@"___________ Socket Manager connect_error");
    }];
    [socketIO on:@"connect_failed" callback:^(NSArray * arrdata , SocketAckEmitter * ack) {
        NSLog(@"___________ Socket Manager connect_failed");
    }];
    [socketIO on:@"disconnect" callback:^(NSArray * arrdata , SocketAckEmitter * ack) {
        NSLog(@"___________ Socket Manager error");        
    }];**
