### ISSUE TITLE
socket has listener like even in ios

### ISSUE THREAD

**Issue by santhoshsk1918** [socketio/socket.io-client-swift#803]
In android there is a function to check if the listener is already attached to the socket. I was checking if there is something with same functionality in ios. 
Not an issue but possible enhancement unable to change open to  enhancement

**Comment by nuclearace** [comment]
Exposing the handlers is something I want to do. The issue is they're defined in a way that wouldn't be exposed to objc. I might be able to think of a workaround though.

**Comment by santhoshsk1918** [comment]
ok Thanks

**Comment by nuclearace** [comment]
@santhoshsk1918 See 91eea96. It opens up a bunch of previously internal things. Including the handlers. The only downside is most of the stuff will be Swift only.
