### ISSUE TITLE
Replicate Transport.EVENT_REQUEST_HEADERS on ios

### ISSUE THREAD

**Issue by SalvatoreAD** [socketio/socket.io-client-swift#804]
I have to insert a header inside the socket connection. Is it possible to replicate android's socket transport control in ios (swift)? 

this is an example

`socket.on(Engine.EVENT_TRANSPORT, new Listener() {
    @Override
    public void call(Object... args) {
        Transport transport = (Transport)args[0];
        transport.on(Transport.EVENT_REQUEST_HEADERS, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                @SuppressWarnings("unchecked")
                Map<String, String> headers = (Map<String, String>)args[0];
                // send cookies to server.
                headers.put("Cookie", "foo=1;");
            }
        }).on(Transport.EVENT_RESPONSE_HEADERS, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                @SuppressWarnings("unchecked")
                Map<String, String> headers = (Map<String, String>) args[0];
                // get cookies from server.
                String cookie = headers.get("Set-Cookie");
            }
        });
    }`

**Comment by nuclearace** [comment]
If it's just inserting you can use the [.cookies](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:FO8SocketIO20SocketIOClientOption7cookiesFMS0_FGSaCSo10HTTPCookie_S0_) or [.extraHeaders](https://nuclearace.github.io/Socket.IO-Client-Swift/Enums/SocketIOClientOption.html#/s:FO8SocketIO20SocketIOClientOption12extraHeadersFMS0_FGVs10DictionarySSSS_S0_) options. 

But currently there's no way to intercept response headers. There's [this](https://github.com/socketio/socket.io-client-swift/issues/307) issue for that, but the demand hasn't been high enough for me to look into it

**Comment by SalvatoreAD** [comment]
i try extraHeaders and cookies, but i receive error

**Comment by nuclearace** [comment]
What error?

**Comment by SalvatoreAD** [comment]
At the first connection I reply with an html page with bad gateway error, but the second connection goes fine.

**Comment by nuclearace** [comment]
What do you mean second connection? Have you turned on logging on the client?

**Comment by SalvatoreAD** [comment]
when I get the first error, I reconnect and it works. in general I have to put the cookie in the socket header. on Android I use the transport. can you help me?Inviato dal mio dispositivo Huawei-------- Messaggio originale --------Oggetto: Re: [socketio/socket.io-client-swift] Replicate Transport.EVENT_REQUEST_HEADERS on ios (#804)Da: Erik Little A: "socketio/socket.io-client-swift" CC: Salvatore AD ,Author What do you mean second connection? Have you turned on logging on the client?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/socketio/socket.io-client-swift","title":"socketio/socket.io-client-swift","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/socketio/socket.io-client-swift"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nuclearace in #804: What do you mean second connection? Have you turned on logging on the client?"}],"action":{"name":"View Issue","url":"https://github.com/socketio/socket.io-client-swift/issues/804#issuecomment-329248725"}}}

**Comment by SalvatoreAD** [comment]
Additionally, when I receive this error, the node server crash

**Comment by nuclearace** [comment]
Why does the node server crash?

**Comment by SalvatoreAD** [comment]
the server crashes because it fails to read the cookie I send. (in req.headers.cookie). how can I place cookies in headers?

**Comment by nuclearace** [comment]
Headers should be added for all polling messages if you use the extraHeaders or cookies options.

https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIO/Engine/SocketEnginePollable.swift#L74

https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIO/Engine/SocketEnginePollable.swift#L101

And on the initial connection and for the initial WebSockets connection

https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIO/Engine/SocketEngine.swift#L275

https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIO/Engine/SocketEngine.swift#L330

**Comment by SalvatoreAD** [comment]
Ok thank you so much. I did the tests and the cookie arrived correctly. so there was a server side issue.
