### ISSUE TITLE
emergency！ Ios data drop package

### ISSUE THREAD

**Issue by JoyGY** [socketio/socket.io-client-swift#807]
经过测试对比安卓的数据，ios这边接收到的数据要比安卓的少，数据获取不全，不知道有没遇到类似的问题？请问是怎么解决的，谢谢！

After testing the data of android, the data received on ios is less than that of android, and the data is not fully obtained. Do you know that there are no similar problems? How do you solve this? Thank you!

我觉得可能是因为需要接收的数据量太大了，所以在 .on(<#T##event: String##String#>, callback: <#T##NormalCallback##NormalCallback##([Any], SocketAckEmitter) -> ()#>) 这个方法中没办法获取到服务器返回的数据，但是通过Log输出的数据中却可以得到该数据，我在想是不是因为数据量太大，您那边做了什么处理？还是说我需要对大数据的返回数据做什么处理才可以解决这个问题，因为现在项目正在使用这个框架，所以比较着急，希望您看到这个问题帮忙解决一下，谢谢！
I think this may be because of receiving the amount of data is too large, so in this way  .on(<#T##event: String##String#>, callback: <#T##NormalCallback##NormalCallback##([Any], SocketAckEmitter) -> ()#>)  , no way to get the data back to the server, but through the Log output data can get the data, I think it is not because the amount of data is too large, you are there to do what treatment? Or that I need to return the data of big data processing do what can solve this problem, because the project is now using this framework, so anxious, I hope you see this issue to help solve it, thank you!

**Comment by nuclearace** [comment]
I have never tested with large data sets? What sizes are we talking about?

**Comment by JoyGY** [comment]
I'm not sure how big the data is, but what I'm sure is that the amount of data that we need to transmit is going to be very large. I later found that when the socket transfers data, if the amount of data is large, it will be subcontracted, but I don't know if I should set something up for receiving big data. My socket is set like this

我也不确定具体多大的数据，但是我可以确定的是我们需要传输的数据量会非常大。我后来查到socket传输数据的时候，如果数据量很大的话会分包，但是我不知道对于接收大数据的时候我是不是应该设置一些什么？我的socket是这样设置的

```objc
let socket = SocketIOClient(socketURL: URL(string: "http://115.160.142.248:8080")!, config: [.log(true), .compress])
```
If I need to receive big data, how should I set my socket? I hope you can teach me, thank you!
如果我需要接收大量的数据的话，我应该怎么设置socket，希望您可以指导一下，谢谢！

**Comment by nuclearace** [comment]
@JoyGY is this the same issue as #806? If so can we track everything there?

**Comment by JoyGY** [comment]
Yes,you can.I'm sorry, is my fault, the two problems are the same, is my description is a little problem, I'm sorry
