### ISSUE TITLE
Export Compliance for Security Frameworks in package.

### ISSUE THREAD

**Issue by murphman300** [socketio/socket.io-client-swift#808]
Hello,
Currently building out a solution with Socket/io and Starscream. Since the first uses the later now, and since you guys have created your new SSCommonCrypto, based on CommonCrypto, I'm left with one question before moving forward with developing with Socket.io. 

I've looked through your pod files, but i cannot find anybit of encryption-related code with does not use Apple provided encryption/decryption libraries or methods. Can you confirm this? As your answer will affect a developer's Export Compliance workload as I'm sure you are already aware of.

My use case is for financial information networking, so this is more than an important answer! 

Cheers and thank you for all the work you do!

**Comment by nuclearace** [comment]
Currently this is correct. All encryption stuff is provided by Apple. I'm about to start work on using two different WebSocket clients which will allow using this lib on Linux. But that shouldn't affect you as long as this is being used on Apple platforms.
