### ISSUE TITLE
server: how to send ack to client

### ISSUE THREAD

**Issue by obsobsobs** [socketio/socket.io-client-swift#81]
the client: 
socket.emitWithAck("canUpdate", cur)(timeout: 0) {data in
            socket.emit("update", ["amount": cur + 2.50])
}

but i don't know how to send the ack from server to client...

**Comment by nuclearace** [comment]
```javascript
socket.on("canUpdate", function(amount, ack) {
    ack(true)
})
```

**Comment by obsobsobs** [comment]
Thank you
