### ISSUE TITLE
no such module 'StarscreamSocketIO'

### ISSUE THREAD

**Issue by TaoTingXing** [socketio/socket.io-client-swift#811]
This error occurred when I was integrated into my project，no such module 'StarscreamSocketIO'，i can't fine this class in your project，why？

**Comment by nuclearace** [comment]
Are you trying to use this in Swift 4?

**Comment by deepakraj27** [comment]
yes same error for me. I'm using swift4

**Comment by pkuhonker** [comment]
same error for me. I'm using swift4

**Comment by pkuhonker** [comment]
@deepakraj27 maybe you should update your pod by 'pod repo update'

**Comment by nuclearace** [comment]
How are y'all install the lib?

**Comment by nuclearace** [comment]
I just tried CocoaPods and everything worked for me.
