### ISSUE TITLE
swift 4 not work

### ISSUE THREAD

**Issue by duckscorpion13** [socketio/socket.io-client-swift#812]
private func handleBase64(message: String) {
        // binary in base64 string
        let noPrefix = message[message.index(message.startIndex, offsetBy: 2)..<message.endIndex]

        if let data = Data(base64Encoded: noPrefix, options:  .ignoreUnknownCharacters) {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Type of expression is ambiguous without more context

            client?.parseEngineBinaryData(data)
        }
    }

**Comment by nuclearace** [comment]
Swift 4 will be supported in v12.

**Comment by udayBabariya** [comment]
> f let data: Data = Data(base64Encoded: **String(noPrefix)**, options: .ignoreUnknownCharacters){
> ...
> ...
> }
