### ISSUE TITLE
Ambiguous without more context

### ISSUE THREAD

**Issue by RichAppz** [socketio/socket.io-client-swift#813]
Guys, we are trying to get a build up and running with Swift 4 and this is the last pod which is just not compiling, can you have a look at the issue, Thanks

`SocketEngine.swift` file 228
![screen shot 2017-09-20 at 11 26 54](https://user-images.githubusercontent.com/2961823/30639498-116f2004-9df7-11e7-81bf-7a9231c4596d.png)

**Comment by nuclearace** [comment]
Swift 4 will be supported in v12.0.0.

**Comment by RichAppz** [comment]
Do you know when this will be available? This is the last error to be completed

**Comment by nuclearace** [comment]
Should be out now.
