### ISSUE TITLE
Error in the SocketEngine.swift class

### ISSUE THREAD

**Issue by olgadanylova** [socketio/socket.io-client-swift#814]
Hello! I've just updated to Socket.IO-Client-Swift v12.0.0 and the error occurs in the SocketEngine.swift class: 

> Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?

That's line 228:
`if let data = Data(base64Encoded: noPrefix, options: .ignoreUnknownCharacters) {`
probably it should be 
`if let data = Data(base64Encoded: noPrefix!, options: .ignoreUnknownCharacters) {`

Also, I'd like to know when the release with Swift 4 support will be available?
There are warnings which report that some methods are deprecated and some parameters are not found in the function declaration.

Thank you,
Regards, Olga

**Comment by nuclearace** [comment]
v12.0.0 is for Swift 4.0. What Xcode version was this with? I got no errors testing this on Xcode 9 and Swift 4.

**Comment by olgadanylova** [comment]
Thanks for the quick response!
Xcode 9 + Objective-C
https://goo.gl/zD21pq

**Comment by olgadanylova** [comment]
This project was firstly written in Xcode 8, then I updated it to the recommended settings in Xcode 9.

**Comment by nuclearace** [comment]
I think those warnings are because of documentation stuff. The documentation is written for the Swift client's api, so it won't always match up with the Objective-C translation.

**Comment by nuclearace** [comment]
Yeah, I'm not getting any errors building and running the tests on Xcode 9. Is something overriding a SWIFT_VERSION setting?

**Comment by akpatrick** [comment]
Hello! unfortunately im getting the same error
i just updated to xcode 9 and v12.0.0

Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
in SocketEngine.swift line 28

**Comment by olgadanylova** [comment]
Just checked my Swift project (it is the same to ObjC project). This error

> Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?

occurred in the Swift project too - I've fixed it.
And there are no more warnings which were in my ObjC project.

Is this the only lib I could use for iOS? 
Is there any lib for ObjC?
What lib can I use for mac os?

Thank you for your response!

**Comment by nuclearace** [comment]
@olgadanylova I'm not aware of any other libs; I haven't looked in ages. This lib should work in ObjC on all Apple platforms except Watch.

I still think something is setting a SWIFT_VERSION to something lower than 4.0. that "Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?" was for an old version of Swift where the string init returned an optional; it shouldn't in Swift 4.0.

**Comment by olgadanylova** [comment]
OK, I'll check. Anyway I've got all the answers I needed - thanks once more!

**Comment by nuclearace** [comment]
<img width="676" alt="screen shot 2017-09-20 at 11 16 29 am" src="https://user-images.githubusercontent.com/1211049/30652002-32dce8a4-9df5-11e7-9600-ec3351714db9.png">

**Comment by akpatrick** [comment]
thanks that fixed it, it was set to Swift 3.x

**Comment by thonydam** [comment]
I set the swift compiler version for specific pods via the Podfile:

```
swift4 = ['Socket.IO-Client-Swift']

post_install do |installer|
  installer.pods_project.targets.each do |target|

    swift_version = '3.2'

    if swift4.include?(target.name)
      swift_version = '4.0'
    end

    if swift_version
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end
```
