### ISSUE TITLE
Some Errors With Definition

### ISSUE THREAD

**Issue by xManson** [socketio/socket.io-client-swift#815]
Hello!
Thanks for watching my question 
I use xcode 9.0  , pod version 1.3.1

When i do
   ` pod 'Socket.IO-Client-Swift', '~> 12.0.0' # Or latest version`
and then "pod update" 
 Terminal said -` None of your spec sources contain a spec satisfying the dependency: `Socket.IO-Client-Swift (~> 12.0.0)`.`

If I do just    `pod 'Socket.IO-Client-Swift' `- it connects with 8.3.0

Thanks for update!

**Comment by nuclearace** [comment]
Be sure to do `pod repo update` before doing pod update. It no longer does this automatically.
