### ISSUE TITLE
handleBase64 in SocketEngine -> Optional noPrefix not unwrapped

### ISSUE THREAD

**Issue by rajeevwhiz** [socketio/socket.io-client-swift#817]
Error: Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?

Line 228
```
private func handleBase64(message: String) {
        // binary in base64 string
        let noPrefix = String(message[message.index(message.startIndex, offsetBy: 2)..<message.endIndex])

        if let data = Data(base64Encoded: noPrefix, options: .ignoreUnknownCharacters) {
            client?.parseEngineBinaryData(data)
        }
}
```
noPrefix needs to be noPrefix!

**Comment by nuclearace** [comment]
Are you trying to use this in Swift 3.x? The latest version is for Swift 4.

**Comment by rajeevwhiz** [comment]
Using latest from master - it was also there on Swift4 branch earlier

**Comment by Vuong-Dao** [comment]
got same problem, any update?

**Comment by aligermiyanoglu** [comment]
You can solve the issue by changing "Swift Language Version" to 4.0 under Build Settings of pod project of 'Socket.IO-Client-Swift' framework

**Comment by nuclearace** [comment]
As @aligermiyanoglu says, this is a sign that something is setting the SWIFT_VERSION to 3.x. The latest version needs it set to 4.0.
