### ISSUE TITLE
WebSocket doesn't connect through proxy

### ISSUE THREAD

**Issue by QaiserAbbas** [socketio/socket.io-client-swift#819]
Hi to the socket.io community,
I am not able to connect my client via proxy server?
is there any possible solution ?

Regards

**Comment by nuclearace** [comment]
See https://github.com/daltoniam/Starscream/pull/202. I think it's been abandoned, but if this is ever merged then it'll start working.

**Comment by QaiserAbbas** [comment]
so we do not have any option to bypass proxy ?

**Comment by nuclearace** [comment]
Connect directly to the server? I'm not entirely sure.
