### ISSUE TITLE
passport support

### ISSUE THREAD

**Issue by hohl** [socketio/socket.io-client-swift#82]
Any chance to get this working with passport support? https://github.com/jfromaniello/passport.socketio

**Comment by cdagli** [comment]
Hello Hohl, it works with passport.socketio already. I am using it on the server side.

**Comment by nuclearace** [comment]
You can send cookies during the handshake using the "cookies" options.

**Comment by hohl** [comment]
@nuclearace Thank you. I'll give it a try.
