### ISSUE TITLE
Unresolved identifier 'SocketIOClient' Swift 4

### ISSUE THREAD

**Issue by Caspert** [socketio/socket.io-client-swift#820]
I trying to setup a Socket IO app with Swift, but ran into the following issue: Unresolved identifier 'SocketIOClient'. 

I installed the library using Cocoapods successfully and is added correctly to my project file. 
When I try to call: var socket:` SocketIOClient = SocketIOClient(socketURL: NSURL(string: "http://192.168.1.XXX:3000")!) ` I receive above error.

I doesn't use import `SocketIO` because when I add it to my Swift file, I receive the following alert: `File 'SocketIOManager.swift' is part of module 'SocketIO'; ignoring import`

Also I tried to create a whole new project, but with no result. On the web I couldn't find an answer for my problem, hope you can help me.

Thanks.
Casper

**Comment by nuclearace** [comment]
Well, you have to import the framework, that's why you're getting an unresolved identifier error.

**Comment by Caspert** [comment]
Thanks for the response. Which framework do you point at? The import SocketIO inside my ViewController.swift or an other library?

**Comment by nuclearace** [comment]
You should do `import SocketIO` in any file you need to access stuff defined in this library.

**Comment by Caspert** [comment]
I've already try that, but than I receive the following hint: `File 'SocketIOManager.swift' is part of module 'SocketIO'; ignoring import` When I try then typing SocketIOClient, auto-completion doesn't fill it out and still get above message.. 
<img width="839" alt="schermafbeelding 2017-09-28 om 16 04 54" src="https://user-images.githubusercontent.com/2439859/30970933-cea61ab8-a466-11e7-832e-3a222cc89881.png">

**Comment by nuclearace** [comment]
I've never seen that kind of error before. Are you trying to include this libraries source files in your targets or something? Are you using the workspace that CocoaPods creates for you?

**Comment by Caspert** [comment]
I just added the pod via the pod file. Than open the newly created workspace, that white paper one..

**Comment by nuclearace** [comment]
I think this is telling you that you've added this file to the SocketIO target, which is meaningless.

**Comment by Caspert** [comment]
Okay, how should I do it correctly?

**Comment by Caspert** [comment]
I just recreate the project one time and is working now. Thanks for your input and help!

**Comment by axita27** [comment]
I facing same issue..how can i solve this type issue without recreate project
