### ISSUE TITLE
Can’t get real chinese string

### ISSUE THREAD

**Issue by jonjes468250** [socketio/socket.io-client-swift#821]
i can’t get real chinese string with ver10.0.1 (ver8.3.3 can)
but use ver 8.3.3 sometime get same event 
(ex: i get one event is return string, but run twice,and so get two same string)
and i can install ver 11 or 12 (cocoa pods ver 1.1.1 Xcode ver8.2)

**Comment by nuclearace** [comment]
What version is the server? Versions past 9.0 contain a breaking unicode change that only support socket.io 2.0+.
