### ISSUE TITLE
No available version for github "nuclearace/Starscream" satisfies the requirement

### ISSUE THREAD

**Issue by nboyd-sportdx** [socketio/socket.io-client-swift#823]
anyone else having this issue?

No available version for github "nuclearace/Starscream" satisfies the requirement: ~> 8.0.4

i'm using xcode 9 and trying to get a project to work/compile

**Comment by premveer** [comment]
No such module 'Starscream' appearing for me

**Comment by nuclearace** [comment]
Shouldn't be relevant for the latest version, since it doesn't use my custom Starscream anymore.

**Comment by Nathan187** [comment]
sorry about that.  was able to get my project working
