### ISSUE TITLE
Unable to build with SPM

### ISSUE THREAD

**Issue by IrfanMarwat** [socketio/socket.io-client-swift#827]
import PackageDescription

let package = Package(
	name: "spmtest",
	targets: [],
	dependencies: [
		.Package(url: "https://github.com/socketio/socket.io-client-swift", .upToNextMajor(from: "12.0.0")),
	]
)

error: type 'Package.Dependency' has no member 'package'
                .package(url: "https://github.com/socketio/socket.io-client-swift", .upToNextMajor(from: "12.0.0")),

If I change p to P, then this error go, Another error appear:

error: type 'Version' has no member 'upToNextMajor'
    .Package(url: "https://github.com/socketio/socket.io-client-swift", .upToNextMajor(from: "12.0.0")),

Please have a look, why my SPM is not building it. Thanks

**Comment by nuclearace** [comment]
Please make sure that you have Swift 4.0 installed. You can check by doing `swift --version`

**Comment by IrfanMarwat** [comment]
Thanks for reply. My swift version: Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37).

**Comment by nuclearace** [comment]
Oh, make sure you add // swift-tools-version:4.0 to the top of your package file.

**Comment by nuclearace** [comment]
Did that fix the issue?

**Comment by IrfanMarwat** [comment]
No It did'nt. I was trying this in a simple perfect template project. I
also try with the sample for spm. But no luck.

**Comment by nuclearace** [comment]
My test project builds fine and the travis build is fine, so I'm not sure.

**Comment by alionthego** [comment]
I am using Swift 4.0 Xcode 9 and trying to install SocketIO for use in my chat application for iOS devices.

I tried installing using the Swift Package Manager but the Library is not recognized.  The following is my Package.swift file:

```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "MyApp",
    dependencies: [

        .package(url: "https://github.com/socketio/socket.io-client-swift", .upToNextMajor(from: "12.0.0"))
    ]
)
```
On command line when I type 'swift build' the packages are fetched but there is an error:

"warning: no targets to build in package"

When I try to import SocketIO in my app I get:

"No such module 'SocketIO'" error.

Swift 4.0 is installed.

**Comment by nuclearace** [comment]
So I guess I need to update the readme a bit better, it only shows adding the dependency, not what a _fully_ correct Package.swift would look like.

This is a full SPM package file that uses the lib.

https://github.com/nuclearace/socket.io-client-testing/blob/master/Package.swift

**Comment by alionthego** [comment]
Sorry, I'm very new to SocketIO and Project Manager.  What is "Runner" referring to in your Package.swift file from the link above?  "socket.io-test" is your project name.

**Comment by nuclearace** [comment]
It's just some made up name for the target.

**Comment by hyperlink** [comment]
I got the same error when I included socketIO as a dependency for my package. It was fixed by using `.product`. I think the problem is dependency is resolved by the name of the repo and the error is caused by the git URL path being `socket.io-client-swift` instead of `SocketIO`.

```swift
// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "TestPackage",
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "TestPackage",
            targets: ["TestPackage"]),
    ],
    dependencies: [
        .package(url: "https://github.com/socketio/socket.io-client-swift", .upToNextMajor(from: "16.1.0")),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "TestPackage",
            dependencies: [
                .product(name: "SocketIO", package: "socket.io-client-swift")
            ]
        ),
        .testTarget(
            name: "TestPackageTests",
            dependencies: ["TestPackage"]),
    ]
)
```
