### ISSUE TITLE
Error in 12.1.0

### ISSUE THREAD

**Issue by alvincrisuy** [socketio/socket.io-client-swift#828]
<img width="970" alt="screen shot 2017-10-03 at 2 50 45 pm" src="https://user-images.githubusercontent.com/7260700/31113144-6113e1c8-a84a-11e7-8bbf-e162b5d03791.png">

**Comment by nuclearace** [comment]
Something is setting the Swift version to 3.2. I don't think CocoaPods correctly updates the Swift Version in its Pods targets. It should be Swift 4.0.
