### ISSUE TITLE
xcode 9 optional 

### ISSUE THREAD

**Issue by kjoe07** [socketio/socket.io-client-swift#831]
xcode 9 complains about this in socketEngine.swift line 228
if let data = Data(base64Encoded: noPrefix, options: .ignoreUnknownCharacters) {
            client?.parseEngineBinaryData(data)
        }
idicating noPrefix shouldbe noPrefix! unwrapped optional...

**Comment by nuclearace** [comment]
Something is setting your Swift Version to 3.2. Check all your targets and any pod targets.

**Comment by nuclearace** [comment]
From what I've seen CocoaPods doesn't automatically fix the SWIFT_VERSION for the pod target.

**Comment by kjoe07** [comment]
perhas i have to make a converstion to swift 4 ill try an say

**Comment by kjoe07** [comment]
true the project was using swift 3.2
