### ISSUE TITLE
Can't send byte array in swift 3

### ISSUE THREAD

**Issue by aryaei** [socketio/socket.io-client-swift#836]
I have been porting my java code to swift but there is this problem i have encountered with array of bytes. there is this socket event that array of picture data is sent to server and then server does some changes on it and save it as a file on server. following are the server and java client code:
Java Code:
```
File file = new File(changeProfileImageEvent.path);
byte[] data = new byte[(int) file.length()];
new FileInputStream(file).read(data);
socket.emit("changeProfileImage", data, new Ack() {
	@Override
	public void call(Object... args) {
		eventBus.post(new ChangeProfileImageResultEvent((int) args[0], args[1].toString()));
	}
});
```

Server Code:
```
let fd = await fs.openAsync(realPath, 'a', 0o755);
await fs.writeAsync(fd, newBuffer, 'binary');
await fs.closeAsync(fd);
```

But when i'm trying equivalent functions in swift server throws an expected 'buffer' error. here is my swift code to turn an image into a [Int8] and send it to sever:
```
let data = UIImageJPEGRepresentation(ANUIImage(), 0.1)
let intArray = Array(data!).map { Int8(bitPattern: $0) }
socket.emitWithAck("changeProfileImage", imageData).timingOut(after: 15) { data in
	//Do the rest
}
```
PS: I have tried with [UInt8] too by commenting second line too, it didn't work either.

**Comment by nuclearace** [comment]
You have to send binary data as Data objects, not arrays.

**Comment by aryaei** [comment]
Got it, thanks :)
