### ISSUE TITLE
Joining multiple namespaces on a single client.

### ISSUE THREAD

**Issue by alihen** [socketio/socket.io-client-swift#837]
Our application communicates on multiple namespaces. I'm looking to join multiple namespaces and emit events to the correct namespace.

### 1st approach:
Connect to **all** the namespaces after `socket.connect()` - i.e
```
...
self.socket.connect()
self.socket.joinNamespace("/a")
self.socket.joinNamespace("/b")
self.socket.joinNamespace("/c")
...
```
☝️ This hasn't worked for me.

### 2nd Approach:
Connect to the require namespace before emitting an event - i.e
```
func emitEvent(eventName: String, namespace: String) {
	socket.joinNamespace(namespace)
	socket.emit(eventName, with: [:])
	socket.on(eventName, callback: { (data, ack) in
		//handle the data received
	})
}
```

Each time I emit an event, I join the required namespace - is this the correct way to handle multiple namespaces in the iOS socket client?

When using the 2nd approach, I'm getting `LOG SocketParser: Got invalid packet: SocketPacket` for an event that is emitted on a different namespace than other emitted events. According to [SocketParsable.swift](https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIO/Parse/SocketParsable.swift) I would assume that the error is due to not being on the same namespace that I've subsequently joined (we emit multiple events in different namespaces throughout the app)

What is the correct approach to join (and listen) to messages on multiple namespaces?

Client version: `11.1.3`

**Comment by nuclearace** [comment]
Joining multiple namespaces isn't supported. You will need multiple sockets for each namespace.

**Comment by alihen** [comment]
I've taken a stab at this in https://github.com/alihen/socket.io-client-swift/tree/multiple-namespace-support

We're currently using `v11.1.3` - I'll submit a PR for the current version once we upgrade.

**Comment by nuclearace** [comment]
My only concern is that it will be too different from the reference implementation, but if it works that would be nice. Honestly I haven't looked into the JS version and how it actually does namespaces behind the scenes. I vaguely remember it has a higher abstraction called a manager that this library lacks.

**Comment by nuclearace** [comment]
I need to update the repo, but to develop on the latest version you'll need to do `carthage update`

**Comment by alihen** [comment]
I'll do more reading on how other clients deal with this and try bring a future PR in line with those where possible

**Comment by nuclearace** [comment]
I think adding a manager might be a bit more work, since it might require restructuring the client in a few places. I would have to see how it's implemented before I make a decision if it's a good thing to add now.

**Comment by nuclearace** [comment]
So @alihen, looking at the js client. Each individual client can only connect to a single namespace.  https://github.com/socketio/socket.io-client/blob/master/lib/socket.js#L220. What this library lacks, and what I'm working on adding now is a "Manager" that will allow multiple clients to share a single single Engine. Currently they must all have separate engines.

**Comment by nuclearace** [comment]
Although this is going to be a pretty drastic change to how things work currently... so I'm not sure if it's worth it.

**Comment by nuclearace** [comment]
https://github.com/socketio/socket.io-client-swift/commit/ba5f8ba4d9622fec81112653c74a54ba4f3810b9

**Comment by nuclearace** [comment]
@alihen You can check out #844. It'll be a somewhat radical change in the API that'll require adding a fair bit of documentation so people can update their code for compatibility.

**Comment by dpakthakur** [comment]
Check my answer in #236
