### ISSUE TITLE
Asyncronous send and receive

### ISSUE THREAD

**Issue by kojiba** [socketio/socket.io-client-swift#838]
Looks like sender pipe is locked when socket receives data. DispatchQueue.global.async creates no effect, pls check this, cause I unable to operate with large amounts of data using this client (10-50mb per response)

**Comment by nuclearace** [comment]
That’s very large for websockets and this library. The best you’ll be able to do is set The handle queue to be something else besides the main queue. But sending such large messages frequently is going to be slow.

**Comment by kojiba** [comment]
ok, checked code and its looks like a major fuckup
instead of 
`
    /// The queue that all interaction with the client should occur on. This is the queue that event handlers are
    /// called on.
    @objc
    public var handleQueue = DispatchQueue.global()`

we need to use DispatchQueue.global() to creating always new queue to process responces

**Comment by kojiba** [comment]
imho U need to add a configuration parameter to use always different processing queues

**Comment by nuclearace** [comment]
That wouldn’t be thread safe. There are some stateful things that happen inside the client and it uses GCD and a serial queue to manage thread safety.

**Comment by kojiba** [comment]
ok, but anyway communication library is mustn't be syncronous

**Comment by kojiba** [comment]
changed all to DispatchQueue.global(qos: .background).async
for first tests its works +- fine

**Comment by nuclearace** [comment]
I should update the docs to specify that the handleQueue needs to be serial queue, and maybe make it clearer about what it means. But it isn't fully synchronous. Once emit gets to the engine it becomes async, likewise, once a message gets to the client it gets put on the handleQueue.

**Comment by nuclearace** [comment]
You probably won't see crashes using a concurrent queue unless you're using `acks` or sending binary data. Since those are the two things that use state. Or if you're adding handlers after connect, that might cause a race condition that results in a crash.

**Comment by kojiba** [comment]
double check the apple docs, cause now it seems better(faster working) to create standalone queue for each request/response, so I am not sure that staticQueue.async will work better

I will tune this for myself locally, but keep this in mind c:

**Comment by nuclearace** [comment]
There's a difference between being async and having concurrent processing. I have no desire to add support for concurrent queues at this time, since it means dealing with locks and other such things which are difficult to reason with and manage.
