### ISSUE TITLE
How to build two socket connection

### ISSUE THREAD

**Issue by dk250** [socketio/socket.io-client-swift#839]
I want to build two socket with different namespace., but when I connected one successfully, the other one was failed.  I new two SocketIOClient instance. it did not work.

**Comment by nuclearace** [comment]
Do you have a code example and log output? What does, "it did not work," mean?

**Comment by dk250** [comment]
`
// create socket 1 

SocketIOClient *socket1 = [[SocketIOClient alloc] initWithSocketURL:[[NSURL alloc] initWithString:@"https://test.lqy.com"] config:@{@"log": @YES, @"nsp":@"test1" }];
 [socket1 on:@"connect" callback:^(NSArray * _Nonnull data, SocketAckEmitter * _Nonnull ack) {
        NSLog(@"socket1 connected successfully");
    }];

[socket1 connect];

//create socket 2

SocketIOClient *socket2 = [[SocketIOClient alloc] initWithSocketURL:[[NSURL alloc] initWithString:@"https://test.lqy.com"] config:@{@"log": @YES, @"nsp":@"test2" }];
 [socket2 on:@"connect" callback:^(NSArray * _Nonnull data, SocketAckEmitter * _Nonnull ack) {
        NSLog(@"socket2 connected successfully");
    }];

[socket2 connect];
`
Socket1 can connect successful and log "socket1 connected successfully", but socket2 is failed. no call back.

**Comment by dk250** [comment]
I think I have solved my problem. The socket2 can not connect the server successfully, because it is a local variable.  I make it to be member variable of class. It works. Thank u.
