### ISSUE TITLE
Usages of emitWithAck(event:String, _ items:AnyObject...) in Objective-C

### ISSUE THREAD

**Issue by sauvikatinnofied** [socketio/socket.io-client-swift#84]
Hello, asking for help again. I have integrated this useful library in an ```Objective-C``` project. I am facing problem while implementing 
```swift
emitWithAck(event:String, _ items:AnyObject...)....
```
 method in ```Objective-C```. I need a completion handler like ```block``` in which I have to modify the view on acknowledgement from server. Please help me how to implement this feature in ```Objective-C```. Will there be any job to be done in server side too? Thank you in advance.

**Comment by nuclearace** [comment]
I updated the objective c example in the readme. It should provide an example

**Comment by sauvikatinnofied** [comment]
I have this code
```objective-c
- (void)sendEvent:(NSString*)event eventData:(id)data withCompletionHandler:(MessageSendingCompletionHandler)completionHandler{

    [_socketClient emitWithAck:event withItems:@[data]](0, ^(NSArray* data) {
        completionHandler();
    });
}
```
and a break point is added on ```completionHandler()```. Event is emitted successfully, server is also listening the event perfectly, but my ```completionHandler()``` is never called. Please suggested me how to execute this _completion block_.

**Comment by nuclearace** [comment]
If you add code directly inside the block passed to the function is it executed? Sounds like it could be a swift-objective-c issue

**Comment by sauvikatinnofied** [comment]
No @nuclearace , it is not executed. First I was trying with a simple ```NSLog(@"Data Sent")```. But it never executed.

**Comment by cmorss** [comment]
I've installed into my Objective-C project via cocapods and can't seem to get the import statement correct. I've read the Apple docs on importing Swift into Objective-C projects to no avail. Can you also include the correct #import statement in the readme as well?  Thanks.

**Comment by nuclearace** [comment]
@sauvikatinnofied can you create the socket with logging on and pastebin it?

**Comment by nuclearace** [comment]
Also @cmorss, I'll have to relearn how to do it myself. I didn't add CocoaPods support, someone else did. What imports have you tried?

**Comment by nuclearace** [comment]
@sauvikatinnofied are you calling the ack function on the server?

**Comment by cmorss** [comment]
@nuclearace I created a new project to figure out what I needed to import. This seems to work:

```
#import "Socket_IO_Client_Swift/Socket_IO_Client_Swift-Swift.h";
```

**Comment by nuclearace** [comment]
I recall if you follow the steps to creating a cocoa project, it's something shorter.

**Comment by PengsreangSrun** [comment]
I have been facing problem with emit and I cannot receive data back. So how can I do?Please help me!

**Comment by nuclearace** [comment]
@PengsreangSrun Are you using `emitWithAck`?

**Comment by nuclearace** [comment]
Also, it's up to the server to actually respond to that ack.

**Comment by PengsreangSrun** [comment]
@nuclearace I used with emitWithAck but i cannot receive anything back!

**Comment by nuclearace** [comment]
Do you know if the server is supposed to respond with something. Also do other events work?

**Comment by PengsreangSrun** [comment]
yes, server is responded and other events are also work out!

**Comment by PengsreangSrun** [comment]
if possible, can u drop code of receive data back?

**Comment by sauvikatinnofied** [comment]
Sorry for late reply. User this type of code snippet in server side, 
```objective-c
- (void)sendEvent:(NSString*)event eventData:(id)data withCompletionHandler:(MessageSendingCompletionHandler)completionHandler{

    [_socketClient emitWithAck:event withItems:@[data]](0, ^(NSArray* data) {
        completionHandler();
    });
}
```

now my completion handler is being executed from server side.

```javascript
        socket.on('newIncomingMessageFromUser', function(message, cb) {
            if (cb) {
              cb(messageObject);
            }
        });
```

Thank you so much for being generous in helping us.
