### ISSUE TITLE
No available "nuclearace/Starscream" in version 11.1.3

### ISSUE THREAD

**Issue by TruongDang** [socketio/socket.io-client-swift#842]
I'm trying to integrate soccket.io version 11.1.3.
I followed the instructions: https://github.com/socketio/socket.io-client-swift/tree/v11.1.3.
I have a problem with github library `nuclearace / starscream" ~> 8.0.5`.
I use carthage.
I get the error message `No available version for github" nuclearace / Starscream "satisfies the requirement: ~> 8.0.5`

**Comment by TruongDang** [comment]
I need to use v11.1.3 for the reason that my project is developing on swift version 3

**Comment by TruongDang** [comment]
```
github "socketio/socket.io-client-swift" ~> 11.1.3
github "daltoniam/Starscream" ~>  2.0.3
```
Can I use it?

**Comment by nuclearace** [comment]
Probably won't work with the lib. I'm not sure why Carthage is not happy. Although I will say you should update to Swift 4 asap. It's not that big a change, and will probably solve this issue since I no longer use a custom Starscream impl

**Comment by nuclearace** [comment]
I solved this by doing 
```shell
rm -rf /Users/username/Library/Caches/org.carthage.CarthageKit/DerivedData/ /Users/username/Library/Caches/org.carthage.CarthageKit/dependencies/
```
