### ISSUE TITLE
Memory leak in SocketIOClientOption

### ISSUE THREAD

**Issue by hoanghung3249** [socketio/socket.io-client-swift#843]
Hi, 
I'm install socket.io version 11.1.3. I followed your example and I found the memory leak in SocketIOClientOption 
![screen shot 2017-10-18 at 5 42 44 pm](https://user-images.githubusercontent.com/20684955/31714871-c9fdceb4-b42b-11e7-8761-364421117217.png)

![screen shot 2017-10-18 at 5 41 31 pm](https://user-images.githubusercontent.com/20684955/31714886-da8ca188-b42b-11e7-9390-865238355040.png)
Can you check again please?
Thank you!

**Comment by nuclearace** [comment]
_ContigiousArrayStorage is an internal Swift entity. And SocketIOClientOption is just an enum with value memory semantics, so it's impossible for users to control when it's released. And the `SocketIOClientConfiguration` is another value type, so it would be released automatically by ARC without needing `weak` or `unowned` declarations.

From my experience, Xcode is pretty bad at determining leaks in Swift code. You see tons of "leaks" in the standard library.
