### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by fabrijp** [socketio/socket.io-client-swift#848]
I'm new to use packages on iOS and I can't just make it work on my project ( I have no much idea how to include this on a new iOS project ). Any help ?  Thank you !

**Comment by nuclearace** [comment]
"I can't just make it work" is not helpful. What does not work? How are you creating the client? Have you turned on logging? Have you checked the [FAQ](https://nuclearace.github.io/Socket.IO-Client-Swift/faq.html)?

**Comment by fabrijp** [comment]
Sorry, I’m just trying to add it to a new iOS project. I never used Managed Packages before and just creating a Package.swift with the dependencies like discribled in the readme file, running swift package resolve isnt helping me much to start using it.

**Comment by nuclearace** [comment]
@fabrijp For an iOS project you'll probably want to use [CocoaPods](https://cocoapods.org/) or [Carthage](https://github.com/Carthage/Carthage), SPM support for iOS projects isn't very good. You'll have to read up on using those package managers in iOS projects. Generally when you use a library, you should have a basic understanding of how to install them.

**Comment by fabrijp** [comment]
Got it to work with Carthage. Thank you !
