### ISSUE TITLE
Cant send multiline messages

### ISSUE THREAD

**Issue by cdagli** [socketio/socket.io-client-swift#85]
We are using socket.io@1.3.5 and Socket.IO-Client-Swift to implement a chat application. Everything works okay when a one line message is send. socket.io-parser parses the packet and process it.

![screen shot 2015-05-23 at 23 25 44](https://cloud.githubusercontent.com/assets/7020369/7787309/c95f5720-020d-11e5-966b-b13837ea6129.png)

<pre>   
  engine handling "POST" http request "/socket.io/?transport=polling&sid=D4hHosMaFHKF2xZAAAAA" +0ms
  engine setting new request for existing client +1ms!
  engine:polling received "20:42["message","test"]" +0ms
  engine:socket packet +0ms
  socket.io-parser decoded 2["message","test"] as {"type":2,"nsp":"/","data":["message","test"]} +8.2m
  socket.io:socket got packet {"type":2,"nsp":"/","data":["message","test"]} +6m
  socket.io:socket emitting event ["message","test"] +0ms</pre>

But when a multiline message is send it looks like socket.io-parser can't decode the packet;

https://cloud.githubusercontent.com/assets/7020369/7787325/a216562c-020e-11e5-8bc0-04684dc1044f.png

<pre>
  engine handling "POST" http request "/socket.io/?transport=polling&sid=D4hHosMaFHKF2xZAAAAA" +0ms
  engine setting new request for existing client +0ms
  engine:polling received "27:42["message","test2
test3"]" +1ms
  engine:socket packet +0ms
  socket.io:client no socket for namespace undefined +1m</pre>

I trim the text that I get from the input box if it is more than 255 chars

<pre>if (text.length > 255) { // trim the text longer than 255
    text = [text substringToIndex:255];
}</pre>
And then I emit it with a "message" event;

<pre>
[_socket emit:@"message" withItems:@[text]];
</pre>
It seems in the NSLog as below;

<pre>
2015-05-23 23:36:43.580 TestApp[383:3300397] Text: test3
test4</pre>

I've checked my old configuration Socket V0.9 and it looks line client sends the message as "test1\ntest2", I am not sure if the issue belongs the client or the server. Is it related with the header content-type?

Any thoughts on how can I solve the issue?

Thank you

**Comment by nuclearace** [comment]
It looks like it wants \n to be escaped before sending
