### ISSUE TITLE
Redefinition of module 'SSCZLib' % 'SSCommonCrypto'

### ISSUE THREAD

**Issue by nageshkumarmishra** [socketio/socket.io-client-swift#851]
Below are the pods i am using
pod 'Fabric'
pod 'Crashlytics'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Alamofire', '>= 1.2'
pod 'IQKeyboardManagerSwift'
pod 'AWSCognito'
pod 'AWSCognitoIdentityProvider'
pod 'AWSMobileAnalytics'
pod 'OpenTok', '~> 2.0'
pod 'Socket.IO-Client-Swift', '~> 12.1.2'

<img width="376" alt="screen shot 2017-10-29 at 3 41 02 pm" src="https://user-images.githubusercontent.com/1469520/32142550-a00f46d6-bcbf-11e7-9720-3b4235356293.png">

Let me know what things I am doing wrong?

**Comment by nuclearace** [comment]
Is this on a clean project? IIRC those modules were removed in favor of a true dependency on Starscream.

**Comment by Codeido** [comment]
You can fix the problem cleaning the project and removing derived data.

**Comment by CAMOBAP795** [comment]
The same problem for me, clean project && `rm ~/Library/Developer/Xcode/DerivedData` didn't help

**Comment by Codeido** [comment]
I noticed that it happens even if you have another open Xcode project that uses Socket.IO (eg the demo project).

**Comment by CAMOBAP795** [comment]
### Long story short

1. Find which source lead to compilation error. In my case it was one of `UIViewController` implementation, `MyViewController.swift`
2. Find related `.swiftdeps` file, in my case `MyViewController.swiftdeps`
```
cat ~/Library/Developer/Xcode/DerivedData/HelloWorld-*/Build/Intermediates.noindex/HelloWorld.build/Debug-iphonesimulator/HelloWorld.build/Objects-normal/x86_64/MyViewController.swiftdeps | grep zlib
```
\* you may have different path

3. Command above produce several lines:
```
- "/Developers/Projects/HelloWorld/Pods/Starscream/zlib/module.modulemap"
- "/Developers/Projects/HelloWorldLibrary/Pods/Starscream/zlib/module.modulemap"
```
4. Here is where duplication comes, now it's up to you how you will resolve it, there is no universal advice (for me it was to delete directory from last line)

### Long story

I'm working on library which I will distribute as closed source product, technically as `framework`, so I build this library locally, and as far as I understood implicitly it have references to all `module.modulemap` files, so once I included this framework as local `pod` it gave me this errors

BTW Anyone can advice good article/doc which will explain swift compilation process, all these: `.swiftdeps`, `.swiftmodule`, and how swift toolchain/pipeline works?

**Comment by zenkimoto** [comment]
Same here.  I'm also trying to build a closed source product and I can confirm the module dependency duplication.  Also removing DerivedData didn't help.  Anyone got any ideas?

**Comment by zenkimoto** [comment]
In your case, try renaming the file: /Developers/Projects/HelloWorld/Pods/Starscream/zlib/module.modulemap to say something like zlib.modulemap

**Comment by CAMOBAP795** [comment]
@zenkimoto rename which you propose will not help because `*. swiftdeps` under control of xcode, and it will overwrite any changes

**Comment by zenkimoto** [comment]
@CAMOBAP795 The modulemap file, not *.swiftdeps.

**Comment by CAMOBAP795** [comment]
@zenkimoto so your proposal to do `mv /Developers/Projects/HelloWorld/Pods/Starscream/zlib/module.modulemap /zlib.modulemap`, right?

**Comment by zenkimoto** [comment]
@CAMOBAP795 Yes.  I was able to rename the modulemap file and get it to compile.  I was wondering if that would help you out too.

**Comment by CAMOBAP795** [comment]
@zenkimoto thanks, yep this helped me to, looks like it's not clear [from my comment above](https://github.com/socketio/socket.io-client-swift/issues/851#issuecomment-354407244) I will improve it
