### ISSUE TITLE
 No such module 'Starscream'

### ISSUE THREAD

**Issue by Fujikatoma** [socketio/socket.io-client-swift#853]
Using the newest Xcode and newest version of the lib result in the following error :

Pods/Socket.IO-Client-Swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: No such module 'Starscream'

**Comment by willdenms** [comment]
Same problem here. I've been trying to work around this for a while. Has anyone had any luck?

**Comment by leonnoel777** [comment]
Same problem... how to solve this..??
