### ISSUE TITLE
IOS 11 has one weird bug

### ISSUE THREAD

**Issue by kacak9229** [socketio/socket.io-client-swift#854]
I ran both on IOS 11 and 10. Same code and both are using Swift 3.2

on IOS 10, everything is good (been testing this for about 1 month already), no problem but on IOS 11 I keep getting Socket nil. I get nil if I close the app and open it again.

**Scenario**

I'm using Singleton concept.

```
import SocketIO

class SocketIOManager: NSObject {
    
    static let sharedInstance = SocketIOManager()
    var socket: SocketIOClient!
    
    func establishConnection() {
        socket = SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .connectParams(["token": getToken()])])
        socket.connect()
    }
    
    func closeConnection() {
        socket.disconnect()
    }
}
```
and on App Delegate

```
func applicationDidBecomeActive(_ application: UIApplication) {
        SocketIOManager.sharedInstance.establishConnection()
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }
```

ViewMainController -> is the initial view controller

```
class ViewController: UIViewController {

  override func viewDidLoad() {
      socketToAllDrivers()
  }

func socketToAllDrivers() {
       SocketIOManager.sharedInstance.socket.on("listening") { data, ack in
              print("hello")
        }
    }
}
```
The error is at  `SocketIOManager.sharedInstance.socket.on("listening")`  

> Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

I have no idea how to fix this problem, my logic would be the time of establishing the socket connection but it doesn't make sense because on IOS 10 it works just fine.

**Comment by nuclearace** [comment]
Generally you should also be wary of using `!`, but in this case if the assumption that `applicationDidBecomeActive` will always be called and always be called before anything else is true, I think this would be okay. So I'm not really sure.

But this isn't really an issue with the library, and more of an implementation issue.
