### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by olgadanylova** [socketio/socket.io-client-swift#856]
Hello!
After the Xcode 9.1 release there is a warning in the WebSocket.swift class (line 668, validateResponse func):
> 'characters' is deprecated: Please use String or Substring directly

Thanks

**Comment by nuclearace** [comment]
WebSocket.swift shouldn't be in this project in the latest version.

**Comment by hansemannn** [comment]
Hey there! I'm having the same issue with `pod 'Socket.IO-Client-Swift', '~> 12.1.3'`.

**Comment by olgadanylova** [comment]
Hello! I've installed v 13 via cocoapods, but this warning is still here and the WebSocket.swift class is also present

**Comment by nuclearace** [comment]
It’s the Starscream dependency, which I don’t have control when they release a new version.
