### ISSUE TITLE
How to transfer pictures (larger pictures)

### ISSUE THREAD

**Issue by meiyongsheng** [socketio/socket.io-client-swift#860]
How to transfer pictures (larger pictures)

**Comment by meiyongsheng** [comment]
How to transfer pictures (larger pictures)

**Comment by nuclearace** [comment]
@meiyongsheng You probably don't want to use socket.io transfer large amounts of data. Should probably use regular HTTP for that. That being said, you can send `Data` objects in payloads back and forth from the server.
