### ISSUE TITLE
I can not listen to messages in any way for Objective-C

### ISSUE THREAD

**Issue by nefy55** [socketio/socket.io-client-swift#861]
this method is not triggered   [self.socket on:@"message" callback:....]  
My project objective c
ı implement socketio's methods in viewdidload 

NSURL* url = [[NSURL alloc] initWithString:@"....3000/"];
    self.socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"token" : jwtToken , @"log":@YES  }];

    [self.socket on:@"connect" callback:^(NSArray *data, SocketAckEmitter * ack) {
                // this method working. socket is connecting
    }];

[self.socket on:@"message" callback:^(NSArray* data , SocketAckEmitter * ack) {
        // this not working any way.
    }];

I implemented the "message" method in different places, but somehow I can not listen to messages. It is don't work. I will be damned

**Comment by nuclearace** [comment]
@nefy55 Are you sure you're adding the right event name? AFAIK socket.io doesn't have a default "message" event.

**Comment by nefy55** [comment]
@nuclearace Yes I am sure. Server sends messages with this name : "message" . But ı not listen messages.

**Comment by nuclearace** [comment]
@nefy55 Have you turned on logging and seen what's coming over from the server?

**Comment by dereknex** [comment]
@nefy55 do you  have check you namespace?

try the following code:

```objective-c
NSURL* url = [[NSURL alloc] initWithString:@"ws://127.0.0.1:8000"];
_manager = [[SocketManager alloc] initWithSocketURL:url config:@{@"log": @YES}];
SocketIOClient* socket = [_manager socketForNamespace:@"/test"];
```

**Comment by SusheelYadavAhex** [comment]
Hi @nefy55 , are you able to listen to socket events ? Actually i am able to connect to socket through namespace and able to sent the jwt token to socket also, but unable to listen to events. 


**Currently i am implementing like this .** 

// **Connecting to Socket**

``
    NSURL *url=[NSURL URLWithString:@"https://app.demo.io"];
    socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"log": @YES}];  // In oder to check the log
    NSLog(@"The socket url is %@", url);
    [socket on:@"connect" callback:^(NSArray *data, SocketAckEmitter *ack) {
        NSLog(@"socket connected ");
        
``

``
        // Joining namespace after socket connection .
        NSString *nameSpaceStr = [NSString stringWithFormat:@"/rt.demo.io/device"];
        [socket joinNamespace:nameSpaceStr];
        
``

``
        // **Get User Login Token from Login API**
        NSString *savedValue = [[NSUserDefaults standardUserDefaults]
                                stringForKey:@"token"];
        NSLog(@"The login token from user defaults  %@", savedValue);
        
 NSMutableDictionary *message = [[NSMutableDictionary alloc] init];
        [message setObject:savedValue forKey:@"id"];
        [self.socket emit:@"setDetails" with:@[message]];
        NSLog(@"Emit message : sending login token to socket %@",message);

  **// Listentng Socket Events**

``
        [self.socket on:@"getVideoCallStatus" callback:^(NSArray * data , SocketAckEmitter  *ack) {
             NSLog(@"On message listening hearing from server  %@", data);
            NSLog(@"On mesage ack is %@", ack);
            
        }];

``

If u have worked on it. Could you help me out please . !

**Comment by nefy55** [comment]
I tried all of them. But not received
