### ISSUE TITLE
In the last Swift version, the utf8 encoding

### ISSUE THREAD

**Issue by usrpark** [socketio/socket.io-client-swift#862]
In the last Swift version, the utf8 encoding for the first ten events after socket connection is incorrect and the characters are broken. So I'm using the dummy event now
![6ce481a0-8167-4546-880c-62ecd7a0e3f8](https://user-images.githubusercontent.com/33507519/32635914-b18e378e-c5f5-11e7-869b-e76114b15c6b.jpeg)

**Comment by nuclearace** [comment]
@usrpark Your server must be on socket.io 1.0. The latest version of the client only supports 2.0+.

**Comment by usrpark** [comment]
thank you!

**Comment by Marwan88** [comment]
hello @nuclearace 

I'm using client version 15.2.0 and server version 1.4.5 but still the same problem
can you help me ?
<img width="919" alt="Screen Shot 2020-05-18 at 10 33 32 AM" src="https://user-images.githubusercontent.com/1782786/82188530-affa1380-98f6-11ea-8065-e2e5f5bc4004.png">

**Comment by malqadi88** [comment]
please check my fix [here](https://github.com/socketio/socket.io-client-swift/issues/640#issuecomment-1323212942)
