### ISSUE TITLE
Updating Authorization headers for subsequent reconnections

### ISSUE THREAD

**Issue by headlessme** [socketio/socket.io-client-swift#863]
I'm using short lived bearer tokens to authorise socket IO connections via the Authorization header, which works fine for the initial connection, but if the socket gets disconnected for some reason then retries with the initial token it will fail. Ideally I need some way to update the headers that will be sent on subsequent reconnections when a token expires. I'd rather not tear down the whole connection and start a new one as I'll lose backoff state etc...

I haven't found a way to update the headers in place with this library, is it possible?

**Comment by nuclearace** [comment]
@headlessme You should be able to modify [the headers](https://nuclearace.github.io/Socket.IO-Client-Swift/Protocols/SocketEngineSpec.html#/c:@M@SocketIO@objc(pl)SocketEngineSpec(py)extraHeaders) directly, (note this should be done on the `engineQueue` for safety.

**Comment by headlessme** [comment]
The `extraHeaders` dictionary seems to be immutable (although I pass a mutable dictionary in the `SocketManager` options), and the property is readonly so I can't assign a new value directly. I've tried replacing the dictionary and modifying it in place:

```
streamSocketMgr.engine.extraHeaders = @{ @"myHeader": @"thing" } // assignment to readonly property
```

or

```
[streamSocketMgr.engine.extraHeaders setObject:@"thing" forKey:@"myHeader"]; // selector not found
```

**Comment by nuclearace** [comment]
Oh, duh. I think I had been wanting to make this mutable for a while but kept forgetting to do that. https://github.com/socketio/socket.io-client-swift/issues/684 This is the original request.
