### ISSUE TITLE
Can't connect in v13.0.0

### ISSUE THREAD

**Issue by olgadanylova** [socketio/socket.io-client-swift#864]
Hi!
In previous versions i've connected socket like this:
```
@interface MyClass() {
    SocketIOClient *socket;
}
@end

@implementation MyClass
...
NSString *path = @"/somePathHere";
NSURL *url = [[NSURL alloc] initWithString:@"http://localhost:5000"];
socket = [[SocketIOClient alloc] initWithSocketURL:url config:@{@"path": path, @"nsp": path, @"connectParams":@{@"token":@"some-token"}}]; 
[self addHandlers];
[socket connect];
...
@end
```
And now I'm trying to do something like:
```
@interface MyClass() {
    SocketManager *manager;
    SocketIOClient *socket;
}
@end

@implementation MyClass
...
NSString *path = @"/somePathHere";
NSURL *url = [[NSURL alloc] initWithString:@"http://localhost:5000"];
manager = [[SocketManager alloc] initWithSocketURL:url config:@{@"path": path, @"connectParams":@{@"token":@"some-token"}}];
socket = [[SocketIOClient alloc] initWithManager:manager nsp:path];
[self addHandlers];
[socket connect];
...
@end
```
In the second way the socket is created but not connected and I can assume it could be because of config and nsp parameters, because the socket without any config and nsp connects fine. Am I doing smth wrong? Could you please help me?

Thanks!

**Comment by nuclearace** [comment]
@olgadanylova You shouldn't be creating `SocketIOClient`s directly. You should be calling [this method](https://nuclearace.github.io/Socket.IO-Client-Swift/Classes/SocketManager.html#/c:@M@SocketIO@objc(cs)SocketManager(im)socketForNamespace:) I would recommend checking out the [migration guide](https://nuclearace.github.io/Socket.IO-Client-Swift/12to13.html)

**Comment by olgadanylova** [comment]
You've made my day! Thanks!

**Comment by olgadanylova** [comment]
Can be marked as closed.
