### ISSUE TITLE
emitWithAck not working properly with no parameter

### ISSUE THREAD

**Issue by thully** [socketio/socket.io-client-swift#866]
If I try to send an emitWithAck message with no parameter, the socket.io server doesn't receive the ack callback.
The timeout function is called with the NO ACK response. The code I'm using looks something like this:

       socket.emitWithAck("message").timingOut(after: 5) { data in
        }

If I add an argument, the ack callback is received correctly:
       socket.emitWithAck("message","").timingOut(after: 5) { data in
        }

I'm using version 12.1.3 of the socket.io-client-swift library.

**Comment by nuclearace** [comment]
@thully This works fine in v13.0, and I don't know of any reason it would've changed between those versions. Are you sure your server isn't always expecting some data? Because if that's the case the server is probably either crashing or just rejecting the event.

**Comment by thully** [comment]
This was a server issue
