### ISSUE TITLE
Websocket ping timeout

### ISSUE THREAD

**Issue by yannickl** [socketio/socket.io-client-swift#87]
Hi,

Despite a `pingTimeout: 3000` and a `pingInterval: 3000` define to the server if I cut the wifi connection (for my test the server running on my computer and the iPad running on the same local network) the client is not notified by a timeout, disconnect or error event.

Everything works correctly except for this use case and unfortunately I don't know where to start the investigations. FYI I connect the client with the `forceWebsockets` option to `true`.

Best,

Yannick

**Comment by nuclearace** [comment]
Is it being notified of a reconnect event? 

When I turn wifi off from my laptop running OS X I get
```
Got error: The operation couldn't be completed. Socket is not connected
Socket reconnecting: The operation couldn't be completed. Socket is not connected
Reconnect tries left: -1
```

**Comment by nuclearace** [comment]
Also, does this iPad have 3G/LTE?

**Comment by yannickl** [comment]
This is an iPad Wifi, I don't have the 3G/LTE.

I forgot to mention I also set the `reconnects` to `false` and `reconnectAttempts` to `0`.
I don't have any events. So when I turn off my wifi the iPad didn't know that the connection is closed.

May be this is not a good idea to put the reconnects to false but I really need to know when the connection is closed or lost.

**Comment by nuclearace** [comment]
This must be some weird case where it handles differently than OS X. Because when I test on OS X it always emits an error if the wifi drops.

**Comment by yannickl** [comment]
I will test it tomorrow with an iOS simulator on an another macbook to check whether it works. It seems that the `Websocket` class didn't notice about the connection lost. I need to go further with the investigation.

**Comment by nuclearace** [comment]
Hm, when I did a simple test with an iphone it seemed to handle going into airplane mode and when it just loses wifi.

**Comment by yannickl** [comment]
I can reproduce the issue with my iPhone and my iPad with this code:

In node.js:
```javascript
var options = {
  pingTimeout: 3000,
  pingInterval: 3000,
  transports: ['websocket'],
  allowUpgrades: false,
  cookie: false
};

var app = require('express')();
var server = require('http').Server(app);
var io = require('socket.io')(server, options);

server.listen(3000, function (err) {
  console.log('server running...');
});

io.on('connection', function (socket) {
  console.log('connected');

  socket.on('disconnect', function () {
    console.log('disconnected');
  })
});
```

In swift (for iOS):
```swift
import UIKit
import Socket_IO_Client_Swift

class ViewController: UIViewController {
  let socket  = SocketIOClient(socketURL: "192.168.0.30:3000", opts: [
    "reconnects": false,
    "reconnectAttempts": 0,
    "forceWebsockets": true
    ])

  override func viewDidLoad() {
    super.viewDidLoad()

    socket.onAny { event in
      println("Got event: \(event.event), with items: \(event.items)")
    }
    
    socket.connect()
  }
}
```

Here is the workflow:
1.  Run the server (app.js) on the macbook
_=> the server is running_
2.  Connect the client (swift)
_=> both the server and the client received a connected event_
3.  Turn off the wifi of the macbook
_=> after 3 seconds the server receive the disconnected event, but the swift client nothing..._

**Comment by nuclearace** [comment]
Hm, when I try this on the iphone simulator it fires a disconnect.

**Comment by nuclearace** [comment]
Okay, but when I do it from an actual iphone it doesn't, weird.

**Comment by yannickl** [comment]
Have you found the workaround? Or this is a problem from my code?

**Comment by yannickl** [comment]
It's my bad, I just see your commit: https://github.com/socketio/socket.io-client-swift/commit/fcebc870c3f7af84bafcfa2370c15f9e9d2cb9e5

Thank you, I'm going to try it right now!
