### ISSUE TITLE
Raw Messages

### ISSUE THREAD

**Issue by GF106** [socketio/socket.io-client-swift#870]
How to send a raw message to the server?

**Comment by nuclearace** [comment]
What do you mean raw? You can send messages through the engine using the write method on it.

**Comment by nuclearace** [comment]
Note that those are engine messages though. So they’d need to be encoded in the socket.io format before sending. So I wouldn’t recommend doing that unless your server is just using engine.io

**Comment by GF106** [comment]
Raw Message means not to use json, but just send a message.

**Comment by GF106** [comment]
Raw Message means not to use json, but just send a message.

**Comment by nuclearace** [comment]
@GF106 You can just do
```swift
socket.emit("myEvent", 1, "someString")
```
You can translate that to Objective-C but you just wrap everything in an array.

**Comment by GF106** [comment]
I use it. 
My code:
[_socketClient emit@"auth" with: [NSArray array withObjects:MyArray. nil]];
Result: 
157:42["auth", {MyArray(json}]
how to specify your number, not 157:42?
My server does not understand me.

**Comment by nuclearace** [comment]
Is your server an actual socket.io server or just a WebSocket server? This library is just for socket.io. You should use Starscream or its objc equiv if you need a Websocket client.

**Comment by GF106** [comment]
Yes my server actual socket.io. 
On Windows OS, I use a library for Visual Studio. With it, I'll post clean messages socket.send("421["auth"{"username" : MyName}]") without using the json conversion.
is it possible to send in the same way?

**Comment by nuclearace** [comment]
No, why would you do this? This is defeating the purpose of using a library like this. Since you're affectively bypassing the entire library and writing directly to engine.io.

**Comment by GF106** [comment]
Well thank you. But can I epigonomize this meaning 157:42?
insert my value

**Comment by nuclearace** [comment]
What?
