### ISSUE TITLE
Not able to sent strings with some special characters

### ISSUE THREAD

**Issue by sumeshshivan** [socketio/socket.io-client-swift#871]
The events are not being sent when there are some special characters in the message.
For example apostrophe in `Don’t` . There is no crash or error happens along with only that the message is not received at the socket.io server

I am using socket.io-client-swift v9.0.1 and the socket.io server version is 1.3.4

I have tried setting `doubleEncodeUTF8` to true and it didn't help.
Is something I am missing here? Please help me tackle this issue.

**Comment by nuclearace** [comment]
Try turn on logging in both the client and server and see what is being sent/received.
