### ISSUE TITLE
Cannot use instance member 'nsp' within property initialiser

### ISSUE THREAD

**Issue by elitelokesh** [socketio/socket.io-client-swift#875]
<img width="311" alt="screen shot 2017-11-20 at 11 00 31" src="https://user-images.githubusercontent.com/8547601/33003690-4620cb5c-cde2-11e7-8ba7-60c8a1ec3bfa.png">
<img width="686" alt="screen shot 2017-11-20 at 11 01 55" src="https://user-images.githubusercontent.com/8547601/33003707-63556818-cde2-11e7-850b-9f03621571e5.png">

Used Pods to install

**Comment by MeGaPk** [comment]
need swift 4 for that

**Comment by nuclearace** [comment]
Sounds like the wrong Swift version.

**Comment by IdeaCentricity** [comment]
Change swift version in Xcode

**Comment by priyankakanojia36** [comment]
need some other solution
