### ISSUE TITLE
Singleton design and token (before user logs in)

### ISSUE THREAD

**Issue by kacak9229** [socketio/socket.io-client-swift#876]
My socket.io is  depending on token, without the user's token, it won't work. The problem that I'm facing is that whenever user loads up the app the init method will initialized the socket without the token. This is before user logs in

```
func applicationDidBecomeActive(_ application: UIApplication) {
        SocketIOManager.sharedInstance.establishConnection()
    }
```

Singleton Design
```

import SocketIO

class SocketIOManager: NSObject {

    static let sharedInstance = SocketIOManager()

    let socket: SocketIOClient!

    init() {
        
        socket = SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .connectParams(["token": getToken])])
       super.init()
    }

    func establishConnection() {
       socket.connect()

    }

    func closeConnection() {
        socket.disconnect()
    }

    func getToken() -> String {
      if let token = keychain["token"] {
         return token
      }
      return ""
   }

}
```

Even user logs in and got the token, it won't establish the connection because the init method already initialized the socket's object without the token.

But If close the app and open it up again, it will establish the connection, because now the init method will initialized with the token.

So my logic will be the Singleton Design's init method will immediately create the socket object with or without the token when the app loads up.

How do I solve this problem? Anyone with experience with socket.io swift could share how you solve this problem?

**Comment by nuclearace** [comment]
@kacak9229 This is an issue for StackOverflow.

**Comment by kacak9229** [comment]
I thought that by posting here, people with experience could help me. Am I wrong?

**Comment by nuclearace** [comment]
@kacak9229 The question is really more general than just this library, it's a design question. You'll get a faster response if you ask the question on stackoverflow.

**Comment by kacak9229** [comment]
Alright thanks! 

I want to ask you personally if you were me. and If your app is heavily depending on token.

Would you go for for

1. Init method - (Problem if token is not there then it initialized the socket without token)

```
var socket: SocketIOClient!
    private override init() {
        socket =  SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .connectParams(["token": getToken()])])
        super.init()
    }
```
or

2. Initialize the socket object in the `establishConnection` - (Problem socket is going to be nil when trying to launch the app)

```
var socket: SocketIOClient!
func establishConnection() {
       socket = SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .connectParams(["token": "asdasdasdsa"])])
       socket.connect()

    }
```
Just your opinion, if you don't mind

Thanks!

**Comment by nuclearace** [comment]
@kacak9229 I would make sure the token is there before doing anything with the socket.

**Comment by kacak9229** [comment]
Just wondering if token is not present anymore, I clear the token

`keychain["token"] = nil`

The .connectParams will still have the token

`socket = SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .connectParams(["token": keychain["token"]!])])`

How do I clear the token inside `.connectPrams`?

**Comment by nuclearace** [comment]
@kacak9229 You'd either need a new socket, or if you're using the newest version, update the manager's configs.

**Comment by kacak9229** [comment]
Are you talking about adding `forceNew(true)` ? to 

`SocketIOClient(socketURL: URL(string: mainURL)!, config: [.log(false), .compress, .forceNew(true), .connectParams(["token": keychain["token"]!])])` 

Is it correct?
