### ISSUE TITLE
BITCODE_ENABLED set to NO in target, but YES for project?

### ISSUE THREAD

**Issue by tw23** [socketio/socket.io-client-swift#879]
Hey,
I recently updated to the new socket io v13, however I noticed that it doesn't compile with bitcode enabled which is making Carthage fail for me. I'm manually re-enabling bitcode and rebuilding, but I was wondering why `BITCODE_ENABLED` is set to `NO` in target framework but `YES` for the project settings?
Is it okay to re-enable bitcode?

Thanks!

**Comment by nuclearace** [comment]
Oh idk. I think it needs to be selectively turned on for certain SDKs since I don't think macOS supports it.

**Comment by tw23** [comment]
Ahh okay cool, you don't happen to know how to force carthage to build with bitcode enabled by any chance?

Thanks!

**Comment by nuclearace** [comment]
@tw23 This should be fixed in 13.1.0.

**Comment by c4mmcnamara** [comment]
For the debug configuration you may want to consider setting BITCODE_GENERATION_MODE to marker instead of bitcode.
