### ISSUE TITLE
won't reconnect when app gets suspended in background 

### ISSUE THREAD

**Issue by obsobsobs** [socketio/socket.io-client-swift#88]
I just debugged this problem and i found out that when the app get suspended in background,

the eventCode in this Method "public func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent)" is equal to .HasSpaceAvailable

I just changed like this:

public func stream(aStream: NSStream, handleEvent eventCode: NSStreamEvent) {
        
        if eventCode == .HasBytesAvailable {
            if(aStream == inputStream) {
                processInputStream()
            }
        } else if eventCode == .ErrorOccurred || eventCode == .HasSpaceAvailable {
            disconnectStream(aStream.streamError)
        }
        else if eventCode == .EndEncountered {
            disconnectStream(nil)
        }
    }

and it works perfectly <3

but i don't know what does HasSpaceAvailable stand for?

**Comment by nuclearace** [comment]
Weird, I'll look into it.

**Comment by nuclearace** [comment]
I'm having trouble reproducing. Going into the background is something the library doesn't account for, because I don't target iOS specifically.

**Comment by obsobsobs** [comment]
you can download the iOS Library and the Simulators in xcode.

**Comment by nuclearace** [comment]
Yes I know, I'm saying I wrote the library to be agnostic as to what platform it's on i.e. OS X/iOS. But I can't get `eventCode` to equal `.HasSpaceAvailable`

**Comment by obsobsobs** [comment]
ok 😊 

under iOS. If you go into the background for ~2min (the app get suspended), i get eventCode == .HasSpaceAvailable.
