### ISSUE TITLE
xcode9 pod error

### ISSUE THREAD

**Issue by EdwinXiang** [socketio/socket.io-client-swift#880]
Hello, I imported the library in xcode9 but gave me a hint that The Swift Language Version (SWIFT_VERSION) build setting must be set to a supported value for targets which is using Swift. This setting can be set in the build settings editor. how to solve this?

**Comment by nuclearace** [comment]
I think you answered your own question.

**Comment by klaus01** [comment]
The problem is that the Starscream library does not specify SWIFT_VERSION. @daltoniam

You can manually specify SWIFT_VERSION for the Starscream library.
![image](https://user-images.githubusercontent.com/338228/33193112-58b2f106-d101-11e7-9cc2-e6281e64bc39.png)
