### ISSUE TITLE
Not receiving messages between two IOS devices using Socket.io

### ISSUE THREAD

**Issue by Davidpacheco1** [socketio/socket.io-client-swift#884]
I am trying to create a chat app on IOS devices using Socket.io.
Here the problem... when I emit a message from the IOS app to a socket I receive it on Node but the users from the IOS App subscribed to this socket not. If I do the emit to this socket from Node all users subscribed receive it but if the emit comes out from the app the users of the app do not receive it.

Node:
`io.on('connection', function(socket){   console.log('a user connected');   socket.on('4-1status', function (from, msg) {     console.log('receive it');   }); }); `
IOS: 
Init SocketClient and sockets.
```
Constants.SocketClient = SocketIOClient(socketURL: URL(string: Constants.baseUrlSocket)!, config: [.log(true), .compress])         
Constants.SocketClient.on(clientEvent: .connect) {data, ack in             
    print("socket connected")        
 } 
Constants.SocketClient.on("4-1status") {[weak self] dataArray, ack in                
 print("Recive")                 
self?.statusChangeDelegate?.statusChange(values: dataArray[0] as! NSDictionary)            
}  
Constants.SocketClient.connect()
```
Emit message to socket:
```
Constants.SocketClient.emit("4-1status", ["id": Constants.me.id, "status": "0"])
```
--

**Comment by nuclearace** [comment]
Your server will need to broadcast messages received from other sockets.

**Comment by Davidpacheco1** [comment]
Can you explain a little more?

**Comment by nuclearace** [comment]
Just sending an event to the server doesn't mean other clients will get an event. The server needs to send another event to the other sockets.

**Comment by Davidpacheco1** [comment]
Got it, tks. @nuclearace
