### ISSUE TITLE
Need off method that accepts a callback reference

### ISSUE THREAD

**Issue by thully** [socketio/socket.io-client-swift#885]
Currently, there are three different off methods - one that accepts a clientEvent, one that accepts a String, and one that accepts a UUID. 

To add to these, it would be useful to have an off method that accepts a callback reference - while is possible to save the UUID and use that to remove a callback, it would be more convenient to just use a reference to the callback itself if the code has it. It would work even if the listener is added/removed/re-added, and It would also be consistent with how the socket.io Java library works (it has an off method that removes a callback).

**Comment by nuclearace** [comment]
Unfortunately this wouldn't be possible in Swift without doing very bad things. https://stackoverflow.com/a/25694072
