### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by packedbox** [socketio/socket.io-client-swift#89]
Hi, i'm using the swift library in an ObjectiveC App to stream data from the phone to a socket, so i emit quite frequently an I see my the memory used by the app growing linearly. 

``` javascript
@property SocketIOClient *socket;
```

``` javascript
[_socket emit:@"GSR" withItems:@[[NSNumber numberWithDouble:timestamp],[NSNumber numberWithFloat:gsr]]];
```

![capture d ecran 2015-05-29 a 12 55 53](https://cloud.githubusercontent.com/assets/1764662/7881331/1a65e934-0602-11e5-99e8-92660e8d1348.png)

If i comment out the write call in the send function in SocketEngine.swift, the memory is stable

``` javascript
   /// Send an engine message (4)
    public func send(msg:String, withData datas:ContiguousArray<NSData>?) {
        if probing {
            probeWait.append((msg, PacketType.MESSAGE, datas))
        } else {
           // write(msg, withType: PacketType.MESSAGE, withData: datas)
        }
    }
```

![capture d ecran 2015-05-29 a 16 49 10](https://cloud.githubusercontent.com/assets/1764662/7885170/ab1a256a-0622-11e5-9ea9-5c99376389f0.png)

**Comment by nuclearace** [comment]
Commenting out that line should actually break things, since it's not sending any messages. But I guess it shows that it's happening somewhere during sending.  Does this happen when using polling or WebSockets?

**Comment by packedbox** [comment]
Yes you’re right it was just to check were the leaks could come from.
I tried to go deeper in the code to check what could be wrong but I must admit i’m a complete newbie in Swift and the code is using async queues so It’s not easy to debug. 

The leaking behavior is present with all combinaisons of forcepolling and forcewebsocket. I tried to use the instruments to track the leak 

setting only forcepolling gives a slighly different pattern in the memory view ( no "steps" in the memory )
![capture d ecran 2015-05-29 a 17 14 40](https://cloud.githubusercontent.com/assets/1764662/7885997/424966a4-0627-11e5-82e2-b60e250b4a66.png)

**Comment by nuclearace** [comment]
How often are you emitting?

**Comment by packedbox** [comment]
I stream data that I receive from a BLE device the rate should be around 60hz

**Comment by nuclearace** [comment]
I think 60 times a second is kinda insane for socket.io. Have you tried doing any instruments profile?

**Comment by nuclearace** [comment]
Also is this the latest version of the client?

**Comment by packedbox** [comment]
Ii have tried instrument but its not clear what's leaking looks like NSString and NSNumber 
Yes it's the lastest version ( I downloaded it yesterday )
Maybe it's the garbage collector that can't cope with the pace, I might need to switch to raw sockets and stay away from NSObjects for this

**Comment by nuclearace** [comment]
Well there is no garbage collector. It's all done with ARC. At least from the client side. So unless this is a Objective-C/Swift issue. It should be reproducible from Swift.

**Comment by packedbox** [comment]
yes you're right i'm too used of using c#

**Comment by nuclearace** [comment]
To me it looks like it thinks the things sent to emit are being leaked.

**Comment by nuclearace** [comment]
Yeah sending a lot messages very quickly seems to stack the memory up.

**Comment by khanhankkhan** [comment]
How are you connecting? Are you connecting to just an IP and port? Or are you connecting with additional parameters as well, such as "host:1234/?something=token" ?

**Comment by packedbox** [comment]
Hi I use this code to creat the socket : 

self.socket = [[SocketIOClient alloc] initWithSocketURL:@"192.168.1.66:4567" options:nil];

**Comment by ingacash** [comment]
I'm also having problems with the memory usage growing with each call to ```emit```. I'm using swift and the latest version of socket.io-client-swift. Here is my code:

```swift
    var socketIOClient: SocketIOClient?

    func socketIOClientStart {
        socketIOClient = SocketIOClient(socketURL: "http://x.x.x.x:xxxx")
        socketIOClient!.on("connect") { data, ack in
            NSTimer.scheduledTimerWithTimeInterval(2.0, target: self, selector: Selector("emit"), userInfo: nil, repeats: true)
        }
        socketIOClient!.connect(timeoutAfter: 5) {
            print("Connection timeout")
        }
    }
    
    func emit() {
        socketIOClient!.emit("foo", "bar")
    }
```

**Comment by nuclearace** [comment]
I'm having trouble pinpointing it. It doesn't seem to detect a leak when using Instruments. Maybe some sort of caching going on?

**Comment by nuclearace** [comment]
Okay, I think it's coming from https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/SocketIOClient.swift#L283

**Comment by nuclearace** [comment]
Gonna have to test this one out. Unless I'm missing something, it seems like Swift is retaining when it shouldn't anymore.

**Comment by hanishabsigh** [comment]
Been debugging this for a few hours. I'm seeing significant memory growth when emitting events quickly. Been hard to figure where this is happening and instruments hasn't detected any leaks. Has anybody made any progress since August?

**Comment by nuclearace** [comment]
Yeah, instruments not detecting leaks was annoying. It's actually occurring very early in the emit process.

https://github.com/socketio/socket.io-client-swift/blob/master/SocketIOClientSwift/SocketIOClient.swift#L260 I don't think it's correctly releasing items.

**Comment by nuclearace** [comment]
Huh, just changing it from

```swift
        dispatch_async(emitQueue) {
            self._emit([event] + items)
        }
```

to 

```swift
        let arr = [event] + items

        dispatch_async(emitQueue) {
            self._emit(arr)
        }
```

Gives a slight improvement.

**Comment by HeineSkov** [comment]
Any news regarding this memory leak?

**Comment by hifall** [comment]
Is this issue fixed?

**Comment by nuclearace** [comment]
Last time I checked, no. From the testing I did it seems to be related a closure capture. Which leads me to believe it's actually just Swift's ARC. It could also be the memory tracking isn't great for tracking Swift.

**Comment by hifall** [comment]
If you think it's a Swift issue, maybe we can escalate this to the Swift team?

**Comment by nuclearace** [comment]
I haven't had time to create a minimal reproducing case.

**Comment by S2V** [comment]
I have same problem. Use carthage: 

> github "socketio/socket.io-client-swift" ~> 6.1.6

. This happend when server is 'down' - server is real off. In console I have print 

> SocketManager -> ERROR: ([{
>     code = "invalid_token";
>     message = "invalid signature";
>     type = UnauthorizedError;
> }], <SocketIOClientSwift.SocketAckEmitter: 0x15d9d520>)

Each message increases  memory consumption  ˜100KB  and generated many thread's.
![xcworkspace](https://cloud.githubusercontent.com/assets/5613351/19770922/c48e27a6-9c69-11e6-93b9-affee96b7d37.png)

**Comment by alevinru** [comment]
I have found that emitting from 1000 async NSOperations within a NSOperationQueue which has maxConcurrentOperationCount = 25 leads to about 20 acks won't be called back due to not safe incrementing of SocketIOClient private currentAck.
