### ISSUE TITLE
fails to reconnect under certain circumstances; did work in 8.3.1

### ISSUE THREAD

**Issue by haemi** [socketio/socket.io-client-swift#896]
When I put the app in the background, the connection is disconnected. Then I put on Airplane mode. No returning in the app, reconnecting does not work (of course). Bring the app in the background, again go into the app. Now I turn off Airplane mode, reconnecting is not possible.

In 8.3.1, reconnecting did work then, now it doesn't; is this intended behavior?

**Comment by nuclearace** [comment]
This isn't something the library will be able to detect. All the underlying networking is handled by the OS, so if it doesn't notify us of a disconnection, there's nothing it can do.

**Comment by haemi** [comment]
I understand your point but it seems as if something's changed in the library as this flow/use case is no problem with e.g. 8.3.1

**Comment by nuclearace** [comment]
Can you look at your logs and see if there's anything there? Generally though the best solution when dealing with background stuff is to take over reconnect logic from the library.
