### ISSUE TITLE
 DefaultSocketLogger.Logger.log(..)

### ISSUE THREAD

**Issue by schm03** [socketio/socket.io-client-swift#899]
Getting "Cannot call value of non-function type 'Bool'" error in numerous places where this function is called. 

Using:
- XCode Version 8.2.1 (8C1002)
- Apple Swift version 3.0.2

For example: 

`    public func parseEngineData(_ data: Data) {
        DefaultSocketLogger.Logger.log("Got binary data: %@", type: "SocketEngine", args: data)
        client?.parseEngineBinaryData(data.subdata(in: NSMakeRange(1, data.count - 1)))
    }
`

My first ever Github post. I know, this is the Big Leagues, I am a rookie.

**Comment by nuclearace** [comment]
You need to the latest Swift/Xcode for the latest version.

**Comment by schm03** [comment]
All updated, thank you.

Followed installation instructions.  No little red warnings in project as of this writing.

Is this the place to ask the questions?
