### ISSUE TITLE
replacement for connectWithParams not working?

### ISSUE THREAD

**Issue by khanhankkhan** [socketio/socket.io-client-swift#90]
Replacing:

     socketIO?.connectWithParams(["token" : escapedToken])

with:

   socketIO = SocketIOClient(socketURL: URLString, opts: ["token" : escapedToken])
   socketIO?.connect(timeoutAfter: 30,
      withTimeoutHandler:
      {
        println("Timed out trying to connect")
      })

though client doesnt connect to server anymore ..

**Comment by nuclearace** [comment]
You need to use the connectParams option. Should be in the readme under options.

**Comment by khanhankkhan** [comment]
Is 'connectParams' not the second input (a dictionary) to the SocketIOClient constructor ?

    socketIO = SocketIOClient(socketURL: URLString, opts:["token" : escapedToken])

**Comment by nuclearace** [comment]
No it's a value of that dictionary. Opts is where you turn on logging and things like that. But it's where I moved connectParams

**Comment by nuclearace** [comment]
```swift
let socket = SocketIOClient(socketURL: "localhost:8080", opts: [
    "connectParams": [
        "blah": "blah"
    ]
])
```

**Comment by gkoeneke** [comment]
Thanks, Erik.  It took some work through the night, still up, but we finally got it all working.  We appreciate it!

**Comment by ManuPerfo** [comment]
Hi Guys,
I am currently working on a project where I need to implement Socket security. I have socket looks like this 
 self.appDelegate.deviceStatusSocket = SocketIOClient(socketURL:  Consatants.domain, options: ["connectParams":["accessToken" : authtoken ,"userId": userId]]

But this not connecting with the host 

We also have a a client side node socket looks like 

socket = io(socketPath, { query: "accessToken=" + userTokenData.id + "&userId=" + userTokenData.userId });

and this is working fine 

What I want to do with the iOS code  to make the socket gets connected with the host

**Comment by nuclearace** [comment]
If you have logging on, does it say anything? Do you have a custom socket.io path defined?
