### ISSUE TITLE
Error build the project after installing library

### ISSUE THREAD

**Issue by cdn34** [socketio/socket.io-client-swift#900]
Hi, I’m trying to use this in a react-native project, and I’m not able to build the project after installing it from CocoaPods.
![screen shot 2017-12-11 at 10 41 25 am](https://user-images.githubusercontent.com/4263618/33828087-905a59fa-de62-11e7-926e-4c471f299b5b.png)
Any help would be appreciated.

**Comment by nuclearace** [comment]
Have you made sure that the SWIFT_VERSION is set properly on everything?

**Comment by cdn34** [comment]
I believe so
![screen shot 2017-12-11 at 11 23 53 am](https://user-images.githubusercontent.com/4263618/33828918-ee089172-de65-11e7-9fad-a55a342ca07d.png)
Is there anywhere else I need to change it ?

**Comment by cdn34** [comment]
Got it working, thanks for the help. Didn't it for the library itself.
![screen shot 2017-12-11 at 11 43 33 am](https://user-images.githubusercontent.com/4263618/33829573-cad3f680-de68-11e7-9031-2e6d93578f06.png)
