### ISSUE TITLE
how can I manually import socketio for swift 4 iOS app

### ISSUE THREAD

**Issue by alionthego** [socketio/socket.io-client-swift#901]
I have followed instructions for installing the socketio libraries for my swift 4 iOS app but can't get it working.  I have tried swift package manager and Carthage.  I don't want to use cocoapods.

My question is how can I install the libraries just manually by downloading and copying the files to my app as I had with previous versions of the socketio?

**Comment by nuclearace** [comment]
Manual import is no longer supported.

**Comment by MiladFaridnia** [comment]
Could you please add it again (manually install support) to your library.

**Comment by MincDev** [comment]
I really wish manual install could be added again. I have been struggling for the last 4 hours trying to get the package manager working.

**Comment by bbs180** [comment]
I really wish too..

**Comment by pranayprajapati** [comment]
I also want to add Socket files manually to my project. I don't want to use Cocoa pods and Carthage.
How can i do it ?
