### ISSUE TITLE
No such Module 'SocketIO'

### ISSUE THREAD

**Issue by schm03** [socketio/socket.io-client-swift#904]
I have, to the best of my ability, followed the installation instructions for this version:
1. modified Package.Swift code (in the socket.io-client-swift-master folder)
2. Attempted to create a class SocketIOClient as per [this tuturial](https://www.appcoda.com/socket-io-chat-app/):

```
import UIKit
import SocketIO
var socket: SocketIOClient = SocketIOClient(socketURL: NSURL(string: "http://192.168.1.XXX:3000")!)
```
Still getting the error.  I have NOT explicitly placed the SocketIO Source folder inside the target project folder, as I am of the understanding that the Package.swift file handles that(?) and I can get a successful test build prior to attempting to modify the code per above.

Hoping to conquer ignorance, and that this is the proper venue for doing so.  Many thanks in advance for assistance in this regard.

**Comment by schm03** [comment]
I'm a bit confused, incidentally, because I still see references to "Starscream" in the SocketIO files I've just downloaded, and I thought I read somewhere that such references have been deprecated.

I changed one of those to "Import SocketIO" but still get the same error.

?!?

**Comment by nuclearace** [comment]
If you're using the SPM you should have a Package.swift file for your project that looks something like this: https://github.com/nuclearace/socket.io-client-testing/blob/master/Package.swift

**Comment by schm03** [comment]
On googling SPM, I don't think I've run it correctly at all.   Is [this](https://gist.github.com/nathanborror/4ecb16bcb1ae0bd11e7eed043c6cd8bd) the way to do it?

**Comment by ratnesh-ahead** [comment]
installation version ,   pod 'Socket.IO-Client-Swift', '~> 13.3.0'



<img width="843" alt="Screenshot 2020-03-09 at 11 40 57 AM" src="https://user-images.githubusercontent.com/54057685/76187241-db77c800-61fa-11ea-8fe0-f96743968d12.png">
