### ISSUE TITLE
SPM error when trying to install SocketIO

### ISSUE THREAD

**Issue by schm03** [socketio/socket.io-client-swift#905]
Is [this](https://gist.github.com/nathanborror/4ecb16bcb1ae0bd11e7eed043c6cd8bd) the correct way to install SocketIO with SPM? 

When I run '**swift package fetch**', I encounter this:
```
error: argument 'targets' must precede argument 'dependencies'
    targets: [
```

I rearranged the code accordingly but encounter other errors.

**Comment by nuclearace** [comment]
You should read up on how to use the SPM. https://github.com/nuclearace/SwiftBot/blob/master/Package.swift is a pretty simple example of how to use it.

**Comment by schm03** [comment]
> You should read up on how to use the SPM.
> https://github.com/nuclearace/SwiftBot/blob/master/Package.swift is a
> pretty simple example of how to use it.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/socketio/socket.io-client-swift/issues/905#issuecomment-352025309


I appreciate your attempts to help your users, and I see that you must
have a pretty busy schedule doing so.

Unfortunately, I cannot find enough information to assist someone who is a
professional developer but has little or no XCode and no Swift experience.

It all gets down to time. I have about 5 hours into this and nothing to
show for it.  I don't know how the open source community can thrive doing
things this way, but it seems to.  It certainly weeds out people who have
other responsibilities and cannot make unlimited time investments in a
hurry.

Thank you again.

**Comment by maintainer** [comment]
For others who will land on this page after googling this error.
Check that you have correct swift version on the first line of your Package.swift
Like this:
`// swift-tools-version:4.0`

**Comment by shrawan2015** [comment]
For me: 
"**swift package tools-version --set-current**" command solved above issue. 
And then run "**swift package fetch**" to fetch data
