### ISSUE TITLE
Missing required modules: 'SSCZLib', 'SSCommonCrypto'

### ISSUE THREAD

**Issue by milotolboom** [socketio/socket.io-client-swift#906]
First of, I know this is a duplicate of [798](https://github.com/socketio/socket.io-client-swift/issues/798), but my issue is a bit different.

When I build the framework locally everything works as expected. I have commited the compiled framework to my branch and as soon as someone pulls this branch and tries to build the app they get the `Missing required modules: 'SSCZLib', 'SSCommonCrypto'` error.

I have tried building the framework with `--no-use-binaries`.
I'm running SocketIO v12.1.2 in a project with Swift 4.
Xcode and swift version is the same on both machines.

Any idea what could have caused this ?

**Comment by nuclearace** [comment]
Make sure you clear any related package manager's caches.

**Comment by milotolboom** [comment]
I have tried cleaning Carthage caches by using `rm -rf ~/Library/Caches/org.carthage.CarthageKit` and deleting the Carthage build folder.

I built the framework using `carthage update --no-use-binaries --platform iOS`.
The problem still occurs though. Changing to another package manager also isn't an option.

**Comment by milotolboom** [comment]
I have found that the project is unable to run if I remove the `Carthage/Checkouts/Starscream/zlib` folder. The Checkouts folder is not commited in my github repo and shouldn't be, the build folder is. I assume there is something wrong with Carthage building the frameworks.

**Comment by nuclearace** [comment]
Could it be related to https://github.com/Carthage/Carthage#nested-dependencies

>If the embedded framework in your project has dependencies to other frameworks you must link them to application target (even if application target does not have dependency to that frameworks and never uses them).
