### ISSUE TITLE
Cannot load underlying module for 'SocketIO'

### ISSUE THREAD

**Issue by WiseNN** [socketio/socket.io-client-swift#908]
I have installed the SocketIO swift  client using cocoaPods _(Swift 4)_. Everything seems to have been installed correctly, but when I try to `import SocketIO` I get an **Error: Cannot load underlying module for 'SocketIO'** .

<h4>Podfile:</h4>

```
use_frameworks!

target 'Push' do
    pod 'Socket.IO-Client-Swift', '~> 13.1.0'
end
```

Does anyone know what this could possibly be due to?

**Comment by nuclearace** [comment]
Have you tried cleaning your project and/or cocoapods?

**Comment by timofverberg** [comment]
I have the same problem after installing manually, and I have tried cleaning the project. Any ideas?

**Comment by nuclearace** [comment]
Installing manually isn't officially supported since there's some dependency stuff that has to be sorted out.

**Comment by dpakthakur** [comment]
This is an issue with cocoa pods I think. Do the following steps to run.
1. Close Xcode and Re-open. Then Shift + Cmd + K to clean. 
2. Product -> Build For -> Testing (Shift Cmd U)
3. You will still see the error, but you just have to hit the "Run" button on Top Left of Xcode until build automatically succeeds and the error goes.

**Comment by ThinhVu** [comment]
Change ios target version from 10.0 to 11.1 fixed this bug in my case.
