### ISSUE TITLE
SocketIOClient is disconnected when app enters background, reconnected when entering to foreground

### ISSUE THREAD

**Issue by sauvikatinnofied** [socketio/socket.io-client-swift#91]
Whenever the application is entering in the background, the socket connection goes missing. And when the application comes to foreground the connection is being established again. Is that the normal behavior of that socket client? Or I am making any mistakes?

**Comment by nuclearace** [comment]
iOS doesn't allow background execution of WebSockets as far as I know.

**Comment by sauvikatinnofied** [comment]
Thank you very much for you quick reply.
