### ISSUE TITLE
Delivered Status Notification

### ISSUE THREAD

**Issue by sandeepsipl** [socketio/socket.io-client-swift#910]
Hello, I m using this library in one of my chat application and it works awesome.
I'm facing issue with the delivered status. For example, If the application is running on the iPhone device, then it works perfectly. Now, if I sent a message from one device to another and at that time the application is not running on that device so notification came on that device but I didn't get any status.

**Comment by nuclearace** [comment]
Sounds like you'd want Apple Push Notifications.

**Comment by sandeepsipl** [comment]
Yes, As soon as the notification received on the iPhone, I want the status "Delivered" even if the application is not running in the background. I know its possible because Whatsapp doing it.

**Comment by faizantariq1** [comment]
@sandeepsipl  did you done that thing???...
