### ISSUE TITLE
Event Handler not calling

### ISSUE THREAD

**Issue by NikhilPrajapat1994** [socketio/socket.io-client-swift#912]
My trying to connect to localhost It is connects with local, but does not call the event handles.
Here is my code 

        let manager = SocketManager(socketURL: URL(string: "http://192.168.0.114:3000")!, config:       [.log(true), .compress])
        let socket = manager.defaultSocket
        socket.on(clientEvent: .connect) {data, ack in
           // app flow does not come here 
           print("socket connected")
        }
        
        socket.on("currentAmount") {data, ack in
          // app flow does not come here  
           guard let cur = data[0] as? Double else { return }
            socket.emitWithAck("canUpdate", cur).timingOut(after: 0) {data in
                socket.emit("update", ["amount": cur + 2.50])
            }
            
            ack.with("Got your currentAmount", "dude")
        }
        
        socket.connect()
/////////////////////////////////////////////////////////////////////////////////////////
My server say 
bd2-Mac-mini:SocketTesting bd2$ cd /Volumes/Workspace/\ SocketApp/SocketAppSingleview/srv-SocketChat 
bd2-Mac-mini:srv-SocketChat bd2$ node index.js
Listening on *:3000
a user connected
user disconnected

Please mention what is issue here

**Comment by nuclearace** [comment]
If you've just copied and pasted the example in the readme, it assumes you create a run loop. So would need to call `CFRunLoopRun` after calling connect.

**Comment by NikhilPrajapat1994** [comment]
thanks.
calling CFRunLoopRun() after 
 socket.connect() works for me

**Comment by evagnostic** [comment]
calling CFRunLoopRun() afterwards causes my socket to remain "connecting" status. Any idea?

**Comment by varkrishna** [comment]
but unable to **update** **UserInterface**, after adding  " **CFRunLoopRun()** " `import UIKit
import SocketIO

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        print("view loaded")
        self.connect()
       
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func connect(){
            let man = SocketManager(socketURL: URL(string: "http://localhost:3000")!)
            let cl : SocketIOClient = man.defaultSocket
            cl.on("hello") { (d, e) in
                print("socket connected hello \(d)")

                let btn = UIButton(frame: CGRect(x: 0, y: 0, width: 200, height: 200))
                btn.setTitle("send", for: .normal)
                btn.backgroundColor = UIColor.red
                print("btn created \(btn)")
                DispatchQueue.main.async {
                    self.view.addSubview(btn)
                }
            }
            cl.on("connect") { (d, e) in
                print("socket connected \(d)")
                cl.emit("chat message", with: ["from IOS"])
                //CFRunLoopStop(CFRunLoopGetCurrent())
            }
            cl.connect()
            CFRunLoopRun()
        return
    }

}
`
