### ISSUE TITLE
When I add a dependency with Carthage, I get the following error:

### ISSUE THREAD

**Issue by ZvOlCuOk2009** [socketio/socket.io-client-swift#916]
*** Building scheme "Starscream" in Starscream.xcodeproj
Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -project /Users/admin/Test\ Tiras/Carthage/Checkouts/Starscream/Starscream.xcodeproj -scheme Starscream -configuration Release -derivedDataPath /Users/admin/Library/Caches/org.carthage.CarthageKit/DerivedData/8.3.2_8E2002/Starscream/3.0.3 -sdk watchos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/2r/nmnc_7gx06j5b51q854nm48h0000gn/T/Starscream SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/admin/Test Tiras/Carthage/Checkouts/Starscream)

Somebody faced the similar? How can you solve this problem?

**Comment by nuclearace** [comment]
Do you have the latest Xcode installed?

**Comment by ZvOlCuOk2009** [comment]
No, I have version 8.3.2

**Comment by nuclearace** [comment]
That's why. The latest version of the client requires the newest xcode.
