### ISSUE TITLE
got a crash when server reject connect

### ISSUE THREAD

**Issue by zhangqippp** [socketio/socket.io-client-swift#92]
hi, I'm new to swift and socket.io, I got a crash when the server reject my connect. 
I connect like this:
        self.socket.connectWithParams(["name": "username", "password": "userpassword"]);
and then got a crash like this:
![d2856b19-fda2-41eb-9968-c7d768d1732d](https://cloud.githubusercontent.com/assets/2979857/7999337/1b2bede4-0b7c-11e5-8624-73d4a4e21a64.png)
![c9230d70-8e5a-49ef-96b1-187da630791f](https://cloud.githubusercontent.com/assets/2979857/7999338/227c8c84-0b7c-11e5-8182-94757ad66a96.png)
It seems like there is something wrong with the response format, and It couldn't be parsed to json.

**Comment by nuclearace** [comment]
That's an old version, try updating.

**Comment by zhangqippp** [comment]
@nuclearace ,Yes, I got a version of 1.3.1 with cocoa pods, don't notice that.
