### ISSUE TITLE
Apple Watch constant `Connecting` status

### ISSUE THREAD

**Issue by RichAppz** [socketio/socket.io-client-swift#922]
I am currently updating my Apple Watch app with Socket.io and I am having a few difficulties - one being the fact that I can't get Xcode to run and debug on my Apple Watch the normal way!

So on the simulator EVERY thing is working as expected, the socket is working beautifully. As soon as I run on an actual Apple Watch the socket does nothing. I have managed to attach to the process and get a break point in and basically the `SocketIOStatus` is always coming back as `connecting` and it constantly hits with the same thing...

`shared.socket?.on(clientEvent: .statusChange, callback: { (data, ack) in
         shared.delegate?.statusUpdate(status: shared.socket?.status) 
})`

Could you advise me if this issue has come up before? And a solution!

**Comment by RichAppz** [comment]
Can anyone help with this? If I can’t get it working will have to roll back

**Comment by nuclearace** [comment]
Have you tried debugging where it should be getting the connected status?

**Comment by RichAppz** [comment]
I really wish I could just debug properly! Don't understand what you are asking - can you elaborate

**Comment by nuclearace** [comment]
Well the first thing would be to check the logs. If it’s the default namespace the socket should go to connected once the engine is connected.

**Comment by RichAppz** [comment]
Like I said debugging on the device is almost impossible due to poor tools - Everything is working beautifully on the simulator which is what I can debug to my hearts content!

**Comment by nuclearace** [comment]
Well, I don't have an apple watch, so I'm not able to debug this myself.

**Comment by RichAppz** [comment]
I have a new MacBook to set up over the coming days, maybe I can try debugging again once it is set up - maybe it's this laptop. Let you know asap
