### ISSUE TITLE
Cant connect to socket with namespace in version 13.1.0

### ISSUE THREAD

**Issue by vsergeev1988** [socketio/socket.io-client-swift#923]
Hi there! I am trying to connect the websocket on the backend using the latest  13.1.0. Here is my source code:
```swift
    let manager: SocketManager

    required init() {
        self.manager = SocketManager(socketURL: Consts.Api.apiUrl,
                config: [SocketIOClientOption.path("/api/v1/communication/socket.io"),
                         SocketIOClientOption.log(true),
                         SocketIOClientOption.extraHeaders(
                                 ["Authorization": "<auth token>"]
                         )])
    }

    func connect() {
        let namespaceSocket = self.manager.socket(forNamespace: "/testRoom1")
        self.addHandlers(namespaceSocket)
        namespaceSocket.connect()
    }
```

Unfortunately, I receive an error from the backend:
> Error decoding socket IO packet '0/testRoom1': Expected ',' to end namespace declaration

Maybe "," is missed in -[SocketManager connectSocket:] where connection command is creating, just like "," is adding after namespace in [SocketPacket createPacketString] method? 
Same for -[SocketManager disconnectSocket:].

Or maybe I have an error in my code? 

Thank you!

**Comment by nuclearace** [comment]
What server version are you using?

**Comment by vsergeev1988** [comment]
On the backend we have this: https://github.com/playframework/play-socket.io

We made some tests and was trying to connect to our backend using official JS client (https://github.com/socketio/socket.io-client) and it works ok with this server. The command, received on the backend from this JS client was "0/testRoom1," - with the comma after namespace.

**Comment by nuclearace** [comment]
Hm, I guess you're right. I'll update the namespace joining code. Although the JS server seems to work without this trailing ,.

**Comment by nuclearace** [comment]
@vsergeev1988 If you could see if the latest development branch fixes it, that'd be helpful.

**Comment by vsergeev1988** [comment]
@nuclearace I have updated to the latest development brunch and it works ok now on connect to namespace, but I still have the same error on disconnect.

**Comment by nuclearace** [comment]
Derp, should be fixed now.

**Comment by vsergeev1988** [comment]
@nuclearace works great now, thank you!
