### ISSUE TITLE
socket remind connecting

### ISSUE THREAD

**Issue by nadia-am** [socketio/socket.io-client-swift#928]
```python
let manager = SocketManager(socketURL: URL(string: "https://test.t/" )!, config: [.log(true), .compress])
let socket = manager.defaultSocket
socket.on(clientEvent: .connect) {data, ack in
            print("socket connected")
        }
socket.connect()
while true {
            print(socket.status)
        }
```
and the result is
```python
connecting
connecting
connecting
connecting
.
.
.
```
this is my code
i stuck in connecting. can anyone help me?

**Comment by nuclearace** [comment]
Because the library uses Grand Central Dispatch for threading, if you aren't doing this inside of an App, you will need to manually start the main runloop by calling `CFRunLoopRun()`. You should know however that once this is called, nothing after it will be executed. So your while true loop will need to be redone using some other way.

**Comment by nadia-am** [comment]
I am running this code inside of my app.

**Comment by nuclearace** [comment]
In any case, you'll need to redo your `while true`. Since that's going to block the handleQueue. If you want to listen for a status change. There's a `.statusChange` client event you can listen for.

**Comment by nadia-am** [comment]
i remove while do i want to listen for connect event but it doesnt happen.
```python
socket.on(clientEvent: .connect) {data, ack in
            print("socket connected")
        }
```

**Comment by nuclearace** [comment]
What do the logs say?

**Comment by nuclearace** [comment]
Also make sure that the manager is not being released by ARC. That would be one cause for connect not happening.

**Comment by nadia-am** [comment]
LOG SocketIOClient{/}: Adding handler for event: connect
LOG SocketIOClient{/}: Adding handler for event: statusChange
LOG SocketIOClient{/}: Adding handler for event: connect
LOG SocketIOClient{/}: Handling event: statusChange with data: [connecting]
LOG SocketIOClient{/}: Joining namespace /
LOG SocketManager: Tried connecting socket when engine isn't open. Connecting
LOG SocketManager: Manager is being released
LOG SocketEngine: Starting engine. Server: https://my ip address/
LOG SocketEngine: Handshaking
LOG SocketEnginePolling: Doing polling GET https://my ip address/socket.io/?transport=polling&b64=1
LOG SocketEnginePolling: Got polling response
LOG SocketEnginePolling: Got poll message: 97:0{"sid":"ZuYDeUge8vQnd1i5AADy","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
LOG SocketEngine: Got message: 0{"sid":"ZuYDeUge8vQnd1i5AADy","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}
LOG SocketEngine: Writing poll:  has data: false
LOG SocketEnginePolling: Sending poll:  as type: 2
LOG SocketEnginePolling: Created POST string: 1:2
LOG SocketEnginePolling: POSTing
LOG SocketEngine: Engine is being released

**Comment by nuclearace** [comment]
`LOG SocketManager: Manager is being released`

That's why. See the [FAQ](https://nuclearace.github.io/Socket.IO-Client-Swift/faq.html)

**Comment by nadia-am** [comment]
thanks alot . it works.

**Comment by DGP13** [comment]
same issue here 
how to solve this issue

**Comment by hardikdarji** [comment]
same issue here
.connect event not called...
how to solve this issue
Please help

below is my code...

//GLOBLE VAR
let manager = SocketManager(socketURL: URL(string: "ws://10.0.3.178/")!,
                            config: [.log(true)])

//SHARED CLASS FOR SOCKET 
class SocketIOManager {
    func addHandlers(){
        manager.defaultSocket.on(clientEvent: .connect) {data, ack in
            print("\nSocket connected\n")
        }
        manager.defaultSocket.on(clientEvent: .disconnect) {data, ack in
            print("\nSocket disconnected\n")
        }
        
        manager.defaultSocket.on(clientEvent: .error) {data, ack in
            print("\nSocket error\n")
        }
        
        manager.defaultSocket.on(clientEvent: .statusChange) {data, ack in
            print("\nStatus change: \(data)\n")
        }
        
    }
    
    func establishConnection() {
        manager.defaultSocket.connect()
        CFRunLoopRun()

    }
    
    func closeConnection() {
        manager.defaultSocket.disconnect()
    }
}

//VIEW CONTROLLER WHER ESTABLISH CONNECTION
class ViewController: UIViewController
{
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        let manager = SocketIOManager()
        manager.addHandlers()
        manager.establishConnection()
    }
}
//CONSOL LOG

2019-07-05 13:06:10.694949+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: connect
2019-07-05 13:06:10.695392+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: disconnect
2019-07-05 13:06:10.695454+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: error
2019-07-05 13:06:10.695487+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: statusChange
2019-07-05 13:06:10.696508+0530 realtime[1139:477284] LOG SocketIOClient{/}: Handling event: statusChange with data: [connecting]

Status change: [connecting]

2019-07-05 13:06:10.696881+0530 realtime[1139:477284] LOG SocketManager: **Tried connecting socket when engine isn't open. Connecting**
2019-07-05 13:06:10.696974+0530 realtime[1139:477284] LOG SocketManager: Adding engine
2019-07-05 13:06:10.701376+0530 realtime[1139:477354] LOG SocketEngine: Starting engine. Server: ws://10.0.3.178/
2019-07-05 13:06:10.701429+0530 realtime[1139:477354] LOG SocketEngine: Handshaking
2019-07-05 13:06:10.702843+0530 realtime[1139:477354] LOG SocketEnginePolling: Doing polling GET http://10.0.3.178/socket.io/?transport=polling&b64=1
2019-07-05 13:06:13.549678+0530 realtime[1139:477355] LOG SocketEnginePolling: Got polling response
2019-07-05 13:06:13.557455+0530 realtime[1139:477355] LOG SocketEnginePolling: Got poll message:

**Comment by idevChandra6** [comment]
> same issue here .connect event not called... how to solve this issue Please help
> 
> below is my code...
> 
> //GLOBLE VAR let manager = SocketManager(socketURL: URL(string: "ws://10.0.3.178/")!, config: [.log(true)])
> 
> //SHARED CLASS FOR SOCKET class SocketIOManager { func addHandlers(){ manager.defaultSocket.on(clientEvent: .connect) {data, ack in print("\nSocket connected\n") } manager.defaultSocket.on(clientEvent: .disconnect) {data, ack in print("\nSocket disconnected\n") }
> 
> ```
>     manager.defaultSocket.on(clientEvent: .error) {data, ack in
>         print("\nSocket error\n")
>     }
>     
>     manager.defaultSocket.on(clientEvent: .statusChange) {data, ack in
>         print("\nStatus change: \(data)\n")
>     }
>     
> }
> 
> func establishConnection() {
>     manager.defaultSocket.connect()
>     CFRunLoopRun()
> 
> }
> 
> func closeConnection() {
>     manager.defaultSocket.disconnect()
> }
> ```
> 
> }
> 
> //VIEW CONTROLLER WHER ESTABLISH CONNECTION class ViewController: UIViewController { override func viewDidLoad() { super.viewDidLoad()
> 
> ```
>     let manager = SocketIOManager()
>     manager.addHandlers()
>     manager.establishConnection()
> }
> ```
> 
> } //CONSOL LOG
> 
> 2019-07-05 13:06:10.694949+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: connect 2019-07-05 13:06:10.695392+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: disconnect 2019-07-05 13:06:10.695454+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: error 2019-07-05 13:06:10.695487+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: statusChange 2019-07-05 13:06:10.696508+0530 realtime[1139:477284] LOG SocketIOClient{/}: Handling event: statusChange with data: [connecting]
> 
> Status change: [connecting]
> 
> 2019-07-05 13:06:10.696881+0530 realtime[1139:477284] LOG SocketManager: **Tried connecting socket when engine isn't open. Connecting** 2019-07-05 13:06:10.696974+0530 realtime[1139:477284] LOG SocketManager: Adding engine 2019-07-05 13:06:10.701376+0530 realtime[1139:477354] LOG SocketEngine: Starting engine. Server: ws://10.0.3.178/ 2019-07-05 13:06:10.701429+0530 realtime[1139:477354] LOG SocketEngine: Handshaking 2019-07-05 13:06:10.702843+0530 realtime[1139:477354] LOG SocketEnginePolling: Doing polling GET http://10.0.3.178/socket.io/?transport=polling&b64=1 2019-07-05 13:06:13.549678+0530 realtime[1139:477355] LOG SocketEnginePolling: Got polling response 2019-07-05 13:06:13.557455+0530 realtime[1139:477355] LOG SocketEnginePolling: Got poll message:

Were you able to resolve it? I am getting same error.

**Comment by czernas** [comment]
> same issue here how to solve this issue

**Comment by czernas** [comment]
> same issue here .connect event not called... how to solve this issue Please help
> 
> below is my code...
> 
> //GLOBLE VAR let manager = SocketManager(socketURL: URL(string: "ws://10.0.3.178/")!, config: [.log(true)])
> 
> //SHARED CLASS FOR SOCKET class SocketIOManager { func addHandlers(){ manager.defaultSocket.on(clientEvent: .connect) {data, ack in print("\nSocket connected\n") } manager.defaultSocket.on(clientEvent: .disconnect) {data, ack in print("\nSocket disconnected\n") }
> 
> ```
>     manager.defaultSocket.on(clientEvent: .error) {data, ack in
>         print("\nSocket error\n")
>     }
>     
>     manager.defaultSocket.on(clientEvent: .statusChange) {data, ack in
>         print("\nStatus change: \(data)\n")
>     }
>     
> }
> 
> func establishConnection() {
>     manager.defaultSocket.connect()
>     CFRunLoopRun()
> 
> }
> 
> func closeConnection() {
>     manager.defaultSocket.disconnect()
> }
> ```
> 
> }
> 
> //VIEW CONTROLLER WHER ESTABLISH CONNECTION class ViewController: UIViewController { override func viewDidLoad() { super.viewDidLoad()
> 
> ```
>     let manager = SocketIOManager()
>     manager.addHandlers()
>     manager.establishConnection()
> }
> ```
> 
> } //CONSOL LOG
> 
> 2019-07-05 13:06:10.694949+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: connect 2019-07-05 13:06:10.695392+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: disconnect 2019-07-05 13:06:10.695454+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: error 2019-07-05 13:06:10.695487+0530 realtime[1139:477284] LOG SocketIOClient{/}: Adding handler for event: statusChange 2019-07-05 13:06:10.696508+0530 realtime[1139:477284] LOG SocketIOClient{/}: Handling event: statusChange with data: [connecting]
> 
> Status change: [connecting]
> 
> 2019-07-05 13:06:10.696881+0530 realtime[1139:477284] LOG SocketManager: **Tried connecting socket when engine isn't open. Connecting** 2019-07-05 13:06:10.696974+0530 realtime[1139:477284] LOG SocketManager: Adding engine 2019-07-05 13:06:10.701376+0530 realtime[1139:477354] LOG SocketEngine: Starting engine. Server: ws://10.0.3.178/ 2019-07-05 13:06:10.701429+0530 realtime[1139:477354] LOG SocketEngine: Handshaking 2019-07-05 13:06:10.702843+0530 realtime[1139:477354] LOG SocketEnginePolling: Doing polling GET http://10.0.3.178/socket.io/?transport=polling&b64=1 2019-07-05 13:06:13.549678+0530 realtime[1139:477355] LOG SocketEnginePolling: Got polling response 2019-07-05 13:06:13.557455+0530 realtime[1139:477355] LOG SocketEnginePolling: Got poll message:

I have exactly the same issue. Global variables etc. but still not working on iOS (but works on Android 🤦‍♂️).
