### ISSUE TITLE
WebSocket never deinit'd if close is not called

### ISSUE THREAD

**Issue by cabal95** [socketio/socket.io-client-swift#93]
I noticed that if I never call the close method on the grandparent SocketIOClient object then the WebSocket sticks around forever, still talking to the server (pings and pongs I am assuming).

Specifically, if I create a SocketIOClient, connect it and then assign nil to the variable I had assigned it to, I can see in logging that SocketIOClient deinits and SocketEngine deinits, but the WebSocket stays around.

Adding this to the SocketEngine deinit method seems to solve the problem, but I don't know if it might cause others.

        engine?.close(fast: true)

It is pretty complex code to grasp quickly with all the async blocks so I am not sure what is the core reason the WebSocket doesn't deinit, there must be some retain going on somewhere that I can't find.

Also, the reason I am not wanting to call disconnect is the client object is shared among multiple other objects and view controllers. I could implement my own refCount system for it, but that seems like the wrong solution.

**Comment by nuclearace** [comment]
Oh I know why. It's because NSURLSession is holding a strong retain to the engine
