### ISSUE TITLE
Received data has the wrong encoding (not always)

### ISSUE THREAD

**Issue by mouchegmouradian** [socketio/socket.io-client-swift#931]
I'm working on a chat using socket.io and I have a strange bug. The received data seems to be decoded too many times and "non-english" characters don't display properly.
If I do an utf8 encode on that wrongly encoded string I get the original string, thus what I said above about the string being decode too many times.

We are using socket.io on Android and there it works properly and the server doesn't do any encoding/decoding so I'm guessing it is coming from this client.

Any ideas ?

**Comment by nuclearace** [comment]
@mouchegmouradian What version of the server are using?

**Comment by mouchegmouradian** [comment]
@nuclearace We are using 1.5.1

**Comment by mouchegmouradian** [comment]
@nuclearace Any ideas ?

(Sorry to bother you but I really need to sort this out)

**Comment by nuclearace** [comment]
The latest version of the client only supports socket.io 2.0. You’ll need to use the socket.io 1.0 branch.

**Comment by kim68666343** [comment]
How can you sure that's the matter about encoding? @mouchegmouradian

**Comment by nuclearace** [comment]
Socket.io 2.0 introduces a breaking Unicode change which would explain the bad encoding.

**Comment by mouchegmouradian** [comment]
@nuclearace Okay that would explain it :)
It seems to work with 1.0-swift4 branch 
thanks
