### ISSUE TITLE
I cannot receive data back from server

### ISSUE THREAD

**Issue by PengsreangSrun** [socketio/socket.io-client-swift#94]
This is my code for receiving data
 if (!socket) {
        socket = [[SocketIOClient alloc] initWithSocketURL:@"localhost:3000" options:nil];
    }
    [socket on:@"connect" callback:^(NSArray* data, void (^ack)(NSArray*)) {
        NSLog(@"socket connected");
        [_reconnectTimer invalidate];
        _reconnectTimer = NULL;
        
        if(blockConnect)
        {
            blockConnect();
        }
        [socket on:_requestring callback:^(NSArray* data, void (^ack)(NSArray*)) {
            NSLog(@"socket connected2");
        }];
    }];
    [socket connect];
-(void)socketIODidSendRequestName:(NSString *)requestName
                             data:(id)data
{
    _requestring = requestName;
    NSArray *arr = [[NSArray alloc] initWithObjects:data, nil];
    [socket emit:requestName withItems:arr];
}

**Comment by nuclearace** [comment]
I don't see any emitWithAck. Check the front readme for what that would look like in Objective-C.

**Comment by nuclearace** [comment]
Also, what do you mean receive data? Are events not working, or are you wanting an ack?

**Comment by nuclearace** [comment]
If you want an ack, I don't see any emitWithAck. Check the front readme for what that would look like in Objective-C.
