### ISSUE TITLE
Invalid HTTP upgrade

### ISSUE THREAD

**Issue by maksTheAwesome** [socketio/socket.io-client-swift#943]
Hello. I've recently updated to a new version `Socket.IO-Client-Swift 13.1.0` form 11.1.3 and noticed that similar code on the old version successfully connects to the socket server but the new updated code below is stuck in a reconnecting loop with the following response in logs:

> 2018-02-02 16:21:55.929935-0500 TheApp[243:5822] LOG SocketManager: Trying to reconnect
> 2018-02-02 16:21:55.930611-0500 TheApp[243:5822] LOG SocketIOClient{/}: Handling event: reconnectAttempt with data: [-1]
> 2018-02-02 16:21:55.931597-0500 TheApp[243:6102] LOG SocketEngine: Starting engine. Server: ws://fw-socket-prod.herokuapp.com
> 2018-02-02 16:21:55.931887-0500 TheApp[243:6102] LOG SocketEngine: Handshaking
> 2018-02-02 16:21:57.049287-0500 TheApp[243:6081] ERROR SocketEngine: The operation couldn’t be completed. (Starscream.WSError error 1.)
> 2018-02-02 16:21:57.049741-0500 TheApp[243:5822] ERROR SocketManager: The operation couldn’t be completed. (Starscream.WSError error 1.)
> 2018-02-02 16:21:57.050055-0500 TheApp[243:5822] LOG SocketIOClient{/}: Handling event: error with data: ["The operation couldn’t be completed. (Starscream.WSError error 1.)"]
> 2018-02-02 16:21:59.110895-0500 TheApp[243:5822] LOG SocketManager: Trying to reconnect
> 2018-02-02 16:21:59.111181-0500 TheApp[243:5822] LOG SocketIOClient{/}: Handling event: reconnectAttempt with data: [-2]

After a short research, I've found that the issue `Starscream.WSError error 1` means: "Invalid HTTP upgrade"

The logs on server-side show:

> Feb 02 12:39:50 fw-rt-node heroku/router:  at=info method=GET path="/socket.io/?transport=websocket" host=fw-rt-node.herokuapp.com request_id=b7e41180-5213-49ee-b317-0ec0d9a697e9 fwd="65.209.36.34" dyno=web.2 connect=2ms service=29052ms status=101 bytes=285 protocol=http 

**The code:**

```
let ssl = SSLSecurity(usePublicKeys: true)
            let specs: SocketIOClientConfiguration = [.path("/theApp"),
                                                      .forceWebsockets(true),
                                                      .reconnectAttempts(3),
                                                      .reconnectWait(3),
                                                      .security(ssl),
                                                      .log(true)]
            socketManager = SocketManager(socketURL: url, config: specs)

            socket?.on(clientEvent: .connect) {data, emitter in
                // handle connected
            }

            socket?.on(clientEvent: .disconnect, callback: { (data, emitter) in
                //handle diconnect
            })

            socket?.onAny({ (event) in
               //handle event
            })

            socket?.connect()
```

**Comment by nuclearace** [comment]
Perhaps some sort of TLS issue?

**Comment by maksTheAwesome** [comment]
I wish I know. I've pulled back socket.io-client to the latest 12.(something) version and it works fine for me now.

**Comment by pablogeek** [comment]
@maksTheAwesome Have you figured it out? I'm having the same problem

**Comment by maksTheAwesome** [comment]
@pablogeek Actually I did not. I rolled socket.io-client back to 12.1.3 and the problem was gone. So I never returned to the issue.

**Comment by xRena** [comment]
@maksTheAwesome can you share your code how you implement client now?

**Comment by jp1987** [comment]
Having the exact same issue, rolling back to 12.1.3. fixed it for me. I noticed that Starscream went from 3.0.5 to 2.1.1, so problem is probably on that side.

**Comment by XiaoXing44** [comment]
Hi, @maksTheAwesome
I am facing on same issue. Now the socket version I am using is v13.2.1
So should I use v12.1.3? then this problem is solved?

**Comment by Ramzi-Alqrainy** [comment]
@nuclearace any luck here? we are stuck here.

**Comment by thesayyn** [comment]
I have this issue as well. I guess the main issue here is when the server does not handle the path for plain HTTP requests for example 'example.com/socket.io', the server returns a 4xx status code. In most cases, the server does not handle plain requests(only upgrade requests.) for socket only paths which are widely known behavior. 

Result: we can't connect to a socket server that we can connect with js client. 

I can work on this @nuclearace

**Comment by thesayyn** [comment]
Confirmed the issue. The main issue here is similar to mine.

**Comment by NachoSoto** [comment]
I'm seeing the same issue.

**Comment by passol1988** [comment]
@nuclearace I am facing on same issue
