### ISSUE TITLE
Socket.IO crahes sometimes

### ISSUE THREAD

**Issue by aly-irshad** [socketio/socket.io-client-swift#949]
Hello, my app is crashing sometimes for the same event handler. I have all the listener UUID and removed on disconnect event.

`if let messageCenter = messageCenter{
         for udid in messageCenter.listenerUUID{
           if let udid = udid{
               messageCenter.socket?.off(id: udid)
           }
    }
    messageCenter.listenerUUID.removeAll()
}`

![screen shot 2018-02-09 at 3 37 46 pm](https://user-images.githubusercontent.com/20099371/36022994-f15bb500-0db0-11e8-8d39-3038e2c700c7.png)

**Comment by nuclearace** [comment]
Make sure all interaction with the client is on the handleQueue. The client is not thread/queue safe.

**Comment by nuclearace** [comment]
Yes, you should be using one queue to interact with the socket.

**Comment by aly-irshad** [comment]
Ok Thanks, I will update my code accordingly.
