### ISSUE TITLE
Cannot compile for iOS 9

### ISSUE THREAD

**Issue by bogdand84** [socketio/socket.io-client-swift#95]
Using Xcode 7 beta version for iOS 9 beta release, the socket.io-client-swift is not compiling with or without automatic conversion to latest swift version.

**Comment by nuclearace** [comment]
I'm working on it. Swift 2 breaks the regex library I'm using pretty good

**Comment by nuclearace** [comment]
You can try using the swift-2 branch, but beware, some things changed, and I'm still testing things.

**Comment by bogdand84** [comment]
I'll give it a shot.
Thanks!

**Comment by nuclearace** [comment]
Also if you notice any edge cases where it breaks let me know.

**Comment by nuclearace** [comment]
Changes will be tracked in the #96
