### ISSUE TITLE
How to destroy a socket permanently

### ISSUE THREAD

**Issue by evagnostic** [socketio/socket.io-client-swift#951]
I want to destroy a socket when the user logs out. However, `socket.disconnect()` does not kill the socket. Currently, it keeps receiving socket updates after disconnecting. I also do want the socket to be able to reconnect when the network is down. Can anyone tell me how to destroy the socket object please?

Update: I found that in order to permanently disconnect the socket, we need to do the following:

```
manager.setConfigs([.reconnects(false)])
socket.removeAllHandlers()
socket.disconnect()
```

However, I noticed the `deinit` function for both `SocketManager` and `SocketIOClient` are never called. How can I destroy those two objects?

**Comment by nuclearace** [comment]
You shouldn't need to call `removeAllHandlers` unless you've strong captured a `self` or captured the manager or socket. But to cause a socket to disconnect you need to call [`removeSocket`](https://nuclearace.github.io/Socket.IO-Client-Swift/Classes/SocketManager.html#/c:@M@SocketIO@objc(cs)SocketManager(im)removeSocket:). But if you want to deinit all of them at once you have to set the manager to nil.

**Comment by evagnostic** [comment]
Thanks! This code below worked for me. 

```
manager.setConfigs([.reconnects(false)])
socket.disconnect()
manager.removeSocket(socket)
manager = nil
socket = nil
```
