### ISSUE TITLE
SocketIOClient doesn't have function (socketURL: URL)

### ISSUE THREAD

**Issue by sullymanIO** [socketio/socket.io-client-swift#956]
<img width="833" alt="screen shot 2018-02-20 at 6 57 17 pm" src="https://user-images.githubusercontent.com/33635352/36427804-f87d89d6-166f-11e8-99b7-52eaa178d879.png">

Hi, im newbie at swift and im trying to set a variable for socket client but SocketIOClient only has this one member function that is attached in this issue

**Comment by nuclearace** [comment]
Please check out the [docs](https://nuclearace.github.io/Socket.IO-Client-Swift/index.html) and the README. They show how to properly create sockets.
