### ISSUE TITLE
how to send cookie  my socket server?

### ISSUE THREAD

**Issue by Bharath2r** [socketio/socket.io-client-swift#957]
I am sending like this,
but it's showing error -> (Type of expression is ambiguous without more context)
 var socket = SocketIOClient(socketURL: URL(string: Constants.socketApi)!,ClientOption:[.log(true),.forcePolling(true),.cookies([cookie])])

**Comment by nuclearace** [comment]
Make sure you're using the API correctly for the version you have. That's just a Swift error.
