### ISSUE TITLE
Question - Updating extraHeaders when the socket was already creted

### ISSUE THREAD

**Issue by BrenoVin** [socketio/socket.io-client-swift#958]
I have an app which the auth process is based in token and refresh_token. I must pass the token updated in socket .extraHeaders, and I do this in the socket init. but I must update the .extraHeaders when the token is renewed without creating another socket instance. 

My doubt is when and how do this.

tks.

**Comment by nuclearace** [comment]
Well, unless you're forcing polling, you would have to reconnect to send the other headers. I'll have to double check if the client can set extraHeaders while it's still connected (I wouldn't count on it)

**Comment by BrenoVin** [comment]
I try some thing and this work for me

- I create a manager with my .extraHeaders

`manager = SocketManager(socketURL: url, config: [.extraHeaders(["Authorization":"token"])])
  socket = manager.defaultSocket
`
- when I my token is refreshed I call the `reconnect()`

- and in the `.reconnectAttempt` socket event I set the token again

`self.manager.setConfigs([.extraHeaders(["Authorization": "new_token"])])`

**Comment by RupeshSappani01** [comment]
> 

> 

> 

> 

> aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa``

**Comment by bhanudhimanHF** [comment]
I fixed this by the following code:-

Step 1:- Create manager > manager = SocketManager(socketURL: URL(string: BaseURL)!, config: [.log(true), .compress, .extraHeaders(["token": getStringValue(key: UserDefaultKeys.loginToken)]), .reconnects(true), .forceWebsockets(true),  .forcePolling(true), .forceNew(true)])

Step 2:- socket = manager.defaultSocket

Step3:- manager.reconnect()
        manager.setConfigs([.extraHeaders(accessToken), .reconnects(true), .forcePolling(true)])
        socket.connect()
        
Thanks
