### ISSUE TITLE
high energy impact on iPhone when idle

### ISSUE THREAD

**Issue by murad1981** [socketio/socket.io-client-swift#959]
when i use the following config:

```
 let config : [String: Any] = ["log": true,
                                  "compress": true,
                                  "forcePolling": true]
    var socketManager = SocketManager(socketURL: url, config: config)
    var socket: SocketIOClient = socketManager.defaultSocket
```

 I noticed that there was big a energy impact on the iPhone device even if it's idle (without emitting commands) as appears in the below screenshot. does anybody have an idea on what's going on here ?

<img width="994" alt="screen shot 2018-02-27 at 9 15 51 am" src="https://user-images.githubusercontent.com/1199045/36713626-a9f20b36-1b9f-11e8-8070-a86741a9db88.png">

**Comment by nuclearace** [comment]
I haven't done any energy impact on this lib on iPhone in a very long time. But in theory it shouldn't be that energy hungry unless it's emitting or if the server has set a crazy ping rate.

**Comment by murad1981** [comment]
it turned about to be something else other than SocketIO, we're using WebRTC along with SocketIO and it's casing this issue when capturing video frames.
