### ISSUE TITLE
socket.io error

### ISSUE THREAD

**Issue by TeemoY2017** [socketio/socket.io-client-swift#960]
i use oc
pod 'Socket.IO-Client-Swift', '~> 9.0.0'
and serve change HTTPS
link error is “The certificate for this server is invalid. You might be connecting to a server that is pretending to be \U201cwww.XXXXX.com\U201d which could put your confidential information at risk.”
- - - -
i try to "[[SocketIOClient alloc]initWithSocketURL:url config:@{@"log": @NO,@"forcePolling":@YES}];"change " [[SocketIOClient alloc] initWithSocketURL:url config:@{@"log": @NO,@"forcePolling":@YES,@"security":@{@"SSLSecurity":@{@"validatedDN":@NO}}}]"
But it doesn't seem to work.
what should i do...

**Comment by nuclearace** [comment]
You'll probably need to use [SSLSecurity](https://nuclearace.github.io/Socket.IO-Client-Swift/Classes/SSLSecurity.html).
