### ISSUE TITLE
Swift Dictionary converted to JSON with wrong syntax

### ISSUE THREAD

**Issue by kvaDrug** [socketio/socket.io-client-swift#962]
I'm trying to send an event with parameters like this:
`socket.emit("register",  ["id": 6, "type": "mentor"])`
But the server (node.js) gets `["id": 6, "type": "mentor"]` string instead of `{"id": 6, "type": "mentor"}`. Looks like SocketIO using Swift dictionary format instead of JSON.

**Comment by nuclearace** [comment]
What server and client versions are you using? This should be impossible since everything is put through a JSON serializer.

**Comment by nuclearace** [comment]
And there are tests for emits.

**Comment by kvaDrug** [comment]
The server is `nginx/1.10.3 (Ubuntu)`  and client is 13.1.1.

**Comment by nuclearace** [comment]
Is this a socket.io server?

**Comment by kvaDrug** [comment]
It uses socket.io v2.0.4.

**Comment by nuclearace** [comment]
I'm not sure how that's possible then. How are you seeing this invalid json?

**Comment by kvaDrug** [comment]
Backend programmer told me that he received `["id": 6, "type": "mentor"]` string. I was able to _fix_ this problem by using `Data` generated by `JSONSerialization` instead of raw `Dictionary`. But I will have more free time I will try to investigate this problem deeper.

**Comment by nuclearace** [comment]
How are you calling `emit`?

**Comment by nuclearace** [comment]
[This](https://github.com/socketio/socket.io-client-swift/blob/master/Tests/TestSocketIO/SocketBasicPacketTest.swift#L48) is one of the tests that makes sure the packet format isn't getting broken. (I admit I need to redo these tests to not compare strings)
