### ISSUE TITLE
Socket event still listen while set controller to nil

### ISSUE THREAD

**Issue by sonysum** [socketio/socket.io-client-swift#964]
I listen a event in many controller and then set some controller to nil but it still receive event from socket in swift?

**Comment by nuclearace** [comment]
You might want to call `removeAllHandlers` before you set some controller to nil. You might have a strong reference that's causing a cycle.

**Comment by sonysum** [comment]
If i call 'removeAllHandlers' its will remove for all other controller i still want want to listen 
how can i do?

**Comment by nuclearace** [comment]
@sonysum I don't understand the issue then. Can you explain a bit more?
