### ISSUE TITLE
reason: 'Invalid type in JSON write (RTCSessionDescription)

### ISSUE THREAD

**Issue by bchen3** [socketio/socket.io-client-swift#966]
i'm using socketIo-client-swift as signaling mechanism for webrtc. After localdescription is set and ready to send an offer over socket.io,  xcode terminated for the following reason: "reason: 'Invalid type in JSON write (RTCSessionDescription)". 

i'm using: xcode 9.0 / objective-c / webrtc ios static library / socketio-client-swift.

anyone know why???

**Comment by nuclearace** [comment]
Sounds like you're trying to send a unsupported type through the client.
