### ISSUE TITLE
String encoding/decoding

### ISSUE THREAD

**Issue by ltsuchiya** [socketio/socket.io-client-swift#967]
Our project was recently migrated to Swift4 but now emojis and apostrophes come through as garbled text. I noticed that this issue was brought up last year with no resolution. Have there been any updates since then?

**Comment by nuclearace** [comment]
What version of socket.io are you using on the server?

**Comment by nuclearace** [comment]
The latest version of the client requires socket.io 2.0, which has a breaking unicode change. So things like emoji would probably be garbled in the client if your server is socket.io 1.0. Use the socket1.0 swift 4 branch if you need socket 1.0 support.

**Comment by ltsuchiya** [comment]
We are using 1.48 on our server and swift socket io 12.1.3

I have found that our data is coming in as iso-latin-1, not sure if this is related to socket io or a problem on our end. 

We have resolved it by encoding the received string back as iso-latin then decoding it into a utf8 string on the app side.
