### ISSUE TITLE
What’s the best way to test apps using this framework?

### ISSUE THREAD

**Issue by davbeck** [socketio/socket.io-client-swift#968]
I see some methods labeled “test” that are used in the unit tests for this project, but I’m having a hard time to see how apps that use socket.io should write unit tests.

**Comment by nuclearace** [comment]
Good question, and one I don't really have a good answer to. Swift doesn't have a very good testing ecosystem IMO. It lacks good mocking support built into the core, so it's hard to test how methods/functions are called. So your best bet is doing something like [this](https://github.com/socketio/socket.io-client-swift/blob/master/Tests/TestSocketIO/SocketMangerTest.swift#L159) where you subclass something and make sure public methods are being called like you expect.
