### ISSUE TITLE
Crash on dispatch_async in SocketEngine with v2.3.4

### ISSUE THREAD

**Issue by sovannarithsok** [socketio/socket.io-client-swift#97]
I have created a simple project that migrate Swift class in ObjC project to connect with a specific IP and port and I have noticed that when I initial the SocketIOClient  local variable it doesn't fire (Doesn't work ) but for global variable it crashed at the method as below:

      dispatch_async(dispatch_get_main_queue()) {[weak self] in
            if let this = self {
                this.pingTimer = NSTimer.scheduledTimerWithTimeInterval(NSTimeInterval(this.pingInterval!),
                    target: this,
                    selector: Selector("sendPing"), userInfo: nil, repeats: true)
            }
     }

**Comment by nuclearace** [comment]
What's the crash?

**Comment by nuclearace** [comment]
@sovannarithsok Do you have a stack trace?

**Comment by sovannarithsok** [comment]
Doesn't any trace, it stuck.

**Comment by nuclearace** [comment]
What do you mean doesn't have a stack trace? If it crashed I would think it would have some sort of stack trace? How easy is it to reproduce?

**Comment by sovannarithsok** [comment]
@nuclearace 

![screen shot 2015-06-23 at 3 57 35 pm](https://cloud.githubusercontent.com/assets/5999202/8302568/8bde7248-19c1-11e5-93d1-f71600d86a75.png)

**Comment by nuclearace** [comment]
Hm, I noticed in your OP that you said you're first creating it with local scope, it should be a property of a class. But as for the crash I'm not really sure. The second screenshot looks like a crash in one of the libraries I'm using.

**Comment by nuclearace** [comment]
Also the first screenshot leads me to believe that perhaps the client is being released but the engine still thinks it exists. But I don't think that should be happening (anymore)

**Comment by sovannarithsok** [comment]
The message with Option Log:
 
      SocketClient: Adding handler for event: connect
      SocketClient: Adding handler for event: disconnect
      SocketClient: Adding engine
      SocketEngine: Starting engine
      SocketEngine: Handshaking
      SocketEngine: Got message: 0{"sid":"OIbtmRBl-ojfZgqpAARR","upgrades":  [],"pingInterval":500,"pingTimeout":60000}

**Comment by nuclearace** [comment]
Okay, I'm seeing a weird crash when the pingInterval is set to something that small.

**Comment by nuclearace** [comment]
I see what's going on
