### ISSUE TITLE
Cannot successfully connect to Django channels sockets

### ISSUE THREAD

**Issue by acandelaria1** [socketio/socket.io-client-swift#970]
django server is logging this error when attempting to connect the socket:
`Not Found: /socket.io/`
Here is my iOS client code: 
`import Foundation
import SocketIO

final class TFTISocketManager {
    
    
    var manager: SocketManager 
    var socket: SocketIOClient
    private static var sharedSocketManager: TFTISocketManager = {
        let socketManager = TFTISocketManager()
        return socketManager
    }()
    
    private init(){
        self.manager = SocketManager(socketURL: URL(string: "ws://tfti-backend.herokuapp.com/")!, config: [.log(true), .compress])
        self.socket = manager.defaultSocket
        socket.on(clientEvent: .connect) {data, ack in
            print("socket connected")
        }
        
        socket.connect()
    }
    
    class func shared() -> TFTISocketManager {
        return sharedSocketManager
    }
    
    //Connects to user specific socket that will be only used to communicate changes in that users user data or
    // if for example the user recieves a new invite
    func connectToUserSocket(currentUser: TFTIUser){
        print("DO THINGS")
    }
}
`

Here is iOS client side logging:
`LOG SocketEnginePolling: Doing polling GET http://tfti-backend.herokuapp.com:8000/socket.io/?transport=polling&b64=1
ERROR SocketEnginePolling: Could not connect to the server.
`

**Comment by nuclearace** [comment]
I think you're looking for a WebSocket library. You should checkout [Starscream](https://github.com/daltoniam/Starscream) in that case. This library is for interfacing with servers that implement the socket.io protocol.
