### ISSUE TITLE
Support for emitting binary data (or documentation for it)

### ISSUE THREAD

**Issue by danikenan** [socketio/socket.io-client-swift#98]
We are trying to emit an event with binary data, an array of numbers.

It all starts by us getting an UnsafeMutablePointer<Float> buffer and its size in a callback from the mic. 

We would like to pass as is or converted to a swift array of ints.

Is there a way to do that now?

10x

**Comment by nuclearace** [comment]
You'll need to convert it into either NSData, or an array of ints before you can send it.

**Comment by nuclearace** [comment]
As for converting, I'm not exactly sure. I've never worked with that specific use case.
