### ISSUE TITLE
Can't to connect 

### ISSUE THREAD

**Issue by tangenttw** [socketio/socket.io-client-swift#980]
Hi 
I am kind of newbie on swift development . I want to use socketIO for build chat app I can Install but I can't to use it from your example code . I try to use my URL but it's not work and No "socket connected" printed . Can you tell me to the way I can use it please 
[SocketIO.zip](https://github.com/socketio/socket.io-client-swift/files/1822576/SocketIO.zip)

**Comment by nuclearace** [comment]
@tangenttw It looks you're declaring your manager to be a local variable. This is a mistake because of ARC. As soon as the function returns the manager will be released, and everything falls down after that. The manager should be a property of something.
