### ISSUE TITLE
Socket IO not connecting to get data look at the code

### ISSUE THREAD

**Issue by deepakyadeedya** [socketio/socket.io-client-swift#981]
`import SocketIO

enum Socket: String{
    
    case serverURL = "http://ios-test.us-east-1.elasticbeanstalk.com/"
    case namespace = "/random"
    case eventName = "capture"
}

let manager = SocketManager(socketURL: URL(string:(Socket.serverURL.rawValue))!)
var socket = SocketIOClient(manager: manager as SocketManagerSpec, nsp: (Socket.namespace.rawValue))

class ViewController: UIViewController {
    

    override func viewDidLoad() {
        
        super.viewDidLoad()        
         //establishConnection()
         connect(){ (socket) -> () in self.nextNumberFromServer() }
        nextNumberFromServer()
        CallUserNotifications()
    }
    

    
    public func connect(withHandler handler: ((SocketIOClient) -> ())?) -> Void{
       
        if(socket.status == .connected){
            handler?(socket)
            return
        }
        
        //connect to the server
        socket.connect()
    }
    
    func nextNumberFromServer(){
        
        socket.on(Socket.eventName.rawValue) {data, ack in
           // let number = data[0] as? NSNumber
            if let number = data[0] as? NSNumber {
            print(number)
            }
        }
        socket.connect()
    }

    func closeConnection() {
        socket.disconnect()
    }
    `

**Comment by nuclearace** [comment]
@deepakyadeedya Don't create a `SocketIOClient` yourself. Use the `socket(forNamespace:)` method on the manager.
