### ISSUE TITLE
With "forceWebsockets", you can't grab a bag with Charles, but you can grab it with "forcePolling".

### ISSUE THREAD

**Issue by PXLZHM** [socketio/socket.io-client-swift#986]
My project is oc,Xcode version 9.2,Socket.IO-Client-Swift is latest version
With "forceWebsockets", you can't grab a bag with Charles, but you can grab it with "forcePolling".

**Comment by nuclearace** [comment]
What?

**Comment by TomZid** [comment]
same issue with me
