### ISSUE TITLE
Very weird bug with socket, when starting up socket.

### ISSUE THREAD

**Issue by shams-ahmed** [socketio/socket.io-client-swift#987]
When I start the socket connecting I get this weird bug. for `reason` parameter is empty and nil. I'm not sure what the issue is here.

<img width="1528" alt="screen shot 2018-03-27 at 10 27 54" src="https://user-images.githubusercontent.com/2887472/37958921-b1e32ac6-31a9-11e8-9dfa-b6b596953df1.png">

Using the latest version of socket-io:
- Socket.IO-Client-Swift (13.1.2):
    - Starscream (~> 3.0.2)

**Comment by nuclearace** [comment]
Dude what. Is everything being released here? Because the statement `reason parameter is empty and nil` should not be true unless something very very wrong is going on.

**Comment by shams-ahmed** [comment]
Closing ticket, can't reproduce all the time. 

thanks
