### ISSUE TITLE
reconnectAttempts config ignored

### ISSUE THREAD

**Issue by yevreinov** [socketio/socket.io-client-swift#989]
I'm working with version 13.1.1
Initializing manager like this:

`let socketManager = SocketManager(socketURL: URL(string: connectString)!, config: [
            .log(true),
            .compress,
            .reconnects(true),
            .reconnectWait(3),
            .reconnectAttempts(10),
            .forceNew(true)
        ])`

reconnectAttempts is ignored, it is always -1 (keeps reconnecting always).

I believe this is caused by setConfigs method in SocketManager.swift - it is missing reconnectAttempts case completely.

**Comment by nuclearace** [comment]
🤦‍♂️
