### ISSUE TITLE
cannot emit to server

### ISSUE THREAD

**Issue by PengsreangSrun** [socketio/socket.io-client-swift#99]
I am having a problem related to emit data to server. I am trying this but at server side does not receive my emit event.
This is my emit code!
 NSArray *arr = [[NSArray alloc] initWithObjects:data, nil];
    [socket emit:requestName withItems:arr];
    if (socket.connected) {
        [socket on:requestName callback:^(NSArray* data, void(^ack)(NSArray*)){
            NSLog(@"doasod");
        }];
        
    }

**Comment by nuclearace** [comment]
Something must not be configured right, are you sure that your socket is connected when you're sending?

**Comment by PengsreangSrun** [comment]
I am definitely sure for connection!

**Comment by PengsreangSrun** [comment]
Can you show me how to emit and on event because i have followed what you show me on readme but it is still useless. Anyways, when I connect, i need to add option like this:
options:@{@"reconnects":@true,@"reconnectAttempts":@5,@"reconnectWait":@5,@"forcePolling":@false,@"forceWebsockets":@true,@"nsp":@"/"}
and then it starts connecting but i still have problems with emit and on event. Please help!!!

**Comment by nuclearace** [comment]
The simplest would be

```objective-c
[socket emit:@"test" withItems:@[@1]];
```

Also be sure this isn't a case where the socket is going out of scope (ie you actually declare the socket inside a function and not as a property). Also, I would setup all your event handlers before you call connect.

**Comment by PengsreangSrun** [comment]
@nuclearace  This is my emit code:
 NSArray *arr = [[NSArray alloc] initWithObjects:data, nil];
        [socket emit:requestName withItems:arr];
before emitting, whether we need to convert to array or not because my data is id. However, when i do not convert data to array, error will happen.

**Comment by nuclearace** [comment]
Emit takes an array of items. This is because Objective-C doesn't have Swift variadics.

**Comment by PengsreangSrun** [comment]
Thank you for your telling me but I still have doubts with parameter that we emit. Can we emit data with only array and dictionary? How's about string? I cannot emit JSon string!

**Comment by nuclearace** [comment]
Whatever you need to emit you have to put inside an NSArray and then pass it to emit. And you can include NSArray, NSDictionary (JSON), NSString, and literals. But don't expect to send a json string and the server to handle it as json. If you have to send JSON you need to send it as a NSDictionary.

**Comment by PengsreangSrun** [comment]
Thank you very much for helping me. From now I emit data with a NSDictionary!
