### ISSUE TITLE
Session ID unknown

### ISSUE THREAD

**Issue by xRena** [socketio/socket.io-client-swift#997]
I have a connection `connect with data: ["/"] `  and I got poll message `Got poll message: 96:0{"sid":"Ed-rNGNbJTsiDC8zAAA8","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}2:40` and after a while I get an error : `error with data: ["Session ID unknown"]`.  How can I resolve this problem? I
My configuration:
`  
 let config: SocketIOClientConfiguration =  [.connectParams(["token=" : token]), .log(true), .reconnectAttempts(3), .reconnectWait(3)]
                
let socket = SocketIOClient(socketURL: URL(string: self.urlPath)!, config: config)`

And I also have a problem with force websockets. After set `true` I can't connect. `error with data: ["Invalid HTTP upgrade"]`

I tried to implement the solutions of other users, but it didn't help.

**Comment by nuclearace** [comment]
What version of the client and server? Are you doing any emits outside of a .connect handler, or when it's not known if the socket is connect?

**Comment by xRena** [comment]
On iOS app 12.1.3 on server 2.1.0. No, I try to have stable connection only for now. I have prepared funcions to emit but now I don't use them

**Comment by nuclearace** [comment]
And is this server running locally? I cannot reproduce on the latest version (which is the only supported version).

**Comment by nuclearace** [comment]
Tracking in #996.
