### ISSUE TITLE
duplicate SSLSecurity.swift when I manual Import iOS Swift to Objective C

### ISSUE THREAD

**Issue by marcuschoong** [socketio/socket.io-client-swift#999]
I know manual import the swift project doesn't support but somehow my condition are require to perform manual import for the project. 

I face a duplicated file on the following directory:
SocketIO/Util/SSLSecurity.swift
SocketIO/Starscream/Sources/SSLSecurity.swift

Can you let me know which file should use from above?

**Comment by nuclearace** [comment]
You should just be able to rename one of the files. The actual file names don't matter. It's the types that matter. You might have to change the name of one of them.

**Comment by MQdoyourbest** [comment]
I don't know how to use it on objective-c language.

**Comment by marcuschoong** [comment]
the problem solve after i rename one of the file, however it appear another error that the "import Starscream" not found in the ScoketIOClientOption.swift eventhought the folder was place on the project.

<img width="826" alt="screen shot 2018-04-12 at 3 25 23 pm" src="https://user-images.githubusercontent.com/26889594/38662177-0dad741a-3e66-11e8-93d9-0d905bcf5140.png">

**Comment by nuclearace** [comment]
@marcuschoong as the Starscream files are in the same target as the socket.io ones, you can remove the import.

**Comment by Vinaykumar-dev** [comment]
@nuclearrace,
Can I publish the app to AppStore after renaming the SSLSecurity file name? Does socketio library permits to change the file names and code inside that file?

**Comment by Vinaykumar-dev** [comment]
Please rename the duplicate SSLSecurity.swift file name in the library, it is there in both SocketIO and Startcream folders. Its is a biggest blocker for my project or suggest any other workaround. I am installing using cocoa pods (not manual import) still I am facing the issue "duplicate files.."
